### ISSUE TITLE
ListFile performance degrades linearly

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1006]
Reported by a user. As the number of commits and files grows `ListFile`s runtime seems to increase linearly. This is somewhat expected since the size of the result that it's returning is growing linearly as well. However the user reported requests getting up to 35 minutes in total latency which is obviously not acceptable for a system like ours.

I think the main thing we can do to fix this is look at turning `ListFile` into a streaming call so that it doesn't need to compute the entire query to return the first result. This should also decrease the peak memory needed by the server. This will help with #1004. My hunch is that the 35 minute query took so long because the db went into swap. This would also prevent that from happening.

**Comment by derekchiang** [comment]
Note that the user was using "recursive" ListFile, meaning that it had to traverse the entire FS hierarchy.  It's unclear how the performance characteristics of non-recursive ListFile are like.

**Comment by derekchiang** [comment]
The direction we are going right now is to implement a `ListFileLite` which only returns filenames but not other metadata such as sizes, which are a lot harder to compute due to internal data structure reasons.

**Comment by derekchiang** [comment]
Fixed by #1011
