### ISSUE TITLE
Display commit durations

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1012]
Right now in `pachctl list-commit` and `pachctl inspect-commit` we display the `started` and `finished` times of commits.  However, if a commit is more than 24 hours old, then they might both look like `2 days ago` and `2 days ago`, making it hard to determine how long a commit actually took.

**Comment by jdoliner** [comment]
It'd probably be better if we just did `started` time and `duration` and left out `finished`. Since you can more or less figure out when it finished from the first 2 numbers. And that would have much nicer resolution for cases like this.
