### ISSUE TITLE
Can't deploy a particular version of Pachyderm from source

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1017]
One would expect that given a Pachyderm repo, you could deploy a particular version of Pachyderm as follows (using v1.2.2 as an example):
1. `git checkout v1.2.2`
2. `make launch`

However, this doesn't work, because for some reason `pachctl deploy` (used by `make launch`) spits out a manifest that uses a version of `pachd` image that does not exist on dockerhub.  In my case it's `pachyderm/pachd:1.2.2-f1701dc4fad9baf08a5ecd4563b9b5144284e1ed`

**Comment by JoeyZwicker** [comment]
`pachctl deploy` checks your version of pachctl and then tries to get that image from DH, right?

You'd need to have the version of pachctl that matches the version you want to deploy. Alternatively, would it make sense to have pachctl deploy check to see if the container is on DH (or just know that that's only true for point release versions) and if it's not build pachd and use that?

**Comment by jdoliner** [comment]
`pachctl` doesn't have the ability to build a copy of the `pachd` image, since it doesn't store a copy of our repo in it.

**Comment by sjezewski** [comment]
This is what `make dev-launch` does, no?

This is stale, so closing.
