### ISSUE TITLE
pachyderm_2.10.7_linux_amd64.tar.gz unzips to pachyderm_2.10.6_linux_amd64 (not sure if this is by design)

### ISSUE THREAD

**Issue by git-withit** [pachyderm/pachyderm#10211]
The tar file obtained from here: https://github.com/pachyderm/pachyderm/releases/download/v2.10.7/pachyderm_2.10.7_linux_amd64.tar.gz unzips to pachyderm_2.10.6_linux_amd64. I believe this may be an error. I am attempting to assist someone with their Dockerfile and I am not sure if, for the long-term, we should use:

ARG PACHYDERM_BINS=pachyderm_2.10.6_linux_amd64.tar.gz
COPY ${PACHYDERM_BINS} /
RUN tar -xzf /${PACHYDERM_BINS} --strip-components=1 pachyderm_2.10.7_linux_amd64/pachd -C /

or 

ARG PACHYDERM_BINS=pachyderm_2.10.6_linux_amd64.tar.gz
COPY ${PACHYDERM_BINS} /
RUN tar -xzf /${PACHYDERM_BINS} --strip-components=1 pachyderm_2.10.6_linux_amd64/pachd -C /

**Comment by jrockway** [comment]
I don't think it's by design.  We're taking a look.

**Comment by jrockway** [comment]
Are you sure that ARG PACHYDERM_BINS is set correctly?  I downloaded both:

```
$ wget https://github.com/pachyderm/pachyderm/releases/download/v2.10.7/pachctl_2.10.7_linux_amd64.tar.gz
$ wget https://github.com/pachyderm/pachyderm/releases/download/v2.10.7/pachctl_2.10.7_linux_arm64.tar.gz
```
and extracted them:
```
$ tar tzvf pachctl_2.10.7_linux_amd64.tar.gz
-rwxr-xr-x circleci/circleci 120725348 2024-07-17 12:07 pachctl_2.10.7_linux_amd64/pachctl
$ tar tzvf pachctl_2.10.7_linux_arm64.tar.gz
-rwxr-xr-x circleci/circleci 117381058 2024-07-17 12:08 pachctl_2.10.7_linux_arm64/pachctl
```
This looks correct to me.  Additionally:

```
$ tar xzvf pachctl_2.10.7_linux_amd64.tar.gz
pachctl_2.10.7_linux_amd64/pachctl
$ pachctl_2.10.7_linux_amd64/pachctl version --client-only
2.10.7
$ tar xzvf pachctl_2.10.7_linux_arm64.tar.gz
pachctl_2.10.7_linux_arm64/pachctl
$ pachctl_2.10.7_linux_arm64/pachctl version --client-only
2.10.7
```
Basically, at least for the linux binaries, the version number seems consistent to me between the URL, directory name, and the version built into the binary.

**Comment by jrockway** [comment]
I downloaded all 4 of the pachctl and pachd binaries, and the version number in the URL matches the version number of the directory.  Did you maybe typo `ARG PACHYDERM_BINS`?  In your example that still says 2.10.6.

**Comment by git-withit** [comment]
Yeah, my bad. The copy pasted code is not what we were running. It was the 2.10.7. See the attached images. Even downloading the file and untarring it locally shows 2.10.6 inside the 2.10.7 tar file.
<img width="841" alt="Screenshot 2024-07-18 at 1 07 15 PM" src="https://github.com/user-attachments/assets/062c5eb5-c0b6-4549-bf2e-d1c18a17ed6b">

<img width="841" alt="Screenshot 2024-07-18 at 1 07 15 PM" src="https://github.com/user-attachments/assets/171275ff-9135-4130-b7a8-1d429ba22795">

**Comment by jrockway** [comment]
Interesting.  I see everything matching:

```
$ tar tzvf pachyderm_2.10.7_linux_amd64.tar.gz
-rw-rw-r-- circleci/circleci 104 2024-07-17 10:25 pachyderm_2.10.7_linux_amd64/dex-assets/BUILD.bazel
...
-rw-rw-r-- circleci/circleci  6005 2024-07-17 10:25 pachyderm_2.10.7_linux_amd64/dex-assets/themes/pachyderm/styles.css
-rwxrwxr-x circleci/circleci 151517041 2024-07-17 10:27 pachyderm_2.10.7_linux_amd64/pachd
-rwxrwxr-x circleci/circleci 120273512 2024-07-17 10:28 pachyderm_2.10.7_linux_amd64/worker
-rwxrwxr-x circleci/circleci   2150175 2024-07-17 10:28 pachyderm_2.10.7_linux_amd64/worker_init
```

Even your command that fails works for me:

```
tar -xvzf pachyderm_2.10.7_linux_amd64.tar.gz --strip-components=1 pachyderm_2.10.7_linux_amd64/pachd
pachyderm_2.10.7_linux_amd64/pachd
```

Is it possible some wires got crossed on your end during the file download, and a 2.10.6 tarball got renamed to 2.10.7 accidentally?

I have the following files:
```
$ sha256sum pachyderm_2.10.6_linux_amd64.tar.gz pachyderm_2.10.7_linux_amd64.tar.gz
23659ccab2e16ecef578f7313d456404a92eb5bd85196a48d7daf9a87d53c769  pachyderm_2.10.6_linux_amd64.tar.gz
b512e256773e15be3955ff87b56cb7aae170334f87fa6627b691b5e8af4817f6  pachyderm_2.10.7_linux_amd64.tar.gz
```
(if you're on Mac OS, `shasum -256` instead of `sha256sum` to check).

**Comment by git-withit** [comment]
Yeah, my bad. I was trying to pull the 2.10.7 file from the 2.10.6 url.....sorry about this!

**Comment by jrockway** [comment]
No problem at all!  Good luck on your Pachyderm adventure!
