### ISSUE TITLE
Update AWS instructions

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1025]
http://docs.pachyderm.io/en/latest/development/deploying_on_the_cloud.html#amazon-web-services-aws

We need to update our '3 line hack' to the k8s start script.

Basically just added that first line to `kubernetes/cluster/common.sh`:

```
  KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
```

If you leave the other 2 lines, you get 'unbound variable' errors and the script exits before completing (but thinks that it has worked ... and so errs silently). Specifically, it thinks that it has spun up the k8s service (and it may well have), but it didn't update the config / credentials for kubectl, so I have no way of knowing if it has, since I cannot connect.

**Comment by JoeyZwicker** [comment]
Since Matt and I wrote and debugged this the first time, I'll try to take a crack at it today if @msteffen has some time to help

**Comment by JoeyZwicker** [comment]
Ran through the guide and turns out we dont need to add anything to get this to work. They seem to ahve fixed the k8s start script. Updating our guide to not include those 3 lines and closing until someone runs into a problem.
