### ISSUE TITLE
Update AWS s3 commands to truly use region

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1026]
I've followed the instructions in the guide to deploy on amazon / s3.

If I do a `putfile` w the `-c` option, it seems to hang.

If I run the fruit stand demo, I get the error message:

```
invalid header field value "BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region\n\tstatus code: 301, request id: 72FB9C1A6CBA2CE4"
```

When doing the `put-file`. Looking at the UI, it does seem that the bucket isn't set. This is true despite the fact that we pass the region info in the creation script. Observe:

```
$aws s3api create-bucket --bucket omgtestbucketregion --region us-west-2
$aws s3api get-bucket-location --bucket omgtestbucketregion
{
    "LocationConstraint": null
}
```

Whereas a bucket we've previously created does have the region set:

```
$aws s3api get-bucket-location --bucket pachyderm-data
{
    "LocationConstraint": "us-west-1"
}
```

So my best guess at this point is that we're not specifying the region correctly

**Comment by sjezewski** [comment]
Looks like we have to set region and a constraint:

```
$aws s3api create-bucket --bucket fwqgahds --region us-west-2 --create-bucket-configuration LocationConstraint=us-west-2
{
    "Location": "http://fwqgahds.s3.amazonaws.com/"
}
$aws s3api get-bucket-location --bucket fwqgahds
{
    "LocationConstraint": "us-west-2"
}
```

**Comment by sjezewski** [comment]
@msteffen and @JoeyZwicker I know you looked at AWS deployment after I ran through it. Have we made these updates to the docs?

**Comment by JoeyZwicker** [comment]
These docs have been updated to include a location constraint.
