### ISSUE TITLE
Long-term security credentials in AWS

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1035]
From #users on Slack. 

On aws deployments, is there any way to use long term security credentials for the deployment? Right now, the sessions you get from `aws sts get-session-token` last a maximum of 36 hours, so it seems kind of cumbersome to be constantly rotating security credentials.

**Comment by JonathanFraser** [comment]
you can simply create an aws account with an access key/ secret pair and leave the token string blank.

**Comment by jdoliner** [comment]
This seems like a solid solution to this problem. Can't think of what we'd do to make it better.
Closing.
