### ISSUE TITLE
Pachctl doc links are broken

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1048]
http://docs.pachyderm.io/en/latest/pachctl/pachctl.html

The links to each command are broken

**Comment by JoeyZwicker** [comment]
pachctl.md is autogenerated. All the links need ../pachctl/ in front of them. I think this needs to be added to `make assets` or whatever we use to autogenerate the pachctl docs. I could obviously change the links in the md file, but that doesn't solve the problem and I probably shouldn't be the one to futz with the `make` file.

**Comment by sjezewski** [comment]
Its more than just that prefix. The links right now point to `somecommand.md` when they should point to `somecommand.html`

There is a problem with how we're rendering markdown on RTD.

This was working in the past because we had a manually updated `doc/pachctl/pachctl.rst` file that mimicked the auto-generated one.

[I've opened an issue on RTD](https://github.com/rtfd/readthedocs.org/issues/2520) so we'll see what they say.  Hopefully I'm just doing something silly. If not, we'll probably just run with the manual curation of the rst file.

**Comment by JoeyZwicker** [comment]
adding an rst file for now. I'll touch up the rst to include 1-liner cmd summaries.
