### ISSUE TITLE
Rely on go to parallelize test suites

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1050]
We're not running tests in the go way.

We have a single `make task` which does some setup, and runs a bunch of different test suites separately. Most of these could be parallelized. This gets especially true after addressing #1049

**Comment by jdoliner** [comment]
These tests already run in parellel. They could maybe be made a little more parallel by running all the test suites together but I doubt it would have much effect given that almost all of our tests are in a single package.
