### ISSUE TITLE
Make non-deterministic tests deterministic by injecting state through etcd

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1052]
One example of this that I found is [TestPipelineTransientFailure](https://github.com/pachyderm/pachyderm/blob/master/src/server/pachyderm_test.go#L522) which fails a random number of times and then succeeds. To control this test a little better, I want to write a utility that can be used anywhere a job needs a PRNG, but stores the PRNG state in RethinkDB, so that every time we run the test, the jobs we start see the same sequence of random numbers, and the test always takes the same amount of time.

**Comment by sjezewski** [comment]
Hmm but wouldn't we need those PRNG to be persistent across databases? (Or keystores, if we replace 'rethink' w 'etcd')

This would be helpful to make CI a bit less jittery, but only if it persists across data stores I think.

**Comment by sjezewski** [comment]
Updating title 'rethink' -> 'etcd'

**Comment by sjezewski** [comment]
We made integration tests run in sequence, which has made them relatively more stable. Since this seems to ameliorate the issue, and this issue is stale, I'm closing it.
