### ISSUE TITLE
Make migration part of pachd / init job

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1055]
Right now migration is implemented as little go scripts in the `migration` directory. This has the downside that they need to be compiled separately and the user needs to get them talking to rethinkdb before they can do their job. Instead we should just integrate that logic into our pachd image. That way we can make migrations happen as part of the init job or do them live from pachd while it's running.

**Comment by sjezewski** [comment]
@jdoliner 's new migration PR does this
