### ISSUE TITLE
The "/pfs/state" folder, replacing "/pfs/prev"

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1057]
Discussed with @jdoliner and @msteffen.  The idea is somewhat inspired by [Millwheel](http://research.google.com/pubs/pub41378.html).

## Problems

The fundamental observation here is that some pipelines are "stateful".  For instance, imagine a pipeline that sums up numbers.  When a new number comes in, the pipeline would add the new number to the original sum to obtain the new sum.  Here, the sum is the state.

Previously, the way we handle state is by exposing the output of a job's parent.  In the example above, a job can see the sum output by its parent.  This approach however has two big problems:

* It assumes that `output == state`, which may not be true for some stateful pipelines.  For instance, imagine a pipeline that computes the average of numbers.  The state here will be 1) the sum of all the numbers, and 2) the number of numbers.  The output will be the average.  Under the current scheme, you will have to put the state in your output, even though you might only want to output the averages.
* By coupling output with state, the current scheme also puts a severe limit on the size of output, since a job needs to download the output of the parent job before it can be run.  This is less of a problem right now since we expose parent output via a FUSE volume, but with #1041 we are removing FUSE for performance reasons.

## Solution

A user uses a `stateful` flag in the pipeline spec to specify whether a pipeline is "stateful".  If a pipeline is stateful, its jobs will have access to a `/pfs/state` folder.  Here is how this folder works:

* If a job does not have a parent (e.g. the first job), then the folder is empty.  The job can then add state by writing to this folder.
* Whatever content that's written into this folder will be exposed to the next job.  Again, the next job can modify this state folder as well.

The content of the state folder is persisted into a `pipeline_name_state` repo as parentless commits.  For instance, a stateful pipeline `foo` will use the `foo_state` repo to store its state.  The state folder from each job will correspond to a distinct, parentless commit.

Using the example of computing averages, a job could write two files to the state folder: `/pfs/state/sum` and `/pfs/state/n`, which corresponds to the current sum and number of numbers.

### Optimization

An important optimization that we can deploy with this change is that, now that the user explicitly tells us whether a pipeline is stateful, we can aggressively parallelize non-stateful pipelines.  Specifically, currently all pipelines are made such that a job won't start until it's parent job has completed.  But if a pipeline is not stateful, meaning that it does not depend on parental output to run correctly, we can spawn jobs without waiting for parents to complete.

**Comment by JonathanFraser** [comment]
I don't think the additional overhead of a seperate view pipeline was that big a cross to bear.  Moreover, with state you start to introduce some ambiguity because, PREV was read only but now STATE needs to be Read-Write. It begs the question if I write to state and then read from it what do I see. Additionally, do I read the state written in a separate job and if I do there is a race condition. Where we previously had a fold operation we now have this strange fold_and_map operation.

Re the optimization: you can do that with prev just as much as you can do it with state, nothing changes.

**Comment by JonathanFraser** [comment]
There is another improvement that can be done if there is no state. The commits following a failed commits do not need to be cancelled. This allows the opportunity to fix data that was previously incorrect.

**Comment by jdoliner** [comment]
Subsumed by #1584
