### ISSUE TITLE
Put job-shim (the binary) into the pachd image, and remove the job-shim image

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1058]
This was brought up by @jdoliner.  Basically, we have seen quite a few users run into issues where the version of job-shim doesn't match the version of pachd.  The solution is that instead of having two images, we only have one and we put both the `pachd` binary and the `job-shim` binary into it.

**Comment by jdoliner** [comment]
I was actually thinking that we would just have a single monolithic binary with `job-shim` and `pachd` functionality built into it. That'd probably make for a smaller image since those 2 binaries share a huge amount of code.

**Comment by JonathanFraser** [comment]
This especially important because it creates deployment issues with upgrades. Not only do you need to update the pachd node but all of your deployed pipeline images as well. If your deployment code tracks changes to images naively, this mean re-running all the pipelines, not ideal.

**Comment by derekchiang** [comment]
@JonathanFraser starting from 1.2.4 (see #1075), user images no longer need to inherit from the `job-shim` image, so you shouldn't need to update your pipeline images anymore!

**Comment by sjezewski** [comment]
I assume this issue is still relevant if we `s/job\-shim/worker/g`

Is that right? @jdoliner @derekchiang

**Comment by jdoliner** [comment]
Yup, still makes sense. I'd say not incredibly impactful but might be a nice to have.

**Comment by sjezewski** [comment]
nice to have + stale = closed
