### ISSUE TITLE
Make it easy to update an image for a pipeline

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1062]
I've run into this myself, and its surprising.

Basically, I want to update my pipeline with new code. I expect users will want to do this quite often. However, if I've updated the image on docker hub, but its under the same name, e.g. `sjezewski/dowager`, the updated version won't be downloaded.

Maybe we can specify a 'development' pipeline w a flag or field in the manifest? Then we could use the `Always` pull policy?

**Comment by jdoliner** [comment]
We have `--push-images` for this. It was added in #962. As you yourself explained in the pull request:

> "As a user ... having a private registry that pachctl updates when I create/update a pipeline allows me to seamlessly update my pipelines when my code is under active development"
