### ISSUE TITLE
YAML support for manifest files

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1079]
Users have requested this, specifically so that they can include comments in their manifests.

Comments can be handy to annotate changes / versions / etc and encourages people to be version controlling their manifest files, which is a convention that we want to support.

**Comment by derekchiang** [comment]
Not sure if there's a YAML-protobuf converter, but we can go YAML-JSON-protobuf using this library: https://github.com/ghodss/yaml

**Comment by sjezewski** [comment]
Yea, that library looks like the right approach. [He has a great blog post about why](http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/)

**Comment by sjezewski** [comment]
To support YAML we need to:

Unmarshal :

- for `pachctl create-job`
- for `pachctl create-pipeline`

Marshal : 

- for `pachctl deploy ...`

However, since we're using backing these structures with protobuf objects, and [since the stdlib json encoder/decoder don't work w protobuf objects](https://godoc.org/github.com/golang/protobuf/jsonpb) I don't think that library will work as is. I don't think it would be too hard to extend that library to use the jsonpb codec instead of the stdlibrary one, but I'm not sure

I opened an issue to ask: https://github.com/ghodss/yaml/issues/17

I also took a look at how k8s handles json and yaml. They use the ghodss library, but there is a lot of abstraction. I'm mostly leaving these breadcrumbs here for myself for future reference:

- [Their create command](https://github.com/kubernetes/kubernetes/blob/da56dc1e33922752a59e592536e01122388317ff/pkg/kubectl/cmd/create.go) uses [a builder abstraction](https://github.com/kubernetes/kubernetes/blob/da56dc1e33922752a59e592536e01122388317ff/pkg/kubectl/resource/builder.go) which seems to handle json or yaml ... not sure about this step
- [They have some helpers for yaml decoders](https://github.com/kubernetes/kubernetes/blob/b359034817685a8d25bb51bae765308d9d200da0/pkg/util/yaml/decoder.go) ... but those use the above library which means they use the stdlib json decoder

So I don't think their approach is compatible with ours.

( Maybe this is why k8s has those crazy types e.g. `IntOrStr` https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/util/intstr/intstr_test.go)

This wasn't the slam dunk we thought it would be. So we'll wait to hear back on the jsonpb support, or hear more requests for this feature.

**Comment by kav** [comment]
Adding a +1 for support here, shame it isn't a simple fix. It also looks like a no dice from Sam. I'll likely workaround with a pre-parse in the meantime

**Comment by JoeyZwicker** [comment]
We continue to see requests for this. I may make sense to evaluate non "simple fix" options -- plus its been a year and there may be other libraries that can do this out of the box. Marking for 1.7 so it gets discussed as part of the planning.

**Comment by homme** [comment]
I currently use [y2j](https://github.com/wildducktheories/y2j) to convert our annotated YAML to a JSON spec for running in Pachyderm.  It works fine but it would be great to see native support in a similar vein to `kubectl`.

**Comment by msteffen** [comment]
Fixed by https://github.com/pachyderm/pachyderm/pull/4078
