### ISSUE TITLE
Denormalization of metadata

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1086]
Discussed with @jdoliner.

Currently, metadata is stored in the form of diffs: to retrieve the complete "state" of a commit, PFS needs to traverse the commit history to merge the diffs.  This makes the performance of operations such as `ListFile` degrade linearly (e.g. #1006).

We could trade space for time by denormalizing metadata: storing more metadata in each commit so that we can spend less time reconstructing commits.  At an extreme, each commit can store a complete copy of the metadata it needs.  We can take some inspiration from git: http://stackoverflow.com/a/10398894

**Comment by JonathanFraser** [comment]
100% this, git has 3  objects (Commits, Trees, and Files) which work together in a massive distributed hash table. The hash table ensures that you have de-duplication and only extra storage you need is the relavant changes. It will mean that you need to perform multiple queries to traverse the file tree but not to traverse a single file.

**Comment by jdoliner** [comment]
This is implemented, commits now store full copies of their metadata.
