### ISSUE TITLE
 Weirdness with FUSE mount in OS X's Finder

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1089]
The FUSE mount on OS X allows deleting files from closed commits (very bad), creates zero-length files when add adding to an open commit (pretty bad), and has weird error messages in a number of other cases (kinda bad)

**In closed commit directories:**

- Adding a new file:
- - Prompts for a password
- - Errors out with "The item [file] cannot be copied because there is not enough free space"
- - No file gets added
- Re-adding an existing file
- - Prompts for a password
- - Errors out with "Operation cannot be completed because you do not have permission to access" (as expected)
- Deleting a file
- -Actually deletes the file from that commit and all future commits (ie re-writes history as shown by `pachctl`, not just as shown in local FUSE filesystem)
- Editing a file
- - Refuses to write data (as expected)
- - Appending to a file in bash gives error message: "Write error: undefined error 0"

**In open commit directories:**

- Re-adding a file that already exists errors out with "Not enough space"
- Adding a new file:
- - Errors out with "Finder cannot complete the op becuase some data in [filename] cannot be read or written. Error -36"
- - Still creates a zero-sized file

**Comment by sjezewski** [comment]
I don't think we planned on having / building finder support for fuse mounts.

FYI - this is likely to do w how we handle the weird metadata files that os x wants (the spotflight and '.' files)
