### ISSUE TITLE
(Auto?)-update pachctl version number in docs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1091]
In [the installation example](http://pachyderm.readthedocs.io/en/latest/deployment/deploying_on_the_cloud.html#install-pachctl) (and likely elsewhere) of the v1.2.3 docs, the version number shown is still 1.2.2

This should be updated, and ideally these updates should happen automatically as part of the release process. Unsure if RTD directly supports a way to do this, but if not, it seems a simple `sed` could.

**Comment by sjezewski** [comment]
I believe this was a bug. This is working now.
