### ISSUE TITLE
Process minimal datums instead of chunks

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1108]
Right now our job model works by breaking the data to be processed into `chunks` and farming those chunks out to several pods. Each pod processes all of the data in its chunk and then uploads the results into a commit and once every pod has succeeded the commits are merged to get the final result. This has a couple of downsides:

- nodes need to be able to fit the entire chunk and its output on disk
- `/pfs/prev` and `/pfs/state` (see #1057) don't work well with chunks, every chunk must see all of `prev` / `state` to be sure it sees the relevant data
- Chunks make incrementality hard, if 1 file changes there's no way to run just that file

The solution to these problems is to not process multiple pieces of data at once and instead always process a minimal piece of data (a datum). Minimal here is defined by the users input semantics for example if their job takes a single input with partition `FILE` then a datum is a file. If it takes 2 inputs, one `FILE` and one `BLOCK` then a datum is a (file, block) tuple. In this scheme each datum will get processed all by itself, ie the users command will be started and only 1 datum will be visible under `/pfs`. The output will be committed as its own commit which contains only the output from processing the datum. At the end all of these commits will be squashed together. This creates a powerful new avenue for incrementality because the commits can also be named as a hash of the datum and transform that was used to produce them. This means that anytime in the future that we try to process the same datum with the same transform we'll skip it and instead just use the commit we already have. This is a much more sophisticated form of incrementality, for example it can handle incrementality between commits that have no parent structure but still have common data between them.

Under this proposal the meaning of the `Method.Incremental` is going to change a bit. Currently jobs in which `Method.Incremental=NONE` aren't incremental at all. In this scheme they will be as long as the partition type isn't `REPO`. It should be pretty clear why this is, since we process each datum separately when a repo has a new file committed to it there's no need for a `FILE` pipeline to process the files that weren't changed in that commit, since we already did exactly that on the previous run of the job. This also means that `FULL` is no longer necessary as a value of `Incremental`, `(FILE,false/NONE)` will satisfy that use case under this new scheme.

### Performance Issues
This proposal has a number of positive effects on performance since it can save you having to do massive amounts of processing. There are some down sides though.

- We require a commit per datum processed. This is going to tick up our metadata size, although not that ridiculously since the commit documents will be pretty small and we already have tables that can require a row per datum processed such as the `Diff` table. I think this is pretty unavoidable if we want to have this level of granularity which I think we do. Along with the benefits in this issue this will also give us per datum provenance which is much more powerful than our existing provenance features.
- The user's process needs to be started once per datum processed. How big a deal this is will depend a lot on how the user implements processing. Ie if it's written in Java and needs to load a bunch of static data off disk before it can process anything it's going to be a big issue, a small C program not so much. I think we can probably fix this issue by having the user instead read datums to process off of stdin and output to stdout so that the same process can process multiple datums but still gives us the right granularity. For the purposes of this issue I think we should ignore this problem though and do the easy thing.

**Comment by gabrielgrant** [comment]
could the metadata explosion be avoided by processing a bunch of datum-tuples locally, and then committing the whole batch at once? From the users' perspective, the effect would be mostly the same: their code operates on a single datum-tuple. Presumably the job shim would just shuttle each set of datums into and out of /pfs before/after each run, and buffer it locally somewhere until it was ready to commit. This loses per-datum provenance, but saves a (potentially-very-large?) amount of network traffic/metadata storage

**Comment by gabrielgrant** [comment]
As for passing tuples of datums via stdin, not sure how that would work in practice. Encoding them in JSON objects or something seems fine in smaller cases, but if entire (potentially-large) files are being passed in, it seems likely there'd be cases where processing them on-disk would be preferable (or, if they're too big to fully buffer in memory, the only option)

**Comment by jdoliner** [comment]
Batching them together would decrease the metadata size but it would negate the benefits to incrementality that we're going for. This is really a fundemental tradeoff that we have to navigate. If the metadata for 2 inputs gets batched together then as far as our system is concerned it's really 1 input. If 1 of those inputs gets changed then we have to rerun both of them because we have no way to figure out which output is from the data that changed and which output is from the data that didn't.

> but saves a (potentially-very-large?) amount of network traffic/metadata storage

This would definitely save a fairly large metadata overhead. Back of the envelope I think we're going to need to at least store a hash for each datum tuple processed, assuming that's a 256 bit hash that's 32 bytes per datum. Which could get quite large, but I think is worth it for the computation speed ups we'll get. I don't think this'll have much impact on network traffic though. It should be about the same amount of data uploaded.

For the json case I was thinking you'd still use the filesystem and just pass in a json object with the names of the files to process, not the entire content of the files.

**Comment by jdoliner** [comment]
We do this now.
