### ISSUE TITLE
Jobs can download a huge amount of unneeded data

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1112]
Consider a very typical workload where you have a `models` repo and a `data` repo.  A pipeline takes both repos as inputs.  If a new model is added, the pipeline runs the model against a subset of data.

Currently (since #1078 landed), a job downloads all input data before executing.  Therefore, if a new commit comes into the `models` repo, the job will download the entire `data` repo.  This is clearly undesirable since:

1. The size of the `data` repo might exceed disk capacity.
2. The job doesn't even actually need the entire `data` repo.  It only needs a subset of the data (as determined by the newly added model).

**Comment by jdoliner** [comment]
I'm a little confused about what's going on here. What are the input methods of `models` and `data` in this example? Unless one of them is `REPO` I wouldn't expect it to ever be necessary to download either one in its entirety.

Also will #1108 help with this?

**Comment by JonathanFraser** [comment]
Lets say your data repo is 100TB and your models repo is small like 1GB. Each model maps to quite a bit of data. Now lets say you have a pipeline which is applying your models to the data (2 input pipeline) and you make a change to your model. Via the cross product rules, you have the change appearing in the model repo, but you have every single shard of data appearing in the data repo. If you cluster is medium sized, say 10 nodes. Hell lets be bold and say 100 nodes you will need to pull down 1TB per node which is not great. Even more so, lets say that a model doesn't apply to all the data and  you can tell which data to apply the model too by its path/filename. In which case you don't need to download all of the data which matches, but you won't be able to tell that until the job is running.

**Comment by derekchiang** [comment]
@JonathanFraser summarized the problem pretty well.

@jdoliner #1108 will help solve the first part of the problem, which is data might not fit into disk.  It doesn't solve the second problem which is that sometimes you really only need a subset of datums, and only the application itself knows which subset it needs (usually by looking at filenames).

**Comment by derekchiang** [comment]
@jdoliner has an interesting proposal:

Instead of using normal files in `/pfs`, we use unix domain sockets.  Each socket corresponds to a file in PFS.  This has the following benefits:

* We still get a non-FUSE file system layout.  That means meta operations (e.g. listing files) will be fast and non-buggy.
* Data is loaded lazily, thereby circumventing both problems mentioned in this issue (i.e. data doesn't fit onto disk, and only partial data is needed)

The downsides are:

* Sockets are still distinguishable from files, which means that certain applications might break.  For instance, sockets don't support seek.

**Comment by JonathanFraser** [comment]
@derekchiang @jdoliner This is probably been summarized in a different issue, but what about the Fuse layer makes it so slow. Is it the trips into userspace or something else?

**Comment by derekchiang** [comment]
It's slow due to the lack of caching.  When you read the same file twice, it's downloaded twice.  Even worse, every time you list a directory it translates to a `ListFile` over the network.

There is technically no reason why we can't just cache everything, but our FUSE implementation was already very buggy as it was, so instead of adding more code to it, we thought we might as well just get rid of it.

Implementing (and maintaining) a FUSE driver is hard because FUSE has many callbacks, since it's supposed to behave like a normal file system.  Compare this with a unix socket, which only needs to implement `read` and `write`.

**Comment by derekchiang** [comment]
With #1130, we now have a solution for this problem.  Basically you can set the `lazy` flag in your pipeline spec to download files lazily.  This is possible because when `lazy` is set, we put named pipes instead of normal files in `/pfs`.  The named pipes only download the corresponding files when they are explicitly read from.  Note that named pipes do not support certain syscalls such as `seek`.
