### ISSUE TITLE
`update-pipeline` Docker Hub logins

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1121]
I'm using `update-pipeline` with `--push-images` like this:

```
pachctl update-pipeline -f annotate.json --push-images --password XXXXX -u dwhitena
```

I can do this once and only once successfully.  After that once successful `--push-images`, I get the following:

```
dwhitena@dirac:annotate$ pachctl update-pipeline -f annotate.json --push-images --password XXXX -u dwhitena
Pushing dwhitena/chess-annotate:48e986766098493cb1bd4ce4b09029ec, this may take a while.
toomanyrequests: too many failed login attempts for username or IP address
```

Despite using the correct credentials and not having any other processing trying to log into Docker Hub.  Thus, it seems like something in the `--update-images` process is causing failed logins.  If I wait 10 minutes or so, the problem goes away (I'm assuming this is the window for Docker Hub).

**Comment by jdoliner** [comment]
Hmm, that is very strange indeed. I can't think of where the failed login attempts would be coming from given that it clearly succeeds in at least one of these attempts.

**Comment by jdoliner** [comment]
This issue seems like it's relevant: https://github.com/docker/docker/issues/22188

**Comment by dwhitena** [comment]
Between that issue from @jdoliner and some debugging, I was able to determine that this had nothing to do with Pachyderm or `pachctl`.  I had changed some setting to my local Docker login, and we trying failed logins when pushing images.
