### ISSUE TITLE
How's one supposed to develop their code without access to `/pfs`?

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1124]
Let's say I'm developing my pipeline.  Now, my code needs to read/write files on `/pfs` because that's how Pachyderm works.  But what if I don't have permission for `/pfs` on my dev machine?  Am I supposed to test my code against another directory (e.g. `~/pfs`), then once my code is passing all the tests, change the path to `/pfs` and build the image?  That seems like a strange workflow since I now have two versions of my code: one that works locally and another that works in production.

**Comment by sjezewski** [comment]
Interesting. Can you expand on cases where this might happen.

Is there a reason you couldn't do something like:

```
sudo mkdir /pfs
sudo chown `whoami` /pfs
```

**Comment by derekchiang** [comment]
In general it's annoying if you have to sudo to get your code to work. Also
you can certainly imagine someone developing via SSH on a company machine
that's shared among many users, so they can't create /pfs

**Comment by derekchiang** [comment]
One solution to this problem would be that, instead of using `/pfs`, a user's code is expected to use `$PFS`.  Then, the user can just set this environment variable to whatever (e.g. `~/pfs`) when they are developing.  Then in PPS, we'd just set this environment variable to whatever we want (e.g. `/pfs`).

**Comment by jdoliner** [comment]
Assuming that they're developing their code inside a container they can do `docker run -v ~/pfs:/pfs ...`. At least I think they can do that, there might be some weirdness with it being a fuse mount.

This problem with also go away if we switched to the model where the user's program is called with `cmd input1 input2 ...` since then there's no reason to hardcode paths.

**Comment by JonathanFraser** [comment]
All of our code takes the folders to process as inputs and we expand them out in the pipeline manifest. This makes it easy to quickly test code without mounkying with absolute paths.

Also please don't enforce how a users program gets called, leave that up to the manifest fixing a positional pattern can seriously hamper how a user passes flags and other information into their processing.

**Comment by sjezewski** [comment]
Stale

We have a few new issues around local user workflows that have an eye towards easier development.
