### ISSUE TITLE
Propagate k8s error messages to Pachyderm

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1125]
Right now, Pachyderm doesn't display very detailed error messages in some cases.  For instance, a job could be stuck in `pulling` state because the image can't be pulled (e.g. because the image is private, or it doesn't exist), but you won't know that until you look into Kubernetes.

**Comment by sjezewski** [comment]
There are a lot of cases to cover here. Feedback like this is going to be required if long term we expect our users to never touch k8s.

**Comment by jdoliner** [comment]
We do a lot better on these issues now, objects that can fail (jobs and pipelines) have a `Reason` field that will contain a description of why they failed. For cases like the one mentioned initially, where the error is coming from k8s, we propagate that back to the user via the `Reason` field.
