### ISSUE TITLE
Default AWS instance type only has 4GB of disk space

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1126]
Right now in the [AWS deployment guide](http://pachyderm.readthedocs.io/en/latest/deployment/deploying_on_the_cloud.html#amazon-web-services-aws), we recommend using the `m3.medium` instance type, which only has 4GB of disk space.  That's too little considering that users commonly use docker images that are GBs in size.

I recommend using `m3.large` as the default instead, which has 32GB of disk space.

**Comment by JoeyZwicker** [comment]
closed via #1155
