### ISSUE TITLE
Documentations on joining files from multiple input repos

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1129]
We've run into this pattern again and again: a user has more than one input repos (let's say 2), and for each file in input repo 1, the user wants to "join" it with a subset of files in input repo 2.  We should have an example or some sort of documentation for this pattern.

**Comment by JoeyZwicker** [comment]
Dan or I can certainly put something together for this. We're racking up a bunch simple pipeline arrangements that could documents -- they're not full-fledged data science examples or anything so should be easy to crank a few of these out.

**Comment by dwhitena** [comment]
This is documented (at least for a start) in the pipeline spec docs.  Closing for now until we want to expand:

![image](https://user-images.githubusercontent.com/4524535/27450622-42c31dd8-575a-11e7-8f6a-21a9460ec57b.png)
