### ISSUE TITLE
Recovering from out of disk errors

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1133]
I just wanted to document this from a customer onsite.

We ran out of disk space because we were using a 2GB image for a job and the nodes only had a 4GB SSD so pulling and unpacking the image failed. This also caused Pachyderm's etcd pod to fail. It's unclear if every node filled up as kubernetes tried to pull the container again after the first failure or just one. 

Unfortunately we didn't have SSH access enabled to be able to get into the node and delete the image. @derekchiang found docs that make it seem like K8s should have GCed the image after the job was deleted, but that didn't seem to work. This was live during an onsite so we didn't investigate then, just spun up a new cluster, but we should investigate further so we have a known recovery path (or definitively not) if we run into this in the future.

Also to check, even if we had been able to free up disk space, would etcd have recovered?

**Comment by sjezewski** [comment]
We've seen this in a few instances. This is a very concrete example (non job data leaking, etc).

In cases where we have cleaned the disk I have seen clusters recover. Sometimes if k8s was thrashing enough (creating/evicting many pods) it takes a while ... or you can delete the evicted pods and it goes faster.

Either way, I do want better tooling for this for the user for cases we can't anticipate. This issue I think is the most pragmatic method: https://github.com/pachyderm/pachyderm/issues/1389
