### ISSUE TITLE
No binaries for 1.2.6 release - Homebrew broken

### ISSUE THREAD

**Issue by dahankzter** [pachyderm/pachyderm#1134]
Are there supposed to be binary releases for 1.2.6 as well? It is very neat. :)

**Comment by sjezewski** [comment]
Hey @dahankzter - thanks for the heads up.

Since that was a custom release, it didn't include some of the build artifacts by default, but we provide the release binaries through homebrew / a public URL for the deb package. I've updated the release notes, but basically your options are:

```
# For OSX:
$ brew tap pachyderm/tap && brew install pachctl

# For Linux (64 bit):
$ curl -o /tmp/pachctl.deb -L https://pachyderm.io/pachctl.deb && sudo dpkg -i /tmp/pachctl.deb
```

**Comment by dahankzter** [comment]
I still get this result:

```bash
brew tap pachyderm/tap
brew install pachctl
==> Installing pachctl from pachyderm/tap
==> Downloading https://github.com/pachyderm/pachyderm/releases/download/v1.2.6/pachctl_1.2.6_darwin_amd64.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pachctl"
Download failed: https://github.com/pachyderm/pachyderm/releases/download/v1.2.6/pachctl_1.2.6_darwin_amd64.zip
```

Perhaps I misunderstood?

**Comment by gabrielgrant** [comment]
Yes, sorry for the confusion @dahankzter , you're right, it does seem the binaries are missing. Reopening.

**Comment by gabrielgrant** [comment]
@dahankzter if you want to try the 1.2.4 release, that should get you going for now

I'm actually on linux, so i'm not able to test the specific commands to run, but i believe you should be able to list the versions available with `﻿⁠⁠⁠⁠brew search pachyderm`﻿⁠⁠⁠⁠

Then you should be able to `﻿⁠⁠⁠⁠brew install <specific-version>﻿⁠⁠⁠⁠`

(I ﻿⁠⁠think﻿⁠⁠ ﻿⁠⁠⁠⁠<specific-version>﻿⁠⁠⁠⁠ should be something like `﻿⁠⁠⁠⁠pachderm/pachyderm_1.2.4﻿⁠⁠⁠⁠` but that's what i'm not 100% sure of)

**Comment by dahankzter** [comment]
Hmm I think it is broken because I removed it before (brew complained a lot) and now I can't use ```switch``` or anything else that allows versions since it seems it has to be installed at least once first. :(

Ill look around to see if there is something I missed about homebrew details.

**Comment by sjezewski** [comment]
You're right ... the binary URL referenced in the homebrew formula was broken. This should be fixed now.

FWIW, to install the latest pachctl, I usually do the following:

```
brew untap pachyderm/tap
brew tap pachyderm/tap
brew unlink pachctl # if you have an existing version
brew install pachctl
```

That should make sure you have the latest formula, and will get the latest version. If you have a better workflow, I've love to hear it!

Please let me know if homebrew is working for you.

**Comment by dahankzter** [comment]
Works now thx!
