### ISSUE TITLE
Reduce verbosity of logs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1139]
Right now our logs are very verbose.  It's even happened a couple times that our logs filled out the disks, causing nodes to crash.

We should look into:

* Reducing log level (right now we use `info`).
* Reducing the verbosity of our logs.
* Reducing the amount of events what we log (e.g. some high-volume events like `PutBlock` are not that valuable for debugging purposes)

**Comment by sjezewski** [comment]
stale
