### ISSUE TITLE
RethinkDB changefeeds do not guarantee at-least-once delivery

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1145]
PPS uses [RethinkDB changefeeds](https://www.rethinkdb.com/docs/changefeeds/ruby/#scaling-considerations) internally to receive events such as pipeline creations, job creations, etc.  However, RethinkDB changefeeds do not provide [at-least-once delivery guarantees](http://www.cloudcomputingpatterns.org/at_least_once_delivery/), which means that we might not receive some of those events, which can in turn lead to pipelines not starting, jobs not starting, etc.

Two solutions:

* PPS can periodically resync its state with the database to ensure that its state is correct (e.g. that all pipelines that should be running are running).
* Use a message queue that guarantees at-least-once delivery (e.g. RabbitMQ, ZeroMQ) in place of RethinkDB changefeeds.

**Comment by sjezewski** [comment]
rethink is dead! long live etcd!
