### ISSUE TITLE
etcd failover causes the cluster to hang

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1148]
Right now all state in etcd is transient except for `cluster-id`, which we use in metrics to identify the cluster.  However, this one piece of transient state makes pachyderm unable to recover from etcd failover, since once a etcd pod fails the state is lost (because we are not deploying etcd on a persistent volume).

We should either move `cluster-id` to a persistent store such as the blob store or rethinkdb.  Or we could deploy etcd in cluster mode, although that seems like an overkill.

**Comment by derekchiang** [comment]
It's worth noting that deploying etcd in cluster mode does have the benefit of enhanced availability: Pachyderm will continue to function even when a etcd pod is down.  Otherwise (i.e. if we only have one etcd pod), Pachyderm will be unavailable until a new etcd pod starts up.

**Comment by sjezewski** [comment]
The deploy flag `--static-etcd-volume` / `--dynamic-etcd-nodes int` flags allow you to deploy w a PV, which solves this issue.
