### ISSUE TITLE
File modification error in Jupyter

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1171]
Even when a notebook is created in `/pfs/out` with "service," the notebook occasionally gives the following error:

![image](https://cloud.githubusercontent.com/assets/4524535/20988443/c5a66a22-bc9e-11e6-8840-e89e4ff3dece.png)

If you select `Overwrite` you can continue working and save the notebook as you go along.  However, this error can still pop up again.

**Comment by sjezewski** [comment]
stale
