### ISSUE TITLE
Pipelines restart slowly

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1182]
Currently if you have a pipeline that has completed N jobs, and you restart pachd, it will take O(N) time before the pipeline can pick up from where it left off and start spawning new jobs.

This is because the pipeline essentially needs to "reprocess" all jobs, except that the jobs that have been completed are not actually run again.  But still, it can take a while if N is large.  In a deployment I'm looking at, it took more than an hour for five pipelines that collectively have about 4k jobs to restart.

**Comment by sjezewski** [comment]
Should be fixed by 1.7 / commit invariance

**Comment by emmapeaxis** [comment]
I'm still having this problem in pachyderm 1.10
