### ISSUE TITLE
A job is not recreated if the underlying k8s job is removed

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1185]
Right now if you have a job running, and you manually remove the underlying k8s job for some reason, the job will be stuck in `running` forever, since there's no mechanism to recreate the k8s job.

**Comment by jdoliner** [comment]
This bug no longer exists exactly as described because there's no longer underyling jobs, but the equivalent would be the deleting the RC for a pipeline while it's running. This will now fail the pipeline with an informative `Reason` field.
