### ISSUE TITLE
Data Egress/Ingress examples

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1186]
We'd like to have more examples of getting data into and out of pachyderm from various other data products. Examples of things we'd like to have:

- postgres
- s3 (and friends)

Feel free to add more things to the list, those are the 2 I've heard the most.

**Comment by JoeyZwicker** [comment]
Redshift is also very common and I assume was included in "friends." 

Elastic Search is a common one too.

Kafka has come up occasionally -- being able to egress data as a kafka topic (I don't really understand the terminology of kakfa so I might be using it wrong)

HDFS has obviously been requested.

**Comment by sjezewski** [comment]
stale
