### ISSUE TITLE
Update troubleshooting docs to include params into --dry-run

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1187]

**Comment by dwhitena** [comment]
@JoeyZwicker is this still needed?  What is the use case?

**Comment by JoeyZwicker** [comment]
there are a number of workflows where users need to generate the manifest using dry run to troubleshoot and make sure things are getting set correctly. I think the impetus was document that somewhere. Not super important

**Comment by gabrielgrant** [comment]
I believe this needs to be done as part of #1226 , but people do seem to have uses for `--dry-run` beyond just deploying from a private registry

Omer Katz and Homme discussed this recently in slack: https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508146446000362

**Comment by gabrielgrant** [comment]
related: #1833
