### ISSUE TITLE
Support languages other than Go

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1189]
Our entire API is defined via GRPC which should, in theory, make it very easy for us to create clients in any language that supports grpc. In practice of course it's a little bit more difficult but should be doable. Languages we'd like to support in approximate order of importance:

- __PYTHON__
- Java
- C++
- Ruby
- Rust

Probably many more that would interesting to people.

**Comment by teodimache** [comment]
I would very much like to see C# on that list if possible :)
It is a gRPC/Protobuf supported language after all. and it's gaining in popularity now with .NET Core being open source and multi-platform.

**Comment by sjezewski** [comment]
We're in the process of transitioning a 3rd party python client for official support. That'll inform how we support other languages going forward.
