### ISSUE TITLE
Persist everything to object storage

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1190]
Right now users need to deploy Pachyderm with a persistent volume for Rethinkdb and they need to make sure they hold onto that data, if they lose it then they won't be able to recover the state of their cluster. This only gets more painful when they shard rethinkdb and now have multiple PVs to keep track of. To fix this we can checkpoint our state into object storage, that way the object store can serve as the source of truth and rethink becomes more of a sophisticated caching layer.

**Comment by jdoliner** [comment]
This feature still makes sense post 1.4 with etcd in place of rethink.

**Comment by sjezewski** [comment]
I believe @jdoliner's recent migration PR does something like this. It marshals all of a clusters state into a file, and you can create a cluster from that file. Saving it into obj storage is left to the user, but can be readily done

**Comment by jdoliner** [comment]
Saving it to object storage is actually something it'll do to. Since it's better to go straight from `pachd` to object storage than have to go through whatever machine `pachctl` is installed on.
