### ISSUE TITLE
Revoke leases on chunks lazily

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1191]
Currently, for each job we have a long-running goroutine (named `jobManager`) that's responsible for revoking the leases on the job's chunks, so that other pods may claim a chunk if the pod that was processing the chunk has crashed.

It occurred to me that we can instead revoke the chunks lazily: when a pod requests a chunk, we simply search for chunks whose leases haven't been "refreshed" in a while.

**Comment by sjezewski** [comment]
Chunks? Leases? Oh my!

These are gone in 1.4
