### ISSUE TITLE
Make jobs more fault-tolerant by moving the job creation logic into jobManager

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1192]
Currently, to create a pipeline, a user calls `CreatePipeline`, and a document is inserted into the database, stating that "there shall be a pipeline."  Then, a fault-tolerant process receives the update from the database and starts a pipeline.

We should do the same for `CreateJob`, which currently is a monolithic function that does everything, containing many failure modes.  `CreateJob` should simply insert a document into the database, stating that "there shall be a job."  Then, the fault-tolerant `jobManager` process (which we already have) should actually create a k8s job.

**Comment by sjezewski** [comment]
We had a user w a specific case where this would have helped:

a user (accidentally) deleted a k8s job that corresponded to a running pachyderm job (part of a pipeline), which made the pipeline unrecoverable

This should be easy enough to add as a test case for this feature.

**Comment by sjezewski** [comment]
@JoeyZwicker you literally just asked about this case ... but I didn't hear the conclusion. Care to chime in?

**Comment by jdoliner** [comment]
This is actually how it works in 1.4 so closing.
