### ISSUE TITLE
Preserve logs from GC-ed containers

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1198]
Currently Pachyderm automatically garbage collects finished jobs in order to reclaim disk space.  However, some users might find it useful to keep the logs (and only the logs, not the data) from those containers around.

Two solutions:

1. Store the logs internally in Pachyderm before we move the containers.
2. Use an external logging services (e.g. GCE's Stackdriver logging); this will mainly just involve adding documentation for setting up these services for each cloud provider.

**Comment by sjezewski** [comment]
We have the `make logging` task which stands up the logging service. This aggregates / stores as needed.
