### ISSUE TITLE
Job scheduling priority

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1203]
This feature request came from @orenyomtov. 

For a simple DAG of A -> B -> C, if the commits frequency into A is much quicker than the processing time of A->B (or, for example, Pipeline B is created after there are already many commits in A), then A->B jobs get queued to be scheduled by k8s before any B->C jobs are triggered. 

The feature being requested would be to specify a priority level to the B->C jobs so, once triggered by the pipeline, they get scheduling priority over the queued up A->B jobs. This is obviously a k8s feature that it either has or doesn't right now (an cursory search doesn't pop up an obvious answer to me, but there are open issues discussing it: [here](https://github.com/kubernetes/kubernetes/issues/22212) [here](https://github.com/kubernetes/kubernetes/issues/28928) [here](https://github.com/kubernetes/kubernetes/issues/12140)) and Pachyderm would just need to expose it if k8s eventually adds this feature.

**Comment by sjezewski** [comment]
No longer valid ... we have workers and so k8s scheduling has a different effect now
