### ISSUE TITLE
Expose secrets to pipeline via env variable

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1204]
Right now you have to specify:

```
    "secrets": [ {
        "name": "secret_name",
        "mountPath": "/path/in/container"
    } ],
```

And when running the command can do something like:

```
    "cmd": [ "/bin/bash"],
    "stdin": [ "some_key=`cat /path/in/container/secret_name` mycommand.exe"]
```

Instead it would be handy to be able to do something like:

```
env: [
    "name" : {
        "type" : "secret",
        "path" : "/path/in/container/secret_name"
    }
]
```

Which would tell the pipeline to mount the secret and set the ENV var

**Comment by jdoliner** [comment]
This seems like a fine idea. I'm a little confused by the API though, what does `/path/in/container/secret_name` do if we're exposing the secrets as EnvVars? I'm imagining it would be something like:

```
Env: {
    "name" : {
        "secret": "my-secret",
        "key: "my-key"
    }
}
```

Also this seems to require using `one_of` in protobuf which we've had our issues with in the past. As always though there's a none `one_of` way to do it using an enum so I suspect we should probably do something like that.

**Comment by dwhitena** [comment]
@sjezewski note that supporting this https://github.com/pachyderm/pachyderm/issues/1883, would seemingly solve this problem.
