### ISSUE TITLE
Allow passing flags to underlying kubectl where applicable

### ISSUE THREAD

**Issue by rrichardson** [pachyderm/pachyderm#1206]
I have multiple k8s clusters, (dev and prod) which I operate from the same jump host.  To avoid accidental applications to one cluster,  I don't put kubeconfigs in the standard location, but rather apply `kubectl --kubeconfig=path/to/kubeconfig`.   For verbs like pachctl port-forward, it uses kubectl without flags. 

If one could do `pachctl --kubeconfig=/path/to/kubeconfig`  or `pachctl --kubectlflags='--kubeconfig=...'`  this would be helpful.

**Comment by JonathanFraser** [comment]
pachctl port-forward is actually only a thin wrapper around kubectl port-forward and it can be used directly for use cases such as this.

**Comment by jdoliner** [comment]
Yeah, all `pachctl port-forward` does is find a pachd pod and do `kubectl port-forward <pod>`

**Comment by sjezewski** [comment]
Fixed in #1441
