### ISSUE TITLE
PetSets have been renamed to Stateful Sets

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1210]
[PetSets have been renamed to Stateful Sets in 1.5](http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set)

**Comment by jnevin** [comment]
I was excited about the Pachyderm 1.3 release (still am). 

This issue, however, **breaks the current Beginner Tutorial documentation.**

It took some (useful learning) hours to figure out a temporary workaround (Mac OS X 10). There's probably an easier way, but this worked for me:

Make sure you can start minikube:
```
$ minikube start
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
```
Create a pachctl manifest you can edit and use with kubectl for a fixed deployment:

`$ pachctl deploy local --dry-run > pachctl-manifest-old.yaml`

Then edit the **pachctl-manifest-old.yaml** file you created above and replace the lines:
```
{
 "apiVersion": "apps/v1alpha1",
 "kind": "PetSet",
```

with (per instructions [here](http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/))

```
{
  "apiVersion": "apps/v1beta1",
  "kind": "StatefulSet",
```

and save the file as, say, **pachctl-manifest-new.yaml**

Then, instead of: 

`pachctl deploy local`

do:

```
$ kubectl create -f pachctl-manifest.yaml`
serviceaccount "pachyderm" created
persistentvolume "rethink-volume-0" created
replicationcontroller "etcd" created
service "etcd" created
service "rethink" created
statefulset "rethink" created
service "rethink-headless" created
job "pachd-init" created
service "pachd" created
replicationcontroller "pachd" created
```

Then you can do your port forwarding:

```
$ pachctl port-forward &
[1] 6291
Jamess-MBP-2:$ Port forwarded, CTRL-C to exit.

```

and see that things are in order:

```
$ pachctl version
COMPONENT           VERSION
pachctl             1.3.1
pachd               1.3.1
```

**Comment by JoeyZwicker** [comment]
Thanks @jnevin for taking the time to write this up and sorry you ran into this! v1.3 came out right before k8s 1.5 and this naming change broke a few things for us. We're going to get this fixed asap as there are a few other k8s v1.5 issues that have cropped up too. 

For future reference, you can also use the flag `--deploy-rethink-as-rc` with `pachctl deploy` which will deploy it as a replication controller as before instead of a PetSet/StatefulSet. For local deployment, having Rethink as a PetSet doesn't really get you as much. :)

Regardless, we'll definitely get this all tidied up ASAP. @msteffen

**Comment by jnevin** [comment]
Thanks @JoeyZwicker

But when I use the `--deploy-rethink-as-rc` option, I get these errors:

```
$ pachctl deploy local --deploy-rethink-as-rc
panic: RethinkDB can only be managed by a ReplicationController as a single instance, but recieved 0 volumes

goroutine 1 [running]:
panic(0x1135340, 0xc4207ae210)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets.WriteAssets(0x1d7ff80, 0xc420292150, 0xc4204534c0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x13912c0, 0xe)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets/assets.go:856 +0xf2b
github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets.WriteLocalAssets(0x1d7ff80, 0xc420292150, 0xc4204534c0, 0x13912c0, 0xe)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets/assets.go:878 +0x83
github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds.DeployCmd.func1(0xc4204e5100, 0x0, 0x1, 0x0, 0x0)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds/cmds.go:60 +0x115
github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/pkg/cobra.RunBoundedArgs.func1(0xc4203e8d80, 0xc4204e5100, 0x0, 0x1)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/pkg/cobra/pkgcobra.go:26 +0x9d
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203e8d80, 0xc4204e50a0, 0x1, 0x1, 0xc4203e8d80, 0xc4204e50a0)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:572 +0x439
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42044eb40, 0xc42011d720, 0xc4204e4ff0, 0xc42011d721)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:658 +0x367
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42044eb40, 0xd, 0xc42044eb40)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.do(0x10f8d40, 0xc42011d700, 0x0, 0x0)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:26 +0x119
github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/env.Main(0x148a328, 0x10f8d40, 0xc42011d700, 0x0, 0x0, 0x0)
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/env/env.go:46 +0x83
main.main()
	/home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:16 +0x7d
```

Note that I'm seeing this with kBs 1.5.1

Any clue how I'd get the `--deploy-rethink-as-rc` option to work now?

**Comment by msteffen** [comment]
This is an unfortunate bug in pachctl 1.3.1. It's already fixed in master, and will be fixed in 1.3.2, which should be released in a few days.

**Comment by jdoliner** [comment]
@jnevin sorry you're running into this. As @msteffen said the fix should land soon but in the meantime here's a manifest that should work:

[manifest.txt](https://github.com/pachyderm/pachyderm/files/659629/manifest.txt)

Note however that I think there are still going to be some breaking issues with 1.5. #1193 hasn't been addressed in master yet so probably you're best path to a working cluster is k8s 1.4 and that manifest. 1 way to get a k8s cluster is to just do `make launch-kube` from the root of the pachyderm repo. This will launch an entirely dockerized k8s cluster.

**Comment by jdoliner** [comment]
This has been fixed by #1230.

**Comment by jnevin** [comment]
Hey @jdoliner 

1.3.2 release plays nicely now with kB8s 1.5.1 -- thanks! Have not tested the Tutorials yet to see if they work. 

Here's good news:

```
$ pachctl deploy local
serviceaccount "pachyderm" created
persistentvolume "rethink-volume-0" created
replicationcontroller "etcd" created
service "etcd" created
service "rethink" created
persistentvolumeclaim "rethink-volume-claim" created
replicationcontroller "rethink" created
job "pachd-init" created
service "pachd" created
replicationcontroller "pachd" created
```

```
$ kubectl get all
NAME               READY     STATUS    RESTARTS   AGE
po/etcd-t8vjc      1/1       Running   0          5m
po/pachd-kn2r6     1/1       Running   5          5m
po/rethink-5x5nx   1/1       Running   0          5m

NAME         DESIRED   CURRENT   READY     AGE
rc/etcd      1         1         1         5m
rc/pachd     1         1         1         5m
rc/rethink   1         1         1         5m

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)                                          AGE
svc/etcd         10.0.0.157   <none>        2379/TCP,2380/TCP                                5m
svc/kubernetes   10.0.0.1     <none>        443/TCP                                          5m
svc/pachd        10.0.0.148   <nodes>       650:30650/TCP,651:30651/TCP                      5m
svc/rethink      10.0.0.225   <nodes>       8080:32080/TCP,28015:32081/TCP,29015:32119/TCP
```

```
$ pachctl version
COMPONENT           VERSION
pachctl             1.3.2
pachd               1.3.2
```

**Comment by jnevin** [comment]
Note: you do have to wait a couple of minutes before the pachd pod runs successfully.
