### ISSUE TITLE
Update AWS docs for permanent credentials setup

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1214]
When we do demo's we want them to use permanent creds, or all the work of getting it setup disappears in a few days.

[The gist is that you can use user credentials as described here](https://github.com/pachyderm/demos/tree/master/modules/s3_upload)

But this should be part of the docs. Often times when we're doing a demo they have these credentials, but use the temp ones just because that is what is listed in our instructions.

**Comment by JoeyZwicker** [comment]
+1 I'll put it on my list and get to it soon since everyone is bust with other things

**Comment by jdoliner** [comment]
Should we also modify `pachctl deploy amazon` so that the token is an optional argument?
That would probably help nudge people in the direction we want them to go.

**Comment by JoeyZwicker** [comment]
That's a great idea IMO. Maybe it makes more sense for the PR to be that change and include updating the docs to reflect it and push users following our AWS deployment steps to set it up correctly. 

Thinking about this more, I actually don't know squat about dealing with AWS tokens or dealing with iam users, so assigning this to myself probably isn't the best answer as I'll need help anyway.

**Comment by orangefuzzball** [comment]
I'm getting a 404 for the gist and currently can't put any data into an AWS deploy due to credentials being expired.

"pachctl put-file data master tripdata.csv -c -f foo.csv
invalid header field value "ExpiredToken: The provided token has expired.\n\tstatus code: 400, request id: 56C969052ED88005"

Where are the docs on how to update this?

**Comment by jdoliner** [comment]
Docs for this are available here: https://github.com/pachyderm/pachyderm/blob/master/doc/deployment/deploying_on_the_cloud.md#start-pachyderm-1

The relevant bit is that all you need to do is leave the token empty and make sure that the user has the correct permissions and the cluster should operate indefinitely.

**Comment by orangefuzzball** [comment]
These credentials are only used for the s3 bucket and the ebs store?

**Comment by jdoliner** [comment]
@orangefuzzball yup, that's correct.

**Comment by dwhitena** [comment]
This has all been updated.  Closing.  Correct me if I'm wrong.
