### ISSUE TITLE
pachctl create-pipeline never times out

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1219]
Even if pachctl can't connect to the cluster for some obviously non-transient reason (e.g. you forgot to run port-forward), `pachctl create-pipeline` happily retries forever. I wonder if it should eventually time out, and notify users when that happens.

**Comment by JoeyZwicker** [comment]
I think many pachctl never time out if port-forward isn't set. `create-repo` definitely has the same behavior.

**Comment by jdoliner** [comment]
This will now exit with `context deadline exceeded`.
