### ISSUE TITLE
Beginner tutorial not working

### ISSUE THREAD

**Issue by binary-finary** [pachyderm/pachyderm#1224]
I’m having trouble running the beginner tutorial on K8s 1.4.7 and P7m 1.3.1 using the manifest posted by Joe at the bottom of GitHub issue 1210.
 
I can create repos and load the data, but when I run the pipleline only the ‘filter’ job is reported and it’s in the ‘failure’ state.  A couple notes:
-          The docs use the 1.2.1 pipeline (which seems wrong), but the 1.3.1 version has the same problem.
-          Both the ‘filter’ and ‘sum’ repos are created, but both are empty.
 
I’m happy to debug this myself, but don’t know where to start.  I couldn’t find anything on your troubleshooting page on how to access the logs.
 
How should I proceed?

**Comment by jdoliner** [comment]
Hi @binary-finary sorry you hit this. Jobs normally fail when the code running in the pod encounters some sort of an error. Could you do `pachctl get-logs <job-id-of-failed-job>` and paste the results in here? That should give us an idea of what's going wrong.

**Comment by binary-finary** [comment]
list-job returns:
ID                                 OUTPUT                                      STARTED             DURATION             STATE               
67c30d70ba9d2179aa133255f5dc81db   filter/9d3816237ecc4e32b38fd3e577376a07/0   5 seconds ago       Less than a second   failure  

I assume the first hash is the job id, but then I get:

$ pachctl get-logs 67c30d70ba9d2179aa133255f5dc81db
job 67c30d70ba9d2179aa133255f5dc81db not found

Sorry if I've misunderstood your instructions.

**Comment by jdoliner** [comment]
That's the correct command. It's possible that kubernetes has garbage collected the job or something. What do you get if you do `kubectl get pod -a`? You should see a pod with that uuid as a prefix followed by 5 random characters. If you do `kubectl logs <pod-name>` that should hopefully get you the same thing. If k8s has already gced it then you won't be able to get the logs, in that case I'd recommend deleting the pipelines and their output repos and then creating the pipelines again. This should recreate the k8s jobs and thus the logs.

**Comment by binary-finary** [comment]
Seems like my pod was removed...

$ kubectl get pod -a
NAME               READY     STATUS      RESTARTS   AGE
etcd-srw0p         1/1       Running     0          1h
pachd-init-m5r6x   0/1       Completed   0          1h
pachd-m99l2        1/1       Running     1          1h
rethink-zttvw      1/1       Running     0          1h

I've looped through the demo script several times now (including deleting the minikube), and the result is always the same (mravi on your Slack channel has confirmed this as well).  Are there extra debugging options to track that down?  I could also just wait for your 1.3.2 release if that's easier for you.

I'm running OSX 10.11.6 and VirtualBox 5.1.10.

Thanks

**Comment by jdoliner** [comment]
By far the easiest debugging option is to get logs from the job before it gets removed by k8s. Unfortunately I think `minikube` is pretty aggressive about garbage collecting completed pods. Would you mind doing one more run through and capturing the logs of the jobs right after it fails before k8s has a chance to garbage collect it?

**Comment by binary-finary** [comment]
I started by deleting the minikube, creating the pods via the suggested manifest and reloading the data repo.  I then issued a create-pipeline and followed with:

$ pachctl list-job
ID                                 OUTPUT                                      STARTED             DURATION             STATE               
67c30d70ba9d2179aa133255f5dc81db   filter/8f4e6468bacd43818dfa878b751fabb3/0   2 seconds ago       Less than a second   failure    

And just a couple seconds later issued a:

$ pachctl get-logs 67c30d70ba9d2179aa133255f5dc81db
job 67c30d70ba9d2179aa133255f5dc81db not found

And a couple seconds after that:

$ kubectl get pod -a
NAME               READY     STATUS      RESTARTS   AGE
etcd-6m5j2         1/1       Running     0          6m
pachd-g46bp        1/1       Running     0          6m
pachd-init-4kdh9   0/1       Completed   0          6m
rethink-c15s6      1/1       Running     0          6m

Am I doing this correctly?  Any environment setting you want to know?  Happy to keep trying if this is worth your time.

Thanks

**Comment by jdoliner** [comment]
@binary-finary hmm, that's a somewhat unexpected result maybe. Few more questions:

- Could you grab logs from `pachd` with `kubectl logs pachd-g46bp`?
- when you delete the minikube and then recreate it is kubernetes empty at this point? `kubectl get all` should just have a single kubernetes service running, no pachyderm jobs / pods. Is this the case?

**Comment by binary-finary** [comment]
Yes, I verified K8s was free of P7m (did I coin that term?) after the minicube reboot.  The attached logs contain several error messages, so we're making progress.

[pachd_logs.txt](https://github.com/pachyderm/pachyderm/files/664982/pachd_logs.txt)

**Comment by jdoliner** [comment]
> did I coin that term?

You did! And I really like it, expect to see that in common usage from now on :P 

Also I think I've found the guilty party here:

```
2016-12-20T22:37:50Z ERROR error running pipeline filter: Job.batch "67c30d70ba9d2179aa133255f5dc81db" is invalid: spec.template.spec.initContainers[0].env[1].valueFrom.fieldRef.apiVersion: Required value; retrying in 620.581479ms
```

K8s seems to be rejecting the job that pachyderm is trying to create. That would also explain why we can't get logs from it, it's not that the job is failing during execution it's just failing to create entirely. This is an issue I'd seen with k8s 1.5 but I'm guessing that k8s 1.4.7 exhibits this behavior too. In the short term running an earlier version of k8s is probably your best bet to get something working. This issue is fixed by #1223 we should have that merged in and shipped by the end of the week in which case this problem should go away.

**Comment by binary-finary** [comment]
Thanks for working through this.  I'll verify 1.3.2 fixes the problem and report back on this thread.

**Comment by jdoliner** [comment]
@binary-finary 1.3.2 has been released so this should no longer be an issue, let us know if things still aren't working.
