### ISSUE TITLE
Add docs for setting up pachctl with a private docker registry

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1226]
http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry

Since this has come up for several PoCs

**Comment by sjezewski** [comment]
Or, since some users don't have access to setting up EC2 container service (ECR), instructions for setting up credentials to a private dockerhub repo:

http://stackoverflow.com/questions/36232906/how-to-access-private-docker-hub-repository-from-kubernetes-on-vagrant

**Comment by sjezewski** [comment]
This will become a blocker for at least one customer's production deployments soon. For now using dockerhub is OK, but they'd prefer to use ECR. Since we'll have to support this endeavor either way, we'll make sure to document it.

**Comment by sjezewski** [comment]
This is a requirement for a paying customer.

**Comment by JoeyZwicker** [comment]
I think this is doc'ed in the pipeline spec.

**Comment by gabrielgrant** [comment]
The pipeline spec explains how to set `image_pull_secrets` so pach can pull user images from a private registry, but AFAICS we still don't have any docs on how to actually deploy pachyderm itself from a private registry (which is what this issue seems to be about)

**Comment by JoeyZwicker** [comment]
#2319 is the issue for deploying pachyderm from an internal registry and I already have it marked as a docs issue. Is there something here that's different?

**Comment by gabrielgrant** [comment]
Nope, it looked to me like that was the issue for making it possible (ie the code), and this was the issue for adding the docs. But if you want to track it all the, that works too :)
