### ISSUE TITLE
Remove --deploy-rethink-as-rc error message for pachyderm 1.4

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1228]
I am working on a change to `src/server/pkg/deploy/cmds/cmds.go` that has the following warning message for users of `--deploy-rethink-as-rc`:

```
fmt.Println("--deploy-rethink-as-rc is no longer necessary (and is ignored). " +
		"The default behavior since Pachyderm 1.3.2 is to manage RethinkDB " +
		"with a Kubernetes Replication Controller. This flag will be removed " +
		"by Pachyderm's 1.4 release, so please remove it from your scripts. " +
		"Also see --deploy-rethink-as-stateful-set.")
```

We should make sure to delete this error message for the Pachyderm 1.4 release, as promised (making all uses of this flag an error)

**Comment by sjezewski** [comment]
No more rethink!
