### ISSUE TITLE
Make blocks available in FileInfo

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1233]
Request by users, they'd like to be able to get the list of s3 files that make up the content of a file in pfs so they can access it directly through the s3 api rather than having to talk to pachyderm. This would allow them to use cdn's like cloudfront to increase performance.

**Comment by derekchiang** [comment]
Related: #223

**Comment by sjezewski** [comment]
We have cloudfront in alpha now, so if that's the ask here, I think we can close this issue. @jdoliner ?

**Comment by jdoliner** [comment]
That is not the ask here. Having cloudfront still doesn't give you a way to request blocks for a file directly from it because you don't know which blocks to request.

**Comment by sjezewski** [comment]
stale

(if we see another request, we can re-open)
