### ISSUE TITLE
The ReplicationController "pachd" is invalid

### ISSUE THREAD

**Issue by willis7** [pachyderm/pachyderm#1246]
```
...
Selecting previously unselected package pachctl.
(Reading database ... 61162 files and directories currently installed.)
Preparing to unpack /tmp/pachctl.deb ...
Unpacking pachctl (1.3.2) ...
Setting up pachctl (1.3.2) ...
No config detected.
Default config created at /root/.pachyderm/config.json
serviceaccount "pachyderm" created
persistentvolume "rethink-volume-0" created
replicationcontroller "etcd" created
service "etcd" created
service "rethink" created
persistentvolumeclaim "rethink-volume-claim" created
replicationcontroller "rethink" created
job "pachd-init" created
service "pachd" created
ERROR >>>>>> The ReplicationController "pachd" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy
ERROR >>>>>> kubectl create -f -: exit status 1
ERROR >>>>>> The ReplicationController "pachd" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Steps to reproduce:

1. `vagrant up --provision` using the script below:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "flixtech/kubernetes"

  config.vm.provision "shell", inline: <<-SHELL
    curl -o /tmp/pachctl.deb -L https://pachyderm.io/pachctl.deb && sudo dpkg -i /tmp/pachctl.deb
    pachctl deploy local
  SHELL
end

```

Here's the repository for the provider of the kubernetes box.
https://github.com/flix-tech/vagrant-kubernetes

This is a full featured Kubernetes install, so I would expect that it is supported.

**Comment by willis7** [comment]
Appears similar to [439](https://github.com/pachyderm/pachyderm/issues/439)

**Comment by jdoliner** [comment]
Hi @willis7, sorry you ran into this.
It appears the problems is that this method of deploying kubernetes creates a cluster that can't schedule privileged containers, Pachyderm can't work on such a cluster because the `pachd` container won't be able to spawn k8s jobs which is how it processes things. To get it working you just need to add a flag to the kubelet `--privileged=true`, it looks like the file you'll need to modify is this one: https://github.com/flix-tech/vagrant-kubernetes/blob/ff4673988b68a235ca5430fe8392db45d63657ca/conf/kubelet.service

I'm going to close this issue since there's nothing we can change about our code to make this work, but please feel free to keep using this thread for support if what I suggests doesn't fix the problem.

**Comment by willis7** [comment]
@jdoliner 

Unfortunately, it still doesn't work. I restarted the kubelet with the `--privileged=true` flag, as suggested, but it failed with invalid flag. After some digging I found that the [correct flag](https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/docker.md) was `--allow-privileged`. Even with this flag set I get the same error.

You can see below the kubelet is started with allow privileged set.

```
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-01-04 14:32:51 GMT; 19s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 3808 (hyperkube)
    Tasks: 12
   Memory: 36.7M
      CPU: 621ms
   CGroup: /system.slice/kubelet.service
           ├─3808 /usr/bin/hyperkube kubelet --logtostderr=true --kubeconfig=/etc/kubeconfig.yml --require-kubeconfig --hostname-override=10.10.0.2 --address=0.0.0.0 --api-servers=http://localhost:8080 --cluster-dns=10.0.0.10 --cluster-domain=k8s.local --allow-privileged
           └─3829 journalctl -k -f
```
Unfortunately, as I'm on a Windows machine, I cant go the Minikube route either because there's currently no `pachctl ` install for windows.

**Comment by jdoliner** [comment]
Hmm, unfortunately I don't really have an explanation for why that didn't work. Setting that flag is all we've ever had to do to get privileged containers running. If this is the only viable way to deploy k8s I'd recommend getting in touch with the package distributor or maybe the k8s team over in their dev channel.

You might also consider going to minikube route, you can `minikube ssh` to get onto the VM which should be an environment you can install pachctl in. I believe it's just an ubuntu machine under the hood so apt-get should work. If not it's possible to schedule an ubuntu container on k8s that will serve as a "jump box" from which you can run pachctl commands with `kubectl exec`. It's a little hacky but it should work.

Also you could just setup a normal ubuntu vm and install dockerized kubernetes on it. `make launch-kube` from the root of our repo will do this.
