### ISSUE TITLE
Incorrect commit sizes

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1253]
A couple users have reported an issue where commit sizes can be incorrect.  For instance, `list-commit` might say that a commit is empty, but you can see files in the commit via `list-file`.  If you run into this issue and your pipeline won't run (because it thinks the commit is empty), you can get around it by setting the `runEmpty` flag to `true` in your pipeline spec.

The issue is caused by the fact that currently `FinishCommit` and `PutFile` can race in such a way that commit sizes might be computed while data is in transit.  There isn't a simple way to solve this issue due to the lack of support for multi-document transactions in RethinkDB.

However, we are moving towards storing metadata in etcd (which supports transactions), so this issue should be solved in the near future.

**Comment by sjezewski** [comment]
stale
