### ISSUE TITLE
slack channel returning "no perms" on attempt to join

### ISSUE THREAD

**Issue by orangefuzzball** [pachyderm/pachyderm#1255]
Tried to get an invite to the pachyderm slack channel.  Enter email, click the button, get "no perms" erros.  Screenshopattached.

<img width="357" alt="screen shot 2017-01-06 at 1 20 05 pm" src="https://cloud.githubusercontent.com/assets/24723890/21733394/15a25c8a-d413-11e6-9a83-eafe1aa1c2e9.png">

**Comment by jdoliner** [comment]
Hey sorry you hit this, it looks like we might have hit our limit on Slack guests, or Slack might have pulled the credentials of the inviter bot. We should have this fixed by eod today.

**Comment by JoeyZwicker** [comment]
@orangefuzzball Ok I think this is fixed. Slack changed some permissioning requirements in the last update I guess -- invite bots need to be admins, but it seems to be working now. If you have any problems joining, you can also email me directly at joey@pachyderm.io and I'll manually send you an invite.
