### ISSUE TITLE
Document file sharding/delimiters and lack of ordering guarantees.

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1258]
We should document better how Pachyderm breaks files into block based on lines, json, or binary blobs (put-files) and how those will get distributed across parallel containers. The pipeline spec mostly covers it, but it's a bit obtuse and not very discoverable. 

Similarly, a user asked today about ordering guarantees when a file is broken up by line. There aren't any.

**Comment by sjezewski** [comment]
delimiters are gone in 1.4
