### ISSUE TITLE
Fix description of diffs in Git

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1261]
Ben Baker-Smith [7:59 AM] 
I'm curious about this line from the docs:

[7:59]  
> Just as in git, the state of each file (and therefore the entire data set) is constructed from the series of diffs that were made to modify that file.

[7:59]  
My understanding is that git is not diff based.

[8:00]  
Rather, it stores full representations of all files in a project, and a commit contains pointers to those blobs. Diffs are calculated by comparing complete versions of each file.

Ben Baker-Smith [8:11 AM] 
https://www.pachyderm.io/pfs.html

In docs and on website

**Comment by dwhitena** [comment]
https://github.com/pachyderm/pachyderm/pull/1263 addresses the docs portion of this.  I opened an issue https://github.com/pachyderm/www/issues/14 on `www` to fix the web portion.
