### ISSUE TITLE
Add "Production" section to docs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1269]
Some potential subsections that should be included:

- Permanent credentials
- Running Rethinkdb/etcd in a persistent way
- Managing logs
- Recovering from job failures
- Data management. i.e. deleting commits with incorrect data
- autoscaling
- Managing/organizing pipeline code and json specs between Git and Pachyderm
- upgrading/migrating pachyderm
- connecting (import/export) with various external data sources and infra
- measuring and optimizing performance
- collaboration among teams of data scientists
- general best practices

**Comment by JoeyZwicker** [comment]
Add section about scaling rethink and pachd pods. Should include that rethink needs one pv per pod.

**Comment by dwhitena** [comment]
Addressed partially here: https://github.com/pachyderm/pachyderm/pull/1967

**Comment by dwhitena** [comment]
@JoeyZwicker Are any of these things high priority for?  Many of them have been addressed and/or standardized.

**Comment by sjezewski** [comment]
Since there are partial fixes, and this is old, I'm gonna close it. We can open new issues for specific asks.
