### ISSUE TITLE
Multiple inputs example

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1276]
Lots of users ask about this one.  We should have a simple example/tutorial with multiple input repositories and how that works.

**Comment by ferrouswheel** [comment]
A trivial example is currently documented here: http://pachyderm.readthedocs.io/en/latest/reference/pipeline_spec.html#multiple-inputs

**Comment by dwhitena** [comment]
Added in the pipeline specification for now:

![image](https://user-images.githubusercontent.com/4524535/27450590-252ad414-575a-11e7-95c4-7aa94b5ab6bf.png)
