### ISSUE TITLE
System overload due to bursts of requests

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1278]
Currently, when a job fetches input files from PFS, it issues GetFile/ListFile requests in parallel.  This means that when a job launches, PFS might receive a large burst of requests.  In production, we seem to be seeing a situation where such bursts overload rethinkdb, causing it to respond extremely slowly, even possibly dropping requests.

There are four ways to solve this problem:

* Make jobs issue GetFile/ListFile sequentially.  This is probably the simplest fix, but it might impact job performance significantly if there are a large number of input files.
* Add rate-limiting to either client side or server side.  The tricky part will be to figure out a reasonable rate limit, since it can be affected by many factors such as machine capabilities, number of nodes, etc.
* Implement a `ListFileRecurse` API that returns all files under a directory, including those in subdirectories.  This means that each pod only has to issue `ListFileRecurse` once, as opposed to issuing many `ListFile` requests to traverse the input directory structure.
* Make `ListFile` fundamentally more efficient.  See #1086.  This is being worked on as part of the ongoing PFS refactor.

**Comment by sjezewski** [comment]
I believe we rate limit the getfiles (and @jdoliner is working on rate limiting the putfiles) for 1.3

I'm not sure if we retain the `sync` package code path in 1.4 -- if so, I believe this will be fixed once JD's PR lands.

**Comment by jdoliner** [comment]
Yup, we rate limits this now, closing.
