### ISSUE TITLE
Prevent pathological PutFile case

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1280]
This came up during the GRPC PR

GRPC 1.0 adds a `MaxMsgSize` to its server ... which means we can now go past that size. When that happens ... the server errs:

```
rpc error: code = 13 desc = grpc: received message length 25165898 exceeding the max size 25165824
```

But the client only sees a `io.EOF` suggesting that the server has just hung up.

On the `pathological_putfile` branch I have a failing test for this.

Going forward ... we should make sure the client's writers never write more than the size of the `MaxMsgSize` limit. Since (right now) that value is set in `src/server/pfs/server/server.go` we'll have to move that to the client (bcz of vendoring ... client code can _never_ import server code).

Right now the limit is set to 16MB so the only way you'll see this is if you:

- write a text file whose line that crosses a block boundary (the 8MB mark) is itself 16MB long
- write a bin file whose block is bigger than 24MB

**Comment by jdoliner** [comment]
I believe our `put file` code is now careful to not exceed this value. Feel free to reopen if you can repro this error with `put file`
