### ISSUE TITLE
kube-up.sh bugs, errors in AWS install 

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1283]
Various Kubernetes and AWS issues were identified by a user, and we likely need to update some things on our end and/or address possible issues with our AWS install:

"You link to the official Kubernetes guide for AWS from here: http://pachyderm.readthedocs.io/en/stable/deployment/deploying_on_the_cloud.html#amazon-web-services-aws

This simply does not work.

This bug has totally broken AWS setup for a while: https://github.com/kubernetes/kubernetes/issues/38290"

"The workaround is to set `export ETCD_QUORUM_READ=false` before running the Kubernetes install scripts.

Even once it does work, the `cluster/kube-up.sh` tooling is just awful.

It's basically designed to be managed from a single workstation, with lots of local credentials and SSH keys, instead of having the cluster managed in a way that multiple employees can share.

The whole thing is an ugly mess of shell scripts that just barely works.

So after roughly a week trying to get AWS Kubernetes to work reasonably and run Pachyderm in a way that our data analysts could turn the cluster on and off, I switched to Rancher."

**Comment by JoeyZwicker** [comment]
kube-up.sh seems to be deprecated by k8s in favor of [Kops](https://github.com/kubernetes/kops) and CoreOS tools [listed here](https://kubernetes.io/docs/getting-started-guides/aws/). We need to update our docs and test the easiest path (most likely kops)

**Comment by sjezewski** [comment]
Our aws.sh script is now in the docs
