### ISSUE TITLE
Update docs for more robust AWS deploy command

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1287]
If you omit the `AWS_TOKEN` you get an error from pachctl reporting that it has 6 args but expects 7

Instead we should wrap the AWS ID, TOKEN, and KEY params in double quotes. This is probably a good idea as well since the TOKEN can have some funny characters I believe.

**Comment by jdoliner** [comment]
I think a better idea would be to just update pachctl so it doesn't take a token by default, that would help coax people toward the better deployment path. We can add it back in as a flag. Quotes are fine if the funny characters actually cause problems, my experience has been that quotes aren't really necessary unless I want to pass an empty token.

**Comment by dwhitena** [comment]
This is fixed, right @sjezewski?

**Comment by sjezewski** [comment]
No ... we still list an empty token `" "` in the `pachctl deploy amazon ...` command:

http://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html

**Comment by sjezewski** [comment]
This is fixed. We use named args now.
