### ISSUE TITLE
Cannot clean up orphaned job

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pachyderm/pachyderm#1289]
Following the [opencv tutorial](https://github.com/pachyderm/pachyderm/tree/master/doc/examples/opencv), I first tried to `create-pipeline` with the file provided in the repo, to see what would happen, even though instructions say to change the image.  I see the pipeline was stuck in the pulling state, and `kubectl` shows the pod in an `ImagePullBackOff` with an error along the lines of not being able to find an image in Docker Hub `library/opencv`.  Makes sense.

I found the `opencv` image made by the person who last commited to the README, and decided to use their Docker image rather than building and distributing my own.  That worked fine, but it left the old job that was bound to fail sitting around forever:

```
$ pachctl list-job
ID                                 OUTPUT COMMIT                              STARTED             DURATION            STATE
db836ed00a62e660240dd83ce211db2b   edges/2b54c9fae81847dcaed353237169d65b/0   11 minutes ago      2 minutes           success
245d076e2e8ea40dcece42c9584f1a1d   edges/9c2f2e8aa98a4208a361b93a4e05bd3e/0   14 minutes ago      -                   pulling
```

I even deleted the job from Kubernetes directly, but the job still shows up in Pachyderm.  I can't delete the job in Pachyderm, because:

```
$ pachctl delete-job 245d076e2e8ea40dcece42c9584f1a1d
error from DeleteJob: cannot delete job (245d076e2e8ea40dcece42c9584f1a1d) that belongs to a pipeline (edges)
```

I had to `delete-all`.

Would this have eventually cleaned itself up?  Even if I hadn't manually deleted the job in Kubernetes, would it still eventually clean itself up?

**Comment by jdoliner** [comment]
Hi @Amit-PivotalLabs pachyderm won't let you delete a job that's part of a pipeline, you can however delete the whole pipeline which will delete the job with it.

Unfortunately this case doesn't get cleaned up naturally when the job is stuck in image pulling. Once you delete the k8s job then it's really just a record in the database so it should be fairly benign. However it's definitely annoying to have those jobs lying around so we should be able to figure out a way to clean them up. Or at least make it so `delete-job` can work in those cases.
