### ISSUE TITLE
Expose logs per datum

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1298]
A user is going to want/need access to user logs per run of a datum.

E.g. if the data is very lumpy and one datum processing fails, I want to know what the inputs are, so that I can a) reproduce it locally b) understand if the input data is abnormal

Discussed this w JD. This will be easy to do once the datum refactor is in place. This would also solve the debug issues I'm running into around debugging a job's intermediate (failing) steps.

**Comment by derekchiang** [comment]
Done in #1272.  `get-logs` accepts a `--inputs` flag that can be used to specify filepaths.
