### ISSUE TITLE
Explain need for CMD in job specification

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1301]
kalugny [4:09 AM] 
Hi again, I have another question I couldn't find the answer to in the docs - What happens if I don't specify a `cmd` in the pipeline file? My expectation was that the image's `ENTRYPOINT` will just run but that's not what happened.

svanharmelen [4:15 AM] 
joined #users

dwhitena [9:26 AM] 
@kalugny  Thanks for the question.  I'm checking on this.  I know that the `cmd` is passed to the docker run invocation, but I haven't tried it myself without a `cmd`.  If it happens that we require a command for proper execution, this should be explicit in the docs.  I will get to the bottom up it and then open a ticket to make sure we explain this better in the docs.

[9:26]  
Welcome @svanharmelen!

svanharmelen [9:28 AM] 
Thanks @dwhitena :slightly_smiling_face:

kalugny [9:30 AM] 
Thanks @dwhitena. As far as I know, a docker should be able to run without a `CMD` as long as it has an `ENTRYPOINT`

dwhitena [9:31 AM] 
Yes, that was my understanding as well @kalugny.  Just checking how we set things up to see if there are any caveats.

[9:31]  
I might need to ask someone as well, what the strategy is in that respect.

sean [2:04 PM] 
hey there @kalugny

[2:04]  
right now we don't support falling back to a `CMD` as an entry point

[2:04]  
the reason is

[2:04]  
we have to do some setup before and after your code runs

[2:04]  
to be able to provide you the input data

[2:04]  
and upload the output data

[2:05]  
so for now you need to specify the `cmd` in the pipeline file

**Comment by jdoliner** [comment]
This is because we actually run a shim process between that sets up he filesystem state before the user code runs. Is it possible to detect the `ENTRYPOINT` and `CMD` from within a container? If so I think we could get this working, otherwise it might be kinda hard.

**Comment by davidgasquez** [comment]
I'm sure you've already looked at it but just wanted to share in case that's helpful. Would be possible to do something like Kubernetes does with the  [container commands](https://kubernetes.io/docs/concepts/configuration/container-command-args/)? 

Disclaimer: _Not sure how they do and if it's compatible with Pachyderm_ 😉

**Comment by jdoliner** [comment]
@davidgasquez that's unfortunately the same thing we were talking about above. We can't use the entrypoint cmd because we need to run our own wrapper command which pulls in the data and gates the user code.

**Comment by sjezewski** [comment]
I believe our requirement for the wrapper is no longer valid. I believe there was discussion (and maybe an issue if I can find it) about removing this requirement in the pipeline spec.

**Comment by jdoliner** [comment]
Cmd can now be left blank, in which case the `ENTRYPOINT` if the container will be used instead.
