### ISSUE TITLE
Switch src/pkg/discovery to docker/libkv?

### ISSUE THREAD

**Issue by peter-edge** [pachyderm/pachyderm#132]
https://github.com/docker/libkv

It needs some quick investigation because I'm not sure if libkv has the concept of directories (it might just say say so in the README, I really haven't even read that more than skimming it), but this could be a free win: etcd -> etcd or consul

**Comment by jdoliner** [comment]
Just took a look, looks like it has a concept of directories and we could totally implement our api using it.

It's also so bleeding edge that it doesn't have a version number yet, but it's pretty simple and clearly meant to do exactly what we want so we'd probably be fine using it.

**Comment by peter-edge** [comment]
I was looking at https://godoc.org/github.com/docker/libkv/store#Store and I was thinking we should just replace the discovery Client with this soon - our fake implementation can be done with their boltdb implementation. The biggest changes I can see would be GetAll would be replaced with List, CheckAndSet and CheckAndDelete would be replaced with AtomicPut and AtomicDelete, and I'm not sure of the equivalent for the Hold function. But this would mean we could delete the discovery package, which would be really nice I think.

**Comment by mattnenterprise** [comment]
Are you still looking to switch to using libkv? If you are I would like to have a go at it.

**Comment by jdoliner** [comment]
Hmm, probably still looking to do this long term but in the lead up to to 0.10 I'd prefer not to introduce any big changes that aren't critical.

**Comment by sjezewski** [comment]
We're considering a different discovery scheme w a refactor to our pfs module. So - closing this issue.
