### ISSUE TITLE
Refactor deploy commands with Minio combos

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1331]
# General thoughts

Now that we have support for Minio, we can deploy to any cloud or on premises with any S3 compatible object store (Minio or otherwise).  As such, our existing deploy commands are somewhat outdated as they only represent pure AWS, Google, etc. deploys.  

# Proposal

## Deploy commands

Refactor the deploy commands with more of a separation between the machine environment and the storage backend.  That way we could deploy to AWS+S3, AWS+Minio, Google+GFS, Google+S3, Google+GlusterFS, etc.  Not that all of those would be necessarily advisable out of the gate, but we would have access to the full list of combinations.

## Clients

Because Minio will connect to any S3 compatible object store (including S3 itself), there is really no need to use the aws sdk only for S3.  Especially given that the minio client is much lighter weight and focused on the object store piece.  I also propose that we use the Minio client for both AWS S3 and for any other S3 compatible object store.  That way, there is no "S3," "Minio," and "S3 compatible" confusion and separation in the commands.  It would simply be "S3" or "S3 compatible."

# Details

I propose commands like this:

default local deploy (currently `pachctl deploy local`):
```
pachctl deploy
```

Pure Google cloud deploy (currently `pachctl deploy google`):
```
pachctl deploy --cloud google --object-store gfs
```

Google cloud deploy + S3 compatible object store (no current equivalent).  This could be Minio, S3, or any other object store with an S3 compatible API:
```
pachctl deploy --cloud google --object-store s3 <id> <secret> ...
```

Pure AWS cloud deploy (currently `pachctl deploy aws`):
```
pachctl deploy --cloud aws --object-store s3 <id> <secret> ...
```

AWS cloud deploy + other S3 compatible object store (no current equivalent):
```
pachctl deploy --cloud aws --object-store s3 <id> <secret> ...
```

and etc...

**Comment by JoeyZwicker** [comment]
Is there a reason `pachctl deploy --cloud google --object-store gfs` is there twice? Just wondering if there was initially multiple variations you where thinking of here?

My guess is that you meant GCS (Google Cloud Storage, their S3 equivalent) which is different from GlusterFS, right?

**Comment by dwhitena** [comment]
Yes, @JoeyZwicker.  Corrected.

**Comment by jdoliner** [comment]
What's the meaning of `--cloud google` if it doesn't set the object store to `gcs`? I'm assuming it would have to be setting the disk types that we use to back etcd and rethink but in that case I think it'd be better to just be explicit and say `--persistent-disk ebs` or something like that. It seems to me that there should be 2 different arguments `--object-store` and `--persistent-disk` since those are the 2 pieces that users can swap out.

Also, if at all possible, I think it'd be good to keep around `pachctl deploy google ...` and friends as quick aliases for deployment on a single cloud. For one thing those already exist, people are using them and it's always better not to break people's code if you can avoid it. Second it seems like those will still be the most common usage patterns so it'll be good to have quick aliases for them going forward.

**Comment by dwhitena** [comment]
@jdoliner Great points.  I agree that `--persistent-disk` and `--object-store` are the best ways to describe the combinations.  Also, I agree that keeping the other defaults is useful.  I want to revise the options as:

default local deploy (currently `pachctl deploy local`):
```
pachctl deploy local
```

Pure Google cloud deploy (currently `pachctl deploy google`):
```
pachctl deploy google
pachctl deploy --persistent-disk google-disk --object-store gcs
```
(these would be equivalent)

Google cloud persistent disk + S3 compatible object store (no current equivalent). This could be Minio, S3, or any other object store with an S3 compatible API:
```
pachctl deploy --persistent-disk google-disk --object-store s3 <id> <secret> ...
```

Pure AWS cloud deploy (currently `pachctl deploy aws`):
```
pachctl deploy aws
pachctl deploy --persistent-disk aws-ebs --object-store s3 <id> <secret> ...
```

AWS cloud deploy + other S3 compatible object store (no current equivalent):
```
pachctl deploy --persistent-disk aws-ebs --object-store s3 <id> <secret> ...
```

and etc...

**Comment by dwhitena** [comment]
Thinking that to keep the structure consistent and more readable we add `custom`:

default local deploy (currently `pachctl deploy local`):
```
pachctl deploy local
```

Pure Google cloud deploy (currently `pachctl deploy google`):
```
pachctl deploy google
pachctl deploy custom --persistent-disk google-disk --object-store gcs
```
(these would be equivalent)

Google cloud persistent disk + S3 compatible object store (no current equivalent). This could be Minio, S3, or any other object store with an S3 compatible API:
```
pachctl deploy custom --persistent-disk google-disk --object-store s3 <id> <secret> ...
```

Pure AWS cloud deploy (currently `pachctl deploy aws`):
```
pachctl deploy aws
pachctl deploy custom --persistent-disk aws-ebs --object-store s3 <id> <secret> ...
```

AWS cloud deploy + other S3 compatible object store (no current equivalent):
```
pachctl deploy custom --persistent-disk aws-ebs --object-store s3 <id> <secret> ...
```

and etc...

**Comment by dwhitena** [comment]
This has been fixed by https://github.com/pachyderm/pachyderm/pull/1371

**Comment by jdoliner** [comment]
@dwhitena so anything left here or close?

**Comment by sjezewski** [comment]
stale
