### ISSUE TITLE
Remove temporary AWS cred option

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1345]
joey [3:59]  
also, it seems there was a little confusion is the permanent creds stuff in the AWs docs. Any chance while you’re at it you cna make a PR to update that and be specific about using `" "` for the permanent token, etc

[3:59]  
honestly, we might want to push people away from using the expiring tokens cuz that’s causing constant problems

dwhitena [4:00 PM] 
Yes, I can do that @joey.  Is that something we might just want to remove, and only address if asked? (edited)

joey [4:00 PM] 
i’m not sure honestly. I think having both is fine, but we should make perm creds the go-to

[4:01]  
ping me in the PR and I can add some edits too

dwhitena [4:01 PM] 
Sounds good.

sean [4:02 PM] 
my 2 cents - just remove the temp token docs

[4:02]  
and if we do that we should probably remove it from the command line

[4:02]  
bcz providing the blank arg is confusing to folks

joey [4:03 PM] 
if there’s not a real reason people would want temp creds, and i cant think of one unless its a security thing, I agree with sean

dwhitena [4:04 PM] 
I agree as well.  Presenting unnecessary options should be avoided, especially if they are causing issues.

**Comment by jdoliner** [comment]
I think we should probably keep the functionality but as an optional flag rather than as a required one. Docs should clearly present permanent credentials as the default option.

**Comment by JoeyZwicker** [comment]
Just had another user hit this. For some reason I thought we had fixed this
already, but the docs still have the temp creds. Adding to the docs docket.
@dwhitena, can you make sure this is fixed correctly in the new aws
deployment docs? We don't talk about creds anymore since it's just a kops
script so just wanted to make sure it sets up permanent creds.

**Comment by dwhitena** [comment]
@JoeyZwicker Already fixed in the 1.4 docs branch

**Comment by dwhitena** [comment]
Closing.  Fixed.
