### ISSUE TITLE
Update release artifact hosting

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1350]
We should use an s3 bucket / custom subdomain for the binaries we host

Right now they're part of the `www` repo which makes the history / updating it bloated.

We don't actually need the files versioned (we have the code + a tag so we can always rebuild).

**Comment by jdoliner** [comment]
Github also has the downloads feature which might be an easier way to accomplish this. Not really experienced with it but my intuition is that it's going to be a little more user friendly than s3 bucket.
