### ISSUE TITLE
Pachyderm cluster breaks if too many jobs start at once

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1352]
One of the customers in our user's channel (Josiah) is being blocked by this. He creates a handful of commits in a small cluster, which starts several jobs. If those job pods are all scheduled together, then they might consume all of the memory of the node they're scheduled on, and then the kernel OOM killer might decide to kill the kubelet. This causes the node that's hosting the pods to die, which leaves all open commits and unfinished jobs in an inconsistent state.

It seems like the easiest way to avoid this is to set a memory request for job pods (details [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md) and [here](https://kubernetes.io/docs/user-guide/compute-resources/)). I think this would mean that if a job pod exceeds its request, it gets killed first, hopefully before the kubelet.

**Comment by sjezewski** [comment]
stale
