### ISSUE TITLE
sort the results from "pachctl list-*" commands

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#1354]
I can't seem to find related topics, so hope this is not a duplicate.

Taking repos as an example: as repos get larger, it makes harder to spot the exact repo we are interested in. It'd be great to have additional command line arguments that facilitate sorting the list. Possibly by `CREATED` and by `SIZE`, and both increasing and decreasing.

Thank you

**Comment by JoeyZwicker** [comment]
Hi @willguxy. We can definitely add some convenience flags like this. After v1.4 lands, we plan to do a bunch small usability polishes like this so thanks for pointing that out. If you have others please open issues for them too. :)

In the meantime, you can certainly use either unix or Go sorting functions to accomplish this in the short-term. You can pipe pachctl list-repo to unix sort or use Go's sorting function from the Go client.

**Comment by sjezewski** [comment]
stale
