### ISSUE TITLE
Nightly cloud provider integration test

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1379]
As part of a nightly build, we should test our deployment scripts, and that they actually work for deploying to each cloud provider.

Matt is running into a situation where there's a big merge conflict on the `assets.go` and it's hard to navigate partly because we don't have test coverage of the result of that codepath.

**Comment by sjezewski** [comment]
We recently ran into a new case.

It seems like a bug snuck in around how we provision volumes for rethink in the non stateful set deployment. (Part of this is k8s changing the default behavior w 1.5). If we had a test that deployed to AWS, created some jobs/output, tore down the cluster, redeployed pach cluster to check that the state persists, we would've caught this error. Now that we have a bead on the issue, we can write a simpler test, but it would still need to be run on a cloud deployment.

**Comment by sjezewski** [comment]
Here's another case we should have coverage for:

https://github.com/pachyderm/pachyderm/issues/1423

**Comment by sjezewski** [comment]
We also want to have coverage of our object stores as described in #906, #648

**Comment by derekchiang** [comment]
We know run integration tests on AWS for every PR.
