### ISSUE TITLE
Standardize/refactor S3 client usage

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1381]
Because the now implemented Minio client will connect to any S3 compatible object store (including S3 itself), there is really no need to use the aws sdk only for S3. Especially given that the minio client is much lighter weight and focused on the object store piece. I also propose that we use the Minio client for both AWS S3 and for any other S3 compatible object store. That way, there is no "S3," "Minio," and "S3 compatible" confusion and separation in the commands. It would simply be "S3."

**Comment by sjezewski** [comment]
One thing that came up recently is the go s3 client does some fancy things like read the EC2 metadata to get the IAM role of the instance the code is running on and using those credentials for s3 access. This has become an important use case for customer installations. I'm not sure if the minio client does that.

That plus the timestamp on this issue, I'm marking it as stale.
