### ISSUE TITLE
v1.4 Docs Checklist

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1383]
Checklist for v1.4 and other docs changes. Working branch: https://github.com/pachyderm/pachyderm/tree/v1.4-docs

### Intro to Pachyderm
Getting Started
Tutorial (should we change to OpenCV at some point?)
Examples
OpenCV Demo
Troubleshooting

### Deployment
```
Deploy Pachyderm
├── Google Cloud Platform
|   ├── Prerequisites (include permissions settings)
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── Amazon Web Services
|   ├── Prerequisites
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── Azure
|   ├── Prerequisites
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── OpenShift
|   └──  Details
├── Custom Object Stores
|   ├── Prerequisites
|   └── S3 Compatible Object Stores
├── On Premises
|   └── Details
├── Migrations
|   └── Details
├── Migrations/secrets?
```

### Analyze Your Data
Ingress
```
├── Pipelines
|   └── creating pipelines
|   └── pipeline spec
|   └── parallelizing analysis code
|             └── parallelism 
|             └── sharding
|   └── Environment variables/secrets
|   └── Updating pipelines
```
Viewing results
Viewing job/pod status
Egress
Services
Investigating Logs
The complete data science workflow

### Production
Permissions
Deployment
Using a private registry
Scaling your infra
Monitoring infra
Logging Infra
Cluster Maintenance
Collaboration
Best Practices (collaboration
Common errors/troubleshooting (OOM, disks full, permissions, etc)

### Advanced Features
Provenance
Incrementality
Composing Piplines

### Misc
FAQ
Examples
PFS
PPS
Go Client
Python Client
Scala Client
Metrics
Contributing

### Examples
Logs (fruit stand)
Image processing (OpenCV)
ML
Distr Joins
Web Scraping
SQL DB ingress/egress

## Other ToDo's
Blog links
Website updates (will list out in separate issue)
Github Readme
Triage GH issues

**Comment by dwhitena** [comment]
@JoeyZwicker here are some structure suggestions based on my digging around in other people's docs:

```
Getting Started
├── Local Installation
└── Beginner Tutorial
Pachyderm Fundamentals
├── Getting data into Pachyderm
├── Creating Analysis Pipelines
├── Getting data out of Pachyderm
├── Updating Pipelines
└── Serving data from Pachyderm
Full Examples
└── Examples
FAQ
└── FAQ
Deploy Pachyderm
├── Google Cloud Platform
|   ├── Prerequisites
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── Amazon Web Services
|   ├── Prerequisites
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── Azure
|   ├── Prerequisites
|   ├── Deploy Kubernetes
|   └── Deploy Pachyderm
├── OpenShift
|   └──  Details
├── Custom Object Stores
|   ├── Prerequisites
|   └── S3 Compatible Object Stores
├── On Premises
|   └── Details
├── Migrations
|   └── Details
Pachyderm Cookbook
├── Tracking Analysis Provenance
├── Leveraging Incrementality
├── Composing Pipelines
├── Interacting with Databases
├── Pachyderm Clients
└── ML workflows
Scaling Pachyderm, Best Practices
├── Best Practices
├── Scaling pachd/etcd
├── Logging and Monitoring
└── Cluster Maintenance 
Reference
├── Pipeline Specification
├── Data Versioning
├── Data Pipelining
└── Pachctl CLI Tool
```

**Comment by dwhitena** [comment]
@JoeyZwicker regarding best practices, do you have a good list of things that should be there.  These are the things I'm seeing frequently:

- scaling k8s volumes
- correcting diskpressure issues
- scaling pachd
- dealing with large files
- dealing with many small files
- organizing repositories
- composing pipelines
- docker image size

I'm sure there is more.  Just wanted to get these down somewhere.  Please add what you think needs to be there.

**Comment by dwhitena** [comment]
A new draft of our deployment docs is ready.  Note:

- I'm assuming @sjezewski's aws deploy script gets merged (we may have to adjust that link)
- I didn't really change the content on the migrations page.

**Comment by JoeyZwicker** [comment]
#1439 We should change the beginner tutorial

**Comment by dwhitena** [comment]
@JoeyZwicker restructured the index here: https://github.com/pachyderm/pachyderm/blob/v1.4-docs/doc/index.rst

Note that I added a bunch of placeholders as `_PLACEHOLDER`.  In all of those cases, the doc doesn't exist or needs to be moved, and, in a few cases, we need to create the respective folder.  I think this will help our organization a lot.  Let me know your thought and feel free to tweak as we go.  I will be pulling often from this branch.

**Comment by JoeyZwicker** [comment]
Looks good. We should still make the folder structure in the repo match,
but i like how well this organizes things.

On Mon, Mar 20, 2017 at 10:55 AM, Daniel Whitenack <notifications@github.com

**Comment by dwhitena** [comment]
@JoeyZwicker Yep, as we tackle each section we can make the folders. We shouldn't collide this way at least.

**Comment by JoeyZwicker** [comment]
Note to self: We should check to make sure all screenshots are v1.4. The deployment docs for instance still show rethink pods. Easy to fix.

**Comment by dwhitena** [comment]
Yep, good call @JoeyZwicker.  Adding to the list.  I made some rearrangements today.  I'm going to work through the "fundamentals" section, then move on to the other things.  I'm still letting you take beginner tutorial and getting started, unless you say different.

**Comment by JoeyZwicker** [comment]
yup I'm on them.

On Wed, Mar 22, 2017 at 10:31 AM, Daniel Whitenack <notifications@github.com

**Comment by JoeyZwicker** [comment]
Monday TODO:
- release blog post
- fundamentals PR
- Migration PR
- merge in @sjezewski Kops script
- Update dynamic provisioning and add minio flag (test later)
- Fix PLACEHOLDER links
-  (non blocking but important) fundamentals/distributed computation (parallelism and glob patterns)

**Comment by gabrielgrant** [comment]
Hey, just talked with @JoeyZwicker about adding a "joins" page under cookbook that just links to the blog post: https://medium.com/pachyderm-data/easy-distributed-joins-with-pachyderm-8307bab8a761

**Comment by JoeyZwicker** [comment]
@dwhitena Add to Monday TODO's above:

- Update GH README.md for the pachyderm repo. (at least check that everything there is correct and links to the right places)
-merge examples -- we're alraedy on it, but didn't make our list above

**Comment by dwhitena** [comment]
Restructure is done, and remaining issues are tracked here: https://github.com/pachyderm/pachyderm/issues/1869
