### ISSUE TITLE
Minio backend bug in getting files

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1385]
# Behavior

Pachyderm backed by Minio in Google Cloud (and possibly elsewhere) is able to:

- create repositories
- put data into repositories

However, when you try to get versioned data out of PFS, the files always return blank, even though you can see that the file content was written to the object store (either via the Minio browser or via `pachctl list-file` and `pachctl list-repo`).

# To Recreate

## Deploy Minio

- spin up a VM on GCE and deploy Minio via:

```
docker run -p 9000:9000 minio/minio server /export
```

- get the Minio creds via

```
docker logs <container id>
```

## Deploy k8s

- set up the environment:

```
CLUSTER_NAME=pach-cluster
GCP_ZONE=us-west1-a
gcloud config set compute/zone ${GCP_ZONE}
gcloud config set container/cluster ${CLUSTER_NAME}
```

- create the k8s cluster

```
gcloud container clusters create ${CLUSTER_NAME} --scopes storage-rw
```

- update kubectl 

```
gcloud container clusters get-credentials ${CLUSTER_NAME}
```

## Deploy Pachyderm backed by Minio

- create a persistent disk:

```
STORAGE_NAME=pach-minio-disk
STORAGE_SIZE="10"
gcloud compute disks create --size=${STORAGE_SIZE}GB ${STORAGE_NAME}
```

- deploy pachyderm backed by minio (using pachctl 1.3.12)

```
pachctl deploy custom --persistent-disk google --object-store s3 ${STORAGE_NAME} ${STORAGE_SIZE} <minio bucket> <minio id> <minio secret> <public ip of minio VM>:9000
```

- once pachyderm is up, port-forward

```
pachctl port-forward &
```

## Put some data in PFS and try to get it back

1. create a repo in Pachyderm

```
➔ pachctl create-repo testminio
➔ pachctl list-repo
NAME                CREATED             SIZE                
testminio           11 seconds ago      0 B
```

2. push data to the repo (in this case just the pachyderm README.md)

```
➔ pachctl put-file testminio master blah -c -f README.md 
➔ pachctl list-repo
NAME                CREATED              SIZE                
testminio           About a minute ago   9.92 KiB
```

3. list the file to make sure it was written with non-zero size

```
➔ pachctl list-file testminio master 
NAME                TYPE                MODIFIED            LAST_COMMIT_MODIFIED   SIZE                
/blah               file                45 seconds ago      master/0               4.96 KiB
```

4. examine the file in the Minio Browser to see it has content

![image](https://cloud.githubusercontent.com/assets/4524535/23716170/3a256312-03fd-11e7-8957-90b9a565e3e0.png)

5. try to get the file

```
➔ pachctl get-file testminio master /blah
➔ 
```

(this returns without error much return empty, where we would expect to get the content)

6. you can also use `pachctl mount` to mount PFS locally and browse the fs.  This also show blank files, although we know the content was written to the object store.

# Thoughts

- For some reason everything returned when getting files is empty.  Maybe a bug in the Minio client get functionality?

- The Minio client works at least for putting files.  Is there something different about getting files?

**Comment by harshavardhana** [comment]
Taking a look @dwhitena
