### ISSUE TITLE
Upgrade worker logs

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1390]
Chatted w Matt / Derek / Gabriel about the existing logging plan for workers.

Without getting into implementation details, the goals of that type of logging were to enable:

- easy provenance (getting the logs for a specific datum)
- easy access to logs (seeing the whole log stdout for that run)

However, we agreed that we need a logging service to do more than that. Specifically these goals are:

- including metadata for debugging
- enable discovery (filtering, search) of logs

These goals are _very_ important for our debugging efforts. 

e.g. If a user's job ran on a specific datum and seems pathological (is eating mem or cpu or taking down a pod) I want to know which worker it was running on, which pod that worker was running on, the timestamp, and the log line. And I want to be able to search / filter based on these fields.

**Comment by sjezewski** [comment]
Matt and I discussed implementation a bit. This should be pretty straightforward.

The worker already captures the stdout of the user's code.

To hook in a k8s log aggregator, we need to write the stdout for the pod.

So, we'll basically be a Tee writer (one output to block store, one to pod stdout), and the one that gets written to stdout will write in the format the log aggregator expects (e.g. statsd wants json) with the metadata fields we want (timestamp, level, workerID, datumID or hash, message/user std out line).

This also has the advantage that we can output more data to the log aggregator that would be helpful for debugging. E.g. While debugging its often helpful to see exactly what part of the input is provided for this run ... so in this case print the datum ... the list of input files.

**Comment by jdoliner** [comment]
I believe we now have everything discussed in this issue including a logging stack provided by `make logging`
