### ISSUE TITLE
pachctl: download a directory within a repo

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1396]
There should be an easy way to download a directory from a repo via `pachctl`.  Think `git clone` except that it works for subdirectories as well.

Right now, to get a directory, the user has to basically write a script that uses `list-file` and `get-file` repeatedly to manually traverse the file hierarchy.

Note that there already exists a way to clone a repo/directory programmatically in Golang, through the `sync` pacakge.

**Comment by jdoliner** [comment]
I like this idea, should be pretty simple given the existence of the sync code.

**Comment by jdoliner** [comment]
This is implemented as `get file --recursive`.
