### ISSUE TITLE
Using nvidia-docker and pachyderm

### ISSUE THREAD

**Issue by brollb** [pachyderm/pachyderm#1401]
Is there any information about using nvidia-docker in pachyderm (to provide GPU access to the docker images)? Would this be something that would be configured in pachyderm or should this be set in kubernetes somehow?

**Comment by sjezewski** [comment]
Hi there!

This is actually something we're actively looking into. I'll provide an update here once we have a PR that addresses this feature.

This will be configured in a pachyderm pipeline manifest, but will rely on the underlying k8s features that enable this. K8s just added support for this in 1.6.0, which is still in beta.

**Comment by sjezewski** [comment]
Nvidia GPUs + Tensorflow support is in alpha ... you can read more about it here:

http://docs.pachyderm.io/en/latest/cookbook/tensorflow_gpu.html?highlight=nvidia

Note ... it's only been tested on a deployment using kops on AWS.

**Comment by brollb** [comment]
This is awesome - thanks!

**Comment by gabrielgrant** [comment]
For anyone coming across this issue now, you can find details on using GPUs with Pachyderm here: http://docs.pachyderm.io/en/latest/cookbook/gpus.html
