### ISSUE TITLE
Passing no branch name/parent commit id with `put-file -c` interprets the pfs path as commit id

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1417]
```
$ pachctl put-file test_repo_1 /pics/ -c -f /tmp/my-image.png
commit /pics/ not found in repo test_repo_1
```

In talking with @JoeyZwicker, sounds like this should just work (same as starting a commit with no branch/parent explicitly specified), but I think the parsing could at least be fixed to show a more useful error (too few arguments)

**Comment by jdoliner** [comment]
How can this give a too few arguments error when, exactly the same command with `master` in place of `/pics/` works? The branch parameter isn't optional, so like with any non-optional positional argument if you omit it the parser has no magical way of knowing that you've skipped an argument it just reads strings and interprets them as the arguments it's supposed to. This error message is a completely reasonable thing to return if someone passes a commit that doesn't exist as a commit argument.

**Comment by gabrielgrant** [comment]
Ah, ok. Usage for `put-file` implies the `path/to/file/in/pfs` is a mandatory field (meaning it should fail with `master` too):

```
Usage:
  pachctl put-file repo-name commit-id path/to/file/in/pfs [flags]
```

But seems like that's just a doc bug. Filed as #1429
