### ISSUE TITLE
delete-commit should work on cancelled commits

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1418]
This specific error case is only relevant for 1.3 users.

Had a user hit this today. 
```
I noticed this when I was running `A -> B -> C` where ABC are repos: the first pipeline failed, and then I committed some data to B directly. I was expecting `B -> C` would still run, but it was not triggered automatically. Thinking it's related to the failed job in `A -> B`?
```

B->C didn't run because repo B had a cancelled commit so the manual commit he made was also cancelled. There was basically no way for the user to recover the branch he was on in Repo B. Rerun-pipeline only works if it was a transient error. Update-pipeline would work if it was a code error. How would they recover this if it was bad input data in v1.3? In v1.4 you can just start a new commit, delete the bad files and that's fine -- plus there are no more cancelled commits.

**Comment by jdoliner** [comment]
I'm pretty sure `delete-commit` does work on cancelled commits in 1.3. Also it seems like he could just delete the upstream commits (which aren't cancelled) and then call `rerun-pipeline`, or delete the downstream commits to get the same effect.

**Comment by JoeyZwicker** [comment]
@derekchiang didn't seem to think it worked on cancelled commits. I thought delete-commit only worked on open commits, so what do you mean by "Also it seems like he could just delete the upstream commits (which aren't cancelled) and then call rerun-pipeline, or delete the downstream commits to get the same effect."?

**Comment by jdoliner** [comment]
We no longer have cancelled commits and have #1586 for tracking delete-commit in 1.4. Closing.
