### ISSUE TITLE
`Start-commit <repo> <branch>`should create the branch if it doesn't exist

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1422]
My understanding of the reasoning for -b is that if a user mistypes the branch name then they'll create a new branch instead of creating a commit on an existing branch. 

I don't think it makes sense to try to be typo-proof here. If a branch it accidentally created, its not like any pipelines are triggered or anything bad happens -- you can delete it and do the right thing when you realize your mistake. 

The fact that start-commit is a different command whether you're creating the first commit on a branch or later commits is a bit weird. Another argument to remove -b is that `put-file -c` current creates a branch if it doesn't exist (and I think we want to keep that functionality). I can't think of a reasonable explanation why `-c` its ok, but for start-commit its not. It should probably work for both.

**Comment by jdoliner** [comment]
This is fixed in 1.4
