### ISSUE TITLE
Object storage rate limiting

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1424]
In cases where there are a lot of input files, we occasionally see AWS rate limiting. Unfortunately, it's not immediately clear to the user when this happens, because the error message is not descriptive.

This can happen during a `put-file` from an s3 bucket ... in which case it looks like we eventually succeed:

```
time="2017-03-14T20:10:50Z" level=info msg="Error reading; retrying in 38.766825003s: obj.RetryError{Err:\"read tcp 100.96.1.2:50436->54.231.169.1:443: read: connection reset by peer\", TimeTillNextRetry:\"38.766825003s\", BytesProcessed:0}" 
2017-03-14T20:11:29Z INFO  protorpclog.Call 
{
    "duration": "324.251298190s",
    "method": "PutBlock",
    "response": "block_ref:<block:<hash:\"wvMOFgnVB_FkwKn1v7pHVHZ2yvw17Fz6tr4JSmh6lJoU0lG0By9MRKIOYxWHsqrbcmTPUYXcewJK_gCg2xdZ3Q==\" > range:<upper:344720 > > ",
    "service": "pfs.BlockAPI.Obj"
}
2017-03-14T20:11:29Z INFO  protorpclog.Call {"service":"pfs.API","method":"putFileObj","request":"file:\u003cpath:\"human/old_data/human_000008387.jpg\" \u003e file_type:FILE_TYPE_REGULAR url:\"human/old_data/human_000008387.jpg\" recursive:true ","duration":"324.361394595s"}
```

Or it can happen in the input / download phase of a job pod:

```
17-03-08[17:02:04]:disk-full:0$kubectl logs e7269c928b541c415061f835a6727b94-ph2jb 
read tcp 100.96.2.4:43608->52.218.144.9:443: read: connection reset by peer
```

In which case it seems to kill the pod. 

---

Tactically, decreasing the streaming semaphore to 50 or 25, has alleviated this problem for me. (I'm working on a 20Gb data set w ~210k files)

Some other things we can try:

- making sure the job download code retries / backs off (like the putfile does)
- exposing the streaming semaphore size as a pachd / jobshim flag
- having a grpc connection pool & multiple pachd's to 'spread out' the throttling ... however I'm not sure that will help based on my reading of [some aws docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html)
- changing how we prefix/store the keys in s3 to optimize reads
- hooking in cloudfront to accelerate gets (we're immutable ... so that would work well for us)

**Comment by derekchiang** [comment]
The challenging part about rate limiting here is that we don't know what the rate limit is.  S3 (and other object stores) for us is essentially a black box.  It adjusts its own rate limit internally.

Therefore, any rate limit that we enforce will never be perfect; it will either be too high in which case it's useless, or it's too low in which case it hurts our performance.

So I think the thing to do here is just to tighten our internal retry mechanism.  That is, we make sure to catch all errors caused by the rate limiting and retry the operations via exponential backoff.  The goal is to ensure that a job never fails purely due to rate limiting.

**Comment by derekchiang** [comment]
Discussed offline with @jdoliner and @sjezewski.  We agreed that we shouldn't impose any internal rate limit, for the reasons listed above.  Rather, we should capture ratelimit-related errors at the worker layer when download/upload happens, and retry those operations in an exponential backoff loop.

**Comment by derekchiang** [comment]
@sjezewski has started using CloudFront for AWS deployments to get around this issue.  Removing the `high-priority` tag for now until the issue becomes more actionable.

**Comment by sjezewski** [comment]
Cloudfront is in alpha support. I think we want to get that to the 'beta' level for the 1.5 release

**Comment by sjezewski** [comment]
This was fixed in: https://github.com/pachyderm/pachyderm/pull/1903
