### ISSUE TITLE
sometimes all jobs get `empty` status

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#1426]
```
COMPONENT           VERSION                                           
pachctl             1.3.16-d78c0b711a995cf6c027c5e35354004a40bc0723   
pachd               1.3.16-d78c0b711a995cf6c027c5e35354004a40bc0723 
```

I have existing repos A and B, each of which has a handful of commits already. Then I create a pipeline with inputs of both A and B. I expect many jobs to spin up since pachyderm would use all cross products of the commits to run this pipeline.

I tested this scenario a couple of times. Sometimes but not always, I ended up getting just a few jobs with `empty` status soon after I created the pipeline. After deleting the pipeline and downstream repo, and creating it again, I got normal amount of jobs running.

`empty` job doesn't seem to contain any log either. So it has been hard for me to get a sense of what's going on.

**Comment by JoeyZwicker** [comment]
@willguxy we're going to try to repro and hunt this down for you. Can you show me what `inspect-commit` returns for one of the empty commits?

**Comment by jdoliner** [comment]
And also what `inspect-job` shows for on of the empty jobs would be helpful.

**Comment by JoeyZwicker** [comment]
ping @willguxy

**Comment by sjezewski** [comment]
stale
