### ISSUE TITLE
Remove --no-archive flag references

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1427]
I think now it is `--archive true` or `--archive false`.

**Comment by jdoliner** [comment]
In 1.4 archive doesn't exist does it?

**Comment by JoeyZwicker** [comment]
No, but it's still in v1.3 I think and we should make sure the functionality works correctly. @dwhitena did you try to repro what @alexsbromberg was hitting?

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
I find no references to `no-archive` in our code base.
