### ISSUE TITLE
Pachyderm 1.4 release blockers

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1428]
These are the things that **must** be done before we cut the 1.4 release, in no particular order:

- [x] `pachctl get-logs` (PR is there, needs to be merged)
- [x] Load testing / benchmarks.  Ideally by the release date, we'd have CI set up such that it runs benchmarks daily, but if not, we need to at least have run the benchmarks manually on an actual cloud provider (AWS > Azure > GCE, in terms of priority) and make sure that the results don't seem too surprising.
- [x] `pachctl put-file pfs://path` (PR is there, needs to be merged)
- [x] Documentation (notably including migration docs)
- [x] Run etcd as a stateful set with persistent volumes
- [x] Egress support
- [x] Merge with `master`
- [x] `put-file -c`, and potentially make it so that `start-commit repo branch` succeed even if `branch` doesn't exist.

Following are the things that would be **very nice** to get done, but it's acceptable if they don't make it into 1.4.

- [ ] Incremental pipelines (similar to `/prev`).
- [ ] Make a pass at all test suites and fix them as needed.

**Comment by jdoliner** [comment]
I think another **must** is:

- [ ] `put-file -c` and `start-commit repo branch` (#1422)

That syntax is pretty ubiquitous from what I understand.

I also think merging with master is kind of a must, for one thing it has a number of bug fixes that have been added since the last merge and it'd be pretty bad to regress on those. But also just from a development hygiene perspective I think getting everyone onto the same branch at release time is a good practice and will prevent some headaches.

**Comment by derekchiang** [comment]
I suspect that most of the "bug fixes" are for code that don't exist anymore in 1.4, but I suppose it makes sense to at least **try** to merge master and see if we are indeed missing important stuff.

Just to be clear though, the current master branch will need to be moved to something like a `1.3` branch anyways, right?  We talked about how we want to support both release branches for a while.

Updating the task list to reflect the discussion.

**Comment by jdoliner** [comment]
Some of the bug fixes are pretty generic stuff though, like all of the fixes I made for object store retries. There isn't a good way to distinguish between stuff that applies and stuff that doesn't other than to merge it in.

And yeah, breaking current master off into `1.3` so we can backport fixes if need be is a good idea.

**Comment by jdoliner** [comment]
The 2 remaining issues have been broken out into separate issues #1584 and #1580.
