### ISSUE TITLE
put-file path to file in PFS is actually optional

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1429]
The usage help text for `put-file` implies the `path/to/file/in/pfs` is mandatory:

```
Usage:
  pachctl put-file repo-name commit-id path/to/file/in/pfs [flags]
```

I think this should be

```
Usage:
  pachctl put-file repo-name commit-id [path/to/file/in/pfs] [flags]
```
right?

**Comment by jdoliner** [comment]
This is correct, it's a little bit weird because if you omit the path and don't include a `-f` argument then it will error because it doesn't have anywhere to get the path from. But that still counts as optional in my book so we should make this change.

**Comment by JoeyZwicker** [comment]
This is very minor, but is an easy change.
