### ISSUE TITLE
`pachctl <noun>` is broken in v1.4

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1430]
`pachctl commit` right now just returns nothing. Either this should not be a command (and error) or it should print out the --help for that noun. I think in v1.3 is prints the help so I think thats the way to go. 

We also need to update the --help docs to actually list all the `<verb-commit>` commands that are available because seeing the actions that can be taken on commits in clearly useful in this context. 

Ditto for all other nouns, repo, file, pipeline, etc.

**Comment by jdoliner** [comment]
This is identical to the behavior in 1.3.
