### ISSUE TITLE
clone/combine repos

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1431]
There could be some usefulness in meta-operations that let you manage repos. Some obvious ones are:
1) copying data from one repo to another
2) combining repos -- 3 repos become 1 repo with 3 directories
3) "rebasing" -- if you have thousands or millions of commits, right now we don't give the user any good ways to garbage collect old commits to reclaim some storage space, simplify their commit tree, or reduce latency on commands that need to actually walk/load the whole commit tree. One simple way to do this is offering the ability to basically just rebase or start a new repo with a `from commit` in another repo. This might just be a --from flag in #1 above. We've had users ask about this before when thinking about maintenance of long-running pachyderm clusters.

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
Most of these use cases are covered by the `copy-file` command.
