### ISSUE TITLE
Create master branch by default

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1433]
We've had discussions going back and forth about branch default behaviors. In a discussion with @derekchiang today, we noticed that some pipeline spec fields default to `master` (e.g. output branch). This seems totally reasonable, but then follows that `master` should be automatically created as a branch on the first commit created in a repo unless the user specifies something else.

**Comment by jdoliner** [comment]
Given that the two ways to create a commit both require you to specify a branch, ie:

```
start-commit repo branch
put-file repo branch -c ...
```

This isn't going to save users anything except maybe in the rare case where they're using the protobuf api directly. On the other hand, doing this would make it impossible to create a commit not on a branch unless you already had `master` defined which is a really weird behavior.
