### ISSUE TITLE
Branch propogation

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1434]
I know we've discussed this a ton, but couldn't seem to find an open issue for it.

Since pipelines take specific branches as input, how do/should branches propagate downstream? 

I believe the default behavior is that they just target the `master` branch in the output repo, but that can obviously conflict in nasty ways. Should they default to the same same branch name as the input? That seems to break down with multiple inputs, right? Users can specify a branch, but it's not a required field so unless we want to make that required, we probably need a little bit of logic in there to do something. 

Also, what happens if two pipelines by different users accidentally target the same output branch, do we error correctly?

We should discuss and think about this more.

**Comment by JoeyZwicker** [comment]
Some info in #1036 might be relevant.

**Comment by jdoliner** [comment]
Pipelines specify their output branches directly in 1.4.

**Comment by JoeyZwicker** [comment]
@derekchiang seemed to think that  "outputBranch": string was not a required field and defaulted to `master` if unspecified.

**Comment by jdoliner** [comment]
I think that's correct... that behavior seems pretty reasonable to me.

**Comment by JoeyZwicker** [comment]
then what happens if you have two pipelines both with output branch unspecified? They both output to `master`? That doesnt seem right.

**Comment by jdoliner** [comment]
Why not? Pipelines don't output to the same repo.

**Comment by JoeyZwicker** [comment]
ah nvm. I was being silly and thinking that two pipelines could target the
same repo if they were on different branches.

So this basically mean there's only ever 1 branch (master) on pipeline
output repos. Or am I missing something else?

**Comment by jdoliner** [comment]
Yup that's correct, and strictly speaking it doesn't have to be master but given that there can only be one branch at this point it probably doesn't make much sense to have it be anything but master. In the future we'll probably allow either multiple versions of the same pipeline, or multiple pipelines targeting the same repo (conceptually those are really the same thing) at which point we'll need to have some validation to make sure repos can't target the same branch.
