### ISSUE TITLE
pachctl docs are generating incorrectly. 

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1437]
we're on 1.3.16 but the docs portal only has up to 1.3.14. In addition some commands aren't showing up correctly and I think that's because of the .md and .rst stuff we have going on there. We should figure out how to correct that.

**Comment by sjezewski** [comment]
If its the 'rst' vs 'md' thing, this will be the 3rd time that it's accidentally been done incorrectly / not done manually. In which case, I think its time to automate that step.

**Comment by dwhitena** [comment]
@JoeyZwicker @sjezewski I fixed most of this in the 1.4 docs.  However, I will make a note to scrub the pachctl docs again here: https://github.com/pachyderm/pachyderm/issues/1869

**Comment by dwhitena** [comment]
I think this is addressed generally.  Closing now in favor of more specific pachctl doc issues.
