### ISSUE TITLE
OpenCV in 1.4

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1439]
@dwhitena I think we are going to have to change the beginner tutorial for v1.4. Logs being processed in the way we do the fruit stand actually isn't a good use case in v1.4. We dont support large files that you constantly append to very well. We also dont support append-based incrementality at all and don't have /prev anymore to do the Sum pipeline efficiently. 

OpenCV just seems much cleaner and is actually a more interesting overall demo IMO. The only part I'm not sure about is i'd like the tutorial to not include `pachctl mount` but viewing images so you can see your data is tough without it. Perhaps we need to think of something else for beginner tutorial entirely.

**Comment by dwhitena** [comment]
Yep, that's great @JoeyZwicker.  I'll think about the mount.

**Comment by jdoliner** [comment]
AFAIK opencv is currently the beginner tutorial in 1.4 but there are some issues with it. @JoeyZwicker is that correct and could you expand on what the issues are.

**Comment by JoeyZwicker** [comment]
OpenCV is used for both the beginner tutorial but also our live demo. The tutorial is pretty good as is, but there are a few places the demo could be improved in v1.4.

1) Mounting with FUSE was a great way to demonstrate the commit structure of PFS when users could see master/0, master/1, etc. In v1.4 you only see UUID's in random order and it's was less visually meaningful. Having commit names aliased as described in #1591 might be a great option. 

2) Having more info displayed in `pachctl inspect-*` commands or potentially in the mount as well if that's possible, would also improve the demo experience. 

3) @dwhitena and I have talked a lot about adding another pipeline step after the edge detection, perhaps just a crop or resize to show pipeline stages, updates, provenance, etc. Dan, I actually dont remember the specifics of what we discussed, but can you add them here if you do?

**Comment by dwhitena** [comment]
Yes, @JoeyZwicker related to (3) above, I got feedback from a number of Google advocates that the demo could be made much stronger by having a very simple second stage.  This could be a crop or resize for example.  We could literally add and run this in a couple of second, but it would really demonstrate the power of pipelines in Pachyderm.  The one stage pipeline doesn't differentiate as much from other things like Domino, for example.

**Comment by jdoliner** [comment]
One idea I had for a second stage was using ImageMagick to turn the outputted images into a montage. You can do some pretty cool stuff with a simple command line invocation: http://www.imagemagick.org/Usage/montage/ and I think it would work well for the demo because you could just open up a single image at the end which shows the original images and their edges side by side. And of course the montage would automatically update as new images come in.

**Comment by dwhitena** [comment]
@jdoliner that's brilliant.  Great idea and I like how it is sort of a reduce after the map, and a different glob pattern.  We could also do it in simple bash if we wanted.

**Comment by sjezewski** [comment]
The montage addition was submitted in https://github.com/pachyderm/pachyderm/pull/1850

So I think this can be closed? @JoeyZwicker ?

**Comment by JoeyZwicker** [comment]
Only #3 on my list above have been added and we haven't actually adding the montage step to the beginner tutorial yet -- the UI might solve this once we have the file browser ready to go, but we're not there yet.

**Comment by dwhitena** [comment]
@JoeyZwicker I have done the OpenCV demo quite a few times using `display` along with `list-file` and `get-file`.  It seems to work pretty smooth.  I'm not quite sure what the FUSE mount adds at this point, especially given that it is somewhat confusing to explain for many people (that is, explaining the mounting of the distributed file system seems to be a hurdle for many people that could be avoided by just listing files and getting them).  I guess you are showing multiple commits, but I think that is pretty clear when you `list-commit` and `list-file`.  The only piece that would be missing would be the timestamp.

These are just my opinions of course.  @JoeyZwicker, you have a ton of experience with the demo.

And, yes, @sjezewski we need to add the docs for the montage, which is part of the 1.5 checklist.
