### ISSUE TITLE
review and update pachctl docs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1448]
We should do a once-over on all the help messages for pachctl docs. We definitely should expand and add details as well as unify the language and terms in the help docs. 

--split-file for instance could be much clearer defining the delimiter and target-datum-count

**Comment by dwhitena** [comment]
Split file updated here: http://pachyderm.readthedocs.io/en/latest/cookbook/splitting.html.  Also, `pachctl` docs were scrubbed at the 1.5 release.  Closing for now in favor of more specific doc issues.
