### ISSUE TITLE
"lazy": true and "error from GetFile: unexpected EOF" (possible data loss during streaming)

### ISSUE THREAD

**Issue by emk** [pachyderm/pachyderm#1452]
When running Pachyderm jobs (with ~110 GB of data split across ~1,500 files and 16 workers, in non-incremental `FILE` mode), I see the following errors:

```
3 | time="2017-03-22T00:40:15Z" level=info msg="error from GetFile: unexpected EOF" 
3 | failed to fill whole buffer
5 | time="2017-03-22T00:40:15Z" level=info msg="error from GetFile: unexpected EOF" 
5 | failed to fill whole buffer
6 | time="2017-03-22T00:40:14Z" level=info msg="error from GetFile: unexpected EOF" 
9 | time="2017-03-22T00:40:14Z" level=info msg="error from GetFile: unexpected EOF" 
9 | failed to fill whole buffer
11 | time="2017-03-22T00:40:14Z" level=info msg="error from GetFile: unexpected EOF" 
```

Also:

```
1 | time="2017-03-22T00:40:14Z" level=info msg="error from GetFile: unexpected EOF" 
4 | time="2017-03-22T00:40:15Z" level=info msg="error from GetFile: unexpected EOF" 
4 | time="2017-03-22T00:41:46Z" level=info msg="error from GetFile: unexpected EOF" 
```

Version:

```
COMPONENT           VERSION             
pachctl             1.3.16              
pachd               1.3.16     
```

The `error from GetFile` appears to come from [these lines here](https://github.com/pachyderm/pachyderm/blob/d11b9edd1025d909a4c80af7d54c1d65b79dc12b/src/server/pkg/sync/sync.go#L64-L89):

```go
					// This goro will block until the user's code opens the
					// fifo.  That means we need to "abandon" this goro so that
					// the function can return and the caller can execute the
					// user's code. Waiting for this goro to return would
					// produce a deadlock.
					go func() {
						f, err := os.OpenFile(path, os.O_WRONLY, os.ModeNamedPipe)
						if err != nil {
							log.Printf("error opening %s: %s", path, err)
							return
						}
						defer func() {
							if err := f.Close(); err != nil {
								log.Printf("error closing %s: %s", path, err)
							}
						}()
						err = client.GetFile(commit.Repo.Name, commit.ID, fileInfo.File.Path, 0, 0, fromCommit, fullFile, shard, f)
						if err != nil {
							log.Printf("error from GetFile: %s", err)
							return
						}
					}()
```

If I understand this code, when an error occurs during a `lazy` copy, the error is logged but not reported back to Pachyderm, so there's no way to tell that the job has failed and retry it.

The `failed to fill whole buffer` message is almost certainly related: This is an error printed by [Rust's standard file reading routines](https://github.com/rust-lang/rust/blob/8c4f2c64c6759a82f143e23964a46a65c67509c9/src/libstd/io/mod.rs#L627-L632) when they were told to expect a known-sized input but didn't receive all the bytes. Since the only Rust code in the pipeline in question was `szip` (applied directly to the lazy pipe from Pachyderm), I'm guessing this means we're seeing incomplete snappy compression frames. This only occurs _after_ the lazy pipe errors out, so I'm not worried about it.

**Comment by emk** [comment]
Oh, yeah, there's a workaround: Disable `lazy` and this code path should never be hit. But this comes at a performance cost, and data loss during processing is pretty bad in any case.

Oh, and a nice bit of confirmation that the numbers add up:

- We saw the `error from GetFile` message 5 times.
- 3 times, this resulted in an incomplete snappy frame read in `szip`. This will still produce output data, of course.
- We saw exactly 2 files which appeared to contain 0 lines. `szip` would likely have assumed that 0 bytes of input means "no compression frames" means "no output".

So I think we can track all the odd behavior we're seeing here back to `error from GetFile`. But there are presumably two actual issues here:

1. Why doesn't Pachyderm notice `error from GetFile` and mark the job as failed?
2. Why is the `unexpected EOF` occuring in the first place on 5 out of 16 workers?

**Comment by jdoliner** [comment]
This issue is now fixed in the sense that if the worker does encounter such an error it will be propagated correctly and the job will be marked as failed. There's still other fixes I'd like to make to pipes but I'm going to do them as separate issues and close this one for now.

**Comment by emk** [comment]
I think that this fix is the most important part: The underlying error seems to be fairly rare when the cloud isn't acting up, and as long as it gets detected and handled properly, we have no real worries. Thank you!
