### ISSUE TITLE
pachctl put-file help docs: -f doesn't have a default

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1453]
docs say `default [-]` but it seems like a required argument

```
$ echo "hello commit 2" | pachctl put-file -c page_views master "/tmp/Screenshot from 2017-03-16 11:23:13.png" -f 
Error: flag needs an argument: 'f' in -f
```

**Comment by jdoliner** [comment]
`-` is the default in that it's what you get if you don't pass `-f` at all. If you do pass a `-f` then it needs to be with a value, there's no meaning to an empty `-f` you should always just omit it in that case. I think this is pretty in keeping with how flags normally work.
