### ISSUE TITLE
pachctl inspect-file commit modified is broken for directories

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1454]
I'm getting `Commit Modified: template: FileInfo:5:34: executing "FileInfo" at <.CommitModified.Repo...>: can't evaluate field Repo in type *pfs.Commit`

In the API, I seem to be getting a null value back for this field. Are directories supposed to have a commit modified field?

Full example: 
```
$ pachctl list-file page_views master --recurse
NAME                TYPE                MODIFIED            LAST_COMMIT_MODIFIED   SIZE                
/page_views.json    file                34 hours ago        master/1               4.009 KiB           
/tmp                dir                 18 minutes ago      master/2               77.31 KiB           
$ pachctl inspect-file page_views master "/tmp"
Path: /tmp
Type: dir
Modifed: 18 minutes ago
Size: 0 B
Commit Modified: template: FileInfo:5:34: executing "FileInfo" at <.CommitModified.Repo...>: can't evaluate field Repo in type *pfs.Commit
```

Note that the directory was actually created in an earlier commit, but the file within the directory was updated in `master/2`, and that seems to be what's showing in `list-file`

**Comment by sjezewski** [comment]
stale
