### ISSUE TITLE
inspect-file children objects' commit id has strange formatting

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1455]
A commit id usually has the format `branch/index` (eg `master/1`), but for files returned in a directory's `children` array, the commit id seems to have the format `repo_name:branch:index` (eg `page_views:master:2`)

Full response example for inspecting a directory called `/tmp`:

```
{
    "children": [
        {
            "commit": {
                "id": "page_views:master:2",
                "repo": {
                    "name": "page_views"
                }
            },
            "path": "/tmp/Screenshot from 2017-03-16 11:23:13.png"
        }
    ],
    "commitModified": null,
    "file": {
        "commit": {
            "id": "master/2",
            "repo": {
                "name": "page_views"
            }
        },
        "path": "/tmp"
    },
    "fileType": "FILE_TYPE_DIR",
    "modified": {
        "nanos": 359499818,
        "seconds": "1490201873"
    },
    "path": "/tmp",
    "sizeBytes": null
}
```

Repro notes on dashboard:
go to http://localhost:4200/app/repos/page_views/commits/page_views-master%2F2/files//tmp
get "resolving with" message
temp1.encodeJSON()

**Comment by gabrielgrant** [comment]
Interestingly, it seems that child commit id also references the commit in which the file was last modified, *not* the same commit as that of the parent file

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
This commit syntax died a while ago so this shouldn't apply anymore.
