### ISSUE TITLE
API 1.4: file.commit_modified doesn't exist

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1457]
In 1.3, I can get the commit in which a file was last modified; there isn't really any way to get that info in 1.4. I had been using this to show the history of a file, which seems like a useful feature

**Comment by gabrielgrant** [comment]
I'm currently doing this in the dash by traversing the commit history and finding the first commit where a particular file hash appears, but this is pretty horribly inefficient, requires code that i shouldn't really have to maintain, and it seems silly that this info isn't available from the CLI

from discussion with @msteffen : this is doable, but will require a migration to generate this info for all past files in all past commits

**Comment by sjezewski** [comment]
stale

**Comment by gabrielgrant** [comment]
re-requested in https://github.com/pachyderm/pachyderm/issues/2065#issuecomment-397159072

**Comment by gabrielgrant** [comment]
solve this by adding a `--history [n]` flag to `ListFile`. More details in https://github.com/pachyderm/pachyderm/pull/3277#issuecomment-446751226

**Comment by ysimonson** [comment]
This is now implemented with the `--history` flag
