### ISSUE TITLE
v1.3: commits should show their status

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1461]
Commits can be open, finished, archived, or cancelled. That status should be shown in inspect-commit and probably list-commit as well. 

Was trying to debug with a user and we had to dig into the logs to find what the commit's status was.

**Comment by jonandernovella** [comment]
+1. And this should also include some command to check the progress of the put-file command- In case of uploading some big data-set it is hard to see whether it hangs or not.

**Comment by sjezewski** [comment]
@jonandernovella -- if you look at the `pachd` logs (e.g. `kubectl logs pachd-erg45`) and look for putfile logs ... you'll see a line per file that is getting put (if its coming from a separate obj store). That might be handy. If that doesn't suit your need, please open a new issue to track put-file progress

Meanwhile, 1.3 gets no new features, so I'm closing this issue.
