### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1463]
Figure out how to allow installation of previous versions using the same workflow as main installs (ie `brew install pachctl140` or `curl -o /tmp/pachctl-1.4.0.deb -L https://pachyderm.io/pachctl-1.4.0.deb && sudo dpkg -i /tmp/pachctl-1.4.0.deb` )

**Comment by sjezewski** [comment]
For brew -- this is in place per `Major.Minor` release. So you can do `brew install pachctl13` or `brew install pachctl14`

For deb packages, the version is fully resolved in the URL
