### ISSUE TITLE
Update docs to install specific version

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1464]
Currently the docs themselves are versioned, but old versions of [the pachctl local installation docs](http://docs.pachyderm.io/en/latest/getting_started/local_installation.html#pachctl) still reference the latest version of the pachyderm binary. eg. http://docs.pachyderm.io/en/v1.2.6/getting_started/local_installation.html#pachctl

These should be updated to reference the specific version of the installation that corresponds to the version of the docs

Depends on #1463

**Comment by sjezewski** [comment]
Going forward, we will be able to provide this easily to stable major.minor releases.

Today, you can accomplish this for _any_ release via the release artifacts on github. It's not the prettiest thing, but it's doable. To date, I haven't had a request to go back more than a single version, so I think our current release mechanisms are 'good enough'.

Also, we're seeing great adoption of the latest release, so right now this is not an issue. In the future it might be, but if we have users on legacy versions, we have the build artifacts so we can provide some install mechanism as needed.
