### ISSUE TITLE
Check version compatibility between pachd API and client

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1465]
Currently our API isn't versioned, meaning clients can fail in surprising ways. In particular, using a v1.4 client with a v1.3 server will almost certainly blow up. `pachctl` should return a usable error message saying 

My inclination is that we should allow using different patch versions (1.3.x) of the client and server  to communicate (possibly with a warning message), but should prevent users from using different minor versions (1.x -- I think this is basically our implicit backwards compatibility promise, right?).

Seems this could be implemented by allowing the client to (optionally?) include it's version compatibility in all messages, and having pachd return errors if it's incompatible, or having the client manually check the version API before all commands. Not sure which is preferable (the latter is simpler; the former saves a round-trip, and formalizes a way for other clients to implement versioning)

**Comment by sjezewski** [comment]
Is this something that we need for 1.5? Having the release boundary might be a good time to test out the behavior we want longer term. @gabrielgrant

**Comment by sjezewski** [comment]
closing, as this is stale

in practice, having user's upgrade their client is usually fine
