### ISSUE TITLE
GetFileGlob

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1467]
This is a feature we talked about having in 1.4 but didn't get around to implemention, it allows you to do `get-file ... foo/*` to get all files under the directory `foo` concatenated.

**Comment by jdoliner** [comment]
This should be part of a 1.4 point release.

**Comment by sjezewski** [comment]
We have `glob-file` which lists files, so you could do something like:

`pachctl glob-file repo master /*/*.json | while read file; do mkdir -p $(dirname $file); pachctl get-file repo master $file > $file; done`

Which would create the file structure locally, but wouldn't provide the output concatenated. It sounds like there's a specific use case you have in mind there. In that case you could do:

`pachctl glob-file repo master /*/*.json | while read file; do pachctl get-file repo master $file >> dump; done`

This seems to enable what users might want (though it requires some bash-fu). Do you think these cases should be first class `pachctl` functions @jdoliner ?

**Comment by jdoliner** [comment]
I do, I think #2631 has the most up to date info on it.
