### ISSUE TITLE
Implement delete-commit in v1.4

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1472]
`delete-commit` in 1.3 wasn't very powerful as it only applied to open HEAD commits. 1.4 changes things enough that we should rethink from scratch how we want `delete-commit` to behave or even if we even want it all. 

Some considerations:
- Once a commit is closed, deleting it would leave downstream commits without provenance which would be nasty. If we allow this we'd need to delete all provenant (<-- is there a better term for commits with this as provenance?) commits as well. 
- We currently do now allow list-file in v1.4 on open commits. This makes `delete-file` and `delete-commit` a bit unwieldy because I can't see what files are actually there. Just finishing that commit and then correcting things in the next one isn't a great solution because the bad commit would trigger downstream pipelines which fail in catastrophic ways (e.g. OOM or OOD because I forgot to do --split-file).

**Comment by jdoliner** [comment]
I think we definitely want `delete-commit`.

- Deleting the commit's subvenance (opposite of provenance) seems like it's probably the right answer. I don't think having commits with provenance that doesn't exist is all that nasty though so there should be an option to leave them intact.
- Deleting a commit `c` should result in any commits that have `c` as their parent having `c.Parent` as their parent.
- If a branch `b` is pointed at `c` and `c` is deleted then `b` should point at `c.Parent`.

**Comment by JoeyZwicker** [comment]
Capturing a discussion that happened offline.

Delete-commit perhaps should only work on input repos (not repos from pipelines). If you delete a commit from an output repo, what happens to the provenant commits in repos further up the DAG? You'd now have pipelines with input commits and no corresponding output and that would cause some very odd edge cases in our current implementation that don't really make sense.

**Comment by sjezewski** [comment]
I believe this is being implemented as part of 1.7 / commit invariance

@msteffen @jdoliner - can you add this to the right PR / issue to make sure we close this once the feature lands?

**Comment by jdoliner** [comment]
I'm actually not sure how to do that anymore. We just need to remember to close this once #2506 is merged.
