### ISSUE TITLE
Reorganize pachctl help the same way kubectl is organized

### ISSUE THREAD

**Issue by davidgasquez** [pachyderm/pachyderm#1476]
Right now is just a list of commands:
```
Available Commands:
  repo             Docs for repos.
  create-repo      Create a new repo.
  inspect-repo     Return info about a repo.
  list-repo        Return all repos.
  delete-repo      Delete a repo.
  ...
  ...
```
 It would be great to quickly locate pipeline/commits/repo related commands. `kubectl` is awesome in this sense because it has some kind of menu:
```
Basic Commands:
  get            Display one or many resources
  explain        Documentation of resources
  ...
  ...
Deploy Commands:
  rollout        Manage a deployment rollout
  rolling-update Perform a rolling update of the given ReplicationController
  ...
  ...
```

**Comment by sjezewski** [comment]
We also had a user get very confused about our use of `verb-noun` syntax in our subcommands as opposed to `verb noun` that kubectl uses. It is confusing to new users (usually of both k8s and pachyderm) to learn which one is which.

e.g. `pachctl list-repo`

vs `kubectl get pods`

**Comment by sjezewski** [comment]
Different user posted related issue about that here: https://github.com/pachyderm/pachyderm/issues/1534

**Comment by JoeyZwicker** [comment]
We're unlikely to change the verb-noun syntax at this point, but organizing the pachctl commands in the docs and help section could be useful. Low priority.

**Comment by sjezewski** [comment]
low priority + stale = closed

**Comment by JoeyZwicker** [comment]
I think @jdoliner has been wanting to do a cleanup pass for pachctl and that might actually happen in 1.8 or shortly after. I'm going to reopen because even though the specifics listed here are low priority, they might be part of the next milestone.

**Comment by Tryneus** [comment]
Commands were changed to be `verb noun` in `v1.9.0`, and the help section was broken up into logical groupings to make it visually parse better.  Old command invocations have been preserved with a deprecation warning for the meantime for compatibility.
