### ISSUE TITLE
Decide on defaults and document new etcd deployment options

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1477]
We now support multi-node etcd on GCE and AWS, and on these providers, we can dynamically provision the volumes.

We need to choose defaults and document these two nobs (dynamicly-vs-staticly-provisioned volumes and single-vs-multi-node etcd) for GCE and AWS.

We also need to document any related changes required to deploy on other providers that don't support dynamic volumes. My understanding is this will be different on Azure, where we'll use re-attachable block storage, and most other VM providers (DigitalOcean, etc), where we'll use local disk storage.

cc @msteffen @derekchiang

**Comment by JoeyZwicker** [comment]
#2287 I think this has been done
