### ISSUE TITLE
Workers should use dynamically provisioned volumes

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1481]
Currently, pipeline workers (available in 1.4) use the local disk to store input/output data.   Thus, it's currently impossible to process datums that are larger than the local disk.  Instead, we should dynamically provision persistent volumes for workers.  The user should be able to specify how big these persistent volumes need to be (which in turn bounds the size of the largest datum they need to process).

**Comment by jdoliner** [comment]
This is possible using `pod_patch` but there hasn't been a strong need for it. Emptydir seems to work well for this, and kubernetes now has the ability to have disk space as a resource request. I think we're happy with where this is but feel free to reopen if you're having issues with this.
