### ISSUE TITLE
Kafka Connector

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1482]
[Kafka Connect](http://docs.confluent.io/3.0.0/connect/index.html) allows you to stream data from and to other systems in a very streamlined version.
It has a [simple API](http://docs.confluent.io/3.0.0/connect/devguide.html) for developing new connectors.

Kafka is a building block for almost every Big Data architecture and can provide a very easy way to get data into pachyderm and out of it.

I'd contribute a connector (or a part of it if you guys want to participate) if I had a Java client ready to use. It should take up to a week to develop the connector and test it. I'd rather not invest the time in writing a Java client for pachyderm as well.

**Comment by rawc0der** [comment]
Hi @thedrow ,

You're idea sounds cool, but I'm not sure how you would define the functionality of a source/sink.

Is this similar to what you are thinking about ?

*) **Source**  Pachyderm Pipeline that injects data to a kafka source from the input repo.
*) **Sink** Extracts data from kafka into the input repo.

Thanks.

**Comment by thedrow** [comment]
Exactly! You specify the file name(s) template in the configuration (or provide it as part of the message) and the Sink will commit it to the desired repository.
The Source will stream results from a repository. Since a pipeline always saves data in a new repository, creating a source from a repository is natural and will result in what you'd expect.

**Comment by derekchiang** [comment]
This would be super cool.  Just to be clear though, we don't have to have a Java client to build a Kafka connector right?  Seems like Kafka has a Go client.   https://github.com/Shopify/sarama

**Comment by jdoliner** [comment]
It seems like we don't really need to worry about which language the kafka connector is written in, within the Pachyderm architecture the most reasonable way to implement this would be a container which reads from a set of kafka topics and writes them out to disk. This is similar, conceptually to a scraper pipeline. This could be written in whatever language is most convenient for kafka, so probably Java, and the rest of the system wouldn't really have to care about what's running inside the container, same is true for pushing data into kafka.

**Comment by rawc0der** [comment]
Hi @jdoliner,

It's really cool that Pachyderm allows you to write language agnostic connectors by using the Pachyderm FS repositories ( assuming the **Connector** is run as a container in the Pipeline). 

@thedrow , here are some ideas about a truly powerful native kafka-connector I've been thinking about:
 * Source with multi-topic publishing ability
 * Sink that can fan out to multiple pachyderm repositories
 * option to add a new commit to pachyderm on each event passing through the topic

Whilst in general it seems that in Pachyderm you can connect with any client to a Kafka Cluster, but what about from a Kafka-Connect Connector (i.e. Sink/Source worker job) to a Pachyderm Cluster, so an important question follows:
 - What is the best option to interact with the **pachd** server from the context of a **Kafka Connector** ?

**Comment by rawc0der** [comment]
After a bit of reading, I see that the  **protocol buffer API**  can be used to build a client interface in java for the Kafka Connector to use.
 - (https://github.com/pachyderm/pachyderm/blob/master/src/client/pfs/pfs.proto)

**Comment by thedrow** [comment]
@jdoliner @derekchiang I think you guys are missing the point. Kafka has a standardized mechanism to move data to/from sources. 
If we're going to use it, we do need to implement the Sink and Source in Java.

**Comment by dahankzter** [comment]
There is a fairly large set of connectors from which ideas and perhaps corner cases with partition handling can be pulled in https://www.confluent.io/product/connectors/

**Comment by gabrielgrant** [comment]
@rawc0der yup, you're right -- Pachyderm's API uses GRPC (which in turn use protobufs), so all that's needed to interact with Pachyderm from Java is to use [the Java-native GRPC library](https://github.com/grpc/grpc-java). It looks like you should just be able to include that lib (whether by downloading the `.jar`s or using the gradle/maven config in that README) and drop the Pachyderm API .proto definition files for [PPS](https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.proto) and [PFS](https://github.com/pachyderm/pachyderm/blob/master/src/client/pfs/pfs.proto) into your `/src/main/proto` dir

There's a full example of using a GRPC client from Java in the GRPC docs: http://www.grpc.io/docs/tutorials/basic/java.html#creating-the-client

**Comment by thedrow** [comment]
Just a note since I forgot to mention it. Kafka does not handle large messages very well. All producers must be able to partition the file in such a way that the connector will be able to reconstruct it.
See [this presentation](https://www.slideshare.net/JiangjieQin/handle-large-messages-in-apache-kafka-58692297).

**Comment by jdoliner** [comment]
We now have an implementation of spouts with a nice example of how to implement a Kafka connector using them. I think that should cover this issue, but feel free to reopen if you think there's more we should do here.
