### ISSUE TITLE
Finish porting tests to 1.4

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1486]
While we have ported all server tests (i.e. PFS tests) and integration tests (i.e. PPS tests), there are still some tests from 1.3 that haven't been ported to 1.4.  FUSE tests notably come to mind.

**Comment by sjezewski** [comment]
Other suites that we're not running are:

- pretest (linter, go vet)
- test-client (coverage for users of our API)
- test-local (which does a go list under /src/server omitting fuse and vendoring, but getting all other packages) ... so we might be missing some there

**Comment by derekchiang** [comment]
Fairly sure linter is getting run.

**Comment by jdoliner** [comment]
I believe everything that can be ported has been. Closing.
