### ISSUE TITLE
Selectively remove datums when there are multiple inputs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1487]
Currently, a worker removes all input data from the previous run before starting a new run.  However, consider the following case with two inputs:

```
Input 1: datumA, datumB
Input 2: datumC
```

There are two tuples to process: `(datumA, datumC)` and `(datumB, datumC)`.

If a worker had just processed `(datumA, datumC)`, it should keep `datumC` on disk and only replace `datumA` with `datumB`.

**Comment by jdoliner** [comment]
subsumed by #1587
