### ISSUE TITLE
Joins docs page

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1490]
The [joins blog post](https://medium.com/pachyderm-data/easy-distributed-joins-with-pachyderm-8307bab8a761) ends with "here we have considered only one type of join, but there are many different types (inner, left, right, etc.). For many of these joins, Pachyderm offers additional optimizations that are discussed further in our docs."

Pretty sure our docs don't deal with these details directly, though. This info should probably be added to the [joins docs page](https://github.com/pachyderm/pachyderm/issues/1383#issuecomment-289568937) (post 1.4). Not sure how some of those patterns are accomplished, but the cool `/prev`, "self-join" should be documented (when 1.4's `/prev` is available)

**Comment by dwhitena** [comment]
@gabrielgrant do you think we need more than this currently: http://pachyderm.readthedocs.io/en/latest/cookbook/combining.html.  Maybe something paralleling certain types of joins (INNER, OUTER, etc.)?

**Comment by JoeyZwicker** [comment]
This is fine for now as it's easily discoverable by someone looking for "joins"

**Comment by gabrielgrant** [comment]
I wouldn't exactly call this doc "easily discoverable by someone looking for "joins"" -- it doesn't show up anywhere on the first page of google search results for "pachyderm join" (whereas the blog post with the broken link is the first result), and it doesn't jump out at me if I'm looking for info on joins in the index or sidebar. I've submitted [a PR that changes the page title](https://github.com/pachyderm/pachyderm/pull/2455) to hopefully make this more discoverable, but given the blog post is still the first result at the moment, could someone please update the link to point at this docs page? (I don't have access to edit the blog)

![image](https://user-images.githubusercontent.com/493968/31846911-27a8eb74-b5c7-11e7-86b6-28f67b7713d5.png)

**Comment by JoeyZwicker** [comment]
We can edit the blog to update the link. Our docs page has its own search bar and its the top result there.

**Comment by dwhitena** [comment]
I linked this blog post to the detailed combining/merging/joining docs.

**Comment by jdoliner** [comment]
It is done.
