### ISSUE TITLE
Revamp error handling throughout our codebase

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1493]
Currently, error handling is a mess.  We almost always simply pass along whatever errors we get from the underlying system; as a result users sometimes get errors through `pachctl` or FUSE that don't really make much sense.  Examples include the `grpc: *` family of errors and errors such as `no node at "/<file_name>"`.

A project that we can refer to for proper error handling is [Upspin](https://github.com/upspin/upspin/blob/master/errors/errors.go).

**Comment by derekchiang** [comment]
We might want to consider bumping the priority of this issue.  @sjezewski and myself have been in situations where we are looking at a super generic-looking error such as `grpc connection unavailable`, and have no idea which part of the code is actually spitting out this error because pretty much any code that uses grpc can return this error.  So we had to resolve to manually adding debug statements to pin down the faulty code.

If we solve this issue the way right way, then every error will embed the call stack and we will have no problem pinning down the source of the error.

**Comment by sjezewski** [comment]
May be related, may be separate implementation ...

@gabrielgrant noted that debugging some stats/datum stuff was hard bcz we see so many expected FNF errors from inspect files under the hood. Maybe there is a way to denote these 'expected' errors have a different log level?

**Comment by ysimonson** [comment]
Addressed by #4681: while we can always make improvements to error messaging, full stack traces will really ensure we know where errors are coming from.

**Comment by jdoliner** [comment]
Updated that PR so it'll close this issue when it's merged.
