### ISSUE TITLE
Decouple pipeline input/output with branches

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1495]
Currently, each pipeline input needs to specify a branch.  Each pipeline also needs to specify an output branch.  If the user does not specify these branches, they default to `master`.

However, it's unclear if this tight coupling between pipelines and branches is a good idea.  For instance, it's currently impossible to have a pipeline that processes more than one branches from an input, which seems limiting.

We should think about this a little more.

**Comment by sjezewski** [comment]
stale
