### ISSUE TITLE
Document the fact that using branches is more expensive than using commit IDs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1496]
When you use a branch with our's APIs (e.g. `get-file repo master file`), we need to check if the branch exists, and resolve it to a commit ID.  This process involves one round trip to the metadata store.  Note that it's hard to cache branches since branches are mutable references to commits, i.e. that they can be deleted and be changed to point to other commits.

An analogy would be that it's faster to use an IP address directly than to use a hostname such as `www.example.com`, since the later involves visiting the DNS server (although browsers do cache DNS entries since DNS entries don't change that often).

If you are making a lot of API calls using a branch that's not being changed, it would be cheaper to use the commit ID directly.  We should document that.

**Comment by sjezewski** [comment]
stale
