### ISSUE TITLE
Pipeline name limitations

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1497]
Currently pipeline names cannot be longer than 64 characters, because we use pipeline names in RC (replication controller) names and those can't be longer than 64 characters.  I'm not sure if this limitation is documented anywhere so we might want to do that.  Furthermore, we might want to come up with a scheme to allow for longer pipeline names.

**Comment by dwhitena** [comment]
Follow up on this issue from Slack:

```
Barnaby Keene [11:29 AM] 
the errors `only alphanumeric characters, underscores, and dashes are allowed` and `may not contain underscore` are a bit weird, since a repo is automatically created for a pipeline and it's named after the pipeline, I think they should both be constrained to the same name requirements. right now, it seems like repos can use underscores but pipelines can not.

Joey Zwicker [11:29 AM] 
@southclaws  we also opened an issue around pipeline chars. I didn't realize we changed this but I think etcd has some contraints on chars.

[11:30]  
Yeah we definitely will unify these

[11:30]  
Sorry for that confusion!

Barnaby Keene [11:31 AM] 
alright great to hear thanks! for now I'll just have to smush our UUIDs and other things into one big mess of characters haha

Joey Zwicker [11:31 AM] 
Or dash perhaps? Sorry again, we'll get this fixed right away

Barnaby Keene [11:35 AM] 
dashes didn't work in 1.3 either, I originally replaced them with underscores but in 1.4 that stopped working
```

**Comment by gabrielgrant** [comment]
a few of us discussed this last week after a request in users -- reopening with a few specific proposals:

1. document the actual requirements for pipeline and repo names (took a crack at this in #3006, but i imagine i'm missing some details, and that is only for pipelines -- not sure if the same rules apply for repos, and where the repo naming info should go in the docs)
2. remove the pipeline-name character length limit. this is currently limited because we use pipeline names as k8s resource names, which have a 64-char-max-length limit. seems this could be worked around by having a short-hash version of longer names. for the sake of being able to find the k8s resources related to a particular pipeline, i'd recommend:
   - only using a hash when a name actually exceeds the maximum length
   - using something like `<first 20 characters of pipeline name>-<10 char shorthash of name>-<last 20 characters of pipeline name>` (or, if `.` is allowed, maybe `...` instead of `-`?)
3. expand the range of acceptable characters by url-encoding in places where plain alphanumeric strings are required (and create explicit checks for the restrictions we do want to enforce)

**Comment by gabrielgrant** [comment]
in talking with @sjezewski and @msteffen we think moving to using an opaque (UU?)ID in k8s resource names and storing pipeline name in a label is probably a better approach than some ugly name mangling. This isn't ideal in that a basic `kubectl get all` doesn't show useful info, but `kubectl get all -L pipeline`'s output makes that extra level of redirection fairly straightforward

**Comment by JoeyZwicker** [comment]
Adding to this issue:

1. Trying to create a pipeline with a name more than 38 characters errors with:

```
pc create pipeline -f ~/pachyderm/examples/opencv/edges.json
commit edges123456789012345678901234567890123 not found in repo __spec__
```

```
{
  "pipeline": {
    "name": "edges123456789012345678901234567890123"
  },
  "input": {
    "pfs": {
      "glob": "/*",
      "repo": "images"
    }
  },
  "transform": {
    "cmd": [ "python3", "/edges.py" ],
    "image": "pachyderm/opencv"
  }
}
```
37 chars seems to work fine. 

Creating a pipeline with more than 63chars errors (expectedly) differently:
```
pc create pipeline -f ~/pachyderm/examples/opencv/edges.json
Pipeline name is longer than 63 characters: %!(EXTRA int=64)
```

2. Starting a pipeline name with a `-` fails and gives no way to delete the pipeline that I can find. Ending a pipeline with a `_` or `-` gets stuck in starting. Even `delete all` fails:
```
pc list pipeline
NAME                                  VERSION INPUT     CREATED        STATE / LAST JOB
1-_                                   1       images:/* 3 minutes ago  starting / starting
-_                                    1       images:/* 4 minutes ago  failure / starting
edges12345678901234567890123456789012 1       images:/* 11 minutes ago running / starting

pc delete all
All ACLs, repos, commits, files, pipelines and jobs will be deleted.
Repos to delete: 1-_, -_, 123456789012345678901234567890123456789012345678901234567890123, 123456789012345678901234567890123456789012345678901234567890, edges123456789012345678901234567890123, edges12345678901234567890123456789012, images
Pipelines to delete: 1-_, -_, edges12345678901234567890123456789012
Are you sure you want to do this? (y/n):
y
error deleting workers: could not list services: unable to parse requirement: invalid label value: "1-_": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**Comment by adelelopez** [comment]
I added the character check recently https://github.com/pachyderm/pachyderm/pull/3976/files

**Comment by JoeyZwicker** [comment]
@adelelopez that only checked for max characters which my test above confirms is fixed in 1.9.4 (was not in 1.9.3). It's like the specific user issue is fixed in 1.9.4, but I happened to find other character funny-business that can occur.

**Comment by nitinjainsj** [comment]
Can you please check if this is correctly documented?

**Comment by svekars** [comment]
@nitinjainsj this is partially documented: https://docs.pachyderm.com/latest/reference/pipeline_spec/#name-required. Need to update the max number of characters to 64. Otherwise, I think the description is accurate.
