### ISSUE TITLE
Unexpected behavior when creating a branch that a pipeline subcribes to

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1499]
Steps to reproduce:

* Create an input repo
* Create some commits on the same branch (but not `master`)
* Create a pipeline that processes `master` from the input repo
* Tag the branch as `master`

What happens:

Only the head gets processed.

What do you expect to happen:

The entire branch gets processed.

**Comment by sjezewski** [comment]
stale
