### ISSUE TITLE
Pipelines should receive commits in deterministic, chronological order across multiple inputs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1500]
Currently if a pipeline subscribes to multiple inputs, the existing commits are returned in chronological order within each repo, but not across repos.  That is, when a pipeline subscribes to repo A and B, the pipeline might receive some (ordered) commits in A before some (ordered) commits in B, even if those commits in A were made after the commits in B were made.

Ideally, we want to preserve chronological ordering of commits even across inputs, so that pipelines created after commits were added spawn the same set of jobs as pipelines created before the commits were added.

**Comment by sjezewski** [comment]
I believe this will be addressed in the 1.7 commit invariance PR, right @msteffen ?

**Comment by jdoliner** [comment]
This was indeed addressed in the 1.7 commit invariants PR.
