### ISSUE TITLE
Release script tweaks

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1514]
I need to update the doc links _before_ the goxc stage runs, otherwise the wrong commit is tagged, and the docs will be exactly one commit behind what we need them to be.

Probably easiest to make the committing part of the release process at this point.

Also - update the release doc instructions to be a bit more accurate / reflect this change.

**Comment by sjezewski** [comment]
Also -- I need to make the check that validates your commit is on origin better. If you haven't pushed to origin, then the goxc bug will cause the new tag to be pointed at whatever is HEAD of master on origin, not the commit you have locally.

**Comment by sjezewski** [comment]
See the comment on #1515 about wrong download URLs. This needs updating too

**Comment by sjezewski** [comment]
To address the needs of the UI deploy, we'll need to increment the `defaultDashImage` value in `src/server/pkg/deploy/cmds/cmds.go` whenever we cut a release.

**Comment by derekchiang** [comment]
I believe I've fixed the issues mentioned in the first and third comments since 1.4.1.

**Comment by sjezewski** [comment]
Closing as this is mostly stale.

The goxc commit checking is still an issue, but lately our release documentation has been smart enough that it hasnt been an issue.
