### ISSUE TITLE
Use Kubernetes Deployments and ReplicaSets instead of ReplicationControllers

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#1529]
It seems that Kubernetes are suggesting to use Deployments instead of RelicationControllers.
From my (small) personal experience, they are very easy to work with.

**Comment by Southclaws** [comment]
I've always wondered this and just assumed it's for backwards compatibility.
Still, would be nice to see a migration to what's recommended as long as there are no downsides.

**Comment by sjezewski** [comment]
We now use deployments
