### ISSUE TITLE
Remove pps.JobStatusType.JOB_STATUS_TYPE_CREATED

### ISSUE THREAD

**Issue by peter-edge** [pachyderm/pachyderm#153]
We have a created_at field on persist now, we want to do one of two things:

- Remove just for persist layer, have an implicit status CREATED for api layer if no status
- Remove completely, assume no status means created including for API user

**Comment by jdoliner** [comment]
I think removing completely is best.
It seems pretty reasonable that if we're returning info about a job that means it's been created.
