### ISSUE TITLE
Verbs first-class in pachctl

### ISSUE THREAD

**Issue by abourget** [pachyderm/pachyderm#1534]
Like Kubernetes,s `kubectl`, all verbs are first-class, and resources or things on which you can apply those verbs are one level deeper, like:

* `kubectl get pods`
* `kubectl get pod`
* `kubectl create secret`

etc.. It'd be great to have the verbs top-level with `pachctl` too:

* `pachctl list jobs`
* `pachctl list job`
* `pachctl list repos`
* `pachctl list files`

I think when you want to do an operation, you first clearly know the verb you want to apply.. I want to delete things, create things.. and then only must you discover the exact name of the thing on which you want to apply that verb. It makes sense, and keeps things less cluttered.

Also, notice how `kubectl` allows the use of plural or singular forms.. I hit errors regarding that all the time.. trying `list-repos` .. but finding out it doesn't exist.

If we're at it.. why not align the `get` / `list` operations, and `describe` / `inspect` verbs.. to something more similar to `kubectl` ?

What do you think ?

**Comment by Southclaws** [comment]
+1

**Comment by abourget** [comment]
I'd also like to have `pachctl logs job/job-id` (with `-f` ?), that would mimic `kubectl` better too.. and it's a different verb.. `get-logs` mixes up things :)

**Comment by JoeyZwicker** [comment]
Subsumed by #1476 since this is likely to be a docs change over an actual command change.

**Comment by gabrielgrant** [comment]
Not clear to me why this should just be a docs change? Seems fairly straightforward to make this change in a backwards-compatible way: since we don't have any nouns named "get" "create" "list" etc, we can have both forms work for a couple releases while we deprecate the old forms and slowly migrate over our documentation

I find myself tripping on the mismatch in command naming conventions between kubernetes and pachyderm (is it inspect, get, or describe??) practically every time I'm poking around a cluster

**Comment by Tryneus** [comment]
This should be done in `v1.9.0` - commands are now `verb noun` (with backwards compatibility for deprecated commands like @gabrielgrant mentions).  Like requested, e.g. `pachctl list` will output the possible subcommands:

```
$ pachctl list
Print a list of Pachyderm resources of a specific type.

Usage:
  pachctl list [command]

Available Commands:
  datum       Return the datums in a job.
  file        Return the files in a directory.
  branch      Return all branches on a repo.
  job         Return info about jobs.
  pipeline    Return info about all pipelines.
  commit      Return all commits on a repo.
  repo        Return all repos.
  transaction List transactions.

Flags:
  -h, --help   help for list

Global Flags:
      --no-metrics           Don't report user metrics for this command
      --no-port-forwarding   Disable implicit port forwarding
  -v, --verbose              Output verbose logs

Use "pachctl list [command] --help" for more information about a command.
```

(Also `pachctl get-logs` is now just `pachctl logs` for some extra parity with kubectl)
