### ISSUE TITLE
Make get-logs more readable

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1536]
Currently it prints a bunch of json structs which are hard to read.

**Comment by dwhitena** [comment]
Also, given that users could potentially have many, many pods up and running but only be processing a small amount of data at a time (large parallelism but a small commit), it might be useful to provide some easy way to let the users/devs know which of the worker pods jobs run on.

This was brought up by a user in Slack.

**Comment by sjezewski** [comment]
I believe there is a way to filter the results. @derekchiang can weigh in

**Comment by jdoliner** [comment]
You can filter by job, pipeline and datum but not by worker. The original part of this issue is fixed by #1539

**Comment by jdoliner** [comment]
This is fixed in 1.4.1
