### ISSUE TITLE
`inputs.from` in pipeline spec should be a string

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1537]
Currently it needs to be a JSON object that specifies a commit, which is unnecessary since we know that the `Repo` field needs to be the same repo from the input anyways.  Therefore `inputs.from` should just be a commit ID (which can be a branch name as well).

**Comment by abourget** [comment]
Could be `from_commit`, to clarify and ease the transition path.

**Comment by jdoliner** [comment]
This should definitely be `from_commit` rather than just `from`

**Comment by sjezewski** [comment]
fixed
