### ISSUE TITLE
delete-pipeline should be able to delete jobs in the pipeline, and stop currently running jobs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1540]
Currently, `delete-pipeline` does not delete the jobs from the pipeline, nor is there an easy way to delete all jobs from a given pipeline.

**Comment by dwhitena** [comment]
Related? https://github.com/pachyderm/pachyderm/issues/1556

**Comment by derekchiang** [comment]
Furthermore, currently running jobs in the pipeline should be stopped as well.  I believe that they are already being stopped; it's just that we are not updating their job states.
