### ISSUE TITLE
A pipeline should run jobs one by one as opposed to running all of them in parallel

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1543]
Currently, a job is spawned as soon as an input commit comes in, even if its parent has not finished.  Thus, for any given pipeline, there might be multiple jobs running in parallel.  This has two downsides:

* Let's say input commit 1 has one datum `(d1)`, and commit 2 has two datums `(d1, d2)`.  Since both jobs run in parallel and `d1` hasn't been processed, both jobs might end up processing `d1`, thus wasting work.
* Since all jobs run in parallel, they contend for workers (each of which can only process one datum at a time).  Thus, it takes longer to see the first couple finished jobs (although the total time it takes to finish all jobs might be roughly equal or shorter).

We should consider running jobs one by one.

**Comment by abourget** [comment]
we have some steps that write to an external DB.. and it doesn't make sense to write out of order..
so it makes re-running this pipeline with `from` a no-go.. as it would go and write out of order..

**Comment by JonathanFraser** [comment]
It would be good to pre-compute the datum diff so that the second job is only processing that which could potentially generate new data. Then processing in parallel would not be a problem.

**Comment by derekchiang** [comment]
@JonathanFraser that's a good idea.  However, if you process all jobs in parallel, it's likely that it takes a while for any given job to complete.  Whereas if you process jobs in order, then earlier jobs will be completed faster (since they get all the cluster resources).

**Comment by JonathanFraser** [comment]
@derekchiang There are two separate issues here. a race condition resulting in double datum processing and job scheduling priority. pre-computing the diffs removes the race condition. On the scheduling side preferring earlier commits is probably a good heuristic.

**Comment by derekchiang** [comment]
@JonathanFraser good points.  We will probably do the simple thing for now which is to run jobs in order.  In the future we can add more sophisticated scheduling logic that would enable us to run jobs in parallel while prioritizing earlier jobs.
