### ISSUE TITLE
Process, best practices for renaming pods

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1545]
Some users are wanting to use unique names for the `pachd` and `etcd` pods.  For example, users may already have an etcd running, so they might want pachyderm's etcd to be `pach-etcd` or something.  Right now this creates some issues.  We should at least come up with some best practices around how to do this and/or implement a way to do it on deploy.

From one user trying to rename `etcd`:

> pachd does not manage to correctly initialize with 1.4
> `env key not set when required: ETCD_PORT_2379_TCP_ADDR main.appEnv``

From another user renaming `etcd`

> related to `ETCD_PORT_2379_TCP_ADDR`, adding that variable in the `env` definition of the pipeline.json, with the value `pach-etcd`, the name of the etcd service, fixes the pipeline.. I just need to put that everywhere.

Some people seem to be able to succesfully deploy with the rename, and others can not.  However, it seems like some complication is added regardless.

**Comment by jonandernovella** [comment]
+1

**Comment by sjezewski** [comment]
Implementation method described here: https://github.com/pachyderm/pachyderm/issues/1549

**Comment by dwhitena** [comment]
@sjezewski @jdoliner is there any update on this or the related https://github.com/pachyderm/pachyderm/issues/1549?  Had some users asking today.

**Comment by jdoliner** [comment]
I think the best recommendation for this is to just use a k8s namespace. That's probably going to be a lot cleaner than trying to bake the namespacing into the names.

**Comment by sjezewski** [comment]
agreed
