### ISSUE TITLE
Parallelism Default if left unspecified

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1546]
Currently it defaults to `coeff:1`. I think this is worth discussing as we've had 4 instances of users confused or caught off guard by this in the last day including @sjezewski and I. 

Defaults should generally do either the “smart” thing or the “simple” thing. In this case we chose smart and had parallelism default to using the number of nodes in the cluster -- not unreasonable. But perhaps it’s worth rethinking and having it do the simple thing and just be `const:1`. Single-worker pipelines are exactly what users get when they run things locally so it abundantly clear to users that if they want more than one container when they run it on a cluster that they should crank up parallelism.

**Comment by sjezewski** [comment]
stale
