### ISSUE TITLE
Namespace k8s deployment

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1549]
I think its time we put our pods into a separate namespace. 

We've seen a few users that are already running an `etcd` instance for their own purposes in their k8s cluster. They've worked around this in 1.4 by going through the deploy manifest and changing all names from `etcd` to `pach-etcd` ... which is kind of a bummer.

Maybe we don't deploy to a namespace by default, but it should at least be a deployment flag.

**Comment by jdoliner** [comment]
I think this can be accomplished simply using by passing the right kubernetes flags to the `deploy` command. I thought that was a feature we had but I'm not seeing it in master.

**Comment by jdoliner** [comment]
Also was there a reason this was closed?

**Comment by sjezewski** [comment]
I closed it because it was born of the same discussion that generated #1545 (which I linked to this issue).
