### ISSUE TITLE
Egress feature should sync, not upload

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1550]
We should make sure we're syncing the output data to an object store ... not just uploading the latest files.

Right now I believe we do the latter ... which is pretty unhelpful if the names of files are changing.

**Comment by jdoliner** [comment]
This would be pretty nice to have, also would be useful to see if we can use etags to make sure we don't upload the same data twice.

**Comment by sjezewski** [comment]
Totally - we want to avoid that as much as possible.

I think s3 has an rsync like feature (which only uploads new things). I'm hoping each client has something similar.

**Comment by jdoliner** [comment]
I think s3cmd has an rsync like feature but I don't see it anywhere in the client library. I think we're likely going to need to roll our own for clients which makes this a bit trickier.

**Comment by sjezewski** [comment]
Yea you're right.

We agreed the easy tactical thing to do here is either:

A) upload under a prefix (e.g. the commit ID)

Advantage: super simple to implement, and gets us 'correctness' for what a user wants
Disadvantage: a user needs to lookup the latest commit (which doesn't really suit the use case ... this is intended for users who are not techincal and 'just want to see a lsit of files' and may not even have access to the p7m cluster)

B) delete the contents, then upload

Advantage: gets us correctness + ease of use for all users
Disadvantage: deleting obj from a bucket can be really time consuming (as I'm finding out when trying to do this cleanup for our AWS buckets)

---

I think we'll go w B for now. It might be slower ... but it gets us closer to the finish line we want ... and is probably step1 in rolling our own rsync like feature.

**Comment by sjezewski** [comment]
stale
