### ISSUE TITLE
Add support for node-selector per job

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1551]
This may or may not be implemented as part of the GPU feature, but want to document a use case.

Users have a large k8s cluster, and use different nodes for different things. They've provisioned ~100nodes, and ~12 are for pachyderm processing. When we do our 'coefficient' based scaling, we don't want that to apply to all the nodes, just the ones that they've provisioned for pachyderm.

**Comment by sjezewski** [comment]
GPU issue is #1401

**Comment by sjezewski** [comment]
And to make it clear what the consequences of not having this ... a user reported that without the selector, k8s scheduled too many worker pods, and other apps got evicted. Not good.

**Comment by sjezewski** [comment]
This is a duplicate of #1547

**Comment by jdoliner** [comment]
I'm not sure if #1547 is exactly the same thing, although it seems related. Also I don't think GPU is a great example of a use case for this because k8s 1.6 now has GPU requests as a first class part of the API so there's no need to meddle with explicit node-selectors.

**Comment by sjezewski** [comment]
#1547 came out of the same discussion in #users 

I agree ... GPU implementation could be related, but is likely to not be since its getting first class support.
