### ISSUE TITLE
Resource requests

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1553]
Don't see it there or anywhere else in the docs. Just had to explain to a user by pointing to the fruitstand.

**Comment by jdoliner** [comment]
Does this even exist yet in 1.4? I can't seem to find any evidence of it in the protos.

**Comment by jdoliner** [comment]
Does this even exist yet in 1.4? I can't seem to find any evidence of it in the protos.

**Comment by sjezewski** [comment]
You're right ... it got pulled out. It was on master before 1.4 landed. Unclear if that was from a funny merge or intentional.

**Comment by jdoliner** [comment]
I think I recall that it was intentional, but it shouldn't be too hard to add it back in.

**Comment by derekchiang** [comment]
Fixed by #1676 and #1683
