### ISSUE TITLE
Update worker to make sure its not over-reporting metrics

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1555]
With job-shim, we were setting the type of event / user metadata so that the events were delineated from user events.

If this isn't getting set properly, its possible that we're over-reporting metrics.

**Comment by sjezewski** [comment]
This is related https://github.com/pachyderm/pachyderm/issues/1113

**Comment by jdoliner** [comment]
@sjezewski is this still an issue?

**Comment by jdoliner** [comment]
And is it worth doing for 1.5

**Comment by sjezewski** [comment]
I need to revisit this to see if it's still valid.

**Comment by jdoliner** [comment]
Closing this until we have concrete evidence that this is an issue.
