### ISSUE TITLE
Add pachctl kill-job <job_ID>

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1556]
If you have a runaway job as part of pipeline (i.e. long-running, is on its 2nd of 3 restarts, and you've already found the bug in your code and want to call update-pipeline), there should be a way to just manually "fail" a job. This should have exactly the same end state as if the job had retried 3 times and then was marked as failed, but we give the user a way to short-circuit that.

**Comment by derekchiang** [comment]
We've added `stop-job` for this purpose.
