### ISSUE TITLE
Worker side deduplication.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1558]
Right now if a worker outputs a datum whose content is already present in the object store that data will be deduplicated but not until the content is uploaded to pachd and written to the object store. This is an opportunity for a pretty big optimization by hashing the content locally and dispatching an `InspectObject` to the object store to see if it's already present, if it is we can just reference the object and avoid uploading.

This is particularly handy for bucketing steps in which data isn't transformed in anyway but just rearranged for parallelism reasons.

**Comment by JonathanFraser** [comment]
This is probably related to #223

**Comment by JonathanFraser** [comment]
A secondary optimization can be performed here in the case of lazy pipelines. In that case, if one of the input pipes is copied into /pfs/out the worker can elide all of the data transfer.

**Comment by derekchiang** [comment]
We should check if the datum exists in parallel to uploading the datum, so as not to slow down the common case where the datum doesn't exist.  The upload can be cancelled via context cancellation if it turns out that the datum does exist.

**Comment by jdoliner** [comment]
We now do this.
