### ISSUE TITLE
Bucketing / time windowing cook book example

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1560]
This is a common workflow in data science and one that can be done pretty elegantly with the 1.4 data model. This example will use time series data bucketed into time windows but it should apply generically to bucketing on any other feature. @JoeyZwicker and I talked about having this be an extension of the existing fruitstand demo so that's what I'm going to use here.

### Input
Input is a repo called `sales` that contains files whose names are timestamps and whose content looks like:

```
apple 3
banana 5
orange 10
```

having the files names be timestamps isn't strictly necessary for bucketing but it's a good practice to promote since it leads to order outputs, (at least once #1468 is fixed)

### Bucketing / Windowing

There are a couple of ways that a user might want to window their data, for example they might want it broken up into discreet weeks, or into overlapping 7 day windows, both are easy to do in pachyderm. The bucketing operates on the `sales` repo with a glob pattern of `*` and should copy each file into a directory for each of the buckets it corresponds to. For example, if you wanted a bucket for each week of the year you might have dirs called `1`, `2`, `3`, `4` etc. Input files from Jan 1st - Jan 7th would be written as `1/timestamp`, Jan 8th - Jan 14th as `2/timestamp` etc. If you want overlapping time windows of 7 days then you might have directories called `01-01`, `01-02` meaning the window beginning on Jan 1st, the window beginning on Jan 2nd etc. A file from `01-07` would be written to `01-01`, `01-02` ... `01-07`.

Notice that copying files around will be made much more performant by #1558.

### Processing

The processing step should consume the bucketed data with a pattern of `*`, this means the code will get run with a single bucket to process each time. In the fruit stand example this is where you'd total up the apples oranges and bananas sold. The only workflow question here is whether or not you process partial data, i.e. if week `1` only contains files from Jan 1st do we process a partial window or wait until we have a full window? If you don't want to process a partial window then the code can just exit `0` and not write anything to `out`. Notice that there is one potential snag in that the obvious way to check if a window is complete is to see if it has data for all the days that it should, however if you somehow have a day without data, maybe you didn't sell any fruit that day, then you'll never process that window. This can be solved with a dummy data file that does nothing but signify "data from this day has been received."

**Comment by JoeyZwicker** [comment]
@dwhitena lets talk through this together next week. I'd like to build this into the fruit stand example and have it as part of the cookbook. 

@abourget, this is an even better way to do your time windowing than we discussed today. It's way more robust and flexible. I will write up a detailed descriptor of the pipelines and then we should chat about it again early next week. Not a big deal if you keep doing it as your are for now, but this structure would be excellent for you especially once #1558 is added.

**Comment by dwhitena** [comment]
Sweet.  Yeah, we will work this into the cookbook @JoeyZwicker.

**Comment by JoeyZwicker** [comment]
Just adding some notes to myself for when we write this doc. 

3 types of time windows that we should have examples for:
- Fixed time windows (e.g. Jan, Feb)
- Moving Time windows: as JD described above
- Shuffle-style time window --> don't have a clear use case for this, but have seen other users asking about "shuffle/reorganization steps" so it might be good to have an example of that.

**Comment by dwhitena** [comment]
Done: http://docs.pachyderm.io/en/latest/cookbook/time_windows.html
