### ISSUE TITLE
Parallelism spec's coefficient should not take the master node into consideration

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1562]
Currently if you have N kublet nodes and 1 k8s master node, and you set coefficient to M, you end up with `(N+1) * M` worker pods.  Instead, you should get `N * M`, since pods can't be scheduled on the master node anyways.

**Comment by jonandernovella** [comment]
Please search into the current issues before posting. Issue aready posted in #1547.

**Comment by jonandernovella** [comment]
#1547 is related to this.

**Comment by derekchiang** [comment]
Oh didn't see that issue.  Closing this.
