### ISSUE TITLE
Recursive, enhanced get-file

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1564]
Do we want recursive functionality on `get-file` similar to `put-file`.  Also, it may be nice to add some naming functionality for `get-file` similar to `put-file`.  I guess more generally, `get-file` is not at parity with `put-file`, so we may want to make these more unified in terms of user interaction.

This was spawned by discussion in the users Slack:

> I have another question - it's somewhat difficult getting files _out_  from a repo using `pachctl`
> `pachctl get-file` does not allow for a `recurse` option, so you need to get each file individually.
> Plus, there is no option for specifying the output file. You have to use shell redirection, and that will only work well for text files.
> What was the use case you had in mind for getting files out of repos?
> Using a client API (like `pypachy` :wink:) can solve this, but this too needs implementing

**Comment by jdoliner** [comment]
This sounds more like `rsync` functionality than `get-file` I'm not sure if it makes more sense to extend `get-file` or add a new command. We've been talking about splitting some of the more complicated functionality of `put-file` out into it's own command as well.

**Comment by derekchiang** [comment]
I had thought about adding a `clone` command similar to `git clone`, but extending `get-file` with a `--recursive` flag actually seems to make a lot of sense.
