### ISSUE TITLE
How about a hello world example and something user-oriented linked from README?

### ISSUE THREAD

**Issue by rrnewton** [pachyderm/pachyderm#157]
I heard the [Software Engineering Daily podcast](http://softwareengineeringdaily.com/2015/10/11/replacing-hadoop-with-joe-doliner/) and was psyched.  I was ready to mount pfs on my macbook and run grep, as described in the podcast.

But the main website basically links to the github repo (README) as documentation.  And it kind of describes installation and then stops.  What next?  Once I get to the point of having the pfs CLI, how can I at least run something that uses pfs?

**Comment by jdoliner** [comment]
Hi @rrnewton. Really sorry we haven't made this better yet. We're still putting the finishing touches on this release functionality wise and are waiting for a few features in other projects (kubernetes and docker) before everything will work. I'm going to add this issue to our v0.10 milestone to make sure we get this fixed before shipping.

I'm also going to make a pass right now to update things. Check back soon :)

**Comment by padioca** [comment]
Any update on this? I'm in the exact same boat...

**Comment by JoeyZwicker** [comment]
We're working on the documentation right now. The plan is post a distributed `grep` tutorial in the next few days. The tutorial will include everything from installing Pachyderm and getting the cluster running, to adding data into pfs and then analyzing it with pipelines. 

We're really sorry for the delay on this -- we've just been working a ton on the development side of things and the documentation is lagging behind, but that'll be fixed this week! Thanks in advance for your patience and we're thrilled to see your interest is playing with Pachyderm.

**Comment by padioca** [comment]
No worries, thanks for the update!

**Comment by cxxly** [comment]
Have this updated? I haven't found a example, and the document is not clear.

**Comment by jdoliner** [comment]
Alright our README now links directly to the fruit stand demo which is our go to quickstart guide. I'm going to call this one closed.
