### ISSUE TITLE
Alluxio storage driver integration

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1573]
[Alluxio](https://github.com/Alluxio/alluxio) is a storage cache that allows you to interact with multiple storage drivers without effort through a unified API. The files are stored in memory which allows faster access.

Alluxio has an integration with [FUSE ](http://www.alluxio.org/docs/1.4/en/Mounting-Alluxio-FS-with-FUSE.html) which we already support. It is unfit to boost performance of data pipelines due to limitations of FUSE and interaction between C & Java.
We can write a guide that walks a user through integrating the system using FUSE if all he needs is data source abstraction.

Alluxio recently released a [REST API](http://www.alluxio.org/docs/1.4/en/File-System-API.html#rest-api) that allows us to build our own clients.
It is much faster and I think the community will benefit a lot from such integration.

**Comment by thedrow** [comment]
Note that Alluxio has made a [Go client](http://www.alluxio.org/docs/1.6/en/Clients-Go.html) available which should ease implementation.

**Comment by thedrow** [comment]
FYI occasional development of this feature occurs in https://github.com/thedrow/pachyderm/tree/alluxio-client
PRs are welcome.

**Comment by JoeyZwicker** [comment]
Thanks for pointing this out and all the helpful info. We'll be doing our
planning for the next release over the coming week and will let you know if
we're able to schedule this as part of it.

**Comment by jdoliner** [comment]
We haven't had an other requests for this and there hasn't been much work done on it, so I'm going to close for the time being. Feel free to reopen if work commences and there's a PR for us to look at.
