### ISSUE TITLE
Lazy is flaky in 1.4

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1576]
We've had a number of user reports of it failing in various ways although it doesn't seem to be 100% consistent. Lazy seems to work for simple workloads, such as those we test for so a bit of exploration needs to be done about when and where it breaks.

Lazy also has the known "bug" that reading from a pipe twice will cause a hang. As part of fixing this issue we should also fix that since it's not too hard to do now.

**Comment by derekchiang** [comment]
Removing `high priority` tag until we can reliably reproduce this.

**Comment by sjezewski** [comment]
stale
