### ISSUE TITLE
Doc linter

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1577]
We have several issues in docs that need to be manually checked every release such as broken links and working examples. I'm sure there are many more I don't know about. Having an automated way to check these things would save us a lot of time writing docs and improve their quality.

**Comment by JoeyZwicker** [comment]
True. But do we have ideas on how we actually want to go about this? I'm sure there are link-checker tools out there we can try. @dwhitena?

This is pretty low priority I think because things seem to be working ok for now.

**Comment by sjezewski** [comment]
stale
