### ISSUE TITLE
Writing to a repo's directory crashes pfsd

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#158]
Steps to recreate:

```
pachctl mount
pachctl create-repo foo
echo foo > /pfs/foo/file
```

**Comment by mattnenterprise** [comment]
This doesn't crash pfsd for me running everything locally in docker. I get
> bash: /pfs/foo/file: Input/output error

**Comment by jdoliner** [comment]
Cool, that's an acceptable behavior then. Wish we could make that error message better, but I'm not sure if fuse will allow us. Closing.
