### ISSUE TITLE
Union input method

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1582]
Currently if a pipeline takes 2 inputs it will see a cross product of those inputs, there should be a way to also see a union of those inputs.

This will likely require rejiggering the schema for the pipeline's inputs a little bit.

**Comment by JoeyZwicker** [comment]
duplicate of #1491 I think.

Many of the issues listed on the board today already have GH issues open.

**Comment by jdoliner** [comment]
So it is, it's actually frustratingly difficult to find the issues via search.

Would you mind just closing dupes I've opened when you find them but transferring over the milestone and tag info when you do? I just did so with this one.

**Comment by JoeyZwicker** [comment]
yup no problem! Especially for issue like this where we didn't have a good name for it, I'll make sure to do it when I see it.
