### ISSUE TITLE
Incremental pipelines in 1.4

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1584]
Incremental pipelines were a feature in 1.3. In 1.4 they'll be slightly different.

In 1.4 incremality happens on a per datum basis, so if your glob pattern is `*` and a file `foo` is written to in successive commits it will be processed incrementally. This means that the second processing of `foo` will see the output of the first in the `/pfs/out` directory. One open question is how to display `foo` to the user options we've considered:

- show new and old versions of the file possibly under `/pfs/repo` and `pfs/repo^` since we're going to start using that syntax
- show some sort of a diff, the question is what sort of diff. Since diffing algorithms tend to be pretty specific to the data they're diffing and we can't make many assumptions about the data stored in pfs this can be tricky.

**Comment by sjezewski** [comment]
stale
