### ISSUE TITLE
get-file put-file progress

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1589]
This has been requested by a number of people, I'm not entirely sure what this would entail though. Would the progress be returned by the api? Maybe as part of a stream in the other direction? I'm not sure.<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/138'>Zendesk ticket #138</a>)<br>gz#138</i>

**Comment by RaananHadar** [comment]
@jdoliner this one seems to have fallen through the cracks, would love to see this in a future version.

**Comment by jdoliner** [comment]
This has been implemented in: https://github.com/pachyderm/pachyderm/pull/5648
