### ISSUE TITLE
Make repo size better

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1590]
This is one we've discussed a lot, it's a tricky tradeoff between complexity of computing the value and accuracy. Hopefully we can find something fast that's pretty accurate. We shouldn't consider anything too slow for this since it's not crucial that this value be correct.

**Comment by abourget** [comment]
Perhaps the `list-commit` view could show the total size, and incremental size (what was added in *this* commit)..

I'm not sure what the `SIZE` column in `list-commit` _is_  right now.

**Comment by abourget** [comment]
Upon commit, that could be saved somewhere, and summed up easily for `list-repo` ?

I understand we could be tempted to list the size of the backing store, but most of the time, I'll want to know if my data is right, if I've been receiving the right amount of data, to assess if my pipelines are properly working, etc.. that's going to be day-to-day. Backing-storage will be a concern once in a while.. but I wouldn't put that first and foremost. Perhaps behind `-o wide`  ? :)
