### ISSUE TITLE
RPC error when getting logs for running job.

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1605]
A user reported this, but I actually ran into it as well.  The scenario is:

1. you run a job
2. something happens where that job is running longer than you expect, it has to restart, etc.
3. you want to get logs, so you run `pachctl list-job`, and then `get-logs`

This results in: 

```
➔ pachctl list-job
ID                                     OUTPUT COMMIT                                 STARTED             DURATION            STATE               
cf1f9928-9e5f-4064-9754-d49e45107621   -                                             11 hours ago        -                   running    
172e5dfb-f04c-4421-9037-23efb31963d0   checkpoint/8759b80e68c74378be0bc02d621d43d0   14 hours ago        3 hours             success    
➔ pachctl get-logs --job cf1f9928-9e5f-4064-9754-d49e45107621 --raw
rpc error: code = 2 desc = invalid character 'm' looking for beginning of value
```

Note, this could be related to the problem we were seeing with @jdoliner and @jonandernovella, where there is a job that runs without an output commit.

**Comment by jonandernovella** [comment]
@dwhitena @jdoliner Indeed. This seems to coincide.with my issue.

**Comment by dwhitena** [comment]
My setup to create this scenario was the following:

1. Pachyderm + Minio in GKE
2. Pachyderm 1.4.1
3. Running this pipeline https://github.com/pachyderm/pachyderm/tree/master/doc/examples/ml/tensorflow
4. On the "maps" dataset that can be found here: https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/

**Comment by sjezewski** [comment]
stale
