### ISSUE TITLE
Detect apiVersion requirements when deploying to different versions of Kubernetes

### ISSUE THREAD

**Issue by Southclaws** [pachyderm/pachyderm#1609]
Tried a Kubernetes 1.6 deployment and because it seems that `StorageClass` has moved from `v1beta1` to `v1` and so it errors out on deployment.

A potential solution could be to map these differences to Kubernetes versions then check the Kubernetes server version on deployment and adjust the manifests accordingly.

**Comment by sjezewski** [comment]
stale

In general, I would like to have better support, or clearer conventions about k8s API version support. Generally speaking, we support the latest release, and the penultimate release.
