### ISSUE TITLE
Fix hang following failed `finish-commit`

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#162]
Steps to reproduce:

```shell
$ pachctl create-repo foo
$ pachctl finish-commit foo bar # commit doesn't exist
$ pachctl start-commit foo # now hangs
```

looks like we have a locking issue when calls to finish-commit fail.

**Comment by mattnenterprise** [comment]
This currently works for me:

> $ pachctl create-repo foo
$ pachctl finish-commit foo bar
rpc error: code = 2 desc = "commit foo/bar not found"
$ pachctl start-commit foo
af44ba6e7aba4e399a563ca5397f3586

**Comment by jdoliner** [comment]
Nice, makes sense that this would be fixed too given the new storage backend. Closing.
