### ISSUE TITLE
Ergonomiz: `list-repo` to show `LAST COMMIT` instead of `CREATED`

### ISSUE THREAD

**Issue by abourget** [pachyderm/pachyderm#1634]
The time delta shown in `list-repo` currently shows `CREATED` time ago.

I'm more interested in knowing the current state of the pipeline, what ran, and when.. to do a quick checkup on the state of the pipeline. CREATED might be useful when you create it.. to confirm it's good.. but I'll be interested in the LAST COMMIT time more often.

Perhaps `CREATED` could be behind `-o wide`, following K8s conventions.

**Comment by sjezewski** [comment]
stale
