### ISSUE TITLE
Use Go's native cross-compilation functionality instead of goxc

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1640]
Currently we use [goxc](https://github.com/laher/goxc) to cross-compile `pachctl`, but cross-compilation has had first-class support [since Go 1.5](https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5), and goxc itself has effectively been deprecated.

We should instead use Go's own cross-compilation functionality.  For automatically releasing on Github (which goxc does for us rn), we can use the more actively maintained [github-release](https://github.com/aktau/github-release) project.

**Comment by sjezewski** [comment]
stale
