### ISSUE TITLE
`ListJob` should allow searching by output commit

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1646]
Currently [`ListJobRequest` has an `input_commit` field](https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.proto#L224)  (although it is actually [not implemented at the moment](https://github.com/pachyderm/pachyderm/issues/1645)). It should also have an `output_commit` field to facilitate finding which job created a given commit

**Comment by jdoliner** [comment]
Implementing `OutputCommit` is already part of #1645.
