### ISSUE TITLE
JobInfos' `outputBranch` field is inaccurate after pipeline a update

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1647]
A [job's `outputBranch` field](https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.proto#L115) hold the name of the branch a job output to at the time the job was run, but if a pipeline is updated, then the name of old jobs' output branches will change. Should old job records be updated so their `outputBranch` field points at the current name of the branch that it output to?

**Comment by sjezewski** [comment]
stale
