### ISSUE TITLE
Undeploy doesn't get rid of dynamically created etcd disks

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1648]
Had a user deploy to AWS with `--dynamic-etcd-nodes=3`.  Then, they did `undeploy` and deployed again.  When they deployed again they used a new bucket and, again, dynamically created etcd disks.  When the cluster came up all the old metadata was there (pipelines, repos, etc.).  I'm assuming this is because it used the disks for etcd that were created in the first deploy?  Is this expected?  It's a bit confusing I think.

**Comment by msteffen** [comment]
This is deliberate. You need to pass (IIRC) `pachctl undeploy --all`. The motivation is that when etcd disks are dynamically provisioned, they are also dynamically deleted when the PVC that has claimed them is deleted from Kubernetes. Therefore we don't delete the PVC without the `--all` flag to avoid users unexpectedly losing their data.

**Comment by msteffen** [comment]
(feel free to reopen, obviously)
