### ISSUE TITLE
`FlushCommit` and pipeline execution issues

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1649]
Currently there are a couple of feature that were present in the 1.3 provenance and execution system that aren't present in 1.4:

- `FlushCommit` blocks indefinitely if the job errors, it should return an error instead.
- Pipelines will pair commits that don't match in provenance, i.e. if you have repo `A`, pipeline `B` which takes `A` as input and pipeline `C` which takes both `A` and `B` as input. Then `C` will process inputs from `A` with commits in `B` that aren't the result of processing the matching commit in `A`, this can cause all sorts of unexpected behaviors in user code such as trying to normalize numbers to the `0-1.0` range and winding up with numbers greater than `1.0`

**Comment by sjezewski** [comment]
stale
