### ISSUE TITLE
launch-kube failing on bare metal

### ISSUE THREAD

**Issue by Binaryblade** [pachyderm/pachyderm#165]
I'm having an issue booting the development cluster on my machine. It gets to the launch-kube step and the created container fails to start stating:
[8] System error: stat /var/lib/docker/btrfs/subvolumes/\<subvolID\>/sys/fs/cgroup/openrc/docker: no such file or directory

navigating to that directory, and it does indeed exist so I'm a bit confused. 

This maybe a docker error or a kubernetes error but I'll start off here, maybe you guys have some ideas.

Docker version: 1.9.1
Go Version 1.5.1
OS: Gentoo

Any help would be appreciated, thanks

**Comment by jdoliner** [comment]
Does this fail immediately or do some of the containers come up?

`launch-kube` is just running a script which starts 3 docker containers, if none of those containers are coming up then it's probably a problem with Docker.

Also can you run other containers, like maybe just `docker run -ti ubuntu bash` and see if that works.

**Comment by Binaryblade** [comment]
I can run the ubuntu container and the etcd container comes up fine, its the created container that is having difficulty.

**Comment by Binaryblade** [comment]
realized I didn't escape the \< braces in the original ticket, there is a subvolumeID in that path string.

**Comment by jdoliner** [comment]
Hmm, so it's either the kubelet or the proxy that's failing. What does `docker ps` and `docker ps -a` look like after the failure?

**Comment by Binaryblade** [comment]
It's the kubelet, the script doesn't reach the proxy.

**Comment by Binaryblade** [comment]
I've tried manually starting the created container outside the scrip and I receive the same error.

**Comment by jdoliner** [comment]
Hmm, I think this might be an issue with btrfs storage driver for docker. That's the only thing I can think of that's different. I'm on devicemapper would you mind trying with that?

**Comment by Binaryblade** [comment]
swapping the storage manager seems to have fixed the problem. It might have something to do with my root file system is also running btrfs.

**Comment by jdoliner** [comment]
Yeah there can be some weird interactions with storage drivers. Glad it's fixed. Is this safe to close?

**Comment by Binaryblade** [comment]
For this yeah, I'll upstream the issue.
