### ISSUE TITLE
Users need a mechanism to recover from bad code

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1652]
A user is running up against the `skipping input, as it's already been processed` error.

In particular, they want to re-run their code + input data. The reason that its non deterministic is that the VM's root volume filled up.

Specifically ... they were extracting some large files (under the `/pfs/out` directory so that their working directory was on the root FS not the container FS), and gzip reported an 'out of disk' error.

The user code should exit on any errors. But we can't assume that user's write perfect code off the back, and so we need to give them a good way to recover from a case like this.

It's not immediately clear to a user (who has just upped their root volume size to handle the disk issue) that they also need to modify their code to get this to re-run.

So maybe we have a 'developer' mode where we always reprocess data? 

Or perhaps we need heck of a lot better tooling around disk space filling up. I would like to see that get way easier for users.

**Comment by jdoliner** [comment]
I don't understand what's being request here. The way to recover from bad code is to write new code and use `update-pipeline`.
What does this issue cover that #1654 doesn't?

**Comment by dwhitena** [comment]
I'm not sure about @jdoliner's suggestion above and how this is different.  However, I can also report that this "... as it's already been processed" error seems to also be popping up in the PharmBio pipeline, which is processing large files (~100MB) and outputting corresponding output files to `/pfs/out/`.  See https://github.com/minio/minio/issues/4077#issuecomment-293396028.  

Specifically, after a job fails (e.g., for some file corruption that is likely unrelated), any attempts at re-running the job, or even running `delete-all` and re-creating the job, end up with a job that constantly restarts. The error's in the job logs return:

```
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/014_CRa_H9M5_M470_Pool_03_alternate_pos_low_mr.mzML","hash":"OUxhSfR26Qne9ZaNqNQuS8hgCaQM9oQpLNvrxZg5XFU="}],"ts":"2017-04-11T16:18:49.006889331Z","message":"Received request"}
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/014_CRa_H9M5_M470_Pool_03_alternate_pos_low_mr.mzML","hash":"OUxhSfR26Qne9ZaNqNQuS8hgCaQM9oQpLNvrxZg5XFU="}],"ts":"2017-04-11T16:18:49.007925932Z","message":"skipping input, as it's already been processed"}
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/014_CRa_H9M5_M470_Pool_03_alternate_pos_low_mr.mzML","hash":"OUxhSfR26Qne9ZaNqNQuS8hgCaQM9oQpLNvrxZg5XFU="}],"ts":"2017-04-11T16:19:10.349249468Z","message":"Received request"}
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/014_CRa_H9M5_M470_Pool_03_alternate_pos_low_mr.mzML","hash":"OUxhSfR26Qne9ZaNqNQuS8hgCaQM9oQpLNvrxZg5XFU="}],"ts":"2017-04-11T16:19:10.351032440Z","message":"skipping input, as it's already been processed"}
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/010_CRa_H9M5_M470_L03_K3_alternate_pos_low_mr.mzML","hash":"Knoj3ZrWlc4sH7xCSaJrybKY0r5n6AZqVLgqylasSas="}],"ts":"2017-04-11T16:19:10.360345396Z","message":"Received request"}
{"pipelineName":"MultiPeakPickerHiRes","pipelineId":"324d164714c1425db5b05d9067ca90c1","jobId":"4cff0f80-f4f2-4f4e-b94d-26c47ed67d98","workerId":"pipeline-multipeakpickerhires-v1-vrjr1","data":[{"path":"/010_CRa_H9M5_M470_L03_K3_alternate_pos_low_mr.mzML","hash":"Knoj3ZrWlc4sH7xCSaJrybKY0r5n6AZqVLgqylasSas="}],"ts":"2017-04-11T16:19:10.362667170Z","message":"skipping input, as it's already been processed"}
etc...
```

Note, there may also be some Minio related issues happening here.  But, for whatever reason, when processing large files, it seems like they are also getting into this bad spot.  For them, I don't think `update-pipeline` even fixes this looping.

**Comment by dwhitena** [comment]
I just checked with Jon, and he ran a test.  This sort of restarting loop happens for him even when a job doesn't fail, or when there wasn't a previous job that failed on the data.  For him, it seems to be more related to the processing of larger files.

If you look at the non-raw logs for his job, the codes looks like it processed all the files just fine.  However, the job doesn't ever end.  It just starts looping:

```
[{"path":"/013_CRa_H9M5_M470_Blank_04_alternate_pos_low_mr.mzML","hash":"5Hk/YSV799tZMfJKlB8mv7hiEUH4ttm/CPSx42HUkLI="}],"ts":"2017-04-12T13:32:31.458187621Z","message":"Received request"}
{"pipelineName":"newpipeline","pipelineId":"d2514a890d3a4a84b82a6a4eb015c92a","jobId":"ee02de42-b24f-4aa4-892a-720de35f0d45","workerId":"pipeline-newpipeline-v1-x12t7","data":[{"path":"/013_CRa_H9M5_M470_Blank_04_alternate_pos_low_mr.mzML","hash":"5Hk/YSV799tZMfJKlB8mv7hiEUH4ttm/CPSx42HUkLI="}],"ts":"2017-04-12T13:32:31.461723545Z","message":"skipping input, as it's already been processed"}
{"pipelineName":"newpipeline","pipelineId":"d2514a890d3a4a84b82a6a4eb015c92a","jobId":"ee02de42-b24f-4aa4-892a-720de35f0d45","workerId":"pipeline-newpipeline-v1-x12t7","data":[{"path":"/019_CRa_H9M5_M470_C01_K3_alternate_pos_low_mr.mzML","hash":"tSxgLrLiJFVwTrs+POCEJBXnYmH65O2P+/sHLEFEJdo="}],"ts":"2017-04-12T13:32:31.466704655Z","message":"Received request"}
{"pipelineName":"newpipeline","pipelineId":"d2514a890d3a4a84b82a6a4eb015c92a","jobId":"ee02de42-b24f-4aa4-892a-720de35f0d45","workerId":"pipeline-newpipeline-v1-x12t7","data":[{"path":"/019_CRa_H9M5_M470_C01_K3_alternate_pos_low_mr.mzML","hash":"tSxgLrLiJFVwTrs+POCEJBXnYmH65O2P+/sHLEFEJdo="}],"ts":"2017-04-12T13:32:31.468799930Z","message":"skipping input, as it's already been processed"}
etc...
```

**Comment by msteffen** [comment]
I'll ask Jon about this as well, but I'm curious if pachd is logging `datum %v is queued up for retry`. I have two hypotheses:
1) The datum is being sent to a worker for reprocessing, and the worker is returning an error, causing the datum to be re-queued ad-infinitum. This would be surprosing to me, because the code in worker that returns early if the datum has already been processed (`s/s/worker/api_server.go:400-406`) doesn't seem like it ever returns an error.
2) Once a datum is scheduled for reprocessing, there's no way to un-schedule it (i.e. pachd just keeps re-sending it forever, regardless of what else happens). This would also be surprising to me, because the code in pachd for sending data to workers is pretty simple (`s/s/pps/server/api_server.go:1234 and 1237`). It's just a slice that we append to and then remove the first element from.

**Comment by jdoliner** [comment]
There's definitely at least one bug afoot here. Seems like there might be a few. However I think there's a decent chance that the "already been processed" log messages are a red herring. If a job fails and gets rerun it's likely that there will be datums which have already been processed that won't need to be processed again, it seems this might be misfiring a bit #1654 so we should look at that. The fact that the job never ends is also clearly a problem.

What versions did these bugs occur on?

**Comment by msteffen** [comment]
I am curious why the datum is rescheduled indefinitely (as opposed to terminating with an incomplete output). I'll ask Jon about this as well, but I'm curious if pachd is logging `datum %v is queued up for retry`. I have two hypotheses:
1) The datum is being sent to a worker for reprocessing, and the worker is returning an error, causing the datum to be re-queued ad-infinitum. This would be surprosing to me, because the code in worker that returns early if the datum has already been processed (`s/s/worker/api_server.go:400-406`) doesn't seem like it ever returns an error.
2) Once a datum is scheduled for reprocessing, there's no way to un-schedule it (i.e. pachd just keeps re-sending it forever, regardless of what else happens). This would also be surprising to me, because the code in pachd for sending data to workers is pretty simple (`s/s/pps/server/api_server.go:1234 and 1237`). It's just a slice that we append to and then remove the first element from.

**Comment by msteffen** [comment]
(JD's theory, that it's the job rescheduling, seems most likely to be right to me). One way to do this (which I think would minimize the amount of redundant computation) would be to remove all hashtrees that were added by the failed job from the object store. It might be easier to simply ignore hashtrees that have already been computed when re-running a failed job

**Comment by dwhitena** [comment]
@jdoliner I tried the above both with 1.4.3 and building from master and encountered the same behavior.

**Comment by sjezewski** [comment]
Just as a data point -- the job that I saw was run, marked successful, and so we couldn't run it.

This was a relic of the user code not 'erring out' when it ran out of disk. In this case gzip did emit an 'out of disk' message (but not an error?). In the general case we'll need users to write code that errs (and exits!) when they run out of disk. It's probably not clear to a user how to 'test for that' with their code ... and their only recourse is to 'exit on all errors'. That works for bash (w the magic incantation) and golang (bcz of the err model), but might not be suitable for other languages (R, python, etc). At the very least, if we required that, we should make that _reallllly_ clear in our docs.

As far as the difference from #1654, I want to make sure we address the broader class of errors that this represents. 

I'd define that class as 'stateful things that corrupt job output that arent captured in the hash'. In other words, things that arent the transform or input data changing that can also effect the user's output.

Some examples include: out of disk errors, OOM errors, transient network issues.

In each of these examples, ideally the user's code errs and exits properly. But we're making a development platform. We can't assume that's the case the first time they run the code. Ideally their workflow is something like:

1) try to run the job, it runs out of disk
2) ideally ... pachctl logs report it ran out of disk ... and that their job should fail if this happens ... and that they need to update their code and redeploy
3) they fix their user code and redeploy

Step #2 is the hard part ... we may be able to define and report specific instances. But whitelisting each way it can fail seems hard. The point I'm making is that there are cases when a user may need to 'force' the job to re-run, and we could include a flag for that.

**Comment by derekchiang** [comment]
Capturing the discussion today: we are going to add a command like `pachctl rerun-pipeline`, which basically re-runs the pipeline as if the pipeline has never been run before, i.e. that no de-duplication or other smartness happen whatsoever.

In terms of implementation, `rerun-pipeline` increments the pipeline's `version` field, and internally we will take the `version` field into account when deciding if a datum has been processed.  That is, even if a datum has been processed by `v3` of a pipeline, we still process it again for `v4`.

**Comment by derekchiang** [comment]
In #1685, we made it so that if you update or re-create a pipeline, the input data will be re-processed (even if the manifest is exactly the same as before).  Therefore we consider this issue fixed.

I will open a separate issue for adding `rerun-pipeline` which would be a sugar on top of `update-pipeline -f the_same_manifest --from HEAD_COMMIT`.
