### ISSUE TITLE
Can't get logs when using invalid glob pattern

### ISSUE THREAD

**Issue by brollb** [pachyderm/pachyderm#1656]
I created the following pipeline spec (where `shallow_repo` isn't 3 layers deep):
```
{
    "pipeline": {
        "name": "hello_world"
    },
    "transform": {
        "cmd": ["sh"],
        "stdin": [
            "echo 'hello world'"
        ],
        "image": "ubuntu:14.04"
    },
    "parallelism_spec": {
        "coefficient": 25.0,
        "strategy": "COEFFICIENT"
    },
    "inputs": [{
        "repo": {
            "name": "shallow_repo"
        },
        "glob": "/*/*/*"
    }]
}
```
After running the pipeline, `pachctl list-job` shows that the job has completed but `pachctl get-logs --job=<job id>` doesn't show any logs. Fixing the `glob` field allows me to get the logs but I found it strange that I couldn't get the logs with a bad `glob` field..

**Comment by jdoliner** [comment]
So what's going on here is that if the `glob` pattern doesn't match anything there won't be any logs because no code ever gets run. I'm not quite sure how we'd make this better, maybe `get-logs` could say explicitly "no logs" or something like that.

**Comment by brollb** [comment]
that makes sense. 

Maybe something stating that the job was not run? In my case, I was puzzled about not seeing any logs and had assumed that it ran since I had data in the repo (although I had no parallelizable datum)... It might be nice to have some indication to help people debug bad pipeline jsons..

I wonder if being able to have a dry run for your pipeline specifications would be useful - maybe something that would tell you some metadata about the creating the given pipeline (such as number of datums, commits to be processed, size of the processed data).

**Comment by jdoliner** [comment]
So technically from, pachyderm's perspective, the job was run it's just that running it didn't entail any actual data processing. One thing that may help with this, as of 1.4.3 you can see datum progress in jobs, so if you do `pachctl list-job` you should see a job that succeeded but its progress will be `0 / 0` which is a tip off the glob pattern is wrong.

Having a dry run seems a little bit weird, I'm not quite sure exactly what it would return, but we can think about it a bit more if the datum status stuff doesn't satisfy your needs for this.

**Comment by sjezewski** [comment]
stale
