### ISSUE TITLE
Process datums in batches

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1662]
@jdoliner brought up the issue.  There's a fixed overhead in processing each datum.  The overhead mostly comes from the fact that we process datums in a request-response model, so processing each datum involves a round trip from `pachd` to a worker.  When there's a large number of datums, the aggregated overhead can be large.

We might want to allow for processing datums in batches, similar to how it was in 1.3 (i.e. `shard`).

**Comment by msteffen** [comment]
One possibility would be to download many data to a side directory, and then copy them into `/pfs/<input>` one at a time (and run the user binary each time).

(total aside, but I feel like ideally this side directory would be completely invisible. I've wondered in general whether it would be easy/beneficial to use other mounting tricks when running the user code, like making `/pfs/<input>` read-only)

**Comment by jdoliner** [comment]
Yeah, I think using some mounting tricks could definitely pay dividends. Ideally we'd be able to just symlink in the data the job needs to process.

**Comment by brollb** [comment]
I like being able to process multiple datums in a single job - especially in "map" jobs. 

This is especially relevant when the job has an additional startup overhead. For example, most machine learning (esp. deep learning) predictions/conversions/etc require the loading of the trained model which can be quite large. If we only process a single piece of data at a time, this can add significant overhead to processing the pipeline.

**Comment by gabrielgrant** [comment]
We had some discussion a while ago about ways to stream multiple datums to a process as an optimization for this case of significant user-process startup time being the dominant factor in some pipelines. This requires some sort of signalling between the user's process and pachyderm, so I don't think we came to a conclusion. One pretty obvious option that I'd discussed a bit with @msteffen would be to have a signalling socket that pachyderm writes to once it's shuttled the current datum's files into place and that the user code writes to when it's done with a datum to alert pachyderm that it should move the next datum's file into place (this could operate over stdin/stdout, but that would conflict with the current behavior of treating stdout as log output)

So long as the datum's PFS structure was pre-prepared and moved into the user-visible location as a single atomic move, the user's code shouldn't ever see inconsistent state, but I imagine this could potentially have issues with users' code maintaining references to old datums' files.

**Comment by JoeyZwicker** [comment]
We've continued to see requests for this and may make sense to address in
1.8 as a performance optimization.

**Comment by jdoliner** [comment]
@gabrielgrant good point, everything here has been implemented.
