### ISSUE TITLE
High CPU and memory usage on local deploy

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1672]
Reported by @gabrielgrant.  When he deployed a fresh cluster on his laptop, he was seeing close to 100% CPU usage by `pachd`, and a total of 10G memory allocated by `etcd` (although the resident memory is much lower.

Here's the [heap dump](https://gist.github.com/derekchiang/dce74806fe06b836f910183c9ad6a3a1).

And the [goroutine dump](https://gist.github.com/derekchiang/ddd7c7b90f749511be414d879655d4f3).

**Comment by sjezewski** [comment]
stale
