### ISSUE TITLE
Problem with quickstart on Mac OSX

### ISSUE THREAD

**Issue by mattnenterprise** [pachyderm/pachyderm#169]
I am having problems with getting the quick start to work on Mac OSX. I have the prerequisites met. When I run:

> make launch-dev

It fails to launch the hyperkube container. I get the following error: 

> Error response from daemon: Cannot start container 36d5c85c1f894a52945a98b3f047795554f9292cd06a840a00b3968c121ab949: [8] System error: stat /mnt/sda1/var/lib/docker/aufs/mnt/36d5c85c1f894a52945a98b3f047795554f9292cd06a840a00b3968c121ab949/sys/fs/cgroup/cpuset/docker/36d5c85c1f894a52945a98b3f047795554f9292cd06a840a00b3968c121ab949: no such file or directory
Error: failed to start containers: [36d5c85c1f894a52945a98b3f047795554f9292cd06a840a00b3968c121ab949]

**Comment by jdoliner** [comment]
Hmm it looks like one of the kubernetes containers isn't being created properly. What's the output of `docker ps` following that error?

We've seen problems like this before with different Docker storage drivers. We've had the best results with devicemapper. Would it be a pain to redeploy with `devicemapper` and try again? Here's a tutorial on how that I think should still work: http://muehe.org/posts/switching-docker-from-aufs-to-devicemapper/.

**Comment by mattnenterprise** [comment]
This also happens to me on linux to. I got it to work by mounting the etc/kube directory to the kubelet container. I created a pull-request for this [here](https://github.com/pachyderm/pachyderm/pull/170). I tested it on both Mac OSX and Ubuntu Linux.

**Comment by mattnenterprise** [comment]
So changing the storage driver to devicemapper works. I will delete my pull request and close this issue, as you have already added the fix to the documentation.
