### ISSUE TITLE
Don't deploy known-broken versions the UI

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1690]
As per @sjezewski 's [comment in the UI deployment PR](https://github.com/pachyderm/pachyderm/pull/1688#discussion_r112092658), we have currently hard-codded a value for the deployed UI version. At the moment that seems like a pretty bad solution, because I'm likely going to be fixing pretty major problems and bumping the UI version far more frequently (multiple times per day) than `pachctl` is released, so having an old version hard coded as a default is _far_ more likely to result in users having broken code than the chance of breaking API changes appearing within 1.4.x releases (the version is already a couple days' dev time out of date).

We should either:

- remove the default image name and require an explicitly specified version as a command-line flag: kind of annoying, but at least it's explicit and won't deploy known-bad versions that have already been fixed
- return to getting the latest compatible version from the website, as we'd discussed before: works in most cases (and doesn't require me to make any changes to the UI deployment process :); breaks if gh.io is down, or if there's a breaking change within the 1.4.x release series (this shouldn't happen, though, right? don't we give a compatibility guarantee across patch releases?)
- figure out some scheme using tagging to get the same effect, but relying only on dockerhub versions: removes gh.io dependency, but violates the general advice to not rely on docker's `latest` (and by extension, other tags that are updated to point at different image versions. Eg ["I would strongly advise repository owners to be wary of the latest tag and consider not using it at all"](http://container-solutions.com/docker-latest-confusion/), ["you should just ignore the latest tag. Don’t use it. Don’t be tempted by it"](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375)

**Comment by sjezewski** [comment]
the release process now handles this
