### ISSUE TITLE
Update-pipeline shouldn't launch a job if nothing changes

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1700]
Let's say I have a JSON file with two JSON blobs specifying two pipeline specifications.  Then I want to update my code or cmd for only one of the pipelines.  If I do this and then run `update-pipeline`, Pachyderm will launch a job for both pipelines, even though only one of the pipelines changed. 

In other words, `update-pipeline` will always launch a new job, even if you don't change anything.  This was a little surprising to me.

Maybe we want to run a quick check to see if anything in the spec for each provided pipeline actually changed?  Then, if and only if something changed, launch the job.

**Comment by jdoliner** [comment]
Hmm, this gets a little weird I think because what you're describing is also how `rerun-pipeline` is going to work.

**Comment by JoeyZwicker** [comment]
I think @dwhitena is just making a good point that we didn't cover when talking about rerun pipeline. When users have a single JSON spec that defines multiple pipelines, this starts to get weird. 

Perhaps only allowing one pipeline per JSON simplifies this? I can see that being annoying in its own right so we might need to tweak our proposal for rerun and/or update pipeline.

**Comment by sjezewski** [comment]
stale
