### ISSUE TITLE
Error upgrading to 1.4.4-HEAD

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1702]
```17-04-19[14:13:11]:etl-and-training:0$pc version
COMPONENT           VERSION                                          
pachctl             1.4.4-c2931d07348cf554c0a7eef805bbd2464fd2143a   
pachd               1.4.4-c2931d07348cf554c0a7eef805bbd2464fd2143a   
17-04-19[14:13:15]:etl-and-training:0$pc list-job
error from InspectJob: line 1.679: invalid pps.JobState: JOB_STOPPED
```

and thats the latest build off master

 ```17-04-19[14:13:23]:pachyderm:141$git pull origin master
From github.com:pachyderm/pachyderm
 * branch            master     -> FETCH_HEAD
Already up-to-date.
17-04-19[14:13:26]:pachyderm:0$git log | head -n1
commit c2931d07348cf554c0a7eef805bbd2464fd2143a
```

I've updated an existing cluster running 1.4.4 that had existing pipelines / jobs / etc. Some of those jobs are marked `STOPPED`

Tracking down the error ... it's happening at line 300 of collection.go

```
	fmt.Printf("readonly collectiong unmarshalling %v ...\n", key)
	v := proto.UnmarshalText(string(resp.Kvs[0].Value), val)
	fmt.Printf("err unmarshalling %v? %v\n", key, v)
```

Reports ...

```
readonly collectiong unmarshalling 02d76ce6-bcd1-4dba-b2f6-95dd1a5e806d ...
err unmarshalling 02d76ce6-bcd1-4dba-b2f6-95dd1a5e806d? line 1.679: invalid pps.JobState: JOB_STOPPED
```

Which suggests the error is at the proto level. Perhaps we need to supply a migration? 

This looks like the commit that made the change: https://github.com/pachyderm/pachyderm/commit/c25596b1c1a76668504ee64cfb3f1f4e3be8836d

We're using the same field number ... I guess I'd expect proto to parse by field number and not worry about the field name, but I guess it does. In which case we need to increment the field number for `JOB_KILLED` and provide a migration.

**Comment by derekchiang** [comment]
If this really requires a migration we should just revert the change.  I don't think the benefit of changing the name to `KILLED` justifies the cost of a migration.
