### ISSUE TITLE
Pipelines' `created_at` field actually contains the time of last update

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1703]
In 1.4 pipelines have consistent IDs across updates making an original "created" (vs "updated") time particularly meaningful.

Proposal: `created_at` contains original creation time of a pipeline; `updated_at` contains the time of last update (ie what is currently in the `created_at` field)

Presumably both these fields should be reset if a pipeline is deleted and deployed again (as the `id` would change, and `version` would be reset to `1`)

**Comment by sjezewski** [comment]
stale
