### ISSUE TITLE
Datum progress can be incomplete

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1706]
Currently we update datum progress for every 1% of total datums processed.  However, if you have, say, 199 datums, then the last datum completed is only 0.5% of total datums processed and therefore won't trigger the update.  So you will see a completed job that has `198/199` datums processed, which can be confusing.

**Comment by derekchiang** [comment]
Turns out that we always set the total datums to 100% when the job successfully completes.

**Comment by derekchiang** [comment]
Actually, we should still consider setting datums to 100% when all datums have been completed, instead of when the job completes.  That way if we see a job at 100% but it's still running, we know that the job is having trouble finishing, not processing the last couple datums.

**Comment by JoeyZwicker** [comment]
Adding to this issue. We're seeing occasional progress update requests fail due to transient network errors. When this happen, the datum count can now be incorrect.

1 processed, 0 skipped, out of 2? It should be 1 and 1
`714b06b5-d2d3-4443-b2c2-68bba86f361f detect/348e26d3a0e24067b8e64af144bf9a95 11 hours ago   14 seconds 0       1 + 0 / 2 29.18MiB 1.968MiB success`

```
pc get-logs --pipeline detect --master
Launching worker master process
error monitoring job state: rpc error: code = Canceled desc = context canceled
error monitoring job state: rpc error: code = Canceled desc = context canceled
error updating job progress: context canceled
error updating job progress: context canceled
error monitoring job state: rpc error: code = Canceled desc = context canceled```

**Comment by jdoliner** [comment]
It's been a while since I've seen datum progress be out of whack, so I'm closing this. Feel free to reopen if you hit such a case.
