### ISSUE TITLE
Report clusterID again

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1710]
We haven't been reporting this to mixpanel for quite a while now. Segment sees:

```
client.Track(&analytics.Track{
  UserId: "f8edc66767a24385834fb48eba62ec08",
  Event: "user.usage",
  Properties: map[string]interface{}{
    "ClusterID": "",
    "VersionFinished": 0.0007354340000000001,
  },
})
```

Not sure when/why we stopped reporting this, but we should fix it

**Comment by sjezewski** [comment]
Hmmm ... another segment data point looks like it reports it ...

```
client.Track(&analytics.Track{
  UserId: "c4dbbe76fe0844ac8b88c3e1205a9ebb",
  Event: "user.usage",
  Properties: map[string]interface{}{
    "ClusterID": "8cab5ebdc47a402bba58a5b491829c05",
    "ListCommitStarted": 1,
  },
})
```

but in mixpanel i dont see it ... still investigating

**Comment by sjezewski** [comment]
Actually it seems like we are reporting it ... I can generate reports on it. However, many times we are not reporting it. And we can see 90% of the user metrics don't have it set:

![image](https://cloud.githubusercontent.com/assets/597953/25255984/9686e5e8-25e2-11e7-9e1b-8338e8995d65.png)

And this has been happening for a while ...

![image](https://cloud.githubusercontent.com/assets/597953/25256052/f7e9d85e-25e2-11e7-91b3-db33cf03ae81.png)

So it doesn't correspond directly to the 1.4 release (though testing / usage may account for some of this data)

**Comment by jdoliner** [comment]
I think at this point we're consistently reporting cluster IDs, feel free to reopen if that's not the case.
