### ISSUE TITLE
Inconsistent behavior with put-file

### ISSUE THREAD

**Issue by rj3d** [pachyderm/pachyderm#1711]
If I use put-file to load locally with a command like the following

```pachctl put-file reference_genome_indices master / -r -p 10 -f./reference_genome_indices```

A folder called reference_genome_indices will be created at root. However, if I use the same command but load from a GCS path like the following

```pachctl put-file reference_genome_indices master / -r -f gs://pici-east/reference_genome_indices```

All of the contents of the folder reference_genome_indices will be placed at root.

**Comment by sjezewski** [comment]
stale
