### ISSUE TITLE
Use sensible gRPC options when dialing

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1715]
Reported by @msteffen.  Opening it here so we don't forget.

Currently in a couple places we dial gRPC connections using the default options, which means that:

1. The connection is established lazily; so if you use it right after `Dial` returns, the connection might not be ready.
2. There's no keepalive; long-standing gRPC connections can thus become defunct.

**Comment by jdoliner** [comment]
Reminder that I should remember to use these on the worker pool connection code once the helpers are merged.

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
We use fairly reasonable defaults now.
