### ISSUE TITLE
Pipeline spec `Egress` docs should specify possible values

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1718]
[The `Egress` docs](http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#egress-optional) say you can push "to an external data store such as s3, Google Cloud Storage or Azure Storage"

Are any external stores supported beyond those three?

From the example spec elsewhere on the page:
```
...
"egress": {
  "URL": "s3://bucket/dir"
},
...
```

Presumably that means I can only egress to one location? What are the other specific protocol values that can be used? (guessing `gcs://` and `azs://` or something? what about `http://` to send `POST` request with the output data and `ftp://` to upload?)

**Comment by JoeyZwicker** [comment]
Good question. I thinks its `gs://` and `as://` but we should document more.

**Comment by gabrielgrant** [comment]
According to @jdoliner the possible values are `s3`, `gcs`, and `as` (with `gs` and `wasb` as aliases for `gcs` and `as` respectively)

**Comment by JoeyZwicker** [comment]
@dwhitena we can easily add the list of example egress urls to the http://pachyderm.readthedocs.io/en/latest/fundamentals/getting_data_out_of_pachyderm.html doc and pipeline spec.

**Comment by dwhitena** [comment]
Yep, I like that @JoeyZwicker. Will do.

**Comment by jdoliner** [comment]
@svekars just did a quick check this seems to still be an issue with the docs.

**Comment by svekars** [comment]
I wonder if `adls` is supported as well? And can it be just `https://` for all or some of them?

**Comment by svekars** [comment]
Resolved in https://github.com/pachyderm/pachyderm/pull/3850.
