### ISSUE TITLE
Re-enable pachctl deployment tests

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1730]
We have [tests here](https://github.com/pachyderm/pachyderm/blob/master/src/server/cmd/pachctl/cmd/cmd_test.go#L30) that runs when we make a release.  However these tests broke since we changed pachd from RC to Deployment.  I disabled them when I released 1.4.5 but we should look into fixing and re-enabling them.

**Comment by sjezewski** [comment]
stale
