### ISSUE TITLE
Compile pachctl binary for arm

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1734]
I'd like to be able to access a pach cluster from my android. @mlhamel was asking about uploading files from raspberry pi in slack. Seems like it shouldn't be too big a deal to cross-compile pachctl for arm.

Actually making it possible to run all of pachyderm on arm would be great too, but that involves more work, since the docker images we're using are all x86-based

**Comment by sjezewski** [comment]
stale

**Comment by gabrielgrant** [comment]
re-requested in #3406

**Comment by ysimonson** [comment]
Closing as per discussion in #3406
