### ISSUE TITLE
Add --no-reprocess flag to update-pipeline

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1738]
Capturing an offline discussion. In v1.4.5 recently made it so pipeline versions and the pipeline UUID are part of the hash.

We should add a `--no-reprocess` flag to update-pipeline which will not update the pipeline version number so that it'll only reprocess failed/unprocessed datums. This mean by default `update-pipeline` reprocesses everything. 

This change came from trying to support a few different behaviors:
1) User only changes the parallelism or resource request and doesn't want to reprocess everything. This proposal would only solve the case where this change is to rerun a failed job. 

2) Using a `from` commit to only process a subset of commits. This is still not supported particularly well because in a _mostly-adding new files_ workload `from: HEAD` still reprocesses everything. The idea of reprocessing only "new" datums isn't supported. To do this users should make a new branch, delete any data they don't want rerun, and create a new pipeline that takes that branch. 

This is a reasonable solution for wanting to "crank up the parallelism" for testing purposes, but doesn't solve the "missing logs and want to rerun" or "non-deterministic pipeline" use cases. 

3) `Delete-all` and then recreating a past pipeline still processes all the data again because the pipeline UUID is different. This is the behavior we want. We just don't store it again in s3. Once #1558 then we wont even need them to pass the data over the network again either. 

I might be missing some use cases we discussed that this proposal may not cover. @derekchiang @msteffen

**Comment by jdoliner** [comment]
I actually think we can this automatically without needing a flag. The only stick in the mud right now is that we include the version number as part of the hash for the pipeline. If we stop doing that then we'll do the right thing in basically all cases. The only thing is we'll want a way to rerun things without changing the `Transform`, maybe we could just move the version into the `Transform` itself as a way to update just the `Transform`?

**Comment by jdoliner** [comment]
Closing in favor of #1963
