### ISSUE TITLE
unique ID output in logs per run of datum

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1744]
I'm running a job that processes a single datum, but due to (a currently unknown) error, processing the datum fails and the datum is reprocessed indefinitely.

It's real hard to find the logs for a single run of the datum. The only fields I have to work with are jobID, or maybe the datum hash ... but those are not unique to a 'run' of the datum.

Should be easy to at least generate a UUID each time `Process()` is called and emit that in the logs.

**Comment by jdoliner** [comment]
A UUID per run might be a reasonable way to do this, but it's also pretty easy right now to do this by looking for the start processing and finish processing log messages. You can get this with `--raw`.

**Comment by sjezewski** [comment]
True - that works for low volume log cases.

It's not easy to do that when there are many many log messages ... because of the logs the user code generates there are huge logs. The kibana UI does provide some methods to refine by time windows, but it would be a whole lot easier if I could just apply a filter to get all the logs from a single run.

**Comment by sjezewski** [comment]
Now we have logs per datum on the UI
