### ISSUE TITLE
Updating a pipeline should kill currently running jobs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1748]
Currently it doesn't as far as I can tell.  At least the job states are not updated.

**Comment by jonandernovella** [comment]
@derekchiang I have also experienced that deleting a pipeline does not fully delete all its jobs and their corresponding metadata.

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
As of 1.7 this should be the case.
