### ISSUE TITLE
Docker report this site have deprecated link 

### ISSUE THREAD

**Issue by HackToday** [pachyderm/pachyderm#175]
in https://github.com/docker/docker/issues/19228

It had old link

https://github.com/pachyderm/pachyderm/tree/master/src/cmd/pfs-volume-driver

As it is 3-rd knows its correct link. please update new link yourself.  Or I can update if needed.

**Comment by jdoliner** [comment]
Created a pull removing us from docs, we no longer have a volume driver.

**Comment by HackToday** [comment]
@jdoliner  if I understand correct, that means pachyderm not support docker volume related function, is it correct ?

**Comment by jdoliner** [comment]
Yeah it wound up not making sense for us to have a docker volume. Pfs isn't usable as general purpose storage so it wouldn't really fill the same use case as other storage drivers. Furthermore it's just a fuse plugin which means I think there should be a generic volume driver we can use.
