### ISSUE TITLE
port-forward seems to forward the wrong ports for the UI

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1753]
Users are reporting that the web UI loads over HTTP, but that it isn't able to connect to the websocket port exposed by port-forward. 

It looks to me like the websocket server is [exposing port 30081](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go#L869) but [port-forward is sending traffic to 32082](https://github.com/pachyderm/pachyderm/blob/master/src/server/cmd/pachctl/cmd/cmd.go#L178)

But I think i may be misinterpreting something, because it also seems the UI is [exposing 30080](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go#L864) while [port-forward is sending traffic to 38080](https://github.com/pachyderm/pachyderm/blob/master/src/server/cmd/pachctl/cmd/cmd.go#L177)
Even if I'm wrong about which port is external-vs-internal, pretty sure these ports should all be standardized (as 30080 & 30081, say) for the sake of simplicity, at least, shouldn't they?

FWIW, the dashboard currently [tries to connect to 30081 for the websocket by default (unless a different port is supplied manually in the `port` query param)](https://github.com/pachyderm/dash/blob/master/app/services/pachd.js#L25)

We never sorted out my port forward issue, so I haven't been able to test/debug this myself, unfortunately.

**Comment by gabrielgrant** [comment]
As discussed with @sjezewski the ports internal and external ports are purposefully in different ranges to avoid confusing them, so just the one needs to be changed.

**Comment by sjezewski** [comment]
stale
