### ISSUE TITLE
Run workers as stateful sets to facilitate worker discovery

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1761]
Talked with @jdoliner and @msteffen.  Currently, we put a service on top of each set of workers, and we discover each individual workers by repeatedly dialing the service and manually de-dup connections.  This is inefficient.  Rather, we should run workers as stateful sets so each of them gets a unique network name such as `pipeline-XXX-worker-1`.  That way establishing one connection per worker becomes trivial.

**Comment by sjezewski** [comment]
stale
