### ISSUE TITLE
etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1763]
I have a cluster that's been running for a couple days.  I ran some jobs two days ago and everything seemed fine.  Then I didn't touch the cluster for the past couple days, and now every write command such as `create-repo/create-pipeline` either hangs or returns the following error:

```
etcdserver: mvcc: database space exceeded
```

Note that readonly commands such as `list-repo/get-file` still work.

**Comment by derekchiang** [comment]
I followed the [maintenance guide here](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota) and am now no longer getting the error.  It's worth noting that I was running 3 etcd nodes and I had to run the commands against each of them.

We still need to look into 1) why we are getting this error and 2) how to automatically resolve this issue.

**Comment by JoeyZwicker** [comment]
We've seen a user hit this too I think

**Comment by derekchiang** [comment]
Fixed by #1771
