### ISSUE TITLE
Allow users to set PullPolicy for pipeline jobs

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#1764]
I had an issue where an old image was used, because the default PullPolicy seems to be `PullIfNotPresent` and it took an old `:latest` version (which is in itself weird).
Changing the PullPolicy to `Always` manually solved it, but there has to be a way to do it for the entire pipeline.
Thanks!

**Comment by derekchiang** [comment]
Hi @kalugny, [this PR](https://github.com/pachyderm/pachyderm/pull/1773) will make it so that if you use the `:latest` tag, the PullPolicy defaults to `Always`.

**Comment by sjezewski** [comment]
stale
