### ISSUE TITLE
Make port-forward swallow errors when dash is not deployed

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1767]
Currently if the dash isn't deployed, `port-forward` will throw errors. These should be ignored, if the UI isn't deployed (but should probably somehow be preserved if the UI is supposed to be available, but is just unreachable). Perhaps just show them as warnings instead? "Dashboard Unreachable -- skipping port 32080 and 32081"

See @jdoliner 's [comment on #1754](https://github.com/pachyderm/pachyderm/pull/1754#issuecomment-297836175)

**Comment by sjezewski** [comment]
stale
