### ISSUE TITLE
Document `put-file`'s split options

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1770]
`split-file` docs aren't clear. These docs are referenced from the 1.4 migration doc to "learn more about how `--split` works)[https://github.com/pachyderm/pachyderm/tree/master/migration/1.3.x-1.4.x#data]

```
      --split string              Split the input file into smaller files, subject to the constraints of --target-file-datums and --target-file-bytes
      --target-file-bytes uint    the target upper bound of the number of bytes that each file contains; needs to be used with --split
      --target-file-datums uint   the target upper bound of the number of datums that each file contains; needs to be used with --split
```
Specific questions: 

- What is the `string` arg to `--split`?
- What is meant by "target upper bound"? In what situations would it not be exactly that number of bytes/datums?
- For `--target-file-datums`: my understanding is we define "a datum" to be "a tuple of inputs' paths matched by their glob patterns", so it's not clear to me how a file would contain multiple datums

**Comment by dwhitena** [comment]
Fixed here: http://pachyderm.readthedocs.io/en/latest/cookbook/splitting.html. Closing for now.
