### ISSUE TITLE
Mount failed job for easy debugging of user code

### ISSUE THREAD

**Issue by brollb** [pachyderm/pachyderm#1779]
when a job fails, it would be nice if we could enter it and debug what went wrong. Currently, I find myself reproducing errors by downloading files from pfs locally and starting a docker job with these files mounted appropriately.

This might be something that pachctl could facilitate

**Comment by brollb** [comment]
this would probably just be running a service but it would be nice if we could pass the job id so we could investigate why the given job id failed

**Comment by sjezewski** [comment]
This is something we've added w stats support. You can browse the state of the input/output directories on the UI, or there is a way to do this via pachctl as well. This will officially land in 1.6, and I believe stats/UI are going to be paywalled.

If you're interested in trying this out, you can sign up on the UI for a free trial. [Here](http://docs.pachyderm.io/en/latest/pachctl/pachctl_deploy.html?highlight=dash) are some instructions on how to deploy the dash (e.g. use `--dashboard-only` if you have an existing pach cluster)
