### ISSUE TITLE
Standardize our use of retryNotify

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1780]
For example ... in `src/server/pkg/obj/obj.go` we use the 3rd party library, but in other places we use our version under `src/server/pkg/backoff`.

The latter allows us to put the logic on deciding if we retry or not in the notify function. We should standardize our usage to use our version. (The other way relies on hoisting the errors in the case of non retryable errors which is easy to miss).

**Comment by jdoliner** [comment]
We no longer use the external backoff library. Confirmed by `ag cenkalti` (the author of the original library).
