### ISSUE TITLE
Workflow for using Pachyderm only for processing but not for storage

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1786]
This stems from a conversation I had with a user.  The user wanted to process HD videos, which can obviously be very large.  The user does not want to store the videos in PFS (presumably because we don't have GC yet?).  Further more, their pipeline has multiple stages, where the output of each stage can be very large.

The user's question was basically how to run his pipeline without storing the videos (or the intermediate outputs) in Pachyderm.

The best answer I could come up with was this:

1. Upload the HD videos to some external storage system (e.g. s3).
2. Add files that contain URLs to the said videos into the input repo.
3. Pipelines download and process the videos.
4. Pipelines upload the output to the external storage system (e.g. s3).
5. Pipelines write to `/pfs/out` the URLs to the output.
6. The next stage of pipelines repeats this process.

Does does workflow seem acceptable?  If so, we might want to document it since the use case could be a pretty common one.

This workflow won't be necessary once #546 is resolved.  #626 would also help.

**Comment by sjezewski** [comment]
stale
