### ISSUE TITLE
Pachctl mount does not umount directory on exit:

### ISSUE THREAD

**Issue by teodor-pripoae** [pachyderm/pachyderm#179]
After stoping `pachctl mount`, the fuse directory should be automatically umounted. Mounting again results in error:

```
$ pachctl mount -p /tmp/pfs
2016/01/13 08:45:17 mount helper error: mount_osxfusefs: mount point /private/tmp/pfs is itself on a OSXFUSE volume
mount_osxfusefs: exit status 64

$ umount /tmp/pfs
$ pachctl mount -p /tmp/pfs # works again
```

After stopping the `pachctl mount`, operations on the fuse directory will not work anyway, so I think it should be better to umount the directory before exiting. This can be done by catching the interrupt signal provided by the OS.

**Comment by derekchiang** [comment]
Fixed by #313 .
