### ISSUE TITLE
A long-running fsck-ish process that repairs cluster state

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1790]
Discussed with @msteffen.  Currently we store our cluster "truth" in etcd.  The state in etcd specifies how the cluster "should be".  The actual cluster state is however stored in Kubernetes, which controls things like which pipelines have workers running, how many workers are running, what images the workers are using, etc.

While we have internal mechanisms that try to configure Kubernetes such that the actual cluster state matches the correct cluster state, the mechanisms themselves can be buggy and subject to subtle race conditions.  Thus, we should consider adding a long-running process that does to our cluster what `fsck` does to file systems, which is to simply repair the cluster when it sees a discrepancy between how the cluster is and how the cluster should be.

Then, by the end-to-end principle, we can potentially remove the existing code that talks to Kubernetes and have this process do all the work.

**Comment by sjezewski** [comment]
stale
