### ISSUE TITLE
`Egress` fails silently in Azure

### ISSUE THREAD

**Issue by josibake** [pachyderm/pachyderm#1800]
Both myself and @jpoon have attempted to use the `egress` functionality while deployed on Azure (k8s `1.5.1` for me), without success. Haven't been able to find any logs on failure either, so it appears to fail silently.

From slack

> Trying to get the egress in the pipeline spec to work. I have this:
> 
> ```  "egress": {
>     "URL": "https://<redacted>.blob.core.windows.net/public"
>   }
> ```
> 
> But don’t see any files or logs :confused:
> 
> Joe Doliner [6:35 PM] 
> you gotta use an `as://` or `wasb://` style url
> 
> [6:36] 
> I think it's like `as://url_endpoint/container`
> 
> Jason Poon [6:45 PM] 
> negative.  tried http/as/wasb: `as://<redacted>.blob.core.windows.net/public`
> 
> [6:48] 
> Don’t see any logs in pachd about `egress` or ^ above url.

**Comment by derekchiang** [comment]
Fixed in #2156
