### ISSUE TITLE
put the same file and the size of the file increase

### ISSUE THREAD

**Issue by swimablefish** [pachyderm/pachyderm#1809]
I put a file several times, but the size keep increasing. I think it shouldn't increase the size

```
abc                 c7ab05ae6bc54fafa3c6c0bd64a5ced7   eafae746824f45809fd8e43a2052b1b6   19 hours ago        Less than a second   2.361 KiB
abc                 eafae746824f45809fd8e43a2052b1b6   bde70398c6ad4d7b995505e86500a9f5   19 hours ago        1 seconds            1.574 KiB
abc                 bde70398c6ad4d7b995505e86500a9f5   a87f6ade9c0540b08018ff6af4e4391b   19 hours ago        2 seconds            806 B
abc                 a87f6ade9c0540b08018ff6af4e4391b   <none>                             20 hours ago        39 minutes           0 B
```

```
pachctl list-file abc  bde70398c6ad4d7b995505e86500a9f5
NAME                TYPE                SIZE
pachyderm.sh        file                806 B
```

```
pachctl list-file abc  c7ab05ae6bc54fafa3c6c0bd64a5ced7
NAME                TYPE                SIZE
pachyderm.sh        file                2.361 KiB
```

**Comment by JoeyZwicker** [comment]
I believe each time you're putting the file again you're appending the same content to end of the last file, not overwriting it. That's why the size goes up steadily. 

If you want to overwrite a file, you should start the commit, the delete-file, put-file, finish-commit. We're working on changing this default appending behavior here: #1531

**Comment by JoeyZwicker** [comment]
If thats not the case though and we're showing file sizes wrong, definitely let me know and we can figure out if there's a bug.

**Comment by swimablefish** [comment]
I checked the file's content. It was as same as the original file, not contain append content.

**Comment by jdoliner** [comment]
Hey @swimablefish I just tried reproducing this and wasn't able to. Pachyderm appends by default, so unless you're explicitly calling `delete-file` before you do your `put-file` you'll be doing appends. Could you try doing `pachctl get-file abc c7ab05ae6bc54fafa3c6c0bd64a5ced7 pachyderm.sh | wc -c` and see what you get? That should tell you the size of the file at that commit, when I did this, using a `delete-file` so as not to append, I got the size of the file I'd put which was the same as the number of bytes I got out from `get-file`.

**Comment by sjezewski** [comment]
stale
