### ISSUE TITLE
Error for invalid pod names.

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1810]
From the users channel:

> kubernetes pod name limit (and I assume all other things) is 64 chars
> I think Pachyderm should throw an error for this, but that's not the important thing here, I've noticed some of our other pipelines have long names and they actually chop off the ID at the end of pods.
> example: `pipeline-j2f318893c6de440fa991e9c9f48b3e44workerexample-v102lz6` is 64 characters long
> however: `pipeline-j2f318893c6de440fa991e9c9f48b3e44documentclassifih95mm` has chopped off the "documentclassifier" at the second 'i' and omitted the '-' character between the pipeline name and the unique ID.
> 
> another quick (albeit not so important) question: is there a defined length for the unique ID thing at the end of pipeline pods? I'm seeing some are 5 characters and some are 7, some have `v` with and without a dash
> `pipeline-j2f318893c6de440fa991e9c9f48b3e44<redacted>-v1-0mdhn`
> `pipeline-j2f318893c6de440fa991e9c9f48b3e44<redacted>-v102lz6`

**Comment by sjezewski** [comment]
stale
