### ISSUE TITLE
Integration tests for upgrades

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1815]
Inspired by the error `line 1.966: unknown field name "input" in pps.Input` that some customers saw upgrading from 1.4.5 to 1.4.6.

One way to avoid problems like that would be to run a test harness that tries to upgrade a pachyderm cluster. If the upgrade test fails (e.g. can't run pipelines after upgrading) we should make sure to include a migration script with the release.

**Comment by sjezewski** [comment]
stale
