### ISSUE TITLE
More info should be reported when 'failed to process datum'

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1820]
In my logs I'm seeing a bunch of failed datums for ctx deadline exceeded. Those seem to be innocuous?

I have to filter through a lot of noise to find log messages that seem to be useful. One thing we could present when a datum fails (and `Process()` has exited) was how long `Process()` had been running. That could provide quite a lot of 'signal' in the noise of the logs. E.g. if I have a long running datum, I care more that it erred

**Comment by derekchiang** [comment]
Potentially relevant issue: #1493

**Comment by sjezewski** [comment]
stale
