### ISSUE TITLE
Rethink the design decision that jobs should be run serially

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1823]
This issue is the opposite of #1543.  The current job execution model is such that a job always waits for its parent to complete (i.e. either succeed or fail) before it starts running.  This model however has the problem that parallelism can be "under-used".

Imagine a scenario where a user is streaming images into a machine learning pipeline.  The user adds one image per commit.  In this scenario, it actually doesn't matter what parallelism the user has set for their pipeline; only one image will be processed at any given point in time.  This is due to the fact that each job only processes one image (since there's only one image per commit), and each job waits for its parent to finish before it starts.

We should think about how we can revise the model to support the streaming use case.

**Comment by brollb** [comment]
It looks like there were two main motivating reasons for #1543: avoiding duplicate processing and being able to see the first couple finished jobs quickly.

Avoiding duplicate processing should be able to be handled by the glob patterns - that is, we can figure out what the new data is in each commit by diffing the datum files (basically what @JonathanFraser said in #1543).

I am assuming that seeing the finished jobs quickly is important for testing a pipeline (and iterating on it to make it work). For getting quick results of finished jobs, it might work to use things like the `from` field to get a quick sanity check for if the pipeline was effective. If you are not getting quick results to test a pipeline, I don't see the value of trading the perf of completing a single commit for the perf of completing the processing of an entire repo. Is there another use case for finishing jobs quickly that I am missing?

**Comment by brollb** [comment]
This seems to be closely related to the problem of representing computation dependencies. Prior to #1543, there was no dependency between computation of the dependencies. After, there were implied dependencies between every commit. I wonder if there is a better way to represent the dependencies. They should certainly be associated with a pipeline (as they certainly depend on the computation being performed - not the commits/data).

Currently, it seems that the only options for this are "in order" or "not in order" (for a given pipeline, of course) though I wonder if there is any other option that people may need...

**Comment by sjezewski** [comment]
stale
