### ISSUE TITLE
Use godeps for vendor package management

### ISSUE THREAD

**Issue by jseaidou** [pachyderm/pachyderm#183]
Godeps is a current solution for Go to manage external dependencies. It allows you to pin your dependencies without necessarily having to include the entire source tree with your code. See the github.com repo for more info: https://github.com/tools/godep

For this issue to be implemented, I will need the hashes to which your vendor directory items depend on. 

Thanks!

**Comment by jdoliner** [comment]
We were using godeps before but had some troubles with it and have moved on to govendor which is supposed to be the new way to do this.
I'm not strongly attached to either but given we just had trouble with godeps I think we'll be sticking with govendor until it gives us a reason not to.
