### ISSUE TITLE
Vision of this project

### ISSUE THREAD

**Issue by cxxly** [pachyderm/pachyderm#184]
What's the long vision of this project, is there any difference with hadoop,spark, storm or others, and is it better?  

I think it is necessary to add main design ideas and roadmap to this project to attract more people to participate in.

**Comment by JoeyZwicker** [comment]
From a high level, this blog post we wrote last year talks about our overall direction and approach. https://medium.com/pachyderm-data/lets-build-a-modern-hadoop-4fc160f8d74f

You're right though, we probably should add a more detailed near-term roadmap.

**Comment by yellow1912** [comment]
I'm also interested in knowing why this is better than Spark or Storm?

**Comment by jdoliner** [comment]
Sorry for the delay on this guys. I'm working on this one right now.

**Comment by jdoliner** [comment]
Alright, our README now has a section title "Our Vision." Closing for now, feel free to reopen if you think that section should be expanded.
