### ISSUE TITLE
Confusing error message on redeploy

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1844]
From a users:

> When doing `pachctl undeploy` and then `pachctl deploy amazon ...` again, Kubernetes complains that the persistent volume already exists and is claimed:
> 
> Error from server (AlreadyExists): error when creating "STDIN": persistentvolumes "etcd-volume" already exists
> Error from server (AlreadyExists): error when creating "STDIN": persistentvolumeclaims "etcd-storage" already exists
> kubectl create -f -: exit status 1
> Error from server (AlreadyExists): error when creating "STDIN": persistentvolumes "etcd-volume" already exists
> Error from server (AlreadyExists): error when creating "STDIN": persistentvolumeclaims "etcd-storage" already exists

**Comment by bpb** [comment]
Experiencing similar issue. Not sure if this is due some misconfiguration in setting up pachyderm on aws. Investigating.

Error below:
`serviceaccount "pachyderm" created
deployment "etcd" created
service "etcd" created
service "pachd" created
deployment "pachd" created
secret "amazon-secret" created
Error from server (AlreadyExists): error when creating "STDIN": persistentvolumes "etcd-volume" already exists
Error from server (AlreadyExists): error when creating "STDIN": persistentvolumeclaims "etcd-storage" already exists

Pachyderm is launching. Check it's status with "kubectl get all"

kubectl create -f -: exit status 1
Error from server (AlreadyExists): error when creating "STDIN": persistentvolumes "etcd-volume" already exists
Error from server (AlreadyExists): error when creating "STDIN": persistentvolumeclaims "etcd-storage" already exists`

**Comment by JoeyZwicker** [comment]
Sorry you're hitting this issue. It's something intermittent and flaky about AWS not releasing volume claims. We're going to change the docs to use dynamically schedules volumes instead of static ones and this shouldn't be a problem anymore.

**Comment by sjezewski** [comment]
stale
