### ISSUE TITLE
Non-root users cannot access /pfs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1845]
A non-root user in a container can't access `/pfs` because it's backed by an `emptyDir`, which according to [this issue](https://github.com/kubernetes/kubernetes/issues/2630) is owned by root with permission set to `750`.

**Comment by derekchiang** [comment]
I haven't personally tested this, but I think one work-around would be to have the container (which is launched as `root`) `chown /pfs` to the non-root user.

**Comment by derekchiang** [comment]
As of 1.6.0-RC1, `/pfs` does not work with `chown` and therefore cannot be used by non-root users.  If you need access to a scratch space, it's recommended that you use the `/scratch` directory.  Note that the scratch space persists between datum runs, and therefore if your code depends on a clean scratch space, you need to clean up the scratch space yourself before your code exits.

**Comment by gabrielgrant** [comment]
It looks to me like this issue shouldn't actually be an issue due to this line:

https://github.com/pachyderm/pachyderm/blob/462145baade0514ffbfa47637711945e1c3917ea/src/server/worker/api_server.go#L1732

Is that not doing what I think it's doing, or is there something else missing?

**Comment by ysimonson** [comment]
#2635 is a dupe, but it's linked off in a few places as part of the OpenShift effort, so closing this one out.
