### ISSUE TITLE
Single file is being processed in multiple pipelines

### ISSUE THREAD

**Issue by vuc4** [pachyderm/pachyderm#1854]
I'm getting some duplication of data and I've traced it down to instances of a single file being processed more than once. The output of the latter run ends up replacing the output of the initial run in the next commit.

[Archive.zip](https://github.com/pachyderm/pachyderm/files/1009008/Archive.zip)

**Comment by jdoliner** [comment]
Looking at `load-steak-pipeline.log` it does seem that a datum was processed twice by different jobs. I'm wondering if this is a case of the bug with 2 jobs running concurrently. @derekchiang you're planning to look into that one soon aren't you?

**Comment by derekchiang** [comment]
From the pachd logs, it doesn't look like those two jobs were running concurrently.  @vuc4 what cloud provider were you using?  Were you using any custom caching solution such as Cloudfront?

**Comment by vuc4** [comment]
Deployed to GCS. No caching solution.

**Comment by derekchiang** [comment]
We have a fix underway.

**Comment by jdoliner** [comment]
This was fixed as part of https://github.com/pachyderm/pachyderm/pull/1832.
