### ISSUE TITLE
Update minio-go version

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1857]
From users:

> Henrik Johansson [11:02 AM] 
> We are seeing some weird issues with our minio. Hefty delays that would explain the long commit times
> 
> Daniel Whitenack 
> [11:10 AM] 
> @dahankzter Interesting.  Does this seem to be a Minio specific issue, or possibly a bug in Pachyderm. Or maybe you don't know yet?
> 
> [11:10] 
> I can connect you with our contacts at Minio as well if that would help.
> 
> Henrik Johansson [11:11 AM] 
> I am in the minio chat and having a discussion there
> 
> [11:12] 
> the minio-go client seems ok and consistently fast but the `mc` program has hickups
> 
> [11:12] 
> However had it been in the client then it would have been more consistent :smile:
> 
> [11:13] 
> since we seem to see it both with put-file and `mc`
> 
> Daniel Whitenack 
> [11:14 AM] 
> Hmmm... ok.  Well, please let me know if you need me to push from my end with Minio, and thanks for helping push that integration @dahankzter.
> 
> Henrik Johansson [11:14 AM] 
> Sure will!
> 
> Henrik Johansson [11:22 AM] 
> It turns out that a new  `go get -u github.com/minio/mc` does not suffer
> 
> [11:23] 
> Maybe the version of minio-go in Pachyderm also suffers?
> 
> [11:23] 
> client or server I really don’t know but the server has this dep right?
> 
> Daniel Whitenack 
> [11:32 AM] 
> @dahankzter Yes, it's in the server.
> 
> [11:32] 
> I will open a ticket to update the client.
> 
> [11:32] 
> We should just be able to vendor in the new version.

**Comment by dahankzter** [comment]
There seems to be breaking changes but perhaps it is just my lack of knowledge of `govendor` and how pachyderm is built that is lacking.

**Comment by dahankzter** [comment]
```bash
minio_client.go:135: invalid operation: errResp == sentinelErrResp (struct containing http.Header cannot be compared)
```
The ErrorResponse now contains http.Header which is a map so it cannot be compared.
Simply removing the explicit sentinel compare at least compile.

**Comment by dahankzter** [comment]
Any news on this? Will it make it into the next RC?

**Comment by jdoliner** [comment]
@dahankzter we should be able to get this into the next RC, @dwhitena could you ping the minio guys and see if they have any guidance on this? (Or maybe just want to do it since they know the code best?) otherwise it seems like it shouldn't be too hard for us to figure it out.

**Comment by dwhitena** [comment]
@jdoliner Yep, I'm on it.  I think the first step is to vendor in the new client and see if that fixes the issue.  That should be easy on our end.  But I will also confirm with the Minio guys and see if they can provide some guidance.

**Comment by dwhitena** [comment]
FYI, some clarification from users slack:

> Daniel Whitenack [10:09 AM]
> @dahankzter Also just to confirm, you were able to speed up Minio + Pachyderm with the latest client yeah?
> 
> [10:10] 
> It's just a matter of vendoring, review issues.
> 
> Henrik Johansson [10:50 AM] 
> @dwhitena well only minio-mc client + same minio-server using new mc code (same lib as pachyderm)
> 
> [10:51] 
> We actually never got a new pachd with the new minio-go lib deployed
> 
> [10:51] 
> We may be able to do that, not sure
> 
> Daniel Whitenack [10:55 AM] 
> @dahankzter Thanks.  I will try as well.
> 
> Henrik Johansson [10:56 AM] 
> but the difference with new `mc` vs HEAD `mc` was remarkable

**Comment by dwhitena** [comment]
@dahankzter This should be fixed by: https://github.com/pachyderm/pachyderm/pull/1867.  Feel free to try out the PR to see if it works for you, but it worked fine for me.  The speedup is indicated in the PR.

**Comment by dahankzter** [comment]
Very nice!

**Comment by dahankzter** [comment]
Any eta on that RC? :)

**Comment by dahankzter** [comment]
Works like a charm!

**Comment by jdoliner** [comment]
Awesome, thanks for your patience while we addressed this. Closing.
