### ISSUE TITLE
Dashboard doesn't work

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#1861]
When loading it outputs a ton of console logs. Specifically:
```
TypeError: Cannot read property 'points' of undefined
    at layout.js:114
    at arrayEach (_arrayEach.js:16)
    at Function.forEach (forEach.js:35)
    at updateInputGraph (layout.js:110)
    at layout.js:433
    at time (util.js:239)
    at layout.js:432
    at time (util.js:239)
    at Object.layout (layout.js:425)
    at Class.<anonymous> (p-network.js:58)
```
And seems to be stuck in a loop.

I'm using Chrome (stable) on Windows 10.

**Comment by JoeyZwicker** [comment]
@gabrielgrant

**Comment by gabrielgrant** [comment]
@kalugny Thanks for letting us know about this. Which version of pachyderm are you using? And do you know if you deployed a specific version of the dashboard?

**Comment by sjezewski** [comment]
We've done a few revs of the dashboard, and haven't been able to reproduce. Please try upgrading and let us know if you're still having the error.
