### ISSUE TITLE
unknown field "from_commit" in pps.PipelineInput

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#1862]
I'm getting this error when trying to use the `from_commit` field in a pipeline:
https://github.com/Cytoreason/kallisto/blob/500030ebdfe8e55d08f4f21f8bab6a8f95748f45/pipeline-specs/kallisto_stage1.json

Can't seem to find what is wrong with it.

**Comment by JoeyZwicker** [comment]
what version are you using? Just wanted to double check because the name of the field has changed a few times.

**Comment by kalugny** [comment]
I'm using 1.4.7 RC1

**Comment by JoeyZwicker** [comment]
I can't see anything obviously wrong with your pipeline manifest. Can you give me a little more detail on what error you're getting? 

@derekchiang @jdoliner

**Comment by sjezewski** [comment]
stale
