### ISSUE TITLE
Openshift - update docs, and address workflow issues

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1865]
There are a variety of things that need to be updated in the Openshift docs.  In general, we just need to go through this deploy and make sure that the docs are up-to-date and accurate.  

In addition there could be various issues lurking around authorization and managing pipelines.  From the users channel:

> I think
> serviceAccount: pachyderm
>       serviceAccountName: pachyderm
> was missing from the generated rc

> okey to fix this we need to run our app container as root ,, and need to add this too `oadm policy add-scc-to-user anyuid system:serviceaccount:pachyderm:pachyderm`  may be this need to be added in the doc
> for running pipeline in openshift..

> updating the pipeline seems to create a new rc in openshift but the old worker  pods are still there that were deployed by old rc.
> 
> oc get rc
> NAME                   DESIRED   CURRENT   READY     AGE
> pipeline-pixeletl-v2   1         1         1         5m
> 
> but the view of pods seems to have both new and old
> 
> oc get pods -w
> NAME                         READY     STATUS    RESTARTS   AGE
> etcd-192035642-y3ind         1/1       Running   0          34m
> pachd-2697247004-gclgg       1/1       Running   2          34m
> pipeline-pixeletl-v1-d9rt0   2/2       Running   1          10m
> pipeline-pixeletl-v2-0bh6n   2/2       Running   1          43s
> 
> i think in openshift when you wipe out rc .. it would not clean pod. but when you wipe out deployment config it cleans up the pods and rc too.
> may be its good idea to scale the rc replica down to zero pods before wiping it out when creating new rc via pipeline update

**Comment by dwhitena** [comment]
In addition, we need to address all of these in the docs, etc. to get things working in openshift: https://github.com/pachyderm/pachyderm/pull/1777

**Comment by sudhirpandey** [comment]
having this `oadm policy add-scc-to-user privileged system:serviceaccount:pachyderm:default` seems to address most of the issue while launching worker pods, it we might also do not need to modify service account fix for json file obtained via running`pachctl deploy custom ..`
