### ISSUE TITLE
1.5 API Breaking Changes

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1872]
Since 1.5 is coming up soon, we should take this opportunity to merge in changes that are API-breaking.  Here's a list of changes we want to make:

- [ ] `inputs` -> `input`
- [ ] `stopped` -> `killed`

**Comment by JoeyZwicker** [comment]
I think https://github.com/pachyderm/pachyderm/issues/1737 is worth discussing too. I know I'm the one who feels most strongly about this issue.

**Comment by dwhitena** [comment]
Related doc changes tracked here: https://github.com/pachyderm/pachyderm/issues/1869

**Comment by gabrielgrant** [comment]
I believe @jdoliner and @derekchiang decided that these naming changes would be deferred until a later release when we have some other reason to require users to run a migration, right?

**Comment by JoeyZwicker** [comment]
Do we not have other API-breaking changes already in this release?

**Comment by jdoliner** [comment]
Afaik there are no other API-breaking changes in this release.

**Comment by derekchiang** [comment]
Closing in favor of more specific issues.
