### ISSUE TITLE
pachctl create-pipeline issues WARNING: field `inputs` is deprecated, use `input` instead.

### ISSUE THREAD

**Issue by davidthewatson** [pachyderm/pachyderm#1877]
I was going through the tutorial here:

http://docs.pachyderm.io/en/latest/getting_started/beginner_tutorial.html

but when I got to the create-pipeline pachctl command, I got a warning:

    $ pachctl create-pipeline -f https://raw.githubusercontent.com/pachyderm/pachyderm/v1.4.0/doc/examples/opencv/edges.json

and successive commands failed. I downloaded the file and tried editing the JSON to replace:

    "inputs": [

with:

    "input": [

but that didn't seem to work because I got this error:

    json: cannot unmarshal array into Go value of type map[string]json.RawMessage

I think some files are out-of-date but I'm not sure where.

**Comment by JoeyZwicker** [comment]
Thanks @davidthewatson . We'll get this fixed right away.

**Comment by jdoliner** [comment]
The only thing that needs to be fixed here is the docs. `edges.json` at master has the correct format.

**Comment by JoeyZwicker** [comment]
Sorry you ran into this @davidthewatson. Should be fixed now. Definitely reopen and let us know if you still get that warning.
