### ISSUE TITLE
Support k8s secret -> env mapping

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1883]
Is it possible and/or do we want to support a mapping of k8s secrets to env variables in worker pods, similar to what is discussed here: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables.

For some users that have many secretes (e.g., 15), doing the export in stdin is a little confusing and/or verbose.  From users:

> Thanks. Are you guys planning on fully supporting the k8 env -> secrets mapping in the future? We have about 15 environmental variables that run our software so using the export syntax is going to end up with one crazy command

**Comment by jdoliner** [comment]
This seems like a reasonable thing to support and it shouldn't be too hard.
