### ISSUE TITLE
File/Folder TTL & Resurrection

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1884]
I have a use-case where I'm storing all my files in compressed and serialized form. The first pipeline will have to decompress them first.
The decompressed files must be stored on PFS in order to be accessible to other pipelines. This defeats the whole purpose of compressing the files in the first place.
A user can currently either decompress the files in every pipeline or store both the compressed and uncompressed forms.

What we can do instead is provide a mechanism for setting Time To Live on a file or folder in PFS. After an object has passed it's TTL it will be deleted but the metadata about the object will remain.
All objects with TTL will be lazily evaluated. If they are not present pachyderm will retrigger all the pipelines that came before it to reproduce it and it will be transparently provided to the current executing pipeline.

A version of this feature without lazy evaluation can be implemented by verifying that all objects are present and reproduce the missing files.

**Comment by jdoliner** [comment]
Definitely see the use case and think that this is something we'll want to service. I'm not sure that TTL is a good abstraction for this though, because we should be able to know the lifetime of the files ahead of time, since they're being consumed by downstream pipelines. I think #546 is probably a better implementation path for this functionality.

**Comment by thedrow** [comment]
#546 and this issue are similar but will be used in different use-cases.
In my use-case, the compressed files are only accessed once during their entire lifetime so theoretically #546 fits unless I'm experimenting. In this case, you don't want to decompress again and again.
In the future, multiple pipelines will use the same file which will also require repeated decompression if I use #546.
This is why TTL is a good addition.

**Comment by sjezewski** [comment]
stale
