### ISSUE TITLE
Update jobs to take the new atom/cross/union input

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1886]
Looks like this might be out of date with the latest atom/cross/union pipeline format: https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/example/example.go

**Comment by dwhitena** [comment]
Actually, it looks like the job spec hasn't been updated to the new atom/cross/union format:

https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.pb.go#L1108

and 

https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.pb.go#L445

So I'm updating the title of this issue to take care of this.

**Comment by jdoliner** [comment]
Job specs are updated, they still have an `Inputs` field for backwards compatibility reasons. That field will be removed in 1.6 when we fully shut off that feature. The original point of this issue still stands though, we should update the example.

**Comment by sjezewski** [comment]
This is done
