### ISSUE TITLE
Add a cookbook/example/best practice for incremental pipelines

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1894]
Incremental pipelines are added in #1832 but we don't have a cookbook/example/best practice that walks through an end-to-end example of using incremental.

**Comment by gabrielgrant** [comment]
Should be completed as part of #1869

**Comment by gabrielgrant** [comment]
Fixed in 3a3bffebb9c305b0640dfecb117e12578a29b16c
