### ISSUE TITLE
Get 'storage: object doesn't exist' when trying to load from GCS without -r flag

### ISSUE THREAD

**Issue by rj3d** [pachyderm/pachyderm#1901]
Hello!

I've been trying to load some data from GCS, and I'm getting a 'storage: object doesn't exist' error whenever I try to load without a -r flag.

I first tried loading the individual file intervals.csv into the repository at the path /tesla but got the aforementioned error
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -f gs://tesla-data/metadata/intervals.csv && \
pachctl finish-commit somatic_variant_aligner_input master
```

Next I tried copying that file to it's own folder and loading the whole folder, but I got the same error.
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -f gs://tesla-data/metadata/intervals && \
pachctl finish-commit somatic_variant_aligner_input master
```

Finally, I tried loading the whole folder with the -r flag, and the commit was successful.
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -r -f gs://tesla-data/metadata/intervals && \
pachctl finish-commit somatic_variant_aligner_input master
```

I'm on version 1.4.7. Let me know if I can provide anything else or if I'm doing anything wrong.

Thanks!

**Comment by jdoliner** [comment]
Hey @rj3d sorry this isn't working for you.

I'm a little confused about what's going on here so sorry if this is a dumb question. Is `gs://tesla-data/metadata/intervals` a directory or a file?  If it worked with the `-r` flag then that probably suggests that it's a directory which means passing the same path without the `-r` flag probably wouldn't work. Also is `intervals.csv` a file that's present or no?

**Comment by rj3d** [comment]
No worries, thanks for the quick reply! `gs://tesla-data/metadata/intervals` is a directory. Based on your explanation it makes sense why that doesn't work. `intervals.csv` is a file that's present. If I try to load the file directly I get the storage: object doesn't exist error. However, if I copy the file into it's own folder and load the contents of that directory recursively it works fine. I guess it was a little confusing how I wrote the commands. To make it a bit more clear, this command also gives me an object doesn't exist error:

```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -f gs://tesla-data/metadata/intervals/intervals.csv && \
pachctl finish-commit somatic_variant_aligner_input master
```
