### ISSUE TITLE
Failure to marshal a pipeline.json prints an unfriendly error

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1904]
I set the stdin key to be a string instead of a list and I got this error message.
```
pachctl update-pipeline -f pipeline.json 
json: cannot unmarshal string into Go value of type []json.RawMessage
```

This error message should be friendlier and point to where the json is not according to the pipeline spec.

**Comment by suneeta-mall** [comment]
@gabrielgrant yeah had mixed syntaxes for image secret. Thanks. 
But that message is so annoying - does not help at all in diagnosing the problem :(

**Comment by gabrielgrant** [comment]
@suneeta-mall yea, it would definitely be nice to provide better error messages. Opened an issue here: #3072
