### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1912]
Sentry is a popular error reporting product used by many companies. I am going to reach production in a few weeks and it occurred to me that pachyderm doesn't report job failures anywhere except pachctl.
Raven, the Sentry client is ported to many languages and it may or may not be feasible to implement the integration for each language port of Raven.
pachd could instead proxy between the Sentry server and the worker and add additional context about the job, commit, files affected, pachyderm version and more.

The protocol is described in https://docs.sentry.io/clientdev/overview/ and specifically, the contexts are at https://docs.sentry.io/clientdev/interfaces/contexts/ which is where pachd should add the additional information.
The alternatives are to implement the enrichment for each Raven client or leave it to the users to do so.
The problem with the latter alternative is that currently, it seems that each worker doesn't expose the necessary metadata in order to enrich the error report.

**Comment by sjezewski** [comment]
stale
