### ISSUE TITLE
Explain Datums

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1913]
Chatting w @gabrielgrant about this, and the question he was fielding at pycon.

There is some confusion about how we talk about a datum (a tuple of data across repos) vs the data within a tuple from a single repo vs files. And also how there are many datums generated from a single commit / combo of input repos.

I think we could use some docs around this. Explaining this one thing clearly really unlocks understanding the PPS processing model simply.

So the request here is to make a single doc page about datums.

**Comment by dwhitena** [comment]
@gabrielgrant and @sjezewski is this sufficiently documented here for now: http://pachyderm.readthedocs.io/en/latest/fundamentals/distributed_computing.html#datums?

**Comment by gabrielgrant** [comment]
I think we could still use a bit more clarity around this -- what we call a datum is the result of combining the files from multiple atom inputs using crosses and joins (ie it is multiple files). To me, that doc makes it sound like each of the individual files matched by a glob pattern is a datum.

these exact semantics are really quite complex to communicate, and there's a fair bit of subtlety that i think a lot of users miss. we probably should have some diagrams

**Comment by JoeyZwicker** [comment]
The pipeline spec doc as specific examples of cross datums. This is definitely a complicated idea, but other than also including those details in the main doc, I'm not really sure there's that much more add here. I'll mark it for @dwhitena to take a quick look through if there obvious improvements

**Comment by sjezewski** [comment]
stale
