### ISSUE TITLE
Getting actual processing logs for an output file

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1914]
Right now there isn't a good way to find the logs generated by the code that actually created an output file.

There are two issues:
1. If the file was created several commits ago, all more-recent commits will have logs that just note that the input datum was skipped
2. I don't believe we have a good way of determining which input datum(s) went into creating a given output file (because output files are concatenated, one file could be created based on the output of multiple inputs)

**Comment by gabrielgrant** [comment]
Note that just having `commit_modified` for a file would help get closer to this: it wouldn't give all the input datums that went into creating a given output, but at least would allow the user to start exploring the logs for the right job (which, assuming they know the structure of the computation, is likely all they need)

**Comment by jdoliner** [comment]
This is pretty tricky and may never really be feasible.

Having `commit_modified` for a while wouldn't get you much closer to this. A 1000 datums across 1000 commits might have gone into creating a file, the most recent of those commits is going to be `commit_modified` that will only get you 1/1000 of the logs you want.

**Comment by gabrielgrant** [comment]
I think I may be missing something...I thought appending output only happened within a single commit, not between multiple commits?

**Comment by jdoliner** [comment]
> I thought appending output only happened within a single commit

That's the right way to think about what the output is, but remember that pps is smart enough not to reprocess datums, so it might be that the actual processing of the datums which are being merged together for this commit was done in a different job with different input commits that happened to have the same content for datums.

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
There is also somewhat doable now with stats.
