### ISSUE TITLE
Make objects' prefixes shorter

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1915]
Had this idea from a conversation with @sjezewski.  Right now all our objects are stored under `/pach/objects`, `/pach/blocks`, and `/pach/tags`.  According to [S3 docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html), storing objects under a common prefix can have performance implications, namely that they will tend to go to the same shards.

So I think we can make the prefixes shorter.  We don't really need `/pach` at all since presumably the bucket is exclusively for pachyderm.  Then we can shorten the prefixes to `o`, `b`, and `t`.

**Comment by sjezewski** [comment]
Would love to do this optimization!

But it hasn't been a priority. Marking as stale
