### ISSUE TITLE
update-pipeline doesn't accept --description

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1926]
`Error: unknown flag: --description`

**Comment by jdoliner** [comment]
`update-pipeline` isn't supposed to accept `--description`, `"description"` is a field in the spec but that doesn't mean it's a flag. I don't think adding a flag for each field in the spec really makes sense because many of them are difficult to represent as simple strings.

**Comment by gabrielgrant** [comment]
I definitely agree that not all fields should have flags, but there is a `--description` flag on `create-pipeline`, and (at least in the [release notes](https://github.com/pachyderm/pachyderm/releases/tag/v1.4.7) ) that's the recommended way to set the description, so it seems a bit strange to never be able to change that description. Do you think description should both be initially set and updated by adding it directly to the pipeline spec?

**Comment by jdoliner** [comment]
Hmm yeah, `--description` is needed for repos because there's no repo spec that you pass. For pipelines I think it makes a bit more sense to have people just pass it as part of the spec.

**Comment by gabrielgrant** [comment]
The other reason it might make sense to special-case the `description` field is that it's the only field that doesn't actually affect processing in any way, so it'd be nice to be able to update it without triggering reprocessing (which i think will happen when the version gets updated by issuing an `update-pipeline`, right?)

**Comment by gabrielgrant** [comment]
Fixed by #1981
