### ISSUE TITLE
Alias for latest commit on a repo

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1927]
Had a discussion with a user who would like a quick alias or command to get the latest finished commit ID for a repo:

> User
> Hello! We use a pfs mount to do our data investigation and run algorithm testing scripts etc, pointing to the master version of the data in the mount. But when pipelines are running the master version in the mount is no longer available. Do you have recommendations for this?
>
> Daniel Whitenack
Yes, when the pipeline is running, there is an open commit on master.  This isn't available until the commit is finished (which ensures that we prevent certain collisions, etc.).  What tools are you using for data investigation and testing scripts, etc.?  Would it be possible to use one of the clients and/or to reference the latest commit by ID rather than by master/head?
>
> User
> We're using python and R (mostly in notebooks). But we'd like to have a latest version of the data mounted for quite a few people in our organisation to use. 
Is there an easy way to find the most-recent-commit-that-is-available, for each repo? An alias for that would be great.
>
> Daniel Whitenack 
I think there are a couple of options here.  You could use the client/CLI to list-commit on a repo and get the latest by timestamp.  Alternatively, you could use our egress functionality to push certain output to an object store bucket for internal/public consumption: http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#egress-optional (then have people just grab what they need from there).
> I don't think there is a one command "latest commit" sort of feature at this point, but it should be relatively easy to script.
> Alternatively you could write that is Python or R as a function/package if that would be preferable.
>
> User 
> Ja I'll try that. 
> Putting out a request for a "latest commit" alias (or something similar) if you get there :slightly_smiling_face:
> At the moment our pipelines are running for a large fraction of the time. So master is effectively unusable

**Comment by dwhitena** [comment]
I think the real issue here is related to mounting.  Because, *I think* that `master` will always give the latest in pipelines and using the CLI/client, right?

**Comment by jdoliner** [comment]
The underlying issue here is #1414. `master` will give you the latest commit unless you're committing to multiple branches at the same time in which case the latest commit isn't super useful. Because files will appear and disappear from it.

**Comment by jdoliner** [comment]
I think I'm going to close this for now in favor of #1414. Feel free to reopen if you think there's something different between them.

**Comment by dwhitena** [comment]
Perfect.  Thanks @jdoliner.
