### ISSUE TITLE
Multiple glob patterns, one datum

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1929]
Here is the scenario:

- you have two directories in a repo, `myrepo`
- in one of the directories you have `file1`
- in another of the directories you have `file2`
- you have a processing stage that always needs both `file1` and `file2` regardless of the other data in a cross or union.  That is, you need `file1` and `file2` in every datum that is processed (they can't be split).

Currently, you can't really do this without a glob pattern of `/` and `lazy`, because you can't specify a single pattern that matches both files.  Well, you could specify a pattern with a `*` for the directories that matches both, but that would split the two files into different datums.

Is this something we want to address?  Note, this request came from a user in Slack.

**Comment by jdoliner** [comment]
I think we actually support this pretty well, if you do an input like this:

```
{
  "cross": [
    { "atom": {
      "repo": "myrepo",
      "glob": "file1"
    }},
    { "atom": {
      "repo": "myrepo",
      "glob": "file2"
    }},
    ...
  ]
}
```

This will have `myrepo/file1` and `myrepo/file2` in every single datum along with whatever `...` produces.

**Comment by jdoliner** [comment]
Gonna close this because I think we satisfy this use case but feel free to reopen if I'm wrong.

**Comment by banchee** [comment]
@jdoliner Gonna give the two inputs and same repo a go. Wasn't aware you could use multiple inputs with same repo, but this is great, will solve my issue 👍

**Comment by banchee** [comment]
@jdoliner Im using pachctl version 1.4.7 and get this error when trying it out 

```
pachctl update-pipeline -f borrower_merge.json                                                                                                                                               ‹ruby-2.3.1›
conflicting input names: platform_borrower
```

Should I try the 1.4.8 pre release?

**Comment by banchee** [comment]
Just a suggestion, not sure how hard something like this would be implement. But as a developer and having to setup pipeline and updating them. To have a single datum with multiple files from a repo I would like to do soemthing like this 

```
{
        "atom": {
          "repo": "platform_borrower",
          "glob": ["/profiles/borrower_all.jsonl", "/applications/borrower_all.jsonl"]
        }
}
```

**Comment by jdoliner** [comment]
@banchee the issue you're hitting is that the inputs are winding up with the same name because we use the repo name when there's not an explicit name specified. You can fix this by explicitly setting the name, so something like:

```
"input": {
    "cross": [
      {
        "atom": {
          "name": "profiles",
          "repo": "platform_borrower",
          "glob": "/profiles/borrower_all.jsonl"
        }
      },
      {
        "atom": {
          "name": "applications",
          "repo": "platform_borrower",
          "glob": "/applications/borrower_all.jsonl"
        }
      },
      ...
    ]
}
```

---

That syntax for doing multiple glob patterns is a lot more concise, however it's unclear if it's a union or a cross. I could reasonable see that meaning "show me all files that match either glob pattern in a single datum" or "show me all files that match either glob pattern in different datums". We'd need to have some way of indicating which one of those the user wanted which would start to duplicate the functionality of `cross` and `union`.

**Comment by dwhitena** [comment]
Thanks @jdoliner.  Makes total sense.

**Comment by gabrielgrant** [comment]
related: auto-merging multiple inputs sourced from the same repo #2441
