### ISSUE TITLE
Figure out better way to build external PRs

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1935]
https://github.com/pachyderm/pachyderm/pull/1918

Is an example of a PR that has a failed build for privilege reasons. The [build](https://travis-ci.org/pachyderm/pachyderm/builds/240455220?utm_source=github_status&utm_medium=notification) fails on the line where it tries to load the secret from travis. This is expected.

I've seen golang / docker / kubernetes all use a GH integration / build bot to solve this. Basically someone who's a dev on the pachyderm org needs to say 'ok to build' in the comment on the PR then the build bot Does The Right Thing (pull that branch and redeploy it) to test it out.

**Comment by jdoliner** [comment]
I think this now works well since there aren't any secrets in travis.
