### ISSUE TITLE
Specify an input name for an union input

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1945]
Currently, when you have an union input over two repos `A` and `B`, your pipeline sees input files whose prefixes are either `/pfs/A/*` or `/pfs/B/*`.  The problem is that now your code needs to be able to look under two different paths (and knows not to error if one of those directories doesn't exist).  It'd be ideal if you could give a name to the union input, let's say `U`, and then all input files are put under `/pfs/U/*`.

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
This is now supported. You can't name unions but atoms within a union can be given the same name.
