### ISSUE TITLE
Use FUSE to support lazy

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1947]
Currently, each lazy file is backed by a real OS thread, as a result of which we can only support up to 10000 lazy files since Go doesn't allow more than 10000 OS threads.

We should look into using our FUSE driver to implement `lazy`.  Some of the challenges are:

* FUSE has a large API surface and therefore the driver will probably be prone to bugs.
* Most container images don't come with FUSE support.

**Comment by sjezewski** [comment]
We have a limit on the # of files we can support using lazy mode (~25k) which corresponds to the OS thread limit I think. FUSE would allow us to support a greater number of files. However, FUSE performance isn't great, so there would likely be a tradeoff.

Marking this as stale, as we haven't had requests for this.
