### ISSUE TITLE
Upgrade workers with new image

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1948]
Currently if there's been an update to our worker image, there is no easy way to ship that update to existing workers.  You'd have to:

1. Update pachd to the matching version (in other words, if you want your workers to be running `pachyderm/worker:1.4.8`, then you need to update your pachd to `1.4.8` as well).
2. Manually restart/recreate pipelines.

I can think of two ways to go about implementing a better upgrade process:

* Implement something along the lines of `pachctl upgrade` or `pachctl deploy --upgrade` that would upgrade workers with the image that matches the `pachctl`'s version.
* Make it so that when pachd restarts (which is inevitable when pachd itself is upgraded), it checks the worker versions of existing pipelines and recreate them if they are out-of-date.

**Comment by jdoliner** [comment]
I think I prefer solution 2. It seems cleaner because `pachd` is the thing that normally makes the RCs so this way it's very easy to reason about potential race conditions. It also means not having to add a step to the upgrade process which is always preferable to adding a step.

**Comment by derekchiang** [comment]
Actually this turned out to be a nonproblem.  You just `pachctl undeploy` and `pachctl deploy` and all workers will be started with the latest version.
