### ISSUE TITLE
custom release process still updates brew

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1959]
Which means we can't have a point release available alongside a custom release. I think we chatted about supporting multiple releases simultaneously. This would allow us to have a custom release as needed.

Another alternative that would've worked for me would've been to run goxc in a way that just generated binaries, and didn't upload anything. That is probably a simpler approach.

**Comment by sjezewski** [comment]
stale

**Comment by sjezewski** [comment]
In the past we've cut custom images, which usually satisfies a customer's needs. However, we've run into this a few times recently -- the customer needs an RC and/or a custom install. Yes, they could download the binaries from GH, but mac users prefer using homebrew.

Seems like we can support a homebrew formula at 0.0 and include the sha in the additional version slot. Which would give us the ability to host custom releases in a way that doesn't occlude the latest release.

**Comment by ysimonson** [comment]
This appears to no longer be an issue, though I'm not sure where it was fixed.

**Comment by jdoliner** [comment]
We now seem to have the opposite problem which is that non-custom releases do not update brew, at least that don't merge in the updated brew formula.
