### ISSUE TITLE
update-pipeline

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1963]
We have a number of use cases we've collected over the last few months that have to do with updating a pipeline after it's been created, in this issue I'm going to outline those use cases and start talking about how we could solve them.

### Use cases
 
- Full update. This is the case where you want to update your code and rerun everything. This is one of the few use cases that `update-pipeline` already supports well.
- Fix broken code. Your pipeline was running fine and had processed many datums until it hit a datum it couldn't process for some reason. You want to update the code to process this new datum but not reprocess the datums that were successfully processed.
- Fix incorrect code. Similar to "Fix broken code" except that in this case rather than the code erroring it outputted data that's in some way incorrect. You want to reprocess the incorrect datums and keep the correct datums intact.
- Make a semantically meaningless change. Often times you want to update something like the parellelism_spec of your pipeline, a change which shouldn't affect the output in any way. In this case it's you want to preserve all of your previously processed datums.
- Rerun datums. Some pipelines are non deterministic, for example scraper pipelines. Sometimes you want to rerun some (or all) datums without actually changing the code.

### Design Questions

- Do we want the API to be in terms of datums or commits? (or perhaps both) Commits can be a lot easier to handle than datums since there can be massively large numbers of datums inside each commit. However if you have a case where a single commit has several datums then a commit based api forces you to treat all those datums the same which you might not want to.

- Do we want a way to delete individual datum/commit outputs (which causes the datum/commit to be rerun on the next run) or do we want to allow the update pipeline API to specify datum/commit lists not to run (or to run)

### Actionable changes

Some of these may be controversial so not all of these are necessarily things we want to do.

- Don't user version number as part of the hash, this is a necessary first step for supporting semantically meaningless changes. The reason that code reruns when you udpate fields like `parellelism_spec` is that the version number gets incremented. I think we probably still want a version number because it's handy in a number of other ways. The version number was originally added so that we could rerun pipelines so we'll likely need a new way to do that. I think we could possibly add a field specifically for forcing reprocessing and a special flag which causes it to be incremented (maybe `--force`).
- Don't base datum hashing on `Transform`. This would help us address the "Fix broken code" use case because it would allow users to update their `Transform` without dissociating their pipeline from the previous computed values. This would allow us to be more explicit about when we wanted a keep datums around and when we want to reprocess them. On the other hand there does seem to be something very powerful about having datums content addressed by code, although it's a bit hard to pin down exactly what the value is.
- Add a `delete-datum` (name is WIP) command which deletes the cached value for the datum allowing it to be reprocessed. This has the downside that it might be kind of racy with a pipelines that's already running so it's probably going to be necessary to first stop the traffic to the pipeline before you do this. Or maybe you just need to update the pipeline first and then call `delete-datum`.

**Comment by gabrielgrant** [comment]
Sounds like this addresses #1738

**Comment by jdoliner** [comment]
@gabrielgrant yes, it is, I'm going to close that issue in favor of this one.

**Comment by gabrielgrant** [comment]
Also, re: pipeline versions, it would be helpful if old pipeline specs were stored (maybe just as a list within the PipelineInfo document?) before being replaced, to make it easy to access previous versions (right now I need to search through old jobs to find the transform spec)

See #1940

**Comment by jdoliner** [comment]
Storing multiple versions is going to be tracked in https://github.com/pachyderm/pachyderm/issues/1036 not in this issue. It is something that we'll add though.

**Comment by derekchiang** [comment]
Re: the first "Actionable change":

Couldn't we keep the version number in the hash, except that we only increment the version number for semantically meaningful updates?  For instance if a user updates `input` or `transform`, we increment the version.  Otherwise we don't.

**Comment by jdoliner** [comment]
We definitely could, but I think it's going to be good to have true version numbers such that any change results in it incrementing and users can always tie a particular version number to a particular pipeline info. It's really weird to think about not incrementing the version number in a scenario where we're storing multiple pipeline versions because you'd inspect the different versions of the pipeline and see 5 copies of version 2.

**Comment by mightyguava** [comment]
What has been implemented already from this issue? It looks like the default for update-pipeline is now to not reprocess old data, with a `--reprocess` flag.
