### ISSUE TITLE
Incremental feature broken, mounts changed files  after the glob.

### ISSUE THREAD

**Issue by abhitopia** [pachyderm/pachyderm#1965]
Hi, we are trying the new incremental feature `incremental: true` in our work. 

1) Added a file `configurations/config.json` to `hello` repo.

2) Deploy a pipeline with following config
```json
{
"incremental": true,
"repo": "hello",
"glob": "configurations/config.json"
}
```
3) Everything works fine at this stage.
4) Modify and commit the `configurations/config.json`
This fails the new job because 

now the mounted files are `/pfs/hello/configurations/config.json/configurations/config.json"  (Notice double config.json

P.S. To reproduce the problem, follow instructions in https://github.com/abhitopia/pachy_bug

**Comment by abhitopia** [comment]
cc: @jdoliner

**Comment by jdoliner** [comment]
@abhitopia sorry you hit this, seems like this should be a very reproducible issue, I'm going to take a crack at reproducing it right now.

**Comment by abhitopia** [comment]
@jdoliner - Thanks. I think the possible solution is that whatever is mounted to the pipeline as `/pfs/repo` is actually an intersection of output of `DiffFile` and `GlobFile`.

P.S. - I am not familiar with go language, but I am referring to #1832 and I couldn't find any intersection between glob and diff files.

**Comment by abhitopia** [comment]
@jdoliner - also, if you need help reproducing the issue, please let me know.

**Comment by jdoliner** [comment]
I wasn't able to reproduce this, is it possible that the file was actually put under the path `configurations/config.json/configurations/config.json`? The semantics of `put-file` can be a bit confusing sometimes so it's possible to wind up with paths like this.

**Comment by abhitopia** [comment]
@jdoliner - I am confident that file was put correctly. Because when I check the contents on original repo `hello`, they are correct as seem using `list-file` and 'get-file`. Its just how its mounted inside the pipeline that changes.

**Comment by abhitopia** [comment]
You can reproduce the error by following instructions here -
https://github.com/abhitopia/pachy_bug
