### ISSUE TITLE
Refactor request: rename `from_commit` to `after_commit`.

### ISSUE THREAD

**Issue by abhitopia** [pachyderm/pachyderm#1966]
`from_commit` is counter intuitive as it **excludes** the commit itself as explain in doc-

"input.atom.from_commit specifies the starting point of the input branch. If from_commit is not specified, then the entire input branch will be processed. Otherwise, only commits since the from_commit (not including the commit itself) will be processed."

Proposal: Rename `from_commit` to more intuitive `after_commit`.
Alternatively, add provision for both `from_commit` and `after_commit`

**Comment by JoeyZwicker** [comment]
Thanks @abhitopia. This is something we've been discussing already in #1737. Closing in favor of the other issue, but feel free to comment more on it there.
