### ISSUE TITLE
Mac PACHCTL network issue on Master branch

### ISSUE THREAD

**Issue by jnevin** [pachyderm/pachyderm#197]
**Problem summary:**
Executing `pachctl` commands result in a `connection refused` error
I'm pretty sure I'm doing something dumb with SSH port forwarding (I'm using Docker-Machine ssh, see below) -- would appreciate advice, I'm stuck!

** Environment: **
I'm trying to get my local Pachyderm environment running properly on Mac El Capitan that is installed with the latest Docker 1.10.1, latest Docker-Machine 0.6.0, latest Docker-Compose 1.6.0. 

My Docker host uses the virtualbox driver and devicemapper for storage driver.

I installed Fuse 2.8.3 from the OSXFusion link in QuickStart.

I installed the `kubectl` CLI and it runs correctly.

I modified my source to use port 30650 and 30750 to serve traffic so that the SSH forward commands stopped giving me the "root" permission issue on reserved ports.

** Running the code and reproducing the issue: **

`$ make launch-dev`
output:
etc/kube/start-kube-docker.sh
9eefbadd0ecbcb2d5a79fd6f54e64d3fbd87f05209a1ae07fb8f230d50592b3d
487683653da795664b3518bee469ea43acfafdbdf5c78362c502dc2d8de5c376
d66ad435dddace4b0c18f91dedf7bc0b9337d80d246f4d42f1b740126de61a08
kubectl  create -f etc/kube/pachyderm.json
serviceaccounts/pachyderm
replicationcontrollers/etcd
services/etcd
services/rethink
replicationcontrollers/rethink
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30650,tcp:30750) to serve traffic.

See http://releases.k8s.io/HEAD/docs/services-firewalls.md for more details.
services/pachd
replicationcontrollers/pachd
secrets/amazon-secret

`$ kubectl get svc`
output:
NAME         LABELS                                    SELECTOR      IP(S)        PORT(S)
etcd         app=etcd,suite=pachyderm                  app=etcd      10.0.0.137   2379/TCP
                                                                                  2380/TCP
kubernetes   component=apiserver,provider=kubernetes   <none>        10.0.0.1     443/TCP
pachd        app=pachd,suite=pachyderm                 app=pachd     10.0.0.57    30650/TCP
                                                                                  30750/TCP
rethink      app=rethink,suite=pachyderm               app=rethink   10.0.0.93    8080/TCP
                                                                                  28015/TCP
                                                                                  29015/TCP

`$ docker build -t mypachyderm .`

`$ docker-machine ssh storagemappedmachine -fTNL 8080:localhost:8080 -L 30650:localhost:30650`

`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock --privileged mypachyderm /bin/bash`
`# make install`
`# pachctl mount -p /tmp/pfs`
`2016/02/17 18:59:48 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30650: getsockopt: connection refused"; Reconnecting to "0.0.0.0:30650"`

**Comment by jdoliner** [comment]
Hmm, everything here looks like it should work except the last part.
It looks like you're starting up `bash` in a new container with the image `mypachyderm`, that container won't have be able to talk to pachd because the port forwarding is on the local machine not in the container.

2 options:
- You can just `make install` and `pachctl mount` on your Mac, no need for Docker.
- If you want to run a container that has access to the pachd API I'd recommend running it under k8s, `pachctl` should work automatically due to k8s injecting the correct env variables to find the `pachd` service.

**Comment by jnevin** [comment]
Thanks jd

Problem: on Mac, a simple `make install` does not generate the `pachctl` CLI. I could only get `make install` to work from within a Docker.

**Comment by jnevin** [comment]
For instance:
`$ make install`
`$ whereis pachctl`
`$`

**Comment by jdoliner** [comment]
Ahh, `make install` is just doing a `go install` under the hood so you might need to put `go/bin` on your `PATH` env variable.

**Comment by jnevin** [comment]
hmmm... go/bin is already on my path
so, for example:
`$ go version` outputs:
go version go1.5.3 darwin/amd64

but a direct invocation of the make command fails to create `pachctl` locally:
`Jamess-MBP:pachyderm jnevin$ go install ./src/cmd/pachctl ./src/cmd/pachctl-doc`
`Jamess-MBP:pachyderm jnevin$ pachctl`
`bash: pachctl: command not found`

**Comment by jdoliner** [comment]
Sorry, by `go/bin` I actually meant `$GOPATH/bin` what do you get if you do `ls $GOPATH/bin/pachctl`?

**Comment by jnevin** [comment]
OK, addiing `$GOPATH/bin` to my PATH now exposes `pachctl` as executable -- now back to seeing if I can get `pachctl` to do mounts and other good stuff!

**Comment by jdoliner** [comment]
Closing feel free to reopen if there are more issues.
