### ISSUE TITLE
Shim in empty directories into workers

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1975]
As of now, Pachyderm will record empty directories in a repository, but it won't check those out and shim them into a running worker.  Some users have use cases where they need to see all directories even if they are empty.

**Comment by tobschmidt** [comment]
We are seeing this issue with our ML pachyderm setup where the first pipeline calls a script that downloads files from S3 and creates a particular directory structure, with some of these directories empty. The following pipeline runs through all directories and populates them according to some predefined rules. The second pipeline does not know about how the directory structure was created or which directories should be present. Therefore, when some of the empty directories are missing, the second pipeline does not populate all required directories / files.

**Comment by tobschmidt** [comment]
Here a dummy pipeline scripts to reproduce the problem:
[pipeline-with-empty-dirs.json.zip](https://github.com/pachyderm/pachyderm/files/1096298/pipeline-with-empty-dirs.json.zip)
