### ISSUE TITLE
Kill backgrounded pachctl port-forward when run again

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1980]
When sleep/wake cycling a laptop, `pachctl port-forward` loses it's connection, but remains alive.

Starting a new `pachctl port-forward` should kill off the old one and it's children.

Note: Killing the `pachctl port-forward` process does not kill it's child `kubectl port-forward` processes, but when the all the `kubectl port-forward` processes are all killed, the pachctl process dies.

cc: @JoeyZwicker

**Comment by JoeyZwicker** [comment]
This also comes up when users have pachd deployed and then want to deploy the dashboard (--dashboard-only). They are forced to manually kill their other port-forward processes and then redo it. 

This issue should be an easy fix, right?
