### ISSUE TITLE
Allow dynamic scaling of clusters

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#20]
Right now clusters are statically configured and thus can't take advantage of new machines that are added to the cluster. This is a basic piece of functionality that needs to be added to pfs.

This issue will serve as the design discussion for this feature. (Details to come later).

We should plan on having this implemented for 0.4.

**Comment by JoeyZwicker** [comment]
Right now this is done by de-scheduling and rescheduling services in fleet. I imagine this will be improved with Kubernetes integration and will eventually result in a "rebalance" command of some sort.

**Comment by jdoliner** [comment]
This has been subsumed by replication work being done now and isn't serving much purpose.
