### ISSUE TITLE
How to Work With Large, Local Datasets?

### ISSUE THREAD

**Issue by pnovotnak** [pachyderm/pachyderm#2022]
Forgive me if this is in the docs or another ticket. We at Cyrus use large protein databases in our pipelines to search for protein sequence alignments, finding homologs, etc. Is there a good way for us to expose 300GB+ of rarely changing (only additive changes) datasets to very parallelized pipelines in an efficient manner?

If there is not a way to handle this case, we are probably able to add this functionality if we are given some pointers on where to start work.

cc @javierbq

**Comment by JoeyZwicker** [comment]
hi @pnovotnak! Large, highly parallelized, and additive data sets are a perfect use case for pachyderm. 

The biggest question will be how you want pachyderm to interact with the database itself. If you're open to just dumping the DB data into Pachyderm (object storage, which is very cheap), Pachyderm can be really smart and only process to new data to massively save on compute requirements. 

What does the shape of your data look like? Is it one big table of proteins?

If you want to talk through this live, you can jump in our [public Slack channel](slack.pachyderm.io) and we can help you structure your data for maximum performance and storage efficiency.
