### ISSUE TITLE
Shouldn't be able to read files before commit is finished

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#203]
This came up when working through the grep example. JD says the bug was introduced when he updated the 'pachctl list-commit data' command to include the commit sizes

Ideal behavior

    pachctl list-commit data

listing includes cumulative data size (for this commit)

trying to cat the file:

parent is nil - file not found
parent non nil - get parents data

**Comment by jdoliner** [comment]
Believe this one is fixed. Reopen if that's not true :)
