### ISSUE TITLE
Update-pipeline non-re-process provenance

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2041]
The problem scenario in my mind is the following: "I have a production model in place, I run a million plus inferences with that model, I update my production model but don't want to reprocess the million plus previous results, but I ALSO want to maintain the provenance for the previous and new results (which basically means I have to know which datums in a commit were processed with which version of the model)

**Comment by sjezewski** [comment]
We're starting to see more and more cluster maintenance type of requests like this. This seems like a very reasonable use case we need to support.

**Comment by jdoliner** [comment]
I'm really having trouble understanding what this is asking for. The default behavior of `update-pipeline` is to not re-process things and provenance should never change after commits are finished so in what sense is it not maintained?

**Comment by jdoliner** [comment]
Closing this since I'm unclear on what this is asking for that we don't already do. It seems like maybe the thing here is being able to see which commit a file was created in, but I think `list file --history` should do that for you.
