### ISSUE TITLE
Replace SHA256/512 with a modern hashing algorithm

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#2042]
SHA256/512 is a slower than modern algorithms.
While some implementation provide hardware acceleration when it is available it seems that Go does not use it. Instead it uses [an AVX2 implementation](https://github.com/golang/go/blob/master/src/crypto/sha256/sha256block_amd64.s#L13) which may or may not be faster than the completely hardware accelerated implementation.

If we hash only to compare file contents, a CRC algorithm is a lot faster than any hashing algorithm.
CRC32 is also hardware accelerated and Go indeed uses [this instruction](https://github.com/golang/go/blob/69972aea74de6a0397a05281475d1ca006da7bb0/src/hash/crc32/crc32_amd64.go#L19).
If you don't want to add further dependencies this is a good way to speed up pachyderm.
Adler32 can also be used instead but it will provide more collisions for short files.

What needs to be done is to calculate the partial CRC instead of the partial SHA256 [here](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/hashtree/hashtree.go#L350).
Then, if you want to compare a node's contents to another node you compare the CRCs of the nodes and only if they match, compute the hashes of both nodes, store them and compare again using the hashes.
This will reduce computing resources spent on hashing.

Furthermore, SHA512 used [here](https://github.com/pachyderm/pachyderm/blob/395935ba9a5623cb408eef0c3493477898b40789/src/server/pfs/server/hash.go#L12) seems to be unnecessary and can be replaced with a faster algorithm.

If another dependency can be added, both xxhash or metrohash provide a high quality and fast CRC implementations, both are superior to CRC32 in speed even with hardware acceleration. However, it seems that the relevant Go libraries don't implement it.
In any case, the x86-64 64bit hash implementation provided by [cespare/xxhash](https://github.com/cespare/xxhash) is much faster than SHA256 and is used in production by InfluxDB.
MetroHash does not have a Go port that is production ready in my opinion.

If security is a concern, both SHA256 and SHA512 are no longer considered secure enough.
SIPHash is considered more secure and is faster than both algorithms.
I cannot think about any attack vectors that might require a secure hash function for Pachyderm but I'm no security researcher.
There are two Go implementations for SIPHash that can be found [here](https://github.com/aead/siphash) and [here](https://github.com/dchest/siphash).

This change may require a migration.

**Comment by thedrow** [comment]
FYI the go port of xxhash now implements the CRC algorithms. See https://github.com/OneOfOne/xxhash/blob/master/xxhash.go#L79

**Comment by derekchiang** [comment]
Agreed that CRC (or any hashing schemes designed specifically for integrity checking) would be a better choice than SHA since we don't really need to worry about attacks at the datum hash level.

**Comment by sjezewski** [comment]
stale
