### ISSUE TITLE
Documentation for incrementality

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2056]
We some high-level docs in the pipeline spec, but incrementality is a pretty complex flag to use and understand. We needs a short doc that explains in detail what data will be available, how it's exposed, and how to use it (files added, modified, or deleted). This should include a simple example.

I think creating a doc for performance optimizations that includes incrementality, batch, perhaps more details on lazy/copy elision or other optimizations we often tell users. 

I don't think @dwhitena nor I actually know how incremental really works. @jdoliner, since you're working on `batch` too, can you take a first pass at this doc and then we'll review and expand?

**Comment by dwhitena** [comment]
Added here: http://pachyderm.readthedocs.io/en/latest/fundamentals/incrementality.html
