### ISSUE TITLE
HTTP file server should allow downloading directories and entire repos

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2062]
Currently the HTTP file server returns an empty response if a directory is requested. As discussed with @sjezewski we would like to also be able to download directoiries and entire repos as as a single .zip or .tar.gz file

**Comment by sjezewski** [comment]
We have to make sure we do this streaming, but looks like the underlying libraries support this:

https://bitbucket.org/kardianos/staticserv/src/5a536ebb8016d795187138ad99881533e14a59ef/main.go?at=default#main.go-232

**Comment by gabrielgrant** [comment]
@sjezewski is this still an issue, or did this get implemented along with raw/non-download file output?

**Comment by sjezewski** [comment]
This has not been implemented. I'm marking it as stale

**Comment by gabrielgrant** [comment]
I still have an open issue on the dash that is blocked on this

**Comment by ysimonson** [comment]
This service is on life support; the long-term goal is to remove it (see #3791.)
