### ISSUE TITLE
BranchInfo objects should have a "created_at" and "updated_at" fields

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2065]
`updated_at` would be the timestamp when it was last updated to point at a new commit (or `created_at` if it's never been updated)

Use case: The UI generally lists objects by most recently active first and would like to do the same for branches (github does this for branches too: https://github.com/pachyderm/pachyderm/branches)

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
This seems reasonable to me.

**Comment by JoeyZwicker** [comment]
Request from a user that I think goes here:

They need the timestamps for the files/datums to not be updated when they are skipped. Currently, all files have a timestamp that matches the commit, even when the datum is skipped. They need the updated_at timestamps for each file to be correct for audit reasons. They really like Pachyderm's prov, but need to also be able to prove easily when the data was last changed.

**Comment by jdoliner** [comment]
Looking at this again, I actually think all the data you guys are after is already present in the system, it's just not exposed in the nicest way. You can think of a branch has having an `updated_at` field equal to the `Finished` field of the head commit a `created_at` field equal to the `Finished` field of the root commit of the branch.

@JoeyZwicker I don't think your use case applies here, this is about Branches, not Files. The information you're after is already present though, it's just the timestamp of the first commit a file shows up in.

**Comment by gabrielgrant** [comment]
Technically those definitions aren't necessarily accurate for manually updated branches, but they're probably sufficient for the use case I'm describing, since they should hold for pach-maintained master/stats branches

**Comment by JoeyZwicker** [comment]
@jdoliner, yup that makes sense. But finding the first commit where a file shows up — or moreso the last commit where the file was actually updated isn’t actually easy to access. Should I make a separate issue for it?

**Comment by gabrielgrant** [comment]
@JoeyZwicker Sounds like https://github.com/pachyderm/pachyderm/issues/1457 is basically what you're looking for?
