### ISSUE TITLE
pachctl commands & help text should reflect pipeline and job naming changes in API

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2071]
`start-pipeline` --> `pause-pipeline`
`stop-pipeline` -->  `unpause-pipeline`
`stop-job` --> `kill-job`

**Comment by JoeyZwicker** [comment]
I don't think any of these were actually implemented so closing. I still think these are better names for the commands, but doesn't seem like they're going to be changed right now

**Comment by gabrielgrant** [comment]
This came up again in the context of discussing/trying to clarify the behavior of `stop-job` vs `delete-job`

**Comment by ysimonson** [comment]
This has been fixed with 1.9
