### ISSUE TITLE
Autoscaling jobs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2074]
Currently, Pachyderm pipelines/jobs don't interact nicely with cloud autoscaling. We only check the number of k8s nodes to determine num_workers at pipeline creation/update. Users are [forced into a tricky workaround](http://pachyderm.readthedocs.io/en/latest/managing_pachyderm/autoscaling.html#default-behavior-with-cloud-autoscaling).

In discussion with @jdoliner it shouldn't be hard to have jobs regularly check the number of k8s nodes and dynamically scale the number of workers. An MVP version of this would be to check once at job creation, so jobs are scaled based on available nodes.  The full feature would actually be able to scale mid-job since that's a main use case. 

Things to consider:
- We probably don't want pipelines that are scaled down to be doing the checking and adding more workers when there's no work for them to do. So this check should probably be at the job level.
- If the number of k8s nodes is reduced, we probably don't want to kill workers that are already successfully scheduled on an active node and processing data. Is it possible to be smart about which workers get killed or which workers to "slate" to kill after they finish their current datums (aka: no assign them any new datums)? This might be too complex to actually implement on a first pass.

**Comment by JoeyZwicker** [comment]
We'll need to address autoscaling with a number of our incoming enterprise users so this will likely need to be discussed more. Interactions with `coefficient` also seem problematic.

**Comment by ysimonson** [comment]
Dupe of #228?

**Comment by JoeyZwicker** [comment]
This and #228 might actually be quite outdated. I think k8s autoscaling has gotten much stable and we haven't seem many people running into issues like this. 

While not totally relevant: #3065 is the flavor of this that we still see requested regularly. 

Closing for GH cleanup since there's not much useful info here
