### ISSUE TITLE
Pipelines always require 1 pod running

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2080]
From a user evaluating Pachyderm. 

ScaleDownThreshold still leaves the master pod running to watch for new commits and that pod maintains the resource requests of the pipeline even when idle.  

With a large number of pipeline or individual pipelines with significant resource requests, this can be a massive waste of resources.

**Comment by jdoliner** [comment]
The simplest solution to this would be to shuffle around the master responsibilities a little bit. The master pod currently does 3 things:

- watch for new commits, and create jobs when they arrive
- run those jobs, pumping data through the workers
- finish those jobs and materialize the final result

The first responsibility is the one that forces us to keep a single pod running.

The easiest solution to this would be to move the logic that covers the first responsibility into the pipeline master thus eliminating the need to keep a pod running for the master.
The down side to this is that it concentrates the workload slightly more on a single node but I don't anticipate it being a problem unless there's a very large number of pipelines.

**Comment by JoeyZwicker** [comment]
I think this was resolved by removing the resource request from the master worker after the `scaledownthreshold` and may also be address by the worker refactor. @jdoliner reopen if I'm wrong and it's still an issue.
