### ISSUE TITLE
Corrections to Lead Developer Advocate Position on jobs.html

### ISSUE THREAD

**Issue by landonbjones** [pachyderm/pachyderm#2094]
While working on my cover letter I noticed a typo. My [mom](http://vedaboydjones.com) noticed a lot more and her suggestions are below:

**Lead Developer Advocate**
Pachyderm is looking **[insert for]** someone to start, lead, and build our Developer Advocacy team. We're is **[delete is]** completely open source **[insert comma]** and we're just hitting our community and product stride where we need someone full-time to build machine learning and data science examples, write blog posts, give talks, evangelize Go, Docker, and Kubernetes, and generally just get Pachyderm in on the conversation. 

"Wearing many hats" would be and **[should be an]** understatement as you're **[should be your]** job, in addition to the above, will include working with developers and customers to get their data into Pachyderm. If you want, you'll even get some exposure building some of the infrastructure itself too [delete too] as you tackle fixing some of the bugs and usuability **[sp. usability]** challenges you come across. The role is perfect for someone who considers themselves a social engineer, loves to teach, and get involved **[delete get involved and add likes involvement for parallel construction]** in tons of small projects.

**Comment by derekchiang** [comment]
Hi @landonbjones, thanks for your (and your mom's) suggestions!  I've made the corrections which should be reflected on the website pretty soon.
