### ISSUE TITLE
Resource requests require all resources specified?

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2096]
From a user:

> hey we're making use of GPUs for training purposes and found that the pipeline wouldn't run with just the gpu in the resource spec, as specified in the docs:
> ```"resource_spec": {
>       "gpu": 1
>   },
> ```
> we had to add in memory and CPU as well

Ideally, we shouldn't have to specify all resource specifications to get GPU support, and, more generally, we shouldn't have to specify all resource specification if we only care about one.  I thought I tested this for GPUs, but maybe it's not totally working.

**Comment by jdoliner** [comment]
Closing in favor of #2075
