### ISSUE TITLE
Datum messages (and thus DatumInfos) should contain the datum's Job

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2099]
For consistency with the rest of the API, and as general good practice, the returned message should contain all the relevant state for an object, without a need to manually add info used to construct the original request for the object. Currently this isn't the case for Datums, as the only link they have to their containing job is that the job ID is used to construct the `List`/`InspectDatum` request, meaning the client code handling the reply has to know to explicitly insert this info into the reply message if it's to be used elsewhere.

Compare to, for example, a `CommitInfo`, which contain a `Commit`, which in turn contains a `Repo`.

**Comment by jdoliner** [comment]
Datums don't correspond to a single job though, there's more than one job you can request to get the same datum.

**Comment by gabrielgrant** [comment]
added this as an edit, but for clarity, i'll make it a new comment:

Basically, if the JobID is part of the "composite primary key" of a datum (which it currently is -- you can't fetch a datum without a JobID), then the `Datum` message should have a `Job` field

**Comment by gabrielgrant** [comment]
offline discussion with JD: although a "Datum" as a group of files is not specific to a Job, the message we currently return from the Datum API contains state that is relevant only to the specific Job for which that datum was requested. This is where the distinction between "Datums" (a group of files) and "runs" (the processing of that group of files within a given job) becomes pertinent.

Conclusion: for the moment, the `DatumInfo` reply should contain the `Job` to which it applies. Later, once we expose `Run`s as a first-class object, that field (and the job-specific state info) should probably be removed from `Datum`, and put into a `Run` message

Also discussed that "run" may be the wrong term to use, since many (most?) runs are not actually executing ("running") the user's code, and in those cases the only really important info is the fact that a run is skipped

**Comment by sjezewski** [comment]
Fixed in https://github.com/pachyderm/pachyderm/pull/2117
