### ISSUE TITLE
make clean-launch-dev removes the dash service, but not the deployment or the pod(s)...

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2108]
...and `make launch-dev` doesn't recreate any dash-related resources

I think this has to do with the way things are tagged (`suite=pachyderm`?)

My inclination is that if `make launch-dev` isn't going to deploy the dash (which i think we said it shouldn't), then `make clean-launch-dev` shouldn't remove it

**Comment by JoeyZwicker** [comment]
Is this done or ever going to be done?

**Comment by gabrielgrant** [comment]
AFAIK this has not been done, and still should be. I don't _think_ it should take long for someone who has a better understanding of how this deploy/undeploy code works and how we group pachyderm parts of the system (not sure if there's anything other than `suite=pachyderm`?). It may just be a matter of adding the right tag in the right place in the deploy manifest

**Comment by gabrielgrant** [comment]
Just ran into weirdness from this again:

```
$ make clean-launch-dev
# check that kubectl is installed
which kubectl
/home/gabriel/.local/opt/kubernetes/bin/kubectl
pachctl deploy local -d --dry-run | kubectl  delete --ignore-not-found -f -
kubectl  delete rc -l suite=pachyderm
No resources found
kubectl  delete svc -l suite=pachyderm
No resources found
$ kubectl delete all -l suite=pachyderm  # manually delete remaining pods
pod "dash-3498131396-mjg3h" deleted
deployment "dash" deleted
```
@jdoliner is this something that's easy to fix? Is there something that you're doing with the other pach pods that makes them go away that I could be doing with this dash pod?

**Comment by jdoliner** [comment]
This seems to be fixed now, just tested it.
