### ISSUE TITLE
Alternative object stores

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#211]
Is it currently possible, and if it isn't, should it be possible to use a separate pluggable object store as the backend for PFS.  PFS is the only storage system out there that I know of which provides git like versioning semantics on the data. But that versioning is distinct from the actual blob storage, so is it possible to attach PFS onto of an existing object storage container like S3,Ceph, or Swift? In this manner you could get all the version control goodness while at the same time reusing data storage infrastructure and replication infrastructure.

**Comment by jdoliner** [comment]
PFS is designed to use pluggable object stores for all the reasons you list here :)

We abstract object storage behind this interface `Client` in `src/pkg/obj/obj.go` The only things needed to add support for a new object store are:

- implement `obj.Client` for the object store
- add a way to pass the necessary credentials to pachd as a k8s secret

Right now we have clients for s3 and GCS. And secrets are implemented for s3.
We're planning to expand this a lot post 1.0.

Adding a new obj backend would be a great project for people looking to get started with Pachyderm dev so I've marked this issue as "noob friendly."

**Comment by JonathanFraser** [comment]
Seems easy enough, although I don't see any concept of locality in that interface. I presume its not  exposed currently?

**Comment by jdoliner** [comment]
It doesn't and I'm not sure if that would be possible. AFAIK most object stores don't expose locality (I don't think s3 or GCS do) so this API couldn't either.

**Comment by JonathanFraser** [comment]
Doing some leg work for the Ceph backend in particular.

There are two ways to access ceph as a object store, via the radosgw which provides a s3 like interface or via the librados library. 

The radosgw has a bug which was just recently patched preventing the go-aws-sdk from communicating with it properly. Specifically radosgw did not support absolute links which the sdk was sending. This was just recently merged into ceph (12 days ago) so we are likely not to see it in a stable version for a while. 

The second option is via librados, which is a C library and is required to be installed to build. There already exist go bindings for it, and integration would be relatively painless, however, it would need to be integrated with some build tag foo to prevent all users from requiring ceph to be installed.

**Comment by jdoliner** [comment]
@JonathanFraser thanks so much for the leg work.
My thoughts on this are that the ideal solution is to use radosgw since then we can reuse the code from our s3 implementation. That being said it's a relatively small amount of code the make Ceph work, it seems like the most painful part will be the build system.

When you say that it'll be a while before we see the changes in a stable version what does a while mean? I have no notion of what release cycles on ceph look like.

**Comment by JonathanFraser** [comment]
@jdoliner there would still need to be some credential monkeying to get ceph to work as it appears to have no concept of tokens. 

As for the ceph cycle, they do a development release once a month or so, this then gets stabilized into a production release some 3 to 4 months later. If you want an LTS release, that might be 8 months to a year out. 

The go wrapper on librados, seemed to work out of the box. While I have yet to integrate it as a pachyderm backend it, I was able to get it up and listing objects relatively quickly. Moreover, the functions more or less line up with the interface. 

If we need to use build tags then I would suggest going  with a method similar to how the stdlib handles sql backends. A scheme where an init function registers it with a frame work which then gets looked up at runtime. This would mean either using a connection string (not ideal), or putting the credential lookup in the same place as the object store code (probably reasonable).

**Comment by JonathanFraser** [comment]
I could be useful if the obj.Client interface had a few comments on it, of if there are some docs where can I find them. For example, when we graph a writer what happens if there is a preexisting object (error, open for truncate, other). Likewise, what is the name parameter in Walk. I assume it's a prefix but what if the backend does not have implicit support for prefixes.

**Comment by jdoliner** [comment]
@JonathanFraser these are good points, I just submitted pr which fleshes out the docs in obj.go a bit more. To answer you're questions directly, if an object already exists then you should return an error. PFS will handle the error depending on what type of object it was writing to obj store. The name parameter is indeed, I renamed it to prefix in the pr. If the backend doesn't have support for prefixes then we may need to figure something out, does ceph not support that? We only need it on a directory level (delimited by `/`s if that makes things easier).

**Comment by jdoliner** [comment]
Update on this, we now have support for both s3 and GCS!
I'm going to move this out of the 1.0 milestone, we'll add more object stores after we get it shipped.

**Comment by sjezewski** [comment]
While we don't explicitly support ceph, we now support azure storage, GCS, S3, and anything that minio can interface with (glusterFS, etc). So I'm closing this issue for now. If you still need ceph support, let's open a separate issue for that.
