### ISSUE TITLE
Pachd fails to load

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#2127]
Deploying on GCS, with the deploy command from the docs.
Pachd fails to load with this error:
```could not initialize treeCache: Must provide a positive size```

Looking at the code it seems that this maybe has to do with the new cache setting and that the default cache value has not been set.

I tried redeploying with 
```--block-cache-size=1M```
but that did not help

**Comment by kalugny** [comment]
This is happening both on `1.5.1` and `1.5.2`

**Comment by najibninaba** [comment]
This is happening for me as well, version 1.5.2 on GCS.

**Comment by jdoliner** [comment]
We have a fix for this which is in master and should be released shortly in 1.5.2. Until then you can work around this issue by adding `--dry-run` to your `pachctl deploy` invocation and then  manually editing the `BLOCK_CACHE_BYTES` environment variable to be a nonzero value.

**Comment by najibninaba** [comment]
I've tested with version 1.5.3 and I've successfully deployed 1.5.3 and ran through the beginner tutorial with no problems.

Recommend to close this issue.
