### ISSUE TITLE
Support exposing ConfigMaps to pipeline workers

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#2133]
ConfigMaps are much like secrets in Kubernetes. The only difference is that they are not encrypted at rest.

See https://kubernetes.io/docs/tasks/configure-pod-container/configmap and https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/ for relevant documentation.

**Comment by sjezewski** [comment]
stale

**Comment by thedrow** [comment]
So this will not happen?

**Comment by marcadella** [comment]
You already support secrets, I guess it would be little work to support configmaps as well.
