### ISSUE TITLE
Feature Ask: Add Azure Data Lake support 

### ISSUE THREAD

**Issue by jpoon** [pachyderm/pachyderm#2135]
Pachyderm currently has support for persisting data to Azure Blob Storage. Feature ask to extend support to write to Azure Data Lake Store (https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-comparison-with-blob-storage) which is geared towards big data analytics workloads. 

cc @JoeyZwicker

**Comment by sjezewski** [comment]
stale

**Comment by JoeyZwicker** [comment]
We actively get this feature request from customers. When we get someone to "sponsor" this work, we'll reopen
