### ISSUE TITLE
Cross/Union misleading behaviour

### ISSUE THREAD

**Issue by jonandernovella** [pachyderm/pachyderm#2162]
I have observed a strange behavior when using the cross/union of two repos.

Steps to reproduce:

1. Run a pipeline with a number of files from repo X and one file from repo Y. No problem, it should work.
2. Upload a new file to repo Y via: `pachctl put-file (...)`
3. Change the pipeline definition for the pipeline to use the new file from repo Y.
4. Run `pachctl update-pipeline <name of pipeline>.json --reprocess`
5. Observe that the job cannot find the new file.

Version: 1.5.2.

**Comment by JoeyZwicker** [comment]
Thanks Jon. We'll look into this. But a few questions:

What do you mean by "change the pipeline definition to include the new file"? If the pipeline has repo Y as an input, shouldn't take it already be seeing that file based on the glob pattern? Or are you explicitly naming every file in repo Y?

Also, when you update the pipeline, you're saying it does see all of the files from Repo X and the old files from repo Y, but not the newest one? If you make additional commits to repo Y, do any of those files show up?

Is the above behavior consistent with both cross and union?

**Comment by jonandernovella** [comment]
By changing the pipeline definition to include the new file, I mean that I change the name explicitly of the file in repo Y in the pipeline definition.

Exactly, it does seem to see the old ones but not the new one. New commits do not seem to help, and the above behavior seems to be consistent with both cross and union.

**Comment by JoeyZwicker** [comment]
Can you post your before and after pipeline definition? That'll help me repro because my initial attempt in my local setup and pipeline isn't doing it.

**Comment by jonandernovella** [comment]
@JoeyZwicker Issue spotted. The thing was that the new file did not exist in the initial commit, so therefore it was not being processed.
