### ISSUE TITLE
Troubleshooting docs for when a pipeline gets stuck starting.

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2163]
A few users mentioned that this would be useful.  We have general troubleshooting docs for what to do when a pod is stuck in `CrashLoopBackoff`, but not generally what to do when a pipeline gets stuck starting.  In particular, when a pipeline pod is stuck in `Pending`.

**Comment by JoeyZwicker** [comment]
Is there any immediate plan to add a troubleshooting doc back with all these types of little things? I'm not really sure there is. We've made this slightly better with other issues so I'm going to close for now.
