### ISSUE TITLE
gcloud kubectl vs. vanilla kubectl

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2185]
Apparently kubectl installed via gcloud causes issues for at least some of our deploys (AWS in particular).  We should document this at the very least, or get that install path working:

>  thanks for checking, really helped me narrow it down. On a clean environment it worked. After investigating I see that I had installed kubectl by running gcloud components install kubectl. After removing this from my PATH and using vanilla kubectl, it worked :sweat_smile:

**Comment by sjezewski** [comment]
This was when hitting the 'waiting for nodes to come online' issue that we've seen w k8s 1.7.0 (but was resolved w an update to the aws.sh script afaict).

FWIW, I have kubectl installed via gcloud and validated that kops 1.7.0 and kubectl 1.7.2 work ok for me and the aws.sh works fine.

**Comment by JoeyZwicker** [comment]
Seems like this is resolved. closing.
