### ISSUE TITLE
Separate the logs of different datums better

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#2190]
A small suggestion that will be useful:
When using `get-logs` it would be helpful to separate the logs by datum. Otherwise they get grouped together and it's hard to see.

For example. here's a little snippet I wrote with python to do it:
```python
current_file = None
for l in pps.get_logs('my_pipeline'):
    if l.user:
        if current_file != l.data[0].path:
            current_file = l.data[0].path
            print('\n\n', current_file, '\n', '=' * len(current_file), '\n')
        print(l.message, end='')

**Comment by gabrielgrant** [comment]
I might be misunderstanding what you're trying to achieve, but filtering by input file(s) is possible directly from `get-logs` today:

`pachctl get-logs --job=<job-id> --inputs /path/to/your/input/file`

**Comment by kalugny** [comment]
That's great.Close #2190  





On Tue, Aug 22, 2017 11:14 PM, Gabriel Grant notifications@github.com  wrote:
I might be misunderstanding what you're trying to achieve, but filtering by
input file(s) is possible directly from get-logs  today:

pachctl get-logs --job=<job-id> --inputs /path/to/your/input/file
