### ISSUE TITLE
Clarify GPU driver copy for nvidia docker images

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2194]
> user:
> @dwhitena Hi Daniel  pachctl version 1.5.3. Yes, that's right, the process is running and producing output as it should ( a model) but it's just not making use of the gpu
> 
> [9:34] 
> and yes, it is running on the correct node
> 
> [9:37] 
> No idea if the problem is actually the docker image since running: 
> docker run -it dwhitena/pix2pix /bin/bash 
> to enter the container and then running:
> python pix2pix.py --mode train --output_dir ./out --max_epochs 5 --input_dir /shared/ --which_direction BtoA
> results in the error:
> E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVICE
> 
> user:
>  what base docker image are you uusing? (edited)
> 
> Daniel Whitenack [10:22 AM] 
> it uses this image: https://github.com/affinelayer/pix2pix-tensorflow/blob/master/docker/Dockerfile, which uses `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04` as a base image.
> GitHub
> affinelayer/pix2pix-tensorflow
> pix2pix-tensorflow - Tensorflow port of Image-to-Image Translation with Conditional Adversarial Nets https://phillipi.github.io/pix2pix/
>  
> [10:22] 
> checking some previous messages related to nvidia images.
> 
> user:
> ok, we use the same one
> 
> Daniel Whitenack 
> [10:22 AM] 
> Ah, and it works ok?
> 
> user:
> you need to copy over the cuda drivers
> 
> Daniel Whitenack 
> [10:22 AM] 
> Gotcha, yeah, I figured it might be something like that.
> 
> user:
> ```        "cmd": [ "/bin/bash" ],
>     "stdin":[
>         "cp -d /rootfs/usr/lib/x86_64-linux-gnu/libcuda.* /usr/lib/x86_64-linux-gnu/ && cp -d /rootfs/usr/lib/x86_64-linux-gnu/libnvidia* /usr/lib/x86_64-linux-gnu/",
>             "python ..."
> ```
> (edited)
> 
> Daniel Whitenack 
> [10:23 AM] 
> Perfect! Thank you so much!
> 
> user:
> aah, thanks!
> 
> user:
> ya, took us a while to figure that out

**Comment by sjezewski** [comment]
It should be easier to add the paths and add them onto `LD_LIBRARY_PATH` colon delimited ... e.g.

```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/rootfs/usr/lib/..."
```

Instead of actually copying the files.

**Comment by dwhitena** [comment]
Yes, I agree with @sjezewski here.  But maybe we should make this clearer in our docs.

**Comment by kareemk** [comment]
adding paths to `LD_LIBRARY_PATH` doesn't work

**Comment by sjezewski** [comment]
Yea I remember you mentioning that when we were debugging this.

I believe you, but I don't see why that should be true. If we're going to recommend a change, first we should try and reproduce and understand why that is. We went to a considerable amount of effort to make this work in a way so that users don't have to copy drivers over. 

If that is required in this case for some reason, I'd like to understand why.

Our goal here was to make this easy for users. I'd like your use case to be handled just as easily.

**Comment by JoeyZwicker** [comment]
It sounds like this is more than a docs issue and actually that we need to do more testing with GPU resources and getting the drivers to work for various setups

**Comment by sjezewski** [comment]
I believe our recommended method of using GPUs has changed, so I'm calling this stale and closing the issue.
