### ISSUE TITLE
DatumInfo should contain list of constituent files

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2195]
`PPS.DatumInfo` should contain a `repeated PFS.FileInfo` field populated with the list of files that make up that datum to allow linking to the file in it's original Repo at the given commit that the job is using as input

**Comment by sjezewski** [comment]
I'm not sure if this was implemented or not. Do we still need this @gabrielgrant ?

**Comment by jdoliner** [comment]
It's implemented. Closing.
