### ISSUE TITLE
Connecting token to usage data

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2196]
We should start connecting tokens for the Enterprise product to mixpanel and usage stats. It would be incredibly helpful to know for various users/leads/trials how many pipelines, users, how much data, etc they have in their clusters. 

Things that need to be added to auth token backend:
- email verification
- warning email of expiration
- duplication checking

This would also help us with lead generation as we can more easily see which trial-period users are using the system more heavily.

**Comment by JoeyZwicker** [comment]
Some of these features are have GH issues in the dash repo as part of the 1.7 milestone. Until those are done, we can't really connect everything together as described here.

**Comment by JoeyZwicker** [comment]
Still relevant, just didn't make it into 1.7

**Comment by ysimonson** [comment]
I think @gabrielgrant was working on this in December, right?

**Comment by JoeyZwicker** [comment]
We've got most of the legal worked out and I'll let you know when it's all
a Go. Waiting on a few final approvals

**Comment by jdoliner** [comment]
The pachyderm part of this has been completed, metrics now report the enteprise token associated with the cluster, and we have dash issues for the other parts, so closing this.
