### ISSUE TITLE
Creating a pipeline with an invalid image leaves it stuck in "starting" forever

### ISSUE THREAD

**Issue by jtratner** [pachyderm/pachyderm#2214]
Right now, if you specify a non-existent or otherwise invalid image for a pipeline, it will always appear to be in "starting" via `inspect-pipeline`. 

Perhaps there could be some log output about invalid image or something? (or add something to the debugging docs to suggest using `kubectl` to debug)

To reproduce:

Given this badpipeline.json
```json
{
    "pipeline": {
        "name": "badpipeline"
    },
    "transform": {
        "cmd": ["/bin/bash", "-c", "echo 5"],
        "image": "reallybadreponamethatdoesnotexit:v1.25"
    },
    "input": {
        "atom": {
            "repo": "input",
            "glob": "/*/*"
        }
    }
}
```

run:

```
pachctl create-repo input
pachctl create-pipeline -f badpipeline.json
```

then running `pachctl inspect-pipeline badpipeline` will always show "starting"

If you inspect with `kubectl get all`, you do see that it's stuck in `ImagePullBackoff`:

```
›› kubectl get all | grep badpipeline
po/pipeline-badpipeline-v1-zq3pq   1/2       ImagePullBackOff   0          19s

rc/pipeline-badpipeline-v1   1         1         0         19s

svc/pipeline-badpipeline-v1   10.0.0.206   <none>        80/TCP                                      19s

```

**Comment by JoeyZwicker** [comment]
@jtratner Thanks for pointing that out. We can definitely improve the docs here for troubleshooting an invalid image. `kubectl describe po/<pod_name>` is a very useful way to debug things so we should make sure that's documented.

We can also look into punching through the error from k8s.

**Comment by JoeyZwicker** [comment]
We're also have a proposal to expose more meaningful info from kuberenetes directly into the job status for Pachyderm

**Comment by jdoliner** [comment]
We have more than a proposal actually, this is in code review right here: #2231
