### ISSUE TITLE
Include related info in AuthenticateResponse message

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2217]
Currently [the `AuthenticateResponse` message](https://github.com/pachyderm/pachyderm/blob/master/src/client/auth/auth.proto#L50) only contains a `pach_token` field. It would be useful if this also contained the expiry time, and whatever info about a user is returned from the github API (at least user name, maybe profile picture link, email address, etc)

**Comment by msteffen** [comment]
Fixed by https://github.com/pachyderm/pachyderm/pull/2259

**Comment by JoeyZwicker** [comment]
fixed via #2259
