### ISSUE TITLE
False flag reported

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#222]
The flag reported at the bottom of `pachctl help`

    Flags:
          --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)

is total nonsense. We're inheriting this somehow from kubernetes code ... some singleton is declaring some flag parsing or something.

**Comment by JonathanFraser** [comment]
Its declared as a global in the kubernetes code. This means that if we import that package or import a package which imports it that flag will show up.

**Comment by jdoliner** [comment]
Alright, easiest way to solve this then would be to not import kube packages for pachctl. The only reason we're doing it is so that we can use their API objects to create pachyderm manifests... but we could probably do that with a template or something.
