### ISSUE TITLE
InspectRepoResponse should contain fields of RepoInfo at the top level

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2228]
re: #2227

As discussed with @msteffen --  the way we've added this extra `Inspect`/`ListRepoResponse` wrapper layer around `RepoInfo`s has several problems. It:
- is a breaking change to the API
- makes it's structure inconsistent with our other API endpoints
- makes the message content/structure differ depending on whether the resource comes from a `List` vs `Inspect` (so response normalization code now has to know the source)
- makes the client responsible for knowing the distinction between fields stored directly to etcd (most of them) and fields only added to the wire message (auth), which isn't really a distinction it should have to care about

I understand that this was the path of least resistance to getting this shipped, but it seems that ideally the public API should have all the same top-level fields as before, and simply added a field for auth info. This isn't a huge deal in this one specific case, but I'm bringing this up, since we discussed using this as a model for other, future cases where we want to have different fields between what gets stored vs serialized.

In terms of how this is implemented, I think we all agree that manually copying over fields from one message type to another is annoying and error prone, so it seems like @jdoliner 's suggestion of having paired proto messages (one for storage, one for the wire) where most fields match in both name and index allowing the same message to be decoded as either would work well. We'd need to ensure that the field types match up, and that differing fields with the same index aren't added to each of the the two paired protos. It seems that a single automated test could check that any proto message defs following a particular naming convention (eg `Private*Info` and `Public*Info`) also have the same names and content-types for any field indexes that overlap.

This still requires manually adding any new field in both places if it is to appear in both etcd and the public API, but this:
- prevents accidentally storing or exposing info that isn't intended
- maintains a public API where info is all top-level (ie where the client isn't required to know details of how the response message was constructed)
- centralizes/minimizes the manual work needed to copy info between message types (just add field to both types)

It also might make sense to use this pattern in other places where we take similar, but slightly different, messages as input vs what is stored and output (eg `Create`/`UpdatePipeline` vs `InspectPipeline`)

**Comment by jdoliner** [comment]
This has been fixed in a slightly different way by including the fields in `RepoInfo` and returning that directly from `InspectRepo`.
