### ISSUE TITLE
pachctl auth activate demands an argument, but none is listed in usage info

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2229]
```
$ pachctl auth activate --admins=gabrielgrant
expected 1 arguments, got 0

Usage:
  pachctl auth activate --admins=[admins...] [flags]
```
I think this maybe used to take an enterprise activation code? Adding an activation code has now been moved to the `enterprise` service, though.

**Comment by msteffen** [comment]
Fixed by https://github.com/pachyderm/pachyderm/pull/2252
