### ISSUE TITLE
Expose datum paths as environment variables

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2232]
It's common for the first lines of a pachyderm pipeline to looks something like this:

```shell
for f in /pfs/input/*
do
    code.py $f
done
```

This boiler plate can be saved by instead exposing the datum's path as an environment variable whose name is the name of input it comes from. Then this could be written as:

```shell
code.py $input
```

**Comment by JoeyZwicker** [comment]
@jtratner We'd love your feedback on this issue to make sure it solving the problems we discussed.

**Comment by jtratner** [comment]
The fix in #2233 works for arbitrarily many data repos? (i.e., a different env var for each name?)

only issue here is you'd still need to use `stdin` because it's not giving you the subpath from the repo for the datum.

i.e., stdin becomes something like:

```
cmd: ["/bin/bash"]
stdin: ["code.py $input /pfs/out/${input##/.*/.*}"]
```

but yeah basically handles what I'm looking for - would it only work in `stdin`?

**Comment by jdoliner** [comment]
> The fix in #2233 works for arbitrarily many data repos? (i.e., a different env var for each name?)
yes, each env var will be the name given to the input, which defaults to the name of the repo if unspecified.

> only issue here is you'd still need to use stdin because it's not giving you the subpath from the repo for the datum.

`$input` will be the full path to the datum. For example if you have a repo `foo` with a file ` bar` in it and you use a glob pattern of `*` then `$foo` will be `/pfs/foo/bar`. The only time you should have to deal with subpaths is if your datums are actually directories which contain multiple files in which case you'll have to traverse those files. I'm not sure if there's a way we could make that use case better, we can't really bind them to env vars because we don't even know how many files there are so user code is always going to have to handle that variability.

**Comment by jdoliner** [comment]
Realized I didn't answer your last question, the env vars should work outside stdin too. So you can just as easily have your python code access them directly.

Also I'm not totally sure I answered your question 2nd question. When you pass `/pfs/out/${input##/.*/.*}` what is that communicating to your code?

**Comment by jtratner** [comment]
Often the transform I want to do is:

code.py --bam=/pfs/input/FlowcellA/Sample1/somefile.bam
--vcf=/pfs/input/FlowcellA/Sample1/something.vcf
/pfs/out/FlowcellA/Sample1/outputfile.txt

So my assumption is this would look like:

code.py --bam=$input/somefile.bam --vcf=$input/something.vcf
/pfs/out/${input#/.*/.*}

Where the goal is to strip out "/pfs/input" and put "/pfs/out" instead.

But def much cleaner

**Comment by thedrow** [comment]
Just noting that this isn't documented but should be. There's no other way of discovering the implementation of this feature other than exploration which some users won't do.

**Comment by JoeyZwicker** [comment]
Thanks @thedrow.

@dwhitena Let's add this to our docs queue.

**Comment by dwhitena** [comment]
Added @JoeyZwicker. Thanks.

**Comment by gabrielgrant** [comment]
Just noting that this does seem to now be documented here: https://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#environment-variables
