### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by srajpal1990** [pachyderm/pachyderm#2235]
in http://pachyderm.readthedocs.io/en/stable/fundamentals/incrementality.html the first example should be 
{
  "atom": {
    "repo": "R",
    "glob": "/*",
  }
}

not 

{
  "atom": {
    "repo": "R",
    "glob": "*",
  }
}

**Comment by JoeyZwicker** [comment]
Thanks @srajpal1990. Technically both are valid and correct, but I agree with you that `/*` is clearer
