### ISSUE TITLE
Proposal: Pachyderm stdlib

### ISSUE THREAD

**Issue by fortytw2** [pachyderm/pachyderm#2242]
Providing a standard library of generic, reusable containers to perform common operations inside pachyderm would be awesome. 

Examples:
- ingress containers (could be triggered via cron)
    - run this SQL on a database and write a file with the query results
    - poll a s3 bucket for new files and import them into PFS on a trigger
- egress containers
    - instead of expanding `egress:` capabilities, containers like `pachyderm/jdbc-egress` would allow writing out of pachyderm into hot stores / other databases
    - hit a configurable webhook etc
- generic transforms?
    - like pachyderm/jq or pachyderm/csvkit etc?
    - not really sure about this

Having this functionality be somewhat standardized would help greatly with maintainability of large pachyderm pipelines and with cross-team collaboration on shared pipelines. It would also provide a place to document common pachyderm functionality that many people would otherwise build bespoke solutions for. 

Thoughts/comments?

**Comment by JoeyZwicker** [comment]
Thanks for submitting this @fortytw2! Building a set a standard containers for common operations is definitely something we've talked about. We've implemented a few as part of other examples. We'll make sure to discuss this as part of our next release. 

You've already listed a few great examples of standard containers above, but if you have more, feel free to add them to this issue. 

Subscribing or emitting to a Kafka topic comes to mind.

**Comment by fortytw2** [comment]
I wonder how exactly subscribing to a Kafka topic / the output of other streaming systems could work within the restrictions of current pachyderm?  

We ( myself and @bpb ) are already working on some of these (for internal use, but to be open sourced), it could be really beneficial to coordinate our efforts so we don't build the same things twice or establish two separate "standards" for standardized operations. 

Also related to https://github.com/pachyderm/pachyderm/issues/657

**Comment by JoeyZwicker** [comment]
We'll be adding some of these examples over time. MongoDB w/ cron has been added and the SQL adapter is part of the 1.7 milestone. 

S3 sync commands are already commonly used, but perhaps a stdlib example of that may make this next release cycle as well. The rest will be on backlog for now, but we'll add them as we run into those use cases. 

@fortytw2 We'd love to see any of your connectors open sourced when they're ready

**Comment by gabrielgrant** [comment]
FWIW, rather than a single standard lib that we maintain, we probably (eventually) want to have some sort of index/ecosystem of contributed pipeline transforms

**Comment by nitinjainsj** [comment]
We have a tracking RFC for a feature that covers most of what is mentioned here.

https://github.com/pachyderm/rfcs/pull/6
