### ISSUE TITLE
Enterprise Deactivate API

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2246]
The Auth API [implements a `Deactivate` endpoint](https://github.com/pachyderm/pachyderm/blob/master/src/client/auth/auth.proto#L148). It would be useful for the Enterprise API to do the same (mostly for testing purposes -- right now I'm stopping my cluster, blowing away all state, and relaunching)

Before removing the activation code, this should probably check if Auth is activated and either deactivate it first, or refuse to run if it is activated.

It could also be useful to have a back-door way to set an expired token. Right now I'm just generating one that expires in a short period and waiting to test the expired-token code path

**Comment by msteffen** [comment]
Per our discussion:
(a)  I'll leave out the ability to remove the auth token completely for now, because you're investigating ways to do that with etcdctl
(b) The ability to make the enterprise token expire early already exists: just call Enterprise.Activate with ActivateRequest.expires set to some time in the past: https://github.com/pachyderm/pachyderm/blob/master/src/client/enterprise/enterprise.proto#L28

**Comment by msteffen** [comment]
For (b): the ability to set the expiration time existed in the API but not in pachctl. It has since been added: https://github.com/pachyderm/pachyderm/pull/2252

**Comment by gabrielgrant** [comment]
Removing the token with `etcdctl` doesn't seem to work:

The key gets removed from etcd
```
$ ETCDCTL_API=3 etcdctl --debug --endpoints=http://localhost:32379 del pachyderm_enterprise/token
1
$ ETCDCTL_API=3 etcdctl --debug --endpoints=http://localhost:32379 get pachyderm_enterprise/token
$
```
...but the API still returns the state as `ACTIVE`

@msteffen believes this may be because of a caching issue

**Comment by msteffen** [comment]
https://github.com/pachyderm/pachyderm/pull/2253 should allow the enterprise token to be unset using etcdctl

**Comment by msteffen** [comment]
I'm closing this issue because I don't have anything else I'm planning to do, but feel free to re-open if the current fixes aren't sufficient.

**Comment by gabrielgrant** [comment]
Nope, between deactivating by setting an old timestamp and deleting with etcd, I think that solves my use cases. Thanks!
