### ISSUE TITLE
Enterprise API should return decoded token

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2247]
Right now I'm still having to decode a submitted token myself in the browser to show the user the time at which the token expires, and when a user has an expired token, there is no way to show at what time that token expired

The token also contains a `scopes` field. While not used at the moment, the intention is that in the future contain info about which features are activated.

So at a minimum, the API should return the expiry time, and should possibly just return the whole token (though this could wait until we have a more clear idea of how scopes will be used)

**Comment by msteffen** [comment]
Per our discussion, both Activate and GetState will return a TokenInfo object that includes the token expiration time (as a boxed submessage). If no token has been provided, the submessage will be unset

**Comment by msteffen** [comment]
This is fixed by https://github.com/pachyderm/pachyderm/pull/2259
