### ISSUE TITLE
Unclear documentiation for setting up on Azure

### ISSUE THREAD

**Issue by jonalm** [pachyderm/pachyderm#2254]
I am trying to set up Pachyderm on Azure, but I get confused halfway down the documentation page http://docs.pachyderm.io/en/latest/deployment/azure.html under "Set up the Storage Resources"

Halfway down the page there is a code block:
```
$ make docker-build-microsoft-vhd 
$ VOLUME_URI="$(docker run -it microsoft_vhd \
                "${STORAGE_ACCOUNT}" \
                "${STORAGE_KEY}" \
                "${CONTAINER_NAME}" \
                "${STORAGE_NAME}" \
                "${STORAGE_SIZE}G"
             )"
```

Should the first line be commented out? Or is it a `make` command? Do I need a `docker-build-microsoft-vhd` file from somewhere?

Running the above gives,

```
make: *** No rule to make target `docker-build-microsoft-vhd'.  Stop.
Unable to find image 'microsoft_vhd:latest' locally
docker: Error response from daemon: pull access denied for microsoft_vhd, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

Is this `microsoft_vhd` repository outdated?

In any case, I guess the documentation should be clarified.

**Comment by dwhitena** [comment]
Thanks for bringing this to our attention @jonalm.  Were you running the `make docker-build-microsoft-vhd` from the root of the pachyderm repo?  Mine executes when running it there.  

(also, I'm going to be scrubbing the deploy docs with some updates soon so I will take this into account then as well)

**Comment by JoeyZwicker** [comment]
Hi @jonalm. Sorry you're hitting this problem and thanks for pointing it out! We can definitely make the docs clearer. The make target you're looking for is the makefile in the root of our Pachyderm repo. 

https://github.com/pachyderm/pachyderm/blob/master/Makefile

**Comment by JoeyZwicker** [comment]
Jinx @dwhitena

**Comment by dwhitena** [comment]
Also, added here so we don't forget to address any issues for 1.6: https://github.com/pachyderm/pachyderm/issues/2224

**Comment by JoeyZwicker** [comment]
@dwhitena This just requires adding "clone the pachyderm repo" as part of the azure deploy docs, right?

Probably worth mentioning since that's not a requirement for either of the other cloud deploys.

**Comment by jpoon** [comment]
We can make things easier by adding support for managed disks (ref: https://github.com/pachyderm/pachyderm/issues/2136). The work to do so is fairly trivial.

Another option is to push that particular image to DockerHub instead of asking folks to build it on their machines?

**Comment by jdoliner** [comment]
We could push that image, although I was under the impression you didn't actually need it anymore because k8s could auto provision drives.

**Comment by jpoon** [comment]
The azure instructions are specifying `static-etcd-volume` argument for pachctl deploy. We can simplify the instructions there to use the new CLI commands.

I noticed there's a new `dynamic-etcd-nodes` flag. How are these disks provisioned? If it's through storage class/pv/pvc's, it should just work on Azure.

**Comment by dwhitena** [comment]
@jpoon @jdoliner Thanks for the comments. My understanding was that provisioning the volumes on Azure wasn't as straightforward and, thus, we could yet use dynamic volumes. However, my info may be out of date.

**Comment by jpoon** [comment]
If you deploy a cluster through AKS, you get storage classes by default:

```
$ kubectl get storageclass
NAME                PROVISIONER
default (default)   kubernetes.io/azure-disk
managed-premium     kubernetes.io/azure-disk
managed-standard    kubernetes.io/azure-disk
```

and so if you deploy with the `--dynamic-etcd-nodes` it'll just work.

```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                         STORAGECLASS   REASON    AGE
pvc-29de5018-c19c-11e7-9204-000d3a14317b   10Gi       RWO            Delete           Bound     default/etcd-storage-etcd-1   default                  1d
pvc-4d89bfdd-c19e-11e7-9204-000d3a14317b   10Gi       RWO            Delete           Bound     default/etcd-storage-etcd-2   default                  1d
pvc-ebb25a97-c19b-11e7-9204-000d3a14317b   10Gi       RWO            Delete           Bound     default/etcd-storage-etcd-0   default                  1d

```
