### ISSUE TITLE
Interoperability with existing code/systems

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#226]
We discussed this offline today and I'm just capturing the discussion here.  @JoeyZwicker @jdoliner @sjezewski please correct me if I'm missing anything.

So sounds like there are two problems:
1. Some users have existing code and systems that expect to talk to a certain API, which usually is the S3 API.  We want to make it easy for these users to transition to using Pachyderm.  One idea was to implement a S3 API on top of pfs.
2. Some users want to use their data in multiple systems.  For instance, a user who uses pps for analytics might also want to use Postgres for quick queries.  So we want to make it easy to pump data from pfs into these external systems.  One idea was to have a pipeline for each of these external systems.  The pipeline would simply listen for new commits and pump new data into the external system whenever a commit comes in.

**Comment by sjezewski** [comment]
The first one is now represented by this issue: https://github.com/pachyderm/pachyderm/issues/257

The second one is described in several issues that are talking about egress pipelines / services / persistent services.
