### ISSUE TITLE
aws.sh zsh support

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2264]
There seem to be some gotchas w the script in zsh

```sudo -E ./aws.sh
+ WHEEL='-\|/'
+ '[' 0 -ne 0 ']'
./aws.sh: line 273: @: unbound variable
```

**Comment by sjezewski** [comment]
I changed my mind about this. I don't think we want to support any shells. Bash is fine. Let's just update the docs to make this clear.

**Comment by JoeyZwicker** [comment]
This just needs to be documented in the aws.sh script and/or the awe deploy docs?

**Comment by sjezewski** [comment]
Just the deploy docs. We don't know all the ways it might err in different shells, so its best just to say that we expect bash.

**Comment by sjezewski** [comment]
stale
