### ISSUE TITLE
Auth status API (or consistent way to determine if auth is enabled)

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2275]
There are a number of places throughout the UI where I'd like to know if auth is enabled. For some of these, i can just check if the user is logged in, but for others, I need to know if auth is enabled regardless of login status (eg: what to show on the login screen if auth is disabled)

I think the most straightforward would be to have an auth status API method, but failing that, having a single, definitive answer from some other endpoint return this info would suffice

**Comment by msteffen** [comment]
Per our discussion: Auth.WhoAmI (https://github.com/pachyderm/pachyderm/blob/master/src/client/auth/auth.proto#L157) should work. It'll tell you:
* if auth isn't activated (`"the auth service is not activated"`)
* if you're not logged in (`"auth token not found in context"`)
* if your login has expired (`"token not found"`)
* who you are, if auth is active and your authentication token is valid
