### ISSUE TITLE
pachctl logout

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2277]
particularly useful for testing

**Comment by gabrielgrant** [comment]
this should both be implemented in pachctl (delete whatever file is persisting the pach token locally) and in pachd (end the client's "session" by deleting the etcd entry for the client's current pach-token in the auth token list)

**Comment by msteffen** [comment]
The pachctl portion of this is fixed by https://github.com/pachyderm/pachyderm/pull/2283

**Comment by sjezewski** [comment]
I'm not sure what the second half means. @gabrielgrant do you mean you want to remove the enterprise token?

**Comment by JoeyZwicker** [comment]
ping @gabrielgrant 

Closing for now, reopen if there us more we need here
