### ISSUE TITLE
Tag/Group Pipelines and repos

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2297]
Once you deploy a bunch of pipelines and have a bunch of input repositories, it can be overwhelming to search through them all (via API, dashboard, or otherwise) for information, or to make updates.

@gabrielgrant and certain users have brought up the idea of tagging or grouping pipelines.  In this way, you could filter for groups of pipelines/repos that you are interested in, and possible make changes group by group.

**Comment by bpb** [comment]
My initial inclination would be to make this a simple pipeline spec field called group tags where you pass an array of strings.  The group tag would let you mark repos and pipelines as belong to a set of possibly overlapping groups.

Then when you run  `pachctl list-repo <group_name>` and `pachctl list-pipeline <group_name>` pachctl would return results filtered on <group_name>.

**Comment by sjezewski** [comment]
As we start to have more usage by bigger teams, we'll probably see more requests for namespacing repos / pipelines as well as defining teams that have access to specific groups.

But for now, we haven't seen explicit requests for this, so I'm marking this as stale
