### ISSUE TITLE
Add watchdog to CI tests to fail quickly if there's a panic

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2301]
Tests will timeout if pachd or a pipeline worker has a segfault. It's unclear when the CI times out this is what's happening, and we lose a bunch of time debugging this.

We could have a long running test that just watches the k8s cluster and looks for restarts, and maybe even checks / prints logs of the stacktrace if there was a panic. That would make CI actually fail quickly and in a way that is helpful.

**Comment by JoeyZwicker** [comment]
@sjezewski is this still relevant? I'm removing from 1.7 milestone, but add it back in if you think its a priority.

**Comment by sjezewski** [comment]
stale
