### ISSUE TITLE
Access AWS resources without static tokens

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2307]
From a user in Slack:

> We have a need/policy to not access aws resources via static tokens. However, it seems, based on the docs and the conversations here, that static tokens are required to operate pachyderm.
> 
> However, it seems like this would be an easy thing to change. Could we not throw an if statement here https://github.com/pachyderm/pachyderm/blob/25cf25053c89db92269ec3614b0c8a9fd49c792f/src/server/pkg/obj/amazon_client.go#L35
> that basically says that if the AccessKey and AccessSecret are the empty string then don't set a credentials provider? The aws libraries will query the metadata service and gather the iam credentials associated with the ec2 node if no provider is given.

**Comment by sjezewski** [comment]
Hmmm I'm not super familiar w the aws metadata services. I'm not sure if/how that plays nice with containers. If running any AWS api tools on a 'raw' ec2 instance Does The Right Thing by querying the metadata API, we could probably figure out how to make this work on containers ... but we may need to poke the right things through from the host to the container.

We'll have to look into this.

**Comment by dcjohnson** [comment]
It works fine while running on containers. I have used iam ec2 roles while running in kubernetes and, as an example, you can exec into a pod and run 
```
curl http://169.254.169.254/latest/meta-data/instance-id/
```
which will return the instance-id of the node the pod is running on.

**Comment by derekchiang** [comment]
Upon some research I think what @dcjohnson said is correct.  Although according to [this doc](http://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/iam-roles.html), it's more involved than simply leaving the credentials blank; you'd also have to annotate the pod in a certain way.  Anyways, sounds like it's doable and I will see if I can get it working.

**Comment by sjezewski** [comment]
Ah, good to know.

In this case, it's really just a matter of specifying a different deployment option for aws. That's pretty easy for us to support.
