### ISSUE TITLE
Document - internal registry usage

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2319]
We should allow users to specify an internal registry for pachd and other Pachyderm required images. Right now the list includes:
- pachd
- worker
- dash
- etcd
- grpc-proxy
- ubuntu (default if `image` isn't specified in a pipeline spec)
- pause (required by k8s)

Overall, we should figure out how to make it easier for on-prem/fire-walled users to get the required images for deployment. Right now it's a major barrier.

**Comment by JoeyZwicker** [comment]
Fixed via #2360 

@jdoliner @dwhitena I'm changing this to a docs issue because we need to document the private registry enterprise usage. This documentation should also provide the list of images (above) that are required and how to get/build them.

**Comment by gabrielgrant** [comment]
kk, just been digging into this a bit

The first step is obviously getting all the images into the private registry. At the moment it seems like this can only be done manually (by getting the most recent version of each of the images listed above). At some point it looks like we had [`list-images`, `export-images`, and `import-images` commands that would assist with this process](https://github.com/pachyderm/pachyderm/pull/2360/files#diff-f19021ab9e693271df9c30e406651630R320), but they appear to have been removed 

Once the images are in the registry, it should just be a matter of adding the `--registry http://your-registry.com` flag to `pachctl deploy`

What that does behind the scenes is
- generate the initial deploy manifest to pull all the images from the right places
- Add a `WORKER_SIDECAR_IMAGE` env var to the pachd deployment so it knows to generate pipeline RCs that pull the sidecar and worker (init container) image from the right registry (added [here](https://github.com/pachyderm/pachyderm/pull/2360/files#diff-585657c092bbb9545c0bd9302d395fffR345))

**Comment by mindthevirt** [comment]
Closing this since we support imagePullSecrets as part of the helm chart, which allows a user to pull images from a private registry.
