### ISSUE TITLE
Pachyderm S3 egress creates unreadable files when used with cross-account IAM

### ISSUE THREAD

**Issue by emk** [pachyderm/pachyderm#2327]
The error and fix are [described here](https://stackoverflow.com/questions/33236192/amazon-s3-file-access-denied-exception-in-cross-account).

This is probably a pretty easy fix: Pachyderm should set the ACL to `bucket-owner-full-control` when performing S3 egress. This will presumable also be necessary when using IAM instance roles across AWS accounts, too.

**Comment by dwhitena** [comment]
Thanks for reporting this @emk. @derekchiang thoughts?

**Comment by derekchiang** [comment]
@emk That seems to make sense.  Should be easy for us to do as well.  I will take a crack at it and hopefully it will make it into the next release.

**Comment by derekchiang** [comment]
Fixed in #2328.
