### ISSUE TITLE
Remove `Perm` and `Offset` from the protocol

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#233]
`Perm` is a field in `pfs.FileInfo` and `OffsetBytes` is a field in `pfs.PutFileRequest`.  As far as I can tell neither of them is actually being used in any meaningful way.  Specifically `OffsetBytes` doesn't make sense because our files are append-only.

Creating a `technical-debt` label for issues like this.

**Comment by jdoliner** [comment]
Scheduling this for v1.0, it should be pretty easy and will be nice to get in for API consistency.
