### ISSUE TITLE
RBAC cluster role binding

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2331]
From the users channel as discussed with @sjezewski:

> Hey guys any word on the RBAC cluster role binding issue we mentioned a while back. Currently when we deploy pachyderm in our Tectonic cluster we have to create a special ClusterRoleBinding for pachd to give it permission to let it use cluster resources unfortunately pachd does not pass these roles down to the workers and so the workers then can't use resources. We have a work around but its not ideal. We grant everyone in the namespace that pachd is in full admin permissions.

**Comment by jdoliner** [comment]
Is this just as easy as having worker pods use the same service account as the pachd pod? Or is there something more to it?

**Comment by bpb** [comment]
I think that should effectively solve it. 
A colleague of mine effectively believed the following fork would solve it
https://github.com/pachyderm/pachyderm/compare/master...fortytw2:master
But this effectively set up a separate role for workers. Passing the same service account should do the trick. 

We never actually deployed his fork.

**Comment by jdoliner** [comment]
Fixed by #2605.
