### ISSUE TITLE
Calling `put-file` with no dest path specified doesn't error, but commit fails 

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2337]
Calling put-file with no destination path specified seems to work, but when trying to finish the commit, gives `Error: could not put file at ""; a node of type directory is already there`

There doesn't seem to be any obvious way to recover from this error

The error should probably occur when a put-file request is sent without the required params

**Comment by JoeyZwicker** [comment]
>put-file with no destination path

can you clarify this? I can't seem to repro via pachctl

**Comment by sjezewski** [comment]
I just had a user run into the same thing. I believe we were trying to put file from an s3 url to a path `/`, but I don't quite recall

**Comment by jdoliner** [comment]
I can't find a way to repro this, putting a file without a name gives: `path () invalid: only printable ASCII characters allowed` and doesn't get you into a bad state.
