### ISSUE TITLE
Installing pachyderm stack on non-standard hardware

### ISSUE THREAD

**Issue by konstunn** [pachyderm/pachyderm#2339]
I'm interested in how one can install pachyderm stack on hardware with non-standard architecture, for instance, i686 with hardware virtualization support and x86_64 without hardware virtualization support?

**Comment by JoeyZwicker** [comment]
Hi @konstunn. We don't officially support those architectures, but you can check out the make file in our repo, `make docker build` in particular should get you started. If you'd like to give it a try and let us know what works or fails, we'd love to see the results.

**Comment by konstunn** [comment]
I've already managed to build and run docker on i686 Debian (though the cpu supports long mode, so its architecture is x86_64, but crossgrading the system from i686 to x86_64 is not an option right now). I've successfully run hello-world container. So it seems to work, right? Unfortunately, I can not reproduce all the build steps right now. What I failed to do so far is to build a debian package so that I could track and manage the installation in my system with a package manager.

I hope that, as long as I have docker set up (though, manually) and running, things will get simpler to build all the remaining things inside docker. What do you suggest?

**Comment by JoeyZwicker** [comment]
Yeah that should work. Once you have docker set up, you should be able to
run Kubernetes and Pachyderm within Docker and get everything deployed.

**Comment by JoeyZwicker** [comment]
@konstunn any luck getting this to work?

I'm going to close the issue since it's not something we're officially supporting right now, but we'd love to hear about any progress you've made
