### ISSUE TITLE
Error on put-file from S3, with Pachyderm in AWS

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2340]
From a user: 

> Hi all, I was wondering how the s3 uri in created when we are copying files from S3 to pachyderm using `put-file`. When I am try to copy a single file I get the following error
> ```InvalidEndpointURL: invalid endpoint uri
> caused by: parse https://s3.eu-west-1
> .amazonaws.com/{Bucket}/{Key+}: invalid character "\n" in host name
> ```
> It seems that somehow an `\n` has been added to the URI. It’s worth to notice that when I try to copy a directory with the `-r` flag I don’t see this error, but I don’t see any data being copied as well.
> 
>  ```COMPONENT           VERSION
> pachctl             1.6.0-RC2
> pachd               1.6.0-RC2
> ```
> 
> Here is the command that throws the exception `pachctl put-file test-repo master -c -f s3://bucket/dir1/dir2/file.csv`
> 
> And this one does nothing `pachctl put-file test-repo master -c -r -f s3://bucket/dir1/dir2/`

Apparently for either case, the put-file doesn't work (i.e., the data doesn't end up in the repository).

**Comment by gabrielgrant** [comment]
See error details in pachyderm/dash#10

**Comment by sarovios** [comment]
@gabrielgrant The link is not working.

**Comment by gabrielgrant** [comment]
Ah, yea, sorry, that's a private repo, so only members of the org will be able to see it. Here's what @dwhitena wrote:

So, I tried the following from an object store URL (s3://):
   1. Uploading a directory recursively, and
   2. Uploading a single file

And the results are:

1. The recursive upload succeeded w/out error in the dashboard, but the data is no where to be found:

```➜  opencv git:(master) ✗ pachctl list-file test2 master
NAME                TYPE                SIZE
➜  opencv git:(master) ✗ pachctl list-commit test2
REPO                ID                                 PARENT              STARTED             DURATION             SIZE
test2               ccd3205e1d934cbba4ce7b6f93624fad   <none>              31 seconds ago      Less than a second   0B
➜  opencv git:(master) ✗ pachctl list-file test2 ccd3205e1d934cbba4ce7b6f93624fad
NAME                TYPE                SIZE
```

2. This actually gave me an error related to a new line character. I think someone else reported this right?  Anyway all the related logs are here:

```$ kubectl logs po/pachd-1036467475-m9bs8 | grep "s3://"
2017-09-28T21:37:31Z INFO pfs.API.PutFile {"request":{"file":{"commit":{"repo":{"name":"test2"},"id":"ccd3205e1d934cbba4ce7b6f93624fad"},"path":"blah"},"url":"s3://object-detection-model","recursive":true}}
2017-09-28T21:37:31Z INFO pfs.API.PutFile {"duration":0.000436399,"request":{"file":{"commit":{"repo":{"name":"test2"},"id":"ccd3205e1d934cbba4ce7b6f93624fad"},"path":"blah"},"url":"s3://object-detection-model","recursive":true}}
2017-09-28T21:39:38Z INFO pfs.API.PutFile {"request":{"file":{"commit":{"repo":{"name":"test2"},"id":"2ce91cb7ff6a4aebbf945815a0496c55"},"path":"airplane.jpg"},"url":"s3://object-detection-model/blah/airplane2.jpg"}}
2017-09-28T21:39:38Z ERROR pfs.API.PutFile {"duration":0.000994404,"error":"InvalidEndpointURL: invalid endpoint uri\ncaused by: parse https://s3.us-west-2\n.amazonaws.com/{Bucket}/{Key+}: invalid character \"\\n\" in host name","request":{"file":{"commit":{"repo":{"name":"test2"},"id":"2ce91cb7ff6a4aebbf945815a0496c55"},"path":"airplane.jpg"},"url":"s3://object-detection-model/blah/airplane2.jpg"}}```

**Comment by sarovios** [comment]
Any updates/workaround on that?

**Comment by gabrielgrant** [comment]
This code is being touched in #2365 but not sure if it addresses this specific issue. @derekchiang ?

**Comment by dwhitena** [comment]
@jdoliner @derekchiang @gabrielgrant just a little update and details here to help reproduce this:

# Reproduce with minikube

## Environment

```
$ minikube version
minikube version: v0.22.2
$ pachctl version
COMPONENT           VERSION
pachctl             1.6.0rc8
pachd               1.6.0rc8
```

## Start minikube

```
$ minikube start
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
```

## Create the `amazon-secret`

Create a base64 encoded secret file with the id, secret, token, and region (us-west-2 in this case).

```
$ cat secret.json
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "amazon-secret"
  },
  "data": {
    "id": "<my encoded id>",
    "secret": "<my encoded secret>",
    "token": "",
    "region": "dXMtd2VzdC0yCg=="
  }
}
```

Add the secret to k8s:

```
$ kubectl create -f secret.json
secret "amazon-secret" created
```

## Create a Pachyderm local manifest w/ the secret

Run deploy with `--dry-run` to get a local manifest:

```
$ pachctl deploy local --dashboard --dry-run > manifest2.json
```

Update the manifest so as to attached the `amazon-secret` to `pachd`:

https://gist.github.com/dwhitena/2ef09c264dd133516c954f8fd940a751

## Deploy Pachyderm

```
$ kubectl create -f manifest2.json
serviceaccount "pachyderm" created
deployment "etcd" created
service "etcd" created
service "pachd" created
deployment "pachd" created
service "dash" created
deployment "dash" created
```

And confirm that things are up and running:

```
kubectl get all
NAME                        READY     STATUS    RESTARTS   AGE
po/dash-1752167053-xgzmz    2/2       Running   0          23m
po/etcd-2142892294-p0299    1/1       Running   0          23m
po/pachd-1887717747-7cnjm   1/1       Running   0          23m

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)                                     AGE
svc/dash         10.0.0.95    <nodes>       8080:30080/TCP,8081:30081/TCP               23m
svc/etcd         10.0.0.132   <nodes>       2379:32379/TCP                              23m
svc/kubernetes   10.0.0.1     <none>        443/TCP                                     31m
svc/pachd        10.0.0.187   <nodes>       650:30650/TCP,651:30651/TCP,652:30652/TCP   23m

NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/dash    1         1         1            1           23m
deploy/etcd    1         1         1            1           23m
deploy/pachd   1         1         1            1           23m

NAME                  DESIRED   CURRENT   READY     AGE
rs/dash-1752167053    1         1         1         23m
rs/etcd-2142892294    1         1         1         23m
rs/pachd-1887717747   1         1         1         23m
```

## Try putting a file from S3

```
$ pachctl put-file test master -c -f s3://object-detection-model/ssd_mobilenet_v1_coco_11_06_2017.tar.gz
InvalidEndpointURL: invalid endpoint uri
caused by: parse https://s3.us-west-2
.amazonaws.com/{Bucket}/{Key+}: invalid character "\n" in host name
```

**Note** - I have confirmed that the base64 encoded region does not have a new line character at the end.

# Reproduce on AWS

I tried both the one shot script and manual deploy, and I had unrelated errors with both of the deploys (outside of this S3 issue).  The one shot error is a bug documented here: https://github.com/pachyderm/pachyderm/issues/2372, and the error I got on the manual deploy was DNS related (i.e., not related to Pachyderm).  I will try again later, but we definitely need to update the docs for the one shot script or fix that problem.

**Comment by dwhitena** [comment]
Ok, thanks to @sjezewski got the AWS deploy issues resolved and tried to reproduce the issue in AWS.  The S3 put-file works as long as it's a bucket in the same region as the cluster. This leads me to believe that it is something about the way I created the secret above. 

That being said, the user that reported this wasn't using minikube.  They were in AWS, so maybe a recent change fixed this.  @sav are you able to check this with the latest RC and/or with 1.6.0 when it is released? 

# Fail to reproduce in AWS

## Deploy Pachyderm in AWS

I used a slightly modified version of the one shot script (to fix issue from https://github.com/pachyderm/pachyderm/issues/2372), and ended up with the following cluster:

```
$ pachctl version
COMPONENT           VERSION
pachctl             1.6.0rc8
pachd               1.6.0rc8
$ kubectl get all
NAME                        READY     STATUS    RESTARTS   AGE
po/etcd-0                   1/1       Running   0          3m
po/etcd-1                   1/1       Running   0          3m
po/etcd-2                   1/1       Running   0          3m
po/pachd-1695804715-bpkcg   1/1       Running   0          3m

NAME                CLUSTER-IP      EXTERNAL-IP   PORT(S)                                     AGE
svc/etcd            100.65.29.90    <nodes>       2379:31168/TCP                              3m
svc/etcd-headless   None            <none>        2380/TCP                                    3m
svc/kubernetes      100.64.0.1      <none>        443/TCP                                     6m
svc/pachd           100.69.17.189   <nodes>       650:30650/TCP,651:30651/TCP,652:30652/TCP   3m

NAME                DESIRED   CURRENT   AGE
statefulsets/etcd   3         3         3m

NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/pachd   1         1         1            1           3m

NAME                  DESIRED   CURRENT   READY     AGE
rs/pachd-1695804715   1         1         1         3m
```

## Try putting a file from S3

```
$ pachctl put-file test master -c -f s3://newlinetest2/airplanes.jpg
$ pachctl list-file test master
NAME                TYPE                SIZE
airplanes.jpg       file                38.72KiB
```

**Comment by sarovios** [comment]
@dwhitena I am not sure if that's relevant, but I have a custom deployment using minio as object store. I am not deploying pachyderm to aws.

**Comment by dwhitena** [comment]
@sarovios Gotcha, well this should be fixed in the newest 1.6 release.  Basically, in these cases you need to create the `amazon-secret` manually if you want to connect to S3, and doing it the way that k8s recommends results in new line characters in the secret.  Now we tolerate and deal with those characters.

**Comment by sarovios** [comment]
@dwhitena Which is the newest release? I am using 1.6.0rc7 at the moment and I encounter this issue.

**Comment by dwhitena** [comment]
@sarovios The latest is v1.6.0, which will be officially released later this morning.  It should be fixed in that release.
