### ISSUE TITLE
Auth usernames should be case insensitive

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2346]
Got into this situation re #2345. GH user names are case insensitive so Pachyderm auth usernames should probably be too. This is not strictly required for us to do if #2345 gets fixed.

It could create a moonshot security whole if with integrate with an auth system that is case sensitive so may need to revisit later.

**Comment by sjezewski** [comment]
#2345 was closed ... so I think we're good? But unclear if the fix also checks case sensitivity (e.g. if validating the user exists against GH will also serve to invalidate spellings of usernames w the wrong cases)

Can you weigh in here @msteffen ?

**Comment by JoeyZwicker** [comment]
ping @msteffen

**Comment by sjezewski** [comment]
stale
