### ISSUE TITLE
put-file/PutFile should (optionally?) indicate progress

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2359]
it would be useful to be able to show a progress indicator on files being ingressed into pach

for uploads this can probably be done more easily from the client, but when pach is fetching a file itself, it would be nice if status messages were streamed back (by making PFS.PutFile() into a bi-directional streaming request, instead of just using a client stream)

**Comment by sjezewski** [comment]
This has come up many times w customers.

**Comment by gabrielgrant** [comment]
I believe @derekchiang was working on this somewhat recently. Did that go anywhere?

**Comment by gabrielgrant** [comment]
Looks like work i was thinking of may be in #2293, which doesn't seem to include anything about progress reporting

**Comment by ysimonson** [comment]
Dupe of #1589
