### ISSUE TITLE
Service docs need more detail re:data updates

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2362]
The [doc says](http://docs.pachyderm.io/en/v1.6.0rc6/fundamentals/creating_services.html) a service has "always got the most up-to-date version of your data exposed to it", but doesn't explain how that works -- is the process killed and relaunched in a new pod when a new commit comes in? Does new data just appear while the process is running? Is the existing process restarted within the same pod when new data arrives?

**Comment by dwhitena** [comment]
@gabrielgrant I didn't know we had service docs. haha. I will look into this.

**Comment by jdoliner** [comment]
The process is killed and relaunched, but in the same pod. This happens pretty quickly because the data gets downloaded in the background. And then swapped out via bind mount.

**Comment by gabrielgrant** [comment]
do you know if the process is sent a SIGKILL or a SIGINT? (Wondering if there's a chance to do a graceful shutdown)

**Comment by jdoliner** [comment]
This is the function we use: https://golang.org/pkg/os/exec/#CommandContext

which claims to send a `SIGKILL` so no opportunity to do graceful shutdown unfortunately, we could probably find a way to add that. I'm not sure how much flexibility the go library gives us though.
