### ISSUE TITLE
Local deployment fails at "kubectl create -f"

### ISSUE THREAD

**Issue by uzdry** [pachyderm/pachyderm#2364]
So, I have now tried this with two PCs, both with Ubuntu 16.04.03
Here some more version Information:
pachctl             1.6.0rc8            
minikube version: v0.22.2
kubectl: 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

So, every time I try to `pachctl deploy local` i get this:
```
error: error validating "STDIN": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ServiceAccount"}; if you choose to ignore these errors, turn validation off with --validate=false

Pachyderm is launching. Check it's status with "kubectl get all"

kubectl create -f -: exit status 1
error: error validating "STDIN": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ServiceAccount"}; if you choose to ignore these errors, turn validation off with --validate=false
```

And after that `kubectl get all` says this: `No resources found.`

I have neither found something through google magic nor in the existing issues. If I missed an issue i am sorry.

**Comment by JoeyZwicker** [comment]
Hi @uzdry, I'm really sorry you're hitting this. I'm wasn't able to reproduce this on my own just now, but we'll take a closer tomorrow and figure this out for you. 

Did you try setting the `--validate=false` flag?

@jdoliner @dwhitena any chance you're able to repro on your setup?

**Comment by uzdry** [comment]
Well, pachctl itself does not have that flag and I do not know how to pass a flag from pachctl to kubectl.

**Comment by JoeyZwicker** [comment]
Ah my apologies. You can do `pachctl deploy local --dry-run` and we'll print out the kubernetes manifest. Save it as then pass it to `kubectl create -f` with the flag.

**Comment by jdoliner** [comment]
I'm guessing that kube 1.8 is the issue here. Something must have changed about the schema that we're running afoul of. Given that your server is still 1.7 I suspect that turning of validation may well work.

**Comment by refrigerator** [comment]
I'm also having this issue. I tried what you suggested @JoeyZwicker - I saved the `--dry-run` output and ran `kubectl create -f ./pachyderm-manifest.json --validate=false` but am getting these errors:

```
unable to recognize "./pachyderm-manifest.json": no matches for /, Kind=ServiceAccount
unable to recognize "./pachyderm-manifest.json": no matches for extensions/, Kind=Deployment
unable to recognize "./pachyderm-manifest.json": no matches for /, Kind=Service
unable to recognize "./pachyderm-manifest.json": no matches for /, Kind=Service
unable to recognize "./pachyderm-manifest.json": no matches for extensions/, Kind=Deployment
```

any ideas?

**Comment by refrigerator** [comment]
Solved it - I didn't have `minikube` up and running - running `minikube start` before trying the pachyderm commands worked :) Perhaps we can make this a bit clearer in the docs?

**Comment by uzdry** [comment]
I now also saved the `--dry-run`.
With minikube up and running following worked:
`kubectl create -f ./pachyderm-manifest.json --validate=false`

But @refrigerator, I think it was clear enough.

**Comment by jdoliner** [comment]
It seems that this is actually an issue with kuberentes: https://github.com/kubernetes/kubernetes/issues/53309 the best we can do for a fix on our end is setting `--validate=false` by default until this gets resolved in k8s.

**Comment by gauti038** [comment]
I am currently running client v1.8 and server is also at 1.8+.
Even when I run this with the validate=false flag, I am still seeing the error 
`error: unable to recognize "dc2.yaml": no matches for /, Kind=Deployment`
Can you please let me know how can I proceed?

**Comment by dwhitena** [comment]
@jdoliner any update here or thoughts for @gauti038?

**Comment by jdoliner** [comment]
@gauti038 are you able to create a simple non-pachyderm deployment like the one here?
 https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
