### ISSUE TITLE
Handle directories correctly

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#237]
Currently, operations such as `PutFile foo/bar` followed by `PutFile foo` or vice versa are allowed, resulting in pfs being in an inconsistent state.

Upon offline discussion with @jdoliner, here are the things we need to implement to correctly handle directories:

* `PutFile foo/bar` should fire **two concurrent requests** (in general, a path with `n` parts will result in `n` concurrent requests):
    * Send the blocks to the shard for `foo/bar`, and in that shard create an `Append` that records the fact that `foo` has a children that is `bar`.
    * Send a request to the shard for `foo`.  The shard will check if `foo` already exists.  If it exists and is a file, we return an error.  If it exists and is a directory, we do nothing.  If it doesn't exist, we create an `Append` for `foo` with no `children`.  This `Append` simply serves to record the fact that `foo` has been created and is a directory.

* `InspectFile foo` (and by extension `ListFile foo`) should fire a request to the shard for `foo`.  One of the following will happen:
    1. `foo` is a file, so the shard simply returns the `FileInfo` for `foo`.
    2. `foo` is a directory, so we now **multicast `InspectFile foo` to the entire cluster**, and then aggregate the responses to generate a complete `FileInfo`.
    3. `foo` is not found so we return a `FileNotFound` error.

* `GetFile foo` should fire a request to the shard for `foo`.  One of the following will happen:
    1. `foo` is a file, so the shard simply returns the `FileInfo` for `foo`.
    2. `foo` is a directory, so we return an error.
    3. `foo` doesn't exist, so we return an error.

* `DeleteFile foo` should fire a request to the shard for `foo`.  One of the following will happen:
    1. `foo` is a file, so we simply append a tombstone.  We also create an `Append` for the parent of `foo` with `removedChildren` set to `foo`, to record the fact that `foo` is no longer a child of its parent (in this case the root directory `.`).
    2. `foo` is a directory.  The shard for `foo` should now create a tombstone for `foo`.   We then **multicast `DeleteFile foo` to the entire cluster**.  Each shard will go through **the entire commit history** (??) and put a tombstone for each file or directory that are under `foo` (including files like `foo/bar/buzz`).
    3. `foo` doesn't exist, so we return an error.

@jdoliner please take a look when you have time.  I've highlighted the parts that have performance implications.

**Comment by jdoliner** [comment]
This looks almost completely correct to me.

A few small points: 

GetFile doesn't return a FileInfo, I suspect that's just a typo though.

For InspectFile we don't necessarily need to multicast. FileInfo has space for children but we could in theory remove that and make people do the more expensive ListFile to get them.

The only other snag seems like the behavior of DeleteFile on directories, I think your approach is probably right, let's chat a bit more offline.
