### ISSUE TITLE
Bash completion should be installed along with pachctl

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2371]
The completion code (added in #2352) should get installed as part of the deb setup (and presumably whatever the equivalent is for OS X installs)

**Comment by sjezewski** [comment]
Our bash completion got even better (it populates values too). We should either document installation or auto install it.

**Comment by ysimonson** [comment]
#3325 adds some flexibility to how bash completions are installed. Beyond that, I think auto-installing bash completions doesn't make sense because:

1. The bash completion tool isn't guaranteed to be installed.
2. The directory path that contains bash completions is not always the same.

**Comment by gabrielgrant** [comment]
To be clear, is the interface that got merged the same as what you mentioned in this comment: https://github.com/pachyderm/pachyderm/pull/3325#issuecomment-451545784 ?

i'd still prefer if we do the right thing on linux, at least

am i understanding correctly that the issue is that there's no standard location on OS X?

**Comment by ysimonson** [comment]
Yes, the interface is the same as that comment. There's two gotchas to auto-installing the completions. These apply to linux, not just macOS:

1. There's no guarantee that bash completions exist on any given system. It may or may not be installed on ubuntu and debian by default, I'm not sure. It is an apt package.
2. Even if bash completions are installed, there's no standard directory for putting the completions into.

I'd prefer to go with the principle of least surprise and go with what most packages do. I did not do a thorough analysis, but from the few I took a look at, it seemed they did not-auto-install the completions.

**Comment by ysimonson** [comment]
Are you sure that most of the completions you see are not installed by bash-completion itself? It comes with a bunch out-of-the-box.

Again, the directory is not standardized on linux either. Apparently you can get at it programmatically, but it requires a bit of gymastics; see the FAQ here: https://github.com/scop/bash-completion/blob/master/README.md

**Comment by gabrielgrant** [comment]
ugh -_-

**Comment by ysimonson** [comment]
Closing this because the install path for completions are not standardized, and there's no clean way to get it. This is in keeping with other tools, e.g. [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) also has separate setup instructions for completions, and we actually make it easier than most tools with the `--install` flag.
