### ISSUE TITLE
Add options for following and tailing logs to `pachctl get-logs`.

### ISSUE THREAD

**Issue by homme** [pachyderm/pachyderm#2383]
It would be very useful to keep a track on pipeline or job status and progress by enabling the streaming of logs in a similar way to `kubectl logs -f --tail=<n> <pod>`, such that we could do something like `pachctl get-logs -f --tail=<n> --pipeline <name>`.

**Comment by derekchiang** [comment]
Yeah that's a good idea and should be fairly doable.

**Comment by JoeyZwicker** [comment]
this is already in PR so adding to milestone

**Comment by jdoliner** [comment]
Fixed by #2574
