### ISSUE TITLE
Document using pachctl with bash/WSL on Windows

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2384]
[According to @najib in #users pach "works great" with Bash/WSL on Windows](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1507179159000167) 

We should walk through this (I think @derekchiang is the only one with a windows box internally?) and document the process and limitations so that we have some alternative until we can land #1636 (or an equivalent that gives full, native windows support)

**Comment by gabrielgrant** [comment]
@msteffen i think you were saying you have windows installed on your machine, right?

**Comment by williballenthin** [comment]
I kept notes as I figured out how to do a local deployment of pachyderm on Win10+Hyper-V+WSL. You can review them here: https://gist.github.com/williballenthin/8bbb7710ca8faa93d6eb57a44eda785b

**Comment by dwhitena** [comment]
Thanks @williballenthin!

**Comment by rmuellerjr** [comment]
I am also interested in the progression of Pachyderm for local Windows deployment

**Comment by dwhitena** [comment]
@rmuellerjr and others. Currently, `pachctl` works in the WSL, and can be installed via the `*.deb` that is specified in the docs. The other issue is really `minikube`. However, now Docker for windows desktop apparently includes k8s, which should make that part easier. We just haven't tested it yet. I will hopefully do this for the Mac Desktop version soon, which should be similar.

**Comment by gabrielgrant** [comment]
@pappasilenus I think you were asking about this yesterday. Did you get this sorted out?

**Comment by pappasilenus** [comment]
I posted to the user, waiting for response.
--
John Karabaic
gpg key available at hkp://keys.gnupg.net
513.295.6365

**Comment by rmuellerjr** [comment]
Let me see if I can give a try on Windows!

**Comment by maedoc** [comment]
I used Docker for Desktop's Kubernetes cluster, with the Linux `pachctl` binary on WSL successfully, along lines of
```bat
REM generate manifest and apply
wsl pachctl deploy local --no-guaranteed --dry-run | kubectl apply -f -
REM wait a bit, then contact pachd
wsl pachctl create-repo images
```
This doesn't handle path mapping for local files, so maybe a Windows native binary would be nice at this point.

**Comment by gabrielgrant** [comment]
Thanks a lot for testing this out and updating us, @maedoc

**Comment by svekars** [comment]
From the #users channel: 

 I'm a beginner with pachyderm and I'm trying to
setup pachyderm locally in my Windows 10 Home machine. I'm using VirtualBox 6.0.8 and Docker Toolbox 18.09.3. `minikube` is already running and I already installed `pachctl` in WSL Ubuntu 18.0.4. Attached here are some screen snips that might help.
Previous steps I did were:
- Run `minikube start`
- Inside WSL, I ran `pachctl deploy local --dry-run > pachyderm.json`
- I copied the json file into `/mnt/c/Users/user/dev/pach` and using powershell in `C:\Users\user\dev\pach`, I ran `kubctl create -f .\pachyderm.json`. All went well until the `ADDRESS=192.168.99.102:30650 pachctl version` command

Using `PACHD_ADDRESS` instead of `ADDRESS` solved the issue.

**Comment by gabrielgrant** [comment]
This came up again yesterday: https://pachyderm-users.slack.com/messages/C3UN0S0Q0/convo/C3UN0S0Q0-1563190674.495800/

> Wesley Yesterday at 4:37 AM
I'm trying to install Pachyderm and got all the way to getting pachctl installed before running into an error on Windows 10. When I ran the `$ curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v1.9.0/pachctl_1.9.0_amd64.deb && sudo dpkg -i /tmp/pachctl.deb`    command, I got a `"Warning: Failed to create the file /tmp/pachctl.deb: No such file or directory" and a "curl: (23) Failed writing body (0 != 16384)"` Any ideas how to fix this?
> ...
> I found that I had to install WSL first, then it worked perfectly
> Wesley  1 day ago
> Maybe put that in the docs?
>
> Wesley  1 day ago
> This link proved useful https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by svekars** [comment]
https://github.com/pachyderm/pachyderm/pull/3928

**Comment by svekars** [comment]
Done in #3928
