### ISSUE TITLE
Add bash completion for values to `pachctl`

### ISSUE THREAD

**Issue by homme** [pachyderm/pachyderm#2388]
At the moment (ea30d33935767eca5dc7d0b00075511f46514124) there is very useful support for bash completion in `pachctl`.  However, this is currently limited to sub-commands and options: it would be great if this could be extended to include values as well. e.g. `pachctl inspect-repo` would complete to show available repositories.

**Comment by dwhitena** [comment]
Thanks for the suggestion. This would definitely be useful!

**Comment by gabrielgrant** [comment]
This would definitely make the auto-completion more useful, and is something we've discussed building. Unfortunately getting potential values (eg. fetching the list of repos via an RPC call to pachd) is substantially more complicated than the simple/static completion we have today, so haven't gotten to it yet.

If any community members are interested in taking a stab at a first substantial contribution, this seems like it would be a good, well-isolated part of the code on which to do so

**Comment by brycemcanally** [comment]
I am going to be looking into this.

**Comment by sjezewski** [comment]
Thanks @brycemcanally , this landed:

https://github.com/pachyderm/pachyderm/pull/2625
