### ISSUE TITLE
grpc incompatibility

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#239]
Discussed offline with @sjezewski.  So basically, you can't use the latest version of `protoc-gen-grpc-gateway` because the Go files it compiles are only compatible with the latest version of `google.golang.org/grpc`, but apparently the latest version of `google.golang.org/grpc` does not work with [vendorization](https://golang.org/s/go15vendor) (??) because it uses [internal packages](https://golang.org/s/go14internal).

Two solutions:

1. We stick with an outdated version of `protoc-gen-grpc-gateway` when we compile protobuf
2. We don't vendor `google.golang.org/grpc`

**Comment by jdoliner** [comment]
We could actually go even farther and completely remove grpc-gateway. We don't really use it, there's one method exposed on pfs as an example but that's it.
