### ISSUE TITLE
pachctl deploy local --dashboard-only shouldn't include pachyderm-storage-secret

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2391]
@homme tried running `pachctl deploy local --dashboard-only --dry-run | kubectl delete -f -` which seems reasonable, but that deleted his `pachyderm-storage-secret`, putting his cluster into a weird state

I don't think the manifest we generate for the dash should touch the storage secret (or any other pach-wide settings)

**Comment by sjezewski** [comment]
Ah, I did `pachctl deploy local --dashboard-only` even though I was connected to an AWS cluster, and it worked fine.

I did see a warning about `pachyderm-storage-secret already exists` but that meant it didn't overwrite it, and I don't seem to see any side effects.

But yea, if we can omit the storage secret, so much the better.

**Comment by JoeyZwicker** [comment]
subsumed by #2390
