### ISSUE TITLE
get-logs doesn't work with stats

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2392]
Once a stats-enabled job has finished running, `get-logs` is supposed to retrieve logs from the stats branch. This seems to not work.

It seems to get some of the logs, then throw a different proto unmarshalling error each time it is run. eg:
- `grpc: failed to unmarshal the received message proto: illegal wireType 6`
- `grpc: failed to unmarshal the received message proto: LogMessage: wiretype end group for non-group`
- `grpc: failed to unmarshal the received message proto: illegal wireType 7`
- `grpc: failed to unmarshal the received message proto: wrong wireType = 0 for field WorkerID`
- `grpc: received message larger than max (1702112626 vs. 20971520)`
- ...

Originally reported by @homme in slack, reproed locally by @msteffen

**Comment by JoeyZwicker** [comment]
@msteffen this is fixed right?
