### ISSUE TITLE
GRPC connections with flanel on AWS get dropped very frequently

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2393]
Reported by @homme in slack. Seems to slow his cluster down, and I also observed it when loading up his dashboard -- it works intermittently, but has almost-constant dropped connections between the GRPC-WebSocket proxy and pachd which make it fairly unusable

We think it may be an issue with Flannel, but not entirely clear. They are running on AWS, with an ELB in front of their cluster. We have access to their pach cluster and k8s web console (ask me for creds) if useful to debug or set up a repro case

**Comment by homme** [comment]
I've torn the cluster down and rebuilt, so please contact me if you need access to replicate the issue.

**Comment by JoeyZwicker** [comment]
Any updates on this issue? Has this been regularly reproduced with Flannel, but works fine with Calico or other networking?

**Comment by sjezewski** [comment]
stale
