### ISSUE TITLE
Password entry with --push-images

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2395]
From a user:

> One feature that would be nice, is if you don't pass a password that it requests one from you like docker login would. For testing, I don't love typing my password into my bash.

**Comment by jdoliner** [comment]
We could probably do something like this, I think a better solution might be to just piggy back on `docker login` such that if you've called `docker login` before doing a `--push-images` would just work.

**Comment by ysimonson** [comment]
@jdoliner it looks like nowadays we do rely on the docker config by default. That said, the default config built for macOS does not work, because the docker library we use doesn't support keychain access - so they need to rely on `--password`.
