### ISSUE TITLE
Design: New Pachyderm Worker Model for 1.7

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2396]
# Objective
Improve Pachyderm's resilience when processing large datums by changing its model for how work is distributed to pipeline workers.

# Background
Pachyderm's current (v1.6.1) model for distributing datums to pipeline workers is fragile in presence of an unreliable network. Currently, a pipeline master sends datums to pipeline workers in a long-running `Process()` RPC. The RPC doesn't return until the worker has processed the datum and uploaded the result to S3.

Some Pachyderm users process datums that are several GB or larger, meaning that even downloading the datum can take minutes or hours. When the network connecting the pipeline master to its workers is unreliable, the GRPC connection (which is a TCP connection) can fail, requiring the master to re-send the large datum to another worker. In the worst case, the datum is effectively never processed and the user's pipeline never finishes.

The new model will be pull-based, rather than push-based, and will avoid long-running RPCs that were part of the previous model. In the new model, information about what datums need to be processed will be stored in etcd and watched by the pipeline's workers. Workers "claim" datums by writing a document to etcd and finish them by writing to etcd again. No RPC is open for the duration of the processing, and a pipeline's state can be discovered at any point by reading persistent data in etcd.

# Data structures
When Pachyderm is processing a job in this model, it will always consider datums in descending order, sorted by their size in bytes (and secondarily sorted by name). Thus d<sub>0</sub> is the largest/maximal datum and d<sub>i</sub> is the i<sup>th</sup> largest datum to be processed in the job

A running pipeline will store
1. A single file in etcd indicating which datums have been finished (the **Done Document**)
2. A collection of documents with expirations, indicating which datums are currently claimed by a pipeline worker (the **Leases**)

## Done Document
The done document contains a list of intervals `[a,b]`, each of which indicates that datums d<sub>a</sub> - d<sub>b</sub> have been processed successfully.

It also contains an error field indicating if and why the job has failed (this information will be copied to the JobInfo, but may be stored here transiently to avoid a race. It may be that the same error is stored in both the Done Document and the JobInfo, which means that the job has failed but the Done Document hasn't been deleted yet)

## Leases
The Leases are a collection of minimal documents that have an expiration time attached to them. The key for a Lease is a number. If the key `i` is present in the Leases collection, then the datum d<sub>i</sub> has been claimed by a worker and is being processed.

Note that workers claiming large batches of datums will have to write several Lease documents to the Leases collection. This is slow but necessary: the key for a Lease cannot be an interval, as `0-9` and `1-10` are distinct keys and will not produce a write collision in etcd, even though they indicate overlapping intervals

#### Alternative Considered
If `i` is present in Leases, then that could indicate that the datums d<sub>i</sub> - d<sub>i+k-1</sub> are being processed. When a worker started processing a set of datums, it would write a single Lease into etcd, and on success it would immediately start downloading and processing all datums in that range. If the worker needed to renew that lease, it would only renew the Lease document for `i`, instead of all documents for `i`, `i+1`, ..., `i+k-1`. All lease keys would be multiples of `k`.

An advantage of this approach is that each worker only has to renew one Lease at a time, instead of `k` Leases. A disadvantage is that workers can't process fewer than `k` elements at once, which precludes using smaller shards when processing large datums and bigger shards when processing small datums, or using smaller shards when the job is nearing completion (see comment below).

As there should be little write contention for Leases once processing has started, the overhead of renewing `k` leases will hopefully be low, so I chose to have workers acquire many Leases instead of one. We might revisit this facet of the design later.

# Steps in Processing a Job

1. When Pachyderm begins processing a new pipeline, it will create a Done Document (in a collection being watched by the pipeline workers).

2. A pipeline worker, seeing that a Done Document has been created, will sleep for a small, random amount of time (to reduce contention) and then read the Done Document and the collection of Leases from etcd. If there is no error in the Done Document, it will pick the smallest value `s` that is not in any interval in the Done Document and not in any Lease key.

    If there is no such value `s`, either because all indices are in the Done Document or because some are in the Done Document and some are in Lease documents, go to step 5 (the end).

    2e. If there is an error in the Done Document, the worker will, in one transaction:

    - read the JobInfo. If the JobInfo has an error already, then skip the write and continue
    - Otherwise, mark the job as failed and write the Done Document's error into the JobInfo (if it has been marked failed already, proceed to deleting the Done Document)

    Then the worker will delete the Done Document if it's still present (separate transaction).

    If either write fails, the pipeline will retry all of 2e until it sees that the JobInfo has been updated and the Done Document has been deleted, indicating that no more work needs to be done for the job

3. The worker will begin writing Lease documents to Leases for datums d<sub>s</sub> - d<sub>s+k-1</sub> . If the write for d<sub>s</sub> fails (because another worker has claimed it), the worker goes back to step 2. If the write for some d<sub>s+i</sub> fails, the worker will begin downloading and processing the datums d<sub>s</sub> - d<sub>s+i-1</sub> (this way workers are always processing a continuous interval). If the worker acquires leases for all of d<sub>s</sub> - d<sub>s+k-1</sub>, it will begin downloading and processing all of those datums.

    The worker should renew its lease documents as needed.

    3e. If the worker encounters an error while processing datums, it will, in a transaction

    - Read the Done Document from etcd. If the Done Document has an error, then skip the write and continue
    - Otherwise, write the error it encountered into the Done Document

    The worker will retry until the write succeeds or the worker discovers that the Done Document has an error. Then the worker goes to step 2e.

4. Once the worker succeeds, it will, inside of a transaction:

    - Read the Done Document from etcd
    - Add an interval to the Done Document indicating all of the datums that it processed
    - Scan through the Done Document and repeatedly merge any adjacent intervals in its list of intervals until all adjacent intervals have been merged. This limits the size of the Done Document, so that it can be read and modified quickly

    The worker will retry this operation until it succeeds, renewing its Leases on d<sub>s</sub> - d<sub>s+k-1</sub> until it does. While these leases are present, no other workers should be writing any overlapping intervals to the Done Document (though the worker may need to wait for other workers to finish adding their datums)

    Finally, the worker will delete its Lease documents. Once that succeeds, the worker will go back to step 2.

5. If some datum indices are not in the Done Document, the worker will sleep until the next upcoming lease expires, and then go to step 2. If all datum indices are in the Done Document (i.e. the job is done), the worker will, in a transaction:

    - Read the JobInfo for the job. If the job has been marked complete already, skip the write and continue
    - Otherwise, the worker will modify the JobInfo to mark it complete and write it back to etcd

    Then, the worker will delete the Done Document (separate transaction). Once the Done Document is gone, there is no more work to be done for the job.

**Comment by msteffen** [comment]
Future optimization: as the number of available datums goes down, the number of datums that workers try to process (i.e. `k`) goes down, to keep workers evenly loaded

**Comment by msteffen** [comment]
I just updated to doc to note that if both this and the new commit/job model are finished, pipelines may no longer need master processes, meaning idle pipelines could consume no resources at all

**Comment by msteffen** [comment]
Updated the title to reflect that this affects how datums are distributed during jobs, rather than e.g. how jobs are triggered or anything else

**Comment by msteffen** [comment]
Two differences between this design and its ultimate implementation (https://github.com/pachyderm/pachyderm/pull/2473):
1. In this design, each chunk of datums (i.e. each "run" of `k` datums in the design above) is protected by a single lock in etcd (above, each datum has its own lock)
2. the chunks are laid out by the pipeline master at the start of the job. Because the master defines the mapping from chunk→datum in advance and writes that map to etcd, the chunks can be different sizes (workers don't have to infer the chunks—they can just read each chunk directly). The master takes advange of this to lay out chunks that contain an approximately equal number of bytes. Currently, each chunk is the smallest run of datums that is >= some fixed size (>= is the condition so that every run contains at least one datum. It if were <=, a datum that was bigger than the fixed size wouldn't fit in any chunk)

**Comment by jdoliner** [comment]
I think everything in here has been implemented and shipped.
