### ISSUE TITLE
Worker details disappearing

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2398]
I have been working through some issues with a user. I think they are experiencing some of the networking issues that we have been seeing lately (https://github.com/pachyderm/pachyderm/issues/2396), but I also think something else is going on independent of that:

> Daniel Whitenack [9:52 AM] 
> Gotcha. Sorry you are hitting this @Homme. Let's continue to try and get to the root of the problem. Just as an update, the issue is that your job processing many datums and then seems to hang. In addition, `list-job` doesn't display any workers working on the datums. Is that correct?
> 
> Homme Zwaagstra [1 hour ago] 
> That's correct.  `list-job` seems to display workers ok for a while, and then goes a bit flaky. 
> The job hanging towards the end is an intermittent problem.  I'm getting around the issue by shuffling inputs that fail into the output repo in the user code, so a job always appears to succeed now, which is working for me.
> 
> Daniel Whitenack
> [44 minutes ago] 
> Ok, thanks for the additional information. This may be related to networking issues we have been having recently (mentioned also by @bbajer). We are currently investigating those. But, with the above workaround, are you currently blocked? I want to make sure you can continue scaling.
> 
> Homme Zwaagstra [27 minutes ago] 
> Yes, that's an interesting issue, I've just subscribed :slightly_smiling_face:  And I think I'm ok at the moment.  For one step I'm setting up a Redis instance for short term storage of data between pipelines just to speed things up.
> 
> ...
>  
> Homme Zwaagstra [5 minutes ago] 
> @dwhitena the issue of worker details disappearing from `inspect-job` output seems to happen _after_ an `update-pipeline`...
> 
> Daniel Whitenack 
> [3 minutes ago] 
> @Homme Ah, good info. I'm going to open a new issue here, because it sounds like there is likely something happening here independent from the networking issues.
> 
> Homme Zwaagstra [1 minute ago] 
> @U3ZRYDDLG I agree.  Is it something you can replicate?  It's happening to me even if I have as few as 2 workers.
> 
> Homme Zwaagstra [< 1 minute ago] 
> @dwhitena Note that I'm updating in the middle of a running job, which may make a difference.
> 
> Daniel Whitenack
> [< 1 minute ago] 
> Gotcha. I'm adding all this to the issue @Homme. Hopefully we can replicate and/or follow up for details.

**Comment by JoeyZwicker** [comment]
@jdoliner Is this something that is likely to be fixed by the worker refactor? Or is it an issue that needs to be investigated independently?

**Comment by sjezewski** [comment]
stale
