### ISSUE TITLE
In-flight jobs cancelled due to a newly-updated pipeline should be "killed" not "failed"

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2401]
Currently if `update-pipeline` is called while a job is running, the job is terminated and a new one is started using the latest pipeline spec. Those terminated jobs are currently marked as `FAILED` state, but they should probably be called `KILLED` instead

This caused some confusion (for me, at least) recently with @homme in the #users slack

**Comment by gabrielgrant** [comment]
@JoeyZwicker do you particularly think this shouldn't be worked on? This bug wasted several hours of time for me, homme, matt and JD trying to debug these supposedly-failed jobs, and it seems like it should be a single-line (or close to it) fix

**Comment by JoeyZwicker** [comment]
It's definitely worth fixing, but we're keeping the 1.7 milestone very lean. I've labeled it as 1.7 backlog which is basically what we'll use to fill the 1.7 milestone queue once we get through the main pieces.

There are lots of small easy fixes like this in the backlog label and it doesn't necessarily mean we'll get to it later than other things, but we want to keep the milestone relatively uncluttered.

**Comment by jdoliner** [comment]
We now implement this behavior.
