### ISSUE TITLE
Worker tolerances, possible `--dry-run` for `create-pipeline`?

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2404]
From a user:

> Hi all,  does anyone know of a way to set tolerances for pipeline workers?  Our situation is that we have an instance group composed of high performance (read expensive!) nodes that scales down to 0 when there is no k8s pod pressure.   We only want pipeline workers to run on this instance group and not any of the other services in the cluster. This is usually the case and there aren't any problems, but occasionally a service will be evicted and end up re-deploying on this worker instance group when a job is running.  This prevents the instance group from scaling down to 0 and costs :moneybag: over the longer term. We would be like any taints that we have set on nodes in the IG to be tolerated by Pachyderm workers but can't figure out how to set these tolerances.  Should this be in the pipeline spec, is there another way to set tolerances, or is there a completely different approach that gets us to where we want to be? Thanks :slightly_smiling_face: 

A possible solution that was suggested here was adding a `--dry-run` option for `create-pipeline` and possibly `update-pipeline` that would allow users to modify certain k8s primitives before deploying pipelines. However, I could definitely see some scenarios where this would be an "unsafe" route to deploying a pipelines. That is, Pachyderm could no longer make certain guarantees about how pipelines were deployed, but maybe that is a trade off some users would like to make.

**Comment by homme** [comment]
@dwhitena Thanks for following this up.  Yes, I agree it would be unsafe and would possibly forfeit any Pachyderm guarantees, but taking this into account it would be a useful 'power user' feature that would increase the flexibility of Pachyderm.

The workaround I'm going to look at goes something along these lines: `kubectl get -o yaml rc/pipeline-my-pipeline-v1 | my-update-script | kubectl apply -f -`.

I would also add `run-pipeline` to the commands that could benefit from a `--dry-run` option.

**Comment by jdoliner** [comment]
Getting `--dry-run` to work for pipelines would require a decent sized architectural shift. Not impossible but kind of difficult and it doesn't seem like that's the easiest way to solve this. Much easier would be to just added a section for tolerances like we've done for other k8s fields in the past.

**Comment by homme** [comment]
@jdoliner Adding a tolerances section would solve the issue in this case, although the `--dry-run` option would be nice to have in the future.

**Comment by sjezewski** [comment]
Another user reports a similar use case (tolerances + affinity)

```
Right, I did that to the resources that `pachctl deploy --dry-run` generates and you can see in the `kubectl get pods` output that all pods but one are on the right node. The misbehaving pod was created with the command `pachctl create-pipeline -f edges.json` that doesn’t have a `--dry-run` option to spit out the resources it would create and allow me to set `affinity` and `tolerations` to achieve what you are suggesting.
The default node scope for a google backed k8s cluster is `storage-ro` so I believe this would impact anyone trying to install  Pachyderm on an existing google cluster.
```

**Comment by jdoliner** [comment]
Tolerances are now possible in addition to other scheduling fields on pipelines. We've also got a stop gap solution for arbitrary modifications to the pipeline in the `pod_patch` field. The path to a `--dry-run` flag for pipelines is most likely going to be CRDs, that work is being tracked in #3345, so I'm going to close this in favor of that.
