### ISSUE TITLE
Linking pipeline script implementation to repo commits

### ISSUE THREAD

**Issue by philipjhj** [pachyderm/pachyderm#2412]
It would be very nice to have a way of linking the actual pipeline implementation to the pachyderm repo commits. Currently, it seems like only a newly created tag for the docker image is used to link the pipeline to the output, when the code is modified.

If the pipeline script is in a git repo wouldn't it be more clean to use the commit hash? Maybe it should just be added as additional information.

**Comment by dwhitena** [comment]
@philipjhj Great questions, and appreciate the feedback. Currently the best practice would be to use unique tags for your Docker images, not `latest`.  This can be enabled in a couple of ways:

- Have some CI pipeline build new Docker images when you push to your code repo and then update the Pachyderm pipeline with `update-pipeline` and the new Docker image tag.

- Use the "push images" flag on `pachctl update-pipeline ...`. This will basically do this unique tagging for you automatically after you build a Docker image locally.

Let me know if that makes sense and/or if there are follow up questions.  In either one of these cases, you will be able to connect commits with the unique Docker tags and see them with `inspect-pipeline`.

**Comment by ysimonson** [comment]
@dwhitena covers current best practices. Possible future improvements are discussed in #228 and #835
