### ISSUE TITLE
Use internal Pachyderm API for calls that should not be exposed

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2427]
This limits the API surface that needs to be covered by auth. In particular, the object store API does no ACL checks, but is exposed externally (because it's hosted on the same port as the PFS and PPS APIs)
BuildCommit also does no ACL checks (along with GetCapability, RevokeToken and a few other API endpoints)

A subset of things that should be moved
* Auth.CreateCapability
* Auth.RevokeCapability
* All of the PFS Object API
* PFS.MergeCommit

**Comment by jdoliner** [comment]
According to @msteffen  this is implemented, closing.

**Comment by msteffen** [comment]
(confirmed; fixed by https://github.com/pachyderm/pachyderm/pull/2977)
