### ISSUE TITLE
Encrypt traffic to and from Pachd using TLS

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2429]
Right now, traffic between Pachd and the dashboard/pachctl is unencrypted. This should be fixed so malicious users can't e.g. snoop the contents of `GetFile` results.

**Comment by sjezewski** [comment]
How would this work?

Pachd would terminate using TLS, and would use a self signed cert, but one that the dashboard trusts?

But if a snooper has access to the k8s network, I think they'd have k8s access? (Maybe this is my faulty assumption). In which case they could see the certs, and decrypt the traffic.

**Comment by jdoliner** [comment]
I think the point of TLS is that it'd protect people snooping outside the k8s network. If you have access to the k8s network then there's probably not much stopping them snooping, but there's good ways to prevent people from having that access. There isn't a good way to send `pachctl` traffic over a secure channel.

This is affecting some users so we're going to get this scheduled ASAP.

**Comment by jkinkead** [comment]
@sjezewski someone with root access to the k8s cluster would be able to snoop the contents of memory, control the pods, etc; but a user running pods shouldn't be able to see anything, even if they could intercept the packets.

If the certs are stored in k8s secrets, then a user with access to the secrets could snoop the traffic - but in a cluster with RBAC enabled, this would not be allowed.

**Comment by SpenGietz** [comment]
I wanted to confirm that this implementation would include the web servers located on ports 651, 652, and 999 as well.

**Comment by brokenjacobs** [comment]
You can front pachd with an ingress controller providing tls and http2, but pachctl won't auto-upgrade to tls connections. And ingress-nginx doesn't like http2 without tls. Suggest an environment flag to use grpcs, or make pachd_address optionally contain grpc:// or grpcs://

**Comment by msteffen** [comment]
Related issue: https://github.com/pachyderm/pachyderm/issues/3944

**Comment by ysimonson** [comment]
Assuming this is specifically about client<->pachd communication, I believe it's addressed at this point (via `pachctl deploy --tls`), but please re-open if I'm wrong.
