### ISSUE TITLE
Create merged output in stats commit for failed jobs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2431]
We can see the successful portion of a failed job's output on a per-datum basis in the stats commit, but we don't do merging of datum outputs. In practice, to help debug, seeing the full job's full, merged output up to the point of the failure would be useful.  Would it maybe make sense to create a single, merged output (ie what would have happened as the last step in creating the output commit if the job had been successful) in the stats commit for failed jobs?

split out from #1880

something similar to this came up when trying to debug a job with homme in slack

**Comment by jdoliner** [comment]
We do this now.
