### ISSUE TITLE
document how to spin down/migrate a cluster

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2435]
From [philipjhj in #users slack](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508233528000116):

> I can not find a description of how to save and restore the repos (both input and output) in the documentation.Say that I have configured the word count example and have it running on Azure. At this point I have no more data to analyze for the time being and want to shutdown my Azure instances, but want to be able to quickly redeploy my pachyderm repos and pipelines with all the results (preferably on any host).What is the correct way of thinking about and doing this?
> 
> Maybe more precisely: how do one store the repos and their history for either redeploying them later or sharing them with others?

@dwhitena gave [a good answer](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508249999000238); this info should probably make it's way into the docs:

> You can definitely tear down Pachyderm clusters and reboot them. You just need to specify the same object store bucket and PV. Then Pachyderm should come up in the same state, assuming those storage resources are preserved. It is also recommended that you backup those storage resources as needed, especially during migrations or redeploys (if you need to ensure that you don't lose any data). However, great suggestions. I agree that there might be useful checkout functionality or cloning functionality that we can discuss.

This should probably go in the "Manage Pachyderm" section

**Comment by dwhitena** [comment]
Yeah agreed @gabrielgrant. This is useful information that we should add.

**Comment by gabrielgrant** [comment]
Just answered basically the same question from @homme and @bbajer (Bart) [in slack this morning](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508515138000223):

> What are the steps to migrate pachyderm between clusters (presevering etcd and the persistant volume and pointing it back to the same S3 bucket)?
> Similarly how do we ensure that when we want to do a clean deploy that everything underneath pachd has been cleared out?
> 
> Gabriel Grant 9:08 AM
> @bbajer my understanding is that if you undeploy a cluster and redeploy with the same PV and object storage source, everything should come back up as expected
> (the flip side being that if you use a fresh PV and bucket that you should have a completely clean slate)

Unclear exactly what he means by "migrate": are both clusters running on the same cloud, and have access to the same storage sources, or do you actually need to move data? (eg moving GCS to Amazon, for example. Or, probably even moving between Amazon regions)

The former should be pretty straightforward (though there's a bit of added complexity in finding the PV name (if it was auto-created by pach) and adding it to the `pachctl deploy` command on the new cluster). Not entirely sure of the steps in the second case, but I'd imagine copying all the bucket contents over, and tar-ing up the full PV, creating a new PV on the new provider, un-tarring there, and then deploying pointed at that _should_ work, right?

**Comment by gabrielgrant** [comment]
relevant slack convo https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508526704000170

> Bart Bajer 12:11 PM
> Kind of a Naive question
> etcd stores everything in the persistent volume.
> There are two ways to deploy pachyderm using `static-etcd` and using `dynamic-etcd`.
> Using `--static-etcd-volume` you can probably point etcd at the volume
> but how would you do that with `dynamic-etcd-nodes`? I imagine directly through kubectl and not pachctl?
> Gabriel Grant 1:04 PM
> @bbajer sorry, i'm honestly not 100% clear on exactly how that works (that's why that part of the issue i filed is a bit hand-wavey). @jdoliner are you able to answer that? (edited)
> 1:05
> (or maybe @dwhitena?)
> Joe Doliner 1:08 PM
> @bbajer I don't think you can use `--static-etcd-volume` with `--dynamic-etcd-nodes`
> Bart Bajer 1:08 PM
> I'm sure you can't
> 1:10
> I'm asking how do you 'migrate/move' a pv from a pachyderm having been deployed via `dynamic-etcd-nodes`
> 1:11
> how do you attach that old pv to a new pachyderm deployment on a different k8s cluster (edited)
> Joe Doliner 1:13 PM
> so I think the easiest way would be to just use `--static-etcd-volume <volume-name>` does that work for your purposes or does it miss something?
> Bart Bajer 1:16 PM
> I think that only works if all you k8s masters are in the same availability zone.
> Joe Doliner 1:20 PM
> @bbajer hmm, because the k8s master can't mount the volume if it's in the wrong zone?
> Bart Bajer 1:20 PM
> I believe so
> 1:21
> I might be mixing something up but I'm pretty sure there was some issue where we had to use dynamic etcd
> Joe Doliner 1:25 PM
> hmm, so that seems like a bit of a problem. Since the volume you need is stored in 1 specific AZ, the etcd pod is going to have to be deployed in that same AZ for this to work
> Joey Zwicker 1:26 PM
> I imagine AWS has some way to snapshot a volume and then load that into a new volume in an AZ, but I havent played with that before

**Comment by dwhitena** [comment]
This seems to be related: https://github.com/pachyderm/pachyderm/issues/2475, and maybe there is some significant overlap in these docs?

**Comment by dwhitena** [comment]
Should be covered in these docs:
- http://pachyderm.readthedocs.io/en/latest/deployment/upgrading.html
- http://pachyderm.readthedocs.io/en/latest/deployment/migrations.html
