### ISSUE TITLE
Cloudfront signed URLs expire before datum/job completes

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2437]
```
cloudfront returned HTTP error code 403 Forbidden for url http://<elided>.cloudfront.net/pach/block/063e6f67d52a4985bfa21a2ffb557ab4?Expires=1508455024&Signature=<elided>
```

Where the expiry is in the past. Looking at the amazon client code ... looks like the default expiry is set to an hour in the future. We should up that.

**Comment by homme** [comment]
Is the expiry something that can be updated as a job progresses in order to make sure it never gets triggered no matter how long a job runs for?

**Comment by gabrielgrant** [comment]
yea, seems we should handle refresh, rather than just relying on a fixed time window (esp in linght of #2436)

**Comment by homme** [comment]
If I update a job using `update-pipeline` should that refresh the expiry?  Just trying to think of a practical workaround in the short term...

**Comment by gabrielgrant** [comment]
closing in favor of #2438 (more context)
