### ISSUE TITLE
Can multiple inputs from the same repo be automatically merged without having to explicitly name them?

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2441]
Currently taking multiple inputs from a single repo requires explicitly naming at least one of the inputs. For example, this pipeline spec fails to create:

```
{
  "pipeline": {
    "name": "edges-cross"
  },
  "transform": {
    "cmd": [ "python3", "/edges.py" ],
    "image": "pachyderm/opencv"
  },
  "input": {
    "cross": [
      {
        "atom": {
          "repo": "images",
          "glob": "/kitten.png"
        }
      },
      {
        "atom": {
          "repo": "images",
          "glob": "/liberty.png"
        }
      }
    ]
  },
  "enable_stats": true
}
```

(it yields the error message `Failed to save pipeline "edges-cross": name images was used more than once`)

Could this instead just create a single `images` directory and merge the file hierarchies from the two inputs? So in this case you'd get `/pfs/images/kitten.png` and `/pfs/images/liberty.png`

I think as long as both inputs are operating off the same branch, then any files that conflict will be the same anyway, so overwriting in either direction first won't make a difference. If different branches are specified, it would be reasonable to fail, but this could also just merge them as `/repo-name/branch-name/path/to/file`

**Comment by jdoliner** [comment]
This seems a little bit weird and potentially confusing for a couple of reasons.

- You could cross 2 files and only get a single file showing up in `/pfs` if it happens to be the same file.
- In the case where it's different branches (which isn't possible right now) you wind up with a deeper file structure than normal which means code will have to be rewritten.

Overall it doesn't seem worth complicating this matter unless there's a clearer use case that we're not satisfying here.

**Comment by gabrielgrant** [comment]
Yes, as i mentioned, I agree those are both issues. I think the issue of branches causing directory structure to change is probably more surprising, but also far less likely to occur -- it can't right now; and even if it could in the future, it's probably pretty rare. So it seems reasonable to just say we'll only do this auto-merging for the same branch on the same repo. Should be pretty easy to enforce that, since the condition of two different branches of a repo both not having names is something that could be easily detected and just result in a failure at pipeline creation time (ie the same error check we already do today).

As for files overlapping. Yes, that's how it would work. Doesn't seem all that surprising, that if I ask for the same file to be loaded into the same location, that that's what I get... 

The specific use-case that I'm targeting is wanting, say, 5 specific files from directory in a repo as input. This is particularly relevant/likely in the context of doing exploratory analysis or debugging in a service. For example @homme had a case last week where he had some datums (each was just a single input file) that were failing, while seemingly-similar datums were succeeding. It would be useful to load up a workspace with both the failure cases and a few examples of datums that work as expected in order to step through and compare them. It feels pretty weird to have to explicitly name each (and then end up with these parallel, mostly-empty directory structures)

**Comment by JoeyZwicker** [comment]
I wonder if there's just an easier or different way to solve the use case you're describing @gg. I've definitely seen users ask questions similar to "How do I easily run my code over a subset or specific datums only for testing/debugging." 

One of the open discussions we've had is around better meta-operations for moving data around pachyderm. A simple example could be `clone-repo` which would let me make a new pachyderm repo with all or some of the data in an existing repo. `clone-repo` is just sugar for `create-repo` and then `put-file -f pfs://...`. I'm not saying we actually need "clone-repo" but what you're describing above could be done by just plucking a few datums from the `master` branch into a 'test' branch (or deleting all except the faulty datums). 

Maybe I'm misunderstanding, but I'm not sure semi-magical semantics like you're proposing are quite to right way to allow this type of workflow.

**Comment by gabrielgrant** [comment]
Copy could possibly work in that case, though I think there are (more?) often cases where what you're really looking for is more of a copy pipeline, rather than a copy operation (ie if the file changes upstream, you want to see the change downstream). I think having sugar around creating auto-updating copies of a subset of files would be great, though.

There are still cases that I think would be better served by merging the directory trees. For example:

I have data and metadata (say a CSV file split into one-file-per-line, and another file for the header row). This should be straightforward to consume as a cross of a glob with the metadata file: `repo/row-*` `X` `repo/header`; currently I can't get these passed to my code with the same directory structure as they appear in the input repo. That seems strange to me

**Comment by jdoliner** [comment]
I think this is a rare enough case that allowing name collision here is more trouble than it's worth, since validating it will require inspecting the glob patterns to make sure they can't collide (this is only valid because the crossed inputs reference specific images rather than using `*`. Feel free to reopen if there's a compelling need for this, but I think having to enter a separate name for a case as weird of this is a reasonable burden.
