### ISSUE TITLE
Dashboard should be auto-deployed

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2443]
When we first rolled out the dash, we were auto-deploying it. I asked for it to not be deployed by default because I didn't feel it was ready for public consumption. That isn't the case anymore, so I think we should deploy it by default, unless the user passes a `--no-dashboard` flag (or something similar)

I have some concern (shared by @JoeyZwicker) about whether it feels weird to include an enterprise feature in the default open source deploy, but I think we agreed that that the concern is outweighed by the better initial user experience so long as:
- it's easy to avoid deploying
- we're offering free initial usage

I'm still a bit squeamish, but this feels like the right decision, given how frequently we field questions from users who are confused by why they can't access the dash after initial deploy (though admittedly, that is likely exacerbated by #2444)

**Comment by JoeyZwicker** [comment]
User PR submitted for this. #2667

**Comment by sjezewski** [comment]
This has been fixed
