### ISSUE TITLE
Show different post-deploy message depending on whether dashboard is deployed

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2444]
Currently, it seems the deploy script prints a message directing the user to visit the dashboard in their browser regardless of whether they have actually deployed it. This should be changed to show something like `To deploy the Pachyderm Dashboard run "pachctl deploy local --dashboard-only` if the dashboard hasn't been deployed

**Comment by dwhitena** [comment]
@gabrielgrant Looks like this has maybe been taken care of. However, there is a confusing message displayed when port-forwarding, which is being addressed in a different issue https://github.com/pachyderm/pachyderm/issues/1728. Closing for now.

```
➜  pachyderm git:(jeffm14vt-docs-fix-typos) ✗ pachctl deploy local
serviceaccount "pachyderm" created
deployment "etcd" created
service "etcd" created
service "pachd" created
deployment "pachd" created
secret "pachyderm-storage-secret" created

Pachyderm is launching. Check its status with "kubectl get all"
```
