### ISSUE TITLE
OSX: update-pipeline --push-images error

### ISSUE THREAD

**Issue by kav** [pachyderm/pachyderm#2446]
Getting an error:
`error parsing auth: open ~/.dockercfg: no such file or directory, try running 'docker login'`

however on OSX it appears that login doesn't create this file. We do have these files: 
~/docker/config.json
~/docker/daemon.json

Any ideas? 

Happy to dig in and PR once I have a bit more context on everything

**Comment by jdoliner** [comment]
I believe if you do `export DOCKER_CONFIG=/home/kav/docker` then it will work.

**Comment by dwhitena** [comment]
We should add a note in the docs. Tagging.

**Comment by gabrielgrant** [comment]
Docs is a good stop gap measure for right now, but if docker on OS X automatically puts it's config there, then we be checking there in addition to the standard linux location

**Comment by gabrielgrant** [comment]
Almost certainly too optimistic...we are dealing with computers, after all
![Hello](https://media.giphy.com/media/l378BaFZ8AUJ20NvW/giphy.gif)

**Comment by kav** [comment]
Looks like on OSX $DOCKER_CONFIG isn't defined on OSX, on my box at least (17.09.0-ce-mac35 (19611)) which is causing the upstream lib's check to pass on to later clauses, I'll file a bug over there or on Docker for OSX depending on whether the removal was intentional on Docker's part.

Closing for now as this is upstream. Will update with upstream issue. For those googling in the meantime `export DOCKER_CONFIG=~/.docker/` will fix the issue.
