### ISSUE TITLE
Downsample flag in pipelines

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#245]
Add a downsample flag in pipelines for when user wants to experiment. Instead of running processing all the data whenever they update a pipeline, they can set a downsample factor. Saves cluster resources and improves the update pipeline <--> view results iteration cycle.

**Comment by JoeyZwicker** [comment]
This may be obvious and our current sharding implementation already supports this: If the downsample factor doesn't change when a pipeline is updated, the input data should remain the same, not resampled each run or update.

**Comment by sjezewski** [comment]
This can be accomplished today w glob patterns. E.g. if at my root I have a bunch of images, I can specify a glob like `11*.tif` to get a consistent subset.
