### ISSUE TITLE
Data corruption & errors from missing objects

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2452]
From [a discussion with Homme in slack](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508510948000206), it seems that data corruption of the referential links in the object store will cause (seemingly-unrelated) jobs to continually restart

Specifically, @homme:

- had a cluster with a bunch of repos, pipelines and Jobs. Some jobs were failing (unclear why; not super relevant to this issue)
- deleted some (but not all) of the data objects in the bucket
- jobs started getting stuck in restart loops with `object not found` errors (not surprising)
- tore down the cluster, and deleted the PV
- deployed a new cluster, with new PV, but pointed at the old bucket
- jobs were still getting `object not found` errors (this *is* surprising)

Output of `kubectl logs -f --tail 20 pipeline-list-dataset-contents-v1-4mx6c` (being run with only one worker):

```
{"pipelineName":"list-dataset-contents","workerId":"pipeline-list-dataset-contents-v1-4mx6c","master":true,"ts":"2017-10-20T14:44:03.662327291Z","message":"error running jobManager for job 9bb5a8fd-81c9-4c3a-8c4f-1562816301a4: rpc error: code = Unknown desc = objectInfoGetter: object f042dce4791862422878dc9e6e6eeebf10a89a001637dc4bafff404bc9cdbb2aebdef9675985efa766a1f4f2119d993a1436f2e445335d16bf5b7b1c011aaefe not found; retrying in 19.704599415s"}
```

The job is continually restarting:

```
# pachctl list-job
ID                                   OUTPUT COMMIT           STARTED       DURATION RESTART PROGRESS  DL UL STATE            
9bb5a8fd-81c9-4c3a-8c4f-1562816301a4 list-dataset-contents/- 5 minutes ago -        31      0 + 0 / 0 0B 0B running 
```

From talking to @jdoliner and @msteffen , my understanding is that the only referential data structures in the object store are TreeObjects (which contain info about the whole directory hierarchy for a commit given by pointing to FileObjects) and Tags, which point to TreeObjects

IIUC, though, this means that a new cluster, with no commits in etcd, has no reason to access either of these referential structures, and should simply use the existing data in raw FileObjects for storage deduplication. This means these failures shouldn't be occurring, when, in fact, they do happen consistently, on all jobs.

<strike>
Open questions for @Homme to clarify:

- were you seeing this issue on the old cluster _before_ you started deleting data from the bucket?
- when you say "this issue" -- do you mean this log output about an object not being found, or just the same symptom of a job that continually restarts?
- are you seeing this error for all jobs, or only some?
- if it's only some jobs, does it happen consistently for jobs from a particular pipeline?
- can we tell from the failed jobs' stats output on which datum the job is failing? (there should be one datum in a failed state) is this the same datum each time?
</strike>

Actionable:

- Guidance for how to cleanly relaunch clusters when there's too much data to delete/the bucket is hard to re-create (in @homme's case, due to usage of cloudfront)
- Figure out where/why this data is being used, when it's not referenced by any commits (or anything else in etcd)
- We could probably do a better job handling this in a lot of cases by detecting when we're missing data that we expect to be there
- At the moment we generally assume that we're the only ones removing data from object storage. If we discover data is missing or somehow corrupted:
  - we could try re-computing it if we have the upstream data to do so (though I imagine that would be a non-trivial change)
  - Inform the user specifically what data is missing, and what effect that will have in terms of making downstream computation impossible
- Figure out why these jobs are restarting repeatedly, instead of being put into FAILED state

My understanding is that we don't aggressively recheck consistency because it's fairly expensive to have to constantly be having to download and rehash masses of data, but we could definitely have some more thorough consistency checking code available to be run on demand,either by a user manually, or automatically in case we come across an inconsistency like this

If, for some reason, we think having the history of which files were deleted from the repo, @homme has said we can have access to their AWS billing logs to extract which items were add/deleted and when

**Comment by sjezewski** [comment]
I think this is not surprising. Idk what was deleted in s3, but I know there is at least one level of dereference happening there. So if you delete the underlying content but not the reference, I could see that error happening.

More broadly, I don't think we support users modifying the underlying obj store.

Marking as stale. If this happens again / is something we want to support we can re-open.
