### ISSUE TITLE
Pipelines with Union inputs don't start jobs if some input repos are empty

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2453]
Currently pipelines with union inputs only trigger when *all* inputs have at least one commit, whereas they should trigger when *any* of the unioned inputs have a commit

**Comment by bpb** [comment]
Should this not also be true for cross input? A new datum input in Repo A should be crossed with all inputs of Repo B even if no new commit has occurred in repo B?

**Comment by JoeyZwicker** [comment]
@bpb With `cross` Pachyderm waits for at least 1 commit in all inputs. In other words, in a `cross`, datums are a tuple of one piece of data from each input and pachyderm waits until at least one complete datum is available. 

In a union, datums are independent so waiting for one datum in each repo isn't required.

**Comment by jdoliner** [comment]
In a cross if one of the inputs didn't have a commit yet you wouldn't have any datums at all since a single empty repo means there's not going to be any tuples. This isn't so in a union.

**Comment by bpb** [comment]
I must have miss understood. Some of the previous documentation made me think that crosses won't trigger unless both inputs have new commits. But the wording is that both inputs have at least one commit which means that no input is _empty_ (aka has no commits).
Sorry for side tracking this ticket.

**Comment by gabrielgrant** [comment]
@bpb no worries, just updated the title to hopefully make it more clear I'm only taking about what triggers the first run of a pipeline

**Comment by jdoliner** [comment]
Jobs now trigger in this scenario.
