### ISSUE TITLE
"Auth model" section of auth docs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2454]
Right now [our auth docs](http://docs.pachyderm.io/en/latest/enterprise/auth.html) dive directly into the details of how to use auth, without giving any sort of high-level view of how auth is structured in pachyderm

Some portion of the info in the design doc (#2024) and possibly the implementation doc (#2153) should make it into the docs

(I'm pretty sure we've discussed this previously, but can't seem to find an issue about it, and since the two auth issues are now closed, want to make sure it doesn't slip through the cracks)

**Comment by dwhitena** [comment]
I think what we have added recently provides a general overview. Closing for now.
