### ISSUE TITLE
Make aws.sh more prescriptive

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2457]
When a user is missing a pre-requisite ... e.g. `pachctl` ... the script exits w the last line that looks like:

```
+ which pachctl
```

Which has tripped up several users. We should have the script literally say something like the following before exiting:

```
Could not find pachctl locally. Please install pachctl, by following these directions ... <link>
```

Same for uuid, jq, kubectl, etc.

**Comment by sjezewski** [comment]
A number of users have stumbled on errors like this. Our audience doesn't know what `which ...` does so we need to be prescriptive.

**Comment by mindthevirt** [comment]
aws.sh is no longer in use. AWS deployments are parts of `pachctl deploy amazon`
