### ISSUE TITLE
Streaming Flag for Pipelines

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#246]
When false, the pipeline runs on the current commit, but doesn't automatically update when new data comes in. Great for experimentation when data is constantly being committed to input repos.

The first time a pipeline is created with `streaming = 0`, it "locks" to that commit so the same data is always being processes as the pipeline is updated. 

Command `catchup pipeline [commitID]' will "lock" the pipeline to the latest commit, or a specific commit. Might also accept tags like "latest". 

`streaming = 1` "productionizes" the pipeline so now it runs automatically on all commits. 

Alternative names: Auto-streaming, stream

**Comment by jdoliner** [comment]
Minor nit, I prefer the name `stream` to `streaming` because it feels like giving an instruction rather than describing something.

**Comment by JoeyZwicker** [comment]
@jdoliner We'll take that under advisement and add it to the alternative names list. :P

**Comment by sjezewski** [comment]
I believe we can support this workflow w `update-pipeline --reprocess` and use of the `--from-commit` flag
