### ISSUE TITLE
aws.sh mktemp support on mac

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2463]
On a mac the script errs on this line:

```
tmpfile="$(mktemp -p .)"
```

In particular ... it reports `illegal option -p`

**Comment by jdoliner** [comment]
This line is now:

```
tmpfile="$(mktemp $(pwd)/tmp.XXXXXXXXXX)"
```

I don't have a mac to test this on, but it looks like this was fixed, feel free to reopen if not.
