### ISSUE TITLE
PutFile gs://bucket only works if Pachyderm is running on Google

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2467]
Currently, it's impossible to ingress data into Pachyderm from GCS if Pachyderm is running outside of Google's cloud, due to the library we're using as our GCS client. When run outside of Google, src/server/pkg/obj/google_client.go:22 calls cloud.WithTokenSource("") which returns an error about not being able to find GCP's metadata service.

**Comment by sjezewski** [comment]
I think if you supplement the `secret/pachyderm-storage-secret` w the google values this will work.

Marking as stale until we see more requests for this.

**Comment by sjezewski** [comment]
Ah, according to

https://github.com/pachyderm/pachyderm/issues/2578

We don't currently support google secrets, only the metadata API. But theres a new lib that would allow us to use secrets. Keeping this closed until we see more requests for this.

**Comment by jdoliner** [comment]
This was actually fixed here #2610.
