### ISSUE TITLE
Recent actions/cluster changes/"Accounting"/Audit logs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2468]
In the dash we'd like to be able to show both a list of recent actions a user has taken ("recent changes") and any changes made to the cluster ("cluster activity")

This same basic idea is also relevant for both the "accounting" part of AAA (ie tracking usage to be able to bill for a hosted product based on usage) and "audit logs" as a feature of the auth system (the DoD person I had spoken to said this was critical for them -- moreso, actually, than restricting access for users within the system. Anyone who has access to the cluster has access to the data, but they need to be able to trace who has accessed what and in what ways after the fact)

**Comment by jdoliner** [comment]
Closing in favor of #3069 since that's more fleshed out.
