### ISSUE TITLE
Add catchup-pipeline command

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#247]
Needed for #246 

`catchup-pipeline [commitID]'

[commitID] is optional and defaults to Head on Master. Let's the user specify an exact commit to "lock" the pipeline to. Branch specification and/or tags such as "latest" may also make sense to support.

**Comment by jdoliner** [comment]
A few clarifications I'd like:

What if there are multiple input repos, can you specify a commit to catchup on each of them?
What if the commit came before the current commit, do we allow users to rewind with this command?

Also how do people feel about `fast-forward` git uses that term for a similar concept.

**Comment by sjezewski** [comment]
This seems stale, so I'm closing. If there are more details / new requests for this we can re-open.
