### ISSUE TITLE
expose cluster ID through the API

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2474]
maybe as part of the `version` service?

**Comment by jdoliner** [comment]
Why would we do this?

**Comment by gabrielgrant** [comment]
to enable tracking from the dash

**Comment by jdoliner** [comment]
That makes sense, this is, as you may have guessed, not terribly hard to implement.

**Comment by sjezewski** [comment]
FYI, if you need this for debugging, you can port forward etcd, then use the client (v2) to read the key. I just had to do this recently, and it would've been handy to be able to poll directly.
