### ISSUE TITLE
Docs on upgrading pachyderm versions

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2475]
This is a very common question in #users. We need a doc to describe this process and common issues we see,  such as the etcd volume mount. This doc should also include backing up your volume and links to the migration doc.

**Comment by dwhitena** [comment]
@JoeyZwicker When you say the common issues, can we list so here (b/c I might not be aware of all of them). Also maybe @jdoliner or @msteffen want to comment on this?  I think some of the issues are:

- You used dynamic volumes in an initial deploy, now you want to reuse that volume(s) in the newly deployed cluster, so you have to use static volumes or do something else different.
- Sometimes you seeing warnings when re-deploying, deploying the dashboard on a previous deployment etc., are these benign?
- Reconnecting `pachctl` and `kubectl` etc. with the new cluster
- others?

**Comment by JoeyZwicker** [comment]
Some ideas, not all need to be included in the first pass of this doc

- Deploying to a non-default namespace and any complications from that
- best practices that include keeping your previous pachctl deploy command saved to reuse
- How to snapshot your volume in each cloud provider for data safety if something goes wrong
- Link to migrations and mention that they may need to update pipeline specs if there have been changes as part of the update
- known problems with AWS mounts being finicky and how to troubleshoot

Until #2451 is solved-- scaledownthreshold resets in a upgrade so they may have resource problems. Perhaps it makes sense to pause pipelines before the upgrade? There's just a lot of surface area for things to go wrong, but given the fast development speed of Pachyderm, we don't want users being scared of upgrading.
