### ISSUE TITLE
Deploying Pachyderm to non-default namespaces doesn't work

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2479]
Per a customer interaction:

> I think the issue is somewhere with the namespace
> cause I just launched with `pachctl deploy amazon ${BUCKET_NAME} ${AWS_REGION} ${STORAGE_SIZE} --dynamic-etcd-nodes=3 --credentials "${AWS_ACCESS_KEY_ID},${AWS_SECRET_ACCESS_KEY},"`
> where it deploy inside the default namespace and it works perfect
> I tried both with namespace and non of them worked

A few notes:
* The way I've been deploying into non-default namespaces for this test is `pachctl deploy amazon ... --dry-run | kubectl create --namespace=<namespace> -f -`
* When I accidentally tried deploying to a namespace that doesn't exist, I saw several errors, but also saw `storageclass "etcd-storage-class" created`, indicating that the etcd StorageClass may, for some reason, be the k8s object that is still created in the default namespace for some reason

**Comment by philtweir** [comment]
Apologies if this is missing the failing functionality, but just as a datapoint, I'm using pachyderm 1.6.3 on Kubernetes 1.7.4 w RBAC (kubectl 1.8.2) and found that the approach mentioned by @msteffen with `pachctl port-forward -k '--namespace NAMESPACE' ` seemed to let local commands work as normal. As an aside, I could be wrong, but I don't think a StorageClass has a namespace?

**Comment by sjezewski** [comment]
This is a requirement for customers w multi tenant k8s clusters.

**Comment by sjezewski** [comment]
Fixed by https://github.com/pachyderm/pachyderm/pull/2714/files
