### ISSUE TITLE
Remove `create-job` command from external API

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#248]
This is an open discussion that JD and I were having recently.  In short, `create-job` it would be replaced with `run-pipeline <pipeline_name>.` Other `*-job` commands would remain(?).

There are a number of reasons to potentially do this.

Currently, there are tons of "dead" output repos hanging around from every job that was run. if the same job gets run again, it creates another repo. Job outpur repos seems substantially less organized and manageable than pipeline output repos. @jdolinder is the transform for the job also saved somewhere? if so, then it's already basically a pipeline except they "live off in the ethereal pachyderm world" instead of fully being pipelines that users can later productionize and reference. 

Adding `run-pipeline` also gives us a easy way to start a pipeline that isn't being triggered by new input data (e.g. web scraper). Similarly, if the user updates the image on DockerHub, no new data has come in, but the pipeline should clearly be rerun (without incrementality optimizations).

This idea is a little half-baked right now. We should think about it more.

**Comment by jdoliner** [comment]
Few clarifications on this, I don't think we ever want to completely remove `create-job` from the API, what we do want to do is obviate it's use for standard operations making it a poweruser feature.

@JoeyZwicker in your mind under this scenario what's the pipeline workflow that's the equivalent of what `create-job` does now? `create-pipeline` followed by `run-pipeline`? I was expecting it to just be `create-pipeline` which automatically runs the job once but not more (see #246). Your other justification for `run-pipeline` makes sense. But I think it's orthogonal so should be separate issue.

`Transform`s are saved inside of `persist.JobInfo` and `persist.PipelineInfo` which get serialized to RethinkDB

**Comment by JoeyZwicker** [comment]
>I was expecting it to just be create-pipeline which automatically runs the job once but not more (see #246).
I was thinking this. We don't want user to make two commands to run a pipeline. 

I can't think of another strong use case for `run-pipeline` that not my second reason, but I feel that there is one. I'll think on it more.
