### ISSUE TITLE
Allow create/update pipeline in one command

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2485]
Currently, if a user has a pipeline specified in a .json, and they add a new pipeline to that .json file, and they'd like to update the first pipeline and create the second, they can't (`update-pipeline` complains that the second pipeline doesn't exist, and `create-pipeline` complains that the first pipeline exists already)

**Comment by jdoliner** [comment]
`update pipeline` now implements upsert semantics, so it will always work and should be used in this case.
