### ISSUE TITLE
Job stats bug

### ISSUE THREAD

**Issue by jonandernovella** [pachyderm/pachyderm#2490]
These are the logs from one job in Pachyderm 1.6.3:

`"started": "2017-10-30T15:27:50.073855757Z",
  "finished": "2017-10-30T16:10:57.077443322Z",
  "outputCommit": {
    "repo": {
      "name": "outputcommit"
    },
    "id": "3ab40acbb8c543ffa1b5ce4bc39898ec"
  },
  "state": "JOB_SUCCESS",
  "outputRepo": {
    "name": "outputrepo"
  },
  "outputBranch": "master",
  "dataProcessed": "25",
  "dataTotal": "25",
  "stats": {
    "downloadTime": "113.759952525s",
    "processTime": "7156.397069079s",
    "uploadTime": "28.758669872s",
    "downloadBytes": "1896638187",
    "uploadBytes": "25625050"
  },
`

Note that the sum of `downloadTime+processTime+uploadTime` does not match with the real total duration of the job, which can be deduced from the `started` and `finished` values. What seems to be happening is that the stats data is accumulating after reprocessing a pipeline using `update-pipeline --reprocess,` despite a separate independent job is created.

**Comment by dwhitena** [comment]
Interesting. Thanks for reporting @jonandernovella. @jdoliner thoughts here?

**Comment by jdoliner** [comment]
> `downloadTime+processTime+uploadTime` does not match with the real total duration of the job

They shouldn't match, a lot more goes into a job than download, process, upload. Other sources of latency are:

- waiting for k8s to schedule the pods
- master election of the pods
- reading and merging output trees
- network latency all over the place

Most of these things are hard to measure and will have very little meaning to users so we don't include more fine grained measurements of them.

**Comment by jonandernovella** [comment]
Solved. I was not aware about the parallelism. The total processing time in this case to the sum of all nodes.
