### ISSUE TITLE
Create a container for compiling protobuf

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#250]
This container should do exactly what `make proto` does today.  The advantage of using a container is that the user doesn't have to install the protoc tool chain, or risk using the wrong version of the tool chain (which seems to be what's happening in my case).

So `make proto` simply becomes:

```
docker run pachyderm/proto .
```

@sjezewski are you the best person to do this?

**Comment by sjezewski** [comment]
I like this idea a lot.

I'm happy to do it, though I think any of us could tackle it
