### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2502]
Similar to the description field for repos, users often request wanted to add a commit message to describe the data change they're making (e.g. deleting malformed file).

Branches are great for aliasing a commit so that it's reference-able by pachyderm commands, but this is just extra info for users who are looking at commits and trying to discern what data changes were made.

**Comment by dwhitena** [comment]
@JoeyZwicker I get this question and request soooooo frequently. I think it's pretty reasonable and natural for us to support commit messages for commits into Pachyderm data repositories. It has a ton of use cases as well that people like:

- Once you figure out provenance, you can quickly deduce the purpose/intent of the original changes.
- Makes actual collaboration of pipelines smoother in many ways
- Provides a nice changelog/history of changes to data, more so than a listing of commit ids
- etc...
