### ISSUE TITLE
Design: New Commit Invariants

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2505]
This is a follow-up to https://github.com/pachyderm/pachyderm/issues/2426. This design is a **work in progress**. Comments are very welcome.

# Background and Objective
The background and objective of this design are essentially the same as https://github.com/pachyderm/pachyderm/issues/2426. However, the product of our face-to-face discussions of that design is a revised design which I'm presenting here

# Data Structures
#### *Repo*s are losing their provenance, and *branch*es are gaining their own notion of provenance
- If a branch *B* is provenant on a branch *A*, then starting a commit in *A* will also start a commit in *B*.
  - This change essentially changes branches from "commit pointers" to "commit listeners".
  - It also solidifies Pachyderm's notion of "data provenance": if data in *B* can be derived from data in *A*, then new data in *A* implies new data in *B*.
- One consequence of this change is that branches may be empty (have no commits).
  - For example, after a user calls *CreatePipeline*, we'll create the pipeline's output branch, and make it provenant on the pipeline's input branches.
  - As soon as a user creates a new commit in an input branch, PFS will create a new commit in the output branch as well.
  - The output branch must exist to receive new commits, but until a new commit is made, the output branch will be empty.

#### *Commits* may have more states
- These commits are jobs' output commits. PPS will observe their creation, and then create corresponding PPS jobs to produce output data and close those commits
- If a PPS job fails, these commits will remain. PPS will indicate that these commits are the output of a failed job by leaving the `Tree` field of these commits empty

#### PPS *JobInfo* and *PipelineInfo* objects are being deprecated internally
  - *EtcdPipelineInfo* objects take the place of *PipelineInfo*s. An *EtcdPipelineInfo* is essentially a pointer into a PFS commit, which has all of the user-specified pipeline information (image, transform, etc). *EtcdPipelineInfo* will still record the pipeline's state, as that information is transient, and we don't want to attach changes in a pipeline's state to downstream PFS commits.
  - The user-specified portion of pipelines will live in in a dedicated PFS repo (the *PipelineInfo repo*). Every PPS pipeline will have a branch in this repo, and every pipeline's output branch will be provenant on a branch in the *PipelineInfo repo*.
  - By extension, every job's output commit will also be provenant on a commit in this repo. We'll replace *JobInfos* internally with *EtcdJobInfo*s, which are essentially pointers to an output commit in PFS.
  - *InspectJob* will reconstruct a job's JobInfo by retrieving the job's output commit, inspecting its provenance to find a commit in the *PipelineInfo repo* and retrieving pipeline details from there.
- We'll preserve the auth system's existing semantics. The *PipelineInfo repo* will be world-readable (so that *ListPipeline* still returns all pipelines in the DAG) and writable only by PPS (which will implement the same auth checks it implements today).

# Operations

### PFS
This change will make PFS provenance significantly more important. Branch provenance will inform the semantics of not only *FlushCommit*, but now also *StartCommit* and *DeleteCommit* (described below).

#### StartCommit
The main change introduced in this design is in StartCommit (in https://github.com/pachyderm/pachyderm/issues/2426 the change was to FinishCommit). Now, when PPS receives a *StartCommit(`Repo`, `Branch`)* message, PFS will create a single commit in every branch that is provenant on `Branch`. All of these commits will be created in a single etcd transaction, so that unlike in Pachyderm's current design, there is no possibility that PPS will drop a *watch* event and fail to trigger a pipeline

Note that PFS must create exactly one output commit in every downstream branch, even when there are multiple paths from `Branch` to `Branch'`. 

#### FlushCommit
Because we're replacing repo provenance with branch provenance, *FlushCommit* will accept a *commit* and a *branch* (really a `<repo>/<branch>` pair)

*FlushCommit*'s semantics become much simpler, however: *StartCommit(C)* starts a single commit in every downstream branch, so when PFS receives a *FlushCommit(C, downstream_branch)* request, there will be a single commit in *downstream_branch* that has '*C*' in its provenance. *FlushCommit* will either return the open commit or block on the commit closing and then return it.

#### DeleteCommit
Likewise, PFS is adding a new operation, *DeleteCommit(C)* that deletes all downstream commits provenant on '*C*'. As described later in this document, this will cause PPS to cancel any running jobs that process '*C*' or any of its downstream commits.

#### CreateBranch
- Currently, *SetBranch* accepts a commit and points a branch tag at that commit. In this change, *SetBranch* is being deprecated in favor of *CreateBranch*, which both creates new branches and modifies existing branches (similar to *CreatePipeline*). More importantly, because branches can now be empty, *CreateBranch* will have to accept, at least, a repo name, a branch name, and a *BranchInfo* specifying the branch's name and provenance. This call would allow the caller to
  - Create a new branch
  - Rename a branch
  - Remove a branch's provenance (for *UpdatePipeline*)

#### RunTransaction
PFS is adding support for transactions in this change. *CreatePipeline* needs this in order to finish a commit (in the pipeline branch), create a new branch in the pipeline's output repo, and rename the previous pipeline's branch in a single etcd transaction. This call accepts a collection of *StartCommit*/*FinishCommit*, *CreateRepo*, and *SetBranch* requests and transforms them into an etcd transaction, which it then sends to etcd.

#### ListJob
In PPS, every job has a corresponding commit in its pipeline's output repo. Therefore, rather than storing *JobInfo* messages in etcd, PPS will read the list of branches in its "pipelines" repo and call *ListCommit* on each pipeline's output repo. Finally, it will transform each CommitInfo into a JobInfo that it can display

#### CreatePipeline
- Create a new branch in the *pipelines* repo
- Create a new commit in this branch, containing the PipelineSpec
- Create a new output repo
- Create a new "master" branch in the output repo, with the inputs:
  1. the new commit in the *pipelines* repo
  2. all branches specified in the PipelineSpec

#### UpdatePipeline
- Create a new commit in the *pipelines* repo (in this pipeline's branch)
- In this pipeline's output repo, rename the "master" branch to e.g. "master.v1". Remove all of its branch inputs (but leave the input pointing to this branch's pipeline version in the *pipelines* repo)
- Create a new "master" branch in the pipeline's output repo, with the inputs:
  1. the new commit in the *pipelines* repo
  2. the branches specified in the PipelineSpec

Note that PPS creates a new branch regardless of whether the user set the `reprocess` bit in their *UpdatePipeline* request.
- Whether or not the user passed `reprocess`, PFS will create new output commits for the new pipeline
  - If the caller set the `reprocess` bit, then the new pipeline will have a new version, and PPS won't be able to re-use any cached output to populate the new output commits
- PPS must therefore recompute the pipeline's output using the new pipeline code
- If the caller didn't set the `reprocess` flag, PPS will be able to retrieved cached output for all of these jobs' input datums. The newly created jobs will finish quickly, and their contents will be the same as the old branch's commits

#### DeletePipeline
- Create an empty commit in *pipelines* repo, at the head of this pipeline's branch. When ListPipeline tries to read a PIpelineSpec from this pipeline's branch and fails, that will indicate that the pipeline has been deleted.

# PPS Job Triggers
One of the biggest changes in this rewrite is that PPS no longer traverses the pipeline DAG or calls *FlushCommit*. Instead, each pipeline watches its output repo. When PFS starts a new commit on the repo's *master* branch, the pipeline spawns a new job (the open commit created by PFS is the job's output commit)

PPS Jobs, in turn, follow this process to compute their output:
  1. The job will read its output commit's CommitInfo, extract its inputs, and watch each of those commits, respectively

  2. Once all of those commits are closed, the job will begin processing data from those commits

  3. The job's workers start claiming input datums. Concurrently, workers will watch the job's output commit (with *SubscribeCommit*). If the commit is moved off of the "master" branch or deleted, then the worker will cancel any in-progress processing and terminate

  4. Once the job has processed all datums from all input commits, it will close its output commit, which may trigger downstream jobs

This implementation has the benefit that a job's state is entirely encoded in the state of its output commit. If PPS restarts, it can simply scan the output repos of all of its pipelines, and if any of those repos have an open commit in its "master" branch, PPS can start a job and lose no state.

**Comment by jdoliner** [comment]
A couple of things I want to clarify / add.

- This implementation will have support for partial provenance. That is if you have a branch `C` with branches `A` and `B` as provenance you'll get a commit on `C` if there's a commit on `A` even if there's no commits yet on `B`. This is because if the inputs are `union` such a job can actually have output. If the inputs are `cross` the job will just output an empty commit. (Commit with no data, not a nil tree.)
- As part of this I'm going to rename `SetBranch` to `CreateBranch` to bring it inline with our other naming. This makes a little more sense now that you can create branches independent of commits.
- re: 3a, We can actually do a little bit better with this on cancellation. I think we can have the workers watch the output commit while the process and use that for cancellation so the moment a commit is deleted the jobs will get cancelled and the workers can move onto relevant work.

**Comment by msteffen** [comment]
Update: when you create, start, or update a pipeline, the pipeline will only process the head commits of its inputs (rather than trying to traverse the commit history of its inputs in a stable order). This is simpler, and hopefully more useful, as users may not be interested in the result of processing old data.

**Comment by msteffen** [comment]
Quick note from a design discussion:
- `--reprocess` is changing significantly
- Before, `--reprocess` meant "Copy master to a new branch, and run the new pipeline code on all old commits, and put the results in the new `master` branch
- Now, we're moving away from processing old commits. Instead, every time a user calls `UpdatePipeline`, we archive the `master` branch and then process only the `HEAD` commit of the new pipeline's inputs (this is whether or not the user passes `--reprocess`)
- If a user *does* pass `--reprocess` we change the pipeline's salt, meaning every datum is recomputed with the new code. If the user *does not* pass `--reprocess`, we'll re-use cached results from the old version of the code

- msteffen note: This is also philosophically consistent with another design idea we've had: Users can look at the results of a pipeline and mark them "bad" to remove them from the processed datum cache. Then if they update their pipeline, datums that were marked bad (and invalidated) will go through the new pipeline code. In general, both of these features are easy to explain in the context of a `computed results cache`, which, incidentally, is how Pachyderm actually works

**Comment by msteffen** [comment]
Another note from working on tests (as part of putting PipelineInfo in PFS):
- In this design, pipelines often have one more job than you expect
- The reason is that pipeline output repos are now provenant on pipeline "spec" repos
- If you create a pipeline with an input, then that'll create an output branch provenant on two other branches: the spec branch and then input branch. *Then*, CreatePipeline commits in the pipeline spec branch, which creates an open commit in the output branch. Starting this commit causes PPS to spawn a job, which immediately realizes it has no datums to process and finishes
- This is functionally equivalent to how Pachyderm works now—the only significance of this is that when you run `pachctl list-job` you often see one more job than you expect. This might confuse customers initially, so I'm noting it here so that hopefully we'll be aware of it

**Comment by jdoliner** [comment]
I wondering if we should try to figure out something to do about that. It seems just annoying / confusing enough that it might be an issue for people.

**Comment by JoeyZwicker** [comment]
+1 to JD's comment

**Comment by JoeyZwicker** [comment]
We've talked a fews times about the idea of having non-triggering input repos #2296). That's basically what we want here, right? No job to trigger when a commit is made to the pipeline_spec repo.

**Comment by msteffen** [comment]
Well, this is a design question, but we've talked about wanting to create a new commit e.g. when a user calls `UpdatePipeline` and there *are* input commits. Basically, the new pipeline would process their code at HEAD.

If we just didn't trigger on commits to the `spec` branch, then calling `UpdatePipeline` would have no effect until the next commit to an input branch

**Comment by msteffen** [comment]
Another design note: because commits now precede jobs, If a job fails, that job will have an output commit. If you try to read data from that output commit, the read will fail. This includes calling e.g. `pachctl get-file pipeline master /output/data` when the most recent job from `pipeline` failed (that `get-file` will return with something like `file /output/data not found in repo pipeline at commit abcd123456`)

**Comment by msteffen** [comment]
One other change: Previously, if a user called `update-pipeline --reprocess`, we would move the commits on e.g. `master` over to an archive branch, e.g. `master-v1`. After this change, we won't create an archive branch. Updating a pipeline will simply leave the pipeline's old output commits dangling (and generally inaccessible, except by extracting them from the provenance/subvenance of other commits)

**Comment by msteffen** [comment]
When working on this change, we initially implemented the decision to store PipelineInfos in PFS by storing them in a branch in their pipeline's output repo. Every output repo had a branch named `spec` with the PipelineInfo in it.

However, this decision interacted badly with Pachyderm's auth model. Currently, Pachyderm ACLs can only protect a repo. This means that if a user doesn't have at least `READER` access to a pipeline's output repo, they can't retrieve that pipeline's PipelineInfo. This means that *ListPipeline* won't be able to return most of a dag's pipelines to most of a cluster's users—a significant departure from Pachyderm's current semantics.

So, we're returning to our original design: PipelineInfos will live in a dedicated *PipelineInfos repo*. All users will be able to read the *PipelineInfos repo* (so that *ListPipeline* retains its old semantics), and only PPS (which has a master auth token) will be able to write to it. PPS will apply its existing auth criteria to UpdatePipeline, meaning that Pachyderm's current auth semantics will be able to persist.

**Comment by msteffen** [comment]
Potential future direction: PFS transactions
- Currently, PFS moves branches and propagates commits in *StartCommit*. This design has a few downsides:
  - Once a user calls *StartCommit(`R`, `B`)*, `B` points at an open commit
  - All downstream commits triggered by this call (and all future downstream commits triggered by future calls to *StartCommit*) point that that open commit.
  - Therefore no jobs can run until this commit closes, and if this commit is abandoned, all pending downstream jobs will fail.
  - For example, if a user has an open commit and are streaming logs into it, no jobs will run until that user calls *FinishCommit*, even if those jobs are triggered by commits to other repos:
```
[      ]
[ Logs ]
[  --  ] --.
[ Open ]    \
[Commit]     \
[      ]      \
               \__( P )__[ Output ]
               /
[          ]  /
[ Metadata ]-'
[          ]
```
Commits to `Metadata` will trigger jobs that won't be able to run until the commit to `Logs` is finished.

- This also has implications for `UpdatePipeline` in this design. Currently, when a user calls `UpdatePipeline`, PPS starts a PFS commit with the new pipeline info. If PPS can't finish this commit, not only will the pipeline never run any new jobs, downstream jobs also won't be able to run. The open commit locks PPS until it's closed or deleted.

An alternative solution may be to make open PFS commits stateful. Specifically:
- When I call `c := StartCommit(Repo, Branch)`, no downstream commits are created. The branch is associated with the open commit. When I call `FinishCommit(c)`, `Branch` is moved and downstream commits are created.
- If another user commits concurrently to other repos, downstream jobs will point at the `closed` commit at the head of `Branch`
- If I abandon my open commit, nothing is blocked
- If another user calls `StartCommit(Repo, Branch)`, and then finishes their commit before I finish mine, I will have to decide, when I call `FinishCommit`, if I want to append to their data or discard my commit.
- One way to think about this change is that it makes PFS more tolerant of concurrent operations. In addition to the job-blocking problem described above, consider this example:
  - I call `StartCommit("repo", "master")` and then fall asleep (I may be a process). Some else calls `StartCommit("repo", "master")`, receives an error ("commit already open"), and then says "oh, msteffen abandoned this commit" and calls `FinishCommit("repo", "master"); StartCommit("repo", "master")`. I then wake up and call `PutFile("repo", "master")`. I'm now writing into someone else's commit, with no way to know what happened.
  - Both of this example and the job-blocking problem are similar: with job-blocking, both I and another user are trying to "write" (i.e. pass data to) a downstream branch, and can't. In this example, both I and another user are trying to write to the same branch, and can't.
- In this model, commits are more like transactions in a traditional MVCC ACID database, which admit multiple concurrent writers and and fit with the PFS transactions described above (in fact, rather than having both PFS commits and PFS transactions, we may be able to combine these into a single concept)

**Comment by jdoliner** [comment]
Another small tweak to existing models was brought about by the new commit invariants design. We're removing the `DeleteJobs` and `DeleteRepo` options from `DeletePipeline` this is because, in the new model, some combinations of these flags won't make sense, for example `DeleteRepo:true` with `DeleteJobs:false` will leave the cluster in a bad state because the record for jobs is now partially stored in the repo that was just deleted due to `DeleteRepo:true`. This will manifest as `ListJob` failing.

I also think that it was a mistake to add so many knobs to `DeletePipeline`, I think it's much better to have it be simple and mean "delete everything." The only use case I can think of for partial deletions is that you want to still be able to access data and maybe job logs but don't want the pipeline to consume cluster resources. `StopPipeline` works quite well for that and has the advantage that it's not permanent so if you decide that actually you do want to run this pipeline again you can just `StartPipeline` whereas if you'd done `DeletePipeline` you'd have to recreate it which would reprocess everything from scratch.

**Comment by msteffen** [comment]
Another design note: We currently store pipeline metadata in a dedicated repo (currently just called `spec`). We chose to have a dedicated repo so that the PPS data model would work well with our auth model:
- all users are allowed to read from the `spec` repo, so that `PPS.ListPipeline()` can return information about all pipelines to all users, as it did before. If pipeline metadata were stored across several repos, users would have to get access to all of them for `PPS.ListPipeline()` to continue working this way.
- only admins are allowed to write to `spec`, so that almost all writes to `spec` have to go through `PPS`. This prevents users from accidentally putting PPS in an invalid state by writing directly to `spec` in an unexpected way and from circumventing PPS's existing authorization logic.

However, having a dedicated `spec` repo does interact badly with two other API calls: `PFS.DeleteAll()` and `Auth.Deactivate()`. Both of these delete all user data from etcd, but now PPS needs two pieces of data to exist at all times: the `spec` repo, and the `PPS` auth token (which it uses to write to the `spec` repo). To accommodate this, `PFS.DeleteAll()` has been modified to re-create the spec repo after deleting it, and the auth API no longer deletes capability tokens (which are held by pipelines) inside of `Auth.Deactivate()`.

The former means that `PFS` has some code that it only runs for the benefit of PPS (arguably a breach of abstraction) and `Auth` has a collection of data that is impossible to delete. Neither of these design decisions seem optimal to me; I think it would be better if Pachyderm had some kind of `initialize()` function that re-initialized a cluster after `DeleteAll()`. Then users could inject their own initialization code if they want to set up additional software inside of Pachyderm.

These changes are simple, though, and will let us get this project finished. I'm just making a note so we can revisit them later.

**Comment by jdoliner** [comment]
This has all been implemented, closing.
