### ISSUE TITLE
Broken link in Brew Install

### ISSUE THREAD

**Issue by amanderson** [pachyderm/pachyderm#2517]
Hello, the download URL appears to be broken in the brew install recipe. This is similar to a previously closed issue (#1134).

`$ brew tap pachyderm/tap
$ brew install pachyderm/tap/pachctl@1.6
==> Installing pachctl@1.6 from pachyderm/tap
==> Downloading https://github.com/pachyderm/pachyderm/releases/download/v1.6.4-no-gpu-01/pachctl_1.6.4-no-gpu-01_darwin_amd64.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pachctl@1.6"
Download failed: https://github.com/pachyderm/pachyderm/releases/download/v1.6.4-no-gpu-01/pachctl_1.6.4-no-gpu-01_darwin_amd64.zip`

Have I got that right?

**Comment by dwhitena** [comment]
Thanks for reporting this @amanderson! I think @JoeyZwicker is aware of this and looking into it. Can you confirm @JoeyZwicker?

**Comment by JoeyZwicker** [comment]
This should be fixed now. Sorry about that @amanderson. closing
