### ISSUE TITLE
Changelog is missing for 1.5.3+

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#2531]
There is no changelog for versions after 1.5.2 in https://github.com/pachyderm/pachyderm/blob/master/CHANGELOG.md
Please consider updating th changelog as part of the release management process.

**Comment by thedrow** [comment]
Also, the releases page is missing the changes for each release for 1.6.4 and 1.6.5.

**Comment by dwhitena** [comment]
@msteffen @sjezewski Does this have to do with some error we had for that release? Thanks for pointing this out @thedrow!

**Comment by jdoliner** [comment]
Just updated 1.6.5 on the release list. I don't think this was due to an error beyond human error. We just forgot to keep updating both the `CHANGELOG.md` when we wrote the changelog to the release page.

**Comment by sjezewski** [comment]
Seems fixed now
