### ISSUE TITLE
Docs for custom name spaces and node pools

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2537]
Need docs for people trying to utilize custom namespaces, as this question comes up quite a bit. Also, we need to specify any caveats (around upgrades, etc).

Node pools and instance groups might be another topic that would be good. For example, from users Slack this morning:

> I’ve setup a custom node-pool that has `storage-rw` and added the correct `affinity` and `tolerations` to the two deployments and one statefulservice that pachyderm wants to create and can now upload the test file from the tutorial. However when I try to create the edge detection pipeline the worker pod that pachyderm spawns doesn’t have the correct affinity or toleration and thus runs in the wrong nodepool. How do I supply the correct configuration so it can run in the right node-pool and thus have write access to the cloud storage bucket?
> ```
> $ kubectl -n test get pods  -o wide
> NAME                      READY     STATUS    RESTARTS   AGE       IP            NODE
> dash-69bfbf9f44-mzbls     2/2       Running   0          33m       10.4.6.3      gke-primary-pachyderm-test-03b3edf8-bc21
> etcd-0                    1/1       Running   0          40m       10.4.6.7      gke-primary-pachyderm-test-03b3edf8-bc21
> etcd-1                    1/1       Running   0          28m       10.4.5.6      gke-primary-pachyderm-test-03b3edf8-2q0c
> etcd-2                    1/1       Running   0          28m       10.4.5.7      gke-primary-pachyderm-test-03b3edf8-2q0c
> pachd-7b54f76d4c-s9ph4    1/1       Running   0          40m       10.4.6.2      gke-primary-pachyderm-test-03b3edf8-bc21
> pipeline-edges-v1-l429n   2/2       Running   0          3m        10.4.19.198   gke-primary-n1s8-100gb-b-059b6df3-gw4d
> ```

**Comment by atombender** [comment]
@dwhitena Your issue says this is about documentation, but does Pachyderm even support custom configuration so that you can add the necessary affinities to new pods?

**Comment by dwhitena** [comment]
@atombender Thanks for the clarification and comment. I guess this is under documentation right now, because we need to:

- Make sure what is and isn't supported in this regard,
- Be clear about that in the documentation

Then we can hopefully move on from there to expanding our support for these types of custom configuration.

**Comment by nitinjainsj** [comment]
Should already be fixed.
