### ISSUE TITLE
Deploy Pachyderm on AWS EKS Docs

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2550]
This should simplify our AWS deploy: https://aws.amazon.com/eks/

As discussed in users Slack:

> Ravi Rayapati [10:41 PM] 
> I’m not sure about SageMaker, but getting Pachyderm work with EKS-bakced K8s cluster would definitely help (edited)
> 
> [10:42] 
> https://aws.amazon.com/eks/
> Amazon Web Services, Inc.
> Amazon EKS - managed Kubernetes service
> Amazon EKS makes it easy for you to run Kubernetes on AWS without needing to install and operate your own Kubernetes clusters.
>  
> Joe Doliner [10:43 PM] 
> Ravi Rayapati definitely, that is very exciting news for all aws users
> 
> [10:43] 
> should substantially ease the process of deploying pachyderm on aws
> 
> Ravi Rayapati [10:45 PM] 
> jdoliner yes, agree. I’m very excited, I know how much I struggled to get K8s setup and deploy pachyderm on aws

**Comment by seamusabshere** [comment]
hey @dwhitena do you know of anybody doing this yet?

**Comment by JoeyZwicker** [comment]
We haven't seen much EKS in the while yet and are still putting together
standardized docs

**Comment by nikhilalmeida** [comment]
Hey Joey, Any updates on this?

**Comment by dwhitena** [comment]
@nikhilalmeida Still delayed here, as we are waiting on official preview access like many others. Hopefully we will be able to update this soon after we finish testing.

**Comment by itssimon** [comment]
Any updates? I'm looking at deploying Pachyderm on AWS EKS now and any guidance would be helpful.

**Comment by jgerber-suplari** [comment]
Any updates?

**Comment by jdoliner** [comment]
@jgerber-suplari none yet, although it seems that EKS is now generally available. Have you attempted to deploy on EKS, I imagine it should work out of the box given that it's just a Kubernetes endpoint that they provide.

**Comment by Nick-Harvey** [comment]
Just appending to this for when we tackle this. After working with a user in slack, when deploying Pachyderm on EKS, additional security group steps might need to be taken to "allow all communication between security groups for the cluster". I don't have specific steps from the user, but if you're able to resolve etcd from outside the cluster but `curl -v ... ` shows `connection timed out` error, allowing communication between security groups will fix it. 

Apologies for the lack of detail, it's all I was able to get from our slack conversation.

**Comment by svekars** [comment]
We have EKS docs here: https://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html. I might need to go through the instructions once again to see if anything needs to be added.

**Comment by chainlink** [comment]
Looks like we don't have EKS docs specifically, will coordinate with @svekars on adding em

**Comment by svekars** [comment]
#3939
