### ISSUE TITLE
Autogenerate doc/pachctl/pachctl.rst

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2559]
This file contains the table of contents for pachctl commands but isn't autogenerated so if you add a new command and forget to add it it the ToC then it won't be present on the docs site.

**Comment by JoeyZwicker** [comment]
I'll take another look at a solution for this -- manually updating the TOC is a pain.

**Comment by pappasilenus** [comment]
I've been doing research on what's wrong, but don't have a good way to fix it yet.  Can explain it to Svetlana and get it fixed.

**Comment by ysimonson** [comment]
The docs have been reworked such that this is no longer an issue. The newer version of this doc (`./doc/docs/master/reference/pachctl/pachctl.md`) doesn't contain an index, but an index is auto-generated in the doc's left pane.
