### ISSUE TITLE
Support S3 API to Pachyderm

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#257]
Support the S3 API so that users can request a file in Pachyderm the same way their code gets a file out of a non-pachyderm S3 bucket. 

Users often have code that is currently accessing data in S3. It's be nice for users to have that same code access data in Pachyderm, even though we chunk files, content address, etc. If the user requests `foo` through the S3 API, Pachyderm would just construct `foo` from the latest version on `master.` Basically, if you put Pachyderm on top of an S3 bucket, it should still offer all the functionality (and more of course) as a non-pachyderm bucket.

**Comment by gabrielgrant** [comment]
The directory structure should probably mirror that of the HTTP API (to be documented in #2660 )

**Comment by JoeyZwicker** [comment]
This feature is likely something we'll still need. Has been requested by users frequently and came up at Kubecon a few times.

**Comment by gabrielgrant** [comment]
work on this is finally underway in #3411  :tada:
