### ISSUE TITLE
Confusing "Local instalation" tutorial

### ISSUE THREAD

**Issue by olegserov** [pachyderm/pachyderm#2572]
I was going thru this http://pachyderm.readthedocs.io/en/latest/getting_started/local_installation.html and on the step `pachctl port-forward` I executed it. That command showed me ```Pachd port forwarded
Dash websocket port forwarded
Dash UI port forwarded, navigate to localhost:30080``` Then I proceeded to `http://localhost:30080/` and the dashboard crashed.
I've spent 60 minutes trying to figure out what is wrong. As it turns out, you don't get a dashboard during that local installation. You should add a warning about that into local installation or into the port forwarding message.

**Comment by dwhitena** [comment]
Thanks for reporting this, and I agree it is confusing. We are currently working on fixing this as tracked by https://github.com/pachyderm/pachyderm/issues/2444 and https://github.com/pachyderm/pachyderm/issues/1728. This should be fixed soon, but closing this as a duplicate.
