### ISSUE TITLE
./aws.sh does not work on Ubuntu

### ISSUE THREAD

**Issue by vijay120** [pachyderm/pachyderm#2573]
I am following these instructions:
```
curl -o aws.sh https://raw.githubusercontent.com/pachyderm/pachyderm/master/etc/deploy/aws.sh
chmod +x aws.sh
sudo -E ./aws.sh
```

However, when I run line 3 `sudo -E ./aws.sh`, I get this output without any other processing:
```
+ WHEEL='-\|/'
+ '[' 0 -ne 0 ']'
+ parse_flags ''
+ which aws
/usr/local/bin/aws
+ which jq
/usr/bin/jq
+ which uuid
```

Next, when I check for the resources, none exist:
```
vijay@dev-kubectl-000:~$ kubectl get all
No resources found.
```

**Comment by sjezewski** [comment]
Looks like you don't have `uuid` installed.

This issue is subsumed by [this one](https://github.com/pachyderm/pachyderm/issues/2457) which will make these lines more prescriptive for users.
