### ISSUE TITLE
Unable to commit a large commit.

### ISSUE THREAD

**Issue by olegserov** [pachyderm/pachyderm#2575]
I've added 210k files into the repo. 
It failed with message: `grpc: received message larger than max (67323059 vs. 20971520)`
I've executed `pachctl finish-commit <repo> <commit>`
it failed with the same message `grpc: received message larger than max (67323059 vs. 20971520)`

Looks like you need to adjust: "grpc.max_send_message_length" for grpc client.
Here is the same issues that has been solved using this method: 
https://github.com/grpc/grpc/issues/8098

**Comment by dwhitena** [comment]
@olegserov Can you provide information about your version of Pachyderm and Kubernetes. We recently updated certain commands to streaming to deal with this issue, so it could be a version thing. If not, we should definitely investigate what's happening here. Thanks in advance!

**Comment by olegserov** [comment]
I've used it locally just to upload the data into the repo. The version was the latest at that date. I've just finished the installation. Unfortunately, I don't have that version anymore.

**Comment by sjezewski** [comment]
I was able to reproduce this issue. I'm looking into it now.
