### ISSUE TITLE
Datum Status is incorrect

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2582]
The default value (0 value in the pb) corresponds to the failed state.

I thought this was working at some point on the UI, but now it is certainly not.

<img width="320" alt="screen shot 2017-12-14 at 3 35 16 pm" src="https://user-images.githubusercontent.com/597953/34017591-355cfa96-e0db-11e7-86c4-d45c1756ec66.png">

<img width="298" alt="screen shot 2017-12-14 at 3 35 30 pm" src="https://user-images.githubusercontent.com/597953/34017582-2f0b45c6-e0db-11e7-97f6-a5d90ca56202.png">

The pending datums are reported as failed, and the # of 'failed' datums decreases.

**Comment by gabrielgrant** [comment]
Interesting. Yea, I though that at some point this was working, but it's not clear how. I see some dashboard code that handles a synthetic `queued` state, but looking at it again, I'm not sure how I, as a client, should be distinguishing between actually-failed datums, and these incomplete datums. Should these be returned in [the `STARTING` state](https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.proto#L131)? Should there be a different `pending` state? Or is there some other field i should be looking at to make the distinction?
