### ISSUE TITLE
Reconsider etcd resource requests?

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2589]
Got this input from a user. Not sure if we have already gone through some analysis @jdoliner or @msteffen to determine a proper default for `etcd`?

> User [10:12 AM] 
> I’m wondering if it is the resource requests for the etcd pods
> 
> [10:12] 
> each requests 1 full CPU
> 
> [10:14] 
> that seems excessive
> 
> [10:15] 
> for example, the etcd servers that are part of k8s (in the kube-system namespace) only request 200m CPU

**Comment by JoeyZwicker** [comment]
I think reducing etcd nodes to 1 will mostly solve this. We leverage etcd heavily and reducing CPU and this will only be a problem for scheduling purposes so I think we're ok to leave as is for now. @jdoliner do you think otherwise?

**Comment by jdoliner** [comment]
I don't see much point in lowering it since it's a request and not a limit it shouldn't have any impact scheduling wise. And we use etcd very heavily so having a full cpu for it can meaningfully improve performance.
