### ISSUE TITLE
Expand pachctl to expose logs from failed jobs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#259]
Currently, there's no easy way to see logs from a failed job.

**Comment by jdoliner** [comment]
This should probably be implemented a little bit deeper than Pachctl.
It seems like we're going to need to make a few requests to kubernetes `PodInterface`
First the list the pods which are part of the job and then a series of calls to `Logs` to get logs from them.

https://godoc.org/k8s.io/kubernetes/pkg/client/unversioned#PodInterface

**Comment by jdoliner** [comment]
You can now see logs from any job (failed, running or succesful) using `pachctl get-logs`.
