### ISSUE TITLE
Document githook nodeport for advanced usage

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2597]
We left the nodeport open/defined for the githook service to enable the following workflows:

1) debugging anything related to githook server
2) running pipelines w git inputs locally (and configuring the githook server to work using ngrok)
3) running pipelines on an on premise installation (so that it's up to them to define a hostname / setup access to their git solution, which may also be on prem)

Those last two are advanced use cases, but some we may want to support. This issue is a reminder to document these cases.

**Comment by mindthevirt** [comment]
Githook will be deprecated in favor of build pipelines.
