### ISSUE TITLE
Only run specific jobs with commit?run

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#26]
right now, /commit?run will run all jobs in that branch. Instead, you should be able to pass an optional argument to only run specific jobs. This is particularly useful when you're developing a job and want to test it. It'd be nice to only run that job and its dependencies instead of the entire DAG. 

Proposed API:
all jobs: /commit?run
single job: /commit?run=job1
multiple jobs: /commit?run=jobs&run=job2

**Comment by JoeyZwicker** [comment]
This issue is going to snowball into a much bigger API for specifying pipeline priority levels, SLAs, and general order of execution primitives. There's no exact timeline for this feature, but it's something that many enterprise customers are going to need long-term.

**Comment by jdoliner** [comment]
No longer applicable with the new pfs/pps.
