### ISSUE TITLE
Fix protofix

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#261]
Protofix doesn't seem to work correctly during the make invocation.
Fixing it adds a bit of time to each `make proto` invocation which gets tedious during development.

**Comment by derekchiang** [comment]
Related #250

**Comment by derekchiang** [comment]
The solution in #268 works if your docker daemon runs locally, ant not otherwise.

**Comment by derekchiang** [comment]
Fixed in #316
