### ISSUE TITLE
One Shot Demo Cluster Deployment

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2612]
## Goal

Have an easily deployable cluster that we can use for demos as a sales tool

## Requirements

- It should be easy (scripted) to deploy and tear down this cluster
- It should use Digital Ocean (where we have credits)
- The UI should be accessible via a custom domain (e.g. `acme-company.beta.pachyderm.io`)
- We should have a way to share the k8s credentials so that users can easily connect and use the cluster

This will be a valuable first step in building our MVP for our hosted solution.

---

## Scoping

There are 3 components to build here.

### 1) Digital Ocean Deployment

- validate we have sufficient credits on DO
- do a manual deployment on DO
- automate the DO deployment
    - it appears [kops doesn't support DO yet](https://github.com/kubernetes/kops/issues/2150)
- do a manual tear down
- automate the DO teardown

### 2) Sharing k8s credentials

- Should be output by the deployment script
- It would be nice to have a readme alongside the credentials? Or perhaps a page on the docs site?

### 3) Custom DNS Provisioning

There are 2 steps here. Exposing the service, and setting up custom DNS so we can serve traffic at something like `acme-company.beta.pachyderm.io`

A) Exposing the Service

Our options here are either:

1) use k8s `LoadBalancer` primitive on each of the services we need to expose (UI port, webhook port, get file port, pachd port)
2) use a reverse proxy to handle exposing all the services/ports at once behind a single port. [We'd probably use traefik](https://github.com/containous/traefik)

B) Setting up custom DNS

Our options here are either:

1) use the public IP from the service exposed via a k8s `LoadBalancer` and update our DNS records on route53 to point a custom subdomain to that IP
2) setup the 'pachyderm ngrok' (as @gabrielgrant has previously described)
    - we could have the reverse proxy dial out to register w this service, which would in turn host traffic on a public custom subdomain and route that to the cluster
    - we could also use the reverse proxy + a k8s `LoadBalancer` and register that IP w this service

---

Open Questions:

- does DO support the k8s `LoadBalancer` type?
    - I suspect the answer is no
    - if not, we can provision / configure those things as part of our script ... or
    - it may be easier to use the 'pachyderm ngrok' solution listed above
- Can we run ngrok / host it ourselves? Or would this be something we'd have to write ourselves?

---
# Roadmap

## Iteration 0

Basic version that allows us to easily spin up a cluster

- Figure out how to support DO's obj store (or deploy minio + xxx on DO)
- Implement the scripted deployments to DO
- Update deploy script to emit k8s credentials + document usage for users

## Iteration 1

Allows us to easily share a cluster

- Figure out if DO supports k8s `LoadBalancers`
- If not, figure out how to script deploying the analogous DO service
- Use simple load balancers + a script to update route53 to provide custom domain names

## Iteration 2

Simplifies and unifies how we expose service outside the cluster

- Instead of using a load balancer per port (UI, websocket, get file, pachd), use a reverse proxy like traefik
- Make sure UI knows how to use / update paths accordingly (e.g. websocket, get file server)
- Make sure pachctl knows how to use a domain w a path in it, e.g. `1234.pachyderm.io:333/pachd`

**Comment by ysimonson** [comment]
Progress has been made on this, but this ticket is very outdated regarding implementation. Closing.
