### ISSUE TITLE
RBAC errors using the one shot deploy script

### ISSUE THREAD

**Issue by mightyguava** [pachyderm/pachyderm#2619]
I'm trying to use the one shot deploy script at http://pachyderm.readthedocs.io/en/stable/deployment/amazon_web_services.html#one-shot-script

Kubernetes deployed just fine, but the script failed at the step

`pachctl deploy <...> us-east-1 100 --dynamic-etcd-nodes=1 --credentials=<...>`

I'm pretty new to Kubernetes. I think some role needs to be added...? Don't know how

```
serviceaccount "pachyderm" created
storageclass "etcd-storage-class" created
service "etcd-headless" created
statefulset "etcd" created
service "etcd" created
service "pachd" created
deployment "pachd" created
secret "pachyderm-storage-secret" created
Error from server (BadRequest): error when creating "STDIN": ClusterRole in version "v1" cannot be handled as a ClusterRole: no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1"
Error from server (BadRequest): error when creating "STDIN": ClusterRoleBinding in version "v1" cannot be handled as a ClusterRoleBinding: no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1"
kubectl create -f - --validate=false: exit status 1
Error from server (BadRequest): error when creating "STDIN": ClusterRole in version "v1" cannot be handled as a ClusterRole: no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1"
Error from server (BadRequest): error when creating "STDIN": ClusterRoleBinding in version "v1" cannot be handled as a ClusterRoleBinding: no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1"
```

Tool versions:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
> kops version
Version 1.8.0
> pachctl version
COMPONENT           VERSION
pachctl             1.6.7
```

**Comment by JoeyZwicker** [comment]
Hi @mightyguava Sorry you're hitting this. We just added rbac support in yesterday's release and it looks like that wasn't updated in the one-shot deploy script. We'll get that fixed for you shortly.

**Comment by jdoliner** [comment]
This is actually just a version issue, you can fix it by bumping the k8s version you're using to 1.8.0 in the script. The linked PR above should give you an idea how to do that, it's pretty simple. Or you can wait for us to merge it which should be in a few hours.

You also could not use the one shot script at all since I believe AWS now has first class support for kubernetes I think that's a better way to deploy than this script.

**Comment by mightyguava** [comment]
Oh wow, I wasn't expecting a reply so quickly. @jdoliner applying the version changes worked for me!

**Comment by jdoliner** [comment]
@mightyguava glad that worked, par has been merged as well so one shot script in master should work out of the box.

Closing, feel free to reopen if there's further issues.
