### ISSUE TITLE
parent commit has not been finished.

### ISSUE THREAD

**Issue by raja1212** [pachyderm/pachyderm#2621]
I am working on the Distributed Hyperparameter Tuning example (https://github.com/pachyderm/pachyderm/tree/master/doc/examples/ml/hyperparameter), and I got stuck while adding some file to 'parameters' repository.

![image](https://user-images.githubusercontent.com/29933077/34910202-65ae1526-f8b0-11e7-8bfe-5f4428bbf3ec.png)

I tried using pachctl commit option, but it didn't work. It will be helpful if someone can suggest how to remove this error.

**Comment by JoeyZwicker** [comment]
Hi @raja1212.

the `-c` flag starts a commit, puts the files, and finishes the commit. It looks like you already have a commit started so there are a few easy options based on what you want to do. 

1. You can finished the commit that's already started which may or may not have files in it already. `finish-commit parameters master`
2. If you havent already added the parameters file, just take out the -c flag in the command you're using above and then call finish-commit as I mentioned in #1. 

To see the current state of commits and files you can run these commands:
`list-commit parameters` -- this will show you start and finish times to see which commits are open.
`list-file parameters master` will show you what files are in your HEAD commit right now so you can decide what you want to add. 

You can also ask questions like this in our slack channel if you want quick feedback/help: slack.pachyderm.io

**Comment by raja1212** [comment]
yes... it's working. Thanks a lot!
