### ISSUE TITLE
Globbing in file commands

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#2631]
It would be useful to support globbing in certain commands that perform file operations. Having this would address #2607, and would be more consistent with the way hdfs works. I am kind of interested in working on this, but I wanted to get some opinions on this before I started looking into it.

**Comment by dwhitena** [comment]
Thanks for the suggestions @brycemcanally. Any opinions on this @jdoliner or @msteffen?

**Comment by jdoliner** [comment]
Being able to delete files based on a glob pattern would definitely be a nice feature. I think glob support should eventually exist for `delete-file` and `get-file` in addition to `list-file` which is already support via `glob-file`. The more interesting question is how we unify this syntax. We could have `glob-file` become `list-file-glob` and add `delete-file-glob` and `get-file-glob` that seems kinda lame though. I think a better idea might be to change those commands to have a `-g` flag that you can pass a glob too. We could also try to do some sort of magical detection on if the path being passed to `*-file` is a glob or a normal path... but that seems like it could be a little difficult and too magical.

**Comment by brycemcanally** [comment]
Maybe I am overlooking something, but why would you not just treat the file name as if it were a glob and use the glob-file functionality then process the original command with the returned file infos? The performance overhead for a non-glob should be minimal, and this would be much more familiar to hadoop and unix/linux users.

**Comment by jdoliner** [comment]
Treating the filename as a glob pattern by default is tempting but has some issues.

- It's ambiguous, if I have a file called `*` then I can't get that file without getting all the other files in the directory.
- There is a very real performance overhead here. Glob patterns are predicates over filepaths, so evaluating them requires a linear scan. We could try to do something smart like detect when something is or isn't a glob pattern but that gets complicated.

All that being said, there is something very appealing about being able to just type `pachctl get-file foo master dir/*` and have it just work, so if we can figure out a way to get this to work I think we should do it.

**Comment by brycemcanally** [comment]
As far as the first point is concerned, the globbing library you guys are using supports escape sequences for those special characters so that information could just be forwarded to the users.

As far as the second point is concerned, I guess I was just thinking about use cases with less than 10 million files. It looks like your globbing on the backend is just running the match on the keys in the fs map, which I could simulate using the globbing library you guys are using. When I did this on 100000 filenames with greater than 50 characters, it took less than 10ms for an exact name, which would mean that this should be less than a second for under 10 million files. I do agree that this is not a great solution, especially for large numbers of files, and it would be better to do some sort of check if the path is a glob first. There is a small javascript library (https://github.com/micromatch/is-glob) that does this very thing, and could probably be transliterated to meet this use case.

**Comment by jdoliner** [comment]
Good points both. I'm convinced, getting an equivalent to `is-glob` shouldn't be too difficult. It looks like it mostly just applies the fairly trivial regex: `/\\(.)|(^!|\*|[\].+)]\?|\[[^\\\]]+\]|\{[^\\}]+\}|\(\?[:!=][^\\)]+\)|\([^|]+\|[^\\)]+\))/`
