### ISSUE TITLE
Instructions how to delete cluster created with AWS one-shot deploy script

### ISSUE THREAD

**Issue by dionjwa** [pachyderm/pachyderm#2638]
http://pachyderm.readthedocs.io/en/latest/deployment/amazon_web_services.html

There are no instructions how to delete this test cluster. I have very basic familiarity with kops+pachyderm+kubernetes etc, so I started the one-shot deploy cluster, but now I need it gone, and I'm left guessing that hopefully there won't by any infrastructure left costing me money.

Perhaps expose this with a kops command?

**Comment by jdoliner** [comment]
`kops delete cluster` should do what you want
