### ISSUE TITLE
[1.6.7] Jobs don't get triggered using Helm Chart

### ISSUE THREAD

**Issue by jonandernovella** [pachyderm/pachyderm#2647]
Pipeline pods don't seem to get scheduled unless i create a pipeline before I push data into a repo.

Steps to repro:

1) `helm install --name my-releasee stable/pachyderm` (This deploys the 1.6.7 pachyderm daemon)
2) `pachctl -k '-n=default' port-forward &`
3) `pachctl create-repo images`
4) `pachctl put-file images master liberty.png -c -f http://imgur.com/46Q8nDz.png`
5) `pachctl create-pipeline -f https://raw.githubusercontent.com/pachyderm/pachyderm/master/doc/examples/opencv/edges.json`

I looked a bit into the manifest changes of 1.6.7, and discovered that `CluresRole` and `ClusterRoleBindings` were added. Might this be the source of the issue? Link to chart: https://github.com/kubernetes/charts/tree/master/stable/pachyderm/templates

**Comment by jdoliner** [comment]
So is the issue here that with those steps you wind up with no pipeline pods at all? Do you have a pipeline `rc`? I can't think of any reason why this would work if you create the pipeline before the data but not the other way around.

**Comment by jonandernovella** [comment]
@jdoliner Logs from the pipeline-rc: `Error creating: pods "pipeline-edges-v1-" is forbidden: service account default/pachyderm was not found, retry after the service account is created` 

I assume that the `ServiceAccount` name is hardcoded to Pachyderm. If this cannot be changed I should also hardcode it on the chart. What do you suggest?

**Comment by jonandernovella** [comment]
@jdoliner Users are actually encouraged to deploy Pachyderm with the Helm chart on a custom namespace. I assume that the `rc` is looking for it on the `default ns`. That might also be an issue.

**Comment by jdoliner** [comment]
I'm pretty sure this is safe to close, people have been using the helm chart for a while and while it has some issues I don't think it has any as glaring as just flat out not triggering jobs, I assume we'd have heard about it if it did.
