### ISSUE TITLE
Document Terraform k8s deployment / advanced deployment

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2649]
We had a customer w the following requirements:

- deploy on AWS
- deploy to an existing DNS hosted zone, VPC ID, and subnets (across amz regions)
- use terraform to manage deployment manifests

We provided instructions on how to generate a TF manifest for k8s deployment meeting these criteria. From there, deploying pachyderm is straightforward. However, ideally we bake the pachyderm's k8s json manifest into TF as well using the TF k8s plugin.

**Comment by dionjwa** [comment]
I could really use a terraform based pachyderm deploy config.

**Comment by gkumar7** [comment]
Deployment of pachyderm using terraform k8s provider: https://github.com/gkumar7/pachyderm-terraform
Hope this helps!

**Comment by thedrow** [comment]
If we had #1068 we could use https://github.com/mcuadros/terraform-provider-helm.

**Comment by JoeyZwicker** [comment]
@thedrow we have a pachyderm helm chart now: https://github.com/kubernetes/charts/tree/master/stable/pachyderm

**Comment by thedrow** [comment]
In that case, please deprecate all other deployment methods and migrate to using the Helm chart + Terraform.
Helm is not a huge dependency to introduce and most if not all k8s clusters already have it installed.
Terraform is used in nearly every DevOps shop. You do not have to require it to deploy Pachyderm but recommending it is a good idea.
Also, it will concentrate our efforts to play nicely with the entire k8s ecosystem.

**Comment by JoeyZwicker** [comment]
That's the plan in the near future.

**Comment by mindthevirt** [comment]
Our helm chart is the new way of deploying Pachyderm which can be integrated with Terraform by the users.
