### ISSUE TITLE
Make block size configurable

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#265]
Currently it's hardcoded as 8MB.

**Comment by sjezewski** [comment]
We kind of have this as a result of the 'no-delimiter' support via `PutFile()` --- if you're putting binary data you implicitly also set the block size. 

But I assume you want this set independently of delimiter type.

**Comment by sjezewski** [comment]
Haven't heard a request for this in a long time. Now that we have files as our finest granularity over blocks I think this is no longer meaningful
