### ISSUE TITLE
Link to Example Guide can not be accessed

### ISSUE THREAD

**Issue by hsaputra** [pachyderm/pachyderm#266]
Looks like the page:
https://github.com/pachyderm/pachyderm/blob/master/examples/grep/GUIDE.md#setup
return 404

Probably have set private mode.

**Comment by JoeyZwicker** [comment]
It's been moved to https://github.com/pachyderm/pachyderm/blob/master/examples/fruit_stand/GUIDE.md

Where did you see the incorrect link?

**Comment by hsaputra** [comment]
It is from "Deploying Pachyderm." link in the README.md file

**Comment by JoeyZwicker** [comment]
Fixed. Thanks @hsaputra
