### ISSUE TITLE
Docs for HTTP interface to PFS

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2660]
Files in PFS can be accessed via `http://127.0.0.1:30652/v1/pfs/repos/<some-repo-name>/commits/<some-commit>/files/<path/to/some/file>` (where `<some-commit>` is either a commit ID or a branch)

I don't think this is documented anywhere, but probably should be.

Added in #2043 though more useful if/when #2062 is implemented

**Comment by ysimonson** [comment]
I think we should _not_ write docs for this, because this service is intended to be for internal use with the dash. For external use of PFS via HTTP, s3gateway is available.

**Comment by gabrielgrant** [comment]
Generally agreed, again, unless we actually follow through with a full HTTP API to Pach's APIs, which has been low-key on the roadmap for at least three years :P

**Comment by ysimonson** [comment]
The long-term goal is to phase out this service (#3791), so closing this out
