### ISSUE TITLE
Vault Plugin

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2662]
This is a requirement for pachyderm to be used by a client. They have a requirement for no credentials stored at rest. Their applications need to access Pachyderm w temporary tokens.

More info on vault plugins found here:

https://www.vaultproject.io/docs/internals/plugins.html

**Comment by sjezewski** [comment]
The ask here is creating the vault plugin that will call the right pachyderm auth API calls to allow vault to login/renew user's pachyderm tokens.

I have their example working, but it's a bit unclear exactly how we would expect users to provide the necessary admin token. I'm going to reach out to hashicorp and ask / read more on this.

**Comment by sjezewski** [comment]
The actual Pachyderm auth API updates are captured in #2700

**Comment by msteffen** [comment]
Closing due to staleness

**Comment by gabrielgrant** [comment]
@msteffen this has been completed, no?
