### ISSUE TITLE
Start job time sometimes incorrect after update-pipeline

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2665]
I have noticed on minikube that `pachctl update-pipeline` will occasionally start jobs with a STARTED in the past, e.g.
```
c88ebd0d-b644-4493-9472-3912c6c6903c pipe/-   13 minutes ago -                  0       0 + 0 / 8   0B       0B       running
```
In this case, 13 minutes ago was actually a few seconds

**Comment by ysimonson** [comment]
I'm not sure if this is fixable; it's presumably due to clock drift in the minikube VM

**Comment by JoeyZwicker** [comment]
As long as its a minikube or `deploy local` problem only, I'm not worried about it.
