### ISSUE TITLE
pachctl edit-pipeline

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2683]
This would be real darn handy when administrating a pachyderm cluster. (I wanted this several times in the last few days when working w a customer).

It's analogous to `kubectl edit ...`

Based on @jdoliner 's migration PR, we have the ability to inspect a pipeline and generate a create pipeline request from that, which is a fair bit of the work here.

**Comment by ysimonson** [comment]
This is supported now (not sure when it was added.)
