### ISSUE TITLE
reported size from pachctl list-repo is inconsistent in sharded environment

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#269]
When running multiple pachd instances the sizes reported by pachd tend to be inconsistent, jumping around in value. Even after being given time to reach equilibrium it still gives cycling values. I suspect it is reporting the portion of the repo which is known to each seperate instance of pachd and kubernetes is rotating between them.

**Comment by jdoliner** [comment]
@JonathanFraser I think your diagnosis is correct. Will investigate and report back.
