### ISSUE TITLE
Design: Pachyderm Robot User Tokens

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2700]
# Background
Storing credentials on disk is risky—the more auth credentials that an organization has stored on disk, the more opportunities there are for an attacker to impersonate an internal entity and potentially escalate their privileges. To avoid the proliferation of machine-user credentials stored on disk, some users want to centralize their credential management. This would be used like so:

1. An entity (U) wants to use Pachyderm, so they ask the credential system (CredSys) for a Pachyderm Token
2. CredSys asks Pachyderm for a temporary token (T) that authenticates U
3. CredSys returns T to U
4. U sends a request to Pachyderm, with the associated credential T
5. Pachyderm authenticates and authorizes U via T and handles their request
6. some time later (e.g. 1 minute) CredSys revokes T, so any attacker that has stolen it can't use it to impersonate U

# Objective
Make this workflow possible, by adding the requisite APIs to Pachyderm

# Data Structures
* No new data structures will need to be added to Pachyderm as part of this change
* In particular, we do not need to add a users table to Pachyerm yet
* However a new type of user may begin appearing on Pachyderm ACLs: **Robot Users**
* The only way to authenticate as a *Robo User* is for an cluster admin to generate a temporary token authenticating that user, and to then present that token in a Pachyderm RPC
* Robot users will be distinguished from Github users within Pachyderm ACLs by prepending "robot:" to user strings that mention them in the proto
  * In Pachyderm ACLs, Github users already have the prefix "github:"

# Interface
We'll modify the Pachyderm interface in two ways:
1. We'll expose Pachyderm's `GetCapability` API via the Pachyderm client. We'll also add a `user` argument
    * The current API is `GetCapability()` which, which called by *U*, returns a token that allows the caller to authenticate as *U*
    * Now, an admin may call `GetCapability(U)` to get a token that authenticates any token bearer as *U*, even if the admin making the call isn't *U*.
    * Users may still call `GetCapability(U)` but their call will be rejected if the argument is any user other than themselves
2. We'll expose Pachyderm's `RevokeCapability(T)` API via the client
    * This will let CredSys revoke a manufactured token at the appropriate interval after passing it to a subsystem

# Project Tracking
https://github.com/pachyderm/pachyderm/projects/1

**Comment by msteffen** [comment]
Update: Because we have two user types now, (github users and Pachyderm robots) Pachyderm's API will now insist that all usernames are preceeded by either 'github:' or 'pachyderm_robot:' to disambiguate usernames

**Comment by msteffen** [comment]
Second update: I also need to change how PPS gets capability tokens for its pipelines, as exposing `GetCapability()` means that that call semantics can't give out god tokens to pipelines before auth is activated

**Comment by msteffen** [comment]
**Update**: To avoid incompatibility with the dash, we're making the following changes to the auth API (which are partially visible):
* (Set|Get)(Scope|ACL) check the `Username` field in requests. If `Username` contains **no ":"** then it's assumed to refer to a GitHub user. If it contains the prefix `robot:` then it's assumed to refer to a Pachyderm robot. Any other form of request is an error

* GetAclResponse is gaining a new field: `RobotEntries`. This is a `map<string,Scope>`, and all keys in the map are robot principals on `GetAclRequest.Repo`'s ACL. The existing field, `GetACLResponse.Entries` will only contain GitHub user principals. This means that the dash won't encounter any unexpected prefixes, but also won't display the robot users on a repo's ACL.

This is an insecure design (as any user relying on the dash won't even know that a given robot user has access to a repo), so we should evaluate if it's absolutely necessary, but it will not break the dash

**Comment by msteffen** [comment]
Note: Pachyderm auth allows tokens retrieved from GetAuthToken to be used after a user's enterprise license has expired (to avoid an expired token sending all of the user's pipelines into a crash loop). Because robot tokens will also be retrieved via `GetAuthToken`, those auth tokens will also be valid after a user's enterprise license has expired (the user still won't be able to mint new robot tokens. Only existing tokens keep working)

**Comment by msteffen** [comment]
**Note**: As part of this design, we also need to be returning tokens (from `GetAuthToken`) that expire.
* In general, when vault authorizes a user to talk to Pachyderm and generates an Pachyderm token for them, that Pachyderm token should be short-lived. This will be a new feature of `GetAuthToken`
* As well, vault must be able to extend the lifetime of tokens that it has issued (on behalf of clients that are still using them). To support this, I'm adding a call `ExtendAuthToken` that **only admins can call**. It takes a short-lived token and new TTL for that token, and extends the lifetime of the token with the new TTL

**Comment by gabrielgrant** [comment]
@msteffen We've shipped (and have people using) a version of Robot Users as of a while ago. Is this all implemented? What's left to do? Is this documented? (if not, possibly something to add to @Nick-Harvey 's todo list?)

**Comment by msteffen** [comment]
Yeah, I'm happy to close this. The only part that isn't done is the users table, and the compromise we arrived at, which at this point is built into the code in a few places, is that a username with no prefix is assumed to be a GitHub user, while a username with a `robot:` or `pipeline:` prefix is assumed to be one of those

**Comment by gabrielgrant** [comment]
Should we open a new issue about a users table? or are we no longer intending to implement that?
