### ISSUE TITLE
When a commit is deleted, list-job fails because commit doesn't exist. 

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2704]

**Comment by msteffen** [comment]
Per in-person discussion:
* ListCommit will detect errors due to deleted output commits, and 
    1. Delete the dangling EtcdJobInfos in a separate goroutine
    2. Not return those jobs to the user (avoiding a breakdown of list-job)
* Stats commits (and stats branches) will be provenant on their pipeline's output branch

**Comment by jdoliner** [comment]
Fixed by #2719
