### ISSUE TITLE
Set the maximum number of retries for a job on a pipeline basis

### ISSUE THREAD

**Issue by hchauvin** [pachyderm/pachyderm#2723]
**What is the ask?**

Set the maximum number of retries for a job on a pipeline basis.

**What is the goal / desired outcome?**

Set this retry number to 1 so that the job is not retried.  The problem is that if you have a human error on a job that takes 3 hours to complete, you don't want to wait 9 hours to see that error. 

**If there is a way to accomplish this today via workaround, what does that require?**

No workaround, the value is hard coded to 3 in src/server/worker/api_server.go.

----

To do this, I propose to add a new int32 field on CreatePipelineRequest and PipelineInfo named max_retries.  If negative or 0, defaults to 3; otherwise, this is the maximum number of retries.

**Comment by dwhitena** [comment]
Thanks @hchauvin.

@jdoliner has we considered making the number of retries configurable? I remember someone else asking me about this recently as well.

**Comment by jdoliner** [comment]
Hey @hchauvin, thanks for a very clear and concise feature request. We can definitely do this. I have a few minor tweaks to your proposal: I think it makes more sense to let people set the number of "tries" than the number of "retries", the reason being that we want to use `0`, the unset value, to indicate the default value of `3`. However if you're setting "retries" then `0` would also be the way to indicate "don't retry this" which is your original ask. If you're setting "tries" though then `1` try is the behavior you're looking for, and `0` tries is meaningless so we can use that as the default. We should be able to get this in for an earlier 1.7.x release.

**Comment by hchauvin** [comment]
Thank you for that @jdoliner!  Yes, number of tries was actually what I had in mind.

**Comment by gabrielgrant** [comment]
It seems other products often have a "retry policy" which is both a number of times to retry, and a delay to wait between attempts (if we're assuming a retried job may succeed, then that presumably means the cause of the error was something transient, which would take some non-zero amount of time to correct itself)

eg:

![screenshot from 2018-03-08 09 35 20](https://user-images.githubusercontent.com/493968/37166661-79322046-22b4-11e8-980d-dd523fc7a69f.png)
