### ISSUE TITLE
Pachctl: --raw is not processed consistently

### ISSUE THREAD

**Issue by hchauvin** [pachyderm/pachyderm#2727]
**What happened?**: When doing pachctl glob-file --raw or some other commands, both the raw and the pretty form are printed.

**What you expected to happen?**: Only the raw JSON to be printed, as with pachctl inspect-pipeline --raw.  In general, --raw is dealt with inconsistently, and other commands are concerned.

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.6.8               
pachd               1.6.8
(But should be a problem at HEAD as well)
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by dwhitena** [comment]
Thanks for the details here @hchauvin. I would have expected just the JSON to be printed as well, which I think is what happens when `--raw` is called on `get-logs`. @jdoliner or @msteffen maybe there is a bit of inconsistency here?
