### ISSUE TITLE
'%' stdout/stderr gets regurgitated as '%!!(MISSING)' etc. in the logs

### ISSUE THREAD

**Issue by hchauvin** [pachyderm/pachyderm#2729]
**What happened?**: If the user process outputs '%' to stdout or stderr, it gets regurgitated as '%!!(MISSING)' etc. depending on the surrounding characters, meaning that fmt.Sprintf is called on the stdout/stderr output.

**What you expected to happen?**: '%' recorded as is.

**How to reproduce it (as minimally and precisely as possible)?**: 

**Anything else we need to know?**: it is due as far as I can tell by taggedLogger.Logf being called by taggedLogger.Write in src/server/worker/api_server.go and not the other way around.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.6.8 server/client
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by dwhitena** [comment]
Thanks for reporting @hchauvin. We will look into this. @msteffen any initial ideas here?

**Comment by jdoliner** [comment]
This should be very easy to fix, PR incoming.

**Comment by hchauvin** [comment]
Thank you!
