### ISSUE TITLE
Soften the 32-character restriction on branch names

### ISSUE THREAD

**Issue by hchauvin** [pachyderm/pachyderm#2732]
Hi, thank for the tool, this is definitely something I was waiting for without knowing it :)

**What is the ask?**

I stumbled upon a feature today that I wasn't expecting: in 1.7, there is this constraint that branch names cannot have exactly 32 characters: https://github.com/pachyderm/pachyderm/pull/2014.  Now I understand that this is for ensuring that a branch name is not mistaken for a UUIDv4, but maybe the 32-length restriction is a bit too harsh. 

**What is the goal / desired outcome?** Maybe, so as not to have a breaking change, it would be best to check whether a branch name is valid through:
not (is 32 character long) || contains only 0123456789abcdef

**If there is a way to accomplish this today via workaround, what does that require?** Some of my branch names are automatically generated, so I worked around this by prefixing all generated branch names that are 32 character long by, e.g., "_pachfix". This feels a bit like the mother of all hacks.

If you then happen to have branch names generated from UUIDv4 ids without dash, it doesn't feel as hacky to prefix them with, e.g., "prefix-" and is something you would probably do anyway.

**Comment by dwhitena** [comment]
Hi @hchauvin, I actually wasn't aware of this restriction either, but I guess I can see both sides. I think there is probably a good compromise that we could figure out here, but I will defer that discussion to @jdoliner or @msteffen. Thanks again for the input!

**Comment by jdoliner** [comment]
I think we can definitely soften this a bit. Your suggestion would help quite a bit, and I'm guessing would make your autogenerated branch names pass the test. In addition we can check that the 13th character is a `4` since that's part of the UUID spec. I suspect at that point it'd be quite hard to run afoul of the restriction.
