### ISSUE TITLE
nodeSelector and scheduling of workers in general

### ISSUE THREAD

**Issue by hchauvin** [pachyderm/pachyderm#2739]
**What is the ask?**

To add some control over the nodes onto which workers are scheduled.  Currently, there are in Kubernetes (1.9) three ways to do so: nodeSelector, nodeName and affinity.  I think that allowing the setting of nodeSelector covers more than enough use cases.

More specifically:
- Add a WORKER_DEFAULT_NODE_SELECTOR environment variable for pachd, which contains a JSON map of node selectors (keys as labels).  This environment variable is optional and, when it is set, it is used as the default nodeSelector for new workers.
- Add a node_selector map<string, string> to JobInfo, PipelineInfo and CreatePipelineRequest to override the default settings.

I did not make a pull request because this changes the interface and I might get ahead of myself on this one, but since I needed it for my own consumption it is ready here: https://github.com/hchauvin/pachyderm/commits/worker-node-selector

**What is the goal / desired outcome?**

- To have more control over how disruptions are handled
- To isolate workers from other pieces of infrastructure
- To schedule some workers on specific machines because of their characteristics (CPU spent in steal mode, network interface, volumes attached, ...)

**If there is a way to accomplish this today via workaround, what does that require?**

There is only a workaround for separating the infrastructure, which is to write anti-affinity rules for all the pods that are not worker.

**Comment by dwhitena** [comment]
Yeah, I think this would'nt be that bad to implement, because we already pass through things like resource limits and requests to k8s. However, we should decide what we want to expose to the Pachyderm user @jdoliner. As we could technically pass through many things, which might be a bit overwhelming. Although the above ask, or at least part of it, might be very useful.

**Comment by hchauvin** [comment]
Well that was exactly my thought.  In the end, I don't think you want to fully duplicate all the options Kubernetes has to offer.  For instance, allowing to set affinity would require to greatly expand the API.  I thought about that and I think that past a certain point, if configuration is really necessary, then you could use a gotemplate for the RC spec that gets all the internals of Pachyderm as variables and outputs a YAML file.  This way, all the cases, present or future, are covered, including security, network policies, ...

However, I thought this was an overkill if the only thing to do is selecting a node.  In the end, with resource requests/limits and a node selector, I think that worker scheduling is covered more than enough.

**Comment by seeb0h** [comment]
I share the need with a mixed cpu/gpu cluster. 
I need: 

 - to prevent cpu pipelines to be run on gpu nodes. 
 - to prevent monothreaded cpu pipelines to be run on cpu nodes with many cpus 
 - to choose my gpu type for my gpu pipelines


Being able to use `nodeSelector` would be perfectly fine.

**Comment by suneeta-mall** [comment]
+1 
I would like to see this feature in pachyderm too. Whilst separating resources by namespace (borrowed from K8S is great), there is no reason why one would not want to isolate the boxes thats processing long running jobs from other critical  services running in cluster sharing same K8S resources. 
Besides I might want to run some pachyderm pipelines on spot instances or boxes of different configuration .. may be even GPU. Node selector will be helpful in deploying these pod at best boxes as users sees it.

**Comment by suneeta-mall** [comment]
I wonder if its enough to have `--dry-run --o yaml|json` sort of option on create/update pipeline which then users can take and modify as per their wish to add selector/affinity(anti-affinity) etc. This saves from adding all those abstractions on pipeline spec. It just means theres more than one way to deploy the pipeline which in a way is a good think .. then ksonnet package for pachyderm could also be a thing :)

**Comment by JoeyZwicker** [comment]
This has been added in 1.7.10 via PR #3169
