### ISSUE TITLE
DeleteCommit lets users delete commits in downstream repos, even if they don't have write access

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2743]
Currently, `PFS.DeleteCommit(commit)` deletes `commit` as well as all of its downstream output commits. It does this even if the caller doesn't have write access to those downstream repos.

Arguably, in this case, it should instead leave a tombstone indicating that the commit was deleted, and leave downstream commits alone. If an owner of a downstream repo tries to follow commit provenance in an affected commit, they'll hit the tombstone

**Comment by jdoliner** [comment]
The behavior we have now, where deleting an upstream commit deletes downstream commits regardless of access seems like it might be right to me. At least it doesn't seem obvious that it's wrong. The question, in my mind, is what it means to "not have write access to an output repo." No one really writes to an output repo, only the pipeline does that, users write to the input repo and that causes downstream writes to happen. If a user without write access to an output repo but with access to the input repo creates a new commit on the input repo that writes to the output repo, so it seems fairly reasonable that deleting that same commit would also delete the downstream job.

**Comment by jdoliner** [comment]
I'm going to close this, since I think it's probably a sensible behavior and it would require rethinking some things in our model to change it, which I don't think is worth it. Feel free to reopen if you have strong feelings that this behavior is incorrect.
