### ISSUE TITLE
port-forward fails if Pachd is in a namespace

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2745]
port-forward can't find pachyderm if it's deployed in a namespace. Probably need to add a --namepsace flag to port-forward. 

Had to run this to make it work:
`kubectl --namespace=pachyderm port-forward `kubectl --namespace=pachyderm get pods -l app=pachd -o json | jq '.items[0]tadata.name' -r` 30650:650 &`

There may be other places where we call kubectl commands under the hood and need that flag.

**Comment by sjezewski** [comment]
We may also want to add the namespace to the `~/.pachyderm/config.json` file ... since we include details that tell pachctl how to connect to a cluster in there (right now the pachd address, user token).

**Comment by jdoliner** [comment]
Adding a namespace flag to `port-forward` is easy enough, (#2749). We could also add this to the config. However I think the best practice is actually to set this at the k8s level with:

```
$ kubectl config set-context dev --namespace=development \
  --cluster=<cluster> \
  --user=<user>
```

That way things like `kubectl get all` and `kubectl logs` will just work.

**Comment by dwhitena** [comment]
Just hit this as well. Need to decide on the best solution. Then I can document it.

**Comment by jdoliner** [comment]
We now have a `--namespace` flag on `port-forward` we should get that documented.
