### ISSUE TITLE
etcd not deployed to pachyderm namespace on GCP

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2754]
**What happened?**:

When deploying Pachyderm to GCP in a custom namespace (with the `--namespace`) command, Pachyderm's `etcd` pod(s) are not deployed to the specified namespace:

```
$ kubectl get pods --namespace pachyderm
NAME                     READY     STATUS    RESTARTS   AGE
dash-68578d4bb4-bdrml    2/2       Running   0          2m
pachd-6d9787cb7b-vt57c   0/1       Running   0          2m
$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
etcd-0    1/1       Running   0          2m
```

This was also seen by a user this morning in users Slack. 

**What you expected to happen?**:

All Pachyderm pods to be deployed to the specified namespace.

**How to reproduce it (as minimally and precisely as possible)?**:

Deploy Pachyderm with `--namespace` to GCP.

**Anything else we need to know?**:

**Environment?**:

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`): 1.7.0rc2

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GCP

- OS (e.g. from /etc/os-release): MacOS

- Others:

**Comment by jdoliner** [comment]
This isn't reproducing for me, can you give me the command you used to deploy? I did: 

```
LAUNCH_DEV_ARGS="--namespace=test" make launch-dev
```

**Comment by dwhitena** [comment]
@jdoliner I followed all of the steps in the [GCP docs](http://pachyderm.readthedocs.io/en/latest/deployment/google_cloud_platform.html) except for the deploy command. I just added the namespace flag to that:

```
pachctl deploy google ${BUCKET_NAME} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --no-rbac --namespace pachyderm
```

**Comment by jdoliner** [comment]
Ahh, the issue is that it's using the etcd stateful set, fix incoming.
