### ISSUE TITLE
Expose activation code removal in the API

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2758]
**What is the ask?**

An API endpoint that remove activation codes (probably that is only active in dev mode)

**What is the goal / desired outcome?**

So that I can test front-end code that activates the cluster

**If there is a way to accomplish this today via workaround, what does that require?**

deleting the key directly from etcd

**Comment by jdoliner** [comment]
We now have the `deactivate` call which does this I think. Closing, please reopen if that end point doesn't satisfy this.
