### ISSUE TITLE
pachctl command line completion

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#276]
Two parts. Make the completion script (gcloud tools have some examples) then add it to homebrew formula like so:

/Users/sjezewski/google-cloud-sdk/completion.bash.inc

**Comment by jdoliner** [comment]
I'd +2 this if I could.

**Comment by jdoliner** [comment]
Part 1 is complete, #619.

**Comment by jpoon** [comment]
A suggestion is to add a `completion` command to pachctl similar to `kubectl completion`. The command can spit out a bash/zsh completion file that you can load. Looks like Cobra has a built-in ability to generate bash completions so the work to implement should be fairly easy:  https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by sjezewski** [comment]
I think @jdoliner implemented this as a command, so I think we can close this.
