### ISSUE TITLE
jobs with exit status 0 are marked as failed

### ISSUE THREAD

**Issue by williballenthin** [pachyderm/pachyderm#2776]
# info

**What happened?**:

Jobs that exit with status 0 are marked as failed.

**What you expected to happen?**:

If a job exits with status 0, then it should be marked as successful.

**How to reproduce it (as minimally and precisely as possible)?**:

Test cases attached below.

**Anything else we need to know?**:

This error seems to manifest itself when a prior job fails, subsequent jobs are marked as failed, even if they exit with status 0.

**Versions**
- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version:
```
$ pachctl version
COMPONENT           VERSION
pachctl             1.6.5
pachd               1.6.5
```
- Provider: cloud k8s on AWS via kops

# test cases

### pipeline

Consider the following pipeline (`b.json`):
```
{
    "pipeline": {
        "name": "B"
    },
    "input": {
        "atom": {
            "repo": "A",
            "glob": "/*.txt"
        }
    },
    "transform": {
        "image": "ubuntu:latest",

        "cmd": ["/bin/bash"],
        "stdin": [
            "INPUT=/pfs/A/*;",
            "ls ${INPUT};",
            "if [[ $(cat ${INPUT}) =~ ^yes ]]; then echo 'yes'; exit 0; else echo 'no'; exit 69; fi;",
            "echo 'shouldnt get here';",
            "exit 0;"
        ]
    },
    "enable_stats": true
}
```

In summary, it reads from text files in repo A, and if the content of the file begins with `yes` then it exits with status 0, or 69 otherwise. All files that start with `yes` should be marked successful, and fail otherwise.

### test case 1
Here is test case one. It demonstrates that sometimes jobs that exit with status 0 are marked successful. This is what we expect to happen.

```
#!/bin/bash

echo "yes1" > yes1.txt
echo "yes2" > yes2.txt
echo "yes3" > yes3.txt
echo "no1" > no1.txt
echo "no2" > no2.txt
echo "no3" > no3.txt

pachctl create-repo "A"

pachctl put-file A master yes1.txt -c -f yes1.txt
pachctl put-file A master yes2.txt -c -f yes2.txt
pachctl put-file A master yes3.txt -c -f yes3.txt
pachctl put-file A master no1.txt  -c -f no1.txt
pachctl put-file A master no2.txt  -c -f no2.txt
pachctl put-file A master no3.txt  -c -f no3.txt

pachctl create-pipeline -f b.json
```

We create three files each of "yes" and "no" files. They are added to the A repo with all the "yes" files first, and all the "no" files second. After the pipeline is installed, there should be three successful jobs, and three failed jobs. This is also the behavior that I see when I run the script.

### test case 2
Here is a second test case. It demonstrates that some successful jobs are marked as failed. This is not what we expect to happen.

```
#!/bin/bash

echo "yes1" > yes1.txt
echo "yes2" > yes2.txt
echo "yes3" > yes3.txt
echo "no1" > no1.txt
echo "no2" > no2.txt
echo "no3" > no3.txt

pachctl create-repo "A"

pachctl put-file A master yes1.txt -c -f yes1.txt
pachctl put-file A master no1.txt  -c -f no1.txt
pachctl put-file A master yes2.txt -c -f yes2.txt
pachctl put-file A master yes3.txt -c -f yes3.txt
pachctl put-file A master no2.txt  -c -f no2.txt
pachctl put-file A master no3.txt  -c -f no3.txt

pachctl create-pipeline -f b.json
```
We create three files each of "yes" and "no" files. They are added to the A repo in an order that mixes "yes" and "no" files. After the pipeline is installed, there *should* be three successful jobs, and three failed jobs. This is *not* the behavior I see when I run the script. I see: `success`, `fail`, `fail`, `fail`, `fail`, `fail`.

Here's a screenshot of the job statuses. See if you can guess which test case was run first.
![jobs1](https://user-images.githubusercontent.com/156560/37424674-b1301986-2786-11e8-9e19-c9a79d9d6e95.PNG)

**Comment by JoeyZwicker** [comment]
@williballenthin So the explanation for this I think is pretty straight forward. Commit's in pachyderm, similar to git, are the accumulation of the files that have been added. So when you add yes1.txt, then no1.txt, then yes2.txt, you still have the no1.txt file in your head commit. When pachyderm triggers a new job, it reprocesses all datums that have no been successfully processes. That means, when the job triggers, it's still processing no1.txt, failing, and then marking the whole job as failed. 

In the example, you've essentially got bad (failing) data in your head commit. To solve this, you need to delete the bad data. 

If I'm understanding your use case correctly, that's actually not quite the behavior you want. You actually want to keep the no.txt files in the system. That mean's you'll want to actually change your code to always exit0 for both no and yes files, but perhaps categorize them differently. You could, for example write all your yes file outputs to a `yes` directory and same for no files. Then have your next pipeline use the glob pattern input/yes/* to only process the output of the yes directory. You may even want to have a separate pipeline that looks at the no files and does something with them (like send alerts) or perhaps not and just ignore them. 

Does this all makes sense? Both in terms of how pachyderm behaves and how to accomplish what i think you're aiming for?

**Comment by williballenthin** [comment]
Hey @JoeyZwicker this makes sense to me. I keep realizing that my mental model of pachyderm is slightly off, so, this is my fault. Thanks for taking the time to clarify how pachyderm handles the files and jobs.

I think that your correct that a reasonable solution is to *always* handle the inputs, and use output paths to indicate success/failure.
