### ISSUE TITLE
Curate content for sandbox

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#278]
[sandbox.pachyderm.io](http://sandbox.pachyderm.io) is up

Could definitely use some revisions on content. If there are any other issues, lets track them on that repo and also use a 1.0 milestone.

@JoeyZwicker - I could use your help here reviewing the copy / content.

Feel free to make a PR for sandbox for the content -- the example contents are all under `/assets/examples/fruit-stand`

**Comment by JoeyZwicker** [comment]
About to get a the plane but I'll do full editing pass PR tomorrow.

**Comment by sjezewski** [comment]
Awesome!

**Comment by JonathanFraser** [comment]
Setting shards to something other than 1 makes it go nuts.

**Comment by sjezewski** [comment]
Thanks for the feedback!

Right now there is a bug w the deployment. Just running the normal setup causes a loop. I'll be looking into the sandbox again next week. For now, we're heads down on some other bugs.

**Comment by sjezewski** [comment]
This is defunct.
