### ISSUE TITLE
Strange Duplicate Pipeline Name Error Message in 1.7

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2781]
Create a pipeline named "test2" when such a pipeline already exists

`Failed to create pipeline "test2": pipeline spec branch for "test2" already exists: delete it with DeletePipeline%!(EXTRA string=spec)`

**Comment by jdoliner** [comment]
This should be fixed by #2777.

**Comment by gabrielgrant** [comment]
ah, sweet
