### ISSUE TITLE
Azure blob limit causing datum upload/download failure

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2790]
Apparently there is a "4-MB limit for each call to the Azure Storage service. If your file is larger than 4 MB, you must break it in chunks.": https://support.microsoft.com/en-us/help/4016806/the-request-body-is-too-large-error-when-writing-data-to-azure-file

At least one user has encountered this failure when using the Azure Blob backend: 

```
{"pipelineName":"spacing-nnpair-gather","workerId":"pipeline-spacing-nnpair-gather-v1-fgxv7","ts":"2018-03-19T12:03:14.628222197Z","message":"worker: watch closed or error running the worker process: acquire/process datums for job 20f67d13308c410e8db7b3662edf5c31 exited with err: rpc error: code = Unknown desc = storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.\nRequestId:1a3ca97b-001e-0026-2e73-bfe4af000000\nTime:2018-03-19T11:11:37.1253580Z, RequestId=1a3ca97b-001e-0026-2e73-bfe4af000000, QueryParameterName=, QueryParameterValue=; retrying in 468.857094ms"}
```

My best guess is that this changed at some point recently, and, thus, our Azure backend client needs to be updated.

**Comment by dwhitena** [comment]
@jdoliner or @msteffen input here?

**Comment by dwhitena** [comment]
Note, this was with 1.7.0rc2.

**Comment by dwhitena** [comment]
Thanks for the insight @rdefreitas!

**Comment by jdoliner** [comment]
This is an issue we've seen before and currently our azure driver breaks data up into 2MB chunks before sending it over the wire. I'm gong to do some digging and see if there's somewhere we're failing to break it up, but that seems unlikely since the breaking up happens at a pretty low level in the API. I'm also going to add some more logging so we can maybe understand better where that error message is coming from.

**Comment by jdoliner** [comment]
Azure driver has been rewritten since this and tested with large (many GB) files without exhibiting this problem. Closing, feel free to reopen if you hit something like this again.
