### ISSUE TITLE
List-job UX degrades around 20k jobs.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2791]
**What happened?**:
Once you get to the 20k jobs range the UX for that call starts to really break down. A single call to `list-job will take 7 minutes. There's no way to paginate or just see the most recent jobs. The job list is so long it becomes impossible to find the job you're interested in. The UI suffers in this case too, because it's using the same API endpoints.

**What you expected to happen?**:

The system should remain usable, allowing for paginated / head / tail of jobs.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a lot of jobs.

**Comment by JoeyZwicker** [comment]
More users starting to hit this is public channels. I think this becomes very doable with the current streaming list-* PR, right?

**Comment by jdoliner** [comment]
The current streaming list-* PR is a direct solution to this issue.

**Comment by jdoliner** [comment]
Streaming `list-*` commands are implemented and solve this problem.
