### ISSUE TITLE
Bundle the appropriate pachctl version along with the server(?)

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2799]
We are generally able assume that people are using the same version of pachctl as the version of pach they have deployed, because generally that deploy comes from the pachctl client. For users who are trying to use an already-running pach cluster (whether because it was deployed by someone else, or because they deployed it via Helm), would it make sense to bundle the appropriate pachctl binaries so they can just download it directly from pachd's built-in HTTP server? This would let me easily link it directly from the dash, for instance

Right now the Helm chart has [instructions to download pachctl](https://github.com/kubernetes/charts/blob/master/stable/pachyderm/templates/NOTES.txt), but that only seems to download the correct version for Linux. My understanding is that OS X users are stuck with whatever is the latest minor version we've published. Is that always sufficient? Or is there some way for an OS X user to get a specific patch release?

**Comment by jdoliner** [comment]
This is an interesting idea, but I'm not quite sure the costs outweigh the benefits. It would be a boost in convenience but I feel like we'd be leading people away from best practices for installing and maintaining packages on their machine. It's generally better for people to go through brew / apt to install their packages, even if that's a bit more work up front. This also would add some non-negligible overhead to the `pachd` container, `pachctl` is about 50MB right now.

As an alternative I think we could maybe have a tab in the ui that gives people apt / brew commands to install the appropriate pachctl and a link the the raw binary if that's what they need to resort to.
