### ISSUE TITLE
Unclear error message when deleting an input repo

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2800]
Trying to delete a repo that is the input to a pipeline results in `Failed to delete repo "test": could not put new ACL: pachyderm/1.7.0/pachyderm_auth/acls/test not found`

Not sure if this is a bug and should be allowed, or if we just need to clarify the error message

**Comment by jdoliner** [comment]
So I think you're hitting another error in auth before you can get to the part where we check if the repo has an branches with subvenance.

**Comment by jdoliner** [comment]
Just checked this and it gives the error message:

```
delete branch repo:<name:"TestSimplePipeline_data2df868909160" > name:"master" : branch master has [repo:<name:"TestSimplePipeline264c57d37b91" > name:"master" ] as subvenance, deleting it would break those branches
```

This seems like a reasonable error message to me, I think the original one was an auth error, which could maybe be improved but seems like a pretty particular situation that users probably won't hit that often.
