### ISSUE TITLE
Object Getter errors after garbage collection

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2801]
**What happened?**:

Pachyderm get's into a weird (seemingly unusable) state when garbage collection is run simultaneously with active jobs (which shouldn't be allowed anyway).

See the below workflow. This issue has been reported by 2 users already.

```
$ pachctl create-repo images
$ pachctl put-file images master -c -i images.txt
$ cat edges.json
{
  "pipeline": {
    "name": "edges"
  },
  "input": {
    "atom": {
      "glob": "/*",
      "repo": "images"
    }
  },
  "transform": {
    "cmd": [ "/bin/bash" ],
    "stdin": [
	   "sleep 30",
	   "python3 /edges.py"
    ],
    "image": "pachyderm/opencv"
  }
}
$ pachctl create-pipeline -f edges.json
$ pachctl list-job
ID                               OUTPUT COMMIT                          STARTED        DURATION RESTART PROGRESS  DL UL STATE
eedd36cb918441a1a4d4c809b6b4e7b9 edges/f6e5e2c1abf242afb4f68ff83749c314 48 seconds ago -        0       0 + 0 / 1 0B 0B running
$ pachctl garbage-collect
$ pachctl list-job
ID OUTPUT COMMIT STARTED DURATION RESTART PROGRESS DL UL STATE
$ pachctl list-pipeline
could not read existing PipelineInfo from PFS: objectInfoGetter: object 160d8c38dab3f9e6a75745b1975c51cd7a2f170311b15e768a66818572fa2c55d7a484a8df97660d50a07c7a52f7bcab57d777f33cd6e6caf05fb2c92f74b55f not found
```

**What you expected to happen?**:

1. Garbage collection to be disallowed when there are active jobs, as stated in our docs: "Currently pachctl garbage-collect can only be started when there are no active jobs running.": http://pachyderm.readthedocs.io/en/latest/managing_pachyderm/data_management.html#garbage-collection

2. If it was allowed, I would expect that jobs aren't deleted and that it doesn't put the cluster in an unusable state.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Run the above slightly modified edges pipeline.
2. While the edges job is active, run `pachctl garbage-collect`

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`): 1.7.0rc2

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube and GCP so far

**Comment by kaktus42** [comment]
Same happened here

**Comment by jdoliner** [comment]
@kaktus42 sorry that you're hitting this. It should be recoverable in the next version of Pachyderm by deleting and recreating your pipeline. Are you getting the same reproduction as the original post?

**Comment by kaktus42** [comment]
I was getting this after deleting a pipeline and then garbage-collect.
In my case there were no jobs running.

I am using version 1.7.1

I wanted to do this, because when I delete-pipeline and then create-pipeline with the same name, I see that the old commits of the pipeline-repo are still there.

**Comment by jdoliner** [comment]
Garbage collect now errors if there are active pipelines or workers running. It's still possible to get this type of corruption but you have to really try by stopping pipelines, starting GC and then restarting the pipelines. I think that's as safe as it's going to get with this iteration of GC, passive GC will be here soon with the new storage layer and this won't be an issue at all.
