### ISSUE TITLE
Document Migration Process for custom deployments

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2802]
**What is the ask?**

As a user I need to know how to migrate when I've made modifications to my k8s cluster.

**If there is a way to accomplish this today via workaround, what does that require?**

Yes.

Today we can

1) Find the previous incantation of `pachctl deploy ...` that was used

OR

2) Do `kubectl get secrets...` for the storage secret to extract the secret id, secret, bucket name, region, etc so that we can reconstruct that command

3) `pachctl deploy amazon ... all the args you originally used ... --dry-run > pachyderm.json`

4) Modify that manifest in place w your customizations

5) do `kubectl apply -f pachyderm.json` to do the rolling update / migration

Some other notes:

- if the rolling update fails ... doc how to do `kc rollout history deployment/pachd` and `kc rollout undo deployment/pachd` to stop it
- we want to STRONGLY recommend storing your deployment `pachyderm.json` manifest in version control
- But! This likely contains secrets! But it's still worth it to commit it (so that you can compare to the previous version to make sure you've included the customizations you need). So we need to doc that you should redact it. Or ... have a tool to do that :-/

**Comment by mindthevirt** [comment]
Closing out due to this being documented [here](https://docs.pachyderm.com/latest/deploy-manage/manage/upgrades_migrations/)
