### ISSUE TITLE
Unclear error messages when files/dir don't exist

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2809]
I'm not sure where/when these types of errors pop up, but `node` related messages like the following for missing directories of files are unclear:

> User [10:54 AM]
> hi! I'm seeing `no node at "/folder"` when I try to run list-file on a dir in a repo, any idea why this happens?

**Comment by jdoliner** [comment]
I get `file "/foo" not found` for when I try to access a file that doesn't exist. So I think this is fixed, feel free to reopen if you find more confusing error messages at "no node at."
