### ISSUE TITLE
Pachyderm worker should not need access to host Docker socket

### ISSUE THREAD

**Issue by emmanuel** [pachyderm/pachyderm#2813]
**What is the ask?**

I need a roadmap that arrives at pachyderm workers not mounting the host Docker socket. Our Kubernetes clusters are multi-tenant and therefore access to the host Docker socket is extremely limited.

**What is the goal / desired outcome?**

So that I can accomplish my goal of using Pachyderm within my organization's security mandate.

**If there is a way to accomplish this today via workaround, what does that require?**

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.8.x
- Pachyderm CLI version (use `pachctl version`): 1.6.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): all
- OS (e.g. from /etc/os-release): N/A
- Others:

**What happened?**:

The Pachyderm worker mounts the host Docker socket in order to describe the user's container (and thereby discover the entry point, working dir, and UID/GID.

**What you expected to happen?**:

No mounting of the host Docker socket.

**How to reproduce it (as minimally and precisely as possible)?**:

Launch a pipeline. Inspect the created Pods.

**Anything else we need to know?**:

This is clearly by design. The request is for a path to an unprivileged worker. 

One option may be to state in the pipeline definition the information currently discovered via the Docker socket. This would allow configuring pipelines without using the socket, which in turn would allow creating a feature to disable use of the socket.

**Comment by jdoliner** [comment]
Hey @emmanuel thanks for a very descriptive feature request. This is definitely something we can get in for you. I think it's already possibly to state most of the relevant info in the pipeline spec. For other stuff such as the work dir and user we can add it. I think this will likely just be a field in the pipeline spec that indicates whether or not it should have the privileges.

**Comment by emmanuel** [comment]
Thanks @jdoliner.

**Comment by jdoliner** [comment]
@emmanuel one question on this, how is this policy actually enforced in your company? I'm wondering if we can just detect the failure and respond to that rather than making users explicitly set it.

**Comment by jkinkead** [comment]
. . . or just limit the launching of privileged pods.

The problem here is that this effectively grants the pipeline root to the entire cluster.

If the init container instead were responsible for looking up the image info, and passing it on to the worker container, only it would need the docker port, and it would close the security hole nicely.

**Comment by emmanuel** [comment]
The mechanism by which we limit the launching of privileged pods will likely also be `PodSecurityPolicy`. 

An alternative would be a custom admission controller, but given that PSP is designed for exactly these use-cases (controlling pod access to `hostPath` mounts, pods with `privileged: true`, and other security controls) that's where I would bet that we start.
