### ISSUE TITLE
port-forward throws regular benign errors

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2815]
```
joeyzwicker$ pc port-forward
CTRL-C to exit
Forwarding the dash (Pachyderm dashboard) UI port to http://localhost:30080 ...
Forwarding the pachd (Pachyderm daemon) port...
E0329 09:28:25.856517   33861 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:30650->127.0.0.1:59974: read: connection reset by peer
E0329 09:32:56.140703   33861 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:30650->127.0.0.1:60193: read: connection reset by peer
E0329 11:49:07.042817   33861 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:30650->127.0.0.1:64929: read: connection reset by peer
E0329 11:58:00.314360   33861 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:30650->127.0.0.1:50745: read: connection reset by peer
E0329 11:58:03.017112   33861 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:30650->127.0.0.1:50760: read: connection reset by peer
```

Users hit this too frequently. We need to silence this error or figure out why it's happening. Does this go away if we upgrade port-forward to reset for each call (or whatever that feature request was)?

**Comment by JoeyZwicker** [comment]
This continues to plague users. Any chance we can bump the priority on this? It's not an intermittent thing, it's every time and constant.

**Comment by JoeyZwicker** [comment]
Not restricted to Mac apparently.

**Comment by jdoliner** [comment]
I still don't think there's anything reasonable to do for this, we could start filtering out kubernetes error messages but that's difficult to do for a number of reasons:

- different versions of kubectl have different error messages
- these error messages change
- there's a very large risk associated with this which is that we might filter out a meaningful error message leaving the system in a state
- lastly, these error messages get logged because they're not always benign, although they certainly seem to mostly be

I don't think these issues are really plaguing users as you suggest, they're coming up and I've seen them mentioned a bunch of times but mostly users mention them as "hey, I'm seeing these errors but everything is working, do these matter?" they're annoying, but I don't think they're blocking many people from doing work. Maybe just a message at the top that says these messages are benign would help.

Also, why are you insisting on labeling this as 1.7 backlog? This issue was opened 3 days after we shipped 1.7, in what sense is it 1.7 backlog?

**Comment by JoeyZwicker** [comment]
oh, my labeling was silly, as it was just to note to myself that 1.7 backlog things are things that we want to consider for slotting into 1.8 when we actually make that label update. 

In terms of fixing, it sounds like there are no good solutions.... but for every user that asks about it there are 10+ that don't and it makes the product feel unpolished when a standard workflow for the basic product is littered with error messages.

**Comment by jdoliner** [comment]
>  for every user that asks about it there are 10+ that don't

I'm sure there are several users that don't ask because they are familiar enough with networking to know that a connection being reset is normally benign and even if they don't the word "reset" suggests this and it's easy to confirm that things are still working. If more than 90% of users are able to figure this out for themselves and a few others who are less familiar with networking need to ask then I think we're doing pretty well. And also, I'd like to reiterate that these error messages might not always be entirely benign, I'm pretty sure for a long running operation like a `put-file` these resets could actually cause problems in which case it's important that the user has some sort of a log message to go on because otherwise they have no chance of figuring out what's going on.

I also very much disagree that this is an example of the product being unpolished, developer tools like Pachyderm and Kubernetes are generally willing to risk giving too much information if it means mitigating the risk that important information doesn't get reported. The prior might cost you a few minutes asking a question in slack, the latter might cost your entire team several weeks as you try to figure out why things are broken. This is the right attitude.

**Comment by jdoliner** [comment]
Also, we may be able to mitigate this a bit by doing what helm does and just doing a new port-forward for each request, I'm not sure that that will totally remove these logs though.

**Comment by jeffdeville** [comment]
Chiming in as a new user.  The first word of this message is 'error'. I think it's reasonable for anyone to assume that the put-file command would have failed.

If this isn't something with a known solution, perhaps including this specific error message in the tutorial (where I encountered it) and troubleshooting section (where I went next) of the docs would help.

**Comment by hassanbakerrts** [comment]
I'm still having the same error when I try to forward RabbitMQ port. As @JoeyZwicker said, it's regular and periodic error, you can see the error through `port-forward` logs: 


`Forwarding from 127.0.0.1:15672 -> 15672
Forwarding from [::1]:15672 -> 15672
Forwarding from 127.0.0.1:5672 -> 5672
Forwarding from [::1]:5672 -> 5672
Handling connection for 15672
Handling connection for 5672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 5672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
E0627 10:29:08.593176   74809 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:5672->[::1]:57645: read: connection reset by peer
Handling connection for 5672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 5672
Handling connection for 15672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
E0627 10:49:01.161585   74809 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:5672->[::1]:58105: read: connection reset by peer
Handling connection for 5672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
E0627 11:00:26.581323   74809 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:5672->[::1]:58377: read: connection reset by peer
Handling connection for 5672
Handling connection for 5672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
Handling connection for 15672
`

**Comment by ysimonson** [comment]
@hassanbakerrts this is unfortunately an artifact of kubernetes' port forwarder, which is not particularly reliable for long-running connections. See here for a discussion: https://github.com/kubernetes/kubernetes/issues/74551

In the mean-time, we're encouraging Pachyderm users to directly connect to their clusters where possible.

**Comment by JamesArthurHolland** [comment]
This is particularly problematic when trying to benchmark requests.

**Comment by ysimonson** [comment]
Port forwarding is a large performance bottleneck. We'd strongly recommend not using it when benchmarking.
