### ISSUE TITLE
Update documentation for delete-commit

### ISSUE THREAD

**Issue by gkumar7** [pachyderm/pachyderm#2821]
https://github.com/pachyderm/pachyderm/blob/55608ad745d53a8fb3d95f9777e8c9b3c5124178/src/server/pfs/cmds/cmds.go#L493-L495

Is this the intended behavior? I am able to delete finished commits as well, possibly a change to the documentation is needed?

**Comment by JoeyZwicker** [comment]
Thanks for pointing this out @gkumar7. 

@dwhitena will update the docs to reflect this change in 1.7
