### ISSUE TITLE
confusing "node of type" error message

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2822]
Another node at message. It's possible this was already fixed in the past PR @jdoliner because I think that's still in master, but just wanted to document it. 

 ```
pachctl list-file sentieon-data-nygc-a 7a89d51d97ed4c82b13c907f0972e0e8
could not put file at "/004-0006-1"; a node of type directory is already there
```

**Comment by JoeyZwicker** [comment]
Not sure why this is showing up with a list-command instead of at the put-file command though

**Comment by jdoliner** [comment]
Got a PR fixing this and other messages. @JoeyZwicker you're reviewer on that.

Error messages like this are basically the Pachyderm equivalent of a merge-conflict. So they occur when merges happen. Merges normally happen in `FinishCommit` however, when you attempt to read from an open commit (ie, `list-file`) we perform a partial merge on all the writes we've gotten to the commit so far, and that can also result in a conflict, as it is here.
