### ISSUE TITLE
Enabling auth succeeds without pachd being able to access the outside world, effectively locking cluster

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2825]
Enabling auth requires a GitHub user's token to use as the first admin, but doesn't seem to actually verify that token? In my test cluster, pachd currently can't seem to talk to the outside world. Despite this, I was able to activate auth using my GH token, but now, because it can't verify with github, I'm unable to log in (so effectively locked out of my cluster).

**Comment by msteffen** [comment]
This is per https://github.com/pachyderm/pachyderm/pull/2759 (a feature that IIRC we wanted for dash testing? Though if it's not helping us test the dash we can/should do something else)

**Comment by msteffen** [comment]
This was fixed by e7616feee3d13a222274ef440a62b06626ad1ded. `pachctl auth activate` now attempts to convert GitHub tokens to a username before putting auth in an intermediate state. Now, Pachctl auth should fail fast instead of getting stuck
