### ISSUE TITLE
pipeline WorkerImage ignores private docker registry and uses `pachyderm/worker` directly

### ISSUE THREAD

**Issue by oskca** [pachyderm/pachyderm#2830]
**What is the ask?**

In an offline installation `k8s` cluster, pachyderm will not bring up pipelines correctlly because of the lack of internet connection to pull pod init docker image `pachyderm/worker:1.7.0`

BTW pachyderm could correctly use the private registry to pull docker images like `pachyderm/pachd` and `pachyderm/etcd` 

**What is the goal / desired outcome?**

make piplelines really running

**If there is a way to accomplish this today via workaround, what does that require?**

manually `docker load` image to every `k8s node` as `pachyderm/worker:1.7.0` with no private registry prefix

**What happened?**:
pipleline pod's init container images defaults to `pachyderm/worker:1.7.0` and don't work in an offline installation
**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:
deploy pachyderm in an offline k8s cluster
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.9
- Pachyderm CLI version (use `pachctl version`): 1.7.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local deployment
- OS (e.g. from /etc/os-release): centos 7
- Others:
  volume is provide by `rook block storage`
  s3 storage is provided by `rook object store`
  no internet connection

**Comment by JoeyZwicker** [comment]
Hi @oskca, Pachyderm's Enterprise Edition has offline cluster support to do exactly what you're looking for here. Shoot me an email at joey@pachyderm.io and we'd be happy to discuss further to get you set up.

**Comment by jdoliner** [comment]
This has since been changed so you can use private registries on oss clusters.
