### ISSUE TITLE
pachctl --raw flag produces empty output for list commands

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2836]
**What happened?**:

```
18-04-10[14:47:33]:pachyderm:0$pachctl list-pipeline 
NAME                INPUT               OUTPUT              CREATED             STATE               
18-04-10[14:49:02]:pachyderm:0$pachctl list-pipeline --raw
18-04-10[14:49:04]:pachyderm:0$
```

**What you expected to happen?**:

There to be at least one `{}` output.

**Comment by sjezewski** [comment]
Perhaps JSON stream decoders handle this case gracefully?

A user who wasn't using a stream decoder lib ran into this.

**Comment by jdoliner** [comment]
This is the intended behavior. Why would there be one `{}`? `--raw` prints out each object in the stream, if there are no objects in the stream it doesn't print anything.

**Comment by jdoliner** [comment]
Closing this, reopen if there's some justification for why what we have now isn't the correct behavior.
