### ISSUE TITLE
Docs for "deploy storage" missing

### ISSUE THREAD

**Issue by kaktus42** [pachyderm/pachyderm#2842]
**What happened?**:
Trying to access http://docs.pachyderm.io/en/latest/pachctl/pachctl_deploy_storage.md from http://docs.pachyderm.io/en/latest/pachctl/pachctl_deploy.html ends in error.

**What you expected to happen?**:
See the page

**How to reproduce it (as minimally and precisely as possible)?**:
Click the links

**Anything else we need to know?**:
-

**Environment?**:
Pachyderm Docs (latest)

**Comment by jdoliner** [comment]
This appears to be a ReadTheDocs issue, the `md` file definitely exists: https://github.com/pachyderm/pachyderm/blob/master/doc/pachctl/pachctl_deploy_storage.md

@JoeyZwicker any idea what's going on with this?

**Comment by JoeyZwicker** [comment]
these are being autogenerated, but the "see also" section is linking to the `.md` file instead of `.html`. I'm not sure why, but can try to to investigate.

**Comment by jdoliner** [comment]
pachctl deploy no longer links to this section, and the `html` version of deploy storage seems to exist, so I think we're good on this.
