### ISSUE TITLE
What is the minimal docker container for a worker?

### ISSUE THREAD

**Issue by alanz** [pachyderm/pachyderm#2848]
I am trying to build a docker container using nix, which starts from basically nothing.

I have worked out that it needs `/bin/sh` as a minimum.

Is there an easy way to find out what else is needed?

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.9.1
- Pachyderm CLI version (use `pachctl version`):v1.7.0 (53ec324422732aa2ca79015ffaac97c043f16257)
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
It needs `/bin/sh`, `/bin/mkdir` and `/bin/cp`.

In general you'll get faster responses to support requests like this if you ask in our slack channel than via github issues.
