### ISSUE TITLE
1 click deploy on aws / gce

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#286]
For pachyderm <1.0 we had a nice `Launch On AWS` button up on pachyderm.io. It'd be nice to have a similar thing post 1.0.

**Comment by jdoliner** [comment]
Moving this out of 1.0. We'll reevaluate this when we've seen the snags people hit on deploy and have a better idea of how to make it easier for them. Until then we're just going to focus on making the documentation for deployment better.

**Comment by sjezewski** [comment]
We now have a deploy script (leaning heavily on kops) for AWS that can be run to stand everything up. Not a 'button', but as close as we're going to get from the terminal

**Comment by sjezewski** [comment]
Stale.
