### ISSUE TITLE
Incorrect object store URLs generated in put-file

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2861]
A user reported this, but I have seen it as well. Basically, bucket names are repeated in the URL that's generated by pachctl. So we need to:

- fix any error with generating the URLs, and/or
- better document examples (which we definitely need)

I'm not sure that there is actually any bug here in generating the URLs, but I'm opening this to, at the minimum, remind us to add examples to the docs.

Details from the user:

> User [9:04 AM]
> Hi folks, I have since ~1 week the problem, that the command "pachctl put-file" doesn't work anymore for s3 files:
> pachctl put-file -v  -c zipped-input master -f 's3://bucket-name/xxx.zip'
> 
> I get the error:
> RequestError: send request failed
> caused by: Get https://bucket-name.s3.s3:/bucket-name/.amazonaws.com/xxx.zip: dial tcp: lookup bucket-name.s3.s3 on 100.64.0.10:53: no such host
> 
> so, apparently the transformation of the s3-string is not working anymore. But I don't know what happened, because it worked before.
> 
> ...
> 
> User [3:26 AM]
> @jdoliner no. the problem is with the generation of the URL either within pachyderm or the pachtl client.
> Because it generates the url "https://bucket-name.s3.s3:/bucket-name/.amazonaws.com/xxx.zip", which obviously can not be resolved...
> 
> User [3:50 AM]
> what it sould create is "https://bucket-name.s3.amazonaws.com/xxx.zip"

**Comment by kaktus42** [comment]
ah. perfect. thanks for putting it here!

**Comment by kaktus42** [comment]
I deployed 1.7.1 and also I can't reproduce anymore.
