### ISSUE TITLE
Add `--force` flag to `delete-pipeline`

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2864]
**What is the ask?**

I need a way to force `delete-pipeline` for cases when I can't otherwise delete it. This can come up in some corrupted states, among other things this would cause the `delete-repo` on the output repo to have `force=true` as well.

**What is the goal / desired outcome?**

To be able to repair clusters that get in broken states.

**If there is a way to accomplish this today via workaround, what does that require?**

You can accomplish this by directly cleaning up state in etcd and pfs but that's annoying and error prone.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by Tryneus** [comment]
This was added about a year ago in 2ec0d9e071d9df1c94fe18451e273458b8b7b90e
