### ISSUE TITLE
Move blobs to objects, rather than using pointers

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2873]
My understanding is that, when writing files into PFS, we write to a randomly-named "blob" in the object store, and compute the data's hash as we stream it in. Once the stream is fully written, and the final hash computed, we write an "object" in the object store with the name of that hash, that points to the relevant blob.

This means that, on retrieval, we have to perform two fetches (object, then blob) each of which is relatively high (and of variable) latency. Is there any reason we can't just move* the blob to the a location corresponding to it's hash after the initial write is complete and the hash calculated? 

*: Technically S3, at least, doesn't have a "move" as a first-class operation, but it's docs suggest using an atomic copy followed by a delete achieves the same thing

**Comment by jdoliner** [comment]
We should totally do this. It looks like s3, GCS and Azure all have workable atomic-copy APIs. I legit didn't know they existed. This can make a bunch of things much easier and more efficient.

**Comment by jdoliner** [comment]
This is no longer relevant as using object storage's namespace for dedupe lookups is way too slow. Still good to know that copy semantics are available in object storage.
