### ISSUE TITLE
Update GKE docs to set role bindings

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2874]
`Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "pachyderm" is forbidden: attempt to grant extra privileges:`

- gke version: 1.8.10
- pachyderm version: 1.7.0

Solved with:
`kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole cluster-admin --user $(gcloud config get-value account)`

@brycemcanally @dwhitena  are these rbac cmds required to be run on GKE for 1.8+ or is there something specific about this user's setup? If they are required now, lets just add to GKE docs. http://pachyderm.readthedocs.io/en/latest/deployment/google_cloud_platform.html#set-up-the-storage-resources

**Comment by brycemcanally** [comment]
Hey Joey,

That command is only required if the user does not already have the permissions that are needed for the pachyderm service account (kubernetes is preventing privilege escalation). Also, that command relies on the user having the permissions needed to create a cluster role binding. So, the way this should be handled really depends on the cluster. For a user who is just spinning up their own cluster with a default configuration, this command should work fine. For a user who is deploying into a cluster their company owns, they will probably need to speak with their admins to decide how they will get the permissions they will need. It would probably be best to explain this in the RBAC doc we have. It would not be sufficient to just say run that command.

**Comment by JoeyZwicker** [comment]
Thanks for the clarification. The right step would probably be to just mention in the GKE doc something like, "if you're cluster is having permissioning problems, check out our doc on RBAC (link)". That's probably the easiest fix

**Comment by dyngts** [comment]
@brycemcanally Thanks for the explanation. Can you elaborate more for following statement:


>That command is only required if the user does not already have the permissions that are needed for the pachyderm service account (kubernetes is preventing privilege escalation).

What exactly kind of permission that user need to get authorized?

**Comment by brycemcanally** [comment]
Here are the permissions that the pachyderm service account will need.
```
Rules: []rbacv1.PolicyRule{{
	APIGroups: []string{""},
	Verbs:     []string{"get", "list", "watch"},
	Resources: []string{"nodes", "pods", "pods/log", "endpoints"},
}, {
	APIGroups: []string{""},
	Verbs:     []string{"get", "list", "watch", "create", "update", "delete"},
	Resources: []string{"replicationcontrollers", "services"},
}, {
	APIGroups:     []string{""},
	Verbs:         []string{"get", "list", "watch", "create", "update", "delete"},
	Resources:     []string{"secrets"},
	ResourceNames: []string{client.StorageSecretName},
}},
```

**Comment by JoeyZwicker** [comment]
@brycemcanally Is this something that we should be trying to do automatically in `pachctl deploy google` or have it as a separate cmd that users may need to run?

@Nick-Harvey Let's get this minor docs change prioritized a bit.

**Comment by brycemcanally** [comment]
@JoeyZwicker I don't think there is a straightforward way to handle this through our deploy process. The command mentioned just binds the user account to an admin role which I don't think is going to fly in most organizations that have a multi-tenant kubernetes cluster. The way this should probably look in the docs is that we should mention the permissions that the user account needs in order to deploy Pachyderm, but also include that command as a shortcut for the case where they are in a cluster where they can make themselves an admin.

**Comment by Nick-Harvey** [comment]
Instructions added to RBAC Doc
https://docs.pachyderm.io/en/latest/deployment/rbac.html
