### ISSUE TITLE
Error message improvement -- put-file when there is no commit

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2876]
```
pc create-repo images
pc create-pipeline -f ~/pachyderm/doc/examples/opencv/edges.json
pachctl put-file images master -i ~/pachyderm/doc/examples/opencv/images.txt
the branch "master" is nil
```
I forgot the -c flag. 

Typically, doing put-file when there is no open commit returns a useful error message. When forgetting the -c flag in the first put-file, `the branch "master" is nil` isn't a very helpful useful error message. I've never had to create the master branch in the past so the telling that the branch doesn't exist does lead me to figuring out the solution.

**Comment by jdoliner** [comment]
This should probably say,  `the branch "master" has no head` or something like that.
