### ISSUE TITLE
pachd crashes with amazon-region not found when deploying on aws with iam role

### ISSUE THREAD

**Issue by joshcc3** [pachyderm/pachyderm#2878]
**What happened?**:
pachd enters a crash loop when pachyderm is deployed on aws with an IAM role. All other services start up as expected.

**What you expected to happen?**:
pachd starts up successfully.

**How to reproduce it (as minimally and precisely as possible)?**:
After following the instructions mentioned [here](http://pachyderm.readthedocs.io/en/stable/deployment/amazon_web_services.html#deploying-with-an-iam-role)

pachctl deploy amazon ${BUCKET_NAME} ${AWS_REGION} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --iam-role my-iam-role

**Anything else we need to know?**:
The pachyderm-storage-secret doesn't contain the amazon-region and amazon-bucket keys and the code crashes [here](https://github.com/pachyderm/pachyderm/blob/66608401b8bd59ac0799add0c1a256b30cdedeac/src/server/pkg/obj/obj.go#L184)
I suspect it's because the credentials are unset [here](https://github.com/pachyderm/pachyderm/blob/5edfdaddc95c2c85046e9316b9142be0f1dc4d2b/src/server/pkg/deploy/cmds/cmds.go#L223) and as a consequence are not written [here](https://github.com/pachyderm/pachyderm/blob/46599b737d58408f57d91be11ca8ce25598e6c61/src/server/pkg/deploy/assets/assets.go#L1248) when the IAM role is provided?

**Environment?**:
- Kubernetes version (use `kubectl version`):
pachyderm jrc12$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
pachctl version
COMPONENT           VERSION             
pachctl             1.7.1               

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
aws

- OS (e.g. from /etc/os-release):
MacOSX

- Others:

**Comment by joshcc3** [comment]
Thanks for the quick reply!

**Comment by DanielMorales9** [comment]
It occured to me as well, but with credentials.

**Comment by JoeyZwicker** [comment]
@Bryce McAnally <bryce@pachyderm.io> was this shipped?

**Comment by jdoliner** [comment]
This has been fixed and shipped.
