### ISSUE TITLE
Allow input specs' branch/repo names to contain glob patterns

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2882]
There have been a few cases recently where it would make sense to have a dynamically changing set of inputs into a pipeline

Examples:
- DIUX are currently spinning up a new instance of their scoring pipeline for each user submission. This could probably be simplified as a single pipeline that takes in a union of all `*_inference` repos' master branches
- Ingestion from multiple spout processes: each process puts commits into it's own branch on a repo, and one pipeline unions those branches into a single merged commit for actual processing
- Doing post-processing on all stats commits
- Reacting to creation/changes of pipelines by watching all branches on spec repo

A couple possible solutions:

1. ~A `branches` branch, that is automatically updated with, say, a file per branch containing a pointer to the branch's current HEAD commit. A pipeline using this as a trigger could update a pipeline to add inputs. This is probably pretty straightforward, and potentially useful in other places, but still pretty hacky for this use-case (details: #2923)~ Edit: as per @jdoliner 's comment below, the second solution is preferred.
2. Probably a more straightforward solution is to allow pattern-based matching of branch and/or repo names in atom inputs. I am imagining that specifying an atom input in a union or cross with a pattern would effectively expand to be the list of all inputs matching that pattern. It's not 100% clear, however, what should happen if a pattern is specified for a bare atom input -- this should probably be disallowed.  I understand the internals of implementing this might be a bit annoying: probably entails iterating through all inputs to build a list* of patterns to match against any time a new branch or repo is created, and updating the corresponding pipeline infos (my inclination is that a pipeline info should contain the currently-matched set of inputs, rather than the raw pattern -- that can be obtained via [`ExtractPipeline`](https://github.com/pachyderm/pachyderm/blob/master/src/client/admin/admin.proto#L52) )

*: If raw pipeline specs are only stored in the spec repo (ie object store), it may make sense to cache this list in etcd

**Comment by gabrielgrant** [comment]
Another option would be letting `SubscribeCommit()`'s repo and/or branch param either be optional or a glob pattern. Then an external process could either do processing, or perform whatever pipeline adjustments are needed based on commits to the spec repo. In this case, doing so for `FlushCommit()` would probably make sense too

**Comment by jdoliner** [comment]
This seems like a good idea to me.
I don't think I like any of the intermediate solutions to this though. I think we should just wait until we're ready to do 2 and then implement that. This is going to require pushing globs through most of the places where we reference branches and repos, particularly branches will need to be able to have glob based provenance, which means we'll need to have a system for checking new branches against all of the branches with glob based provenance to see if they match. This does get somewhat complicated but I think it's doable.

**Comment by gabrielgrant** [comment]
Expanding on how this would be shown via inspect-pipeline/the dash: my thinking is that we'd have a pipeline spec that the user submits with the wildcard, but the info that comes back from inspect-pipeline is a snapshot of the current DAG structure as matched at the time of the request. So, in the dash, users would see the current DAG structure from the overview, but then delving into any single pipeline would show the list of currently matched inputs, but also the fact that it's a wildcard

**Comment by jdoliner** [comment]
I think closing this in favor of #3820 makes sense. Since it's a broader proposal.

**Comment by marcadella** [comment]
I'd really like to see this feature implemented too! Just an addition since it has not been mentioned: the output branch should be a function of the actual input repo/branches. For instance it could be:
- a constant (as it is today)
- same branch as input1
- a more complex function: "branchInut1_branchInput2"
