### ISSUE TITLE
Design: New Hash Tree Model

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#2893]
**Background:**
Hash trees are currently implemented as a monolithic structure that holds all of the metadata of the file system in one proto. This creates a limit on the number of files we can store in Pachyderm because this data structure needs to be loaded and modified in memory during each operation on it.

**Objective:**
Change the design of hash trees such that they are in the form of subtrees pointed to by a root hash tree node. This will allow us to store much more data in hash trees because we can load only the subtrees that are being accessed/modified, thus removing the need to load the full hash tree into memory on a single node. Also, this will improve performance because we could do access/modifications to different subtrees in parallel and distribute this among Pachd nodes. An implication of this is that we will need to traverse subtrees when accessing/modifying data stored in the hash tree.

**Things to do first:**
Create a more sophisticated benchmarking suite to help identify the pain points when scaling up the amount of data Pachyderm is processing.

**Potential Models:**

- The hash of each path determines the subtree it gets stored in. This is nice because it will be easy to implement, but comes with the downside that we could be potentially accessing a lot of subtrees when performing certain operations (list file for a directory with a lot of files)

- Each subtree stores paths within a certain range and as paths are added, subtrees are split to maintain a certain maximum subtree size (the root hash tree node would store the first prefix of each subtree in lexicographic order). This adds more complexity because we would need to write code that would split the subtrees and update the root at the right time, but it is nice because we would need to access less subtrees in most cases.

**Notes:**

-  The new hash tree will only be one level because the branching factor will allow us to support significantly more files. This means that traversing the hash tree will be quick with either model.

**Open questions:**
1. How does this affect the object caching we currently use? We could route requests to Pachd nodes that have the object currently cached.
2. What are the performance implications of queries that require access to many subtrees? A situation we will run into with the hashing model is that a user is doing a list file on a directory of which each of the files are stored in a different subtree (doing a hash of the path rather than co-locating similar paths will cause this). We can get these trees in parallel and process the request in parallel, but we need to consider whether we care about order when we are merging the data.

**Additional Improvements:**
- For files less than 64 bytes (the object hash size), we can store the actual bytes in the hash tree node rather than storing it in object storage and referencing it with a hash.
- Make object upload one write to object storage instead of two (hash->uuid, uuid->data becomes hash->data)

**Update(05/29/18):**

An idea that seems very appealing is to do hashtree modifications on disk rather than in memory. This would allow us to no longer worry about managing the size of the hashtree, which means we can avoid the complexity of paging subtrees. One way to do this would be to use an embeddedable key-value database such as BoltDB or Badger which would allow us to ship around a database file that would be loaded onto the disk of a node that is making modifications to the hashtree. There is one key downside to this: the download time needed for shipping the full database. One way to address this would be to cache the database file in the cluster and read/write from there while having updates to object storage happen asynchronously. This of course introduces some new problems such as recovering from a crashed cluster.
 
**Side notes:**
- There was also some discussion about using our own implementation of SSTables/LSM, but this did not seem suitable because of the way we merge hashtrees. The main problem was that we would need to traverse the full dataset, or a significant part of it if using bloom filters, to construct a new value for a key because we concatenate values rather than overwriting them. Because of this, we would lose either the quick writes or the quick reads, which means this solution would not be worth the extra complexity it would entail.
- We should also consider lazily merging hashtrees because there are use cases where we would get significant performance gains.

**Comment by jdoliner** [comment]
@brycemcanally you should also be aware of this: https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/hashtree/hashtree_bench_test.go

**Comment by gabrielgrant** [comment]
I really like the idea of in-lining small files. We obviously want to keep these _fairly_ small, but is there any reason that the size needs to be limited strictly to exactly 64 bytes (the size of the hash)? It seems this would be a worthwhile optimization for (somewhat) larger files too

**Comment by jdoliner** [comment]
In-lining is definitely going to be a big improvement. And there's no hard limit on the size threshold we use, it could even be configurable. It should definitely be higher than 64 bytes though, object hashes are 512 bytes.

**Comment by brycemcanally** [comment]
The sha512 hash is actually 64 bytes (512 bits). I used that number because it is the absolute minimum size we should use for in-lining, but it definitely makes sense to in-line larger files and we can discuss what number makes sense when we get to it.

**Comment by jdoliner** [comment]
@brycemcanally just checked an actual FileInfo, you're way less wrong than I was, but there's still 1 wrinkle. Here's one the FileInfo for reference:

```
{
  "file": {
    "commit": {
      "repo": {
        "name": "TestSimplePipeline_data1b51649365e3"
      },
      "id": "f61942aaa2694fb8bf522f5af58abf3c"
    },
    "path": "file"
  },
  "fileType": "FILE",
  "sizeBytes": "3",
  "objects": [
    {
      "hash": "f7fbba6e0636f890e56fbbf3283e524c6fa3204ae298382d624741d0dc6638326e282c41be5e4254d8820772c5518a2c5a8c0c7f7eda19594a7eb539453e1ed7"
    }
  ],
  "hash": "oyiJsC9v26djlDC3ci+ODADeea9N00AI2OBF7Aqttq0="
} 
```

The hash field is actually 128 bytes, that's because it's 64 bytes but it's encoded lexicographically so each byte gets encoded as 2 characters, doubling the length.

**Comment by gabrielgrant** [comment]
Does this issue represent anything close to the final state of where this design landed?

**Comment by brycemcanally** [comment]
@gabrielgrant Nope.
