### ISSUE TITLE
Bulletproof Delete-Commit

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2894]
There are a number of situations in which it can be impossible to call `delete-commit` on a commit. These unfortunately tend to happen when the commit is in some sort of a corrupted state, which is exactly when you want to be able to call `delete-commit`. We should go through that function with a fine toothed comb and make sure all the errors that can potentially be ignored are so the function is as bulletproof as possible.

**Comment by gabrielgrant** [comment]
Would it make sense to have deletes fail on errors by default, and to require `-f` to kill it with fire?

**Comment by jdoliner** [comment]
That makes sense for most errors, we have some really dumb errors though where you get stuff like: `can't delete X because X doesn't exist` which, because deletes often cascade to sub objects can block you from deleting other objects that do exist. Nonexistence shouldn't prevent you from deleting in my opinion, your goal with deleting is to achieve nonexistence. For other errors they should definitely require a `--force` although I'm not sure if having a `--force` flag for commits is going to make sense, there's too many really bad states you can get in by force deleting commits we don't want you to delete.

**Comment by jdoliner** [comment]
We've gone through delete-commit with the proverbial fine toothed comb by fuzz testing it with randomly generated traffic, we found a number of issues that have since been fixed, we haven't seen any unable to delete commit issues since then. Closing, reopen if there are further issues with `delete commit`.
