### ISSUE TITLE
Deploy pachyderm through K8s manifests

### ISSUE THREAD

**Issue by elgalu** [pachyderm/pachyderm#2895]
The current deploy mechanism of pachyderm relies on using the cli: `pachctl deploy ...`

However in enterprise K8s cluster we don't have direct access to the kube API, deployments can only be done via K8s manifests (files) for auditory and traceability.

Do you plan to provide this manifests? or a Helm chart?

**Comment by JoeyZwicker** [comment]
Hi @elgalu. We've got a few options for you. 

First, if you use the --dry-run flag after `pachctl deploy ...`, it'll spit out the full k8s manifest that you can edit and use manually. 

Alternatively, we do have a [Helm chart](https://github.com/kubernetes/charts/tree/master/stable/pachyderm), but it's relatively recent and is still being improved. 

I'm going to close this issue, but feel free to reopen if neither of these solve your requirements
