### ISSUE TITLE
per-job duration increases linearly with the number of commits

### ISSUE THREAD

**Issue by williballenthin** [pachyderm/pachyderm#2896]
**What happened?**: per-job duration increases linearly with the number of commits

**What you expected to happen?**: pachyderm administration overhead increases sublinearly, probably logarithmically, with the number of commits/files.

**How to reproduce it (as minimally and precisely as possible)?**:
  - create pipeline that does minimal work, such as sort an input file into directories
  - create one commit per input file, and create some input files (a thousand or so)
  - note that as jobs complete, `job.finished - job.started` increases linearly

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
$ pachctl version
COMPONENT           VERSION
pachctl             1.6.5
pachd               1.6.5
```
- Cloud provider: AWS, k8s deployed via kops
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Anything else we need to know?**:

Is this behavior expected? Is there a chance of user error? Are there any places I can check/tweak/configure to ensure performance remains close to constant? I would like to be able to push 10s of thousands of files in this manner, but worry about overwhelming overhead.

Below are some diagrams that demonstrate decreasing performance. 

There are three pipelines:
  - `user-idb` is a simple file sort pipeline
  - `idb-push-names` and `idb-sync-fid` do a few seconds of seconds of CPU work, and then HTTP POST their results elsewhere

I created around 1200 commits, each with a single input file. Pachyderm is still catching up. You can see that job durations are increasing, while CPU and network activity remain constant. My interpretation is that pachyderm administration overhead is increasing with each job, file, or commit (unsure which once).

![job-duration](https://user-images.githubusercontent.com/156560/39780427-7a1ee940-52c9-11e8-883c-ea177d57a73a.PNG)

![utilization](https://user-images.githubusercontent.com/156560/39780430-7c3d2700-52c9-11e8-8931-d10975d32bea.PNG)

**Comment by williballenthin** [comment]
Other theories I've considered:

  - overhead from job depth; however, after I stopped creating new input files, job duration continued to increase as before
  - too many processes/threads/tasks running on worker nodes; however, via manual inspection (and CPU utilization charts above), CPU load has remained between 3 and 5 on four core nodes.

**Comment by williballenthin** [comment]
in comparing job logs from early and recent jobs from the same pipeline, I noticed that the time before the first log entry (before `process call started - request: ...`) has increased dramatically. see cherry-picked example below:

*early job*
```
130ms: process call started - request: job_id:"ced77a2e-3f67-4402-81de-e0bb2ea2975e" data:<file_info:<file:<commit:<repo:<name:"idbs" > id:"cdc35bcc1ec243809dc8561248f30d20" > path:"/73665ca317de49300c8a373d180b2b619a8b865e913688120d97635c1c57f8e0" > file_type:FILE size_bytes:4607861 hash:"\025\335c\263y\256\300\342\267\271\374R\214!s\266G\037\330\005\026p_E*8\253\020)j\rw" > name:"idbs" branch:"master" > enable_stats:true
174ms: input has not been processed, downloading data
325ms: input data download took (151.445356ms)
325ms: beginning to run user code
327ms: inputs:
328ms: 73665ca317de49300c8a373d180b2b619a8b865e913688120d97635c1c57f8e0
330ms: input:  73665ca317de49300c8a373d180b2b619a8b865e913688120d97635c1c57f8e0
378ms: WARNING:idb.fileformat:section class not implemented: id2
386ms: INFO:idb.netnode:resolved string netnode Root Node to ff00000000000002
386ms: INFO:idb.netnode:resolved string netnode Root Node to ff00000000000002
420ms: output:
421ms: 00d6cfd5bdf6998f39ce1af16d7b4e6f.i64
421ms: done
422ms: finished running user code - took (97.095435ms) - with error (<nil>)
438ms: starting to upload output
746ms: finished uploading output - took 307.179174ms
```


*recent job*
```
10948ms: process call started - request: job_id:"8e8a712a-a917-40d3-8fc3-62d22c5abd73" data:<file_info:<file:<commit:<repo:<name:"idbs" > id:"1ba6e5d8590141d69a41cd5e5193c046" > path:"/e2cca7bed72a04647422b4d9adc214c9f69acd25bb5ceeacd4e633e7b2ec2c34" > file_type:FILE size_bytes:1273955 hash:"\304\341\306p\332_\335S\350\222\362z\374\303\265\032*mG&/21W\230\211\270\231n\266\257," > name:"idbs" branch:"master" > enable_stats:true
10996ms: input has not been processed, downloading data
11192ms: input data download took (195.252644ms)
11192ms: beginning to run user code
11195ms: inputs:
11196ms: e2cca7bed72a04647422b4d9adc214c9f69acd25bb5ceeacd4e633e7b2ec2c34
11198ms: input:  e2cca7bed72a04647422b4d9adc214c9f69acd25bb5ceeacd4e633e7b2ec2c34
11262ms: WARNING:idb.fileformat:section class not implemented: id2
11289ms: INFO:idb.netnode:resolved string netnode Root Node to ff000002
11289ms: INFO:idb.netnode:resolved string netnode Root Node to ff000002
11315ms: output:
11316ms: 3442f17ac4cb2559d69fcefe79fce345.idb
11318ms: done
11319ms: finished running user code - took (126.904087ms) - with error (<nil>)
11338ms: starting to upload output
11825ms: finished uploading output - took 486.345898ms
```

**Comment by williballenthin** [comment]
in reviewing a slack conversation from earlier, i see this explanation:

> @jdoliner:  so basically what's going on here is that for each commit you create the system needs to figure out what all the datums are for that commit. Then for each datum either process, if it's new, or skip it if it's already been processed, and then merge the results together. Skipping datums is much faster than processing them, but there's still some overhead associated with it since you have to check if you have the right objects in the object store. Because you're committing one datum at a time Pachyderm needs to do n^2 checks for already processed datums to process n datums. One of the major things we're going to make faster is the check for already processed datums. But in the meantime you can make this a lot faster by committing things in batches.

I won't self-close the issue yet to allow for some discussion. I find the existing behavior surprising (though, understanding after explanation), and definitely look forward future enhancements.

**Comment by gabrielgrant** [comment]
To summarize: the number of past commits/jobs has no bearing on processing time of future jobs (other than to potentially reduce the amount of work required, if some of the current job's datums have already been processed), but job runtime _does_ increase linearly with the number of datums in that job (which, in your case, are one-per file).

At the moment, the added overhead of an additional skip-able datum is fairly small (check if it exists in the object store), but non-zero. There are certainly ways to reduce this time (worker-side bloom filter checks being the obvious answer). There are also, however, potentially design changes that could be made to effectively eliminate it (by, say, storing and only processing a diff per commit, rather than scanning all datums), but that gets complicated when files in an upstream commit don't map one-to-one with downstream datums, and would require (much) more significant changes.

**Comment by williballenthin** [comment]
Hey @gabrielgrant thanks for adding to the discussion here!

Would you mind clarifying a bit (so that my future pipelines are most efficient):

> job runtime does increase linearly with the number of datums in that job

So with one datum per job, then overhead is at its minimum?

> At the moment, the added overhead of an additional skip-able datum is fairly small.

Cool, this makes sense to me. In my example above, none of the datums are skippable. Is there an overhead for non-skippable datums? 

Does the increasing overhead reported here comes from having to check "for the new datum, does it match any of the old datums so that i can skip it?". If so, is the correct name for this github issue "per-job duration increases linearly with the number processed datums"? Ultimately, I'm trying to understand the crux of the issue and avoid linear performance degradation as I add commits.

**Comment by williballenthin** [comment]
Whoops, probably just getting tripped up on terminology. I had been using "datum" to refer to a group of files added in a commit that are grouped and processed together.

In the example "user-idb" pipeline from above (and whose contents are below), the inputs are unique files that can be processed independently. 

```
{
    "pipeline": {
        "name": "user-idb"
    },
    "input": {
        "atom": {
            "repo": "idbs",
            "glob": "/*"
        }
    },
    "parallelism_spec": {
        "constant": 1
    },
    "transform": {
        "image": "...",
        "image_pull_secrets": ["dockerhubkey"],
        "cmd": ["/bin/bash"],
        "stdin": [
            "cd /pfs/idbs/;",
            "echo 'inputs: ';",
            "ls -1;",
            "FILE=$(ls -1 | head -n 1); ",
            "echo 'input: ' $FILE; ",
            "IDBMD5=$(python /opt/idb_md5.py $FILE);",
            "FMD5=$(md5sum $FILE | cut -d ' ' -f 1);",
            "mkdir -p /pfs/out/$IDBMD5/$FMD5/;",
            "if [ $(head -c 4 $FILE) = 'IDA1' ]; then ",
            "  cp $FILE /pfs/out/$IDBMD5/$FMD5/$FMD5.idb ;",
            "else ",
            "  cp $FILE /pfs/out/$IDBMD5/$FMD5/$FMD5.i64 ;",
            "fi; ",
            "echo 'output:';",
            "ls /pfs/out/$IDBMD5/$FMD5/;",
            "echo 'done'; ",
            "date > /pfs/out/$IDBMD5/$FMD5/success.txt;",
            "exit 0;"
        ]
    },
    "resource_requests": {
        "cpu": 0.1,
        "memory": "100M"
    },
    "resource_limits": {
        "cpu": 2.0,
        "memory": "500M"
    },
    "enable_stats": true
}
```

**Comment by JoeyZwicker** [comment]
@williballenthin so you're not reprocessing the old datums it sounds like, only processing the new ones that are being added in the new commit. So if you do inspect-job, you should see a number of datums processed and number skipped, right?

**Comment by williballenthin** [comment]
Ah, I see that now:

```
$ pachctl inspect-job 378cca63-622c-4575-b95f-f32fb413b955
ID: 378cca63-622c-4575-b95f-f32fb413b955
Pipeline: p1
Parent: cf6ccaac-5f64-403a-941d-96282e504b2d
Started: 2 minutes ago
Duration: 5 seconds
State: success
Reason:
Processed: 1
Skipped: 151
Total: 152
```

So, as new files are added and processed independently, the other existing files are considered skipped. And there is a constant overhead for each other file that is skipped. So as more files are added to the repo, jobs will take longer and longer. Thanks for walking me through this behavior @gabrielgrant and @JoeyZwicker.

So, given the above, is there anything I can do to keep overhead down, when my use case is to process small subsets of a repo independently? I've heard a suggestion to batch commits to the input repo by @jdoliner, but I think this will only delay the problem, rather than solve it.

**Comment by JoeyZwicker** [comment]
We've got an improvement incoming that will drastically reduce the overhead for skipped files which should pretty much completely resolve this issue.

**Comment by williballenthin** [comment]
For future reference, here are scripts and a pipeline spec to reproduce the behavior described in this issue.

#### p1.json

```
{
    "pipeline": {
        "name": "p1"
    },
    "input": {
        "atom": {
            "repo": "inputs",
            "glob": "/*"
        }
    },
    "transform": {
        "image": "alpine:3.7",
        "cmd": ["/bin/sh"],
        "stdin": [
            "for F in /pfs/inputs/*;",
            "do",
            "  HASH=$(sha256sum ${F} | cut -d ' ' -f 1);",
            "  mkdir -p /pfs/out/${HASH}/;",
            "  ln -s ${F} /pfs/out/${HASH}/${HASH};",
            "done;"
        ]
    },
    "enable_stats": true
}
```

#### setup.sh
```
#!/bin/bash

pachctl create-repo inputs
pachctl create-pipeline -f p1.json
```

#### trigger.sh
```
#!/bin/bash

for i in $(seq 1 1000); do
    echo "$i";
    echo "$i" > "/tmp/${i}.txt";
    pachctl put-file inputs master "$i" -c -f "/tmp/${i}.txt";
    rm "/tmp/${i}.txt";
done
```

#### reset.sh
```
#!/bin/bash

pachctl delete-pipeline p1 --delete-jobs --delete-repo
pachctl delete-repo inputs
pachctl garbage-collect
```

**Comment by williballenthin** [comment]
For my particular scenario, I've found a solution that reduces job overhead. I'll describe it here so that other's can decide if its relevant to their setups. @pachyderm-masters you can close this issue out if appropriate, or maintain it as a discussion thread.

In my scenario, I don't care about file names, only file content. Therefore, I can name inputs as cryptographic hashes of the contents (or anything, really). By placing input files into nested directories derived from their content hash, per-job overhead is reduced to a logarithmic amount.

For example: given file `a.txt` with md5 hash `abcdef012345...`, commit this file to: `/inputs/ab/cd/abcdef012345...`. Downstream pipelines read from `/inputs/*/*/*`. Configuration dials to tune the performance include: number of nested subdirectories, and length of each component.

Here's the per-job duration plots for three strategies:

![computer-science](https://user-images.githubusercontent.com/156560/40014427-c6618288-576d-11e8-8c43-0f22a22a694a.PNG)

1000 input files (though not yet complete processing).

  - p1: naive approach with all input files in same directory
  - p3: nested directory depth two, each component is two characters (branch factor 256)
  - p4: nested directory depth two, each component is one character (branch factor 16)

**Comment by JoeyZwicker** [comment]
@brycemcanally Is this issue fixed by the changes you've been making recently?

**Comment by jdoliner** [comment]
This issue is largely fixed, most of the time here was being spent checking for previously processed datums and performing the merge, these have both been optimized in the append only case to be mostly skipped. With the new storage layer this will get even better, but I think the original ask has been fulfilled here so I'm closing. Feel free to reopen if there are further issues of this sort.
