### ISSUE TITLE
update-pipeline command defaulting to creating the pipeline

### ISSUE THREAD

**Issue by kaktus42** [pachyderm/pachyderm#2899]
I would like the update-pipeline command to have a switch that lets it create the pipeline if it does not exist.

For now I have to do `pachctl update-pipeline -f /tmp/pipeline.json || pachctl create-pipeline -f /tmp/pipeline.json`

**Comment by jdoliner** [comment]
I approve of this, I'm not sure if we need a switch or if `update-pipeline` should just have upsert behavior by default.

**Comment by jdoliner** [comment]
`update pipeline` now has upsert behavior, so use that if you want the pipeline to always get created and aren't worried about overwriting another pipeline with the same name.
