### ISSUE TITLE
PFS HTTP server should serve up CORS header

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2908]
Right now files served by the PFS HTTP server can't be consumed by web apps (including the dashboard) because there is no cross-origin response (CORS) header set. This should be set to accept requests from all domains (`*`)

**Comment by ysimonson** [comment]
@gabrielgrant I think this might be fixed by now, is that correct?

**Comment by gabrielgrant** [comment]
Not as far as I know, though would certainly appreciate if it were, to be able to improve dash file loading perf (for the same reason discussed in #3791 -- I believe right now all displayed file content comes via GRPC and transits through JS before being rendered :grimacing: ; the HTTP server only provides content for "raw" view and file downloads)

**Comment by ysimonson** [comment]
The long-term goal is to phase out this service (#3791), so closing this out
