### ISSUE TITLE
Add exclude glob pattern.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2911]
**What is the ask?**

A way to exclude files from globbing, both in pipelines and in `GlobFile`. This would take the form of an "Exclude" glob pattern, paths that matched the exclude pattern will be excluded.

**What is the goal / desired outcome?**

This is useful if you have a file structure with some files in it that you don't want your pipeline to see.

**If there is a way to accomplish this today via workaround, what does that require?**

You can accomplish this today by having your code ignore datums you don't want to process. This is suboptimal because the datum still gets downloaded and still incurs the processing overhead of a datum.

**Comment by gabrielgrant** [comment]
I'm not sure i follow what this would do/how this would work. Are you thinking something like `!` in .gitignore files? And then it would match everything other than that? (if that's the case, still not sure how datum-ization would happen...)

**Comment by gabrielgrant** [comment]
edit: nvm, misread. this sounds great

**Comment by jdoliner** [comment]
For others who may be confused, the key thing here is that this isn't an extension to globbing, it's just a second glob pattern that, when it matches, excludes that path, rather than including it.

We do support set notation, we also support `!` for exclusion in character ranges, but there's not way to do `{foo, bar, !buzz}`. At least as far as I know, I'm just going off the docs of the library we're using which can be found here: https://godoc.org/github.com/gobwas/glob

**Comment by gabrielgrant** [comment]
Interesting, didn't realize the support was so extensive. Haven't tested, but if I'm reading [this grammar](https://godoc.org/github.com/gobwas/glob#Compile) correctly*, it seems that should be valid, no? I'm not totally sure it whether it would have the same behavior as the new exclude pattern field you're proposing, though.


*: How I'm reading that: `foo`, `bar` and `!buzz` are all valid `terms`, each `term` is a `pattern` and multiple `patterns` can be composed into a `pattern-list`, which, wrapped in`{}` is again a valid `term`/`pattern`

**Comment by adelelopez** [comment]
Implemented in ohmyglob
