### ISSUE TITLE
Update Release Script to update all download links

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2930]
Seems like we don't update the 'other linux flavors' URL.

On the docs site I see:

```
# For OSX:
$ brew tap pachyderm/tap && brew install pachyderm/tap/pachctl@1.7

# For Debian based linux (64 bit) or Window 10+ on WSL:
$ curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v1.7.2/pachctl_1.7.2_amd64.deb && sudo dpkg -i /tmp/pachctl.deb

# For all other linux flavors
$ curl -o /tmp/pachctl.tar.gz -L https://github.com/pachyderm/pachyderm/releases/download/v1.7.1/pachctl_1.7.1_linux_amd64.tar.gz && tar -xvf /tmp/pachctl.tar.gz -C /tmp && sudo cp /tmp/pachctl_1.7.1_linux_amd64/pachctl /usr/local/bin
```

[Our script doesn't seem to update this one](https://github.com/pachyderm/pachyderm/blob/master/etc/build/release_version)

**Comment by gabrielgrant** [comment]
FWIW, it looks like you're looking at an out-dated version of the docs (1.7.2 vs current is 1.7.3) Noted this issue last week (#3002) and updated the latest docs in #3003

**Comment by gabrielgrant** [comment]
@msteffen does this also address the page title issue? #3022
