### ISSUE TITLE
1.7.2 Newline needed on put-file -c deprecation message

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2951]
When running a script containing these a few `put-file -c calls`, i'm seeing this output:
```
flag --commit / -c is deprecated as of 1.7.2, you will get the same behavior without itflag --commit / -c is deprecated as of 1.7.2, you will get the same behavior without itflag --commit / -c is deprecated as of 1.7.2, you will get the same behavior without itpath () invalid: only printable ASCII characters allowed
flag --commit / -c is deprecated as of 1.7.2, you will get the same behavior without itpath () invalid: only printable ASCII characters allowed
flag --commit / -c is deprecated as of 1.7.2, you will get the same behavior without itpath () invalid: only printable ASCII characters allowed
```

**Comment by jdoliner** [comment]
So it seems we're missing a newline on this message. But I think the invalid characters message is coming from somewhere else.

**Comment by gabrielgrant** [comment]
ok, yea, @brycemcanally thinks the invalid character message is coming from his new validation code. I'll try to track that down with him/file another issue

**Comment by jdoliner** [comment]
This has been fixed. We should probably remove that message since it's been deprecated for a while.
