### ISSUE TITLE
Proposal: Spout/ingestion Pipelines

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2958]
**What is the ask?**

I need a way to ingest continuously-streaming data into pachyderm. I think a notion of an ingestion/spout pipeline is the most elegant solution to this: basically pipeline processes that run continuously, outputing data, and have some way of signalling to pachyderm that the data stream they've written (probably just to /pfs/out) can be processed as a commit.

**If there is a way to accomplish this today via workaround, what does that require?**

For some workloads today, this can effectively be accomplished by polling with a cron pipeline. That doesn't work for truly continuous data streams (eg twitter firehose), processes that receive "push" messages (eg webhooks), and is far from ideal for anything where the "hit rate" on polling is sparse (ie where the interval between new data appearing in the polled source is long, but latency requirements on time from that data appearing until processing begins is short). In these cases, running a spout process outside of pachyderm is the only viable option.

The other (kinda) workaround is what we've done for `git` and `cron` inputs: to bake these spouts into pachyderm itself. Special casing each of these is obviously not tenable in general, though

This kind of relates to #2387, in that we need to devise some more explicit inter-process signalling mechanism beyond just having the process end

**Comment by thedrow** [comment]
See #1482 for another use case.
I have data in Kafka that I want to commit to pachyderm without doing so periodically.

**Comment by gabrielgrant** [comment]
There are some more use-cases in #2242 (in general, these pipelines seem like the most likely candidates for sharing between users)

**Comment by gabrielgrant** [comment]
@adelelopez do you think your implementation in #3531 sufficient to call this issue resolved? if not, what's left to be done?

**Comment by adelelopez** [comment]
I wouldn't feel comfortable saying that until I have the Kafka demo working... I've uncovered some issues with this implementation which I think need to be addressed first.

**Comment by ysimonson** [comment]
This is now implemented, including the Kafka demo
