### ISSUE TITLE
What should the behavior of incremental be when a job fails?

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2961]
It seems right now that if an incremental pipeline fails, then when it goes to process the next commit, the user's code sees the diff against the grandparent (ie two commit's worth of data)

On the one hand, this behavior is understandable, given my understanding of how it's implemented. On the other hand, this can have some weird consequences if the specific way data is batched is meaningful, and the order of batches matters, because there is no way to recover this order info from one of these "double-batch" diffs

Imagine incrementally processing batches of transactions. Each gets written into some directory with an opaque transaction ID, and you want to maintain a list of the batches, in order, for some downstream process. A simple incremental pipeline that just appends the dirname onto a text file would work in general, but will produce fail if multiple batches are present. This could be updated to handle the case of multiple batches and just append them both to the list, but AFAICS there's no way to do so and ensure the ordering of the two batch IDs appended is correct

Just want to clarify/confirm: is the current behavior (clear semantics, but potentially more work for users, and makes some operations impossible) actually what we want? or do we need to specify the expected behavior more and make implementation changes? 

One possible alternate behavior would be to have a new input commit trigger a "catch-up" job for each of the previous diffs that has failed to process correctly. It seems to me the ideal case may be to have each of these produce a new commit on the output that has the same parent as failed commit, but I understand this doesn't really match with the current provenance model. An alternative might be to trigger a job that again attempts to fill in the already-created null commit, but I'm not sure if editing commits after the fact is a good idea either.

**Comment by jdoliner** [comment]
We no longer have incremental jobs, so this no longer applies, we may readd them in which case this will be one of the issues we have to deal with. But I think it makes sense to close for now and revisit it in a design issue for incremental jobs.
