### ISSUE TITLE
Worker pods run in privileged mode

### ISSUE THREAD

**Issue by jkinkead** [pachyderm/pachyderm#2979]
**What happened?**:

Worker pods run with `privileged: true`

**What you expected to happen?**:

Worker pods do not run in privileged mode. This is not suitable for our shared tenant cluster.

**Anything else we need to know?**:

Workers require privileged mode because [they run `syscall.Mount`](https://github.com/pachyderm/pachyderm/blob/a512eb4e55e574c8a0268d530d320444befa7170/src/server/worker/api_server.go#L1393-L1400), which requires privilege.

I don't know if other areas require privilege. This usage looks like it could be replaced by a symbolic link.

This is related to #2813 .

**Environment?**:
- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION                                          
pachctl             1.7.3
pachd               1.7.3

**Comment by JoeyZwicker** [comment]
@jdoliner didn't we removed the need for privileged here: https://github.com/pachyderm/pachyderm/pull/2887?

I guess not for worker pods?

**Comment by jdoliner** [comment]
@jkinkead this unfortunately isn't easily replaced with a symlink. That's actually how the behavior used to be implemented, but we found that with some container images the symlink would silently fail and show up as an empty directory. Switching was the only way we could find to implement it that worked with all containers.

@JoeyZwicker yeah, that was only for pachd.

**Comment by jkinkead** [comment]
Did you figure out a set of conditions under which symlinks would fail?

Would it make sense to make this a pipeline option (noprivileged flag or similar)?

**Comment by delwaterman** [comment]
Any update on this?

**Comment by jdoliner** [comment]
Small update on this, I think we have found a path forward on this that will allow us to use symlinks. I'm not sure if we'll be able to land the fix before the 1.8 release but it should come out in a 1.8.x release or 1.9 at the latest.

Thanks for bearing with us.

**Comment by jdoliner** [comment]
Pachyderm workers have checked their privilege.
