### ISSUE TITLE
Pipelines have access to pachyderm Kubernetes service account credentials

### ISSUE THREAD

**Issue by jkinkead** [pachyderm/pachyderm#2990]
**What happened?**:

Pipelines have access to Pachyderm service account credentials. These are mounted in `/var/run/secrets/kubernetes.io/serviceaccount`, and are readable from the executing pipeline.

This allows users on all cloud providers access to the Kubernetes API at the same level as the Pachyderm user, allowing them to create jobs, pods, and perform any other action Pachyderm is permitted to perform.

**What you expected to happen?**:

Pachyderm service account credentials are not exposed to running pipelines.

**Comment by jdoliner** [comment]
I think this could probably be removed without causing too much trouble now that scaling up and down workers is handled by the pps master. I don't think there's anything else that we need it for, but I could be mistaken.
