### ISSUE TITLE
Support header row/metadata with put-file --split

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3000]
**What is the ask?**

I need a way to specify metadata be written separately when running `put-file --split`

**What is the goal / desired outcome?**

So that I can, in the simplest case, put a CSV file with a header row and have it be treated sensibly. Right now the header row gets split and written out as a datum just like every other row.

**If there is a way to accomplish this today via workaround, what does that require?**

Not _that_ big a deal with a local file, but in the same way we considered the advantage of splitting remote files and standardizing the practice enough to justify creating a flag for it, this pattern also seems to warrant canonicalizing it as a best practice:

```
pachctl start-commit myrepo master
head -1 myfile.csv | pachctl put-file myrepo master metadata/header.csv
tail -n +2 myfile.csv | pachctl put-file myrepo master data --split line
pachctl finish-commit myrepo master
```

**Comment by jdoliner** [comment]
We now have first class support for headers (and footers) for files.
