### ISSUE TITLE
Different version numbers of pachyderm linked in install docs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3002]
Right now the version of pach linked in the install script differs between the deb package (1.7.3) and the non-deb linux tarball (1.7.2): http://docs.pachyderm.io/en/latest/getting_started/local_installation.html#pachctl

I can fix this manually in the rendered output, but i thought that updating this version number was automated somehow as part of the release process, so not sure how this discrepancy happened (or if it's not automated, perhaps it should be?)

**Comment by gabrielgrant** [comment]
@msteffen i think this is permanently fixed by #3014, right? (as well as the temp fix in #3003)

**Comment by jdoliner** [comment]
Yup, this seems to be fixed. Closing.
