### ISSUE TITLE
Restore doesn't pass caller's auth credentials to pachd

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3011]
Currently, if a cluster enables auth, Extract/Restore stops working because Restore makes internal RPCs but doesn't propagate the caller's auth information

**Comment by JoeyZwicker** [comment]
When we make this change along with #3012, we should probably extract/restore the activation token as well. This stops users from having to call `activate` again, but also stops users who abuse enterprise trial tokens with multiple email addresses from just extract/restoring their cluster easily.
