### ISSUE TITLE
Set up https://cla-assistant.io/

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3015]
Adds a github PR check for CLA signature, and a bot that requests CLA signature if missing. Seems simple to set up, and saves having to check/request CLA signatures manually: https://cla-assistant.io/

**Comment by jdoliner** [comment]
I'd be down for this. We had something like this at one point and they went out of business which was when we switched to wufoo. Wufoo has been pretty simple and worked though so I wouldn't say this is a burning need.

**Comment by Nick-Harvey** [comment]
cla-assistant has been configured and added to the repo.
