### ISSUE TITLE
Incremental doesn't work on downstream pipelines.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3017]
**What happened?**:

Incremental doesn't work if the input is the output of another pipeline. The output directory shows up blank.

**What you expected to happen?**:

It should work the same as if the input was a pure input. (`/pfs/out`) should be populated.

**How to reproduce it (as minimally and precisely as possible)?**:

Create an incremental pipeline downstream from another pipeline.

**Comment by jdoliner** [comment]
We have a fix for this in code review right now.

**Comment by jdelfino** [comment]
Great, thanks @jdoliner!
