### ISSUE TITLE
inspect-job lists latest image for the pipeline, rather than the image that was actually used

### ISSUE THREAD

**Issue by jdelfino** [pachyderm/pachyderm#3024]
**What happened?**:

While trying to debug some older pipeline runs, I noticed that `inspect-job` is returning the latest image specified for the pipeline, rather than the image used for a particular job. Note that we are using docker image digests to specify images, instead of tags.

```
-- 21:31 $ pachctl inspect-job 05b8336b98c64cc59dc3c0e666aa000b
ID: 05b8336b98c64cc59dc3c0e666aa000b
Pipeline: <pipeline name>
Started: 22 hours ago
Duration: 27 seconds
State: success
Reason:
Processed: 1
Failed: 0
Skipped: 0
Total: 1
Data Downloaded: 1.276MiB
Data Uploaded: 0B
Download Time: Less than a second
Process Time: Less than a second
Upload Time: 11 seconds
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER              JOB                 DATUM               STARTED             QUEUE
Restarts: 3
ParallelismSpec: constant:1
ResourceRequests:
	CPU: 0
	Memory: 64M

Input:
{
  "atom": {
    "name": "<pipeline name>",
    "repo": "<pipeline name>",
    "branch": "master",
    "commit": "0e8f18bb4b9446ea831368cb03a041f8",
    "glob": "/*"
  }
}

Transform:
{
  "image": "<image>@sha256:1accbc5cf0886e34a6b1da88bda7a50776b0a3c310f3332fcef7ab740e376599",
  "cmd": [
    "<cmd>"
  ]
}
Output Commit: 73b511b7ca594fcbbfcca2113e047c1a
```

Note in the above that the job ran 22 hours ago, and references an image with digest `1accbc5cf0886e34a6b1da88bda7a50776b0a3c310f3332fcef7ab740e376599`. Looking in our container registry, the image with that digest was uploaded 2 hours ago, so it's impossible that it was used in a job run 22 hours ago. Note that `1accbc5cf0886e34a6b1da88bda7a50776b0a3c310f3332fcef7ab740e376599` is the current digest used in the latest update of the pipeline. 

**What you expected to happen?**:

I expect the job metadata to retain the exact image digest used for the job.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a pipeline using an image with a digest instead of a tag. Run the pipeline. Push a new version of the image, and update the pipeline with the new image digest. `inspect-job` on the old job, and note that it lists the new image digest.

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`):
```
COMPONENT           VERSION
pachctl             1.7.1
pachd               1.7.1
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): gke

**Comment by jdelfino** [comment]
@gabrielgrant I haven't tried with tags, and unfortunately it's not trivial for me to switch things around - digests are fairly baked into how we push images & pipelines right now.

**Comment by jdoliner** [comment]
@jdelfino no worries, we understand the issue and have enough to fix it. And I don't think tags are going to work as a workaround.
