### ISSUE TITLE
Prometheus polluting logs with errors

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3027]
On a fairly-fresh cluster, I'm seeing hundreds of log lines like this: `2018-06-29T20:46:40Z WARNING authclient.API.WhoAmI [error registering prometheus metric &{{0 {0xc420d08840} 0xc420b9a070 1 []}}: who_am_i_seconds_count duplicate metrics collector registration attempted]`

@sjezewski thought this might have something to do with @msteffen 's TLS changes?

**Comment by ysimonson** [comment]
@mdaniel it's driving me crazy too. I'll dig in sometime soon.
