### ISSUE TITLE
PersistentVolumeClaimis not bound: "etcd-storage-etcd-0" (repeated 3 times)

### ISSUE THREAD

**Issue by shayshahak** [pachyderm/pachyderm#3032]
hi, if your pod is stuck on:
etcd-0                   0/1       ContainerCreating
and you see using the describe command:
kubectl describe pod etcd-0
you get the error in the title

then what you need to do in order to fix it is to manually add the SPN on the resource group where the Storage Account is. you can find the SPN on the long resource group that's been created using the "Access Control" button.

Shay

**Comment by shayshahak** [comment]
I'm referring to the deployment on Azure:
https://github.com/pachyderm/pachyderm/blob/master/doc/deployment/azure.md

**Comment by jdoliner** [comment]
@shayshahak thanks for the report.

Just to make sure I'm understanding correctly you're past the issues you're describing here and are documenting how you did it so we can add it to our docs. We'd be happy to do so, would you mind clarifying a bit about what you're saying here. Particularly what does SPN stand for and what does one need to do to add it to the resource group where the Storage Account is? It may be easiest to communicate that with screenshots of the Azure console.

Also, you may not know the answer to this, but I recently deployed on Azure and didn't have to do anything with SPN or Storage account, it seemed to just work for me. Do you have any idea what might be different between our Azure setups that required you to do this but not me?

**Comment by shayshahak** [comment]
hi Joe, thanks for your reply. moving our conversation to private emails

**Comment by shayshahak** [comment]
Hi Joe,
Bug has been fixed, I confirmed it in my internal lab.
Sorry for the hassle.

Shay

**Comment by jdoliner** [comment]
@shayshahak no hassle at all, thanks for taking the time to check on this.
