### ISSUE TITLE
pachctl completion only supports bash. add support for zsh (+ others?)

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3035]
**What happened?**:

`pachctl completion` seems to be buggy. Error into `open /etc/bash_completion.d/pachctl: no such file or directory` and if path is created manually, it installs the completion but does not really 'do' completion 

**What you expected to happen?**:

`pachctl completion` should handle the missing path and create if absent or ask for alternate path. When installed, it should assist with completion

**How to reproduce it (as minimally and precisely as possible)?**:

`pachctl completion` 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.10.4
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): both  bash and zsh - same behaviour 
- Others:

**Comment by suneeta-mall** [comment]
@JoeyZwicker Creating path to leads to successful install, but the behaviour before and after install is same i.e. no command completion is performed.

**Comment by jdoliner** [comment]
@suneeta-mall did you restart your shell after installing? I just tried it on my machine and it worked perfectly.

**Comment by suneeta-mall** [comment]
This is what I see:
```
> pachctl completion                        
open /etc/bash_completion.d/pachctl: no such file or directory
sudo  mkdir -p /etc/bash_completion.d/
Password:
> pachctl completion                              
Permission error installing completions, rerun this command with sudo:
$ sudo env "PATH=$PATH" pachctl completion
open /etc/bash_completion.d/pachctl: permission denied
> sudo env "PATH=$PATH" pachctl completion
Bash completions installed in /etc/bash_completion.d/pachctl, you must restart bash to enable completions.
```
On a new shell post install:
> pachctl <tab> 
hands me new files from current dir. 

I have zsh and I am on mac - perhaps thats whats different.

**Comment by jdoliner** [comment]
@suneeta-mall it's bash completion, you're not going to see anything in zsh.

**Comment by jdoliner** [comment]
We unfortunately haven't had the time to write zsh completion, and cobra doesn't support it as nicely so it's more work than bash completion. I use zsh too.

**Comment by suneeta-mall** [comment]
doh! I missed that bit. Thanks for pointing out .. would love to have zsh completion

**Comment by ysimonson** [comment]
cobra has support for zsh completions now: https://godoc.org/github.com/spf13/cobra#Command.GenZshCompletion

**Comment by Nick-Harvey** [comment]
Another zsh user here :) would love to have this added

**Comment by itssimon** [comment]
Me too!

**Comment by ysimonson** [comment]
This seems more important now that zsh is the default shell for macOS
