### ISSUE TITLE
failure alerts blocks access to setting page

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3038]
Please see the issue with UI error/warning alerts. It renders UI completely unable. 

<img width="1128" alt="screen shot 2018-07-09 at 2 38 41 pm" src="https://user-images.githubusercontent.com/25972660/42430996-078e874e-8386-11e8-9d08-86e45150865a.png">

**Comment by JoeyZwicker** [comment]
Thanks for submitting this. We’ve already filed a internal report on this issue and will have a quick fix and new dash release out shortly. Really sorry you’re hitting this issue
