### ISSUE TITLE
Jobs get wedged after a updating a pipeline with `--reprocess` multiple times in quick succession.

### ISSUE THREAD

**Issue by jdelfino** [pachyderm/pachyderm#3045]
**What happened?**:
Jobs get wedged after a updating a pipeline with `--reprocess` multiple times in quick succession.

Digging in a bit, I see this in the raw logs:
```{"pipelineName":"<pipeline name>","workerId":"pipeline-<name>-v10-lpzzg","ts":"2018-07-12T13:52:00.086231497Z","message":"worker: watch closed or error running the worker process: job's version (8) doesn't match pipeline's version (10), this should automatically resolve when the worker is updated; retrying in 13.502824341s"}```

`kubectl get pods` shows v10 is running:
```
pipeline-<name>-v10-4bdcb                             2/2       Running   0          23m
pipeline-<name>-v10-4bmks                             2/2       Running   0          23m
pipeline-<name>-v10-55dx5                             2/2       Running   0          23m
...
```

`pachctl list-jobs -p <name>` shows 2 jobs that think they are running (note first and last lines):
```
2500e8912a1d483eb3e3e69e4abfb00e <name>/a4e0b23d454440158c4d01a3da4f9100 26 minutes ago -             0       0 + 0 / 158063         0B       0B       running
3464159fd57c417b94a1a58474462693 <name>/95f8a5b10ba248d8b7e0ee383b0acdc2 18 hours ago   23 minutes    0       563 + 156148 / 151412  49.14KiB 155.5MiB success
735b8f41ee334c86963dacfe3c4d4ffb <name>/b28b9de29b1d4683913c7cd558806554 19 hours ago   34 minutes    0       0 + 150886 / 150886    0B       0B       success
c93063b08a60434dac46388f4b6a9da9 <name>/89293db918994242ab05bda827930818 19 hours ago   30 minutes    0       1056 + 154354 / 150886 120.8KiB 393.5MiB success
...
6ef11c3f7efe494db6fc1ee7de1e5222 <name>/4220777b3f7d4d6e96b8d698a68f2d85 38 hours ago   45 minutes    0       2 + 141708 / 141710    168B     134.9KiB success
a61dc215e6bd45c2ad08101e63a38d17 <name>/23f1356683594d79a239daf4c7b97116 38 hours ago   40 minutes    1       276 + 145682 / 141710  22.85KiB 59.71MiB success
18d84336e8ac414fac1b692fe43a09fd <name>/c99b497e825b448fac57d713eafa709a 39 hours ago   About an hour 0       0 + 143557 / 141436    0B       0B       running
```

After running `pachctl delete-job 18d84336e8ac414fac1b692fe43a09fd`, everything unwedges and job `2500e8912a1d483eb3e3e69e4abfb00e` starts moving.

**What you expected to happen?**:
The new job to run immediately

**How to reproduce it (as minimally and precisely as possible)?**:

I believe this happens when I run `pachctl update-pipeline` with `--reprocess` and a new image version more than once in quick succession. I haven't tried to explicitly reproduce, but have hit this several times over the past few days.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
-- 21:31 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```

-- 21:31 $ pachctl version
COMPONENT           VERSION
pachctl             1.7.4
pachd               1.7.4
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE

**Comment by gabrielgrant** [comment]
Thanks for the report, @jdelfino -- you're right that this does sound like a race
