### ISSUE TITLE
glob pattern for a static file that doesn't exist

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3068]
**What happened?**:
job goes into infinite restart loop stuck in "starting"
```
56cd7af30335445d948238587d1124c7 suneeta/4232b4d9520e437a83168c0b0337ebcf 5 minutes ago  -                  29      0 + 0 / 0 0B       0B   starting
```

**What you expected to happen?**:
User code should run but have zero datums

**How to reproduce it (as minimally and precisely as possible)?**:

Create a pipeline with a glob pattern for a file that doesn't actually match anything. 

Example:
        "atom": {
          "glob": "/non_existent_image.jpg",
          "repo": "repo1"
        }
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mdaniel** [comment]
It cheerfully generates seemingly infinite error messages on the pod output, too:

```console
$ k -n pach3 logs -c user pipeline-bug3059-v1-lf79v
{"pipelineName":"bug3059","workerId":"pipeline-bug3059-v1-lf79v","master":true,"ts":"2019-01-31T18:53:35.797259216Z","message":"Launching worker master process"}
{"pipelineName":"bug3059","workerId":"pipeline-bug3059-v1-lf79v","master":true,"ts":"2019-01-31T18:53:35.906952171Z","message":"waitJob: 99a5bfc771044c5d87f61813e4f4c743"}
{"pipelineName":"bug3059","workerId":"pipeline-bug3059-v1-lf79v","master":true,"ts":"2019-01-31T18:53:36.045082494Z","message":"error in waitJob rpc error: code = Unknown desc = file \"/yankeedoodle\" not found, retrying in 351.593438ms"}
{"pipelineName":"bug3059","workerId":"pipeline-bug3059-v1-lf79v","master":true,"ts":"2019-01-31T18:53:36.428705637Z","message":"error in waitJob rpc error: code = Unknown desc = file \"/yankeedoodle\" not found, retrying in 645.653563ms"}
{"pipelineName":"bug3059","workerId":"pipeline-bug3059-v1-lf79v","master":true,"ts":"2019-01-31T18:53:37.192060452Z","message":"error in waitJob rpc error: code = Unknown desc = file \"/yankeedoodle\" not found, retrying in 1.204507436s"}
...
```

**Comment by JoeyZwicker** [comment]
Yeah we should fix this, especially because it's a valid use to have a glob pattern that might purposely not match anything at times.
