### ISSUE TITLE
Enable more tests on travis

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#307]
Currently we're disabling the tests at `src/server/pfs/fuse` and `src/server/pps/persist/server` since they won't pass on Travis.

**Comment by sjezewski** [comment]
This has been fixed by the changes in issue #270. The fuse tests (all server tests) are now running [succeeded on travis](https://travis-ci.org/pachyderm/pachyderm/builds/124342428)

Closing since this is now redundant
