### ISSUE TITLE
Document support for secrets as env variable in pipeline specification 

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3075]
**What is the ask?**
Could you please support secrets as ENV variables  in pipeline specifications (http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html) as well ? 
see "Using Secrets as Environment Variables" https://kubernetes.io/docs/concepts/configuration/secret/

Currently it only supports as volume mount AFAICT

**Comment by jdoliner** [comment]
Hi @suneeta-mall we actually do have this feature it's just not documented, sorry about that. Here's an example of what it would look like:

```json
{
  "secrets": [{
    "name": "secret",
    "env_var": "secret",
    "key": "key"
  }]
}
```

this will take `key` from `secret` in k8s and bind it to `$secret` in the environment of your process.

**Comment by suneeta-mall** [comment]
https://github.com/pachyderm/pachyderm/pull/3076

**Comment by suneeta-mall** [comment]
I am closing this given its merged
