### ISSUE TITLE
pachctl glob-file behaves strangely because bash expands 

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3084]
**What happened?**:

Because bash expands the glob pattern, glob-file thinks I'm sending it a list of all the files in my cwd:

```
$ pachctl glob-file test master *
expected 3 arguments, got 57

Usage:
  pachctl glob-file repo-name commit-id pattern [flags]

Flags:
      --raw   disable pretty printing, print raw json

Global Flags:
      --no-metrics   Don't report user metrics for this command
  -v, --verbose      Output verbose logs
```

**What you expected to happen?**:
It would be great if this could Just Work, but afaik there isn't any way to tell bash to not expand a glob. Maybe next best thing would be to make it very clear at the top of this error message that the glob pattern needs to be quoted?

**Comment by jdoliner** [comment]
There's nothing we can really do here, we neither control that error message nor bash's behavior. I also think it's a pretty reasonable error message that should allow people to figure out what's going on, and this error message is also the one you'll get if you accidentally type an extra argument, which is much more common, and will be incredibly confusing to people if they get back some error message about globs when they don't even know what that is.
