### ISSUE TITLE
v1.0 documentation list

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#309]
I have had a long list locally, but it makes more sense to have it open for everyone to add to.

GH Docs:
- [x] Deployment on K8s, AWS, locally @derekchiang 
- [x] Contributor guide @derekchiang 
- [x] Release notes
- [x] pipeline spec guide @JoeyZwicker
- [x] document stat tracking
- [x] Design Goals @sjezewski 

Quickstart guide:
- [ ] GOPATH common errors
- [x] pachctl mounting/connection
- [x] grep pipeline needs "image" specified, even though it uses default `ubuntu`. Users are getting confused about how to connect other containerized analysis. 
- [x] update mount command (see #339) @sjezewski 

- [x] FAQ
- [x] Git for data paradigm and terminology document @JoeyZwicker
- [x] Expand help messages: @jdoliner 
     - [x] e.g. pachctl put-file -- help message outdated
- [x] Godocs API @jdoliner 
- [x] Docs for delete/overwrite behavior (described in #303) @derekchiang @sjezewski 

Website: @JoeyZwicker
- [x] Front page copy
- [x] Navigation bars
- [x] About Us
- [x] Use cases
- [x] remove/fix "deploy on AWS" --> GCE

- [x] Explainer video
- [x] In the news
- [x] News letter sign up
- [x] Follow/star buttons
- [ ] Make dropdown menu not ugly

- [x] Check all docs/site for correct links @JoeyZwicker and everyone else

**Comment by derekchiang** [comment]
We need to be explicit about the version of kubernetes/kubectl that we are supporting.  See #327

**Comment by sjezewski** [comment]
Turns out we are already explicit about kubectl version in SETUP.md but we should probably mention it before the one-liner (the first thing you see on readme.md) ?

**Comment by sjezewski** [comment]
And we need to update how we run / mount FUSE. I'm doing it w sudo, but our docs don't use sudo. Again, see #327

**Comment by sjezewski** [comment]
Writing this down so we don't forget --- we also discussed going a 'Pachyderm Design Principles' or goals page, where we'd discuss:

- Reproducibility
- Incrementality
- Collaboration
- Data Provenance
