### ISSUE TITLE
inconsistency in datum seen by downward pipelines

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3097]
**What happened?**:
There are two pipelines P1 and P2. P2 feeds off input from P1. 

# P1 

P1 is scheduled pipeline that run periodically. P1 creates several commits and completes the jobs. 

```
pachctl  list-job | \grep  --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn  P1
013a2e67b78a4f48941a78f6b2b15be6 P1/23f1f57791c64c9ca6d234386d5dae89      2 hours ago    About an hour  0       34 + 190 / 224 24.66KiB 7.845MiB success 
8f7e7de62a684b318192c521b65336dc P1/d4d9fc5b54d74cdead26fd7b692eac19      8 hours ago    7 hours        0       0 + 197 / 197  0B       0B       success 
c7a91f0e480348ab858d49855f9a82d7 P1/1054585cccb2406d8e8e3992ddd50592      14 hours ago   13 hours       1       12 + 185 / 197 9.092KiB 2.608MiB success 
e9448aed051b4674b23301f7e88aba38 P1/4d07d4b1e1254b1283aa780435c672ad      20 hours ago   19 hours       0       116 + 77 / 193 83.94KiB 26.32MiB success 
f9f842b626cc4016a929fa071597c2e7 P1/fb0f57bc2d0342faa7ba78c43eddb579      26 hours ago   25 hours       0       55 + 28 / 83   40.45KiB 12.31MiB success 
72cc1434b998433fbce49d1982f1f44d P1/ba765c7548854f099e9a32d7867328cf      32 hours ago   30 hours       0       0 + 28 / 28    0B       0B       success 
6f96e58a59df4de59fa4428816d86cd4 P1/77530c79125744fda37a8ce583469271      38 hours ago   36 hours       0       0 + 28 / 28    0B       0B       success 
bbd33466a40644fc8b3767e0a9c86fe7 P1/33b2450d9201432490ada841eb463430      44 hours ago   42 hours       0       0 + 28 / 28    0B       0B       success 
8160cd8866af43a586379adbd7b8f376 P1/06e3574f7b53430a8da25ca3103bd503      2 days ago     2 days         0       0 + 187 / 215  0B       0B       failure 
62945f36bc534b8287863a83b36d4b12 P1/0ef54f1e09e4415d907aafd953104fad      2 days ago     2 days         0       0 + 187 / 215  0B       0B       failure 
65addea3e0d142b89a87395a44f3feeb P1/f689b619b8e34192bacfe27ab6168407      2 days ago     2 days         0       70 + 117 / 215 51.14KiB 15.76MiB failure 
6a373f84f0fa4c7a940e486e3bf38b3a P1/0e7a7b42d7254af99f182b48951c9ae5      2 days ago     2 days         0       135 + 0 / 163  97.65KiB 31.43MiB failure 
e06376aeab2b4351916af726f5c36b7c P1/3aba47fa9a59491bac56997b9eb9b103      3 days ago     2 days         0       14 + 14 / 28   9.952KiB 3.158MiB success 
7447c1271d484279a5add9e51cf7d4ef P1/769d725959534de5acfb5dc23ae45d6e       3 days ago 2 days             0       15626 + 0 / 15626 10.92MiB 3.504GiB success 
```

One inspect job on job that did massive processing: `pachctl inspect-job 7447c1271d484279a5add9e51cf7d4ef`
```
ID: 7447c1271d484279a5add9e51cf7d4ef 
Pipeline: label-masks  
Started: 3 days ago 
Duration: 2 days 
State: success
Reason: 
Processed: 15626
Failed: 0
Skipped: 0
Total: 15626
Data Downloaded: 10.92MiB
Data Uploaded: 3.504GiB
Download Time: 15 minutes
Process Time: 8 days
Upload Time: 2 hours
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER              JOB                 DATUM               STARTED             QUEUE               
Restarts: 0
ParallelismSpec: constant:3 
ResourceRequests:
	CPU: 0
	Memory: 64M 

Input:
{<>}
Output Commit: 769d725959534de5acfb5dc23ae45d6e  
Stats Commit: e6851c65e97349048a4c70c63c7f806d 
```

List files on latest and massive job on P1 pipeline:
**Massive job**
`pachctl list-file label-masks 769d725959534de5acfb5dc23ae45d6e "/*/*/*/*.hdf5" | wc -l`
>   45168
**Latest job**
`pachctl list-file label-masks 23f1f57791c64c9ca6d234386d5dae89 "/*/*/*/*.hdf5" | wc -l`
     640

# P2
```
pachctl  list-job | \grep  --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn  P2
75638e10276a432988212f43c6398ca4 P2/694a48ed886243a49fd098f69c83a465      24 minutes ago -              0       480 + 0 / 627  1.702GiB 3.54GiB  running 
07f6172e7834423b86ab9dff8e644659 P2/38c7fe1fb0a44066a353bc7c97e836cc      2 hours ago    About an hour  0       180 + 0 / 627  653.4MiB 1.288GiB killed  
```
Inspect job on only running job on this P2 pipeline:
```
ID: 75638e10276a432988212f43c6398ca4 
Pipeline: P2  
Started: 25 minutes ago 
State: running
Reason: 
Processed: 540
Failed: 0
Skipped: 0
Total: 627
Data Downloaded: 1.914GiB
Data Uploaded: 3.984GiB
Download Time: 47 seconds
Process Time: About an hour
Upload Time: 4 minutes
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER                          JOB                                DATUM                                                                                    STARTED                  QUEUE               
pipeline-P2-v2-l2snq   75638e10276a432988212f43c6398ca4   <>.hdf5   3 seconds ago            1                   
pipeline-P2-v2-v7ljh   75638e10276a432988212f43c6398ca4   <>.hdf5   3 seconds ago            1                   
pipeline-P2-v2-z4x84   75638e10276a432988212f43c6398ca4   <>.hdf5   Less than a second ago   1                   
Restarts: 0
ParallelismSpec: constant:3 
ResourceRequests:
	CPU: 0
	Memory: 64M 

Input:
{
  "cross": [
    {
      "atom": {
        "name": "P1",
        "repo": "P1",
        "branch": "master",
        "commit": "23f1f57791c64c9ca6d234386d5dae89",
        "glob": "/*/*/*/*.hdf5"
      }
    },
    {
      "atom": {
        "name": "sample-areas",
        "repo": "sample-areas",
        "branch": "master",
        "commit": "68736f0a10a8488a82784b2b4e7092eb",
        "glob": "/"
      }
    }
  ]
}
Output Commit: 694a48ed886243a49fd098f69c83a465 
```

It is only seeing datum from latest commit. 

Please note the I have tried several permutation combination of pausing-start pipeline and cleaning and restarting P2 from scratch. It seems P2 only see the to commit for some reason. Running with `--reprocess` flag has no affect what so ever i.e. running with reprocess does not force it to replay all commits of P1 pipeline. I have created this https://github.com/pachyderm/pachyderm/issues/3098 for reprocess problem but feel free to close it if its user error and I am mistaken

**What you expected to happen?**:
P2 to see all datums of P1 not just latest. 

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by suneeta-mall** [comment]
@jdelfino Created this based on info I have got. Please let me know if anything else is required.

**Comment by jdoliner** [comment]
This is the intended behavior, when you create or update a pipeline the intent of that is to have the pipeline's output repo be kept up to date with the heads of the branches it's targetting, processing historical commits isn't part of the intent, although it happens as a natural consequence of the head commit becoming a historical commit as new commits are added. But everything that a pipeline processes was at one point the head of the input branches while the pipelines existed. There are several reasons for this, by far the biggest is that it doesn't make sense with our delete semantics. The most common use case for `delete-file` is to get rid of data that messes up processing in some way, either causing it to fail or to take a really long time, perhaps hanging forever. If we processed old datums then at best it would greatly delay when you got out real results from the new pipeline because it would force the pipeline to go through a bunch of failed jobs before it processed a commit that might succeed, at worst it would prevent you from getting results all together, because it would reprocess the datum that made the code hang. If you want historical datums to be processed when you update the pipeline then you should avoid deleting (or overwriting) those datums and instead keep them present in the head of the branch.
