### ISSUE TITLE
reprocess flag is ignored ? 

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3098]
**What happened?**:
Whats the behaviour of `--reprocess` ? Would it replay the failed jobs? As per doco, http://docs.pachyderm.io/en/latest/fundamentals/updating_pipelines.html#re-processing-data, I get impression it will replay all the commits

I have a pipeline that shows status as 
`Job Counts:
starting: 0	running: 0	failure: 2	success: 2`

I process it with `--reprocess` flag and I expect it to reprocess all commits on updated spec irrespective of job status. But new pipeline pod that came up when triggered with reprocess just sits there with log message at"
```

{"pipelineName":"P4","workerId":"pipeline-P4-v4-2zpd7","ts":"2018-07-30T11:31:22.203098048Z","message":"skipping job 8941c57ac4ea41ca89610bb50fdd0f7a as it is already in state JOB_SUCCESS"}
{"pipelineName":"P4","workerId":"pipeline-P4-v4-2zpd7","ts":"2018-07-30T11:31:22.204677049Z","message":"skipping job 0f8e414c7e334a82b7d0f5852445bbe0 as it is already in state JOB_SUCCESS"}
{"pipelineName":"P4","workerId":"pipeline-P4-v4-2zpd7","master":true,"ts":"2018-07-30T11:31:22.204883415Z","message":"Launching worker master process"}
{"pipelineName":"P4","workerId":"pipeline-P4-v4-2zpd7","ts":"2018-07-30T11:31:22.206230341Z","message":"skipping job 79675e1141234e7c8ca5e0897a1801c2 as it is already in state JOB_FAILURE"}
{"pipelineName":"P4","workerId":"pipeline-P4-v4-2zpd7","ts":"2018-07-30T11:31:22.207727198Z","message":"skipping job 7553d73174544c1689a0f68a9559172c as it is already in state JOB_FAILURE"}
```

I expected it to churn though all 4 commits 2 success and 2 fail. 

Please close this issue if I am wrong but I think something is wrong here and reprocess should process all 4 commits irrespective. 

reprocess is started as `pachctl update-pipeline -f p4.json --reprocess` nothing fancy here 

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by gabrielgrant** [comment]
The intention of `--reprocess` is not to re-process historical _commits_, but to short-circuit pachyderm's computation deduplication so user code will be run for all _datums_ in the current head commit: normally any datums that have already been processed by a previous job will be `skipped` if they appear in the latest commit, and the previous result will be reused in the current job's output commit. The `--reprocess` flag ensures that a job will not skip any of it's datums. 

Hope that makes sense?

**Comment by jdoliner** [comment]
`update-pipeline` will only process the head commits of the input branches, not historical commits, for reasons described [here](https://github.com/pachyderm/pachyderm/issues/3097#issuecomment-408985941). `--reprocess` has no effect on which commits get processed, it affects whether or not we skip previously processed datums or use cached versions of them. To confirm, are you seeing no new jobs getting processed here, or a single job? The prior would be a bug, the latter is expected.

**Comment by suneeta-mall** [comment]
Thanks guys.. I will close this
