### ISSUE TITLE
Failures/interruptions during egress leave job in running state

### ISSUE THREAD

**Issue by jdelfino** [pachyderm/pachyderm#3109]
**What happened?**:
We have egresses that can take some time - 20+ minutes. I've notice that if a job is interrupted while egressing (usually by a pipeline update, although I've also seen this happen when an upstream pipeline fails while a previous egress is finishing), the job is left marked as `running`. The job can't be stopped at this point, because the commit is finished. The only way to clean it up is to delete it.

**What you expected to happen?**:
The job to be properly listed as killed/failed.

**How to reproduce it (as minimally and precisely as possible)?**:
I have not intentionally triggered this, so don't have specific steps, but I believe you could trigger by running a job with a long egress, and running `update-pipeline` on it while it is egressing.

**Environment?**:
- Pachyderm CLI version (use `pachctl version`): 1.7.4

**Comment by jdoliner** [comment]
Thanks for reporting this @jdelfino this is definitely something we can get fixed.

No worries on not having a repro, we can figure this one out internally.

**Comment by workflow** [comment]
Stil running into this problem as of version `1.9.3`, would love to see a fix as well :)

**Comment by workflow** [comment]
@jdoliner Any update on this by any chance? :bowing_man:

**Comment by JoeyZwicker** [comment]
@workflow Sorry, this issue might have slipped through the cracks. We'll double to check to see if its still an issue and, if so, will get it slotted in for a fix. Sorry again!

**Comment by Tryneus** [comment]
This should be fixed in 1.11 by #4572, which adds a separate `EGRESS` state for jobs.
