### ISSUE TITLE
failed to read stats tree error

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3127]
**What happened?**:
Every once in a while we see this our pipelines:
```
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:32:18.127522732Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:32:18.865062169Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:32:24.060873373Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:32:31.226821739Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:35:30.034400407Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:36:53.335867679Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:37:11.237990860Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
{"pipelineName":"P1","workerId":"P1-v6-h7lq7","master":true,"ts":"2018-08-15T21:37:32.094315523Z","message":"failed to read stats tree, this is non-fatal but will result in some missing stats"}
```

**What you expected to happen?**:
I am not sure what cause this but I seem to be getting this a lot. 

**How to reproduce it (as minimally and precisely as possible)?**:
NA

**Anything else we need to know?**:
Let me know what other info I can provide. At this point, I dont have much but just the error. 

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Pachyderm CLI version (use `pachctl version`): 1.7.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
@suneeta-mall was this pipeline run for a while without stats enabled and then had them turned on later?

**Comment by suneeta-mall** [comment]
The pipeline always had stats enabled from beginning - its only 5/6 days old pipeline on a fresh cluster with enterprise key enabled from start ..

**Comment by jdoliner** [comment]
This is likely explained by issues we had where writing an object could error and in certain situations we'd fail to notice the error and retry. Since it's probably fixed and we don't have a concrete repro to check I'm going to close this. Feel free to reopen if you hit this again.
