### ISSUE TITLE
Add DNS Breakdown section to AWS deploy Docs

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3138]
**What is the ask?**
When deploying Pachyderm Enterprise on AWS, customers should be informed about the different  DNS options, expand on their effects, and provide suggestions on which route to take.

[Kops Documentation has layed down some of the work](https://pachyderm.readthedocs.io/en/stable/deployment/amazon_web_services.html) 

**What is the goal / desired outcome?**

The goal is to have a more prescriptive install doc for customers 

**If there is a way to accomplish this today via workaround, what does that require?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
This is no longer needed as the default DNS works. Closing this issue out.
