### ISSUE TITLE
Expose previous pipeline versions.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3144]
**What is the ask?**

I want to be able to view previous versions of pipelines.

**What is the goal / desired outcome?**

So that I can audit how the pipeline has changed over time.

**If there is a way to accomplish this today via workaround, what does that require?**

Theoretically this can be done today by directly accessing the pipelines branch in `__spec__` and then unmarshalling the protocol buffer found in there. This is probably a bit too unwieldy to qualify as a real workaround though. However, architecture wise, this is everything we need, so the ask here is to take that information and make it into a usable API. The first thing we want is a way to display that previous versions of a pipeline exist. This will just be an `int64` field in `PipelineInfo` called `versions`. The next question is what you can do to interact with these versions. I can see 2 paths to exposing this. The first is to have an `int64` field `previous` on `InspectPipelineRequest`, `ExtractPipelineRequest` and maybe some other pipeline rpcs, and a corresponding flag `--previous n` so you would interact with it like this:

```sh
# look at foo
$ pachctl inspect-pipeline foo
# look at the previous version of foo
$ pachctl inspect-pipeline foo --previous 1
# inspect the previous previous version of foo
$ pachctl inspect-pipeline foo --previous 2
```
The second way to do this is rather than having a flag we could bring our algebraic commit syntax over to pipelines, so the above would instead be:

```sh
# look at foo
$ pachctl inspect-pipeline foo
# look at the previous version of foo
$ pachctl inspect-pipeline foo^
# inspect the previous previous version of foo
$ pachctl inspect-pipeline foo^^
```

I'm leaning toward the second option since it's more terse and consistent with our existing syntax for commits.

Another important use case for this is reverting a pipeline to previous versions. Once we have this syntax it becomes pretty easy to do that, since you can do `ExtractPipeline` for a previous version (using either syntax) and then pass that to `update-pipeline`. However it'd be nicer if there was single command to do that.

I think we might want to add a `from` field to `CreatePipelineRequest` which can point to another pipeline to get the spec from. So you could do:

```sh
$ pachctl update-pipeline foo --from foo^
```
And that would revert `foo` to its previous version, this would also allow you to create a pipeline as a copy of another with:

```sh
$ pachctl create-pipeline foo --from bar^
```

Create pipeline `foo` which is a copy of the previous version of `bar`.

**Comment by gabrielgrant** [comment]
This all sounds great, and will enable features we've wanted in the dash for a while.

for accessing historical versions from the CLI, I also prefer the commit-style syntax, rather than numerical indexing. Under the hood in the API, however, I'd be inclined to use a `version` field, rather than a `previous` field. This would have to be 1-indexed (assuming we want the default value to be the latest), and using negative numbers to walk backwards from the most recent

**Comment by jdoliner** [comment]
I think if we go with the commit-style syntax then that's likely going to be true at the API level as well. I.e. you'll pass protocol buffers that have a pipeline named `foo^^` This is the way it works for commits as well, parsing actually happens server side. This has the advantage that it works across all clients, not just the cli.

**Comment by gabrielgrant** [comment]
@jdoliner is this all implemented? (and documented? ;) )

**Comment by jdoliner** [comment]
We have ancestry syntax but we still want `pachctl list-pipeline --history` to work.

**Comment by jdoliner** [comment]
Subsumed by #3634
