### ISSUE TITLE
Broken link : example machine learning workflows

### ISSUE THREAD

**Issue by ro7m** [pachyderm/pachyderm#3151]
Broken link : example machine learning workflows on this page https://pachyderm.readthedocs.io/en/latest/cookbook/ml.html#examples on clicking some example pipelines it opens up http://docs.pachyderm.io/en/latest/examples/readme.html#machine-learning which says " SORRY This page does not exist yet."

**Comment by JoeyZwicker** [comment]
Thanks for pointing this out! We'll definitely work on getting that fixed @Nick-Harvey
