### ISSUE TITLE
Add docs to help debug dash loading issues

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3153]
This will probably need more context/links for someone new to pachyderm, but this should at least help others familiar with the different pieces to track down problems (and is a good starting point for a general troubleshooting doc):

If the dash shows a blank page, or a browser error page, the content isn't being served correctly:
- is `pachctl port-forward` running properly (if needed -- it won't be required in some production deployments, or if connecting directly to the minikube IP)
- can you curl the dash address from the command line?
- is the dash pod running? (check with `kubectl get all`)

if the dash is hanging on the pachyderm loading page, there's a problem getting info from pachd over the websocket connection via the grpc-websocket proxy. the first thing i usually try is to connect directly to the websocket port (so if i'm accessing the dash at http://localhost:30080, i just change the browser address to http://localhost:30081)

if the grpc proxy websocket port is working correctly (ie properly exposed and the service is running), then that should show a page that says Upgrade Required. In that case there's likely a problem connecting from the proxy to pachd. On the other hand, if loading that page hangs, or gives a connection error or something, then the problem is likely between your computer and the proxy

If it's a problem between the proxy and pachd (connecting to the proxy over http shows`Upgrade Required`):
- confirm that if the websocket is connected: in the browser's dev tools' network tab, you should see the websocket connection(s), and they will likely show the state as "pending"
- do you have the right pachd address loaded in pachd-address.txt?
  - compare what the browser shows in the dev tools "Network" tab to what is shown as the internal address of the pachd service in kubectl get all. if those are different, that's likely the problem:
    - try hard refresh (shift + click refresh) to get the latest pachd-address.txt
    - if that's still wrong, kill the dash pod so it re-fetches that address, then hard-refresh again

if it's a problem between your machine and the  (connecting to the proxy over http hangs/errors out):
- is port-forward running properly?
- do you need to be explictly adding `?host=something` or `?port=something` to the dash URL?
- do you have firewall rules, a load balancer, or some other network troll blocking your connection to the proxy?

**Comment by mindthevirt** [comment]
Dash 2.0 is actively under development and going to replace the current dashboard. Connection issues will be documented for Dash 2.0
