### ISSUE TITLE
dry-run install and undeploy out of sync

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3167]
**What happened?**:
Deploy pachyderm with dry-run yamls:
```
$ kubectl apply -f deploy-dev.yaml                                                                                                                                        serviceaccount/pachyderm created
clusterrole.rbac.authorization.k8s.io/pachyderm created
clusterrolebinding.rbac.authorization.k8s.io/pachyderm created
storageclass.storage.k8s.io/etcd-storage-class created
service/etcd-headless created
statefulset.apps/etcd created
service/etcd created
service/pachd created
deployment.apps/pachd created
service/dash created
deployment.apps/dash created
secret/pachyderm-storage-secret created
```

Undeploy:
```
$ pachctl undeploy -a                                                                                                                (ml-
By using the --all flag, you are going to delete everything, including the
persistent volumes where metadata is stored.  If your persistent volumes
were dynamically provisioned (i.e. if you used the "--dynamic-etcd-nodes"
flag), the underlying volumes will be removed, making metadata such repos,
commits, pipelines, and jobs unrecoverable. If your persistent volume was
manually provisioned (i.e. if you used the "--static-etcd-volume" flag), the
underlying volume will not be removed.

Are you sure you want to proceed? yN
y
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
clusterrole.rbac.authorization.k8s.io "pachyderm" deleted
clusterrolebinding.rbac.authorization.k8s.io "pachyderm" deleted
storageclass.storage.k8s.io "etcd-storage-class" deleted
No resources found
No resources found
```

**What you expected to happen?**:
Undeploy should delete resources no matter how it was provisioned `dry-run` or not.
It use to work as expected before something broke with 1.7.5 -> 1.7.9 I think 

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
Is Pachyderm deployed in a namespace? I think it might be that `undeploy` is deleting the unnamespaced resources here `clusterrole` `clusterrolebinding` and `storageclass` are all cluster scoped, not namespace scoped, but it's missing the other resources because they're in the namespace. If you pass the `--namespace` flag it should be able to find the relevant resources.

This interface could probably use a bit of work, it's a little tricky though because it needs to take into account the case where there's 2 clusters deployed in different namespaces.

**Comment by suneeta-mall** [comment]
Ah yeah sorry my bad .. I forgot namespace arg .. my bad
