### ISSUE TITLE
Setup DNS / Ingress for Hosted Cluster

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#3171]
We want `hub.pachyderm.io` to be routed to the ELB for this cluster.

We need

- ports open for pachctl
- ports open for hub (which contains the dash)
- the right type of timeout to be setup for the websocket connection for the dash (default ELB idle timeout is too low and makes the reconnections pile up in the dash) ... I think this may require us to use an ALB or perhaps just tune the timeout

SSL

- an SSL cert setup for this domain / terminated at the ELB
- then setup port 443 to serve the hosted application (hub) via SSL
- setup the web socket port to use wss and also get terminated via SSL (since its the same hostname / diff port the same cert should work ok)

**Comment by gabrielgrant** [comment]
Broader issue here is comprehensive docs/process/scripts defining what a production-grade Pachyderm deployment looks like

**Comment by ysimonson** [comment]
This has been moved to several new tickets
