### ISSUE TITLE
General thoughts for improving performance on GKE using Pachyderm 1.8

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#3178]
**Increasing ingress throughput:**

Setup a node pool that consists of one big machine for Pachd. To ensure that Pachd is scheduled on this machine, create a node taint during pool creation time that applies to the created pool. Then, modify the Pachd deployment such that it has an appropriate toleration. Also, bump up the limit of CPUs and memory available for Pachd based on the size of the machine.

Example:
`gcloud container node-pools create pachd-pool --cluster pach-cluster --scopes storage-rw --machine-type n1-standard-16 --num-nodes 1 --node-taints dedicated=pachd:NoSchedule`

This command creates a node pool for the "pach-cluster" cluster with the node-taint "dedicated=pachd:NoSchedule"

The corresponding toleration in the Pachd deployment spec should be:
```
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "pachd"
  effect: "NoSchedule" 
```

**Increasing upload performance:**

Create the kubernetes cluster with an ssd as the boot disk. Also, you can scale up the disk size to improve performance since IOPS and throughput increase with disk size in GCP.

Example:
`gcloud container clusters create "pach-cluster" --scopes storage-rw --machine-type "n1-standard-4" --num-nodes=10 --disk-type "pd-ssd" --disk-size=200` 

This command creates a cluster called "pach-cluster" with a boot disk type of "pd-ssd" and a size of 200GB. This means that each node will have 200GB available to read and write from.

**Increasing merge performance:**

Increase the number of hashtrees (hashtree spec) in the pipeline spec. This number determines the number of shards for the filesystem metadata. In general this number should be lower than the number of workers (parallelism spec) and should not be increased unless merge time (the time before the job is done and after the number of processed datums + skipped datums is equal to the total datums) is too slow.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/929615524065415)

**Comment by JoeyZwicker** [comment]
This is some brain-dump details for a future performance optimization doc that will need to be written eventually. That doc will still require additional input from Bryce at a future time.

**Comment by Nick-Harvey** [comment]
Pull request created: https://github.com/pachyderm/pachyderm/pull/3351

**Comment by Nick-Harvey** [comment]
Merged
