### ISSUE TITLE
Document glob-file better around shell glob expansion

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3181]
```
pachctl glob-file <repo> master /*
expected 3 arguments, got 21
```

Joe Doliner [11:11 AM]
 glob patterns have a bit of a gotcha in that your shell will also expand them, so if you do `/*` then that's going to get expanded to all of the files at the root of your local filesystem, that's why it's complaining about too many arguments. If you put it in quotes that'll prevent your shell from expanding it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/929614107710209)

**Comment by Nick-Harvey** [comment]
Updated https://github.com/pachyderm/pachyderm/blob/master/doc/pachctl/pachctl_glob-file.md with a note to help users avoid the issue.
