### ISSUE TITLE
Delete-commit doesn't clean up stats commit correctly

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3183]
**What happened?**:
Running normal openCV demo with stats:true for edges pipeline. Deleting commits seems to have left some hanging commits (probably stats commits) that have provenance that no longer exists. 

```JosephZckersMBP:demo joeyzwicker$ pc list-commit images
REPO   ID                               PARENT STARTED           DURATION           SIZE
images bb43143a866a41489d1851dfa3d7e428 <none> About an hour ago Less than a second 714.2KiB
JosephZckersMBP:demo joeyzwicker$ pc list-commit edges
REPO  ID                               PARENT                           STARTED           DURATION  SIZE
edges 2b4391dd71e6468ea2aa8e0d99aab860 <none>                           About an hour ago 1 second  390.3KiB
edges a84e2a21c07642edb9edc87893ddb3a2 <none>                           About an hour ago 1 second  1.089MiB
edges 8ebfbcf2cdf642c5a6d04bf37623827a <none>                           About an hour ago -         -
edges 58bb97ce81814878b406192a1892d608 5a62771d2f204a9786d869f0c6c9e83d About an hour ago -         -
edges 389d1acdb61845e38906da79b5b0c61f <none>                           About an hour ago 4 seconds 390.3KiB
edges 5a62771d2f204a9786d869f0c6c9e83d <none>                           About an hour ago 4 seconds 1.091MiB
JosephZckersMBP:demo joeyzwicker$ pc inspect-commit edges 8ebfbcf2cdf642c5a6d04bf37623827a --raw
{
  "commit": {
    "repo": {
      "name": "edges"
    },
    "id": "8ebfbcf2cdf642c5a6d04bf37623827a"
  },
  "started": "2018-10-16T00:01:17.628980417Z",
  "provenance": [
    {
      "repo": {
        "name": "edges"
      },
      "id": "118e2ff3cb14437fb9a4870b53dabba5"
    }
  ],
  "branchProvenance": [
    {
      "repo": {
        "name": "edges"
      },
      "name": "master"
    }
  ]
```
There's only 1 commit in images, because I added a bunch of commits, called update-pipeline -f edges a few times (w/ and w/o reprocess), and then started deleting commits from images. There shouldn't be so many commits in edges. Some of them reference other edges commits that no longer exist and are missing a tree, but the commit-info still exists. 

**What you expected to happen?**:
All stats commits to be properly deleted when their provence is deleted. 

**How to reproduce it (as minimally and precisely as possible)?**:
I don't have 100% nailed down repro steps yet, but something along these lines:
1. set up opencv demo and create multiple input commits. Make sure stats is turned on for edges.
2. Call update pipeline (w/ and w/o reprocess, i'm not sure if that makes a difference) on edges.
3. add a few more input commits
4. start deleting commits from images, especially not the HEAD commit (e.g. delete-commit images master^3)

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
pachyderm version 1.7.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by kevindelgado** [comment]
@JoeyZwicker I believe this has been fixed by #3585. My suspicion is that by improperly computing provenance in the subset in the `propagateCommit` step this enabled commits to hang around after commits they were provenant on had been deleted.

My methodology for verifying this has been to  run
```
pachctl delete-all
pachctl create-repo images
pachctl put-file images master liberty.png -f http://imgur.com/46Q8nDz.png
pachctl create-pipeline -f stats_edges.json
pachctl create-pipeline -f https://raw.githubusercontent.com/pachyderm/pachyderm/master/examples/opencv/montage.json
pachctl put-file images master AT-AT.png -f http://imgur.com/8MN9Kg0.png
pachctl put-file images master kitten.png -f http://imgur.com/g2QnNqa.png
pachctl update-pipeline -f stats_edges.json
pachctl put-file images master dog1.png -f http://imgur.com/XgbZdeA.png
pachctl put-file images master dog2.png -f http://imgur.com/Qz4bU.png
pachctl update-pipeline -f stats_edges.json --reprocess
pachctl put-file images master dog3.png -f http://imgur.com/A8eQsll.png
pachctl put-file images master dog4.png -f http://imgur.com/fOKhA.png
```
and pepper in various `delete-commit` calls and confirm that all commits in all repos (especially edges) don't contain any provenance to deleted commits.

Let me know if there is anything else you'd like to try or would me to verify before closing this issue out

**Comment by JoeyZwicker** [comment]
If you were able to repro initially and couldn't any longer after the fix, feel free to close. I can test it further when it get released

**Comment by kevindelgado** [comment]
Yup, repro'd before and after, closing.
