### ISSUE TITLE
master not found error with put-file into open commit

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3184]
**What happened?**:
When doing put-file into an open commit, get `master not found` error, but the file(s) still get put into the commit correctly. Haven't found any other effects other than an incorrect error message. 

```
pc list-commit images
REPO ID PARENT STARTED DURATION SIZE
JosephZckersMBP:demo joeyzwicker$ pc start-commit images master
9dd26fda14474f33bebe546b711e69ed
JosephZckersMBP:demo joeyzwicker$ pachctl put-file images master -r -f set1
pachyderm/1.7.0/pachyderm_pfs/openCommits/ master not found
JosephZckersMBP:demo joeyzwicker$ pc list-file images master
NAME TYPE SIZE
set1 dir  78.7KiB
```

**What you expected to happen?**:
No error message since everything seems to be working fine

**How to reproduce it (as minimally and precisely as possible)?**:
above
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
pachctl 1.7.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by ysimonson** [comment]
@JoeyZwicker did you observe _all_ of the files in `set1` being put in correctly? I'm only seeing one file being put.

Here's my `set1`:

```
$ ls set1/
1VqcWw9.jpg  9iIlokw.jpg  FsPcjlw.jpg  LV1Ap55.jpg  VnOxwyl.jpg  bXHb7sT.jpg  lgLYAVq.jpg  sqgLozf.jpg
2GI70mb.jpg  Bx36V6G.jpg  GWYejkj.jpg  MVcakFW.jpg  VyAlcbq.jpg  foDqKls.jpg  lrkcRaq.jpg  statue.jpg
3Kr6Mr6.jpg  C0cqLzA.jpg  JzO6aky.jpg  QAmyGmE.jpg  Wv84dI2.jpg  g9v1Q6N.jpg  nkC6fxH.jpg  tG4pKeg.jpg
4Vp1OMR.jpg  F8FbGHL.jpg  JzYTdvw.jpg  RMknOd5.jpg  XrFx4gJ.jpg  iEGTqhO.jpg  sJtIFf0.jpg  uNJQvA4.jpg
7mNRGwN.jpg  FdMlBz1.jpg  LKzpo4V.jpg  U76TTRm.jpg  ZEyfHJE.jpg  k0gFmm6.jpg  sTAMXEp.jpg  yt1olXP.jpg
```

...vs what's in PFS after running `pachctl put-file images master -r -f set1`:

```
$ pc list-file images master set1
COMMIT                           NAME              TYPE COMMITTED    SIZE     
5ad7cf4c98ea4650b914c3fcd28dc466 /set1/4Vp1OMR.jpg file 49 years ago 218.6KiB 
```

**Comment by ysimonson** [comment]
Timestamp bug moved to a separate issue: https://github.com/pachyderm/pachyderm/issues/3328

**Comment by ysimonson** [comment]
The error is being produced here: https://github.com/pachyderm/pachyderm/blob/5e11c8dff04cbd297f9e39f69df3d40c3bfc2193/src/server/pfs/server/driver.go#L3010

Not sure why yet.
