### ISSUE TITLE
Figure out how to get gifs to work with ReadtheDocs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3201]
e.g. http://docs.pachyderm.io/en/latest/cookbook/deferred_processing.html is broken but works fine on GH

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/929615493943528)

**Comment by Nick-Harvey** [comment]
Fixed. You need to use the markdown syntax for RTD to create the image correctly i.e `![my gif image](path/to/image.gif)
