### ISSUE TITLE
Clarify distinction between `lazy` and `empty_files` in "lazy shuffle" example doc

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3209]
The "lazy shuffle" example added in #3202 is implemented correctly in terms of code (ie only using `empty_files`), but the explanation (and even the title) conflate `lazy` with `empty_files`. These aren't the same thing in Pachyderm, and afaiu actually using `lazy` here would be ill-advised. Is there a reason basically all references to "lazy" in that PR shouldn't be changed to "empty files"?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/939777983401619)

**Comment by JoeyZwicker** [comment]
Agreed. I’ll correct the example docs to empty files.

**Comment by lbliii** [comment]
https://pachyderm.atlassian.net/browse/DOC-164
