### ISSUE TITLE
Expand KubeFlow example to leverage TFjobs

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3210]
We need to expand https://github.com/kubeflow/examples/pull/282 to leverage the TFJob part of KubeFlow

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/929614113195980)

**Comment by mindthevirt** [comment]
Closing in favor of new KFData proposal, worked on by the integrations team. 
[KFData Initiative ](https://docs.google.com/document/d/1ccIM5-khU52HuZKSujRmgDyzxyzJZ6cmI597uqdh-ek/edit)
[KF Data presentation](https://docs.google.com/presentation/d/1LlVk-5Ua-GdNClekHbj-4b6Nt5-whU4LdU0VAVWLFoE/edit#slide=id.p)
