### ISSUE TITLE
pachctl list-repo and inspect-repo size estimates are incorrect

### ISSUE THREAD

**Issue by zebesta** [pachyderm/pachyderm#3211]
**What happened?**:
`pachctl list-repo` and `pachctl inspect-repo` listed repo size estimates that are false and unbelievable, e.g. `16EiB`.

**What you expected to happen?**:
pachctl should be able to provide realistic size estimates

**How to reproduce it (as minimally and precisely as possible)?**:
Not entirely sure, but both repos that are exhibiting this behavior have had committed files deleted from them.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): N/A
- Pachyderm CLI version (use `pachctl version`):
pachctl v1.7.5
pachd v1.7.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): N/A
- OS (e.g. from /etc/os-release): N/A
- Others: N/A

**Comment by gabrielgrant** [comment]
@ysimonson i believe you recently fixed some problems with displayed repo size, right? would that have addressed this issue?

**Comment by ysimonson** [comment]
Yes, this should be fixed now. @zebesta would you be able to try this again against the repo that was bugging out?

**Comment by JoeyZwicker** [comment]
I wasn't able to repro with the steps where I was in the past. Closing for now, but definitely reopen if you hit this again.
