### ISSUE TITLE
Broken link to "our team" in readme.

### ISSUE THREAD

**Issue by discdiver** [pachyderm/pachyderm#3222]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:
Clicked on the "our team" link in the readme
<img width="1045" alt="screen shot 2018-11-19 at 8 21 08 am" src="https://user-images.githubusercontent.com/7703961/48709856-b6f67780-ebd4-11e8-97b6-10888dd6d231.png">
 in the sentence: "Learn more about our team and email us at jobs@pachyderm.io."

Result: 404 Error

Link is to:
http://www.pachyderm.io/jobs.html

**What you expected to happen?**:
Wasn't directed to a working webpage.

**How to reproduce it (as minimally and precisely as possible)?**:
Reproduce by clicking the link in the readme

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
Fixed. Thanks!
