### ISSUE TITLE
Older Pachyderm version docs do not point correctly to the latest version link.

### ISSUE THREAD

**Issue by cbzapata** [pachyderm/pachyderm#3224]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:
Older pachyderm website, eg. Pachyderm v1.2.1, showed up higher when googling, but when trying to go click v1.7.11 link for latest documentation, led to "Maze" page.

E.g.
https://pachyderm.readthedocs.io/en/v1.2.1/getting_started/troubleshooting.html#
says "You are not reading the most recent version of this documentation. v1.7.11 is the latest version available." 
but v1.7.11 goes to the wrong link 
"https://pachyderm.readthedocs.io/en/v1.7.11/getting_started/troubleshooting.html" 
which says "SORRY This page does not exist yet."

**What you expected to happen?**:
It should reference the correct link:
http://docs.pachyderm.io/en/latest/managing_pachyderm/general_troubleshooting.html

**How to reproduce it (as minimally and precisely as possible)?**:
https://pachyderm.readthedocs.io/en/v1.2.1/getting_started/troubleshooting.html
Click 'v1.7.11' in the "Note You are not reading the most recent version of this documentation. v1.7.11 is the latest version available." box

**Anything else we need to know?**:
Same thing happens to https://pachyderm.readthedocs.io/en/v1.2.1/development/updating_pipelines.html
Link does not go to correct link.
https://pachyderm.readthedocs.io/en/v1.7.11/fundamentals/updating_pipelines.html
Instead goes to:
https://pachyderm.readthedocs.io/en/v1.7.11/development/updating_pipelines.html

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release): OS
- Others:

**Comment by JoeyZwicker** [comment]
Thanks @cbzapata. 

What's happening here is that between those old versions and current versions of docs, those urls have been removed or renamed/moved and ReadTheDocs isn't handling that linking correctly. We'll investigate and mostly like will just get rid of the docs from super old versions.

**Comment by Nick-Harvey** [comment]
I went ahead and created redirects for these pages, but the bigger issue is still at large I believe. I'll take a look and see what we need to do to properly fix it (i.e old doc versions being properly retired)

**Comment by JoeyZwicker** [comment]
@Nick-Harvey We still have docs from 1.4 showing up. Is this closed because you have a fix in for everything or is "the bigger issue is still at large" -- in which case we should reopen and figure out how we want to proceed there
