### ISSUE TITLE
Killing job stuck in running creates new job instead of changing status

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3227]
Just wanted to document this issue for the future if we start seeing it again. We don't have all the info or clear repro steps yet, but will fill out those details as we gather them

**What happened?**:
When a job is stuck in running state (possibly from egress issue) and the job get killed and user deletes the pod (to restart it), list-job now shows two jobs -- one still stuck in running and a new jobID for the killed one. 

``` sees the same behavior where it creates a new job id:

ID                               OUTPUT COMMIT                                               STARTED      DURATION       RESTART PROGRESS  DL  UL       STATE
1c18333f734a44e78831d14e7905611c my_pipeline/9801ab05d84447f6beb39b6dafeb1fa2 16 hours ago 16 hours       0       0 + 0 / 0 0B  0B       killed
50573ac6909f40bfa3b4cdfb19be93ee my_pipeline/31ad5f2b46824565965a79a7067ebf41 16 hours ago 59 seconds     0       1 + 0 / 1 26B 5.654MiB running
4095d1243b7145d38b366f93e68681c6 my__pipeline/c4e26b2724324bcea91a021998e848f7 22 hours ago About a minute 0       1 + 0 / 1 26B 8.491MiB running
```
Granted, both of these are stalled in the same way: wrote data to the repo, but never egressed
it only shows 'killed' as a new job if you delete the pod after it's in that state````

**What you expected to happen?**:
I expect the job status to change from running to killed and that's it. 

**How to reproduce it (as minimally and precisely as possible)?**:
Customer has been able to repro a few times, but there are a number of major factors that make it difficult to clearly repro. We're focusing on solving the stuck job issue first and maybe this goes away?

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 
1.7.11
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
AWS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
I think this has been fixed, we haven't seen an issue like this in a while and have fixed a number of things that could have caused this, we also don't have a concrete repro so we unfortunately can't check explicitly. I'm going to close for now, please reopen if you hit something like this again.
