### ISSUE TITLE
inspect-commit doesn't display commit message 

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3242]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**: 
Pachctl doesn't display commit message when running `inspect-commit`

**What you expected to happen?**:
When running inspect-commit it should display commit message if one exists for that commit. 

**How to reproduce it (as minimally and precisely as possible)?**:
`pachctl put-file <repo> <branch> <filename> -m "Test message" -f /path/to/file`

Then to display commit message

`pachctl inspect-commit repo <commit id> 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.10
- Pachyderm CLI version (use `pachctl version`): 1.7.11
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): Mac
- Others:

**Comment by ysimonson** [comment]
Addressed in #3251
