### ISSUE TITLE
Remove incremental (intra-datum) feature from 1.8 docs.

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#3245]
The incremental (intra-datum) feature has been removed for 1.8. We chose to remove this feature because it was convoluted, not used often, and did not work well with our performance improvements. The mentions of this feature need to either be removed from the docs or marked as deprecated. We will re-visit this feature in the future if there is enough demand for it, or we come up with a more elegant design.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/934066748529753)

**Comment by Nick-Harvey** [comment]
Completed
