### ISSUE TITLE
Create Upgrade Path for 1.7 to 1.8

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3259]
**What is the goal / desired outcome?**
Users who are using Pachyderm 1.7 should be able to seamlessly upgrade to 1.8. 

**If there is a way to accomplish this today via workaround, what does that require?**
Users who want to upgrade have to deploy a new cluster and manually migrate data over. 

**(Optional) What is your proposal for a feature to solve this?**
Users should be able to upgrade in the same fashion as previous upgrades. 

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
@msteffen is working on migration for 1.7 to 1.8 that will do exactly this

**Comment by gabrielgrant** [comment]
I believe the technical side of migration shipped a while ago. Is there more to this issue than that (ie some additional docs?)

Or is there still technical work to be done @msteffen ?

**Comment by JoeyZwicker** [comment]
tech is done. Docs are 90% done and will be published this week

**Comment by ysimonson** [comment]
I think this is done now, right?

**Comment by JoeyZwicker** [comment]
Yes I believe so.
