### ISSUE TITLE
Enable better kube log tooling

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#326]
kubetail is nifty, but I don't think it fully qualifies each log line w the pod name that it came from. This is helpful when debugging issues.

I bet we can upgrade our logs to:
- read whatever config is needed (env / files / etc) to get the pod name they're running on
- put this value in all the log lines that are output

Then using kubetail to collate logs would be super helpful!

**Comment by derekchiang** [comment]
@sjezewski can you confirm that we want to include this in 1.1?  I'm not sure what's the difficulty/return ratio here.

**Comment by sjezewski** [comment]
Fair question.

I haven't seen an exact need for this yet, but I'm sure we will run across one soon. Pretty standard faire to ask your logs to tell you the place the log originated from. 

If we want to wait until we're debugging an issue that is intermittent enough to happen on a single pod at a time, we can do that.

**Comment by sjezewski** [comment]
Oh and to answer your question of difficulty - I don't think its hard - assuming that k8s exposes an index somehow within a pod that represents its pod number among its parallel peers.

**Comment by sjezewski** [comment]
We now have the ability to stand up a logging service. In v1.4 we also add the metadata we can (jobid, etc)
