### ISSUE TITLE
FUSE issue / PFS mounting

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#327]
Hey guys, I tried a fresh install and experienced the following issues.  Below is the process I went through:

- FUSE for non-OSX people?  This might be confusing. I basically ignored this dependency.  haha

- error on creating the pachyderm cluster:

    ```
    dwhitena@dirac:pachyderm$ kubectl create -f http://pachyderm.io/manifest.json
    unable to get type info from "http://pachyderm.io/manifest.json": invalid character '{' after top-level value
    ```
    
- figured this was a possible syntax error in the file on the site, so I tried:

    ```
    kubectl create -f etc/kube/pachyderm.json
    ```

    but this gave me this error:
    
    ```
    error: could not read an encoded object from etc/kube/pachyderm.json: API version "extensions/v1beta1" in "etc/kube/pachyderm.json" isn't supported, only supports API versions ["v1"]
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30650,tcp:30750) to serve traffic.
    ```

- but "kubectl get all" seems to give the same output as indicated on the quickstart guide, so I'll just move on assuming the error above is not a big deal.  Maybe consider adding "expected output" from the above "kubectl" command.  This would be really helpful for kubernetes noobs like myself.

- tried to mount PFS, but had permissions issue on my local:

    ```
    mkdir /pfs: permission denied
    ```

- super user doesn't have the right PATH, so I just created the /pfs directory with sudo manually and changed the permissions.  Then retried "pachctl mount &" and got the following:

    ```
    dwhitena@dirac:pachyderm$ 2016/04/20 07:05:41 mount helper error: fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
fusermount: exit status 1
    ```

- assuming this may be due to me ignoring FUSE as mentioned above.

- I'm using the following:
ubuntu 15.10
go version go1.6 linux/amd64
Docker version 1.11.0, build 4dc5990

**Comment by sjezewski** [comment]
Thanks for the detailed notes!

A few questions / comments so far:


1) That url for the manifest we did update recently, but needed to double check. I can reproduce that error and will fix that bug

2) That error message (and warning) when you use the local manifest is new. Can you run `kubectl version` and `gcloud version` and share the output with me? 

3) FUSE mounting 

So did you do an apt-get for FUSE ? Or did you already have it installed? Again, a version number would be helpful. (I think there was a recent change that requires the config flag you mention).

You can see how we handle [setting that flag for our CI](https://github.com/pachyderm/pachyderm/blob/issue_270/.travis.yml) or [heres another post that has some suggestions](http://unix.stackexchange.com/questions/37168/unable-to-use-o-allow-other-with-sshfs-option-enabled-in-fuse-conf) on how to handle setting and using fuse.conf.

As far as permissions go for mounting/unmounting fuse ... I do think that I run `sudo -E ...` when running those commands. Perhaps I'm running it wrong, or perhaps we need to update the documentation.

**Comment by sjezewski** [comment]
Looking into the manifest from the URL, it should be identical to the local copy:

    www$ diff manifest.json ../pachyderm/etc/kube/pachyderm.json 

(Returns nothing)

But we definitely added another top level object to that file. I wonder if the difference is in how its served / how kubectl is treating it based on mime type?

**Comment by derekchiang** [comment]
Just a comment on the second error you were seeing: it's saying that a kubernetes job could not be created, which resulted in pachyderm not being initialized, which might have resulted in some of the errors that you saw later.  It's very likely that you are using an outdated version of kubernetes/kubectl.  As a reference, this is the output of `kubectl version` in our cluster:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}
```

**Comment by dwhitena** [comment]
@sjezewski @derekchiang Thanks.  Here is the output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

and `gcloud version` return:

```
gcloud: command not found
```

is gcloud a dependency?

**Comment by dwhitena** [comment]
I'm using the `make launch-kube` command to start kubernetes via docker.  Maybe I need to blow away the old images and retry.

**Comment by sjezewski** [comment]
gcloud is not explicitly a dependency, but happens to be how I install / upgrade kubectl

**Comment by sjezewski** [comment]
Looking at your versions, it does seem like you have an older version of kubectl (the client version). So I would recommend updating that before you retry building.

**Comment by dwhitena** [comment]
@sjezewski Ok I will try later today and I will also apt-get FUSE.

**Comment by sjezewski** [comment]
Ah interesting, updating my version of kubectl client helped w the first error.

This is what it was before:

```shell
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

And after updating (via `gcloud components update kubectl`)

```shell
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

And now running the kubectl command using the URL works just fine. I'll update the docs to specify a new minimum version

**Comment by sjezewski** [comment]
Ok I think the remaining issues here are just documentation related (which I also updated in #309). I'll leave this issue open though until

a) dwhitena validates its working for him, and 
b) when the documentation branch lands

**Comment by dwhitena** [comment]
@sjezewski One thing to note is that the `make launch-kube` command will start kubernetes as mentioned above.  That is:

```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

So if this a problem for the quickstart, you may want to update `start-kube-docker.sh`.  Working on updating kubernetes now.

**Comment by derekchiang** [comment]
@dwhitena `make launch-kube` launches the kubernetes server, which is of version `1.2.0`, which we support.  What you need to do is to update `kubectl`, since you are running `1.0.1` right now which is outdated.  The version of your `kubectl` needs to be at least `1.2.0`.  Let me know if you need any help on that.

**Comment by dwhitena** [comment]
Ok, updated the kubectl binary.  Now I have:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

And the following seems to work:

```
kubectl create -f http://pachyderm.io/manifest.json
```

I also updated my `fuse.conf` based on the above, and now when I am trying to mount:

```
dwhitena@dirac:pachyderm$ pachctl mount &
[1] 16663
dwhitena@dirac:pachyderm$ mkdir /pfs: file exists
^C
[1]+  Exit 1                  pachctl mount
dwhitena@dirac:pachyderm$ ls /pfs
ls: cannot access /pfs: Transport endpoint is not connected
```

Suggestions?

**Comment by jdoliner** [comment]
Hmm, looks like that `mkdir` might have crashed our fuse layer, which is weird.
Few ideas, I normally have to `sudo` my mount.
What happens if you try: 
```
$ pachctl create-repo foo
$ sudo pachctl mount
$ ls /pfs
```

You should see a single directory `foo`.

Also careful with doing `sudo pachctl mount &` and not seeing the prompt for your password because it's backgrounded. I've wasted more time than I care to admit stumped by that one.

---

I'm going to see if I can reproduce a crash using `mkdir`

**Comment by dwhitena** [comment]
@jdoliner Thanks.  `sudo pachctl mount` returns:

```
mkdir /pfs: file exists
```

probably because I manually created it and changed permissions earlier trying to get it to work.  If I try to `rm -r` or `ls` that directory I always get:

```
 rm: cannot remove ‘/pfs’: Transport endpoint is not connected
```

or

```
ls: cannot access /pfs: Transport endpoint is not connected
```

So I did:

```
fusermount -uz /pfs
```

got rid of `/pfs`.   And upon retrying `sudo pachctl mount`, it just hangs (assuming because I didn't run in the background).  But if I `ls /pfs` in another directory I can see `foo`.  

So success, I guess?

**Comment by jdoliner** [comment]
Yup, that's the expected behavior!

**Comment by dwhitena** [comment]
Sweet.  Thanks guys!

**Comment by jdoliner** [comment]
Happy to help. Looks like this issue is closable unless there's something here I'm missing?

**Comment by sjezewski** [comment]
I think the only remaining todo is to see if mkdir causes a consistent fuse crash and how we handle that error. But I'll make that into a separate issue.
