### ISSUE TITLE
Pachct deploy storage docs are incorrect

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3272]
http://docs.pachyderm.io/en/latest/cookbook/ingressing_from_diff_cloud.html
`$ pachctl deploy storage aws <bucket-name> <access key id> <secret access key>` should be `$ pachctl deploy storage aws <REGION> <access key id> <secret access key>`

We should check where else these arguments might be documented and make sure they're all updated.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/929603687556535/943039528788602)

**Comment by Nick-Harvey** [comment]
Fixed. 

I also did a broader search for `pachctl deploy amazon` and `pachctl deploy storage aws` to ensure that `region` was part of the instructions, and this looked to be the only instance where it wasn't.
