### ISSUE TITLE
Add CI for guide/setup?

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#328]
We've seen a few bumps where the setup instructions or fruit-stand example didn't quite work for users. 

Maybe this is going too far w automation, but it wouldn't be hard to add a test that parses the *.md files for each (setup / fruit-stand) and runs them in order.

Some of the issues (See #327) do seem to appear from using the latest versions of some of the tools (kubectl / gcloud / etc), which I believe we lock in our CI. IF we want to make this a robust test, we should use the latest versions.

**Comment by jdoliner** [comment]
I love this idea, I tried to do this some with integration tests like `TestGrep` which at one point matched the grep example. But they drifted out of sync and it was never good enough to prevent the types of failures we've been seeing as people start up using the product.

**Comment by sjezewski** [comment]
This is redundant w #364, closing
