### ISSUE TITLE
Support CEPH object storage

### ISSUE THREAD

**Issue by XVilka** [pachyderm/pachyderm#3280]
I saw previously mentioned bugs for support CEPH, but they were closed without actual resolution.
Thus opening a new one.

There is a good library in Go for CEPH bindings: https://github.com/ceph/go-ceph

**Comment by JoeyZwicker** [comment]
Thanks for submitting @XVilka. While I'm not super familiar with Ceph, it supports the S3 API which means it should be workable with Pachyderm as is, even if it's not full Ceph functionality. 

Adding more first-class Ceph support is definitely we'll consider in the future.

**Comment by iswaverly** [comment]
I am trying to deploy CEPH as backend storage, and I set `s3` in charts configuration (reference: https://github.com/helm/charts/tree/master/stable/pachyderm). It seems that it use minio, and I am not sure whether minio support CEPH alghough both of them use s3 as interface.

**Comment by gabrielgrant** [comment]
@iswaverly Sorry for the confusion, Pachyderm uses the Minio client to communicate with all non-Amazon S3-compatible object stores (including Ceph)

**Comment by jdoliner** [comment]
I'm going to close this because I think our generally s3 support should cover ceph, please reopen if that doesn't work. We unfortunately don't have the resources to test with all the s3 compatible object stores out there right now.
