### ISSUE TITLE
cobra-generated docs produce 404ing links

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3283]
cobra-generated docs are producing broken links in these two places:

* [SEE ALSO section under put-file](http://docs.pachyderm.io/en/latest/pachctl/pachctl_put-file.html)
* [SEE ALSO section under get-file](http://docs.pachyderm.io/en/latest/pachctl/pachctl_get-file.html)

This is because they're referencing the markdown files rather than the built html artifacts. Hopefully cobra provides a way to do link rewriting.

**Comment by JoeyZwicker** [comment]
I don't know if they do, but certainly worth exploring. Either that or take our these sections @Nick-Harvey
