### ISSUE TITLE
Pachyderm Dashboard Pod won't start in OpenShift

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3292]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:
When deploying Pachyderm in OpenShift, the pod will not start due to OpenShift not allowing privileged containers to run by default. The logs for the dash pod display the following:  

`bash: run.sh: Permission denied`

**What you expected to happen?**:
Dash Pod should start without any issues 

**How to reproduce it (as minimally and precisely as possible)?**:
1. Deploy OpenShift 3.10
2. Deploy Pachyderm with an appropriate cloud backend

**Anything else we need to know?**:
According to the docs in openshift, the container image needs to be able to "Support Arbitrary User IDs" https://docs.openshift.com/container-platform/3.10/creating_images/guidelines.html. 

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by gabrielgrant** [comment]
We'll need to follow the guidelines about being able to run as any user here: https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#general-container-image-guidelines

**Comment by OchiengEd** [comment]
The `run.sh` script is located in /root , and is consequently owned by the root user. As a result, when the container runs in Openshift with an unprivileged service account, then we get the permission denied error mentioned above.

I encountered this issue on Openshift 4.7.12

**Comment by msteffen** [comment]
Hi @OchiengEd thanks for resurfacing this!

At this point, Pachyderm's current dash (and associated dash pod) aren't being maintained anymore, so I think we're unlikely to be able to get the `dash` pod running in OpenShift. The goal is currently to re-add support for non-root usage (i.e. OpenShift) in the next version of Pachyderm's dash, which will work with Pachyderm 2.0.

We can help over slack with working around this.
