### ISSUE TITLE
--push-images flag doesn't work (at least on OS X)

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3293]
from https://medium.com/bigdatarepublic/pachyderm-for-data-scientists-d1d1dff3a2fa

> ...
>  using --push-images one can have that done automatically. So let’s update our pipeline accordingly:
> 
> ```
> $ pachctl update-pipeline -f iris.json --push-images
> error parsing auth: Failed to read authentication from dockercfg, try running `docker login`
> $ docker login
> Authenticating with existing credentials...
> Login Succeeded
> $ pachctl update-pipeline -f iris.json --push-images
> error parsing auth: Failed to read authentication from dockercfg, try running `docker login`
> ```
> 
> Unfortunately that doesn’t work as expected, at least not on my machine. Let’s do it ourselves:
> 
> ...

**Comment by gabrielgrant** [comment]
looks like this may be the same issue as #2446?

**Comment by gabrielgrant** [comment]
Seems the root of this issue is that the go-dockerclient library doesn't support creds stored in `oxskeychain` (more details [here](https://github.com/kubernetes/kompose/issues/911), among other places)

This should probably be addressed with a PR against that lib, but can be worked around by embedding the docker creds in the `~/.docker/config.json` file (as is done on Linux)

by default, that file will look something like this:

```
{
  "stackOrchestrator" : "swarm",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credSstore" : "osxkeychain"
}
```

you can generate a string containing your dockerhub creds by running 

```
echo -n "username:password" | base64
```

and paste the resulting string into the config file's `auths` section:


```
{
  "stackOrchestrator" : "swarm",
  "auths" : {
    "https://index.docker.io/v1/" : {
      "auth": "<YOUR CREDS STRING HERE>"
    }
  },
  "credSstore" : "osxkeychain"
}
```

**Comment by ysimonson** [comment]
There seem to be two issues going on here.

Without any changes, I'm hitting the same issue as #2446.

With the config change, if I do `pachctl update-pipeline -f edges.json --push-images`, it fails, because it tries to push the image to `[system user]/[repo]` rather than `[docker user]/[repo]`. It appears that this is `pachctl`'s default behavior [when a user is not explicitly specified](https://github.com/pachyderm/pachyderm/blob/80176efe4eb1a4184a8357773616f819668378cb/src/server/pps/cmds/cmds.go#L838-L844). Is this intended? Or should we instead default to the docker user?

**Comment by ysimonson** [comment]
I'll go ahead and open a PR with the fix. We can just not merge the PR if defaulting to system user is expected behavior.

**Comment by ysimonson** [comment]
@gabrielgrant confirmed that your fix, in tandem with #3322, allows you to push images in macOS.

**Comment by ysimonson** [comment]
Sure, that makes sense. Do we have an idea of how frequently `--push-images` is employed? That would help decide whether it makes sense to just print a friendly error message, or build a full workaround.

**Comment by gabrielgrant** [comment]
well, given how broken it seems it was, i doubt it has been used much to date :package: 
so yea, maybe just checking for the existence of `~/.docker/config.json`'s `["auths"]["https://index.docker.io/v1/"]["auth"]` key and printing a warning message pointing to this workaroud if that key doesn't exist?
