### ISSUE TITLE
Clarify docs for `--push-images`

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3296]
The [docs for `--push-images`](http://docs.pachyderm.io/en/latest/fundamentals/updating_pipelines.html#updating-the-code-used-in-a-pipeline) don't make it clear how to build images that can be auto-updated by that flag. How does `--push-images` know what image to push to dockerhub? If you just run `docker build` without specifying a tag name, afaiu the image will just have an ID, which has no connection to the value specified in the `image` field of the pipeline spec. So i don't think that would work. Is it that you have to manually specify a tag name, and `--push-images` will just push the latest-tagged image from the given repository, and update the spec to use that? Or are you supposed to build the image locally with the image name specified, but no tag (or `latest`?), and `--push-images` will re-tag that image with a randomly-generated tag, push that to docker hub, and update the pipeline spec?

Note this is all made more confusing by docker conflating "tags" and "image names"/"repositories" -- in order to name an image (ie specify it's "repository"), you "tag" it with that name (eg `pachyderm/pachd`). You can also include a "tag" (eg `1.8.0`). Both these values are passed together to the `--tag` flag of the `docker build` command (in this case, as `pachyderm/pachd:1.8.0`)

**Comment by JoeyZwicker** [comment]
Just FYI: Please try to label these as docs issues and assign to @Nick-Harvey and myself.

Obviously if there's a bug with push-images, that'll get passed to eng, but it helps us not lose track

**Comment by ysimonson** [comment]
I'm finding myself confused by `--push-images` as well. It seems to generate a new tag for the image, but not build a new version of the image. So I'm not sure what tag it's going off of. Is it the one in the pipeline spec? `latest`? Something else?

Once the pipeline is updated, presumably it uses the new tag. But then that means the pipeline has diverged from what's in the spec.

More broadly, if it's not rebuilding the image, is there much utility to this? I can get why a flag that would rebuild + retag + push + pull a docker image would be really helpful; that way, you could update a script and just run one command to see the changes reflected. But with this, you still need to run some docker commands before seeing script changes reflected.

**Comment by ysimonson** [comment]
Added support for rebuilding docker images (as outlined in the last comment) in #3370

**Comment by ysimonson** [comment]
The docs are now oriented around `--build`, which doesn't have the same issues
