### ISSUE TITLE
CLI reference doesn't show in last several versions of docs

### ISSUE THREAD

**Issue by discdiver** [pachyderm/pachyderm#3306]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:
Click link in the left hand menu for *Pachctl Command Line Tool* in a recent version of the docs.

Last several versions of the docs don't have the reference for the Pachyderm CLI. Screenshot below.
![screen shot 2018-12-20 at 3 09 59 pm](https://user-images.githubusercontent.com/7703961/50308482-5d01ff80-0469-11e9-8295-21f1a9d50a2c.png)

 
But v1.7.3 shows the reference. Screenshot below.
![screen shot 2018-12-20 at 3 09 02 pm](https://user-images.githubusercontent.com/7703961/50308450-393eb980-0469-11e9-8444-feb88786394f.png)

**What you expected to happen?**:
See the Pachctl Command Line Tool reference.

**How to reproduce it (as minimally and precisely as possible)?**:
Click link in the left hand menu for *Pachctl Command Line Tool* in any recent version of the docs.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI version (use `pachctl version`): 1.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
Thanks @discdiver. We'll figure out what's going on there. I'm pretty sure we just broke some formatting thing in the ReadtheDocs and it's not finding the .rst or .md file correctly. @Nick-Harvey and I can investigate

**Comment by pappasilenus** [comment]
related to #2559

**Comment by jdoliner** [comment]
This seems to be fixed, at least I'm seeing those docs on the page.
