### ISSUE TITLE
Deduplication Improvement(s)

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#3310]
**Problem:**

Pachyderm's current approach to deduplication in input repos uses fixed size content-addressed chunks and stores each chunk as an object in object storage. This approach to deduplication does not work well with workloads that make modifications to large files. Any modification that adds to or removes from the middle of a file will change all of the chunks following the modification which could mean re-storing a lot of the same data. Also, as of 1.8, content-addressed based deduplication was removed from job output (there still can be implicit deduplication through skipped datums), because chunks were being created for every file output by a datum regardless of the size which would have resulted with billions of objects in object storage in our scalability tests.

**Potential Solution:**

Files greater than a certain size (probably configurable) will be split into content-addressed chunks using a content-based chunking algorithm. An example of this is to chunk based on a particular bit pattern that is expected to show up with a particular frequency that will on average give us reasonable chunk sizes. This would fix the problem with modifications in the middle of large files because the chunks following the modified chunk(s) will not be changed since the chunk boundaries will shift as data is added/removed. It may also make sense for this bit pattern to be configurable for workloads where the default pattern does not provide reasonable chunks. 

**Potential Concerns:**

_What about a large number of small files in the input repos?_

Making the deduplication file size threshold configurable would allow users to deduplicate smaller files at the cost of more object storage activity. There are probably ways to do clever batching to make this workload better, but as of now I think it is a reasonable expectation for deduplication with this workload to be more expensive.

_What about jobs that have many datums that contribute small chunks to each of the output files' content?_

Skipped datums would implicitly deduplicate these small chunks. There is still the case of a lot of processed datums uploading some of the same small chunks, but that does not seem to be an important case to think of right now. 

01/01/2019: This case could potentially be improved by deduplicating across the concatenation of the files output by a datum.

_How would this work in terms of files that get appended to?_

If the file starts smaller than the threshold, then no chunks would be created. As soon as it gets larger than the threshold, the file would be chunked. Each following append would re-write the last chunk and additional chunks based on where the bit pattern shows up.

**Notes:**

In Pachyderm 1.8, global access to content-addressed chunks was removed from job output because the implementation at the time would create way to many object storage objects and requests. I think with a file size threshold and a content-based chunking algorithm, we may be able to re-visit this idea and get the value it could provide.

**Comment by jdoliner** [comment]
Update: work on this has been underway for a while. The earliest it'll be available is 1.10, more likely 1.11

**Comment by echohack** [comment]
This issue appears out of date. @jdoliner @brycemcanally I'm closing the issue because it appears to have been solved.

For those doing a bit of software archeology, please note that the discussion on this issue isn't reflective of the current state of Pachyderm.
