### ISSUE TITLE
FlushCommit doesn't work if job with stats enabled fails

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3314]
If a job with stats enabled fails, the job's stats commit is never finished. If a user calls FlushCommit on an input to said job, it will hang indefinitely waiting for the stats commit to finish

**Comment by msteffen** [comment]
Update: in general, it seems that the stats commit does finish. The only codepath we see in which it doesn't finish is the one in which one of the job's datums times out

**Comment by ysimonson** [comment]
Maybe fixed by https://github.com/pachyderm/pachyderm/pull/3355 ?

**Comment by jdoliner** [comment]
I believe this has indeed been fixed. Please reopen if we hit an issue like this again.
