### ISSUE TITLE
Upgrading from V1.7 to V1.8 : pachd Pod stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by chungmeng** [pachyderm/pachyderm#3316]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI version (use `pachctl version`): 
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release): 
- Others:

**What happened?**:
Upgraded pachctl from V1.7 to V1.8 by following steps outlined in https://pachyderm.readthedocs.io/en/latest/deployment/upgrading.html

Pachd pod is stuck in CrashLoopBackOff after deployment 
**What you expected to happen?**:
Pachd pod running
**How to reproduce it (as minimally and precisely as possible)?**:
$ pachctl undeploy --all

$ curl -o /tmp/pachctl.tar.gz -L https://github.com/pachyderm/pachyderm/releases/download/v1.8.1/pachctl_1.8.1_linux_amd64.tar.gz && tar -xvf /tmp/pachctl.tar.gz -C /tmp && sudo cp /tmp/pachctl_1.8.1_linux_amd64/pachctl /usr/local/bin

$ pachctl deploy --no-dashboard local

$kubectl get pods 
NAME                        READY     STATUS             RESTARTS   AGE
etcd-5fd7b4f778-mf2zp       1/1       Running            0          8h
pachd-8f6c9c8fb-xrjmh       0/1       CrashLoopBackOff   99         8h

$kubectl log pachd-8f6c9c8fb-xrjmh 
*Excerpt only. Full log attached
[pachd_pod.log](https://github.com/pachyderm/pachyderm/files/2712859/pachd_pod.log)
*
time="2018-12-27T15:54:51Z" level=warning msg="TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory" 
time="2018-12-27T15:54:51Z" level=warning msg="TLS disabled: could not stat private key at /pachd-tls-cert/tls.key: stat /pachd-tls-cert/tls.key: no such file or directory" 
2018-12-27T15:54:52Z ERROR pfs.API.CreateRepo {"duration":0.001604219,"error":"cannot create \"__spec__\" as it already exists","request":{"repo":{"name":"__spec__"}},"response":null} []
2018-12-27T15:54:52Z ERROR pfs.API.CreateRepo {"duration":0.001204403,"error":"cannot create \"__spec__\" as it already exists","request":{"repo":{"name":"__spec__"}},"response":null} []
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.9.11, GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"
- Pachyderm CLI version (use `pachctl version`): v1.8.1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local deployment - dockerized k8s
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Others:

**Comment by JoeyZwicker** [comment]
Hi @chungmeng, sorry you're hitting this. For right now, 1.8.x clusters need to be fresh as we don't offer a clean migration path (we're working on it). Check out the docs here for more details: http://docs.pachyderm.io/en/latest/deployment/upgrading.html
