### ISSUE TITLE
`pachctl list-repo` results in output repo showing SIZE 0B when output repo has files in it

### ISSUE THREAD

**Issue by discdiver** [pachyderm/pachyderm#3330]
**What happened?**:
`pachctl list-repo` results in output repo showing SIZE 0B
However, `list-file` shows SIZE > 0B 

screenshot:

![screen shot 2019-01-04 at 2 05 28 pm](https://user-images.githubusercontent.com/7703961/50706150-041a9580-102b-11e9-9d5a-a6ccd0c35896.png)

**What you expected to happen?**:
`pachctl list-repo` result in output repo showing SIZE > 0B 
and you can see the files in the output repo

**How to reproduce it (as minimally and precisely as possible)?**:
- create an input repo
- create an output repo
- pachyderm pipeline saves files to a subdirectory in the output repo
- `pachctl list-repo` 

Output repo should show SIZE 0B

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 0.30.0
- Pachyderm CLI version (use `pachctl version`): 1.8.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):minikube
- OS (e.g. from /etc/os-release): Mac

**Comment by discdiver** [comment]
Same bug with `pachctl inspect-repo repo_name`  - 0B size shown when files are in subdirectories.

![screen shot 2019-01-04 at 10 10 43 pm](https://user-images.githubusercontent.com/7703961/50719665-bd01c400-106d-11e9-81df-b9d154ffb396.png)

**Comment by gabrielgrant** [comment]
Thanks for filing this! To confirm: does this only occur 1) on output repos (not repos you manually create and add files to explicitly) that 2) have files only in subdirectories (files at the top level are counted towards the computed filesize?)

**Comment by discdiver** [comment]
Sure thing, @gabrielgrant.

Confirming this bug only occurs only on output repos.
Neither files in the directory nor files in the subdirectories count toward the computed filesize.

**Comment by marcadella** [comment]
Same error for me
