### ISSUE TITLE
pachd requires ports to bind on be explicitly specified in env vars rather than using names exposed by k8s

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3333]
pachd requires a number of container ports be exposed:

- api-grpc-port (default: 650)
- trace-port (default: 651)
- api-http-port (default: 652)
- peer-port (default: 653)
- api-git-port (default: 999)
- saml-port (default: 654)

But if these are changed from their default values in the deployment manifest, pachd seems to fail to come up, because it is still trying to bind on the default ports. Instead of reading the correct port to bind on from k8s, it relies on it's own set of environment variables to change the bindings (`PORT`, `PPROF_PORT`, `HTTP_PORT`, and `PEER_PORT` -- I haven't found env vars to control the Git and SAML ports)

It seems pach should just be able to pick up the correct port numbers from K8S instead of relying on the user specifying custom port bindings both in the `env` and `ports` sections of the deployment manifest

**Comment by gabrielgrant** [comment]
related: #3295

**Comment by nadegepepin** [comment]
NO longer relevant with Helm install since 1.12.x
