### ISSUE TITLE
Double-asterisk glob patterns should be modified to be more useful

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3335]
As discussed with @jdoliner right now `**` glob patterns are rarely useful, because they include every file as a datum, including the top-level directories that contain the lower-level ("leaf node") files which will also be the contents of separate datums. We think filtering the list of files returned by globbing to include files, not directories, is probably more likely to be useful (though there admittedly still aren't many use-cases i can imagine even for that)

**Comment by gabrielgrant** [comment]
related: #2386 glob file docs

Also, it's possible some of this is more useful if used in conjunction with exclude patterns (#2911)...have to think about that more

**Comment by jdoliner** [comment]
> We think filtering the list of files returned by globbing to include files, not directories, is probably more likely to be useful

I think an even better option would be to filter to only include paths that don't have any paths beneath them that match. That would mean you could do the following semantics:

- `**`, all files (and empty directories, but it's hard to get empty dirs
- `**/` all directories that don't contain other directories.
- `**/foo` all files named (this one should already work)

This does add the big complication that `GlobFile` now can't tell if a file should be returned just by looking at it, it has to iterate through the paths under it as well. This might not be so bad though, it already has to iterate all paths, this just changes when you can return values a bit.

**Comment by gabrielgrant** [comment]
That does seem more useful, though I thought avoiding this type of lookahead matching was (a big?) part of what allowed glob patterns to be more performant than generic regexes. Not sure matching is actually ever a perf bottleneck for us, but potentially something to keep in mind?

Related: i can haz generic regex path matching? :)

**Comment by jdoliner** [comment]
Looking at this now I'm not sure this is something we want to do, it's true that `**` is generally not a very useful glob pattern, but it is useful when you put something on the end, for example `**.json` gives you all of the json files in the repo, and I don't think `**` not being useful is a good reason to make this change, a good reason would be if there's a way that users wanted to glob files that isn't supported by our current semantics. I also think the proposed changes here are too complicated and confusing to implement, it'll make it harder for users to figure out which datums are actually being processed, furthermore they do pose some serious performance challenges, those might be something we could work around, but given we don't have a good reason to do so I don't think it's worth it.
