### ISSUE TITLE
Cumulative cron workloads

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3342]
**What is the goal / desired outcome?**
Perform cron workloads that scrape a time window's worth of data rather than the whole dataset.
Presently this is impossible because cron inputs expose a single datum that is repeatedly overwritten, which means that each new tick effectively deletes the previous tick's output. A simple solution to this is to have each tick be a new file, rather than overwriting. Probably numbered `0`, `1`, `2` etc...

It probably makes sense for this to be the default. Although that may break some existing pipelines it should be a pretty easy fix for users.

**If there is a way to accomplish this today via workaround, what does that require?**

You can implement your own cron and do whatever you want.

**Comment by gabrielgrant** [comment]
since cron is inherently time-based, would it maybe make sense to have the file just be named after the (probably ISO 8601) timestamp?

**Comment by jdoliner** [comment]
Yeah, that probably makes sense. Although it raises a few questions:
- Should not cumulative `cron` inputs also use timestamps for names? Seems like that'd be the most consistent option.
- Should the files still contain content given that that content is now redundant with the names of the files. My gut says no.

**Comment by adelelopez** [comment]
## Proposal
Add a new field to the cron input of a pipeline spec. This will be a bool, and called `overwrite`. If `input.cron.overwrite` is true, then it will do the current behavior where it has a single datum which it overwrites on each tick. If false, then it will create a new datum on each tick; implementing the feature requested here.

`input.cron.overwrite` will be an optional field and default to `false`. This may break some existing pipelines, but I think it will be the least surprising behavior for most users.
