### ISSUE TITLE
Error handlers in pipelines

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3343]
**What is the goal / desired outcome?**

Have a way to handle errors that doesn't fail the job and doesn't prevent the datum from being reprocessed on later runs.

**If there is a way to accomplish this today via workaround, what does that require?**

No, a datum must either succeed or fail, if it fails it fails the job, if it succeeds it won't be processed again unless the pipeline is updated or the datum changes.

**(Optional) What is your proposal for a feature to solve this?**

Pipeline specs will have a section for error handlers. Handlers will effectively be a new Transform that gets run after the actual Transform fails. They'll still have access to the data that the Transform failed on, in addition they'll have a new input directory `/pfs/error` with files that describe the error this should include: return code from their program, logs, a pachyderm reason for failure encoded in some way, rather than freeform text. If the error handler returns an error, that will fail the job. The output from the error handler will go in a separate branch called `error`, this allows you to make downstream pipelines that handle the error output.

**Comment by JoeyZwicker** [comment]
Just to make sure I understand this: so if I user has this `error transform` set, then any datums that error/fail for any reason will no longer cause the job to fail? Successful datums will get passed through to the next steps and failed datums will get triaged into their error handling process. So a job can never really "fail" any more or can it still fail just not in the specific user-defined ways?

But if there is no error transform defined then the pipeline will continue with the current behavior where any failed datum means the whole job fails and an output commit is not finished?

**Comment by jdoliner** [comment]
> So a job can never really "fail" any more or can it still fail just not in the specific user-defined ways?

> If the error handler returns an error, that will fail the job.

Think of it like an exception handler.

> But if there is no error transform defined then the pipeline will continue with the current behavior where any failed datum means the whole job fails and an output commit is not finished?

Yes

**Comment by jdoliner** [comment]
Also to clarify another point, output commits do get finished post 1.7.0.

**Comment by jdoliner** [comment]
We're scheduling this for 1.9. Reading this now I want to make one tweak to the original design which is that I don't think it makes sense to have a whole separate `Transform` for the error handler. It seems pretty unlikely that you'd want to have a separate container image for the error handler, and it adds a lot of complication to the implementation. If it's just a separate field in the `Transform` called `OnErrorCmd` or something of the sort then it should be pretty straightforward to just call it right after `Cmd` exits with an error.

**Comment by jdoliner** [comment]
Also it probably makes sense to expose the exit code of `Cmd` as an env var, `$?` is the standard in shell for the exit code of the previous command, so we should probably use that.

**Comment by adelelopez** [comment]
Implemented in https://github.com/pachyderm/pachyderm/pull/3611
