### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#335]
We should add a command to the pps api, `Provenance`. It takes as input a set of `Commits` and returns a full accounting of the computations that were triggered by them. That should include:

- `Pipelines` which were triggered
- `Jobs` which were created
- `Commits` which were created

Possible behavioral toggles:

- `any` vs `all` semantics, do we want information about any of the commits or only information about all of them
- `failures`, get exclusively objects that errorred

**Comment by JoeyZwicker** [comment]
There's also a use case where you'd want the input a `repo` and `commit` that is the result and track provenance up the commit tree to see what data went into it. 

I think the `provenance` command should be able to go both up and down the full parental structure. `provenance` should return a full accounting of everything that went into creating a set of `commits` as well as everything that was triggered by them. We could have a behavioral toggle for either direction or just have it do both ways by default.

**Comment by jdoliner** [comment]
Yup that's a great call.

How does `--upstream` and `--downstream` sound? Default should be both.

**Comment by jdoliner** [comment]
Updating this proposal based on offline conversation. Here's what we'll be adding to complete this feature:

- Repo provenance: pfs will expose the ability to set other repos as provenance in `CreateRepo`. This will be used by pps to indicate which repos are derived from others. This allows us to figure out all the repos that _could_ be affected by an incoming commit.
- Commit provenance: pfs will expose the ability to set other commits as provenance in `StartCommit`. This will be used to pps to indicate which commits derive from others. It will be an error to start a commit on repo `A` with a commit from repo `B` as provenance if repo `B` isn't provenant of repo `A`.

Using provenance tracking we'll fix a number of issues:

- Finding the provenance of a commit or repo. The simplest use of this feature just lets you find the repos and commits that led to a commit or repo.
- Correctly handling propagating data through the dag. #367 
- Extending `ListCommit` and `ListRepo` so that you can filter by provenance. Ie being able to say "give me all the commits for which this commit is provenant"
- `Flush` a porcelain command that waits for all the commits of which a set of commits are provenant to be finished and returns the commits.

**Comment by jdoliner** [comment]
Development on this is happening in #391

**Comment by jdoliner** [comment]
Merged into master!
