### ISSUE TITLE
Make steps in quote block clearer in pachyderm/examples/gatk/README.md

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3353]
**What is the goal / desired outcome?**

1. Easy to miss creation of reference repo. Make it easier to follow the steps in the gatk demo. 
2. joint-call shoulda be joint_call. Just generally need to update and proof this example

**If there is a way to accomplish this today via workaround, what does that require?**

Reading very very carefully

**(Optional) What is your proposal for a feature to solve this?**

Break the big quote block into individual steps, as it is below the block.  It's easy to miss creating the "references" repo, for example.  

Each command that changes state and the command to check that the state has changed should be an individual step, with text in between them.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**What happened?**:

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
This has been fixed.
