### ISSUE TITLE
pachd should propagate "*_PORT" env vars to worker/storage containers in pipeline pods

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3363]
Pach allows setting env vars to control which ports it binds on:

- `PORT` (default) 650
- `PPROF_PORT` (default 651)
- `HTTP_PORT` (default 652)
- `PEER_PORT` (default 653)

but it doesn't seem pass those port number env vars on to the pipeline pods it creates. It should do that (by default, at least -- not sure if there's any reason you'd want the pipeline pods to be using different values than the pachd master?)

**Comment by gabrielgrant** [comment]
yes, sorry, it's supposed to be `650` -- just edited to correct the original issue description (1650 is what i was using to test)

This issue is about setting the ports in the k8s manifest generated when a user deploys a pipeline; #3362 is about the worker not making use of the ports if they are set

**Comment by ysimonson** [comment]
Do `PORT` and `HTTP_PORT` need to be propagated? I don't see them used in `src/server/cmd/worker/main.go`

**Comment by gabrielgrant** [comment]
afaict that PR (https://github.com/pachyderm/pachyderm/pull/3368)  handles the worker (which, yes, requires a subset of the ports), but the sidecar (`storage` container) is a full pachd process, so i think it will need all the ports propagated

**Comment by gabrielgrant** [comment]
@ysimonson once #3367 lands, I believe all ports will be configurable. Does that PR include propagation? (doesn't seem like it would make sense for it to not -- the port it's making configurable isn't even used on the pachd master afaict)

**Comment by ysimonson** [comment]
Yes, it includes propagation
