### ISSUE TITLE
pipeline services allocate port 80 as "grpc-port"; this needs to be configurable by env var

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3365]
Unclear to me all of what this port is for (worker statuses?), but if it is used, it will cause problems in OpenShift, since it's privileged (#3334)

This should be read from an env var, instead of hard coded, and will also need to be propagated from pachd to pipeline pods (#3363)

Alternatively, for the sake of getting openshift working, pretty sure this could just be changed to be hard-coded to be a non-privileged port (8080?) instead of 80

**Comment by gabrielgrant** [comment]
When #3367 lands, this will be set-able via the `PPS_WORKER_GRPC_PORT`, correct?

**Comment by gabrielgrant** [comment]
would it also make sense to change the default from `80` to, say `680`, or even just `654` (to be in keeping with the rest of our `650`-`653` ports)?

If it were a webserver, this would kinda make sense, but it's not clear to me why a GRPC service would have been on 80 in the first place...

**Comment by ysimonson** [comment]
Let's get port customization working first before changing defaults

**Comment by gabrielgrant** [comment]
generally agreed, though my thinking was partly that changing the default would flush out the places where customization won't work (due to implicit-use-of 80)
