### ISSUE TITLE
Confirmation check for `pachctl undeploy` --feature request

### ISSUE THREAD

**Issue by discdiver** [pachyderm/pachyderm#3369]
**What is the goal / desired outcome?** Ask for confirmation after `pachctl undeploy` command is entered by a user. 

Mistakes happen. Before deleting everything, confirming the user's intent might be nice.

**(Optional) What is your proposal for a feature to solve this?**
Ask for confirmation after `pachctl undeploy` command is entered.

**Comment by jdoliner** [comment]
Worth noting on this: `pachctl deploy` deletes the kubernetes deployments, but doesn't actually delete the underlying data. So an accidental `undeploy` can be undone by reissuing the `pachctl deploy` that was originally used to deploy the cluster. `pachctl undeploy -a` is the version of the command that does delete things and that one does have a prompt attached to it. Maybe for this we should clarify when `undeploy` starts running that everything it's doing is reversible, and if they want to truly undeploy everything then the `-a` flag is needed.
