### ISSUE TITLE
put-file appends to existing file instead of replacing it

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3371]
?Bug?
`put-file` appends to existing file instead of replacing it

Example:
```pachctl create-repo test
echo "a" | pachctl put-file test master myFile
echo "b" | pachctl put-file test master myFile
pachctl get-file test master myFile
```

displays `a\nb`

COMPONENT           VERSION             
pachctl             1.8.2               
pachd               1.8.2

**Comment by JoeyZwicker** [comment]
That is expected behavior. Use the -o (overwrite) flag if you want put-file to overwrite instead of append.
