### ISSUE TITLE
Port forwarding does not respect customized remote ports

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3374]
#3368 et al. introduces the ability to customize ports used within the k8s cluster. But currently, the port forwarder does not respect this and uses hard-coded default for the remote end. This means that the port forwarder will only work if ports are not customized at the moment.

**Comment by gabrielgrant** [comment]
It seems that PR adds a flag to set which `remote-port` is forwarded (to?). Can you explain what needs to be done in order to use `port-forward` to attach to a cluster with custom ports?

(thinking maybe that flag needs to be set to the same value as passed in the `PORT` env var?)

**Comment by ysimonson** [comment]
Yes, you need to set the `remote-port` flag
