### ISSUE TITLE
Better support/docs for running multiple instances of pachyderm in a cluster

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3375]
Running multiple instances of Pachyderm in the same Kubernetes cluster is in theory doable, but in practice kinda tricky (and made more difficult by ~a few open technical issues and~ there not being good docs on how to achieve this)

at a minimum you'd need to:

- set different namespaces
- use different etcd volumes
- set different port numbers
- use different object storage buckets

... and probably a few other things i'm missing right now

~This is also affected by a few open issues:~

- ~#3374~ 
- ~#3365~
- ~#3363~

Edit: I believe all technical blockers for this have been fixed, so it should just be a matter of setting up the proper values in the initial kubernetes deployment manifest for the second (and subsequent) pachyderm clusters (get the initial deployment manifest by running `pachctl deploy --dry-run [YOUR_OPTIONS_HERE] > manifest.json`, make your edits, and do `kubectl create -f manifest.json`)

**Comment by gabrielgrant** [comment]
also need to explicitly set the namepace for some commands to work (see #2745)

**Comment by jdoliner** [comment]
Talking with @chainlink today, he mentioned that this can probably be solved well by the addition of a pachyderm k8s operator.
