### ISSUE TITLE
MongoDb example fails

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3380]
**What happened?**:
When running the example with MongoDb, the job fails with the log saying: 
```Error parsing command line: unrecognised option '-n'
try 'mongo --help' for more information
Error parsing command line: unrecognised option '-n'
try 'mongo --help' for more information
Error parsing command line: unrecognised option '-n'
try 'mongo --help' for more information
```
Although when I run the same `mongo` command from a terminal it works.

**Anything else we need to know?**:
It is the second  example failing. Perhaps you should have unit test for all your examples?

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.8.2               
pachd               1.8.2 

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube

- OS (e.g. from /etc/os-release):
ubuntu 18.04

**Comment by ysimonson** [comment]
The mongodb example was removed because it ran on a very old version of pachyderm
