### ISSUE TITLE
Update autoscaling docs

### ISSUE THREAD

**Issue by mdgoldberg** [pachyderm/pachyderm#3388]
The autoscaling docs here refer to `scaleDownThreshold`, but the Pipeline spec docs indicate that `standby` replaced `scaleDownThreshold`. Could they be updated to reflect how one would use `standby` to achieve the same thing? Thanks!

http://docs.pachyderm.io/en/latest/managing_pachyderm/autoscaling.html#pachyderm-autoscaling-of-workers

**Comment by mindthevirt** [comment]
This has been fully replaced by the `standby` functionality.
