### ISSUE TITLE
Add a `-n` flag for as a shorthand `--namespace`

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3395]
To mirror k8s. This may not be possible if we already use `-n` as shorthand for flags elsewhere.

Requested in https://github.com/pachyderm/pachyderm/pull/3359#discussion_r250361772

**Comment by ysimonson** [comment]
@JoeyZwicker adding a `-n` as shorthand for `--namespace` would break backwards compatibility for `list-commit`, which uses `-n` as shorthand for `--number`. It was introduced 2 years ago. Do we want that?

IMO it's not worth it.

**Comment by JoeyZwicker** [comment]
Agreed that its not worth it for right now. I do think that namespace is a super common use case for enterprise deployments and we might want a shorthand for it at some point
