### ISSUE TITLE
worker fails to exec user code when run as non-root user

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3405]
when worker (`user` container in a pipeline pod) is running without being root, it fails when trying to execute user code: `"failed to process datum with error: error runUserCode: error cmd.Start: fork/exec /usr/bin/python3: operation not permitted"`

The problem emanates from this call: https://github.com/pachyderm/pachyderm/blame/462145baade0514ffbfa47637711945e1c3917ea/src/server/worker/api_server.go#L565-L583

Current working theory is that the problem lies in the user switching, here: 
https://github.com/pachyderm/pachyderm/blob/462145baade0514ffbfa47637711945e1c3917ea/src/server/worker/api_server.go#L573-L578

part of #2635

**Comment by gabrielgrant** [comment]
The pachctl binary for linux corresponding to that image version is here:
[pachctl-1.8.2-2df33038a2e15e53e70b1269438b9681c03bf618.tar.gz](https://github.com/pachyderm/pachyderm/files/2798620/pachctl-1.8.2-2df33038a2e15e53e70b1269438b9681c03bf618.tar.gz)

**Comment by ysimonson** [comment]
It looks like you should be able to set the user via the pipeline spec. Have you tried that already?

**Comment by gabrielgrant** [comment]
`transform.user` controls which user the worker exec's as, but it seems we need to disable explicitly exec-ing as a specific user altogether

**Comment by ysimonson** [comment]
Oh right, they randomize the user id in openshift right?
