### ISSUE TITLE
Cannot get to compile on the PI

### ISSUE THREAD

**Issue by Mccpie01** [pachyderm/pachyderm#3406]
I am trying to compile for the ARMS (Raspberry Pi/ Rock Pi). But i get the error with that make. 

> sudo make launch

GO15VENDOREXPERIMENT=1 go install -ldflags "-X github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/version.AdditionalVersion=-82a7869060f00a48b266fffde9cdf87452740370" ./src/server/cmd/pachctl pachctl deploy local --dry-run | kubectl apply -f - /bin/sh: 1: pachctl: Exec format error error: no objects passed to apply Makefile:357: recipe for target 'launch' failed make: *** [launch] Error 1
My best Guss is that it did not see the ARM architecture. **Can it be added?**

**What is the goal / desired outcome?**  To make it work on ARMs (Raspberry pi/Rockpi)

**If there is a way to accomplish this today via a workaround, what does that require?**   recognize that it’s on arm

**(Optional) What is your proposal for a feature to solve this?**  Add support to recognize that it’s on arm

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm64"}

- Pachyderm CLI version (use `pachctl version`): won't compile/Install

- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

**Comment by gabrielgrant** [comment]
To clarify, are you trying to run `pachctl` on the RPi, or run the whole of pachyderm (including kubernetes) there?

**Comment by Mccpie01** [comment]
I want to run pachyderm on my Pi. I cannot get it to compile.

I saw that you tried it in the past. Were you ever able to compile it on the Pi?

**Comment by gabrielgrant** [comment]
@Mccpie01 the error you've shown is because there is no target in the Makefile called `launch`, so running `sudo make launch` is going to fail on any machine, regardless of architecture

I think you may want to be running `make install`?

**Comment by Mccpie01** [comment]
I found the issue. It installs in my local user and not in /usr/local/bin
and in the user local bin is a x86 bin. (Probable for my first steps in Linux )
So i have to close the issue.

Thanks for pointing me in the right direction

**Comment by Mccpie01** [comment]
``

**Comment by gabrielgrant** [comment]
@Mccpie01 to clarify, did you manage to get it to compile for arm?

**Comment by Mccpie01** [comment]
Yes

________________________________
De : Gabriel Grant <notifications@github.com>
Envoyé : 29 janvier 2019 01:03
À : pachyderm/pachyderm
Cc : Mccpie01; Mention
Objet : Re: [pachyderm/pachyderm] Cannot get to compile on the PI (#3406)


@Mccpie01<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMccpie01&data=02%7C01%7C%7Cea87d1d7f7624faab70a08d685859876%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636843206159448543&sdata=Le29b7ssQ3IfoLyJq3Lr9QHzcyjuphNIwAsoZQHN%2F%2Fs%3D&reserved=0> to clarify, did you manage to get it to compile for arm?

**Comment by gabrielgrant** [comment]
ok, to get the whole of pach running on RPi will require rebuilding the docker images for ARM, in addition to  recompiling the command line client

Have you got kubernetes running on RPi/ARM already? It seems that isn't something that is officially supported by k8s out of the box, though it does seem to be possible: https://github.com/luxas/kubernetes-on-arm

**Comment by Mccpie01** [comment]
Ye si got kubernetes running ok, I also have docker running but have not tested it yet


________________________________
De : Gabriel Grant <notifications@github.com>
Envoyé : 30 janvier 2019 09:39
À : pachyderm/pachyderm
Cc : Mccpie01; Mention
Objet : Re: [pachyderm/pachyderm] Cannot get to compile on the PI (#3406)


ok, to get the whole of pach running on RPi will require rebuilding the docker images for ARM, in addition to recompiling the command line client

Have you got kubernetes running on RPi/ARM already? It seems that isn't something that is officially supported by k8s out of the box, though it does seem to be possible: https://github.com/luxas/kubernetes-on-arm<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fluxas%2Fkubernetes-on-arm&data=02%7C01%7C%7C4026bef6bb4a4ac16ed408d68696d66d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636844379726049736&sdata=aGmS%2ByzHzKBOwexCe0fnximSOK0yHbi5kysXcldcB3w%3D&reserved=0>
