### ISSUE TITLE
Implicit port forwarding does not respect `--namespace` in commands that take the flag

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3413]

**Comment by gabrielgrant** [comment]
This should almost certainly be available as a config param in addition to a flag -- having to add this to every command is a terrible user experience #3036

**Comment by gabrielgrant** [comment]
:+1: filed as #3419

**Comment by gabrielgrant** [comment]
actually, this suggestion from @jdoliner  might be even better: https://github.com/pachyderm/pachyderm/issues/2745#issuecomment-371302004

That should still work with new auto-port-forwarding, right?

**Comment by ysimonson** [comment]
Yeah that would work.

Turns out this is not a bug. I thought a bunch of `pachctl` commands take `--namespace`, but the only ones that do are explicit port forwarding and deployment-related. All of the commands that use implicit port forwarding do not take a `--namespace`.

**Comment by mdaniel** [comment]
> All of the commands that use implicit port forwarding do not take a --namespace.

Yes, and it is the **implicit** part which makes that a bug. Through what mechanism would you expect `pachctl version` to learn that `pachd` is in a `pach` namespace, and not just dumped into `default`?

I'm on-board with adding the namespace to `~/.pachyderm/config.json` as #3419 proposes, but given that I had absolutely zero idea such a file existed before Wednesday, that might not be the best UX in the world. It also means that the user would need to swap `config.json` files around to interact with more than one `pachd` (or use `$PACHCTL_CONFIG`, which I also only recently learned about)

**Comment by ysimonson** [comment]
Implicit port forwarding is not meant to work for all situations, but rather streamline the default use case (i.e. using the default namespace, and no port customization.) Because of that, any of these methods will disable implicit port forwarding:

1) Setting `ADDRESS`
2) Running explicit port forwarding (which additionally allows you to set a namespace.)
3) If you're on the bleeding edge, running a command with `--no-port-forwarding`

Do you need implicit port forwarding? If so, have you tried [setting the k8s context?](https://github.com/pachyderm/pachyderm/issues/2745#issuecomment-371302004)

**Comment by LaurentGoderre** [comment]
@ysimonson can you explain your case 2\. Running explicit port forwarding (which additionally allows you to set a namespace.)

I did run explicit port forwarding but I was getting tons of errors on all pachtcl commands about implicit port forwarding not enabled because of an error.

**Comment by ysimonson** [comment]
@LaurentGoderre were you getting a warning that looked something like this? `Implicit port forwarding was not enabled because the pidfile could not be written to.`

I can update it to just log a debug message; warning seems too high of a level for something like that.

**Comment by ysimonson** [comment]
Addressed in #3494
