### ISSUE TITLE
Allow setting namespace flag in pach config file

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3419]
With our new automatic/implicit port forwarding, users now will ahve to set `--namespace` on every command (#3413). This is pretty annoying, so we should let people set this in one place (the config) to affect all commands

**Comment by gabrielgrant** [comment]
ooh, actually, this looks like it might be a better approach: https://github.com/pachyderm/pachyderm/issues/2745#issuecomment-371302004

**Comment by ysimonson** [comment]
There's no `--namespace` argument, except for explicit port forwarding (`pachctl port-forward`)

**Comment by gabrielgrant** [comment]
does that mean that implicit port forwarding breaks when pach is deployed in a non-standard namespace? (but works if the steps in https://github.com/pachyderm/pachyderm/issues/2745#issuecomment-371302004 have been followed?)

**Comment by ysimonson** [comment]
Yeah. You have to use explicit port forwarding for non-default namespaces.

**Comment by gabrielgrant** [comment]
but if you've set up your default namespace with `kubectl config set-context dev --namespace=development` does auto-port-forward use that?

**Comment by ysimonson** [comment]
I think so, but haven't checked

**Comment by christianladron** [comment]
I made these changes to use the namespace of the kubectl context in the implicit port forward, do you think that this is a good approach?
https://github.com/christianladron/pachyderm/pull/1/files

**Comment by ysimonson** [comment]
@gabrielgrant It looks like port forwarder actually does not respect the currently set context namespace. Let's use this ticket to address that specific issue.

@christianladron That looks like the right approach to get the port forwarder to respect the currently set namespace, and wish I saw it earlier before digging around k8s' labyrinthine documentation to find the same thing! #3786 is going to make some overlapping changes, though, and I want to also address the same issue for deployment-related commands as well.
