### ISSUE TITLE
Lots of "transport is closing"

### ISSUE THREAD

**Issue by gregfriedland** [pachyderm/pachyderm#3424]
**What happened?**:
I get "transport is closing" for all sorts of pachctl commands including: inspect-job, update-pipeline, inspect-pipeline, list-pipeline, etc. If I keep trying the command it eventually succeeds but then it crops up again in a minute for a different command.

**What you expected to happen?**:
No error to occur.

**How to reproduce it (as minimally and precisely as possible)?**:
I can repro it easily on my setup but not sure what about it is causing issues.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION
pachctl             1.8.2
pachd               1.8.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
aws
- OS (e.g. from /etc/os-release):
Mac OS X 10.14.2
- Others:

**Comment by gregfriedland** [comment]
I just ran `list-job` 10 times in a row and got 10 errors.

**Comment by mkaja** [comment]
any update on this ? having similar issue
pachctl list-repo
transport is closing


 pachctl port-forward &
NOTE: kubernetes port-forward often outputs benign error messages, these should be ignored unless they seem to be impacting your ability to connect over the forwarded port.
Forwarding the dash (Pachyderm dashboard) UI port to http://localhost:30080 ...
Forwarding the pachd (Pachyderm daemon) port...
 E0326 22:24:01.395667   65263 portforward.go:178] lost connection to pod


pod logs : 
kubectl logs pachd-xxx --previous
time="2019-03-25T21:47:06Z" level=info msg="AWS deployed with cloudfront distribution at
"
time="2019-03-25T21:47:06Z" level=warning msg="TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory"
time="2019-03-25T21:47:06Z" level=warning msg="TLS disabled: could not stat private key at /pachd-tls-cert/tls.key: stat /pachd-tls-cert/tls.key: no such file or directory"
time="2019-03-25T21:47:06Z" level=info msg="validating kubernetes access returned no errors"
time="2019-03-25T21:47:36Z" level=info msg="error starting githook server context deadline exceeded
"
panic: could not intiailize Pachyderm client in driver: context deadline exceeded

goroutine 181 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient.func1()
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:164 +0x12d
sync.(*Once).Do(0xc4205502e0, 0xc420722f88)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient(0xc4205502d0, 0x1daf940, 0xc4200480b0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:160 +0x50
github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver.func3(0xc4205502d0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:148 +0x43
created by github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:148 +0x498

**Comment by ysimonson** [comment]
@gregfriedland these errors happen when there's trouble connecting to the cluster, which is tricky because there's a number of reasons why it can happen.

@mkaja can you try port forwarding directly through k8s and seeing what happens?

1) Find the name of the pachd pod name via `kubectl get pods`
2) Port forward via `kubectl port-forward <pachd pod name> 30650:650`
3) Issue `pachctl` commands through kubectl's port forwarding: `PACHD_ADDRESS=localhost:30650 pachctl list-repo`

**Comment by jdoliner** [comment]
I think generally speaking you should expect to see these when using any sort of port forwarding. The only real long-term solution is to connect through the service.

**Comment by mkaja** [comment]
@ysimonson tried that 

kubectl port-forward pachd-5988d68cd7-9zx9w 30650:650
Forwarding from 127.0.0.1:30650 -> 650
Forwarding from [::1]:30650 -> 650

PACHD_ADDRESS=localhost:30650
pachctl list-repo
context deadline exceeded

**Comment by ysimonson** [comment]
@mkaja that'd be an issue with k8s connectivity, rather than a bug with pachyderm itself. I'm not sure what the most common causes are. The first thing I'd look into are whether there's a firewall between you and the cluster that's blocking connectivity.

**Comment by jdoliner** [comment]
I'm going to close this because I don't think there's anything particular for us to fix in Pachyderm to make this better. Afaict these are connectivity issues stemming from port-forward and k8s service unreliability. Which are fairly out of our control, they also seem to be things that work fairly well for most deployments. Please reopen if there's something you think we could change in Pachyderm to make this better.
