### ISSUE TITLE
Update official Helm chart to 1.8

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3438]
from https://github.com/pachyderm/pachyderm/issues/2771#issuecomment-459919746

This should really just happen automatically as part of our deploy process (#2798), but for now we should do so manually

Unclear how upgrades/migrations should be handled with helm deployments (#3439)

**Comment by jdoliner** [comment]
This seems to have happened. Just in time for it to need to be updated to 1.9. We're working on having an official helm chart though so hopefully this well get better soon.
