### ISSUE TITLE
Intermittent Failure of Test296

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#344]
@ commit: 0e9966766af72e7e649c5d923e5775f473d43ad4

Running the line:

CGOENABLED=0 GO15VENDOREXPERIMENT=1 go test -v -cover -timeout 20s $(go list ./src/server/... | grep -v '/src/server/vendor/' | grep '/src/server/pfs/fuse')

Creates a failure of Test296 (see attached logs). We don't expect this output to have multiple valid values.

[failure6-weird.log.txt](https://github.com/pachyderm/pachyderm/files/232581/failure6-weird.log.txt)

**Comment by sjezewski** [comment]
Popped up on travis too:

https://travis-ci.org/pachyderm/pachyderm/builds/125140723

**Comment by derekchiang** [comment]
Fixed
