### ISSUE TITLE
Create official docker image for pachctl

### ISSUE THREAD

**Issue by LaurentGoderre** [pachyderm/pachyderm#3446]
**What is the goal / desired outcome?**

Having official images for the `pachct`l executable would make it simple to run the client on multiple environments. (see postgres image as an example https://github.com/docker-library/postgres)

**(Optional) What is your proposal for a feature to solve this?**

I am an official maintainer for the NodeJS docker image and have done a lot of the work for the management of that image and I am volunteering to do most of the ground work required to get the image setup. I already created an image for Alpine linux which gives an image that is 60mb.

**Comment by jdoliner** [comment]
Doing it this way should also be much easier since it can use the same script we use to compile our other binaries. If you take a look at `docker-build-pachd` it looks like this:

```
docker-build-pachd: docker-clean-pachd
	docker run  \
		-v $$GOPATH/src/github.com/pachyderm/pachyderm:/go/src/github.com/pachyderm/pachyderm \
		-v $$HOME/.cache/go-build:/root/.cache/go-build \
		--name pachd_compile $(COMPILE_RUN_ARGS) $(COMPILE_IMAGE) /go/src/github.com/pachyderm/pachyderm/etc/compile/compile.sh pachd "$(LD_FLAGS)"
```

that argument on the last line `pachd` could be changed to `pachctl` to compile `pachctl` instead. I suspect a few other complications will arise but that should be most of it.

The harder question here is how to make `pachctl` connect to `pachd` from within a container. Have you thought about how we might pull that off @LaurentGoderre?

**Comment by LaurentGoderre** [comment]
@JoeyZwicker I would strongly recommend using `FROM scratch` and adopt the official image standard. Otherwise you will not get the full benefit of the images security scans and automated security updated you get from Docker Hub

**Comment by LaurentGoderre** [comment]
@jdoliner for connecting to pachd from a container, wouldn't it simply be a matter of setting `-e ADDRESS=[ip to pahcd]`?

**Comment by LaurentGoderre** [comment]
Here's the repo that creates the images: https://github.com/LaurentGoderre/docker-pachctl

**Comment by tianon** [comment]
Given that there's an officially-published binary release of `pachctl`, I'd honestly recommend _not_ going for `FROM scratch` and instead targeting `FROM alpine:3.9`.  It's a ~4MB difference (which is pretty negligible when compared to even the _compressed_ ~14MB of `pachctl` on https://github.com/pachyderm/pachyderm/releases/tag/v1.8.5).  Then the image can ideally consume those official release binaries directly, something like this:

```dockerfile
FROM alpine:3.9
ENV PACHCTL_VERSION 1.8.5
RUN set -eux; \
	wget -O pachctl.tgz "https://github.com/pachyderm/pachyderm/releases/download/v$PACHCTL_VERSION/pachctl_${PACHCTL_VERSION}_linux_amd64.tar.gz"; \
	tar -xvf pachctl.tgz --strip-components=1 -C /usr/local/bin/; \
	rm pachctl.tgz
```

(Note that this doesn't currently actually work because the release binaries are compiled dynamically instead of statically, so they're expecting to find glibc, but that's a reasonably easy problem to solve and IMO worthwhile for published binary releases.)

**Comment by LaurentGoderre** [comment]
@tianon, what about all the other achs?

**Comment by tianon** [comment]
I mean, it's Go, so releasing official binaries for every architecture the
project wants to officially support is a pretty easy task too. 😅

(Go's cross-compilation support is legendary 😃)

**Comment by gabrielgrant** [comment]
There have been a few requests for arm (#1734 ), but hasn't been tackled yet. I haven't done any cross compilation with go, so good to know it shouldn't be hard

**Comment by LaurentGoderre** [comment]
@gabrielgrant if we can create the binaries for all the arch using static linking, we can probably get this as an official image and all the different arch will be managed in docker hub.

**Comment by tianon** [comment]
Still no idea what `pachctl` is, but I took https://github.com/tianon/gosu/blob/f87df69c868e19f7258b4facb7c2472d76d98dda/Dockerfile (which I use to release `gosu` binaries for a pretty large number of architectures with the smallest possible binaries I could get Go to create), and adapted it to build the latest release of `pachctl`:

```dockerfile
FROM golang:1.12-alpine3.9

RUN apk add --no-cache file

ENV PACHYDERM_VERSION 1.8.5
WORKDIR /go/src/github.com/pachyderm/pachyderm
RUN set -eux; \
	wget -O pachyderm.tgz "https://github.com/pachyderm/pachyderm/archive/v${PACHYDERM_VERSION}.tar.gz"; \
	tar -xvf pachyderm.tgz --strip-components=1; \
	rm pachyderm.tgz
WORKDIR ./src/server/cmd/pachctl

# disable CGO for ALL THE THINGS (to help ensure no libc)
ENV CGO_ENABLED 0
ENV BUILD_FLAGS="-v -ldflags '-d -s -w'"

# /go/bin/pachctl-$(dpkg --print-architecture)

RUN set -eux; \
	eval "GOARCH=amd64 go build $BUILD_FLAGS -o /go/bin/pachctl-amd64"; \
	file /go/bin/pachctl-amd64; \
	/go/bin/pachctl-amd64 --help

# ../../pkg/deploy/assets/assets.go:82:37: constant 8589934592 overflows int
#RUN set -eux; \
#	eval "GOARCH=386 go build $BUILD_FLAGS -o /go/bin/pachctl-i386"; \
#	file /go/bin/pachctl-i386; \
#	/go/bin/pachctl-i386 --help

# ../../pkg/deploy/assets/assets.go:82:37: constant 8589934592 overflows int
#RUN set -eux; \
#	eval "GOARCH=arm GOARM=5 go build $BUILD_FLAGS -o /go/bin/pachctl-armel"; \
#	file /go/bin/pachctl-armel
#RUN set -eux; \
#	eval "GOARCH=arm GOARM=6 go build $BUILD_FLAGS -o /go/bin/pachctl-armhf"; \
#	file /go/bin/pachctl-armhf
# boo Raspberry Pi, making life hard
#RUN set -eux; \
#	eval "GOARCH=arm GOARM=7 go build $BUILD_FLAGS -o /go/bin/pachctl-armhf"; \
#	file /go/bin/pachctl-armhf

RUN set -eux; \
	eval "GOARCH=arm64 go build $BUILD_FLAGS -o /go/bin/pachctl-arm64"; \
	file /go/bin/pachctl-arm64

RUN set -eux; \
	eval "GOARCH=ppc64 go build $BUILD_FLAGS -o /go/bin/pachctl-ppc64"; \
	file /go/bin/pachctl-ppc64

RUN set -eux; \
	eval "GOARCH=ppc64le go build $BUILD_FLAGS -o /go/bin/pachctl-ppc64el"; \
	file /go/bin/pachctl-ppc64el

RUN set -eux; \
	eval "GOARCH=s390x go build $BUILD_FLAGS -o /go/bin/pachctl-s390x"; \
	file /go/bin/pachctl-s390x

RUN file /go/bin/pachctl-*
```

I've had to comment out all 32-bit platforms since there's some constant in here somewhere that overflows an `int`, but otherwise it appears reasonably OK:

```
/go/bin/pachctl-amd64:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Qa0N5tgrqh9Ws0hmAjMX/CEcy2VNZ5newmwm-9eEN/lz6JT17Cb3v33NZRNA-k/LYWF4FzHeFQwmsE9zDpl, stripped
/go/bin/pachctl-arm64:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=ObIrbZrDC3xbeByO3fx-/ErjTZZbyXg_t-vOeOuW1/eqgptHcmaTinyAFtYn5f/Hg1WybSpenoIqPbmKUjR, stripped
/go/bin/pachctl-ppc64:   ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, Go BuildID=69hid6CLNHdtMJ7EoQnI/V9kt7uUKIWT1IdlEIr7-/rxITTV8y3BaBlYgjJ7ga/ovG2muJF0dlgWwqtaYgH, stripped
/go/bin/pachctl-ppc64el: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, Go BuildID=8C976BozPzHj0VgHiMU7/ZPhDqujGUzSZy2gu77K6/_h8Ya2tJA44Mt6AArntS/n8v4HgLqAKqs_bnMNrxL, stripped
/go/bin/pachctl-s390x:   ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, Go BuildID=a-CIo0Wry9oMWQh-yk22/R-RZZEv4QAEhIJ7k1Xqm/cn6TkXDy2viLE2QW8UBn/iUbdfe827iokF_AJm_I_, stripped
```
```
-rwxr-xr-x    1 root     root       42.4M Feb 28 23:43 pachctl-amd64*
-rwxr-xr-x    1 root     root       40.6M Feb 28 23:45 pachctl-arm64*
-rwxr-xr-x    1 root     root       41.1M Feb 28 23:45 pachctl-ppc64*
-rwxr-xr-x    1 root     root       41.0M Feb 28 23:46 pachctl-ppc64el*
-rwxr-xr-x    1 root     root       42.4M Feb 28 23:46 pachctl-s390x*
```

**Comment by LaurentGoderre** [comment]
Amazing @tianon!! Thanks for this!

**Comment by chriszs** [comment]
Currently using a fork of @LaurentGoderre's Dockerfile for this. Would also like an official one.

**Comment by LaurentGoderre** [comment]
I can transfer ownership of my repo to this org and help maintain it.

**Comment by ysimonson** [comment]
Official support is a WIP, and should come out around the 1.11 release. However, we've pursued a different approach than the excellent work @LaurentGoderre has done. The official version ties deeply into our CI and deployment infrastructure. This will provide better support for the newest versions of `pachctl`, at the detriment of lack of support for multiple architectures or non-glibc bindings.

This covers our internal needs for a dockerized `pachctl` (for use in testing Pachyderm hub, and as a first step toward integrating with github actions) and I suspect may cover most other needs as well. However, users who want support for other architectures or non-glibc can use Laurent's builds, at least for versions up to 1.9.

I do hope to support multiple architectures (and possibly non-glibc) eventually via docker multi-arch builds. But I get the impression that it's not particularly mature yet.
