### ISSUE TITLE
CreateRepo __spec__ should not always emit an error

### ISSUE THREAD

**Issue by mdaniel** [pachyderm/pachyderm#3458]
**What happened?**:

On startup, `pachd` emits at least minimum two `ERROR` level log messages complaining about the inability to create the `__spec__` repo

```
2019-02-06T21:28:12Z ERROR pfs.API.CreateRepo {"duration":0.009202572,"error":"cannot create \"__spec__\" as it already exists","request":{"repo":{"name":"__spec__"}},"response":null} []
2019-02-06T21:28:12Z ERROR pfs.API.CreateRepo {"duration":0.002710935,"error":"cannot create \"__spec__\" as it already exists","request":{"repo":{"name":"__spec__"}},"response":null} []
```

**What you expected to happen?**:

The optimal outcome would be not to repeatedly try and create the `__spec__` repo, but if that has distributed-processing landmines to it, then the second best is to inspect the `err` and if it is "as it already exists", then suppress the `ERROR` message because it's not an **ERROR** if the request was to create a repo and the repo already exists, since the `CreateRepo` did as it was asked

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
```
pachctl             1.8.2
pachd               1.8.2
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by Bucca1992** [comment]
@mdaniel Did you solve this problem?

**Comment by mdaniel** [comment]
No, but I'm not the one who is solving it. I haven't seen it in a while, but I also haven't been creating repos recently, so unknown if it went away or I just haven't been triggering the behavior

**Comment by jdoliner** [comment]
This has been fixed, if you see this error message again please reopen this issue.
