### ISSUE TITLE
Specify upgrade version for brew in docs

### ISSUE THREAD

**Issue by discdiver** [pachyderm/pachyderm#3463]
**What is the goal / desired outcome?**
Clear upgrade command for Mac users in the docs.

**If there is a way to accomplish this today via workaround, what does that require?**
Looking up the version elsewhere in the docs. I thought the command might be several things other than `brew upgrade pachctl@1.8`, e.g. (pachyderm@1.8.3). 

**(Optional) What is your proposal for a feature to solve this?**
List `brew upgrade pachctl@1.8` as the command to use in the docs on the Pachyderm Version Upgrades page [https://pachyderm.readthedocs.io/en/latest/deployment/upgrading.html#upgrading-pachctl](https://pachyderm.readthedocs.io/en/latest/deployment/upgrading.html#upgrading-pachctl).

**Comment by JoeyZwicker** [comment]
This is definitely an easy clarification we can make. Thanks @discdiver !

**Comment by svekars** [comment]
#3945
