### ISSUE TITLE
Uses consistent hashing for shards assignment

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#348]
Currently, each server is mapped to a set of shards through hashing.  However, a change in server membership (i.e. nodes joining and leaving) can result in a drastic change in the mapping, causing each server to remove and re-add a large number of shards.  Such remapping can be costly since each re-adding of a shard results in a large number of I/Os to the object store.

We can get around this problem by using a [consistent hashing scheme](kubernetes.io/docs/user-guide/jobs/), which has the property that when a hash table is resized, only k/n keys need to be remapped on average, where k is the number of keys, and n is the number of slots.

**Comment by jdoliner** [comment]
I think we're going to do away with shards in the pfs refactor so this will become a non issue.
Closing.
