### ISSUE TITLE
Pachyderm 1.8.3 and 1.8.4 missing oidc dependency, can't auth. 1.8.2 works

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3482]
**What happened?**:
Upgraded pachctl to 1.8.4 from 1.8.2 (also tried 1.8.3) and pachctl commands won't work with our OIDC enabled cluster
**What you expected to happen?**:
pachctl commands to work
**How to reproduce it (as minimally and precisely as possible)?**:
Install k8s cluster with OIDC auth. Run:
```
$ pachctl port-forward --namespace pachyderm
No Auth Provider found for name "oidc"
```
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
sjacobs@neon-07071 ~ $ pachctl version
COMPONENT           VERSION
pachctl             1.8.4
ERRO[0000] Implicit port forwarding was not enabled because the kubernetes config could not be read: No Auth Provider found for name "oidc"
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
kubeadm v1.13.2
- Others:
Fix imports:
import (
     _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
[https://github.com/kubernetes/client-go/issues/345](https://github.com/kubernetes/client-go/issues/345)

**Comment by gabrielgrant** [comment]
Looks like this may have something to do with the new auto-port-forward feature...

Have you upgraded the version of pach deployed in your k8s cluster, or just the local client?

If you've upgraded the deployed version, can you please try accessing it again with the old (<=1.8.2) client?

**Comment by brokenjacobs** [comment]
This is an issue with the pachctl client. port-foward.go needs to include that library or it can't talk to the api service when an oidc provider is in the kubeconfig.

pachd won't be affected because it doesn't use OIDC authentication.

The k8s client-go library is parsing the ~/.kube/config file and erroring out when it sees:
```
auth-provider:
  name: oidc
```
Under a user setting in the configuration. Looks like a common problem among client-go using projects from google, just a missing dependency.

**Comment by brokenjacobs** [comment]
FYI I can confirm for you that setting the "ADDRESS" env (and not adding --no-port-forwarding at all) works against the v1.8.2 cluster with a v1.8.4 client:
```
$ export PACHD_ADDRESS=******:30650
$ pachctl list-repo
NAME       CREATED       SIZE
images     9 seconds ago 0B
level-zero 29 hours ago  295.2KiB
$ pachctl version
COMPONENT           VERSION
pachctl             1.8.4
pachd               1.8.2
$ unset PACHD_ADDRESS
$ pachctl version
COMPONENT           VERSION
pachctl             1.8.4
ERRO[0000] Implicit port forwarding was not enabled because the kubernetes config could not be read: No Auth Provider found for name "oidc"

**Comment by brokenjacobs** [comment]
I would test adding the import but I'm having some issues compiling pachctl.

**Comment by brokenjacobs** [comment]
As requested, 1.8.2 works against 1.8.4 cluster:
export ADDRESS=****:30650
$ pachctl version
COMPONENT           VERSION
pachctl             1.8.2
pachd               1.8.4
$ unset ADDRESS
sjacobs@neon-07071 bin $ pachctl.old port-forward --namespace pachyderm &
CTRL-C to exit
NOTE: kubernetes port-forward often outputs benign error messages, these should be ignored unless they seem to be impacting your ability to connect over the forwarded port.
Forwarding the dash (Pachyderm dashboard) UI port to http://localhost:30080 ...
Forwarding the pachd (Pachyderm daemon) port...
Forwarding the SAML ACS port...
[1]+ pachctl.old port-forward --namespace pachyderm &
$ pachctl.old version
COMPONENT           VERSION
pachctl             1.8.2
pachd               1.8.4

**Comment by ysimonson** [comment]
Thanks for all the details @brokenjacobs, I'll dig in today

**Comment by ysimonson** [comment]
@brokenjacobs are you still having issues building `pachctl` with `make install`? If not, could you see if this branch fixes it for you? https://github.com/pachyderm/pachyderm/pull/3504

**Comment by ysimonson** [comment]
It's probably worth waiting until CI is green first actually; pulling in these dependencies is requiring a bunch of upgrades to some other dependencies we have, which in turn may require some further changes.
