### ISSUE TITLE
Confused about backend storage

### ISSUE THREAD

**Issue by iswaverly** [pachyderm/pachyderm#3493]
As is mentioned in the official charts documents, Pachyderm support S3 as backend storage. However, the "PFS" file system use POSIX as interface. 
Does it means that Pachyderm store the data use S3, but provide POSIX as interface for pipeline component.

**Comment by JoeyZwicker** [comment]
Hi @iswaverly. 

> Does it means that Pachyderm store the data use S3, but provide POSIX as interface for pipeline component.

Yes that is correct. Pachyderm uses S3 to store the content-addressed data that you put into the system, but that data is exposed to your Pachyderm Pipelines as simply files in the local file system of the container. 

I'm going to close this issue, but if for any reason your question doesn't feel fully answered, feel free to reopen or just continue the conversation here. In addition, you can join our [Public Slack Channel](slack.pachyderm.io) anytime to get answers like this from the Pachyderm team and other members of the community.
