### ISSUE TITLE
Kubernetes credentials issue

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#350]
We had an issue show up in the wild where `runPipeline` failed because it couldn't find the output commit that it was creating. Logs are attached, bug was reported by @dwhitena.

[logs.txt](https://github.com/pachyderm/pachyderm/files/235234/logs.txt)

**Comment by jdoliner** [comment]
Updates on this, it seems to be due to kubernetes credentials issues, for some reason when we send the job to K8s it says we need credentials for it. Likely the culprit here is a k8s configuration we haven't seen before but unfortunately we don't know anything more specific than that.

**Comment by jdoliner** [comment]
@dwhitena it just occurred to me that another thing that might be handy in debugging this is the logs from kubernetes itself. You can get those with `kubectl logs k8s-master-127.0.0.1`

**Comment by dwhitena** [comment]
@jdoliner Attached is the output of `kubectl logs k8s-master-127.0.0.1 apiserver`, because just running `kubectl logs k8s-master-127.0.0.1` returns:

```
Error from server: a container name must be specified for pod k8s-master-127.0.0.1, choose one of: [controller-manager apiserver scheduler setup]
```
[log.txt](https://github.com/pachyderm/pachyderm/files/238755/log.txt)

**Comment by sjezewski** [comment]
I can't reproduce this issue. Some googling suggests that it may be a credentials issue?

If we see this popup again, I'd like to see your kubeconfig file
