### ISSUE TITLE
pachctl brew tap for 1.8.5 is failing its checksum

### ISSUE THREAD

**Issue by mdaniel** [pachyderm/pachyderm#3507]
**What happened?**:

The [sha256 in the formula](https://github.com/pachyderm/homebrew-tap/commit/c694da588a9855075685048decfa169cd851da53#diff-022b80f74905b9865520dba97c5d1a2cR9) is incorrect for the binary that is on the releases page

```
==> Downloading https://github.com/pachyderm/pachyderm/releases/download/v1.8.5/pachctl_1.8.5_darwin_amd64.zip
==> Verifying 11a504de4d10ef015cc6acdf14225f578105d3161da1b75b196da674bffb6dee--pachctl_1.8.5_darwin_amd64.zip checksum
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: f096d0153150614b9be8d66116790d7fd3052185d7c4e723d07c576899038394
Actual: 5bd04888de2567c2a07e405c240efba4f3cee8c9ca36d4f11d1fd92d8285c3c4
```

**What you expected to happen?**:

For the checksum to match

**How to reproduce it (as minimally and precisely as possible)?**:

I confirmed this is not a brew problem:

```console
$ curl -sSfL https://github.com/pachyderm/pachyderm/releases/download/v1.8.5/pachctl_1.8.5_darwin_amd64.zip | shasum -a 256
5bd04888de2567c2a07e405c240efba4f3cee8c9ca36d4f11d1fd92d8285c3c4  -
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by brycemcanally** [comment]
This should be fixed now. You will need to delete and re-download the package.
