### ISSUE TITLE
option to show timestamps with logs

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3521]
**What is the goal / desired outcome?**

see when certain output came from (particularly important for people still learning pach's semantics eg. did my datum actually get re-processed after i pushed my updated code? when did that retry happen? etc.)

**If there is a way to accomplish this today via workaround, what does that require?**

1. make sure to log verbosely and always include your own timestamps. this only works for your own log lines, not for pach-generated log lines

2. view raw logs, but this makes the output super noisy and hard-to-read

**(Optional) What is your proposal for a feature to solve this?**

a command-line flag to output lines prefixed with a human-readable timestamp (for bonus points, accept an optional user-defined date format string)

Note: This was one of the warts mentioned in @szeitlin's [blog post](https://szeitlin.github.io/posts/engineering/pachyderm-vs-airflow/#some-things-that-are-currently-being-improved)

**Comment by jdoliner** [comment]
The `--raw` option on `pachctl logs` does this, it shows other stuff too so it's not quite as nice, but I'm not totally sure that we could add something that would be nicer than formatting the logs yourself using `jq` or something like it.

**Comment by ysimonson** [comment]
These are now shown
