### ISSUE TITLE
start-commit without branch specified should throw an error

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3528]
**What happened?**:
When you start a commit with `pachctl start-commit <repo>` without specifying a branch pachctl continues without throwing an error. 

```
$ pachctl start-commit GoT_Scripts
244e78b42def4e00b76c3a1454ea266a
``` 

**What you expected to happen?**:
pachctl should throw an error stating a branch has to be specified that same way `pachctl put-file` would. 
**How to reproduce it (as minimally and precisely as possible)?**:
1. deploy pachyderm
2. create repo
3. run `pachctl start-commit <repo>` 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`): pachctl 1.8.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): Mac Mojave
- Others:

**Comment by JoeyZwicker** [comment]
This is expected behavior. Branch is a option argument and not specifying one creates the new commit with no parent and no branch, just a fresh lonely commit. Check out pachctl start-commit --help for details
