### ISSUE TITLE
Cookbook docs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#353]
This issue is just public notes about various use cases and data structures.

Goals:
- classify representative set of use cases

Thinking about how data comes into pachyderm:

Incremental:
- Time Machine for row-based table data
  - line-based extraction to enable per-line metrics/queries. e.g. Data Dan's use case

- Experiment: each new commit is a new data set for a given experiment.

Cummulative:
- Logs: data appending log lines

Other topics:
DAG Topology
Commits topology --> Genomics?

**Comment by jdoliner** [comment]
Closing this issue since it's just notes and doesn't seem like there's a win condition here.
