### ISSUE TITLE
`pachctl get-logs -v` is confusing

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3534]
`-v` is a global flag to enable verbose client-side log output. It's not obvious that `pachctl get-logs -v` will enable verbose output for client-side logs, but not the server side logs that are being spit out.

**Comment by gabrielgrant** [comment]
do you think this should be changed/removed? i agree this is somewhat confusing, but i also think having it's behavior be inconsistent with the other commands' `-v` seems strange (and afaik we don't actually have  a more verbose version of server-side logs to show)

**Comment by ysimonson** [comment]
I don't have a proposed solution, just noting that this is weird

**Comment by ysimonson** [comment]
Closing. I don't really see a way around this, and it's a fairly small papercut.
