### ISSUE TITLE
Add a flag to put-file to create the repo if it doesn't exist

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3539]
**What is the goal / desired outcome?**

The `put-file` equivalent of `mkdir -p`: create the repo if it doesn't exist before putting data. Makes it easier to script, and (potentially) takes a line out of the beginning of each example

**If there is a way to accomplish this today via workaround, what does that require?**

run `create-repo` before `put-file`

**Comment by jdoliner** [comment]
I think we've gotten most of the value of this by making `update repo` have upsert semantics. So you can reliably script this with:

```
pachctl update repo <repo>
pachctl put file <repo>@master:<file>
```
Saving that line is a minor improvement but having to add a `--create-repo` flag to `put file` (we couldn't do this by default) clutters `put file` which I don't think is worth it. Feel free to reopen if you strongly feel like this would be an improvement, I don't hate it, it just doesn't seem worth it to me.
