### ISSUE TITLE
Expose index to pods

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#354]
When a job with a parallelism of N runs, N pods get started.  We should assign each of these pods a number from 0 to N-1 and expose the number as an environment variable (e.g. `PACH_JOB_INDEX`) to the pod.  This would make it possible for the pods to share work (e.g. scrape only every n-th URL where n is the `PACH_JOB_INDEX`).

**Comment by jdoliner** [comment]
I think we should punt on this until we have indexed jobs in kubernetes. We'll want to use them anyway since it simplifies things a bunch and they make this issue trivial.

Also afaik we haven't had a user request this yet so I think we're ok with it taking a little while.

**Comment by sjezewski** [comment]
Doesn't apply to 1.4 processing model
