### ISSUE TITLE
Option to show full timestamps rather than pretty-printed relative times

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3543]
**What is the goal / desired outcome?**

Compare the exact time that two events happened in the system, when the pretty-printer simplifies both as "3 hours ago"

**If there is a way to accomplish this today via workaround, what does that require?**

use --raw you can get the actual timestamps and do whatever searching/sorting/filtering you want by piping output to `jq`. This is fairly ugly/annoying

**(Optional) What is your proposal for a feature to solve this?**

Command-line flag (`--full-timestamps`?) to show full timestamps

**Comment by kevindelgado** [comment]
@gabrielgrant do we want timestamp displayed as seconds since epoch or as a timestamp string(i.e. `2019-03-04T22:10:12.572638018Z`), or a different flag for both?

**Comment by gabrielgrant** [comment]
@kevindelgado i think ISO datetime strings (the former) are generally a lot more useful. am i understanding correctly that is that what should be coming out of this, right? https://github.com/pachyderm/pachyderm/pull/3547/files#diff-412ea471cf093eeab2b3162c664da90cR183

**Comment by kevindelgado** [comment]
Yes that is correct, figured the ISO string would be better, wasn't sure if there are any use cases where someone explicitly wants seconds from epoch.

**Comment by gabrielgrant** [comment]
I haven't heard any requests for tha. I think if someone really needs epoch time, they can use --raw and convert it themselves with `date` or whatever

**Comment by jdoliner** [comment]
This has been implemented as `--full-timestamps`.
