### ISSUE TITLE
Default custom deployment doesn't work with SwiftStack

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3544]
**What happened?**:

pachd fails to come up with

```
INFO error starting grpc server pfs.NewBlockAPIServer: storage is unable to discern NotExist errors, "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'z1-a'" should count as NotExist
```

**What you expected to happen?**:

pachd comes up fine

**How to reproduce it (as minimally and precisely as possible)?**:

use a custom deployment with SwiftStack, when the region is set to something other than `us-east-1` in SwiftStack

**Anything else we need to know?**:

First, this can be worked around by just setting the region to `us-east-1` in SwiftStack (that's what they have set in all their examples where they talk about S3 compatibility: https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html )

We debugged the specific issue (details below) but need to better understand and document this v2-vs-v4 issue.

It seems the problem stems from there being two different types of S3 API signatures (v2 and v4). The default, v4, seems to hard code the region as `us-east-1`: https://github.com/pachyderm/pachyderm/blob/fcfd38ef20db2402df3c969c0ebd1a82f680c824/src/server/vendor/github.com/minio/minio-go/api-put-bucket.go#L193

(as well as that being the default value in [several other places](https://github.com/pachyderm/pachyderm/blob/fcfd38ef20db2402df3c969c0ebd1a82f680c824/src/server/vendor/github.com/minio/minio-go/api.go#L588))

It seems SwiftStack is expecting this to not be hard coded, so the fix is to use v2-style S3 API signatures. This can be done by passing the `--isS3V2` flag to the `pachctl deploy custom ...` command.

What this changes in the generated manifest is the `minio-signature` field: when set to 0 (base64 encoded as `MA==`) it uses v4-API-style signatures (ie with hard coded region); when set to 1 (base64 encoded as `MQ==`) it uses v2-API-style signatures

more context and debugging info in this slack thread: https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1551488385104800

**Environment?**:

SwiftStack as object store, using a region other than `us-east-1`

**Comment by mindthevirt** [comment]
This is no longer an issue.
