### ISSUE TITLE
`list-file` on a missing repo does not error

### ISSUE THREAD

**Issue by Tryneus** [pachyderm/pachyderm#3548]
**What happened?**:

```
$ pachctl list-repo
NAME                                CREATED      SIZE (MASTER) 
TestSimplePipeline5d17c37492ae      20 hours ago 3B            
TestSimplePipeline_databd927b06f7e5 20 hours ago 3B         
$ pachctl list-file foobar master
$ echo $?
0
```

**What you expected to happen?**:

Print an error that the `foobar` repo doesn't exist and return a non-zero status code.

**How to reproduce it (as minimally and precisely as possible)?**:

100% reproducible on `master` as far as I can tell.

**Anything else we need to know?**:

Nope

**Environment?**:
- Kubernetes version (use `kubectl version`): client: `v1.13.4`, server: `v1.13.0`
- Pachyderm CLI version (use `pachctl version`):
```
COMPONENT           VERSION                                          
pachctl             1.8.5-fcfd38ef20db2402df3c969c0ebd1a82f680c824   
pachd               1.8.5-fcfd38ef20db2402df3c969c0ebd1a82f680c824   
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2
- Others: Nope

**Comment by mdaniel** [comment]
Isn't this a dupe of #3083?

**Comment by Tryneus** [comment]
Yep, I'll close in favor of that (and set the milestone) - thanks!
