### ISSUE TITLE
Putting the same file concurrently results in fuse errors

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#355]
I have a pipeline with parallelism N > 1.  If this pipeline is run, and each of the pods try to write to the same file, only one pod succeeds.  The other pods get an `I/O error`.

Here is my conjecture: since `PutFile` acquires a global lock, only one `PutFile` can proceed at a node at any point in time.  So only one pod gets to write the file, while the other pods are waiting for the lock.  However, the fuse driver is not handling the waiting correctly, resulting in an I/O error.

**Comment by derekchiang** [comment]
@jdoliner @sjezewski do you guys have any immediate thoughts on this before I dive into it?  You guys know more about the fuse driver than I do.

**Comment by jdoliner** [comment]
Eh, I don't think just the delay on a `PutFile` would result in an error, but perhaps.
Feel free to dive in I don't have an immediate thought.
Also is the code for the test committed somewhere? I'd like to have a look.

**Comment by derekchiang** [comment]
@jdoliner https://github.com/pachyderm/pachyderm/blob/9a568816576612475621cfed986b8d98f707ca4e/src/server/pachyderm_test.go#L366-L411

It hangs on `ListCommit` because `ListCommit` does not return cancelled commits by default.  The reason the commit was cancelled was that two of the three parallel pods failed, which I found out by looking into server logs.

**Comment by derekchiang** [comment]
Rather curiously, if I use `dd` instead of `echo >` in the test, the test passes: https://github.com/pachyderm/pachyderm/blob/fix-355/src/server/pachyderm_test.go#L494

So it seems like `echo >` interacts with the file system in a way that's not correctly handled by our driver?

**Comment by jdoliner** [comment]
`echo >` does a truncate before it writes to the file which might account for the difference. I wasn't aware we were handling it differently though.

**Comment by derekchiang** [comment]
Actually I was using `>>` instead of `>`.  In either case the test fails.

**Comment by derekchiang** [comment]
A new development on this.  So I found out that, in the [echo test](https://github.com/pachyderm/pachyderm/blob/df7ea5b47ffd756ef6f014848d3532ce340dd6b2/src/server/pachyderm_test.go#L534-L580), 2 of the 3 `PutFile`s returned prematurely.  Specifically, they returned [here](https://github.com/pachyderm/pachyderm/blob/df7ea5b47ffd756ef6f014848d3532ce340dd6b2/src/server/pfs/server/api_server.go#L406), meaning that 2 of the 3 `PutFile`s somehow got `EOF` from FUSE, instead of the actual bytes `foo`.

This is very bizarre.

**Comment by derekchiang** [comment]
I think I've identified the issue.

`>>` means append, which means that the file system will try to write the data at an offset that is the current length of the file.

Which means that [this check](https://github.com/pachyderm/pachyderm/blob/9a568816576612475621cfed986b8d98f707ca4e/src/server/pfs/fuse/filesystem.go#L287-L294) will fail if you are doing `echo foo >> file` and there is already some data in `file`, since `h.written` will be zero and `request.Offset` will be greater than zero.

**Comment by derekchiang** [comment]
And I was wrong earlier in that using `>` instead of `>>` does make the test pass, which makes sense since `>` will result in the file being written at an offset of zero.

**Comment by derekchiang** [comment]
This will be fixed along with #303
