### ISSUE TITLE
RBAC role command in GKE doc errors out

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3550]
**What happened?**:

I ran the command in the bottom of the doc

http://docs.pachyderm.io/en/latest/deployment/rbac.html

as specified:

```
kubectl create clusterrolebinding cluster-admin-binding \ --clusterrole cluster-admin --user $(gcloud config get-value account)
```

and I got the error

```
error: exactly one NAME is required, got 3
See 'kubectl create clusterrolebinding -h' for help and examples.
```

**What you expected to happen?**:
I expected it to work :-)

**How to reproduce it (as minimally and precisely as possible)?**:

See above.

**Anything else we need to know?**:

I believe I fixed it in this command, but want to make sure I'm not on drugs,so opening an issue.

```
kubectl create clusterrolebinding cluster-admin-binding  --clusterrole=cluster-admin --user=$(gcloud config get-value account)
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
GKE 

Google Cloud SDK 237.0.0
bq 2.0.42
core 2019.03.01
gsutil 4.37

- OS (e.g. from /etc/os-release): macOS 10.14.3 (18D109)
- Others:

**Comment by msteffen** [comment]
The new command seems to work (@kevindelgado and I just tried it after running into the same issue you did). Updated the docs in https://github.com/pachyderm/pachyderm/commit/1b9a623d122a98ad43c4472b3da0cb31414ee44d#diff-b981c927fa5cbfdc99942ad4535e44a4

I'm marking this fixed, but please feel free to re-open if it's not
