### ISSUE TITLE
Documentation Bug: Backup/Restore instructions use aliases for kubectl and pachctl

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3551]
**What happened?**:
Backup and restore documentation use pc and kc aliases for kubectl and pachctl and this is not explained well in the documentation.

**What you expected to happen?**:
no customer aliases should be used in examples without defining the aliases.

**How to reproduce it (as minimally and precisely as possible)?**:
N/A
**Anything else we need to know?**:
No.
http://docs.pachyderm.io/en/latest/managing_pachyderm/backup_restore_and_migrate.html

## kubectl alias used
```
# Modify the service to accept traffic on port 30650, again
$ kubectl get svc/pachd -o json | sed 's/30649/30650/g' | kc apply -f -
```
## pachctl alias used
```
# Make sure you can talk to pachd (if not, firewall rules are a common culprit)
$ pc version
```

**Comment by JoeyZwicker** [comment]
Thanks @brokenjacobs. That's a silly oversight on our part. @pappasilenus, please make these fixes and do a search elsewhere in our docs to make sure we don't have similar errors
