### ISSUE TITLE
Add note about EC2 instance limits to  tutorial [DOCS]

### ISSUE THREAD

**Issue by rschoenbeck** [pachyderm/pachyderm#3552]
Tutorial for manual AWS deployment here: http://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html

Mentions that `r4.xlarge` instances should be used, but the default instance limit for at least some regions (e.g. us-west-2) for that type is currently 1, meaning you can't actually create a pachyderm cluster with that configuration (and kops also won't tell you why the nodes aren't created).

So it'd be good to add a note for users to check their EC2 instance limit and suggest viable alternatives.

**Comment by JoeyZwicker** [comment]
Thanks for pointing this out @rschoenbeck. Adding docs label and we can make these adjustments. Always open to PRs for little stuff like this as well :)

**Comment by mindthevirt** [comment]
Given that AWS limitations per region are constantly updated by AWS, it is probably best to double-check that those limits are not exceeded within your AWS Console. Closing this issue out as there's nothing to be done here.
