### ISSUE TITLE
Pachyderm provenance should include user information

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3556]
**What is the goal / desired outcome?**
To be able to easily tell what was created by whom. 

As it stands right now, there doesn't seem to be any user information included in any of the pachyderm properties. This can be a problem for more complex pipelines where there are multiple owners. 

examples:
```
$ pachctl list-repo
NAME   CREATED        SIZE     **CREATED BY**        ACCESS LEVEL
edges  19 minutes ago 22.22KiB  **Nick**  OWNER
images 26 minutes ago 57.27KiB **Nick**  OWNER
```

```
$ pachctl list-job
ID                               PIPELINE     **OWNER**      STARTED        DURATION RESTART PROGRESS  DL       UL       STATE
41b81ad96ad44619b84bee69b0276afc edges  **Nick**   20 minutes ago 1 second 0       1 + 0 / 1 57.27KiB 22.22KiB success
```
etc. 

**If there is a way to accomplish this today via workaround, what does that require?**
Not to my knowledge

**(Optional) What is your proposal for a feature to solve this?**
Have user and owner information added to advanced statistics or at least default enterprise 

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI version (use `pachctl version`): 1.8.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by Nick-Harvey** [comment]
This should be included for the Pachyderm Enterprise roadmap

**Comment by gabrielgrant** [comment]
This sounds like it is one part of #2468 (and #3069, which is basically the same thing)

**Comment by jdoliner** [comment]
Closing this in favor of #3069 since that's more fleshed out.
