### ISSUE TITLE
Reference specific versions of `pachyderm/pachd` in our manifest files

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#356]
I wasn't experiencing this behavior after I pulled yesterday morning but when I pulled this morning and tried to launch a cluster all pachd nodes enter a crash loop immediately.

```
pachyderm# kubectl get all                                                    
NAME                   DESIRED      CURRENT            AGE                                                           
etcd                   1            1                  24m                                                           
pachd                  2            2                  24m                                                           
rethink                1            1                  24m                                                           
NAME                   CLUSTER-IP   EXTERNAL-IP        PORT(S)                        AGE                            
etcd                   10.0.0.158   <none>             2379/TCP,2380/TCP              24m                            
kubernetes             10.0.0.1     <none>             443/TCP                        6d                             
pachd                  10.0.0.143   nodes              650/TCP,750/TCP                24m
rethink                10.0.0.18    <none>             8080/TCP,28015/TCP,29015/TCP   24m
NAME                   READY        STATUS             RESTARTS                       AGE
etcd-ccyyq             1/1          Running            0                              24m
k8s-etcd-127.0.0.1     1/1          Running            0                              6d
k8s-master-127.0.0.1   4/4          Running            1                              6d
k8s-proxy-127.0.0.1    1/1          Running            0                              6d
pachd-dw4u5            0/1          CrashLoopBackOff   4                              24m
pachd-init-3n9j5       0/1          CrashLoopBackOff   4                              24m
pachd-jreqx            0/1          CrashLoopBackOff   4                              24m
rethink-ktrre          1/1          Running            0                              24m
```

**Comment by jdoliner** [comment]
Hi @erikreppel really sorry you ran into this. I think I know what's going on here.
I updated our manifest last night in such a way that old versions of the `pachyderm/pachd` image will crash. By default right now if the `pachyderm/pachd` image already exists in docker then a new version won't be pulled. Is this on a k8s instance that already had had Pachyderm running on it?

I think it's probably time that we start shipping manifests that reference versioned copies of our container image. @sjezewski what are your thoughts?

In the meantime @erikreppel I think you could side step this by grabbing a copy of the manifest and manually changing the `PullPolicy` field for `pachyderm/pachd` to `"Always"` instead of `"IfNotPresent"`. Note you'll have to do it in 2 places, one for the pachd and one for the pachd init.

**Comment by erikreppel** [comment]
Hey @jdoliner,
yes it was an instance of k8s that had Pachyderm running on it before.

I restarted kubernetes and ran the tests (which failed), then tried again to launch a dev cluster, but after a minute or so in a crash loop it now seems to be stable. I'll try changing the pull policy if I run into this again, but for now it seems to be working (I think you guys build the docker images in the `make test` script somewhere right? Could be what fixed it)

**Comment by erikreppel** [comment]
That being said tests in `make test` still fail

**Comment by jdoliner** [comment]
`make test` does build the image so that should fix it as well. What are you test failures you're seeing?

**Comment by erikreppel** [comment]
```
eplicationcontroller "pachd" created
# wait for the pachyderm to come up
# if we can call the list repo, that means that the cluster is ready to serve
until timeout 5s /home/erik/dev/go/bin/pachctl list-repo 2>/dev/null >/dev/null; do sleep 5; done
CGOENABLED=0 go test ./src/server -timeout 300s
--- FAIL: TestLogs (24.11s)
        require.go:121: /home/erik/dev/go/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:181
        require.go:123: No error is expected but got rpc error: code = 2 desc = container "user" in pod "fe4d3ad1635140d092004c84a9a5153f-55z8h" is waiting to start: ContainerCreating
--- FAIL: TestGrep (31.00s)
        require.go:121: /home/erik/dev/go/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:233
        require.go:123: No error is expected but got rpc error: code = 4 desc = context deadline exceeded
--- FAIL: TestJob (31.21s)
        require.go:121: /home/erik/dev/go/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:78
        require.go:123: No error is expected but got rpc error: code = 4 desc = context deadline exceeded
FAIL
FAIL    github.com/pachyderm/pachyderm/src/server       32.912s
make: *** [integration-tests] Error 1
```
Was the output

**Comment by derekchiang** [comment]
Ah, we've seen these before.  These are not real test failures.  Since we run tests in parallel, sometimes you get these failures due to kubernetes being slow.  These failures go away if you run the tests sequentially or run them on a beefy machine.

**Comment by erikreppel** [comment]
Ahh gotchya, thanks for the help!

**Comment by jdoliner** [comment]
Yeah, we've been plagued by this a bit. Every once in a while kubernetes seems to get incredibly slow on us and just takes forever to schedule pods causing tests to time out. We've found that restarting kubernetes tends to help but other than that we haven't been able to do much once this starts happening.

**Comment by jdoliner** [comment]
I'm actually going to repurpose this issue as the issue for referencing versioned containers in the manifests.

**Comment by sjezewski** [comment]
I like this plan. Additionally, when we start including versions in the manifest, I'll update the release instructions for pachd to include updating the manifest

**Comment by dwhitena** [comment]
Having the same issue here:

```
NAME                   DESIRED      CURRENT            AGE
etcd                   1            1                  21h
pachd                  2            2                  21h
rethink                1            1                  21h
NAME                   CLUSTER-IP   EXTERNAL-IP        PORT(S)                        AGE
etcd                   10.0.0.202   <none>             2379/TCP,2380/TCP              21h
kubernetes             10.0.0.1     <none>             443/TCP                        1d
pachd                  10.0.0.53    nodes              650/TCP,750/TCP                21h
rethink                10.0.0.47    <none>             8080/TCP,28015/TCP,29015/TCP   21h
NAME                   READY        STATUS             RESTARTS                       AGE
etcd-w1qmp             1/1          Running            0                              21h
k8s-etcd-127.0.0.1     1/1          Running            0                              1d
k8s-master-127.0.0.1   4/4          Running            4                              1d
k8s-proxy-127.0.0.1    1/1          Running            0                              1d
pachd-2yjyp            0/1          CrashLoopBackOff   14                             21h
pachd-m6sfg            0/1          CrashLoopBackOff   14                             21h
rethink-5a0uf          1/1          Running            0                              21h```

Where do I put the modified manifest file you mention above?  Where is the one it is currently using?

Thanks.

**Comment by erikreppel** [comment]
@dwhitena run `make docker-build` to re build the pachd to the latest version, that got it working again for me

**Comment by jdoliner** [comment]
Hi @dwhitena really sorry this is affecting you. @erikreppel's solution is probably the easiest one.

Make launch looks for the manifest at `etc/kube/pachyderm.json`. Here's the [modified manifest](https://github.com/pachyderm/pachyderm/files/238994/pachyderm.txt).

One thing I'm noticing about your situation though is that you don't seem to have an init container that's crashing, just the pachd containers, I'm still hopefully that those solutions will work but if they don't the first step is probably checking the logs from one of those pachd pods.

**Comment by sjezewski** [comment]
Yup that should work. We're also going to make detecting/reporting this a lot clearer to the user -- see issue #358

**Comment by sjezewski** [comment]
Also related to #390

**Comment by pratheekrebala** [comment]
I was also facing the "crash loop" error with the latest build -- replacing the original manifest file with the one provided above did the trick for me!

**Comment by sjezewski** [comment]
Fixed in https://github.com/pachyderm/pachyderm/pull/510
