### ISSUE TITLE
pachd emits entirely too many WhoAmI log messages

### ISSUE THREAD

**Issue by mdaniel** [pachyderm/pachyderm#3564]
**What happened?**:

```console
$ kubectl logs -l app=pachd | grep "2019-03-09T00:07:41Z INFO authclient.API.WhoAmI" | wc -l
54
```

**What you expected to happen?**:

```
$ kubectl logs -l app=pachd | grep "2019-03-09T00:07:41Z INFO authclient.API.WhoAmI" | wc -l
1
```

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.8.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
Pachd emits logs each time the `WhoAmI` request is received, which happens a lot, that's necessary to validate requests aren't doing things they shouldn't be. I don't really so any reason that the expectation should be that this endpoint is only called once, pachd isn't checking who it is with this request, it's checking who the caller of the request is, so it needs to be done for every request.

**Comment by jdoliner** [comment]
I will add that we're working on the efficiency of `WhoAmI` calls so this doesn't become a bottleneck, but we'll still probably be making a lot of them, because of the nature of authentication it's important to recheck it frequently because using stale information can lead to some pretty disastrous consequences.

**Comment by mdaniel** [comment]
ok, well, are those actually `INFO` messages? Given that they appear to have no arguments nor any `"duration"` in any of the replies -- so are they informative, or just chatty?
