### ISSUE TITLE
Improve pod_spec and pod_patch documentation; include specific usage examples

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3567]
There are some gotchas in using `pod_spec` and `pod_patch` (discussed in #3319; added in #3427) that should be clarified, and having specific examples of the most common use cases (which seems to mostly be adding volumes) would be helpful. 

In particular, the most obvious way of adding a volume (using an `add` operation with an array of `volumes` at that location) doesn't actually work, unless you know pachyderm already uses some  volumes and append to the list instead of adding it. More details here: https://github.com/pachyderm/pachyderm/issues/3319#issuecomment-471478256

[Specific example of the problem from #users:](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1552117931505200)

Matt Goldberg

> I have another question about using pod_patch. After I run create-pipeline, my pipeline is not being created and I see errors in the pachd logs.
> This is the pod_patch I’m trying to apply:
> ```
> [
>   {
>     "op": "add",
>     "path": "/volumes",
>     "value": [
>       {
>         "name": "config",
>         "emptyDir": {}
>       }
>     ]
>   },
>   {
>     "op": "add",
>     "path": "/affinity",
>     "value": {
>       "nodeAffinity": {
>         "requiredDuringSchedulingIgnoredDuringExecution": {
>           "nodeSelectorTerms": [
>             {
>               "matchExpressions": [
>                 {
>                   "key": "kops.k8s.io/instancegroup",
>                   "operator": "In",
>                   "values": [
>                     "nodes"
>                   ]
>                 }
>               ]
>             }
>           ]
>         }
>       }
>     }
>   },
>   {
>     "op": "add",
>     "path": "/dnsConfig",
>     "value": {
>       "options": [
>         {
>           "name": "ndots",
>           "value": "2"
>         }
>       ]
>     }
>   }
> ]
> ```
> These are the logs I’m seeing in pachd:
> ```
> 2019-03-09T07:51:48Z INFO moving pipeline test-secrets to PIPELINE_STARTING
> 2019-03-09T07:51:48Z ERROR master: error running the master process: ReplicationController "pipeline-test-secrets-v1" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "pachyderm-worker", spec.template.spec.containers[0].volumeMounts[2].name: Not found: "pachyderm-storage-secret", spec.template.spec.containers[0].volumeMounts[3].name: Not found: "docker", spec.template.spec.containers[1].volumeMounts[0].name: Not found: "pach-dir-volume", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "pachyderm-storage-secret", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: "pachyderm-worker"]; retrying in 20.004449691s
> 2019-03-09T07:51:52Z INFO Launching PPS master process
> 2019-03-09T07:51:52Z INFO pfs.API.GetFile {"request":{"file":{"commit":{"repo":{"name":"__spec__"},"id":"655e62c792ec408bbd5e4375e3a5fc3a"},"path":"spec"}}} []
> 2019-03-09T07:51:52Z INFO authclient.API.WhoAmI {"request":{}} []
> 2019-03-09T07:51:52Z INFO authclient.API.WhoAmI {"request":{}} []
> 2019-03-09T07:51:52Z INFO authclient.API.WhoAmI {"request":{}} []
> 2019-03-09T07:51:52Z INFO pfs.BlockAPI.Obj.GetObjects {"request":{"objects":[{"hash":"84e57bf24a8d24b81d2dced5a9c9a33604288718b9440ed61cee82345d55d5504672eeebac565ae37e4826d9650cf7bcfd8c728f3cde328de22b4d35c5fd53db"}],"total_size":743}} []
> 2019-03-09T07:51:52Z INFO pfs.BlockAPI.Obj.InspectObject {"request":{"hash":"84e57bf24a8d24b81d2dced5a9c9a33604288718b9440ed61cee82345d55d5504672eeebac565ae37e4826d9650cf7bcfd8c728f3cde328de22b4d35c5fd53db"}} []
> 2019-03-09T07:51:52Z INFO pfs.BlockAPI.Obj.InspectObject {"duration":0.000018182,"request":{"hash":"84e57bf24a8d24b81d2dced5a9c9a33604288718b9440ed61cee82345d55d5504672eeebac565ae37e4826d9650cf7bcfd8c728f3cde328de22b4d35c5fd53db"},"response":{"object":{"hash":"84e57bf24a8d24b81d2dced5a9c9a33604288718b9440ed61cee82345d55d5504672eeebac565ae37e4826d9650cf7bcfd8c728f3cde328de22b4d35c5fd53db"},"block_ref":{"block":{"hash":"6d0ddfb72c45410b8ceecb3b07b6b41e"},"range":{"upper":743}}}} []
> 2019-03-09T07:51:52Z INFO pfs.BlockAPI.Obj.GetObjects {"duration":0.000462571,"request":{"objects":[{"hash":"84e57bf24a8d24b81d2dced5a9c9a33604288718b9440ed61cee82345d55d5504672eeebac565ae37e4826d9650cf7bcfd8c728f3cde328de22b4d35c5fd53db"}],"total_size":743}} []
> 2019-03-09T07:51:52Z INFO pfs.API.GetFile {"duration":0.00602323,"request":{"file":{"commit":{"repo":{"name":"__spec__"},"id":"655e62c792ec408bbd5e4375e3a5fc3a"},"path":"spec"}}} []
> 2019-03-09T07:51:52Z INFO PPS master: creating/updating workers for pipeline test-secrets
> 2019-03-09T07:51:52Z INFO enterprise.API.GetState {"request":{}} []
> 2019-03-09T07:51:52Z INFO enterprise.API.GetState {"duration":0.000002547,"request":{},"response":{}} []
> 2019-03-09T07:51:52Z ERROR error creating workers for pipeline test-secrets: ReplicationController "pipeline-test-secrets-v1" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "pachyderm-worker", spec.template.spec.containers[0].volumeMounts[2].name: Not found: "pachyderm-storage-secret", spec.template.spec.containers[0].volumeMounts[3].name: Not found: "docker", spec.template.spec.containers[1].volumeMounts[0].name: Not found: "pach-dir-volume", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "pachyderm-storage-secret", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: "pachyderm-worker"]; retrying in 623.768688ms
> 2019-03-09T07:51:52Z INFO enterprise.API.GetState {"request":{}} []
> 2019-03-09T07:51:52Z INFO enterprise.API.GetState {"duration":0.000002166,"request":{},"response":{}} []
> 2019-03-09T07:51:52Z ERROR error creating workers for pipeline test-secrets: ReplicationController "pipeline-test-secrets-v1" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "pachyderm-worker", spec.template.spec.containers[0].volumeMounts[2].name: Not found: "pachyderm-storage-secret", spec.template.spec.containers[0].volumeMounts[3].name: Not found: "docker", spec.template.spec.containers[1].volumeMounts[0].name: Not found: "pach-dir-volume", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "pachyderm-storage-secret", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: "pachyderm-worker"]; retrying in 404.080357ms
> 2019-03-09T07:51:53Z INFO enterprise.API.GetState {"request":{}} []
> 2019-03-09T07:51:53Z INFO enterprise.API.GetState {"duration":0.000002691,"request":{},"response":{}} []
> 2019-03-09T07:51:53Z INFO moving pipeline test-secrets to PIPELINE_STARTING
> 2019-03-09T07:51:53Z ERROR master: error running the master process: ReplicationController "pipeline-test-secrets-v1" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "pachyderm-worker", spec.template.spec.containers[0].volumeMounts[2].name: Not found: "pachyderm-storage-secret", spec.template.spec.containers[0].volumeMounts[3].name: Not found: "docker", spec.template.spec.containers[1].volumeMounts[0].name: Not found: "pach-dir-volume", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "pachyderm-storage-secret", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "pach-bin", spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: "pachyderm-worker"]; retrying in 8.617200437s
> ```

Gabriel Grant

> @goldberg i believe the problem you're running into is that pachyderm already uses several volumes internally, but your patch is replacing the list of volumes with the one you've defined. instead you'll need to append to that list, so your patch's `path` should be `"/volumes/-"` instead of `"/volumes"`

see full thread: https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1552117931505200

**Comment by pappasilenus** [comment]
More issues around adding k8s directives via 'pod_spec' & `pod_patch`.  https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1558352661036200

```json
{
  "pipeline": {
    "name": "mypipeline"
  },
  "transform": {
    "cmd": [
      "R",
      "-e yyy::generate_data()"
    ],
    "image": "xxx/yyy:v0.1.6-pachyderm"
  },
  "pod_spec": "{\n\t\"containers\": [\n\t\t{\n\t\t\t\"env\": [\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"S3_SECRET\", \n\t\t\t\t\t\"valueFrom\": {\n\t\t\t\t\t\t\"secretKeyRef\": {\n\t\t\t\t\t\t\t\"name\": \"xxx-basics\", \n\t\t\t\t\t\t\t\"key\": \"API_SECRET\"\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}, \n\t\t\t\t{\n\t\t\t\t\t\"name\": \"APP_DEBUG\", \n\t\t\t\t\t\"valueFrom\": {\n\t\t\t\t\t\t\"configMapKeyRef\": {\n\t\t\t\t\t\t\t\"name\": \"xxx-basics\", \n\t\t\t\t\t\t\t\"key\": \"APP_DEBUG\"\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]\n}",
  "input": {
    "pfs": {
      "repo": "images",
      "glob": "/*"
    }
  }
}
```

**Comment by JoeyZwicker** [comment]
When we move to CRDs, pod spec/patch go away. Depending on the estimates delivery date of CRD pipelines by @msteffen (which seems like it's not in the super near future), it may or may not makes sense to even bother with this. Marking at low priority
