### ISSUE TITLE
File Splitting doc should explain how it works with subsequent commits/--overwrite

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3569]
[The file splitting doc](http://docs.pachyderm.io/en/latest/cookbook/splitting.html) doesn't seem to mention how `--split` interacts with `--overwrite`/subsequent commits

I _think_ subsequent calls to `put-file --split` should delete and re-create the split dir with files counting from zero if `--overwrite` is passed.  if `--overwrite` is not passed, i think it should add files to the existing split dir, and start naming files from the largest line-numbered file that already exists. Haven't actually tested this behavior yet, though

**Comment by JoeyZwicker** [comment]
@pappasilenus @svekars Doesn't this doc already cover this and isn't the behavior @gabrielgrant os describing how split with and without overwrite works?

Is this closeable?

**Comment by mindthevirt** [comment]
This has been addressed and is available in our documentation.
