### ISSUE TITLE
InspectFile from the client API causes pachd to crash and blocks /pfs

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#357]
[Code](https://gist.github.com/erikreppel/e38b4596b50c260930ca2a864e81d468)

I was playing with the client API and found that InspectFile was causing pachd to crash if a the file it was looking for was present. If the file doesn't exist it doesn't have a problem. It also causes /pfs to become unavailable:

```
# umount /pfs
umount: /pfs: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
```

`pachctl inspect-file` works so I modified my code to work exactly like the pachctl command for pfs (the code I link to above) but that still causes the same issue.

**Comment by jdoliner** [comment]
Hi Erik,
Really sorry you ran into this, we'll look into it ASAP.
Thanks so much for providing the code that'll make things much easier on our end.

**Comment by jdoliner** [comment]
Oh hmm, I think I have an idea what's going wrong here, this is going to send a `FilterShard` with `0` for `BlockModulus` and `FileModulus`. I bet that's leading to a panic somewhere. Will investigate.

**Comment by erikreppel** [comment]
Yeah I'm more surprised that my code wasn't working be `pachctl inspect-file` works. `pachctl` seems to also pass `FilterShard` with `0` for everything too: https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/cmds/cmds.go

**Comment by jdoliner** [comment]
Those calls to `IntVarP` are actually setting default values of `1` for both `FileModulus` and `BlockModulus`.

Still this certainly shouldn't be crashing our server.

**Comment by jdoliner** [comment]
Also I may have misheld the most important piece of info here. If what you're trying to do is just return everything you can just pass `nil` for `Shard`. I'm going to make sure we document this as part of this issue.

**Comment by erikreppel** [comment]
good to know!

**Comment by erikreppel** [comment]
So I'm finding if I specify the shard as `nil` it works fine
