### ISSUE TITLE
include branch name in pachctl list-/flush-commit

### ISSUE THREAD

**Issue by David-Development** [pachyderm/pachyderm#3571]
**What is the goal / desired outcome?**
Include the branch name in the `list-commit` and `flush-commit` output (by default). It's confusing if you use `flush-commit` and two output commit are made to the same repo (when stats are enabled). If the branch name would be visible, it would be much clearer which commit is for data and which one is for statistics.

**If there is a way to accomplish this today via workaround, what does that require?**
No

**Comment by JoeyZwicker** [comment]
You can pass an optional branch argument flag to `list-commit` to filter only by branch. e.g. `pachctl list-commit edges master` will only return commits on the master branch and not the stats branch. 

It doesn't look like flush-commit offers similar options including a branch field could still be useful
