### ISSUE TITLE
Change all instances "commit-id" to "commit-id-or-branch" (or something) in CLI help

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3582]
In general, any place that asks for a commit id will accept a branch name, since branches are technically just pointers to the head commit of what are usually colloquial referred to as "the branch" (ie the series of commits). For those of us who understand this technical detail, the use of branch names in lieu of commit IDs makes a lot of sense, but for people who aren't as intimately familiar with the implementation, it's not obvious.

Right now we generally just ask for a commit id. eg:
```
Usage:
  pachctl glob-file repo-name commit-id pattern [flags]
```
This should be updated to make it clear that branch names can be accepted too

**Comment by mindthevirt** [comment]
This is related to #3575

**Comment by nadegepepin** [comment]
No more relevant - The `pachctl glob file` now mentions both in the `--help`: `pachctl glob file <repo>@<branch-or-commit>:<pattern> [flags]`
