### ISSUE TITLE
`ListFileHistory` can deadlock

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3608]
Concurrently writing to a file and calling `ListFileHistory` on it can get into a deadlocked state. Here is a minimal, reproducible test: https://github.com/pachyderm/pachyderm/compare/list-file-history-test

Observed on k8s on docker for mac.

**Comment by ysimonson** [comment]
^ I have committed the cardinal sin of mixing tabs and spaces in that branch, sorry

**Comment by ysimonson** [comment]
This appears to have been fixed in the mean-time. I'll open a PR with the regression test.

**Comment by ysimonson** [comment]
I spoke too soon. It passed the first few times, but is now failing again.

**Comment by ysimonson** [comment]
I'm still seeing the issue - deadlocks occur when calling `View` on `*bolt.DB`.

**Comment by ysimonson** [comment]
Holding on continued investigation of this. Our intention is to no longer use BoltDB for filesets, which would obviate the need for a fix.

**Comment by ysimonson** [comment]
@Tryneus not sure if I heard right, but did @brycemcanally mention that you fixed this already?

**Comment by Tryneus** [comment]
Could not reproduce this error with the given test, so I think it is safe to assume the problem has been fixed.  Ported the test forward to our current PFS unit tests and merged it in #5045.
