### ISSUE TITLE
pachctl list-job shows start times 6 hours in the past

### ISSUE THREAD

**Issue by ccotar** [pachyderm/pachyderm#3609]
**What happened?**:
Summary: `pachctl list-job` shows jobs starting 6 hours ago even though they just ran a second ago.

I’ve been running through examples locally with minikube on mac os x and when I commit a file to the repo the `list-job` command shows that job starting 6 hours ago even though I just started the job.

**What you expected to happen?**:
`pachctl list-job` to show correct start time for jobs

**How to reproduce it (as minimally and precisely as possible)?**:
I don't have a bare bones repro of this issue, hoping for a quick tip to set up clock timezone or some other simple solution.

**Anything else we need to know?**:
Example run locally was the beginner tutorial first pipeline to generate images with edges using opencv.

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Pachyderm CLI version (use `pachctl version`):
pachctl             1.8.6
pachd               1.8.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube
- OS (e.g. from /etc/os-release):
Mac OS X Mojave
10.14.2
- Others:

**Comment by JoeyZwicker** [comment]
Hi @ccotar. I've tested things locally on Mac with all the same versions as you and am not able to repro the behavior you're seeing. 

That said, I think I've seen something similar to this in the past, but was never able to repro successfully -- I didn't spend much time on it. My theory was it had something to do with minikube getting out of sync when I put my laptop to sleep, but again, never tested this extensively. If you're able to figure out more concrete repro steps, we'd be happy to take another look at this.

**Comment by ccotar** [comment]
Thanks for trying to repro, I will try restarting minikube since I let my laptop sleep with it on a lot and see if that fixes the timing issue

**Comment by ccotar** [comment]
Restart of Minikube worked as well as using the docker for mac k8s.
