### ISSUE TITLE
Better documentation of dashboard ingress

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3610]
Along with improving docs about cluster API ingress (#3466), we should also improve docs about how to set up ingress to the dash. 

The dash requires two ports to be open:
1. An HTTP port used to serve static assets (HTML, CSS, JS, images, etc; port 30080 by default routes to the `dash` container within the `dash` pod)
2. A WebSocket port, used to connect to the GRPC proxy (which in turn connects to pachd; port 30081 by default routes to the `grpc-proxy` container within the `dash` pod)

In order to make these accessible, they are usually exposed on localhost by running `pachctl port-forward` (the call needs to be explicit, since implicit port-forwarding doesn't really make sense in the context of web requests). The dash can also be accessed by directly connecting to the K8S host (similar to using the `PACHD_ADDRESS` env var for `pachctl`), or be exposed on a public-facing domain (though we've had a number of issues with that in the past). Additionally, the websocket connection can be divorced from the HTTP connection (ie it's defaults can be changed) by specifying query params (more details about how to specify a custom websocket endpoint: https://github.com/pachyderm/pachyderm/issues/3232#issuecomment-477262482)

That's a start, but I'm sure we've written a ton more info about this in various places. Lets use this issue as a place to collect that relevant info

**Comment by gabrielgrant** [comment]
Some more notes about the various pieces required for a comprehensive, production-grade deploy are here: #3171

**Comment by gabrielgrant** [comment]
expanding a bit more on why this is tricky: right now the pach security model basically assumes that anyone with "physical" (ie network-level) access to the cluster is supposed to have access to it in some capacity (ie they are allowed to ingest their own data, run code, etc.). what the auth system is focused on primarily is protecting specific data from being seen by people (within the company) who aren't authorized to see it.

this is why recommending port-forward is such an easy option: it allows us to rely on k8s' security setup. it means that only people who have been granted access to the k8s cluster can access pach at all, which (pretty safely) assumes that anyone who has been granted access to that k8s cluster inherently has some level of trust already.

so at the moment, if you want to securely expose a publicly-hosted pach instance without relying on k8s to protect the connection, you really should set up some other form network-level access control system (like a VPN or SSH tunnel), which is inherently tricky, extremely infra-specific, way outside the realm of our expertise, and quite possibly just as flaky as port-forward. which is why, to date, we've just recommended port-forward

this means that anyone who finds an unsecured pach cluster's IP address is able to log in. because of this, we're in the process to be making some improvements to the pach auth system to lock down access, so that it's possible to securely expose a pach instance, but for user to even make use of that will require that they either exclusively use robot accounts or that they set up SAML auth, which, AFAIK, only one customer is actually using

all that to say: this is complicated, and i still don't have a great answer, and it would be really nice if kubectl port-forward would just work :P

**Comment by svekars** [comment]
How to do it if you are still evaluating?
How do you do it in production?

Dashboard access 
S3 gateway
Pachctl access
Language clients

On-Prem
AWS
Azure
GKE 

with DNS
with Authentication
with SSL
