### ISSUE TITLE
Header/Footer docs are wrong

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3613]
`Pachctl put-header` and `put-footer` seem to have been deprecated and moved into --split, which means this doc is completely wrong: http://docs.pachyderm.io/en/latest/cookbook/splitting.html#specifying-header-footer

The --help for --split is incomplete:

- it does not mention the `csv` or `sql` arguments that can be passed to --split
- It's unclear if only header is supported or is footers are still supported too

**Comment by gabrielgrant** [comment]
AFAIK the header functionality for CSVs does not exist in `--split`, just for SQL (hence #3000). So i think this needs to be re-instated on the eng side, rather than removing it on the docs side

**Comment by svekars** [comment]
We have updated the Splitting Data for Distributed Processing doc: http://docs.pachyderm.io/en/latest/cookbook/splitting.html#specifying-a-header. Is there anything else left to cover as part of this issue?

**Comment by JoeyZwicker** [comment]
I think its good. the csv functionality seems to work.
