### ISSUE TITLE
Join inputs

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3623]
**What is the goal / desired outcome?**

Be able to join files across repos.

**If there is a way to accomplish this today via workaround, what does that require?**

The standard way to do this in Pachyderm right now is with a shuffle pipeline. This works, but it's a bit awkward, and leads to having a lot of pipelines that just symlink around files.

**(Optional) What is your proposal for a feature to solve this?**

#### Join Inputs

Add a new kind of input, `join`, that joins multiple inputs together based on their names, for example:

| inputA | inputB | inputA ⨝ inputB |
| ------ | ------ | --------------- |
| foo    | foo    | (foo, foo)      |
| bar    | bar    | (bar, bar)      |
| fizz   | buzz   |                 |

Note that in this example `fizz` and `buzz` don't match anything, and thus neither appears in the resulting join, in SQL terms this is an [equi join](https://en.wikipedia.org/wiki/Join_(SQL)#Equi-join) on the filenames. We can discuss whether or not we want to support more complicated forms of joins, my sense is that we should just stick to the simplest thing for now and see if there's need for something more complicated. Because pachyderm has a much simpler data model than SQL, I suspect more complicated joins won't be useful in our system.

#### Glob Replacement

Join inputs as described above would only be useful if you committed your files with the right names so they would get joined together. This would be very limiting, especially if you wanted to do multiple joins for different pipelines that include the same pipeline. Glob replacement would allow you to rename a file, it's similar to regex replacement, but using globs instead. For example, suppose I had a repo with sensor readings with paths of the form `<location>/<instrument_id>/<time>` and a number of calibrations with paths of the form `<instrument_id>/<time>`. I could group the matching instrument ids together with an input like this:

```json
{
  "join": [
    {
      "pfs": {
        "repo": "reading",
        "glob": "*/(*)",
        "replace": "\1"
      }
    },
    {
      "pfs": {
        "repo": "calibration",
        "glob": "(*)/*",
        "replace": "\1"
      }
    }
  ]
}
```

One obvious question here is why add capture to globs when regex already has capture. I'm not totally opposed to adding regex as an alternative to globbing in general, although I'm not convinced it would be usable. However I think that should be a separate decision from this issue and that it's worth it to implement this in terms of globbing because:

- globbing is already an established part of Pachyderm that users understand.
- globs are meant for matching filepaths, while regexes are meant for matching strings in general. And as such I think would have a much higher overhead than globs. In the example above the equivalent regexes would be: `[^\/]*\/\([^\/]*\)` and `\([^\/]*\)\/[^\/]*`, respectively... not especially pretty. Not exactly pretty.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by gabrielgrant** [comment]
This looks very cool.

I'm not sure I follow why we'd want to do these in terms of "replacements", though, rather than, say having a "match field"... am i misunderstanding something, or are you effectively just specifying the section of the path on which to match for the join (by "replacing" the rest of the path with nothing)

**Comment by gabrielgrant** [comment]
Also, seems like this would work nicely with the ability to have split files be named meaningfully: #3568

**Comment by jdoliner** [comment]
So the idea with the replacements is that it allows you to have paths that give you a lot of indexing information about the files, such as location, instrument and time in the example. And then be able to pick out various pieces of information you want to use in this specific join.

I'm not quite sure what a "match field" would look like, or how it would be specified for the different inputs, could you expand on it a bit?

**Comment by jdoliner** [comment]
One thing that the original proposal doesn't cover is more free form joins, or overlapping joins, overlapping in this case means that the same datum in `input1` is supposed to be joined to more than one of the datums in `input2`. This won't work because the datum from `input1` can only be renamed to one thing. For this case we need another solution:

### Input Extensions

The idea looks something like this, we'd add a new input type, called an `ExtendInput`, that'd looks like this:

```proto
message ExtendInput {
  Input input = 1;
  repeated PFSInput extension = 2;
  repeated string extend_cmd = 2;
}
```

This input extends another input with some extra files from PFS, it does this by first setting up the file structure in `/pfs` as if it were just processing the datum from `input` then it runs `extend_cmd` which writes to stdout (or possibly in `/pfs/out`) a list of newline delimited paths that it wishes to extend the datum with. Those files are then loaded into `/pfs` and the transform proceeds. Using this you can arbitrarily extend datums to have whatever additional context you want.

#### Example

Suppose I have a repo `images`, that contains (you guessed it) images, and I want to assemble them into arbitrary montages. I could accomplish this by creating another repo `montages` in which each file is a list of images that you want to assemble together. I.e. one file might be called `animals` and contain the lines:

```
images/dog.jpg
images/cat.jpg
images/rhino.jpg
images/hippo.jpg
images/horse.jpg
```

another file called `pachyderms` might contain the lines:

```
images/rhino.jpg
images/hippo.jpg
images/horse.jpg
```

I could then use the following input:

```json
{
  "extend": {
    "input": {
      "pfs": {
        "repo": "montage",
        "glob": "/*",
      }
    },
    "extend": [
      {
        "repo": "images",
      }
    ],
    "extend_cmd": ["cat", "/pfs/montage/*"]
  }
}
```

which would process two datums, `animals` and `pachyderms` from `montage` and each one of those would have the relevant files available to them once the actual transform code runs.

It should also be possible to specify globs in the filename, for example if I wanted to have a montage that included all images beginning with an `a` then I could have a file with the single line:

```
images/a*.jpg
```

**Comment by gabrielgrant** [comment]
Making it easy to pull in a collection of files seems like it would be super helpful. I think this is another case where being able to merge them as part of the download would make it a lot more usable (#2902)

**Comment by gabrielgrant** [comment]
To clarify [my question above about "match" vs "replace"](https://github.com/pachyderm/pachyderm/issues/3623#issuecomment-479673182): I find "replace" to be a bit of a strange name for this field -- my initial reading of that implied that the matched group in the glob pattern was being replaced by something else

Suggesting using "match" instead was partly me misunderstanding exactly what the "replace" value was doing, though, so I don't think that's a good alternative. 

It seems like it makes sense to think about/describe this as a re-mapping of "actual" (in PFS) filenames to "to-join-against" (in PPS) filenames, so I would have found something like `rename`, `rename_as`, `remap_as`, etc. to be more intuitive.



 it isn't really "replacing"  one thing think `rename" or "

**Comment by gabrielgrant** [comment]
Update from in-person discussion:

we actually think it would be better to not actually rename the matched/joined files (so they'll still show up with their original names in `/pfs`), but instead to just specify a `join_key`

**Comment by ddlenz** [comment]
The join_key approach sounds like it would be most useful for the use cases here. An ability to have multiple join keys would be very useful for cases where the repo structures don’t align. 
For example, if it were possible to specify two input repos with patterns something like:
/<1>/<2>/*/*
/<2>/<1>
such that the parts of the path indicated with <1> and <2> match in the joined datum, that would be very useful.

Then we could have:
input readings:    /12345/2018/01/02
input calibration: /2018/12345
joined datum:      (/12345/2018/01/02, /2018/12345)

Having even a single join_key though would be a huge help.
