### ISSUE TITLE
Service debugging is opaque

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3628]
**What happened?**: I'm working on updating the jupyter notebook example. As part of it, a pipeline is setup that's configured as a service. This service was failing to start due to issues with the demo itself. However, debugging the issue was opaque than it should be:

1) `pachctl list-pipeline` indicates that the pipeline is running fine:

```
$ pachctl list-pipeline
NAME    INPUT                           CREATED           STATE / LAST JOB  
jupyter (sales:/ ⨯ trips:/ ⨯ weather:/) About an hour ago running / running 
sales   trips:/                         About an hour ago running / success 
```

2) `pachctl get-logs` don't indicate anything is wrong:

```
$ p get-logs | grep ERROR
2019-04-08T16:16:49Z ERROR sharder.AssignRoles error from unsafeAssignRolesCancel: cancelled by user
```

As a workaround, it's possible to get what's causing the failure by getting the kubectl logs of the user container associated with the pipeline. This will give a bunch of json message, but you can use jq to extract out the error messages, e.g. like so: `k logs service/pipeline-jupyter-v1-user user | jq .message`.

**What you expected to happen?**:

1) `list-pipeline` to indicate a failure to start the service
2) `get-logs` to indicate an error

**Comment by jdoliner** [comment]
Pipeline states definitely need to be expand a bit to accurately reflect what's going on with services. Ultimately it may make more sense to break them out into their own resource.

I think `get-logs` works ok for services though, although maybe it could be more obvious on how to get the logs from a service. Remember that `get-logs` with no arguments gets logs from pachd, if you want to see why a service or pipeline failed you do `get-logs -p <pipeline-name>`.

**Comment by ysimonson** [comment]
Ah, right, forgot that about `get-logs`. Are logs not merged for performance reasons?

**Comment by ysimonson** [comment]
Going to close this; ultimately, the cause of the problem was that I wasn't passing in an argument to `p get-logs`.
