### ISSUE TITLE
pachctl get-logs --job=xxx returns logs of job and all previous ones

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3636]
**What happened?**:

pachctl get-logs --job=xxx returns logs of job and all previous ones

**What you expected to happen?**:

pachctl get-logs --job=xxx would return only the log generated by running job xxx.

**How to reproduce it (as minimally and precisely as possible)?**:

Just run a job twice and run `pachctl get-logs --job=xxx` where xxx is the job id of the latest job that run.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.8.6
- Pachyderm CLI version (use `pachctl version`): 1.8.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): linux
- Others:

**Comment by JoeyZwicker** [comment]
Hi @marcadella. Can you explain what you mean when you say, "just run a job twice?". Specifically what commands are you running and what are you seeing?

**Comment by marcadella** [comment]
Sorry I probably made a mistake earlier because I get the expected result now.
Thanks for the follow up.
