### ISSUE TITLE
Diagram high-level components

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3648]
One that would've helped me build a mental model of pachyderm faster is a diagram that lays out the high-level components (pachd, workers, pachctl, etc.), what containers they're running on, how they communicate with each other, etc. I think this, along with #3647 would be really useful as a "getting started as a contributor" document.

**Comment by JoeyZwicker** [comment]
I think we can expand the ask here a little to be a bit more of a user-facing architecture diagram rather than contributor focused specifically. @svekars and I have already been going over this in office hours

**Comment by ysimonson** [comment]
@JoeyZwicker what specifically did you have in mind?

**Comment by JoeyZwicker** [comment]
@svekars and I have sketched various diagrams of the last few months outlining "how data get written into pachyderm", "how a job/workers interact", as well just general outlines of pachd, etcd, pfs, pps, object storage, etc. None of it is publishable right now, but there are plans to do add architecture overview docs in the medium term future. 

I don't have anything all that more specific than that right now.

We totally agree on the value of this, but it's definitely one of those projects just caught in the backlog for a while

**Comment by smthpickboy** [comment]
Any update on this?

**Comment by mindthevirt** [comment]
@smthpickboy this is something we're looking into it at the moment. This will likely come before #4770

**Comment by mindthevirt** [comment]
This has now been addressed as part of #5791
