### ISSUE TITLE
Make `pachctl` have better error messages when args are wrong

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#365]
Right now if you do the wrong number of args to `pachctl` you get a very uninformative error message like:

```
Expected 1 args, got 0
```

We should make it so you get back `Usage` instead.

**Comment by sjezewski** [comment]
Since we're using pedge.io helpers for this, where do you want the solution to live?

Make a PR for those helpers? Write our own?

**Comment by jdoliner** [comment]
I think our best bet would be just getting it into the library with a PR, printing usage with the wrong number of args seems a better default to me. Hopefully getting it merged in will be painless. If not a suppose we could just write our own we're talking about some pretty simple functionality here.
