### ISSUE TITLE
Allow scheme in PACHD_ADDRESS environment variable

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3653]
**What is the goal / desired outcome?**
allow grpc:// grpcs:// in the environment variable PACHD_ADDRESS to support TLS environments

**If there is a way to accomplish this today via workaround, what does that require?**
I have not found a way to use a SSL enabled GRPC endpoint with pachctl. I did notice that pachd has the ability to reference TLS keys, so perhaps there is a way to do this from the pachd side? WHat I did was set up an ingress_nginx ingress controller with GRPC support and a CA signed tls cert, but I can't make pachctl work with it because the transport comes in as h2c and not h2 (alpn). 
**(Optional) What is your proposal for a feature to solve this?**
Allow grpc:// and grpcs:// to appear in the PACHD_ADDRESS environment variable (As well as an optional path, so... grpcs://mypachdhostname:443/grpc for instance would be valid. Default to / and grpc:// to preserve compatibility

Or, if this is possible in the current system, document how to do it.

**Comment by gabrielgrant** [comment]
Thanks for filing this, and sorry for the delayed reply. My understanding is that pachd should support TLS already, though i think it may rely on sharing a self-signed cert. I believe @msteffen was the one who implemented this, though, so perhaps he can add some more color (and maybe point at relevant issues/docs explaining how this works? i'm not seeing them right now...)

**Comment by msteffen** [comment]
@brokenjacobs pachctl does indeed support TLS (with pachd as the endpoint). You can set it up with a self-signed cert, but if you've already set up a trusted CA on your machine, you should also be able to a use a CA-signed cert). `pachctl deploy` has a flag `--tls` which takes a path to a signed certificate and private key, which get placed in a kubernetes secret and used by pachd after startup.

That said, if supporting an ingress with a cert and key is easy I think it would be great for us to do in principle. People have all kinds of setups and security is important so giving people more options seems better. If you already know how to do it, tips (or patches!) would be welcome.

I think supporting h2/ALPN may just be a matter of setting the right options in `grpc.Dial` in our client library, in which case that's easy and I'm happy to do it. I'm less certain of the feasibility of supporting a path—I know GRPC is implemented on top of HTTP/2, but I don't understand the relationship very well, and I don't know if/how it uses paths

**Comment by gabrielgrant** [comment]
@chainlink do you have any knowledge of/experience with routing GRPC traffic as HTTP requests (including moving an entire server to use a subpath)?

**Comment by brokenjacobs** [comment]
my assessment was it was a grpc.Dial issue as well, hence the request for specifying a uri in the environment variable. When I look at the ingress-nginx logs attempting this it indicates that the pachctl command never attempts tls.

**Comment by msteffen** [comment]
I believe this issue is fixed by https://github.com/pachyderm/pachyderm/pull/4093. The fix should be in Pachyderm 1.9.6+
