### ISSUE TITLE
Document compatibility with various object stores

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3663]
In theory, pachyderm should work with any S3-compatible object store. In practice, however, some object store implementations have bugs/quirks that make them either hard or impossible to use with pach. As we work through setting up more object stores, it would be good if we started compiling a list of which versions/products are known to work, and config pitfalls we know how to overcome.

Object stores known to work via S3 compatibility layer:
- Digital Ocean
- IBM Cleversafe
- Dell EMC ECS (only v3.3 and above due to #3443)
- Minio
- Ceph (I think? not actually 100% sure who is using this)
- SwiftStack (there were some hoops to jump through to get this working: #3544)

Clarification -- these S3-compatible object stores are in addition to the three cloud object stores supported via their native APIs:

- Amazon S3
- Google Cloud Storage
- Azure Storage

**Comment by JoeyZwicker** [comment]
@pappasilenus is working on an "on prem" deployment doc that includes exactly this. Thanks for the issue and we'll make sure everything here gets covered.

**Comment by danielefranceschi** [comment]
@pappasilenus I can share my experience with [zenko cloudserver](https://github.com/scality/cloudserver) deployed via [its official helm chart](https://github.com/helm/charts/tree/master/stable/cloudserver).

**Comment by gabrielgrant** [comment]
@danielefranceschi that would be very helpful. Did it work completely? Any particular hoops/config/auth requirements to jump through?

**Comment by danielefranceschi** [comment]
> that would be very helpful. Did it work completely? Any particular hoops/config/auth requirements to jump through?

I haven't encountered particular issues; the only _boring_ thing is the requirement of https for connections from pachd to the S3 server (which IMO is annoying in a same-cluster in-house deployment), solved using a tls-enabled ingress with a valid star certificate:
```shell
helm install --namespace STORAGENS --name zenko 
   --set localdata.persistentVolume.existingClaim=MYPVC 
   --set api.ingress.enabled=true --set api.ingress.hosts="{\"S3.DOMAIN\"}" 
   --set api.endpoint=S3.DOMAIN --set api.credentials.accessKey=ACCESSKEY 
   --set api.credentials.secretKey=SECRETKEY stable/cloudserver
```
where `MYPVC` is a pvc bound to a pre-provisioned (large) PV and  `S3.DOMAIN` is a DNS alias pointing to the ingress node IP.  

I created a bucket with
```
s3cmd --host=S3.DOMAIN --access_key=ACCESSKEY --secret-key=SECRETKEY 
  --bucket-location=us-east-1 mb s3://BUCKETNAME
```
then I deployed Pachyderm with
```shell
pachctl deploy custom --etcd-storage-class=nfs --dynamic-etcd-nodes=1 --namespace=PACHNS  
        --object-store s3 any-string 10 BUCKETNAME ACCESSKEY SECRETKEY S3.DOMAIN
```
Everything works well so far, IMHO better than Minio but with slightly greater resource requirements.

HTH

**Comment by gabrielgrant** [comment]
Thanks @danielefranceschi 

You're right that _requiring_network-internal object stores use TLS seems a unnecessary if the transport is secured in other ways. I had thought there was a flag somewhere on the deployment to disable this requirement, but could be remembering.

@pappasilenus you were working on more comprehensive docs for on-prem clusters recently, right? Is this TLS-disabling flag something you came across?

**Comment by pappasilenus** [comment]
Thanks, @danielefranceschi.  I can see having a requirement for TLS everywhere in some circumstances due to regulatory requirements or a security environment where internal threats are prioritized.   I think your solution would pass muster in those environments. Thanks, again!

**Comment by mindthevirt** [comment]
Currently, any object store with an S3-compatible API should be working. We're not aware of any object stores which have recently caused any trouble. Some examples of S3-compatible object stores are referenced in the on-premises deployment documentation [here](https://docs.pachyderm.com/latest/deploy-manage/deploy/on_premises/#deploying-an-object-store). I'll go ahead and close out this issue and we'll open a new one if we encounter any object stores which need tuning or don't work.
