### ISSUE TITLE
Restrict characters used in branch names before v1.9 release

### ISSUE THREAD

**Issue by Tryneus** [pachyderm/pachyderm#3666]
Now that `pachctl` commands use the format `repo@branch:file`, we should make sure repo and branch names don't create a situation where they can't be referenced.

For repo names, this is already a given because they are restricted to "alphanumeric characters, underscores, and dashes", but branch names have no such restriction.  I think we should still allow _some_ special characters on branch names (I like using `/`, for example), but we should at least restrict `:` to avoid ambiguity on CLI params.

This is a harder-to-solve problem for migrations from previous Pachyderm versions.  We can automatically rename branches and do some handling for name conflicts, but changing data during an upgrade is not very user-friendly.  It would be better if we could error during the upgrade and have users pass a flag to indicate that they are aware these changes are going to be made to their data (i.e. a '--force' of some kind).  I'm not too familiar with our upgrade process, so this might be hard to find a place for.

**Comment by JoeyZwicker** [comment]
Do we also want to think about issues like #3652?

> several environment variables are named after repositories. If your repository contains an invalid character for an environment variable (like the '-' or '=' characters) this will break.

**Comment by JoeyZwicker** [comment]
@Tryneus is this done as part of 1.9.0 already or still outstanding?

**Comment by Tryneus** [comment]
@JoeyZwicker - this was fixed in #3692, although I don't think there's any specific migration changes.
