### ISSUE TITLE
Images are not showing up on SAML docs page

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3677]
The Okta screenshots on [the SAML docs page](http://docs.pachyderm.io/en/latest/auth/saml.html) aren't showing up right now

![image](https://user-images.githubusercontent.com/493968/56842028-76b3b900-6846-11e9-93fb-170a19b1e403.png)

However it looks like they are showing up if you look at that docs page directly in github: https://github.com/pachyderm/pachyderm/blob/master/doc/auth/saml.md

**Comment by JoeyZwicker** [comment]
fixed
