### ISSUE TITLE
First-class JupyterHub support

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3681]
**What is the goal / desired outcome?**

Ability to run JupyterHub in the same k8s cluster as pachyderm, with first-class support so that it's possible to interact with pachyderm via Jupyter notebooks.

**If there is a way to accomplish this today via workaround, what does that require?**

There is an example of using Jupyter running on a user's machine with the Python API client: https://github.com/pachyderm/python-pachyderm/tree/master/examples/jupyter

This isn't ideal, as it requires users to install a bunch of deps locally, pull all data locally, and has no story for how to persist/version output and/or analysis

There was a demo of running Jupyter as a pach service in this repo, but it was broken in a number of ways (#2846) and so it was removed in #3633

**Comment by jdoliner** [comment]
Repurposing this issue a little bit to focus on creating a Jupyter plugin for Pachyderm that allows people to checkpoint their jupyter notebooks from within a Pachyderm cluster and save them to PFS. I think that's probably the past path forward on a good Jupyter story. That may or may not lead to general Python SDK, I think that will have to happen eventually, but the Jupyter integratation story is arguably more important and I can't really imagine it'll take us too far out of our way.

**Comment by ysimonson** [comment]
What's the difference between this ticket and #2846?

**Comment by ysimonson** [comment]
This is effectively complete now, and we're onboarding customers to it
