### ISSUE TITLE
v1.1 Documentation

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#369]
Moved over some issues from v1.0 #309 

- [ ] Roadmap
- [x] scraper demo?
- [x] Developer guide

- [ ] Architecture overview
- [ ] Support page and docs
- [ ] Migrate blog?

- [ ] Follow/star buttons more prominent
- [ ] Make dropdown menu not ugly
- [ ] Check all docs/site/GH for correct links @JoeyZwicker and everyone else
- [ ] fruit stand video tutorial @jdoliner 
- [ ] Website: add support page.

**Comment by sjezewski** [comment]
Reminder for docs for new ENV variables for user job environments:

https://github.com/pachyderm/pachyderm/pull/409

Basically this, but w real names:

```shell
PACH_COMMIT_OUTPUT_ID
PACH_COMMIT_INPUT_REPO_NAME_1_ID
PACH_COMMIT_INPUT_REPO_NAME_1_ID
```

**Comment by sjezewski** [comment]
That specific item was added to the docs. The rest of these look like todos for the corp site. I assume this gets pushed to 1.2?

**Comment by jdoliner** [comment]
Sounds good to me.

**Comment by sjezewski** [comment]
@msteffen and @JoeyZwicker are doing a docs overhaul, but the things listed here I'm pretty sure are not releveant. So I'm closing this issue

**Comment by szeitlin** [comment]
guys, I am having trouble finding where these are in the docs. Can you point me to where they are in the code?
