### ISSUE TITLE
Docs links are broken on github

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3716]
It seems our docs links generally point at the HTML version of the file (eg the link to `create-pipeline` docs [here](https://github.com/pachyderm/pachyderm/blob/master/doc/reference/pipeline_spec.md), or [this](https://github.com/pachyderm/pachyderm/pull/3715/files#diff-d4ae44c7d44330220d7351a4b3e4a572R253)). I'm assuming that is needed for these links to work on ReadTheDocs, but that causes them to be broken on github. It seems like there must be some way to make docs usable in both places, no?

**Comment by JoeyZwicker** [comment]
This is a known issue that we've tried to figure out a fix for about 5 times and have not figured out a solution. When we migrate off of ReadtheDocs in Q3, this will stop being a problem.
