### ISSUE TITLE
deploy storage amazon help unclear

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3727]
**What happened?**:

The help for 

`pachctl deploy storage amazon`

specifies the following parameters

` pachctl deploy storage amazon <region> <bucket-id> <secret> [<token>] [flags]`

It appears that `<bucket-id>` would be more accurately specified as `<aws-key-id>`.

It's also unclear whether `<token>` should be actually be specified _instead_ of the `<aws-key-id> <secret>` combination, maybe like so:

` pachctl deploy storage amazon <region> <bucket-id> <secret> [ | <token> ] [flags]`

Unclear to me how to specify this.

**What you expected to happen?**:

I expected it to be straightforward, and it was not.

*

**Comment by Nick-Harvey** [comment]
Another user reported similar confusion in the users channel this morning.  

@pappasilenus `<bucket-id>` is the name of the bucket I believe and not the `<aws-key-id>`. If i'm correct, perhaps it should be something like:   
`pachctl deploy storage amazon <region> <bucket-name> <aws-AccessKeyId> <aws-SecretAccessKey> [<token>] [flags] `

**Comment by mindthevirt** [comment]
This issue can be closed since it has been fixed on 5/20/2019
