### ISSUE TITLE
Track of Hostfiles

### ISSUE THREAD

**Issue by pratapaprasanna** [pachyderm/pachyderm#3735]
**Say i get a data of 1000 files/per day i have to manually add those files to my pipeline using the `pachctl put file ...` It would be great if the cron job present in pachyderm also has the ability to check host the directory from where data has been added based on spec time has any change and accordingly make a commit **

**The other way around is to write a cron job and execute the pachctl command**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by ysimonson** [comment]
The challenge here is that there's so many different ways the content could be stored, it's not really feasible for pachyderm to provide a generic solution. That's why pipelines are great: they contain executable user code, and can crafted to whatever your needs are.

**Comment by jdoliner** [comment]
Pachyderm's cron isn't appropriate for this, since there's no guarantees about which host the cron is going to run on. Your host machine has its own cron implementation though, that would be a good way to implement the behavior you're looking for.
