### ISSUE TITLE
worker tries to create /pach directory; fails without root access

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3738]
Usage of `/pach` directory was added to the `user` container within pipline RCs/pods (for caching hashtrees during the shuffle step). creation of this directory fails if the container isn't run with root permissions (eg on openshift). This directory should be created as a volume in the generated RC manifest, instead of being created in the worker code.

The same change was already made for the `storage` container. Details here:  https://github.com/pachyderm/pachyderm/issues/3404

This problem can be worked around by ensuring that any docker image used as a pipeline has an empty `/pach` dir added to it as part of the docker image authoring process

**Comment by JoeyZwicker** [comment]
@pappasilenus Is this fixed already or something that users need to manually change in the manifest currently, but we should be fixing in pachyderm automatically?

**Comment by gabrielgrant** [comment]
@JoeyZwicker this is still an issue (was introduced some time around 1.8.4), and should be fixed in Pach. AFAIK this is the last issue that blocks us from claiming full OpenShift support

**Comment by jiangytcn** [comment]
hi @gabrielgrant what's the status of OpenShift support now ? I followed the wiki to install pachyderm on OKD on-prime environment, but now failed to start pod/pipeline-edges-v1- with 
```
    message: 'pods "pipeline-edges-v1-" is forbidden: unable to validate against any
      security context constraint: [spec.volumes[4]: Invalid value: "hostPath": hostPath
      volumes are not allowed to be used]'
```
is it related to the issue of here ?
