### ISSUE TITLE
cross jobs runs with incomplete datum causing "broken" full history

### ISSUE THREAD

**Issue by jfri3d** [pachyderm/pachyderm#3756]
**What happened?**:
Not able to retrieve full history from output repo of cross pipeline when all input repos have valid data (i.e. a complete datum). This is a bug with started a cross job when not *all* input repos have valid datums.

**What you expected to happen?**:
A cross job should only start when a *complete* datum exists. This would fix the "broken" full history from the output repo.

**How to reproduce it (as minimally and precisely as possible)?**:

1\. Add dummy pipeline **join.json** to “join” two input filenames

```json
{
  "pipeline": {
    "name": "join"
  },
  "transform": {
    "image": "alpine:latest",
    "cmd": [ "/bin/sh" ],
    "stdin": [
       "for a in /pfs/A/*",
       "do", 
       "for b in /pfs/B/*",
       "do",
       "touch /pfs/out/$(basename $a)_$(basename $b)",
       "done",
       "done"
    ]
  },
  "input": {
    "cross": [
        {"pfs": {
           "repo": "A",
           "glob": "/*"
            }},
        {"pfs": {
           "repo": "B",
           "glob": "/*"
            }}
  ]},
  "standby": true
}

```

2\. add pipeline + repos

```sh
pachctl create repo A
pachctl create repo B
pachctl create pipeline -f join.json
```

3\. check pipeline status

```sh
pachctl list pipeline

NAME INPUT         CREATED       STATE / LAST JOB
join (A:/* ⨯ B:/*) 2 seconds ago standby / starting
```

4\. add empty dummy file to repo **A**

```sh
echo "" | p put file A@master:A1
```

5\. job successfully runs and makes an output commit with *only one input*

```sh
pachctl list job

ID                               PIPELINE STARTED        DURATION           RESTART PROGRESS  DL UL STATE
64277ed3fcaf4c7abc8c5ce85ad04b76 join     3 seconds ago Less than a second 0       0 + 0 / 0 0B 0B success
```

6\. inspection of job yields **incomplete** datum

```sh
pachctl inspect job 64277ed3fcaf4c7abc8c5ce85ad04b76

# abbreviated output

Input:
{
  "cross": [
    {
      "pfs": {
        "name": "A",
        "repo": "A",
        "branch": "master",
        "commit": "913b3e11fbf04e6c9b4af245d1ee1de4",
        "glob": "/*"
      }
    },
    {
      "pfs": {
        "name": "B",
        "repo": "B",
        "branch": "master",
        "glob": "/*"
      }
    }
  ]
}


```

7\. add empty dummy file to repo **B
**

```sh
echo "" | p put file B@master:B1
pachctl list-job

ID                               PIPELINE STARTED        DURATION           RESTART PROGRESS  DL UL STATE
63c5451d74d24b35922c4b33c9ae9501 join     17 seconds ago 15 seconds         0       1 + 0 / 1 2B 0B success
64277ed3fcaf4c7abc8c5ce85ad04b76 join     32 seconds ago Less than a second 0       0 + 0 / 0 0B 0B success
```

8\. check file in **join** repo

```sh
pachctl list file join@master

COMMIT                           NAME   TYPE COMMITTED          SIZE
185000eda854410b8a03c5ca4e73e719 /A1_B1 file About a minute ago 0B
```

9\. add more files to repo **A** and **B**

```sh
echo "" | p put file A@master:A2
echo "" | p put file A@master:A3
echo "" | p put file B@master:B2
echo "" | p put file B@master:B3
```

10\. check output files in **join** repo (**default**)

```sh
pachctl list file join@master

COMMIT                           NAME   TYPE COMMITTED    SIZE
e3d061d667b84843a74714bb9c0f2b7d /A1_B1 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A1_B2 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A1_B3 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A2_B1 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A2_B2 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A2_B3 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A3_B1 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A3_B2 file 1 second ago 0B
e3d061d667b84843a74714bb9c0f2b7d /A3_B3 file 1 second ago 0B
```

11\. check output files in **join** repo (**actual commit history**)

```sh
pachctl list file join@master --history -1

no file(s) found that match /A1_B1
```

---

I would expect the actual commit history, similar to how the input repo **A** (or B) would look.

```sh
pachctl list file A@master --history -1

COMMIT                           NAME TYPE COMMITTED     SIZE
913b3e11fbf04e6c9b4af245d1ee1de4 /A1  file 5 minutes ago 1B
186f168990714da2a0aca0b2521c7804 /A2  file 3 minutes ago 1B
5542804fe7e946088782e6585adbabec /A3  file 3 minutes ago 1B
```

**Comment by JoeyZwicker** [comment]
Thanks for submitting @jfri3d!

And just to clarify what you said in Slack, if you repeat this process but don't create the pipeline until _after_ at least one commit is created in both A and B, this error does not occur?

**Comment by jfri3d** [comment]
Exactly. A workaround is to first create and add files to both *A* and *B* then the pipeline will not create an "incomplete" datum job.

**Comment by jfri3d** [comment]
@jdoliner - I came across this issue once more with the latest version of pachyderm (1.9.0). Any idea why this issue resurfaced? I followed the same example as above.

**Comment by JoeyZwicker** [comment]
@jfri3d Pachyderm's model to still trigger a zero-datum job when you have data in one input but not the other didn't change. This fix was the make sure history didn't error in that use case as it does in the initially-filed issue. 

Does `pachctl list file join@master --history -1` work for you now?
