### ISSUE TITLE
Make it possible to deactivate auth flows

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3759]
When using robot users exclusively, we want to deactivate/lock down other auth flows (namely GitHub). We need to add an API end-point to do so

Proposal: add a `pachctl auth disable` command. By default it disables all auth flows. In the future, this can potentially be extended to disable specific auth flows (eg if using SAML, one may want to disable github only). Alternatively, if we move all auth to use the same auth config API used by SAML, then this kinda becomes obsolete

Note: this operation could potentially be pretty dangerous, since any users that lose their auth keys will no longer be able to log in, so should require confirmation through the CLI.

**Comment by chainlink** [comment]
@kevindelgado can this be closed?

**Comment by kevindelgado** [comment]
Closed via #3992
