### ISSUE TITLE
Glob matching with capture groups

### ISSUE THREAD

**Issue by adelelopez** [pachyderm/pachyderm#3762]
**What is the goal / desired outcome?**
To implement capture groups using Glob pattern matching for the purpose of implementing #3623 in addition to solving aspects of #3335, #2911, and #1488.

Specifically, to allow capture groups, support extended glob patter matching, and potentially some introduce some Pachyderm-specific features which make it easier for our users. Any significant deviations from the [bash standard](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html) will have flags, so that we can contribute a general purpose glob tool to the Go ecosystem.

At the same time, we will require the implementation to be performant.

**What is your proposal for a feature to solve this?**

The overall idea is to write a parser for the desired glob syntax, which will convert it into a standard regular expression. This will be processed with the [regexp](https://golang.org/pkg/regexp/) standard library. 

The Go regexp library has the nice property that it is guaranteed to run in time O(nm), where n is the length of the regular expression, and m is the length of the test string. It does this by using a finite state machine to process test strings. See [this article](https://swtch.com/~rsc/regexp/regexp1.html) for details. The parser will be written to preserve this property on the overall glob pattern.

As a starting point for the parser, I intend to use the parser for the glob library we currently use: https://github.com/gobwas/glob/tree/master/syntax

In order to guide the implementation of the parser, I intend on looking to https://github.com/micromatch/extglob, which implements extended glob pattern matching by converting it into an equivalent regular expression in javascript. This library also has extensive tests, which will be useful for ensuring conformity to the bash standard.

**Comment by jdoliner** [comment]
This sounds like a great general purpose approach to expanding globbing. As for the question we talked about offline with negations, having read the issue I initially posted on it I still don't remember what the use case I had in mind for it was. And I don't remember this coming up much with users since then, so I'd say it's fine to ignore it for now, especially if it makes things tricky.

**Comment by adelelopez** [comment]
Alright, that makes sense. I was thinking it might be simplest just to using a PCRE like https://github.com/glenn-brown/golang-pkg-pcre for the negation case, which it would be easy to determine after parsing.

But at first, I'll just get the basic functionality working.

**Comment by brokenjacobs** [comment]
If the regex route doesn't work out, Participle looks like a reasonable approach:
https://github.com/alecthomas/participle

Good performance, easier to document.
