### ISSUE TITLE
reorganize backup, restore, upgrade and migration documents

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3771]
** Background **

Currently, our documentation has two sections relating to backup, restore, upgrading and migration.  These two documents are confusing, overlapping and not task specific.

1. https://github.com/pachyderm/pachyderm/blob/master/doc/managing_pachyderm/backup_restore_and_migrate.md
2. https://github.com/pachyderm/pachyderm/blob/master/doc/deployment/upgrading.md

** Reorganization Proposal **:

Break these documents into four discrete operations documents

1. Backing up Pachyderm
2. Restoring Pachyderm from backup
3. Pachyderm minor version upgrades (upgrades)
4. Pachyderm major version upgrades (migrations)

**Comment by JoeyZwicker** [comment]
I believe this is done. @pappasilenus please reopen if not
