### ISSUE TITLE
Config/Context management

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3774]
**What is the goal / desired outcome?**

Easily manage configurations for connecting to multiple pachyderm clusters, potentially in multiple K8S clusters, for testing in different environments, or from different projects

**If there is a way to accomplish this today via workaround, what does that require?**

Right now pachctl has the following cascade of checks for where to connect:
1. `PACHD_ADDRESS` env var
1. `ADDRESS` env var
1. `~/pachyderm/config.json` file
1. `localhost:30650`

So changing the env var to change which cluster is being connected to is doable, but not the most ergonomic experience. There is, however, other contextual info that this doesn't work for. For example, AFAIK there is no way to set env vars to sub out auth info, and I believe the config file also can hold some TLS-related keys/certs that should be cluster-specific, but end up being globally scoped, since the config file is global

**(Optional) What is your proposal for a feature to solve this?**

Current tentative proposal is implement a notion of "config contexts" which contain all the info for connecting to a particular cluster, as a particular user, with a particular setup
By default these contexts would be stored in a user-global config file, but we have also discussed having directory-scoped configs (so you could have a different config used automatically for different projects in different directories, much like how git, heroku etc. work)

Exact user experience of interacting with/changing these contexts is TBD. It would be useful to collect various use-cases for cluster config management, to make sure they're being adequately addressed by the design

Related issues:
- Allow setting namespace flag in pach config file #3419
- Document use of pachyderm config file #3036
- Config info messages should be written to stderr, not stdout #3311
- Info about API ingress (incl PACHD_ADDRESS usage) #3466 
- global pachctl ADDRESS setting can be confusing for users #2606

**Comment by ysimonson** [comment]
Agreed that it makes the most sense to put this in config. Contexts would have these values:
- Connection methodology (direct, implicit port forwarding, or connect locally with the assumption that port forwarding is already setup.)
- IP address
- Remote ports (pachd, SAML ACS, dash UI, dash websocket, PFS-over-HTTP, s3gateway)
- k8s namespace

**Comment by gabrielgrant** [comment]
In talking about this more, I actually think the "correct" pattern today for switching between multiple clusters is just to have multiple complete config files. I believe there's an env var that lets you switch which config file is being used. That's actually not a _terrible_ way of doing this, so one approach would just be to add some sugar/conventions around that pattern: basically the pach dir would contain a dir full of config files, each config file encapsulating an entire context. This seems like it could potentially make the migration a lot easier, but it's also not clear to me how exactly this would work, since it still relies on an env var, which pach is unable to export across runs

**Comment by jdoliner** [comment]
I think this design basically makes sense, one small tweak, I think rather than having `~/.pachyderm/config.json` contain a key that points to a different config why not just have it be a symlink? This is how I've manually handled multiple configs for both k8s and Pachyderm and it works really well and I think should be pretty obvious what's going on to users. This also probably eliminates the need for the `PACH_CONFIG` variable.

**Comment by ysimonson** [comment]
@Tryneus brought up the good point that pachyderm isn't file- or repository-oriented in the way that heroku is, so having configs scoped in specific directories doesn't make as much sense. Moreover, I think it would be confusing to people accustomed to k8s contexts. Between that and the added complexity of config migrations (or broken symlinks), I don't think scoped configs makes sense.

I do like the idea of building on `ConfigV1` as it stands for contexts via multiple config files, and will see how far we can take that.

One other note: `ADDRESS` is gone as of 1.9. I am somewhat concerned about churn on this end of things with pachctl (deprecation of `ADDRESS`, addition of implicit port forwarding, and with this, the removal of `PACHD_ADDRESS`), so will try to see if there's a clean way to do this without an immediate deprecation of `PACHD_ADDRESS`.

**Comment by ysimonson** [comment]
Should contexts contain NodePort values for services, in case they're customized? i.e. do we want first-class support for NodePort customization?
