### ISSUE TITLE
pfs fuse mount should automatically update when new commits are added

### ISSUE THREAD

**Issue by benwbooth** [pachyderm/pachyderm#3781]
**What is the goal / desired outcome?**

If a user has a pfs fuse volume mounted with `pachctl mount`, then commits new files with `pachctl put file`, currently the new file will not be visible until the pfs volume is unmounted and re-mounted. The new file should be visible automatically without having to unmount and re-mount.

**If there is a way to accomplish this today via workaround, what does that require?**

un-mount then re-mount manually.

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
This is something that we've found to be a general limitation of FUSE, due to the way that the kernel caches filesystem results. Even if our FUSE layer were to receive updates it's unreliable when those updates will be reflected in system calls. Feel free to reopen this if you know of a reliable way to accomplish this.

**Comment by benwbooth** [comment]
It might be worth looking at the code for [sshfs](https://github.com/libfuse/sshfs) to get an idea how to write a FUSE filesystem that can be updated. SInce sshfs is a network filesystem, it has to deal with the filesystem changing on the host and reflecting those updates to the client.

**Comment by jdoliner** [comment]
Looking through sshfs I don't think they're doing anything special to get around caching effects. I think it's just implemented with the expectation that changes on the host will eventually be reflected on the client. I'm not sure how useful this is in sshfs I suspect it breaks down if you have any sort of programmatic access to the sshfs mount, or your programmatic access winds up having a lot of retry logic built into it. But it's probably fine when all the access is manual and the user knows to wait and retry if he doesn't see something. Pachyderm's fuse layer gets used for programmatic access and back when it tried to do automatic updates users had to wait and retry a lot or just remount the filesystem. So auto updating never worked that well and we decided to remove it in favor of something simpler but more predictable.

**Comment by benwbooth** [comment]
I'm not sure how feasible it would be, but another idea I had was running [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) on top of pachyderm's s3-gateway. I'm not sure if that approach would also suffer from caching issues, also s3-gateway is only in pachyderm enterprise version.

**Comment by ysimonson** [comment]
I would advise against that because it's so many layers of indirection, so more opportunities for bugs and performance regressions
