### ISSUE TITLE
Document passing GKE credentials

### ISSUE THREAD

**Issue by robfras** [pachyderm/pachyderm#3792]
**What happened?**:
Newly deployed pachyderm cluster on GKE does not run any jobs but shows pipeline in running state constantly. No commit seen in repos.

**What you expected to happen?**:
Testing opencv example on a newly deployed GKE cluster using v1.9.0rc3, I was expecting to 
make it work as it did locally. 

**How to reproduce**:

Follow the tutorial https://docs.pachyderm.io/en/latest/deployment/google_cloud_platform.html to deploy the pachyderm cluster. Then use the beginner tutorial to create pipelines of the opencv example.

**Environment**:
- Kubernetes version : **1.12.7-gke.10**
- Pachyderm CLI version : **1.9.0rc3**
- Cloud provider : **GKE**
- OS :from Mac OS High Sierra

gz#21

**Comment by robfras** [comment]
On Mac OS , I needed to pass a credentials files like such 
`pachctl deploy google ${BUCKET_NAME} ${STORAGE_SIZE} /path/to/private/key/privatekey.json --dynamic-etcd-nodes=1`

this private key was downloaded on google cloud console > IAM & admin > Services accounts and creating a key for the relevant service account.

**Comment by gabrielgrant** [comment]
Thanks for updating @robfras 

Reopening to add to docs

**Comment by mindthevirt** [comment]
This has been addressed in the docs. The deployment of Pachyderm on GKE now mentiones a cluster-role-binding.
