### ISSUE TITLE
Document how to mount a volume (cookbook using pod_patch?)

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3793]
Beyond general docs for `pod_spec` and `pod_patch` (tracked in #3567), we should have somewhere in the docs (maybe a Cookbook?) specifically telling people that is the feature that should be used to add volumes, since, if i'm looking for how to add a volume, it is _far_ from obvious that pod_patch is what I should be looking for to do so

**Comment by svekars** [comment]
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1585662848052100

**Comment by svekars** [comment]
pod_patch would indeed be the way to do this. It’s a JSON patch of the fields you want to change in the pipeline pod spec. So the steps would be:
Create the persistent volume on the cluster
Figure out what the volume mount would look like on the pod as a k8s manifest
Turn that manifest into a JSON patch
Add that JSON patch to the pipeline spec
I’m not aware of any examples of this offhand, but let me check in with the docs/customer team to see if there is something available.

To fill in the blanks on step 3:
3.a. Get the rc for the pipeline into a file.  The command will be something like
kubectl get rc pipeline-<pipeline-name>-<pipeline-version> -o json > <pipeline-name>-rc.json
3.b. Edit the volumes section to add the volume mount you want.  Save it into a file with another name, so you can do a diff later on.
3.c  Deploy the rc and make sure the pipeline pod restarts.  You may need to kill the pod so it gets restarted from the rc.
3.d Test the pipeline, to see if it works right
3.e  Repeat 3.b-3.d until it works
3.f  Use a json patch generator to generate the patch between your original rc manifest and the one you edited.
4. Same as above
5.  Redeploy the pipeline using the new spec.
6. Test to make sure it works.
