### ISSUE TITLE
One liner to install on linux

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#381]
Would be nice to be able to `apt-get install pachctl`

**Comment by sambooo** [comment]
Working one-liner:
`$ curl -o /tmp/pachctl.deb -fhttps://github.com/pachyderm/pachyderm/releases/download/v1.0.1-RC1/pachctl_1.0.1-RC1_amd64.deb && dpkg -i /tmp/pachctl.deb`

**Comment by sjezewski** [comment]
Great. What I'll do as part of the automation scripts is put that deb file on the corp site so we can make the one liner a bit nicer:

```shell
$ curl -o /tmp/pachctl.deb -L https://pachyderm.io/pachctl.deb && dpkg -i /tmp/pachctl.deb
```

**Comment by sjezewski** [comment]
We're going to run w the one-liner solution for now. Renaming this ticket to reflect this.

I'll open a new ticket for upgrading both brew/deb installations to use the official repositories.
