### ISSUE TITLE
`pachctl logs --follow` immediately exits

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3855]
**What happened?**: Running `pachctl logs --pipeline=... --follow` exited immediately with no error, even though the pipeline exists.

**What you expected to happen?**: With `--follow`, the process should keep running until ctrl+c.

**How to reproduce it (as minimally and precisely as possible)?**: I don't have repro steps yet, but suspect that this occurs when the pipeline has been newly created and no jobs have run yet (Sometimes? Always? Not sure.)

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`):

```
COMPONENT           VERSION                                          
pachctl             1.9.0-25f6e960af2ee74e4e1e5f46c8fef2a3daa051bb   
pachd               1.9.0-25f6e960af2ee74e4e1e5f46c8fef2a3daa051bb  
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): docker for mac
- OS (e.g. from /etc/os-release): macOS

**Comment by jdoliner** [comment]
The pipeline pods not existing would probably explain this, because the call to k8s' log function would fail. We should return an error in that case though.
