### ISSUE TITLE
Make it clear that pipelines will run on all input commits during a restore

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3864]
Bring clarity to the docs based on @msteffen's input to [this conversation](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1560933434358600):

>It used to be the case that Pachyderm would only run pipelines on the HEAD commits of their inputs during `restore`. Some users needed to keep old output commits for various internal/retention reasons, though, so we changed that behavior relatively recently. Now pipelines run on every input commit, to try and preserve old output data in the new cluster.

>Unfortunately whenever we want to move output commits from an old version of Pachyderm to a new version of pachyderm we have to rebuild them because output commits contain metadata that input commits don't (which pachyderm uses to decide, for example, which datums it can skip) and that extra metadata often changes between major releases. For output commits generated by the most recent version of your pipeline, though, Pachyderm should be able to avoid rerunning your code against the pipeline's input data—it simply looks up the old precomputed data for each input datum and reassembles the output commit from the old per-datum output data. Hopefully that makes the transition more manageable.

>In general, we know that migrations are harder than they should be. Our goal is definitely to make them more seamless (by hiding or delaying the conversion from old output formats to new ones) but at least with the designs we're using now, that conversion process does have to happen

**Comment by pappasilenus** [comment]
@svekars I've been writing these, so I assigned it to me.  I'll ask you to review when I fix this...

**Comment by JoeyZwicker** [comment]
I believe eng is changing this behavior. Marking a low priority for now and will likely close later if/when it longer is the case. Maybe end up changing this to just "update docs on restore to explain what users should expect to see happen"

**Comment by JoeyZwicker** [comment]
@svekars I think JD is updating this behavior in his new extract/restore improvements. Let's wait to have that land and then take a boarder pass at clarifying the semantics since they're going to change. I think we can put it on hold for a bit until that last and we test it a bit

**Comment by mindthevirt** [comment]
@jdoliner did this get addressed in one of the refactors during 2019/2020?

**Comment by jdoliner** [comment]
Sorry for slow reply on this. Pipelines now shouldn't rerun anything during a restore since it restores output commits. Closing.
