### ISSUE TITLE
List of Use Cases

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#388]
Until we start actively discussing / working on these, they're listed here.

Each of these will provide learnings internally (inform our technology design) and externally (inform users about usage). We want to balance these effects, so consider these when choosing a use case to start in on.
- Time Machine for Data
- Data CI + CD 
- Scraper Demo
- NN incrementality
- SQL/Postgres Adapter
- Client Library in web language(s) -- ruby/python/node
- Tensor Flow / NN Example
- Scalability Testing
- Human Readable S3 bucket --- #257

**Comment by JoeyZwicker** [comment]
A user suggested we add another non-NLP tensorflow example similar to this at some point in the future. https://databricks.com/blog/2016/01/25/deep-learning-with-apache-spark-and-tensorflow.html

**Comment by sjezewski** [comment]
This tool has proved ineffective for organizing our todos
