### ISSUE TITLE
Autogenerate proto docs?

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3881]
We could use a [library like this](https://github.com/pseudomuto/protoc-gen-doc) to automatically generate docs for our protobuf/gRPC definitions. It might be worthwhile, I'm not sure.

**Comment by mindthevirt** [comment]
@nitinjainsj not sure if this is a docs issue, should this be handled by eng?

**Comment by jdoliner** [comment]
This would probably be better managed by the eng team since it's part of the protobuf compile process. I think it's pretty low priority though, I haven't seen a lot of people asking for docs of our protobufs who aren't willing (in fact many prefer) to read the docs embedded in the .proto files.

**Comment by lbliii** [comment]
https://pachyderm.atlassian.net/browse/DOC-144
