### ISSUE TITLE
Migration docs should clarify same-cluster process

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3883]
Our migrations (moreso than upgrade, but possible upgrade too) docs today are geared towards users spinning up a new cluster and then doing `restore` to that new deployment. 

That's actually a pretty uncommon case because most users just want to update their existing cluster. For big migrations (e.g. 1.7 -->1.8) this can make more sense because there is more area for this to go wrong and its safer. For 1.8 --> 1.9, most will try/want to do it in place and so the docs should clarify that. Specifically, when you restore to un upgraded 1.9 cluster, you need to deploy etcd on a fresh volume that doesnt have the 1.8 data still on it. 

@pappasilenus Just like we have a specific 1.7-->1.8 section, can we add a short and simple 1.8 -->1.9 section that talks about the specifics fort hat migration. namely `extract --no-objects` should be fine here, and restore to a fresh etcd.

**Comment by svekars** [comment]
This was clarified in the latest update to the backup/restore/migrate docs.
