### ISSUE TITLE
union and * behave differently

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3900]
**What happened?**:
Below is an example where using union or glob pattern should yield the same result, but union seems to behave weirdly....

s1.json: 
```
{
  "pipeline": {
    "name": "s1"
  },
  "transform": {
    "image": "ubuntu",
    "cmd": ["bash", "-c", "echo 1 > /pfs/out/1.txt ; echo 2 > /pfs/out/2.txt"]
  },
  "input": {
        "pfs": {
          "repo": "testInput",
          "glob": "1.txt",
          "name": "input"
        }
  }
} 
```
s2union.json: 
```
{
  "pipeline": {
    "name": "s2union"
  },
  "transform": {
    "image": "ubuntu",
    "cmd": ["bash", "-c", "cat $input > /pfs/out/res.txt"]
  },
  "input": {
    "union": [ {
        "pfs": {
          "repo": "s1",
          "glob": "1.txt",
          "name": "input"
        },
        "pfs": {
          "repo": "s1",
          "glob": "2.txt",
          "name": "input"
        }
      } ]
  }
} 
```

s2glob.json
```
{
  "pipeline": {
    "name": "s2"
  },
  "transform": {
    "image": "ubuntu",
    "cmd": ["bash", "-c", "cat $input > /pfs/out/res.txt"]
  },
  "input": {
        "pfs": {
          "repo": "s1",
          "glob": "/*",
          "name": "input"
        }
} 
```

Now create `testInput` as well as the three pipelines and push a random file to `testInput`:
```
pachctl create repo testInput
pachctl put file testInput@master:whatever.txt -f whatever.txt
pachctl create pipeline -f s1.json
pachctl create pipeline -f s2glob.json
pachctl create pipeline -f s2union.json
```

**What you expected to happen?**:
s1 is only here to produce two datums. s1@master will contain:
- 1.txt: ```1```
- 2.txt: ```2```

We expect s2glob and s2union to contain the same unique file `res.txt`:
```
1
2
```
(modulo the order)

**What actually happens**:
s2glob gets the expected result.
However s2union outputs (using `pachctl get file s2union@master:/res.txt`):
```
2
```
The `1` is missing!

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.9.0               
pachd               1.9.0  

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by JoeyZwicker** [comment]
Hi @marcadella. I figured out your issue here. You've got a minor issue with your union json. You're missing a set of brackets and therefore it thinks you're unioning only one input. The correct json (minus comments) is:

```
{
  "pipeline": {
    "name": "s2union"
  },
  "transform": {
    "image": "ubuntu",
    "cmd": ["bash", "-c", "cat $input > /pfs/out/res.txt"]
  },
  "input": {
    "union": [ {
        "pfs": {
          "repo": "s1",
          "glob": "1.txt",
          "name": "input"
        }     // <--- this is missing
      },   
      {      // <---  and this too
        "pfs": {
          "repo": "s1",
          "glob": "2.txt",
          "name": "input"
        }
      } ]
  }
} 
```

I was able to figure this out because when I used your s2union pipeline I noticed the job only had 1 datum:

```
905b687327084e37bd7d36d8bf465ead s2union  13 minutes ago 7 seconds         0       1 + 0 / 1 2B 2B success
```

So that meant that it didn't even think that you had two datums to work with. Doing inspect pipeline revealed the issue:

```
pc inspect pipeline s2union
Name: s2union
Created: 13 seconds ago
State: running
Stopped: false
Reason:
Parallelism Spec: <nil>
ResourceRequests:
  CPU: 0
  Memory: 64M

Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Input:
{
  "union": [
    {
      "pfs": {
        "name": "input",
        "repo": "test",
        "glob": "2.txt"
      }
    }
  ]
}


Output Branch: master
Transform:
{
  "image": "ubuntu",
  "cmd": [
    "bash",
    "-c",
    "cat $input > /pfs/out/res.txt"
  ]
}


Job Counts:
starting: 0	running: 0	failure: 0	success: 1
```

**Comment by JoeyZwicker** [comment]
Please reopen or comment here is anything above isn't clear or you think I'm missing something.

**Comment by JoeyZwicker** [comment]
I don't really know if there's any way for us to fail more gracefully here because your pipeline had valid json. Perhaps we should throw a message if you try to create a pipeline with a union or cross with only one input?

**Comment by marcadella** [comment]
Thanks a lot and good tip to inspect the pipeline.
However, even though the json was valid and I agree that my union had only one element, this element was probably not valid: a couple of pfs does not really make sense does it?
So your parser could probably detect that and throw an exception?
