### ISSUE TITLE
Overwritten "dynamic" output from two datums

### ISSUE THREAD

**Issue by jfri3d** [pachyderm/pachyderm#3909]
**What happened?**:
First datum (`D0`) produces a dynamic output. Second datum (`D1`) produces another dynamic output. Both datums contain the same file with altered contents. The processing of the two datums only produces a single output file on HEAD of master (from `D1`). The actual output can be found via the `pfs_state` on the `stats` branch.

**What you expected to happen?**:
Two output files on HEAD of master since the output file names are dynamic.

**How to reproduce it (as minimally and precisely as possible)?**:
1\. simple transform for dynamic output files

```code
{
  "pipeline": {
    "name": "single"
  },
  "transform": {
    "image": "alpine:latest",
    "cmd": [ "/bin/sh" ],
    "stdin": [
       "for a in /pfs/A/*",
       "do", 
       "rand=$(hexdump -n 16 -e '4/4 \"%08X\" 1 \"\n\"' /dev/random)",
       "touch /pfs/out/$rand",
       "done"
    ]
  },
  "input": {
        "pfs": {
           "repo": "A",
           "glob": "/*"
            }},
  "enable_stats": true
}
```

2\. create repo + pipeline

```code
pachctl create repo A && pachctl create pipeline -f single.json
```

3\. add “elephant" file to A

```code
echo "elephant" | p put file A@master:A1
```

4\. job output for “elephant"

```code
pachctl list job

ID                               PIPELINE STARTED      DURATION           RESTART PROGRESS  DL UL STATE
57f1c0b57ee54851a82e636d47a2e08c single   1 second ago Less than a second 0       1 + 0 / 1 9B 0B success
```

5\. check output for “elephant"

```code
p list file single@master

COMMIT                           NAME                              TYPE COMMITTED      SIZE
97ede16f756148cfa1825579713a71c8 /8FF6074D2D183C5BA4867D8FF6FC9099 file 44 seconds ago 0B
```

6\. append “rhino” to A1 to have a “altered” file

```code
echo "rhino" | p put file A@master:A1
```

7\. check job list to only find **a single datum** -\> technically there are two datums but “overwritten” since the input file is the same (i.e. path = /A1)?

```code
pachctl list job

ID                               PIPELINE STARTED            DURATION           RESTART PROGRESS  DL  UL STATE
9dd0417912be4b67a81257ab98a040ea single   2 seconds ago      Less than a second 0       1 + 0 / 1 15B 0B success
57f1c0b57ee54851a82e636d47a2e08c single   About a minute ago Less than a second 0       1 + 0 / 1 9B  0B success
```

8\. check output for “rhino” -\> dynamic output from “elephant” is overwritten!

```code
p list file single@master

COMMIT                           NAME                              TYPE COMMITTED          SIZE
594d644a66594f59ba196082f2edd81e /52CACA44579CE44C329A8E3EF859316F file About a minute ago 0B
```

**Environment?**:
```code
COMPONENT           VERSION
pachctl             1.9.0
pachd               1.9.0
```

**Comment by jdoliner** [comment]
This is the expected behavior, by appending to `A1` you're creating a new file and thus your output reflects only the results of running against that version of the datum, the results from running against the previous version of the datum aren't reflected in the output because that version no longer exists in head. Read more about this in our [Lifecycle of a datum docs.](https://docs.pachyderm.io/en/latest/fundamentals/lifecycle_of_a_datum.html)
