### ISSUE TITLE
Create a beginner's tutorial for the Dash UI

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#3915]
Create a beginner's tutorial for the Dash UI that is shown upon loading in hub:
Walk the user through the initial process of creating a repo, uploading their data, creating a pipeline, reiterating, processing the results.

**Comment by ysimonson** [comment]
@JoeyZwicker @svekars: re-prioritizing this based off conversations today. The short of it is that we think we'll need this in order for dash to be digestible for hub users, some of whom will have no prior experience using pachyderm.

**Comment by JoeyZwicker** [comment]
I think that this is pretty doable for end of Sept or early Oct (before we demo/present hub publicly). It might not be full "beginner tutorial in Hub" but we can certainly scope out some specifics to make sure first-time pachyderm users accessing things through Hub can have a good first experience. 

We can write the whole doc with current screenshots and then just replace all of those as the UI develops. There's a little bit of chicken-and-egg here, but it's manageable and something the customer team can probably handle managing to make sure Hub team doesn't have to spend extra work on this. @svekars does that seem ok to you or any major issues that I'm not thinking of?

**Comment by svekars** [comment]
Yes, @JoeZwicker, looks good.
