### ISSUE TITLE
How to install old version of Pachctl in Mac?

### ISSUE THREAD

**Issue by RobertWan91** [pachyderm/pachyderm#3922]
I am trying to install pachctl 1.8.6 in Mac. 

However, _**brew install pachyderm/tap/pachctl@1.8**_ gives me 1.8.7.

Not sure how I can get 1.8.6 in Mac. 

When I am trying brew install pachyderm/tap/pachctl@1.8.6. It shows me that nothing was found. Maybe from the source code? It will be appreciated if any help can be offered. Thanks.

**Comment by JoeyZwicker** [comment]
@RobertWan91 brew only is able to keep the latest version for each release (e.g. 1.8.x, 1.9.x, etc), but you can always just download the 1.8.6 binary from GH. https://github.com/pachyderm/pachyderm/releases/tag/v1.8.6
