### ISSUE TITLE
Cannot delete a file in the HEAD of a repo through an S3 gateway

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#3930]
**What happened?**:

Running `mc rm path-to-file` does not work.

I'm trying to test MinIO with Pachyderm. I was able to create and delete bucket by using the MinIO client. I was also able to upload a file to a Pachyderm repo.

```
    $ mc cp test.csv local/master.raw_data/test.csv
    test.csv:                  62 B / 62 B  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 206 B/s 0s
```

However, when I try to delete that file I get an error that it's not supported.
```
$ mc ls local/master.raw_data
    [2019-07-19 12:11:37 PDT]  2.6MiB github_issues_medium.csv
    [2019-07-19 12:11:37 PDT]     62B test.csv
```

As far as I understand, this suppose to work:

```
$ mc rm local/master.raw_data/test.csv
Removing `local/master.raw_data/test.csv`.
mc: <ERROR> Failed to remove `local/master.raw_data/test.csv`. This functionality is not implemented in the pachyderm s3gateway.
```
 But it does not.

**What you expected to happen?**:
The `test.csv` file to be delete from the repo.
**How to reproduce it (as minimally and precisely as possible)?**:
1. Install MinIO client and server.
2. Deploy Pachyderm.
3. Create a repo.
4. Put a file to the repo by using `mc cp path-to-file` command.
5. Try to delete the file by using `mc rm path-to-file`
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Pachyderm CLI and pachd server version (use `pachctl version`):
$ pachctl version
COMPONENT           VERSION
pachctl             1.9.0
pachd               1.9.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
$ minikube version
minikube version: v0.35.0
- OS (e.g. from /etc/os-release):
macOS
- Others:

**Comment by svekars** [comment]
@ysimonson ^^

**Comment by svekars** [comment]
It seems that for AWS, it does work:

```$ aws --endpoint-url http://localhost:30600/ s3 rm s3://master.raw_data/test.csv
delete: s3://master.raw_data/test.csv```

```$ aws --endpoint-url http://localhost:30600/ s3 ls s3://master.raw_data
2019-07-26 12:20:44    2685061 github_issues_medium.csv```

**Comment by JoeyZwicker** [comment]
So it works for aws CLI but not Minio?

**Comment by svekars** [comment]
Yes.

**Comment by ysimonson** [comment]
I wasn't able to repro this issue:

```
$ mc rm s3g/master.minio
Removing `s3g/master.minio`.
$ mc --version
mc version RELEASE.2019-08-07T23-14-43Z
```

**Comment by ysimonson** [comment]
This is because minio's client issues multi-object delete, even when a single file is being deleted. Verbose output indicates it's hitting the `delete` subresource:

```
Removing `s3g/master.minio/README.md`.
mc: <DEBUG> POST /master.minio/?delete= HTTP/1.1
Host: localhost:30600
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.32 mc/2019-08-07T23:14:43Z
Content-Length: 73
Content-Md5: ZvsRygom2wjgQGVrmjgTeA==
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 232
Content-Type: application/xml
Date: Mon, 12 Aug 2019 14:40:25 GMT
X-Amz-Id-2: f8a7561b-6573-4224-9161-94c04018a90e
X-Amz-Request-Id: f8a7561b-6573-4224-9161-94c04018a90e

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>This functionality is not implemented.</Message><Resource>/master.minio/</Resource><RequestId>f8a7561b-6573-4224-9161-94c04018a90e</RequestId></Error>mc: <DEBUG> Response Time:  12.33075ms
```
