### ISSUE TITLE
panic: slice bounds out of range when cmd not specified in pipeline

### ISSUE THREAD

**Issue by danielefranceschi** [pachyderm/pachyderm#3932]
**What happened?**:
```
panic: runtime error: slice bounds out of range
goroutine 170 [running]:
github.com/pachyderm/pachyderm/src/server/worker.(*APIServer).runUserCode(0xc000270240, 0x21d4d40, 0xc000163e40, 0xc0004f8380, 0xc00013b800, 0xc3, 0x180, 0xc000625270, 0x0, 0x0, ...)
src/github.com/pachyderm/pachyderm/src/server/worker/api_server.go:645 +0xbff
```

**What you expected to happen?**:
To use a self-configuring (via ENV) custom docker image with a correct ENTRYPOINT/CMD as a pipeline step without rewriting its command inside the pipeline descriptor.

**How to reproduce it (as minimally and precisely as possible)?**:
Create a pipeline without `transform.cmd`.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.15.0
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.0
- Cloud provider: on-premise (1Master+3Worker, kubeadm)
- OS (e.g. from /etc/os-release): Centos 7.4
- Others: Docker 18.09.06

**Comment by JoeyZwicker** [comment]
@danielefranceschi Sorry you're hitting this, it should be a pretty simple fix for us to make sure we don't panic in this scenario. I'll double check with eng to see if we are able to support not having a transform.cmd field at all or if we should just error more gracefully.

**Comment by danielefranceschi** [comment]
BTW, browsing in your code and digging in the generated YAMLs, I _probably understood_ why the `transform.cmd` is eventually **required**.  
The main process of the `user` container in the pod is the `init`-injected `pachd`, that execs the `transform.cmd` stuff when a datum payload becomes available.  
I don't think that analyzing the supplied container image to infer ENTRYPOINT and CMD is possible in a K8S environment; this brings to the `transform.cmd` obligatoriness.

IMHO (I'm not a gopher) the feasible options could be:
- playing with [entrypoints and cmd](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes) to implicitly pass the container default CMD to `pachd`
- reject pipeline when `transform.cmd` is null

Thanks again ⭐️
