### ISSUE TITLE
Unable to recover from pipeline container failure

### ISSUE THREAD

**Issue by mrene** [pachyderm/pachyderm#3934]
I'm performing the following test case in order to validate how pachyderm recovers from spout failures:

- Create a pipeline with no inputs and `{ "spout": { "overwrite": true } }`
- Trigger a condition that causes the pod to repeatedly fail
- Wait until it enters `CrashLoopBackoff`
- Stop the pipeline
- Update it with a new container
- Start the pipeline

At this point, the pod is not re-created and the pipeline stays in an error state forever.

inspect pipeline shows `stopped: false` and compains that the underlying `replicationcontroller` doesn't exist

pachd logs at https://gist.github.com/mrene/6f31d3b0755e674f47aee1405ba5b398
pachd image `pachyderm/pachd:1.9.0` (I did bump it to `1.9.1` while in the failure state with no changes in behaviour)

**Comment by JoeyZwicker** [comment]
We have a fix coming in 1.9.2 that should make it so that after you update the pipeline, it'll definitely come back in that case. But in general, once a pipeline has been put into state: failure (which sometimes can happen for transient reasons like not being able to pull the container image), you'll need to run `update pipeline` for it to try again. 

We could consider having `start pipeline` do this too perhaps? @msteffen

**Comment by housejester** [comment]
fwiw, i get this behavior even when not due to the pipeline failing on its own. If i try to update a stopped pipeline, the pipeline moves to a 'failed' state. If i take the `edges.json` example pipeline and do the following:
```
$ pachctl create pipeline -f /tmp/edges.json
$ pachctl list pipeline
NAME  VERSION INPUT     CREATED       STATE / LAST JOB
edges 1       images:/* 8 seconds ago running / starting
 
# update while running is fine:
$ pachctl update pipeline -f /tmp/edges.json
$ pachctl list pipeline
NAME  VERSION INPUT     CREATED       STATE / LAST JOB
edges 2       images:/* 2 seconds ago running / starting

# update after stopping causes failure
$ pachctl stop pipeline edges
$ pachctl list pipeline
NAME  VERSION INPUT     CREATED        STATE / LAST JOB
edges 2       images:/* 17 seconds ago paused / starting
$ pachctl update pipeline -f /tmp/edges.json
$ pachctl list pipeline
NAME  VERSION INPUT     CREATED       STATE / LAST JOB
edges 3       images:/* 2 seconds ago failure / starting
$ pachctl logs -p edges
no pods belonging to the rc "pipeline-edges-v3" were found
```

**Comment by JoeyZwicker** [comment]
Thanks @housejester. The update fix we have in in final PR review right now addresses this issue too. Essentially, what's going on is when you stop the pipeline, we remove the RC, but then when updating it, we don't seem to recreate it correctly is all circumstances. 

@msteffen might be able to shed more light, but we're just about the merge this in and cut 1.9.2

**Comment by msteffen** [comment]
I recently tried this reproduction on a 1.9.2 cluster and failed to reproduce the issue. 
@housejester If you have time, is there any chance you'd be willing to upgrade your cluster to 1.9.2 and let us know if you still see this issue?

Here's a (lightly redacted) transcript of my repro for reference:
```
$ pc create pipeline -f ./examples/opencv/edges.json 
$ pc list pipeline
NAME  VERSION INPUT     CREATED        STATE / LAST JOB   
edges 1       images:/* 35 seconds ago running / starting 

$ pc update pipeline -f ./examples/opencv/edges.json 
$ pc list pipeline
NAME  VERSION INPUT     CREATED       STATE / LAST JOB   
edges 2       images:/* 2 seconds ago running / starting 
$ pc list pipeline
NAME  VERSION INPUT     CREATED        STATE / LAST JOB 
edges 2       images:/* 44 seconds ago running / success 

$ pc stop pipeline edges
$ pc list pipeline
NAME  VERSION INPUT     CREATED        STATE / LAST JOB 
edges 2       images:/* 44 seconds ago paused / success 

$ pc update pipeline -f ./examples/opencv/edges.json 
$ pc list pipeline
NAME  VERSION INPUT     CREATED       STATE / LAST JOB 
edges 3       images:/* 2 seconds ago paused / success 

$ pc start pipeline edges
$ pc list job --history=all -p edges
ID                               PIPELINE STARTED            DURATION           RESTART PROGRESS  DL       UL       STATE   
259d7e76be3743899e2ceee477362619 edges    21 seconds ago     Less than a second 0       0 + 1 / 1 0B       0B       success 
1e65db445c16498b9ddbac2628e3fea1 edges    22 seconds ago     Less than a second 0       0 + 1 / 1 0B       0B       success 
9250b20bd9e147b18aeee14fb2368ac0 edges    About a minute ago 21 seconds         0       0 + 1 / 1 0B       0B       success 
392b2298ec5e40ff91c92ddb927c8ac5 edges    About a minute ago Less than a second 0       1 + 0 / 1 57.27KiB 22.22KiB success 
```

**Comment by housejester** [comment]
yep, tested on friday as well, and works on 1.9.2. thanks!
