### ISSUE TITLE
Describe Pachctl contexts in the user documentation

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#3946]
References:
- https://github.com/pachyderm/pachyderm/pull/3786
- https://github.com/pachyderm/pachyderm/issues/3774
- https://github.com/pachyderm/pachyderm/issues/3036

Give a broader overview of what Pachyderm contexts are and how to use them.

**Comment by JoeyZwicker** [comment]
Is your plan for this to be a section of the "connecting to you cluster" doc or its own doc just for contexts?

**Comment by svekars** [comment]
I think it this should be in the connecting to "your cluster section".

**Comment by svekars** [comment]
https://github.com/pachyderm/pachyderm/pull/3981
