### ISSUE TITLE
Unable to deploy Pachyderm

### ISSUE THREAD

**Issue by elsonrodriguez** [pachyderm/pachyderm#397]
Following the example from the readme, I issued:
```
kubectl create -f https://pachyderm.io/manifest.json
```

However the pachd pods didn't come up:
```
$ kubectl get pods
NAME                      READY     STATUS             RESTARTS   AGE
etcd-nw6qs                1/1       Running            0          16m
pachd-tiu8f               0/1       CrashLoopBackOff   8          16m
pachd-yhg0z               0/1       CrashLoopBackOff   8          16m
pachyderm-init-db-wkxcm   0/1       CrashLoopBackOff   8          16m
rethink-31ppb             1/1       Running            0          16m
```

Logs show:
```
100: Key not found (/cluster-id) [2]
```
For both pachd and pachyderm-init.

This was done on AWS via kube-up, on this version of kubernetes:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

**Comment by jdoliner** [comment]
Hey @elsonrodriguez, really sorry you ran into this. I just checked the manifest online and realized that somehow we wound up with an older version of the manifest hosted on our site. I'm going to update it right now so this should be resolved shortly.

**Comment by jdoliner** [comment]
Just pushed the correct version of the manifest, it may take a few minutes for it propagate through CDNs and such. Please let us know if this doesn't resolve the issue.

**Comment by elsonrodriguez** [comment]
That did it.

Thanks!
