### ISSUE TITLE
pachctl mount is very slow and unstable

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3982]
**What happened?**:

Mounted a pachyderm repo and response to `ls` and other files commands were so slow as to render it unusable.  
The blocking call to `pachctl mount` crashed with no obvious errors in the log
`pachctl list file` was zippy enough to be usable.

**What you expected to happen?**:

Expected it to be usable.

**How to reproduce it (as minimally and precisely as possible)?**:

Mounted a repo@branch with the debug flag.
Observed the slowness in the channel
See logs at the end of this report.

**Anything else we need to know?**:

See logs at the end of this report

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): On-prem K8s deploy with SwiftStack object store
- OS (e.g. from /etc/os-release): MacOS
- Others:

$ pachctl mount ./dpm -c data-pump-all@master -d
2019/07/03 13:22:27 Dispatch 2: INIT, NodeId: 0. data: {7.19 Ra 0x100000 XTIMES,VOL_RENAME,CASE_INSENSITIVE,ATOMIC_O_TRUNC,0x18000000}
2019/07/03 13:22:27 Serialize 2: INIT code: OK value: {7.8 Ra 0x100000  0/0 Wr 0x10000 Tg 0x0}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: ACCESS, NodeId: 1. data: {}
2019/07/03 13:22:27 Serialize 3: ACCESS code: 78=function not implemented value:
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Dispatch 3: STATFS, NodeId: 1.
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Serialize 3: STATFS code: OK value: {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 3: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 2: GETATTR, NodeId: 1. data:
2019/07/03 13:22:27 Serialize 2: GETATTR code: OK value: {A0.000000000 {M040555 SZ=0 L=1 0:0 0 0:1 A 0.000000000 M 0.000000000 C 0.000000000}}
2019/07/03 13:22:27 Dispatch 3...

**Comment by jdoliner** [comment]
`pachctl mount` is very fast for me:

```
time ls pfs/images 
46Q8nDz.jpg  8MN9Kg0.jpg  g2QnNqa.jpg  Togu2RY.jpg  w7RVTsv.jpg
ls --color=tty pfs/images  0.00s user 0.00s system 2% cpu 0.171 total
```

I have a feeling the slowness you're seeing is coming from OSX fuse, or official stance is that we only support Linux FUSE. That's definitely a pain, and in a perfect world we'd support OSX well, but I'm not sure what we could do to make this better, this is the code path that lists files in a directory:

```golang
		commit, err := fs.commit(r.Name)
		if err != nil {
			return nil, toStatus(err)
		}
		if commit == "" {
			// master branch has no head, so we report an empty dir
			return result, fuse.OK
		}
		if err := fs.c.ListFileF(r.Name, commit, "", 0, func(fi *pfs.FileInfo) error {
			result = append(result, fileDirEntry(fi))
			return nil
		}); err != nil {
			return nil, toStatus(err)
		}
```

There's not much to change there, it's just doing the `ListFile` (which is snappy) accumulating the results, and returning them. I suspect that this means that most of the time you're seeing here is actually being spent in the kernel / FUSE implementation, rather than in our code. I'm going to close this but feel free to reopen if you think I missed something here and there's a way we could solve this.

**Comment by pappasilenus** [comment]
There is an alternative to this on macOS & windows: use the S3 gateway and something like [Mountain Duck](https://mountainduck.io/), which allows you to mount S3 resources as macOS and windows file shares.
