### ISSUE TITLE
recursive put files from aws s3 buckets are somewhat slow & consistently fail

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3984]
**What happened?**:

A recursive put of 1100 files from an S3 bucket consistently fails with no errors in the log and no files transferrred.

**What you expected to happen?**:

Successful transfer of files from S3.

**How to reproduce it (as minimally and precisely as possible)?**:
created a Pachyderm cluster in AWS with these characteristics:

```
export CLUSTER_NAME=s3-recursion-repro
export BUCKET_NAME=${CLUSTER_NAME}-bucket
export NODEGROUP_NAME=${CLUSTER_NAME}-nodegroup
export STORAGE_SIZE=10
export AWS_REGION=us-west-2
export IAM_ROLE=<role redacted>
export MACHINE_TYPE="m5.xlarge"
export K8S_VERSION=1.13
export SOURCE_BUCKET_NAME=${CLUSTER_NAME}-source-bucket
export DEFAULT_NODES=3
export MIN_NODES=3
export MAX_NODES=6

#create the cluster 
eksctl create cluster --name ${CLUSTER_NAME} --version ${K8S_VERSION}  --nodegroup-name ${NODEGROUP_NAME} --node-type ${MACHINE_TYPE} --nodes ${DEFAULT_NODES} --nodes-min ${MIN_NODES} --nodes-max ${MAX_NODES} --node-ami auto

#create the bucket
aws s3api create-bucket --bucket ${BUCKET_NAME} --region ${AWS_REGION} --create-bucket-configuration LocationConstraint=${AWS_REGION}

#deploy pachyderm
pachctl deploy amazon ${BUCKET_NAME} ${AWS_REGION} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --iam-role $IAM_ROLE

#create the bucket to copy from
aws s3api create-bucket --bucket ${SOURCE_BUCKET_NAME} --region ${AWS_REGION} --create-bucket-configuration LocationConstraint=${AWS_REGION}

# omitted: steps to properly set up roles to access the buckets from pachyderm
# available on request
# This cluster is up and running in our AWS account

# create test data
for file in $(seq 0 1000); do
    dd if=/dev/urandom bs=50M count=1 of=/tmp/test.bin
    aws s3 cp /tmp/test.bin s3://${SOURCE_BUCKET_NAME}/${file}.bin
done

for file in $(seq 1100 5000); do
    dd if=/dev/urandom bs=50M count=1 of=/tmp/test.bin
    aws s3 cp /tmp/test.bin s3://${SOURCE_BUCKET_NAME}/data/${file}.bin
done

pachctl create repo testdata

time pachctl put file testdata@master -r -f s3://${SOURCE_BUCKET_NAME}/
```

This consistently fails for 1000 or 1100 fiies.  It succeeded with 314, but at a speed of about 100MBS.  pachd logs attached for two failures.

**Anything else we need to know?**:

While I'm running this through port-forwarding, users in the channel have had this same issue with direct ingress using PACHD_ADDRESS.  Given that the download is direct from the S3 url, no data is passing through port-forwarding, only the command.  The instances are set up with 5GB networking, so the transfer from S3 for 55GiB of data should be pretty fast. 

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.13
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): macos and ubuntu 14.04 
- Others:
[pachdlogs.txt for failure of 1100 files with larger instance types](https://github.com/pachyderm/pachyderm/files/3479462/pachdlogs.txt)
[logs.txt for failure with 1000 files, using smaller instance types](https://github.com/pachyderm/pachyderm/files/3479464/logs.txt)

**Comment by pappasilenus** [comment]
@JoeyZwicker The issue we discussed today.

**Comment by abramovi** [comment]
Just want to add - issue reproduce also when dir is local and not on s3
`pachctl put file -r repo@master:/ -f .`
