### ISSUE TITLE
Unable to create pipeline from fruit stand example

### ISSUE THREAD

**Issue by elsonrodriguez** [pachyderm/pachyderm#399]
When running through the fruit stand example:
```
$ pachctl create-pipeline -f examples/fruit_stand/pipeline.json
$ pachctl  list-job
ID                                 OUTPUT                                    STATE               
406f8b9f09d27023864d5d78275ce0c2   filter/70cf20f005a5426a90598a6e40ef0b3a   running    
$ pachctl  get-logs 406f8b9f09d27023864d5d78275ce0c2
rpc error: code = 2 desc = container "user" in pod "406f8b9f09d27023864d5d78275ce0c2-oz77b" is waiting to start: trying and failing to pull image
```

From the job's events:

```
  42m		27s		13	{kubelet eu-central-1.compute.internal}	spec.containers{user}	Warning		Failed		Failed to pull image "fruit_stand": Error: image library/fruit_stand:latest not found
```
Suggesting that the fruit_stand image be built and uploaded on Docker hub (maybe pachyderm/fruit_stand), and have that be hardcoded into the pipeline.json

**Comment by sjezewski** [comment]
Hi there!

Sorry you ran into this. Yes - we need to either update the docs or provide that image on dockerhub as you suggest.

If you run `make docker-build-fruitstand` it'll build the image locally. However, if your cluster already has some repos created, it may be easiest to reset your cluster by doing the following:

```shell
make clean-launch
make clean-launch-kube
make launch-kube
make launch
```

**Comment by elsonrodriguez** [comment]
sent in a PR for this.
