### ISSUE TITLE
[DOC] recursive put file from s3 fails if s3 folders created in AWS console UI

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3994]
**What happened?**:

Created two-level deep hierarchy of files and folders in S3 using the AWS S3 console. It looks like this:

```
$ aws s3 ls --recursive s3://s3-recursion-repro-source-bucket/test_folder
2019-08-12 09:36:01          0 test_folder/
2019-08-12 09:36:33          0 test_folder/csv/
2019-08-12 09:37:10     113487 test_folder/csv/slack-pachyderm-users-members 2019-07-23.csv
2019-08-12 09:37:10     115877 test_folder/csv/slack-pachyderm-users-members 20190807.csv
2019-08-12 09:37:10     115341 test_folder/csv/slack-pachyderm-users-members 201908085.csv
2019-08-12 09:37:10     116180 test_folder/csv/slack-pachyderm-users-members 20190809.csv
2019-08-12 09:37:10     111901 test_folder/csv/slack-pachyderm-users-members.csv
2019-08-12 09:37:11     111404 test_folder/csv/slack-pachyderm-users-members20190708.csv
2019-08-12 09:37:11   10484681 test_folder/csv/swift_stack_pachyderm_logs_7days.csv
```

Then attempted a recursive put file and it failed.
```
pachctl put file test_csv@master -r -f s3://s3-recursion-repro-source-bucket/test_folder/
could not put file at "/test_folder"; a file of type directory is already there
```

**What you expected to happen?**:

I expected the files to be recursively copied with no errors.

**Note**: _files which have been recursively uploaded to S3 using aws cli can be put into Pachyderm with no problems.  See below._

```
$ ls -R test_folder
ls -R test_folder/
test_folder/:
temporary_folder

test_folder/temporary_folder:
csv

test_folder/temporary_folder/csv:
'slack-pachyderm-users-members 2019-07-23.csv'	 slack-pachyderm-users-members.csv
'slack-pachyderm-users-members 20190807.csv'	 slack-pachyderm-users-members20190708.csv
'slack-pachyderm-users-members 201908085.csv'	 swift_stack_pachyderm_logs_7days.csv
'slack-pachyderm-users-members 20190809.csv'

$ aws s3 cp --recursive test_folder/ s3://s3-recursion-repro-source-bucket/

$  pachctl put file test_csv@master -r -f s3://s3-recursion-repro-source-bucket/temporary_folder/

$ pachctl list file test_csv@master:/temporary_folder/csv
NAME                                                               TYPE SIZE     
/temporary_folder/csv/slack-pachyderm-users-members 2019-07-23.csv file 110.8KiB 
/temporary_folder/csv/slack-pachyderm-users-members 20190807.csv   file 113.2KiB 
/temporary_folder/csv/slack-pachyderm-users-members 201908085.csv  file 112.6KiB 
/temporary_folder/csv/slack-pachyderm-users-members 20190809.csv   file 113.5KiB 
/temporary_folder/csv/slack-pachyderm-users-members.csv            file 109.3KiB 
/temporary_folder/csv/slack-pachyderm-users-members20190708.csv    file 108.8KiB 
/temporary_folder/csv/swift_stack_pachyderm_logs_7days.csv         file 9.999MiB 
```
**How to reproduce it (as minimally and precisely as possible)?**:
1. Create an S3 bucket.  
2. Create a Pachyderm instance and create a repo in it.
3. Ensure your Pachyderm instance has access to the bucket you created in step 1.
4. Via the AWS console web UI, create a folder and then create a folder within it,  such as `temporary_folder`, `temporary_folder/csv/`
5. Upload some files to the leaf folder via the web ui (that is, upload to `temporary_folder/csv/`)
6. Try to put those files in Pachyderm via a recursive put at the first folder level, not the root bucket level.  That is, something like `pachctl put file test_csv@master -r -f s
3://s3-recursion-repro-source-bucket/test_folder/`
7. Watch it fail with an error like `could not put file at "/test_folder"; a file of type directory is already there`
8. Create another, similarly-structured folder hierarchy using the aws cli tools. Something like, `aws s3 cp --recursive test_folder/ s3://s3-recursion-repro-source-bucket/`, assuming that `test_folder` contains a structure like this:
```
test_folder/:
temporary_folder

test_folder/temporary_folder:
csv

test_folder/temporary_folder/csv:
'slack-pachyderm-users-members 2019-07-23.csv'	 slack-pachyderm-users-members.csv
'slack-pachyderm-users-members 20190807.csv'	 slack-pachyderm-users-members20190708.csv
'slack-pachyderm-users-members 201908085.csv'	 swift_stack_pachyderm_logs_7days.csv
'slack-pachyderm-users-members 20190809.csv'
```
9. Do a recursive put from that folder, something like `pachctl put file test_csv@master -r -f s
3://s3-recursion-repro-source-bucket/temporary_folder/`
10. Watch it succeed. 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION             
pachctl             1.9.3               
pachd               1.9.2-18f20c6cfebc398466f8363c725bcf050babd633 
```
(This is identical to v.1.9.2 but contains the recursive put fixes to https://github.com/pachyderm/pachyderm/issues/3984 by @brycemcanally )
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): EKS
- OS (e.g. from /etc/os-release): macOS 10.14.6
- Others:

**Comment by ysimonson** [comment]
I bet this has something to do with the idiosyncratic and varied ways s3 represents directories, i.e. the dashboard crates a 0B object for directories, and the CLI doesn't create directories.

**Comment by jdoliner** [comment]
I think this is unfortunately the "correct" behavior here, as bad as it is. S3 doesn't really have a notion of directories afaik, that means that it's permissible to have an object called `foo` and an object called `foo/bar`, this isn't permissible in filesystems, because a file called `foo/bar` implies a directory called `foo`, which means there can't also be a file called `foo`. Pfs implements the filesystem behavior of explicit directories that conflict with normal files of the same name, this gets a bit awkward when trying to map s3 objects into it, but I think the filesystem semantics are the right choice for us because 1) they're generally more familiar and less confusing to people 2) pipelines need to be able to manifest pfs filesystems as actual linux filesystems, so we'd have a whole bunch of new error cases to handle if we didn't enforce those semantics in pfs 3) layouts like this are pretty rare in object storage, to the point where I'm tempted to say there isn't really a legit use case for them. So all in all I don't think it makes sense for us to make PFS support this.

**Comment by JoeyZwicker** [comment]
@svekars @pappasilenus While definitely low priority, we should eventually document this known behavior for S3 objects created through the AWS console. 

Turning this into a Docs issue instead.

**Comment by chainlink** [comment]
This is an interesting case. pulling in a ton of files is almost a 'job' in itself. ie. it could be a long very running command

**Comment by echohack** [comment]
Thank you everyone for your comments on this issue. We've documented it in our support systems and will be closing this issue out.
