### ISSUE TITLE
create tech note for AWS recursive put workaround

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3995]
**What is the goal / desired outcome?**

A way to document for users the workaround of using the aws cli to address a possible issue with the aws console UI when doing recursive puts of files.

See issue https://github.com/pachyderm/pachyderm/issues/3994 for details.

**If there is a way to accomplish this today via workaround, what does that require?**

You could add a note to the documentation for the command or in Read The Docs for "getting data into pachyderm", but that seems like it would clutter up the documentation with a bunch of workarounds, eventually.

**(Optional) What is your proposal for a feature to solve this?**
A dedicated tech notes area for workarounds such as this, which is groomed regularly as the workarounds are obsoleted or improved.

**Comment by mindthevirt** [comment]
This will be addressed as part of 3994 which is going to be covered in a FAQ/KBA.
