### ISSUE TITLE
deploy custom help incorrect for object-store arguments

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3996]
**What happened?**:

`pachctl deploy custom help` gives this advice:

```
      --object-store string      (required) Backend providing an object-storage API to pachyderm. One of: s3, gcs, or azure-blob. (default "s3")
```

When it is run with anything other than `s3` as an argument, it gives the following error:

```
Did not recognize the choice of object-store
```

This is verified as  what the code will do by inspecting [assets.go](https://github.com/pachyderm/pachyderm/blob/2d147967671bb8ee283b89c71655d4cfc6566294/src/server/pkg/deploy/assets/assets.go#L1477)

**What you expected to happen?**:

The help should match what the code will accept.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Run `pachctl deploy custom help` and verify the help for the `--object-store` flag.
2  Run either of the following and watch it error out.
```
pachctl deploy custom --persistent-disk azure --object-store gcs foobar 10  foobar foobar 10  foobar  localhost:9000 --dynamic-etcd-nodes 1 --dry-run

pachctl deploy custom --persistent-disk azure --object-store azure-blob foobar 10  foobar foobar 10  foobar  localhost:9000 --dynamic-etcd-nodes 1 --dry-run
```
**Anything else we need to know?**:
The  deploy custom commands are a maze of tiny passages, all alike.

**Environment?**:
- Kubernetes version (use `kubectl version`): N/A
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): custom
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
@pappasilenus is this just a change requirement in the help docs or something that actually need to be fixed in the server? 

@svekars should probably (if she's not already) get to the point where she can update those help docs as well, even though that involves direct commits to the codebase I think. How easy or hard would this be?

**Comment by svekars** [comment]
@JoeyZwicker it shouldn't be difficult, I just didn't have time to look into it yet.

**Comment by JoeyZwicker** [comment]
Im going to label this as docs so engineering does need to tackle it. Feel free to change the labels if we need eng help

**Comment by szeitlin** [comment]
we're also getting bitten by this.

**Comment by mindthevirt** [comment]
This is no longer relevant since `pachctl deploy` has been deprecated and Helm is the new way to deploy Pachyderm.
