### ISSUE TITLE
Pipeline jobs are created in the Default namespace, instead of Pachyderm's namespace

### ISSUE THREAD

**Issue by elsonrodriguez** [pachyderm/pachyderm#400]
When running through the fruit stand example, the pipline creates a job in the `default` namespace, instead of the `pachyderm` namespace I deployed pachyderm to.

If a user is restricted to a certain namespace, this may affect their ability to interact with the jobs, assuming they can create them.

**Comment by jdoliner** [comment]
This shouldn't be too hard to add. Question: is it possible to detect what namespace we were deployed in? If so we can just do the right thing. If not then I guess we'll have to take an environment variable to specify the namespace we should deploy in.

Either way shouldn't be too hard to get this in for 1.1.

**Comment by elsonrodriguez** [comment]
From the client side there's no guaranteed way.

Safest way is to get the namespace from a k8s object. The Pachd pod that is processing the request is a good bet.

**Comment by derekchiang** [comment]
This seems to be what we want:

https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/downward-api.md

**Comment by jdoliner** [comment]
> The following information is available to a Pod through the downward API:
> - The pod's name
> - The pod's namespace

Sounds like that would do it.

**Comment by derekchiang** [comment]
@jdoliner https://github.com/pachyderm/pachyderm/pull/451
