### ISSUE TITLE
Parameter to turn off TLS/HTTPS for amazon S3 client in local/on premise deployment

### ISSUE THREAD

**Issue by OliverWalter** [pachyderm/pachyderm#4007]
**What is the goal / desired outcome?**

Parameter to turn off TLS/HTTPS when using the amazon s3 client for a local deployment with with local minio storage. TLS/HTTPS is enabled by default which prevents PACHD from starting with a non TLS/HTTPS minio deployment.

**If there is a way to accomplish this today via workaround, what does that require?**

- Switch back to MINIO client (not desired an not default)
- Get a valid SSL certificate with valid certification chain (not feasible in this setup)
- Run though proxy with SSL encryption (not desired for local deployment due to added overhaed)

**Environment?**:
- Pachyderm CLI version (use `pachctl version`): 1.9.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local deployment with dockerized k8s.

**Comment by ppaanngggg** [comment]
It works to set CUSTOM_POINT=http://{minio:9000}

**Comment by OliverWalter** [comment]
Thanks -  this works (without the curly brackets though)

I'm using the following options for a custom deployment:

`--object-store s3 pachyderm-s3 10 ${S3_STORAGE_BUCKET} ${S3_STORAGE_USERNAME} ${S3_STORAGE_PASSWORD} http://myminio:9000`
