### ISSUE TITLE
Support LoadBalancer Services for pachd

### ISSUE THREAD

**Issue by elsonrodriguez** [pachyderm/pachyderm#401]
Not sure how possible this is, but when using a manifest modified to produce a LoadBalancer service for Pachd: https://gist.github.com/elsonrodriguez/a7c45374753e83536d293ab5701b4c6a

I got this error message:

```
$ pachctl list-pipeline
2016/05/10 19:15:19 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp xxxx:650: i/o timeout"; Reconnecting to "xxxx.elb.amazonaws.com:650"
```

**Comment by jdoliner** [comment]
Hmm I don't know much about how elb load balencers work. Are they generally compatible with grpc?

**Comment by elsonrodriguez** [comment]
The ELB that was provisioned is just raw TCP supposedly. Going from port 650 to 30650 on the nodes (the nodeport).

**Comment by sjezewski** [comment]
Newer versions of k8s have support for LB w different cloud providers. We have an issue to document this further: https://github.com/pachyderm/pachyderm/issues/2684
