### ISSUE TITLE
Job hangs on error when in standby

### ISSUE THREAD

**Issue by rmarkel-neon** [pachyderm/pachyderm#4010]
**What happened?**:
The Pachyderm job hung with an open commit and the pachctl logs --job=<job id> also hung when the pipeline specification had standby set to true and the job failed (in this case due to the container python command not being able to find a missing module).

**What you expected to happen?**:
The job should finish with an error status and logs for the job should always be returned by the pachctl logs command.

**How to reproduce it (as minimally and precisely as possible)?**:
Set standby to true in a pipeline specification. Deploy a container with an error (such as a missing python module). Create the pipeline. It is unknown if this is sufficient to reproduce the error or other conditions also need to be present. Fixing the Dockerfile, deleting the pipeline, removing standby from the pipeline specification, and redeploying resulted in the job running successfully.

**Anything else we need to know?**:
The pipeline causing the error has two inputs.

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:56:58Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.9.3               
pachd               1.9.3-6221e9ed57a10b39d363e0e97cdd6e4e41796af2   

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
ECS

- OS (e.g. from /etc/os-release):

- Others:

**Comment by nitinjainsj** [comment]
We were not able to reproduce it successfully. With 1.11 release the job logic was re-worked.

Please reopen, with repro steps, if this is still an issue.
