### ISSUE TITLE
Describe how to configure ingress and egress for a local deployment

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4014]
To be able to ingress files from external S3 storage,  it has to use the same storage secret as Pachyderm does for the object store Pachyderm uses. You don’t need the S3 gateway to get data into Pachyderm from an S3 datasource.   pachctl put file can access s3:// urls just fine if Pachyderm is configured correctly to access the endpoint that the bucket is served by. 

Therefore, you need to deploy a Kubernetes Secret with the secret that Pachyderm uses to access object storage.

The sequence of steps:

1. Deploy Pachyderm by running `pachctl deploy local.`
2. Create the Secret manifest (example below)
    For each field in the template that tells you it needs base64-encoded data, run a unix command like `echo  -n '<secret>'  | base64`.
3. Apply the secret manifest with `kubectl apply -f <path/to/your/minio-secret-manifest.json>`
4. Pachd restarts automatically or you might need to delete the existing pod so Kubernetes starts a new one.
5. Verify that it's working by running `pachctl put file repo@branch:file -f s3://bucket/path/to/file`

Example manifest:
```
{
	"kind": "Secret",
	"apiVersion": "v1",
	"metadata": {
		"name": "pachyderm-storage-secret",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "pachyderm-storage-secret",
			"suite": "pachyderm"
		}
	},
	"data": {
		"minio-bucket": "<base64 encoded bucket name without s3:// prefix or / suffix>",
		"minio-endpoint": "<base64 encoded ip-address:port or hostname:port",
		"minio-id": "<base64-encoded userid>",
		"minio-secret": "<base64-encoded secret>",
		"minio-secure": "MA==",
		"minio-signature": "MA=="
	}
}
```

**Comment by svekars** [comment]
@pappasilenus does this look correct?

**Comment by pappasilenus** [comment]
I think the  command in step 5 should be

`pachctl put file repo@branch:file -f s3://bucket/path/to/file`

Add this warning, too:

**NOTE** You can only do this to a cluster deployed locally.  This storage secret is used by Pachyderm to access object storage in production clusters, and if you change it to something other than what you deployed Pachyderm with, it will break your Pachyderm cluster.  In that case, you can egress to buckets on the same storage provider that use the same credentials that you deployed Pachyderm with.

**Comment by pappasilenus** [comment]
Note that since we changed to the amazon driver being the default, we need to change this to a parameterized Amazon storage secret.  This may preclude using plain old HTTP and S3v2 signatures.  Here's what the parameterized amazon secret looks like:

```
{
	"kind": "Secret",
	"apiVersion": "v1",
	"metadata": {
		"name": "pachyderm-storage-secret",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "pachyderm-storage-secret",
			"suite": "pachyderm"
		}
	},
	"data": {
	    "amazon-bucket": "<base64 encoded bucket name without s3:// prefix or / suffix>",
	    "amazon-distribution": "",
	    "amazon-id": "<base64-encoded userid>",
	    "amazon-region": "<base64-encoded region, use us-east-1 by default (dXMtZWFzdC0x)>",
	    "amazon-secret": "<base64-encoded secret>",
	    "amazon-token": "",
	    "custom-endpoint": "<OPTIONAL base64 encoded ip-address:port or hostname:port>"
	}
}
```
You only need to set the custom endpoint if you're using an object store other than AWS.

**Comment by mindthevirt** [comment]
This issue is blocked by https://github.com/pachyderm/pachyderm/issues/4609

**Comment by mindthevirt** [comment]
Closing this issue as we'll document this feature as part of the implementation work on #4609
