### ISSUE TITLE
[DOC] GKE docs formatting and version number fix

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#4022]
In http://docs.pachyderm.io/en/latest/deployment/google_cloud_platform.html it says:

**Important Note: You must create the Kubernetes cluster via the gcloud command-line tool rather than the Google Cloud Console, as it’s currently only possible to grant the storage-rw scope via the command-line tool. ** Also note, you should deploy a 1.8.x cluster if possible to take full advantage of Pachyderm’s latest features.

The formatting/sizing on the first sentence is weird. I assume "note" should be the part in bold?

The 2nd sentence say 1.8.x but we're on 1..9.x now. Probably just remove this sentence completely, its obviously assumed they should deploy the latest version for the latest features.

**Comment by svekars** [comment]
It looks like it was resolved as I cannot see the mentioned note, but if not feel free to reopen.
