### ISSUE TITLE
backup and restore documentation should discourage stopping pipelines for versions < 1.9.4

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4023]
**What happened?**:

A bug in Pachyderm prior prior to current releases creates unusable backups if pipelines are stopped during the backup.  We instruct users to do this; we should discourage the practice for releases prior to 1.9.4, the first release which will have this fix.

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):  1.8.X - 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by svekars** [comment]
I think we have outlined this in the PR that update this doc, but if not, please feel free to reopen.
