### ISSUE TITLE
document how to access etcd via etcdctl for snapshotting

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4024]
If you need to get at `etcd` for backups, it's easily accessed via the service address from inside and outside the cluster.  

Required software: etcdctl and, if backing up from outside the cluster, kubectl.

If backing up from outside the cluster, first, forward the `etcd` service IP and port:

```
kubectl port-forward --address localhost pod/etcd-0 32379
:2379
```

Then, run a snapshot command:

```
ETCDCTL_API=3 etcdctl --endpoints http://12
7.0.0.1:32379 --insecure-discovery snapshot save /tmp/snapshot.db
```

 From within the cluster, you should be able to use the DNS name:
```
ETCDCTL_API=3 etcdctl --endpoints http://etcd.<namespace>:<service port> ...
```

NOTE: Pachyderm's `etcd` is configured by default for only inside-the-cluster access and for one `etcd` instance, which is why authentication and SSL are off and the `advertise-urls` IP address settings are  `0.0.0.0`.  If you require changes to these settings for your cluster, contact your Pachyderm support resource.

**Comment by pappasilenus** [comment]
I don't think this is high priority, but wanted to get it in the queue if you're touching backup/restore.

**Comment by mindthevirt** [comment]
This is covered in https://docs.pachyderm.com/1.13.x/deploy-manage/manage/backup_restore/#back-up-your-pachyderm-cluster
