### ISSUE TITLE
Job failure when running fruit_stand example.

### ISSUE THREAD

**Issue by elsonrodriguez** [pachyderm/pachyderm#404]
When running `pachctl create-pipeline -f examples/fruit_stand/pipeline.json`, the job fails:
```
$ pachctl list-job
ID                                 OUTPUT                                    STATE               
371f481bbe1b02c378c9248170bc24eb   filter/80a2cf28365c45ea8dc10fe4ba64986a   failure    
```

Pachctl logs show:
```
$ pachctl get-logs 371f481bbe1b02c378c9248170bc24eb
0 | 2016-05-11T16:47:49Z NONE  WriteRequest: apple	6
0 | apple	9
0 | apple	4
0 | apple	5
0 | apple	4
0 | apple	2
0 | apple	2
0 | apple	5
0 | apple	6
0 | apple	8
0 | apple	5
0 | apple	4
0 | apple	9
0 | apple	3
0 | apple	9
0 | apple	4
0 | apple	6
0 | apple	3
0 | apple	1
0 | apple	4
0 | apple	8
0 | apple	8
0 | apple	2
0 | apple	3
0 | apple	7
0 | apple	6
0 | @0
0 | 2016-05-11T16:47:49Z NONE  WriteRequest: banana	2
0 | banana	9
0 | banana	6
0 | banana	6
0 | banana	5
0 | banana	3
0 | banana	2
0 | banana	2
0 | banana	4
0 | banana	4
0 | banana	5
0 | banana	1
0 | banana	2
0 | banana	5
0 | banana	3
0 | banana	2
0 | banana	7
0 | banana	9
0 | banana	2
0 | banana	1
0 | banana	8
0 | banana	6
0 | banana	2
0 | banana	8
0 | banana	9
0 | banana	3
0 | banana	8
0 | banana	7
0 | banana	7
0 | banana	4
0 | banana	5
0 | banana	4
0 | banana	5
0 | banana	9
0 | @0
0 | 2016-05-11T16:47:49Z NONE  WriteRequest: orange	4
0 | orange	9
0 | orange	4
0 | orange	2
0 | orange	5
0 | orange	7
0 | orange	6
0 | orange	5
0 | orange	5
0 | orange	3
0 | orange	8
0 | orange	3
0 | orange	4
0 | orange	3
0 | orange	6
0 | orange	6
0 | orange	3
0 | orange	1
0 | orange	6
0 | orange	2
0 | orange	5
0 | orange	2
0 | orange	4
0 | orange	6
0 | orange	6
0 | orange	9
0 | orange	6
0 | orange	4
0 | orange	7
0 | orange	8
0 | orange	8
0 | orange	2
0 | orange	6
0 | orange	9
0 | orange	7
0 | orange	7
0 | orange	3
0 | orange	6
0 | orange	3
0 | orange	5
0 | @0
```

Job shows success from k8s side:
```
$ kubectl get jobs
NAME                               DESIRED   SUCCESSFUL   AGE
371f481bbe1b02c378c9248170bc24eb   1         1            5m
```

Pachd output is here: https://gist.githubusercontent.com/elsonrodriguez/a7c45374753e83536d293ab5701b4c6a/raw/d5c0efa9be54854165b271df507b00615ef9ff4c/pachd-logs-pipeline-issue

This was on k8s 1.2.3 deployed with kube-up on aws.

**Comment by jdoliner** [comment]
Hmm, I saw an issue like this due to some docker image version incompatibility. I think what's happening is that the version of `pachyderm/job-shim` on Docker Hub isn;t compatible with `pachyderm/pachd:v1.0.0(849)` the pachd image you're using.

I just repushed the job-shim image so I think if you rebuild the fruit stand image it will just work. If not please let us know.

Really sorry you hit this snag, I think we need to start versioning our API to prevent stuff like this.

**Comment by elsonrodriguez** [comment]
Was able to finish the fruit-stand example!

The job-shim should be version pinned to prevent any future incompatibilities. The surest way to do this is probably to blank out the image field in pipeline.json, and then set this to include a tag string:

https://github.com/pachyderm/pachyderm/blob/27329056b99dd0b7966815a11e1f5c05e2394769/src/server/pps/server/api_server.go#L941

 That way pachd always uses the right version of job-shim by default. Pre-reqs for that are to make sure that CI is chucking an image to docker hub per pachd release/build.

Some other notes are that I couldn't figure out what to delete to kill the job and re-create the pipeline. Once the pipeline errored out I just deleted pachyderm from k8s and started from scratch.

**Comment by jdoliner** [comment]
This seems to have been resolved. And suggestions have been spun off into other issues. Closing.
