### ISSUE TITLE
Clarify that the old cluster should be kept until the migration to a new version is completed

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4040]
Clarify in the docs that the old cluster should be kept alive until the migration to a new cluster is successfully complete.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Pachyderm CLI version (use `pachctl version`): 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
Its not as simple as this. We need to get a full understand from eng about what should/should not be happening in a cluster when they do `extract` and then make sure the doc match. 

If pipelines should not be `stopped`, is it ok if jobs are running? Or new data is still coming in?

**Comment by svekars** [comment]
The backup/restore section has been recently updated and this issue was likely addressed. Closing.
