### ISSUE TITLE
pachctl does ignores PACHD_ADDRESS

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4042]
**What happened?**:
pachctl ignores `PACHD_ADDRESS`:
```
> echo $PACHD_ADDRESS
192.168.64.57
> pachctl -v list job
DEBUG Attempting to implicitly enable port forwarding...
[0000] DEBUG Implicit port forwarding for the daemon failed: No pods found for app pachd
[0000] DEBUG Implicit port forwarding for SAML ACS failed: No pods found for app pachd
[0000]  INFO parsed scheme: "" source=etcd/grpc
[0000]  INFO scheme "" not registered, fallback to default scheme source=etcd/grpc
[0000]  INFO ccResolverWrapper: sending update to cc: {[{0.0.0.0:30650 0  <nil>}] } source=etcd/grpc
[0000]  INFO ClientConn switching balancer to "pick_first" source=etcd/grpc
[0000]  INFO pickfirstBalancer: HandleSubConnStateChange: 0xc0006b4710, CONNECTING source=etcd/grpc
[0000]  WARN grpc: addrConn.createTransport failed to connect to {0.0.0.0:30650 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:30650: connect: connection refused". Reconnecting... source=etcd/grpc
```

So it looks like even though PACHD_ADDRESS is set it still tries to connect via 0.0.0.0. It is the first time I observe this error...

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by marcadella** [comment]
I solved the issue by setting the IP:port in the pachyderm config file, but there is definitely something broken with PACHD_ADDRESS being ignored.
In addition in the doc you say that if the port is not set, 30650 is used by default. But when I set only IP in the config, port 0 was used. I had to explicitly set the port for it to work.

**Comment by pappasilenus** [comment]
I can't reproduce this behavior on macOS.  I'm wondering if it's a problem with the shell you're using. Do you get the same result if you do
```
PACHD_ADDRESS=192.168.64.57 pachctl -v list job
```

**Comment by marcadella** [comment]
Since it happened only once, I cannot test it right now, but next time it happens I'll give it a try.
I guess we can close it for now since it looks more like a "glitch" and I'll re-open if necessary.

**Comment by msteffen** [comment]
One thought that comes to mind: if this comes up again, make sure that `PACHD_ADDRESS` is an environment variable and not a shell variable. You can accomplish this by running:
```
env | grep PACHD_ADDRESS
```
(whereas `echo $PACHD_ADDRESS` will print a value even if it's only a shell variable, which pachd can't see)
