### ISSUE TITLE
Pachctl create branch -p won't accept a v4 UUID

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#4044]
**What happened?**:
I was creating a branch using the `-p` flag and the help file says you can use a commit id or branch

**What you expected to happen?**:
I expected to be able to create a branch with the `-p` flag using a `repo@commitid` format. 

**How to reproduce it (as minimally and precisely as possible)?**:

1. Create two repos and start a commit on the first repo
2. try to create a branch on the second repo using the `-p` flag and specify the first repo and the commit id
3. Receive the following error: 
```
➜ pachctl create branch outputrepo@model_mnist -p inputrepo@fec7f5e8cd264a248b5d6c7c30340fb0
branch name cannot be a UUID V4
```
4. Create the branch using the repo@branchname format

```
➜ pachctl create branch outputrepo@model_mnist -p inputrepo@mnist
```

**Anything else we need to know?**:

`pachctl create branch -h` says that it should be possible to create a branch using the commit id instead of the branch

```
➜ pachctl create branch -h
Create a new branch, or update an existing branch, on a repo, starting a commit on the branch will also create it, so there's often no need to call this.

Usage:
  pachctl create branch <repo>@<branch-or-commit> [flags]

Flags:
      --head string           The head of the newly created branch.
  -p, --provenance []string   The provenance for the branch. format: <repo>@<branch-or-commit> (default [])

Global Flags:
      --no-color   Turn off colors.
  -v, --verbose    Output verbose logs
```

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.12
- Pachyderm CLI and pachd server version (use `pachctl version`):  
```
COMPONENT           VERSION             
pachctl             1.9.3               
pachd               1.9.3
``` 
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE
- OS (e.g. from /etc/os-release): MacOs
- Others:

**Comment by JoeyZwicker** [comment]
I think this is just a minor docs bug. I think `create branch -p` should only take repo@branch. not repo@<branch or commitID>. I'm not sure what it would mean for a branch to be provenant on a specific commit. 

For the use case you're working on, you want it to be repo@branch. Also, I recommend using master to keep thing simpler in the example instead of using a model_mnist branch. 

If i'm misunderstanding something about this issue, feel free to reopen.
