### ISSUE TITLE
Update s3gateway docs

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4064]
The s3gateway docs need to be updated to reflect the new features landed in https://github.com/pachyderm/pachyderm/pull/3906. Most of the API docs are updated, but [the guide](http://docs.pachyderm.io/en/latest/enterprise/s3gateway.html) needs some touchups.

**Comment by JoeyZwicker** [comment]
Are the APi docs enough for @svekars to make these minor updates or are there steps that need to be taken that aren't described anywhere? Either way, we'll ask if we have any questions
