### ISSUE TITLE
Kubernetes services aren't cleaned up 

### ISSUE THREAD

**Issue by mrene** [pachyderm/pachyderm#4071]
**What happened?**:
After running pipelines for a while, there are a considerable number of kubernetes services defined, that are pointing towards objects that have been cleaned up.

```
kubectl get svc -l suite=pachyderm,component=worker | wc -l
     630
```

The RCs, however, have been properly cleaned up:
```
kubectl get rc -l suite=pachyderm,component=worker | wc -l
      19
```

```
pachctl list pipeline | wc -l
      19
```

**What you expected to happen?**:
The services are deleted at the same time as the RCs whenever a pipeline is updated. 

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.12-gke
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.3

**Comment by mrene** [comment]
Just want to drop this error here in case anyone encounters it. We had most of the kubernetes cluster fail to start with the following error: 

```
standard_init_linux.go:178: exec user process caused "argument list too long"
```

In our case, there were so many created services that the space reserved for environment variables was exhausted, and pods could effectively not start. All services can then be deleted with `kubectl delete svc -l suite=pachyderm,component=worker` (in our case we didn't use services as part of pipelines).

This was partially caused by one of internal component updating a lot of pipelines automatically.

**Comment by marcadella** [comment]
I have the same issue: old services are not deleted after `pachctl update`. This is an important issue as my k8s cluster has quotas limitting the number of created services.

**Comment by mrene** [comment]
@marcadella everything worked fine for me after deleting them all, I suspect it recreates objects that it needs

**Comment by msteffen** [comment]
I believe this was fixed by https://github.com/pachyderm/pachyderm/pull/4782. If you see this issue post Pachyderm 1.10.3, please re-open and we'll take another look.
