### ISSUE TITLE
Add docs for Pachd and worker environment variables

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4073]
Apologies if an issue exists for this already, I couldn't find it with GH search. It would be good to add docs for all the environment variables that can be set on Pachd. Fortunately this information is all in the same place: https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/serviceenv/config.go

It would probably be best to add descriptions of each variable with comments in the struct which can act as the source of truth and get updated as things change in the code. And then have those reflected in an outside doc.

**Comment by pappasilenus** [comment]
@svekars Here's some stuff I figured out by poking around:

Environment variables that folks may be interested in for logging would be
```
PACH_JOB_ID
PACH_OUTPUT_COMMIT_ID
```
And for every input repo, you’ll have an environment variable of the form
```
<input_repo_name_case_sensitive>_COMMIT
````
For example, if you have two input repos named “foo” and “bar”,  you should see
```
foo_COMMIT
bar_COMMIT
```
There are quite a few other environment variables used by pachyderm, too.  And remember that if you ever have your pipeline log to stdout, you’ll see the message bracketed by the jobID, workerId, datumID, and the hash for the datum, like this:
```
{"pipelineName":"env","jobId":"5c71d007264f42d1b55cc1171fdd783d","workerId":"pipeline-env-v1-cbvgm","datumId":"ba5e64f933b5242d130b6bbacef7f11c6b712ccd9c15a96c93722972e0c6639e","data":[{"path":"/","hash":"HUMhPWFwvUweM6SHLyt2BeMXfwosIySj22+oLxaQvss="}],"user":true,"ts":"2019-09-25T23:00:38.285919148Z","message":"your logline here"}
```

I found a lot of this out by creating a pipeline that just did an "env" to stdout (attached, works with an input repo called `images` 'cause that's what I had already).
[env.json.txt](https://github.com/pachyderm/pachyderm/files/3655199/env.json.txt)

**Comment by JoeyZwicker** [comment]
@pappasilenus Can you just post the list of results for your example so we can see and example full list of env vars

**Comment by pappasilenus** [comment]
[Environment.txt](https://github.com/pachyderm/pachyderm/files/3655551/Environment.txt)
[Environment2.txt](https://github.com/pachyderm/pachyderm/files/3655552/Environment2.txt)


Here are a couple of examples. The second one has a union input
