### ISSUE TITLE
Update go1.6 install link

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#410]
In the user job Dockerfile, we need to update the go1.6 download link to:

`https://golang.org/dl/go1.6.linux-amd64.tar.gz`

(Which is what is used on the go1.6 image on Dockerhub). Surprising it was broken. We should add a test for this too.

**Comment by JonathanFraser** [comment]
funny if I copy paste that into my browser it works fine?

**Comment by sjezewski** [comment]
The existing link in the Dockerfile under `etc/user-job/Dockerfile` is:

https://storage.googleapis.com/golang/go1.6.0.linux-amd64.tar.gz

Which provides an error for me. Is that what you see?

**Comment by JonathanFraser** [comment]
yes, that returns just and xml page for me.
