### ISSUE TITLE
run-pipeline command does not create new job

### ISSUE THREAD

**Issue by Justin-Kuehn** [pachyderm/pachyderm#413]
While running pachyderm locally, when I run the `pachctl run-pipeline` command on an existing commit it does not re-run the pipeline, instead it returns the ID of an old job that was previously run on that commit.

I would expect explicitly commanding a `run-pipeline` would create a new job that would re-process the data in the commit.  If this is the intended behavior is there a way to explicitly kick off a pipeline without creating a new commit?

```
>pachctl list-pipeline
NAME                INPUT               OUTPUT
wordcount_reduce    wordcount_map       wordcount_reduce
wordcount_map       rawtext             wordcount_map

>pachctl list-job
ID                                 OUTPUT                                              STATE
8cf1d8f8200eadb9b5e9249a4c9d9fce   wordcount_map/9f4cb0cecab242f99891f60221b42fc2      success
9591e07e75de0cb68f4d1ef346044c50   wordcount_reduce/674f90831a6c4d0f8fbed0023e63578a   success

>pachctl run-pipeline wordcount_map -f job.json
8cf1d8f8200eadb9b5e9249a4c9d9fce

>pachctl list-job
ID                                 OUTPUT                                              STATE
8cf1d8f8200eadb9b5e9249a4c9d9fce   wordcount_map/9f4cb0cecab242f99891f60221b42fc2      success
9591e07e75de0cb68f4d1ef346044c50   wordcount_reduce/674f90831a6c4d0f8fbed0023e63578a   success
```

No new jobs were created, despite calling `pachctl run-pipeline wordcount_map -f job.json`

job.json
```
{
  "parallelism": "1",
  "inputs": [
    {
      "commit": {
        "repo": {
          "name": "rawtext"
        },
        "id": "8ab3aa89c42f4277a7811589533f7cf0"
      }
    }
  ]
}
```

```
>pachctl version
COMPONENT           VERSION
pachctl             1.0.0(849)
pachd               1.0.0(849)
```

**Comment by jdoliner** [comment]
Hi @Justin-Kuehn sorry you hit this, I think your expectation on what this command should do is pretty reasonable. The reason it behaves this way is that `CreateJob` was made idempotent to make handing off responsibilities for pipelines a little easier. We should add a way to override that behavior for `run-pipeline`, probably a `force` flag on the `CreateJob` protobuf which causes a new job to always be run if it's set to `true`. Does that seem reasonable to people?

**Comment by Justin-Kuehn** [comment]
Hi Joe, thanks for the response.  Having `CreateJob` be idempotent makes sense.  In my case I was iterating on the pipeline (changing the docker image and such) and found the only way I could reprocess data was to make a new commit with the same data or rename my pipelines. I think a force flag sounds like a reasonable solution here.
