### ISSUE TITLE
Merge gRPC services?

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4131]
Currently Pachyderm splits functionality across several gRPC services (e.g. PFS vs PPS), even though:

1) The CLI with regard to its UI does not expose these distinctions (though it does in places in the usage docs.)
2) The go client exposes a single [APIClient](https://godoc.org/github.com/pachyderm/pachyderm/src/client#APIClient) with all the functionality (though it does also define individual clients for each service.)

We minimize the distinction between these disparate services to users, yet do not reflect this with gRPC definitions.

This ambiguity makes it unclear if a distinction should be made between services for client library authors. While go's support for anonymous structs allows our go client to support both setups, it's not clear what to do in other languages; e.g., it's led me to mulling on which evolutionary path is best for the python library ([distinct classes](https://github.com/pachyderm/python-pachyderm/pull/128) or a [single class](https://github.com/pachyderm/python-pachyderm/pull/129)?)

I'm not sure if it would be better to just merge all functionality into a single gRPC service, but wanted to bring this up to see what others think.

**Comment by jdoliner** [comment]
I'm generally a fan of having separated grpc services, admittedly a lot of that is probably just that I'm used to it. But we do use the fact that they're separate in a few places. For example: the sidecar is basically a pachd node that strips out some of the services that the worker doesn't need to have access to.  I don't think these uses are crucial, or that we couldn't accomplish something similar in a different way though. The other argument I see for keeping it the way it is is that I think it's served as a good way to split up the code, again something that could be accomplished in other ways, but I think the way we have things split up right now does make a lot of sense, and of course has the advantage that it exists in the code base today.

**Comment by ysimonson** [comment]
Given that, do you think it makes sense for pachyderm libraries to keep functionality separated by service as well? Or merge it all into one, as per [python-pachyderm#129](https://github.com/pachyderm/python-pachyderm/pull/129)?

**Comment by gabrielgrant** [comment]
My recollection is that we were talking about this as a potential difference between what we want to use as an "internal" API (ie separate GRPC services exposed on the internal k8s network) vs a public pach API: a single, merged API namespace, that matches up with what users see in the CLI, and has internal-only functionality removed (object API, probably some internal-use-only fields?). This public-vs-private distinction is something @msteffen has been talking about for ages, and probably becomes more important as we want to start provided better public-API backwards compat promises

**Comment by ysimonson** [comment]
There isn't much in terms of internal APIs, and we ultimately decided that [it's not worthwhile to hide them](https://github.com/pachyderm/pachyderm/issues/3867#issuecomment-520960280).

Going to close this out, given @jdoliner's prior comment.
