### ISSUE TITLE
Fix the documentation regarding steps to follow for local install

### ISSUE THREAD

**Issue by jcabraham** [pachyderm/pachyderm#4137]
In the documentation, under Getting Started/Local Installation the steps outlined are as follows (my case, MacOS):

- Install Docker Desktop/Kubernetes (OK)

- Install pachctl via brew (OK)

- From the docs:

> Verify that installation was successful by running pachctl version:
```
$ pachctl version
COMPONENT           VERSION
pachctl             1.9.1
```

**This fails.** 
It times out trying to connect to the pachd server, which isn't running. Nowhere in the docs is the daemon even mentioned, not even in the troubleshooting section.

You've omitted a step. It should be : 

> Start the pachd server: 

```
$ pachctl deploy local
```

Then

>Verify that installation was successful by running pachctl version:

```
$ pachctl version
COMPONENT           VERSION
pachctl             1.9.5
pachd               1.9.5

```

Also, the troubleshooting guide has this section

> Cannot connect via pachctl - context deadline exceeded
> Symptom
> 
> You may be using the pachd address config value or environment variable to specify how pachctl talks to your Pachyderm cluster, or you may be forwarding the pachyderm port. 

...
> Recourse
> It’s possible that the connection is just taking a while. Occasionally this can happen if your cluster is far away (deployed in a region across the country). Check your internet connection.

This cannot connect error also pops up when pachd is simply not running, i.e. no deployment to the cluster. Probably it's no biggie, but easy to fix and might save some time trying the thing out.

**Comment by JoeyZwicker** [comment]
@jcabraham Thanks for submitting this! The docs can definitely be improved a bit. That timeout is expected because the next section is where we have you deploy Pachyderm, but we should add a quick line along the lines of:

```
Verify that installation was successful by running `pachctl version`. The pachctl version should be shown, but it should timeout for pachd because we haven't deployed the server yet. This is expected and we'll deploy the pachyderm server next. 

$ pachctl version
COMPONENT           VERSION
pachctl             1.9.1
```

**Comment by jcabraham** [comment]
Makes sense, I'm liking Pachyderm!
