### ISSUE TITLE
Line Based Diffs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#414]
Wanted to break this out into a new issue. Just got off a customer call where they emphasized an interest in line-based diffing of files (mostly csv). There are two parts to this feature:
1. How does PFS expose a line-based diff to PPS for computation? This would feed into how to do incremental processing on in-line updates, etc.
2. How does the user visualize a diff? There a use case around allowing human-readable line-based diffs, even if we can only do incremental processing on append diffs. This particular customer "salivated" at the idea of being able to view diffs of his csv files in a Git-like view (+/-, green/red highlighted lines).

**Comment by sjezewski** [comment]
This is stale
