### ISSUE TITLE
[DOC] Glob capture docs

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4144]
Create documentation for the glob capture feature base on https://github.com/pachyderm/pachyderm/pull/4123

**Comment by svekars** [comment]
@adelelopez can you please provide a summary of the change and what needs to be described in the documentation?

**Comment by nadegepepin** [comment]
The PR #4123 has been held back. A new feature request #5624 has been created to migrate the code from 4123 to the API. It was labeled `needs docs` and will be documented when the implementation is done.

Closing this.
