### ISSUE TITLE
clients throw error when the S3 rate limit is hit

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#415]
```
rpc error: code = 13 desc = invalid header field value "SlowDown: Please reduce your request rate.\n\tstatus code: 503, request id: 1134F6E552866794"
```
S3 has a request rate limit of `300 req/s` when that gets hit it triggers an rpc error in the golang client

**Comment by jdoliner** [comment]
This is actually a bit curious. Unless I'm misreading the code it seems that in the amazon obj client we're using an exponential backoff writer which should catch errors like this and retry.

@derekchiang any thoughts on this one?

**Comment by derekchiang** [comment]
@erikreppel we've increased the backoff rate and added more logging so that if this error happens again, there will be more info to work with.
