### ISSUE TITLE
list-commit should report "repo not found" if the repo does not exist

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#416]
Currently it just prints an empty output, making people think that there are just no commits.

**Comment by derekchiang** [comment]
Will fix with #411

**Comment by jdoliner** [comment]
I think it'd be better to keep this open and move it into v1.2 just to make sure we remember to do this. It'd be pretty easy to inadvertently keep the old behavior during the refactor.

**Comment by sjezewski** [comment]
This is covered by the fix I did for #428 

I have a test in place for ListCommits that reports the error you describe.
