### ISSUE TITLE
`pachctl config set context -k` omits `"namespace"` field when it is empty

### ISSUE THREAD

**Issue by bpeabody** [pachyderm/pachyderm#4166]
It should be populated with `"default"`. When this field is missing `pachctl port-forward` does not work.

You can work around the problem by manually adding `"namespace": "default"` to `.pachyderm/config.json`.

**Comment by pappasilenus** [comment]
@ysimonson Two choices, I think:

1. pachyderm contexts assume "default" when no namespace is specified in a config (the same as kubeconfig behavior)
2. `set context` automatically sets the "namespace" property in a context when importing from kubeconfig contexts with no namespace

I'm inclined to mimic the kubectl behavior, but it seems to me that there is an argument for making it easier to use  and precise by *requiring* a namespace spec in a context.

**Comment by ysimonson** [comment]
Thanks @bpeabody! Fixed in #4170. In the mean-time, you should be able to work around this by doing `pachctl port-forward --namespace=default`.
