### ISSUE TITLE
Run pipeline CLI

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4172]
Currently `pachctl run pipeline` can only send a limited subset of the permissible `RunPipeline` requests. This is because the `RunPipeline` request takes as its argument a repeated set of `CommitProvenance` objects, which are branch commit pairs, but the cli takes a repeated list of Commits, so the `Branch` field in the `CommitProvenance` is always empty. This leads to most CLI invocations of `run pipeline` failing. To fix this we need to introduce a CLI syntax for `CommitProvenance` objects. I propose we represent them as `repo@branch=commit`, so running a pipeline would look like:

```sh
pachctl run pipeline <pipeline> <repo1>@<branch>=<commit> <repo2>@<branch>=<commit> ...
```

**Comment by JoeyZwicker** [comment]
Where `<commit>` = `<commit or branch>` and supports `^` syntax. I figure that was assumed, but wanted to mention explicitly

**Comment by jdoliner** [comment]
That is assumed, and already implemented in the API, it should be basically impossible for a Pachyderm command that takes a commit to not also accept branches and ancestry syntax.
