### ISSUE TITLE
On-the-flight output branch

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4177]
**What is the goal / desired outcome?**

Related to [this comment](https://github.com/pachyderm/pachyderm/issues/2882#issuecomment-538624656), it would be really nice to be able to use the traditional `output_branch` pipeline field as a default output branch, but having a special file in the PFS (for example `/pfs/output_branch`) where the container could overwrite the desired output branch name. This would make the pipelines super flexible.

In addition there could be a special branch `null` that would be the equivalent of linux `/dev/null`: everything committed to that branch is just ignored (no pipeline could define `null` as it's input branch).

**If there is a way to accomplish this today via workaround, what does that require?**

Currently no simple workaround.

**(Optional) What is your proposal for a feature to solve this?**

As describe above: just use a special PFS file where one can write the desired output branch. One could get crazy and have a list of output branches.

**Comment by pappasilenus** [comment]
HI, @marcadella. I'm unclear on what problem you're solving here. Can you give us a more concrete use case?

**Comment by marcadella** [comment]
Some of the use cases:
- conditionals:
  - Lets assume a workflow can take two paths A or B. Which path the workflow follows depends on a result. If it was possible to determine the output branch on-the-flight it would be possible to push the output commit to branch A or B.
  - Early termination: same as above but, while one branch leads to the next pipeline, another branch is used for stopping the workflow where it is (that's the "`/dev/null`" branch I mentioned above).
- Using branches a lanes: One could use branches as separate lanes. For example let's assume I want to run a workflow on a dataset D1, I could push it on `inputRepo@D1`, then, provided that #2882 is implemented, pipeline `P1` runs and pushes the output on `P1@D1`, and so on. The whole workflow is executed on branches `D1` for each pipelines. In this model you'd have one branch per dataset.

**Comment by pappasilenus** [comment]
There are open design issues for each of these use cases. Please add your input there.
Loops and conditionals: #3345 
Branches and lanes/parallel job processing: #3963 

Going to close this since it’s covered by other issues
