### ISSUE TITLE
run pipeline should accept a --job parameter

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4180]
**What is the goal / desired outcome?**

`pachctl run pipeline myPipeline` works fine if one wishes to re-run the latest job. But in a context were pipelines can fail, it would be nice to have a `--job` parameter to retry jobs older than the latest. I understand it's possible to reach this goal by looking at the input commits for that job, then using those commits with the `run` command. But that's a bit complicated for such a basic need.

**Environment?**:
- Pachyderm CLI version (use `pachctl version`):
1.9.6

**Comment by pappasilenus** [comment]
Add to #3985
