### ISSUE TITLE
PACHD_ADDRESS or context config can contain grpcs:// but not grpc://

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#4181]
**What happened?**:
I put grpc:// in the PACHD_ADDRESS
**What you expected to happen?**:
Connection as usual
**How to reproduce it (as minimally and precisely as possible)?**:
put grpc://address_to_pachd:port in your PACHD_ADDRESS or in a context
**Anything else we need to know?**:
```
could not connect to pachd at "grpc://***:650": address shouldn't contain protocol ("://"), but is: "grpc://***:650"

but with grpcs there are no complaints
```

Mostly, this just seems inconsistent. Minor bug.

**Comment by pappasilenus** [comment]
@ysimonson seems like this should be addressed in configs.

**Comment by ysimonson** [comment]
Indeed. I believe checking for `grpcs://` was recently added, but in general the code for parsing pachd address is not particularly structured. Maybe it's time to do proper URI parsing.
