### ISSUE TITLE
pachd OOM_KILLED when attempting to upload files in pachyderm > 1.9.5

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#4182]
**What happened?**:
Fresh install of pachyderm. Tried to upload a recursive directory tree, pachctl returns EOF. Running with verbose output indicates pachd is refusing connections. Confirmed by netcat, connections are refused when pachctl says connection refused.

**What you expected to happen?**:
Files upload to the repo.

**How to reproduce it (as minimally and precisely as possible)?**:
Install pachyderm 1.9.6 or 1.9.7. Use PACHD_ADDRESS to connect directly to pachd as a loadbalancer service in the cluster without encryption. Upload recursively. you will see:
```
[0005]  WARN grpc: addrConn.createTransport failed to connect to {pachd1.k8s.ci.neoninternal.org:650 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.206.28.150:650: connect: connection refused". Reconnecting... source=etcd/grpc
[0005]  INFO pickfirstBalancer: HandleSubConnStateChange: 0xc0001c4e60, TRANSIENT_FAILURE source=etcd/grpc
[0006]  INFO pickfirstBalancer: HandleSubConnStateChange: 0xc0001c4e60, CONNECTING source=etcd/grpc
[0006]  WARN grpc: addrConn.createTransport failed to connect to {pachd1.k8s.ci.neoninternal.org:650 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.206.28.150:650: connect: connection refused". Reconnecting... source=etcd/grpc
```

**Anything else we need to know?**:
setting LOG_LEVEL to debug in the pachd deployment doesn't seem to help. The pachd logs don't indicate any sort of error, but I can't get debug logging so this probably doesn't mean anything.

Reverting to pachyderm 1.9.5, and the problem goes away.

Also, pachctl 1.9.7 and pachd 1.9.5 work, so this appears to be a pachd issue not a pachctl issue.

**Environment?**:
- Kubernetes version (use `kubectl version`):
1.15.4
- Pachyderm CLI and pachd server version (use `pachctl version`):
pachd 1.9.7 - fails
pachd 1.9.6 fails
pachd 1.9.5 works (even with newer pachctl)

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
local deployment. LoadBalancer pachd service provided by MetalLB
- Others:

Happy to provide more debug logging if someone gets me instructions on how to raise pachd's log level.

**Comment by brokenjacobs** [comment]
Ok so what's happening is pachd is getting OOMkilled:
```
Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 07 Oct 2019 16:48:31 -0600
      Finished:     Mon, 07 Oct 2019 16:49:34 -0600
```
But OOMKiller doesn't restart the pod, so that's what was confusing me. pachd is definitely dying. There is no difference between the requests/limits on 1.9.5 to 1.9.7.
```    Limits:
      cpu:     1
      memory:  3G
    Requests:
      cpu:      1
      memory:   3G
```

**Comment by brokenjacobs** [comment]
root cause... setting the part size larger (128MB in this case) using the new settings available in >=1.9.6 causes this crash.

**Comment by pappasilenus** [comment]
@brycemcanally reproducible issue. Thoughts?

**Comment by brycemcanally** [comment]
@brokenjacobs @pappasilenus making the part size that large eats up significantly more memory per object storage writer (>20x the default of 5MB). I guess we could expose a way to have finer control of the object storage write concurrency, but the best suggestion right now is probably to leave the default. This seems more like Pachyderm lacking some configuration rather than a bug though.
