### ISSUE TITLE
`pachctl run pipeline B A@master` fails due to duplicate __spec__ in commit provenance

### ISSUE THREAD

**Issue by simeonmiteff** [pachyderm/pachyderm#4183]
**What happened?**:
I have two pipelines, A and B. A has as input cron and an input repo with some configuration data. B has input the A repo. After the issue described in issue #4168, after restoring the deleted ClusterRole/ClusterRoleBinding, I was able to restart pipeline A and it has since run successfully on each cron tick. Pipeline B, however, wouldn't run.

When A commits to it's output repo, a job is created for B, which fails with an error saying that the output of A failed. Inspecting the job shows the input commit for the job is the last output commit of failed A jobs (just before I fixed the k8s issue). 

At this point I started moving head around in B, but that didn't help so I put head back to the latest commit.

In this state, running `pachctl run pipeline B` results in the same issue above as when B runs by itself in response to output commits in A.

If I try running `pachctl run pipeline B A@master`, then I get this error:
```the commit provenance contains multiple commits from the same branch```

Inspecting pachd logs I see the pfs.API.StartCommit is failing because it finds two instances of the `__spec__` commit for pipeline B in the commit provenance parameter passed to the function. Here is how I figured that out:

```
cat <request json> | jq -r '.request.provenance[]|.commit.id, .commit.repo.name, .branch.name, .branch.repo.name' | paste - - - -
f2824f1f74384bc2b801f4b2ced13de5    A            null    null
b33f6e8eebbd41a7810272afa1e50268    __spec__    B        __spec__
b7e647b199654ca88ed12a3abd7598df    __spec__    A        __spec__
b92c74bc85244cf7a4e0222e7ce8ee56    otherrepo-A    master    otherrepo-A
187b69785e4f498696620d480d74835d    A_cron-1h    master    A_cron-1h
b33f6e8eebbd41a7810272afa1e50268    __spec__    B        __spec__
```

**What you expected to happen?**:
- I expect `pachctl run pipeline B` to succeed, because I would think it should reference the head commit in A.
- I also expect `pachctl run pipeline B A@master` to succeed without the error caused by the duplicate commit in the request provenance.

**How to reproduce it (as minimally and precisely as possible)?**:
Not exactly sure. I have tried to describe how I got to this state above. I am keeping things in this state to aid the pachyderm team in troubleshooting for the moment (see below).

**Anything else we need to know?**:
This will be a blocking issue for our team in a day or two, at which point I'll be under pressure to blow away the pipelines and reprocess. I would feel a lot more comfortable if we could figure out how we got to this state, so I would appreciate a quick triage on this issue!

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION             
pachctl             1.9.4               
pachd               1.9.4
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
GKE
- OS (e.g. from /etc/os-release):
Google Cloud-Optimised-Linux
- Others:

**Comment by pappasilenus** [comment]
@simeonmiteff Did you ever try
```
pachctl fsck --fix
```
to correct the __spec__ provenance issues?

**Comment by simeonmiteff** [comment]
@pappasilenus no, on @JoeyZwicker's advice I did a `pachctl update pipeline` and that seems to have corrected the issued (not sure why).
