### ISSUE TITLE
list_buckets() and list_objects() are returning empty lists from pachyderm using minio client

### ISSUE THREAD

**Issue by chaitanyak52** [pachyderm/pachyderm#4187]
Dear all,

when using list_buckets() or list_objects() on an account/bucket in pachyderm, the result is an empty list, allthough there are buckets/objects in that account.
```
s3_client = Minio(endpoint=s3_endpoint,
                  access_key=s3_accesskey,
                  secret_key=s3_secretkey,
                  region=s3_region,
                  secure=s3_secure)
the_bucket = s3_bucket
list_buckets = s3_client.list_buckets()  #Returns empty list
is_bucket = s3_client.bucket_exists(the_bucket)  #Returns True
list_objects = s3_client.list_objects(the_bucket)  #Returns empty generator object
[print(obj.object_name) for obj in list_objects]  #Throws the error below
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
kubernetes version v12
- Pachyderm CLI and pachd server version (use `pachctl version`):
pachctl version         
COMPONENT           VERSION             
pachctl             1.9.2               
pachd               1.9.4  

- Cloud provider (e.g. aws, azure, gke) or local deployment 
custom kubernetes on azure 
- OS (e.g. from /etc/os-release):
Mac OS Sierra

Error on trying to access the objects from existing bucket

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/minio/parsers.py", line 104, in get_child_text
    return self.element.find('s3:{}'.format(name), _S3_NS).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "pachyderm_s3.py", line 75, in <module>
    main()
  File "pachyderm_s3.py", line 60, in main
    for obj in objects:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/minio/api.py", line 906, in list_objects
    bucket_name=bucket_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/minio/parsers.py", line 238, in parse_list_objects
    is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/minio/parsers.py", line 108, in get_child_text
    'Message: {}').format(self.root_name, name, error.message)
AttributeError: 'AttributeError' object has no attribute 'message'```

**Comment by ysimonson** [comment]
It looks like you're hitting some sort of error with the minio library. This isn't being triggered by anything pachyderm-related. Maybe try opening a ticket with minio?

**Comment by chaitanyak52** [comment]
@ysimonson, I have tried using list_buckets with minio library and works ok. I see a similar issue which is opened on minio-library and they have redirected to S3 bucket implementation.
https://github.com/minio/minio-py/issues/788

**Comment by pappasilenus** [comment]
A workaround is to use the popular [boto3](https://github.com/boto/boto3) library.  Here's some sample code using it to perform that same operation on a Pachyderm server with the S3 Gateway port-forwarded to localhost and auth disabled.

```
import boto3

s3 = boto3.client('s3',
                  aws_access_key_id='',
                  aws_secret_access_key='',
                  endpoint_url='http://localhost:30600/')

response = s3.list_buckets()

for bucket in response['Buckets']:
    print(bucket['Name'])
```

**Comment by msteffen** [comment]
Reopening and self-assigning this issue. Seldon has run into this and in their case, the minio library is used by KFServing (a dependency) rather than by seldon itself. While KFServing is being changed to use boto3, I think it might be worth revisiting this and double-checking for reasonable mitigations in the s3 gateway server, for the purpose of unblocking Seldon.
