### ISSUE TITLE
recovered datums don't get retried; they are always skipped

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4195]
**What happened?**:

I created a pipeline with an err_cmd that would result in a recovered datum. The datum was successfully marked as recovered during the job that resulted from its commit.  It was skipped in every subsequent job, even pipeline updates.

**What you expected to happen?**:
I expected it to be marked as recovered in every subsequent job.  I expected the datum to be retried, especially after the pipeline was updated with new code

**How to reproduce it (as minimally and precisely as possible)?**:

1. I created the opencv example with this `err_cmd` and `err_stdin` for both the `edges` and `montage` transforms. (See also attached pipeline specs.)
```
        "err_cmd": [ "bash" ],
        "err_stdin": [ "if [ -a /pfs/images/foo.jpg ]; then exit 0; elif [ -a /pfs/edges/foo.png ; then exit 0 ; else  exit 1 ; fi " ]
```
2. I committed both the images.txt and images2.txt files
3. Created an empty "foo.jpg" file: `touch /tmp/foo.jpg`.
4. Commit that file `pachctl put file images@master:foo.jpg -f /tmp/foo.jpg`
5. See that the `foo.jpg` is marked as recovered.
6. Commit more files: `pachctl put file images@master -i images3.txt`
7. The job stats show the datum as skipped, not recovered.  Logs show it's not retried.
8. Update the `edges` pipeline to not have the `err_cmd`, just from the normal example json.  Instead of the datum getting retried and failing, it is skipped.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
OMPONENT           VERSION             
pachctl             1.9.7               
pachd               1.9.7               
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
both docker-desktop and hub
- OS (e.g. from /etc/os-release):
- Others:
[montage-with-error.txt](https://github.com/pachyderm/pachyderm/files/3703348/montage-with-error.txt)
[edges-with-error.txt](https://github.com/pachyderm/pachyderm/files/3703351/edges-with-error.txt)

**Comment by mattusifer** [comment]
I am also facing this issue. I am using `err_cmd` to alert on pipeline failures. This is the situation in which I've run into this:

1. A pipeline contains a bug
2. `err_cmd` captures the datums that trigger the bug
3. We update the pipeline code to fix the bug
4. The next job runs and skips the captured datums
