### ISSUE TITLE
yaml parser fails to parse time

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#4209]
**What happened?**:
JSON based cron spec works to parse `start` time but `yaml` doesnot.
```bash
cat << EOF | pachctl create pipeline -f -
{
  "input": {
    "cron": {
      "name": "crons",
      "start": "2019-10-10T22:30:05Z",
      "spec": "@yearly"
    }
  },
  "pipeline": {
    "name": "one"
  },
  "transform": {
    "cmd": [
      "/bin/bash"
    ],
    "image": "myimg",
    "stdin": [
      "blah blah"
    ]
  }
}
EOF
```
Equivalent `yaml` is:
```bash
cat << EOF | pachctl create pipeline -f -
input:
  cron:
    name: crons
    start: "2019-10-10T22:30:05Z"
    spec: "@yearly"
pipeline:
  name: one
transform:
  cmd:
  - "/bin/bash"
  image: myimg
  stdin:
  - "blah blah"
EOF
```

and throws error ```malformed pipeline spec: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `2019-10...` into types.Timestamp``` despite being correct format.

**How to reproduce it (as minimally and precisely as possible)?**:
Plz see above.

**Comment by JoeyZwicker** [comment]
Thanks for filing @suneeta-mall. @msteffen is working on the yaml parsing and will take a look at this.
