### ISSUE TITLE
make-launch error

### ISSUE THREAD

**Issue by kevinemoore** [pachyderm/pachyderm#422]
I got the following error running make launch:

```
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy ./src/server/cmd/pachctl-doc
src/server/cmd/pachctl/main.go:4:2: cannot find package "github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd" in any of:
	/Users/kmoore/toa/github/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd (vendor tree)
	/usr/local/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd (from $GOROOT)
	/Users/kmoore/toa/github/pachyderm/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd (from $GOPATH)
src/server/cmd/pach-deploy/main.go:6:2: cannot find package "github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds" in any of:
	/Users/kmoore/toa/github/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds (vendor tree)
	/usr/local/go/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds (from $GOROOT)
	/Users/kmoore/toa/github/pachyderm/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds (from $GOPATH)
```

**Comment by jdoliner** [comment]
Hi @kevinemoore really sorry you ran into this.
What version of go do you have installed?

**Comment by kevinemoore** [comment]
How do I tell? I'm not a go user, but I just tried go --version and go -v and neither worked.

**Comment by kevinemoore** [comment]
According to brew, it's go-1.6.2.

**Comment by jdoliner** [comment]
You were really close. `go version` will do it.

**Comment by kevinemoore** [comment]
go version
go version go1.6.2 darwin/amd64

**Comment by jdoliner** [comment]
Ahh, this might be some GOPATH issues. What does `echo $GOPATH` get you and where is the repo in your filesystem?

**Comment by kevinemoore** [comment]
The repo lives at:
/Users/kmoore/toa/github/pachyderm

And, for now, GOPATH=/Users/kmoore/go_workspace

**Comment by jdoliner** [comment]
Ahh, that's the problem I think. Our repo expects to be located at `$GOPATH/src/github.com/pachyderm`. Probably the easiest way to get it setup correctly would just be `go get github.com/pachyderm/pachyderm`. That'll clone the repo into the right spot on the `GOPATH` and get the dependencies as well.

**Comment by kevinemoore** [comment]
OK. We got farther. Now, I'm seeing this:
src/server/cmd/pachctl-doc/main.go:22: cannot use rootCmd (type *"github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra".Command) as type *"server/vendor/github.com/spf13/cobra".Command in argument to doc.GenMarkdownTree
make: *** [install] Error 2

**Comment by sjezewski** [comment]
Hmmm I can't reproduce that error. Can you help me by providing a bit more information? I'd like to know:

- the output of `ls $GOPATH/src/github.com/spf13`
- the output of `ls $GOPATH/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13`

Thanks!

**Comment by kevinemoore** [comment]
ls $GOPATH/src/github.com/spf13
ls: /Users/kmoore/pachyderm/src/github.com/spf13: No such file or directory

ls $GOPATH/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13
cobra	pflag
