### ISSUE TITLE
Reading lazy=true data in R

### ISSUE THREAD

**Issue by CelebrateVC** [pachyderm/pachyderm#4227]
### Issue explanation
Using lazy=true on a PFS referring to a large directory (1000 files) of raw data csv files, only actually using 2 files per job task ever.

- PFS spec :  `{"pfs":{"repo":"rawdata","glob":"/","lazy"=true}}`
- Environment : R (Rocker)
- Code line : `read.csv(pipe("/pfs/rawdata/filename.csv","r"))`
- Error : `sh: 1: /pfs/rawdata/filename.csv: Permission denied`
`Error in read.table(file = file, header = header, sep = sep, quote = quote,  :`
  `no lines available in input`
`Calls: read.csv -> read.table`
`Execution halted`

### Sob Story
Adapting existing code (non-pachyderm) code to go through pachyderm for a project task. The code itself is written in R and I'm trying to keep the number of code changes to a minimum. At one stage of the process, 2 sets of processed data are compared on similarity (`A_processed`, and `B_processed`), if the data is a match, the unprocessed data is retrieved for the 2 datasets (`A` and `B`), concatenated and passed on as `A union B` to be processed again. Ergo downloading the whole rawdata directory is unnecessary 

I am having difficulties finding examples of where "lazy"=true has be implemented. I see the docs say that:
> Some applications do not work with pipes. For example, pipes do not support applications that makes `syscalls` such as `Seek`.

I do not know if that restriction is applicable in this case, R does have a `sys.call` function, but that is not being invoked in this case to my knowledge. I would appreciate any guidance that could be provided in how to effectively navigate this issue. Thank you in advance.

**Comment by ysimonson** [comment]
If you want to read files from `/pfs/`, you'll want to not set lazy (or set it to false.)

**Comment by ysimonson** [comment]
Sorry, I missed the call to `pipe`!

I'm not familiar with R, and not sure if/how it handles named pipes. For starters, have you tried with `lazy: false` anyways, and seeing if you can read the normal files correctly?

**Comment by CelebrateVC** [comment]
Hi Yusuf, thanks for your quick response. I have tried `lazy=false` and that does work correctly. I am personally also quite new to working with non-trivial file connections, so cannot say much. According to the [R code descriptions of Connection manipulators](https://stat.ethz.ch/R-manual/R-devel/library/base/html/connections.html) it says that the first parameter passed into the pipe function is 
> the command line to be piped to or from. This is run in a shell, on Windows that specified by the COMSPEC environment variable. 

which now that I stop and RTFM, doesn't sound correct. Is it possible that I could need one of the other file manipulators? There's a `fifo` function, that seems like it might be more applicable, I'll try that tomorrow and report back.

**Comment by jdoliner** [comment]
There's a good chance that you don't need to do anything special to work with the pipe, many applications can just use named pipes in place of regular files without any modification. If that fails you can also resort to doing `cat /pfs/rawdata/filename.csv >/tmp/filename.csv` that will turn it into a regular file that you can then manipulate.

**Comment by CelebrateVC** [comment]
Hi there, so I just got in and made a few discoveries. As expected changing `pipe` to `fifo` removed the Permission Denied error, however still reported `no lines available in input`.  *Removing the connection function entirely*, and simply calling `read.csv("/pfs/rawdata/filename.csv")` reads the pipe just fine

After further testing it turns out that R reads lazy connections using `file(...)` exactly the same as it would for a non-lazy connection.
