### ISSUE TITLE
Error command listing unexpected input paths

### ISSUE THREAD

**Issue by gpkc** [pachyderm/pachyderm#4250]
**What happened?**:
When creating some error handler, I wanted to access some of the input files to obtain information from the running task. However, the path was different from the one you would expect from the normal `cmd` command. Instead of, for example, `/pfs/test-input/abc`, I got `/pfs/.scratch/14472802a9f94258a86722ea2ca2f341/test-input/abc`

**What you expected to happen?**:
The file paths were expected to be the same.

**How to reproduce it (as minimally and precisely as possible)?**:
Create a pipeline such as:
```
{
  "pipeline": {
    "name": "test_pipeline"
  },
  "description": "",
  "input": {
    "pfs": {
      "repo": "test-input",
      "glob": "/*"
    }
  },
  "transform": {
    "image": "ubuntu",
    "cmd": ["/bin/bash"],
    "stdin": ["exit 1"],
    "err_cmd": ["/bin/bash"],
    "err_stdin": [
"echo \"Starting error handling...\"",
"root=/pfs",
"FILES=$(find \"$root\" -type f)",
"for f in $FILES; do",
"    echo \"Found file $f \"",
"done",
"echo \"Done!\""
    ]
  }
}
```

Create the input repository. Then, commit a dummy file:

`$ pachctl put file test-input@master -f abc`

Get the job ID and retrieve the logs:

```
Starting error handling...
Found file /pfs/.scratch/68e688f5cc254b47afa2e9b67f80127c/test-input/abc 
Done!
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`): Both `1.9.7`
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS EKS
- OS (e.g. from /etc/os-release): Xubuntu 18.04.3 LTS
- Others:

**Comment by jdoliner** [comment]
Those files are present when the normal command runs too, they're actually the scratch space where the files are downloaded, and then symlinked into the correct directories. The issue here seems to be that the symlinks are being deleted before the error command runs, is that accurate? I.e. are you not seeing the `/pfs/test-input` repo? Or are you just seeing `/pfs/.scratch` in addition.

**Comment by gpkc** [comment]
@jdoliner I see. No, I'm only seeing the `.scratch` files. The bash script for the pipeline I attached would list all files under `/pfs`.

**Comment by gpkc** [comment]
OK I think I figured this out. The problem is actually that the bash command `find` won't show symlinks. So you have to pass the `-L` flag to it.
The `.scratch` showing up I guess is fine. Just ignore it and run the `find` command with the `-F` flag on `/pfs/input-repo`.
