### ISSUE TITLE
Go client ListCommit bug

### ISSUE THREAD

**Issue by tsiutsiu** [pachyderm/pachyderm#4252]
**What happened?**:
It seems the "up to" commit boundary is included but not the "from" one when using ListCommit. 

**What you expected to happen?**:
As per the documentation, I expect to see a list of commits with both the "from" and "to" commit boundaries included.

**How to reproduce it (as minimally and precisely as possible)?**:
Pre-requisite: Create a repo and commit some files to it.

Then run the following code by 
a) substituting [to_commit_goes_here] [from_commit_goes_here] with upper and lower boundary commits you wish
b) putting same commit value in both upper & lower boundaries

package main

import (
	"fmt"
	"log"

	"github.com/pachyderm/pachyderm/src/client"
)

func main() {

	pachClient, err := client.NewFromAddress("localhost:30650")

	if err != nil {
		log.Fatal(err)
	}

	ls, err := pachClient.ListCommit("fruits", "[to_commit_goes_here]", "[from_commit_goes_here]", 0)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(ls)

}

**Anything else we need to know?**:
If you decide the functionality will be that the "from" commit boundary not included please check case (b) as current one is buggy -->  If you put the "from" and "to" commit being the same, you should be getting 1 commit back (for "from" not included, "to" included) but you get 0.

**Environment?**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
pachctl             1.9.7               
pachd               1.9.7 

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
local deployment (minikube)

- OS (e.g. from /etc/os-release): macOS Mojave 10.14.6

**Comment by JoeyZwicker** [comment]
> As per the documentation, I expect to see a list of commits with both the "from" and "to" commit boundaries included.

@jdoliner Is this something we should update in the docs only are there functionality changes?

**Comment by jdoliner** [comment]
I think the behavior we have right now is the behavior we want but the docs are incorrect. They currently read: 

```golang
// If `to` is given, only the ancestors of `to`, including `to` itself,
// are considered.
// If `from` is given, only the descendents of `from`, including `from`
// itself, are considered.
```

And should be changed to:

```golang
// If `to` is given, only the ancestors of `to`, including `to` itself,
// are considered.
// If `from` is given, only the descendents of `from`, not including `from`
// itself, are considered.
// If `to` and `from` are the same commit not commits will be returned.
```

The use case for `to` and `from` is to check for commits on a branch since a commit that you received previously. So the most common invocation is:

```
pachctl list commit repo@master --from <previous-commit>
```

With the semantics we have now you can run that command and all the commits it returns are guaranteed to be new commits. If that invocation returned `<previous-commit>` when there hadn't been any commits to `master` you'd have to check the commits to see if it's actually new.
