### ISSUE TITLE
get-file with a nonexistent commit should report that commit does not exist

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#428]
Right now it outputs an error message like `rpc error: code = 2 desc = diff sum2/6a6d6d48860b482fae28bcc456ee0d76/19 not found`

**Comment by sjezewski** [comment]
@derekchiang - where exactly do you expect the cleaner error message? I assume you mean a better error message for CLI users. (So this would correspond to the pachctl binary).

We probably still want the full grpc error even at the client level, because some of the grpc codes tell a client when its appropriate/not to retry.

**Comment by derekchiang** [comment]
Yeah showing grpc error might be fine.  I guess I just wanted an error message that would make it clear that the commit does not exist.  The current error message is indecipherable for users who don't know what diffs are.

**Comment by derekchiang** [comment]
Actually after a little more thought, I think showing grpc errors on the client side is probably not a good idea.  It just makes the error messages ugly and the fact that we are using grpc is an implementation detail anyways.

I found [this function](https://godoc.org/google.golang.org/grpc#ErrorDesc) that can be used to expose the original error (i.e. getting rid of the grpc wrapper error).  We don't have to do it as part of fixing this issue, but that's probably what we want to do at the CLI in the long term.

**Comment by sjezewski** [comment]
Yea, I was using that function already in the CLI to only print the error description. Having a friendly message like that for users of the CLI makes sense. I'll be trying to standardize that too.

But grpc errors (in particular the [codes](https://godoc.org/google.golang.org/grpc/codes)) tell a client when its appropriate to retry and when its not. So we def want to use grpc errors where we can. 

I'm fine w scrubbing the error messages that our client returns. That makes sense to me. And that will be pretty easy to do across the board in the client code.
