### ISSUE TITLE
`start transaction` should throw a warning or error if there's already a pending transaction

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4300]
`pachctl start transaction` doesn't throw a warning or error if the operation will overwrite an existing transaction ID in the pachyderm config, leading to unintuitive behavior like this:

```
$ pachctl start transaction
Started new transaction: f2f86e0f-2d7b-4708-b9f7-5dae738ee6c6
$ pachctl start transaction
Started new transaction: 5e083ef7-808e-4bef-bec8-1e6db22b8d96
$ pachctl finish transaction
Completed transaction with 0 requests: 5e083ef7-808e-4bef-bec8-1e6db22b8d96
$ pachctl finish transaction
no active transaction
$ pachctl list transaction
TRANSACTION                          STARTED        OPS
f2f86e0f-2d7b-4708-b9f7-5dae738ee6c6 32 seconds ago 0
```

Instead, `pachctl` should throw a warning or error if there's already a transaction ID in the pachyderm config.

**Comment by farhaanbukhsh** [comment]
can I pick this up? How can I reproduce this bug? Thanks in advance :smile:

**Comment by ysimonson** [comment]
Please feel free! The above commands should demonstrate the bug - the issue being that the first transaction started (`f2f86e0f-2d7b-4708-b9f7-5dae738ee6c6`) is "lost" since it is overwritten when the second transaction is started. What we'd want is to throw an error when starting a transaction if there's already one.

**Comment by farhaanbukhsh** [comment]
I was able to reproduce it and have started to work on a work in progress for this.

**Comment by ysimonson** [comment]
That won't work because it's valid for multiple users to concurrently have different transactions. Fortunately the solution is a bit simpler: we just need to check if the current user already has a transaction (by checking the config) when starting a transaction.

**Comment by farhaanbukhsh** [comment]
Raised a pr for this https://github.com/pachyderm/pachyderm/pull/5010

**Comment by farhaanbukhsh** [comment]
Hey @ysimonson just a gentle reminder I have raised a PR for this, please have a look whenever you find some extra time.

Sorry for nudging so much. 

Thanks a ton in advance ☺️

**Comment by ysimonson** [comment]
No problem! I was planning to pick up review once the colorized terminal output is merged, in case someone else picked up review in the mean-time, and because I'll be offline for a couple days in the coming week.
