### ISSUE TITLE
Pipelines getting stuck (blocking on parent commit)

### ISSUE THREAD

**Issue by gpkc** [pachyderm/pachyderm#4304]
**What happened?**:

It is happening relatively consistently that pipelines get stuck when some error occurs for some datums. When seeing the logs for the pipelines on kubernetes, it shows`blocking on parent commit`, even though that commit shows up as closed when inspected. This is still happening on 1.9.8.

**What you expected to happen?**:

The jobs should keep going.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a pipeline that takes a few seconds to run, sometimes fail, and has error handling. Example:

```
{
  "pipeline": {
    "name": "pipeline-error"
  },
  "description": "",
  "input": {
    "pfs": {
      "repo": "input",
      "glob": "/*"
    }
  },
  "transform": {
    "image": "ubuntu",
    "cmd": [
      "/bin/bash"
    ],
    "stdin": [
      "echo Starting...",
      "sleep 5",
      "if [ $(( RANDOM % 100 )) -gt 40 ]",
      "then",
      "   echo Error...",
      "   exit 1",
      "fi",
      "echo Done"
    ],
    "err_cmd": [
      "echo",
      "\n\n===== Handled the error! =====\n\n"
    ]
  }
}
```

Create a bunch of commits to its input repository. I have used this code to do that (`pachyderm_python` version 1.9.7):

```
import json
import random

import python_pachyderm

client = python_pachyderm.PfsClient()

datums = range(1, 15)

for datum in datums:
    print(datum)
    filename = f"{datum}.json"

    with client.commit("input", "master") as c:
        data = {
            "id": random.randint(0, 10000),
        }

        client.put_file_bytes(c, filename, json.dumps(data).encode(), overwrite_index=0)
```

After pushing those commits, watch `pachctl list job` until a job fails and is error handled. After that, and before the pipeline finishes processing the other commits, run a `pachctl update pipeline` on that pipeline. This will close all its outputs commits and start a new one (let's call it commit `A`). When this new commit is processed, it will provide the remaining datums.

Wait for this new processing to finish, and run the Python script above again (i.e. issue more commits to the input repo). They will get stuck on `running` and if you check the kubernetes logs, they will show `blocking on parent commit "A"`, even though `A` is finished.

**Anything else we need to know?**:

`pachctl fsck` returns `No errors found.`

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
$ pachctl version
COMPONENT           VERSION             
pachctl             1.9.8               
pachd               1.9.8
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
GKE but also happens on EKS.
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by itssimon** [comment]
I'm having a similar issue, except my pipeline is stuck in status "merging". Every pod of that pipeline logs the following message and then stops doing anything.

```
blocking on parent commit "f2d0af230fc644068723cf29fec77072" before writing to output commit "e41c379f4d5c495dac5ea5a50206d1aa"
```

In my case, the pipeline has made a lot of API requests that we're paying for. I don't really want to execute that again due to the cost. Is there any way how I can recover from this without deleting and recreating the pipeline?

**Comment by JoeyZwicker** [comment]
I was able to repro this following approximately the steps above (used pachctl instead of python client). Storage logs show:

```
2019-11-19T01:49:50Z ERROR pfs.BlockAPI.Obj.GetTag {"duration":0.105709389,"error":"tagGetter: tag 7939942c477c1231a4a5fca2af264f11a7443cbdb926baa81f1eb506b41b52726f5d not found","request":{"name":"7939942c477c1231a4a5fca2af264f11a7443cbdb926baa81f1eb506b41b52726f5d"},"response":{}} []```

Similar in `user` logs:
```
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.802953761Z","message":"blocking on parent commit \"ea2b1df3dd1e49b0a27c7e0c9c13f241\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.817275356Z","message":"blocking on parent commit \"9d04adf281234a8d8f979976c072b9cf\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.826083260Z","message":"blocking on parent commit \"8d165088498a424288400c90ee2e2a76\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.835407359Z","message":"blocking on parent commit \"9945276814674fcdb9e2452b6853850f\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.843668524Z","message":"blocking on parent commit \"a327dcffe59848a2bbd330ba0873fb38\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.854208691Z","message":"blocking on parent commit \"e4e4473f42c743a6afc0e965a03ed733\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:32.863666020Z","message":"blocking on parent commit \"5ad63823798744e6b5ba753ac402e374\" before writing to output commit \"d7da9df8e76d4bb4887d9de00bd94e74\""}
{"pipelineName":"pipeline-error","workerId":"pipeline-pipeline-error-v2-29fn8","ts":"2019-11-19T01:55:51.672987567Z","message":"worker: watch closed or error running the worker process: acquire/process/merge datums for job 4de1f397c0c446fab022a489a329b100 exited with err: error claiming/processing chunk: tagGetter: tag 7939942c477c1231a4a5fca2af264f11a7443cbdb926baa81f1eb506b41b52726f5d not found; retrying in 14.705225937s"}
```

This repro is currently active in hub cluster `g7rq85zp3k` if that's helpful

**Comment by JoeyZwicker** [comment]
@nitinjainsj I see this was marked in high-priority bugs -- I presume that means I should leave the test cluster with this repro still up and running?

**Comment by gpkc** [comment]
Hey, is there something more I can do to help with this? On our end this issue is a bit breaking, since if any error occurs when running a pipeline, you essentially need to redeploy everything to reset the commit history. How are people currently dealing with this? Or is it not happening with others?

**Comment by brycemcanally** [comment]
Hey @gpkc , are you still using 1.9.8? I think this may have been fixed by #4310, which was in the 1.9.9 release. What I think happened in your case (based on our repro) is that we were recording a datum that was recovered as skippable, which resulted with us erroring when attempting to cache (the tag getter error message) the non-existent metadata of the recovered datums for merging.

**Comment by gpkc** [comment]
Okay! Yes, I was waiting for this bug to be fixed before upgrading. I'll upgrade and test. Thanks!!

**Comment by nitinjainsj** [comment]
Please reopen if this happens again.
