### ISSUE TITLE
[DOC] Improve pachctl docs and examples

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4306]
Check all pachctl commands and add/improve descriptions/examples for these commands.

**Comment by JoeyZwicker** [comment]
for example:

run pipeline has a --job flag that is not documented. Similarly, it says it has a --reprocess flag, which isn't actually implemented.

**Comment by mindthevirt** [comment]
This has been completed as part of the 2.0 release. One-off issues should be opened up as bug reports.
