### ISSUE TITLE
Broken bulletpoint styling in docs

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4307]
The bulletpoints on this page are not rendering correctly: https://docs.pachyderm.com/latest/reference/s3gateway_api/

**Comment by svekars** [comment]
Thanks, @yusef. In general, we need to make sure that we add a blank line between a paragraph and a list. For example:

```
To do:

1.
1.
1.
```

instead of:

```
To do:
1.
1.
1.
```

The latter won't render correctly.
