### ISSUE TITLE
Automate versioned docs

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#4320]
- [ ] Bash/misc changes:
  - [ ] ~Build docs in a docker container (for consistent builds)~
    - [ ] ~Modify `make doc` to run this process~
  - [x] Rename `latest` to `master`
  - [x] Copy `master` to the most recent feature branch in `make point-release`
- [ ] Netlify changes:
  - [x] ~Compare output hashes in a test, as with our .proto files (instead of rebuilding output)~
  - [x] Symlink `latest` to the most recent version
  - [x] Clarify in version selector which version is latest

**Comment by svekars** [comment]
I think this is resolved now. Feel free to reopen @msteffen if needed.
