### ISSUE TITLE
rapidly opening and closing /pfs/out in a spout can cause it to miss data

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4327]
**What happened?**:

I wrote a spout that doesn't open /pfs/out until it sees one datum, then writes the datum, closes /pfs/out, and processes the next datum until the queue is empty. When the datums would come in at a rate of less than 100ms apart or so, the spout started missing data.  This was particularly a problem on launch, if there was data in the queue.  Adding a delay after closing /pfs/out of over 150ms seemed to solve the issue.

**What you expected to happen?**:
I expected data to be processed at speed correctly.

**How to reproduce it (as minimally and precisely as possible)?**:
1. Create a spout that reads a data source one line time, opening /pfs/out, writing the line of data to a file, and closing /pfs/out. (Mine read a kafka queue, source attached along with various logs).
2. Add data to the file more rapidly than one line per 100ms.
3. Datums will be missed.

**Anything else we need to know?**:
My script for creating the cluster, my spout code, and logs are attached.  I'm going to check all my source into examples/spouts/go-kafka-spout as a PR for @JoeyZwicker to review.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.13
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS (see script)
- OS (e.g. from /etc/os-release):
- Others:
[cluster.txt](https://github.com/pachyderm/pachyderm/files/3826652/cluster.txt)

[main.go.txt](https://github.com/pachyderm/pachyderm/files/3826655/main.go.txt)

**Comment by pappasilenus** [comment]
@adelelopez @jdoliner reraising attention on this.  Note that the kafka-spout example has a delay built into its message loop because of this issue; this bug number is referenced there.

**Comment by ysimonson** [comment]
@pappasilenus just to double-check, did you confirm that this wasn't an issue on the kafka-side? e.g. if you print messages as they're read from kafka, they're all there?

**Comment by pappasilenus** [comment]
That was the first thing I checked.
