### ISSUE TITLE
Faster datum skipping

### ISSUE THREAD

**Issue by itssimon** [pachyderm/pachyderm#4340]
**What is the goal / desired outcome?**

At the moment pipelines take too much time skipping datums. I have 5 sequential pipelines which after running for a while have processed about 10,000 datums each. Committing one extra file to the input repo now takes about one hour to complete, even though the actual work shouldn't take more than 2 minutes. This is due to the 5 pipelines taking about 10 minutes each to skip all the previously processed datums.

**If there is a way to accomplish this today via workaround, what does that require?**

Periodically recreating the pipelines helps, but defeats the purpose of Pachyderm.

**Comment by jdoliner** [comment]
I think a big chunk of the time is being spent on the merge here. Merging together all the datums into a single resulting filesystem takes a good chunk of time and resources, even though there's only a little bit of new data there. We have some big changes to the storage layer coming that should make the merge process a lot faster. In terms of the datum skipping I'm not sure how much faster we can make that, right now I think it's basically just a look up in a go map (if the previous job succeeded), and based on the numbers here it seems like skipping a datum is only taking about 1ms per datum.

**Comment by echohack** [comment]
Hi @itssimon. You should see this performance improved dramatically in our upcoming 2.0 release of Pachyderm. We already have alpha releases available if you'd like to check if your issue is resolved there.

I'm closing this issue out for now. If you continue seeing this slow behavior in 2.0, please feel free to reopen.
