### ISSUE TITLE
Just enough pods in standby mode (smarter replication controller)

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4344]
**What is the goal / desired outcome?**

Currently, in standby mode, the rc will schedule the number of pods specify in `parallelism`, and keep those pods up until all the datums are processed. The leads to sub-optimal resource utilization: if the number of datums to process is less than the parallelism value some pods are doing nothing.
Therefore it would be nice if the number of pods could be scaled up and down depending on the number of datums to process (up to the limit specified in `parallelism` of course).
This would lead to huge speed-up time at the very modest cost of perhaps restarting pods more often (but this cost almost nothing).

To give a better picture of why this might be interesting: cf #4345

**Comment by jdoliner** [comment]
Closing this in favor of number #3065. This is definitely something we'd like to do, but is hard for the reasons outlined in that issue. However it should get easier in the near future thanks to #4354.
