### ISSUE TITLE
pachctl logs -f  with -p flag should not exit if pipeline updated

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4358]
**What is the goal / desired outcome?**

If you follow the logs for a pipeline, and the pipeline is updated, the pachctl command following the logs exits.  Rerunning the command will follow the logs again.

Submitting this as a feature request because it's not rightly a bug

**If there is a way to accomplish this today via workaround, what does that require?**

In the shell, when running the pipeline log, you can use a shell loop to force a reread when pachctl exits.  
```
while [ true ] ; do pachctl logs -p pipeline -f ; done
```

**(Optional) What is your proposal for a feature to solve this?**

Since we are hiding the fact that the pipeline is running in a particular pod from the user with this bit of syntactic sugar, the command should not exit.  pachd and pachctl should handle the cutover to a new pod seamlessly, perhaps even putting a "pod updated" event into that log stream.

**Comment by pappasilenus** [comment]
@svekars It might be nice to include this in the documentation for the logs command, warning users that it will exit when the pipeline is updated and recommending use of the workaround.

**Comment by ysimonson** [comment]
I can tackle this, since I worked on a similar issue recently

**Comment by ysimonson** [comment]
Unfortunately, I don't think there's a way to do this presently [without introducing a great deal of complexity](https://github.com/pachyderm/pachyderm/pull/4361). I'm going to close this, but will reopen if I can come up with a different way to do this.
