### ISSUE TITLE
standby pipeline not removed after run

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4371]
**What happened?**:
Sometimes a standby pipeline is not removed. Unfortunately this is not consistent: sometimes it is, sometimes not. I check that `pachctl inspect pipeline xxx --raw | grep standby` and it shows `true`. Of course I check that there was no input to be processed. I can see that after the job is complete, the replicationController remains set to `1` instead of going down to `0`.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.11.10
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.7

**Comment by JoeyZwicker** [comment]
Is there anything else you can provide or think of to get us repro steps? Without that, it might be pretty hard to track down what's going on here because it's not something that I've seen before.

**Comment by marcadella** [comment]
Difficult for me to isolate a reproducible setup as it happens a bit randomly. However it might be related to issues with `pachctl delete all (`#3724 and/or #4375):
I tend to use `kubectl delete all` to wipe out my cluster, then re-deploy my pipelines (using the same names). Because `pachctl delete all` doesn't seem to be doing it's job properly, could it be that pachyderm uses some old data to the new pipelines?
For instance, let's suppose that pipeline `A` is running. etcd or minio store that piece of information. I run `kubectl delete all`, but because it doesn't do it's job properly, the fact about `A` running is still there somewhere. Now I re-create pipeline `A` and pachyderm thinks it is running (even though it is not) and sets the replicacontroller to 1.

**Comment by msteffen** [comment]
Reopening because this is fixed in 1.11.5 but not in master

**Comment by msteffen** [comment]
Fixed in master, closing
