### ISSUE TITLE
Add an example of using `pod_patch` and `pod_spec`.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4378]
**Provide a link to the page with an issue:**

**Describe what is wrong:**

We don't have an example of using `pod_patch` and `pod_spec`

**Describe the suggested changes:**

Add an example of those things.

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by svekars** [comment]
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1575431025362700?thread_ts=1575420129.355400&cid=C3UN0S0Q0

**Comment by svekars** [comment]
Resolved by https://github.com/pachyderm/pachyderm/pull/5026
