### ISSUE TITLE
Error when input is /

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4380]
Having a pipeline defined as follows:
```
"input": {
    "pfs": {
          "name": "myOtherPipeline",
          "repo": "myOtherPipeline",
          "branch": "master",
          "glob": "/"
        }
      }
```
where myOtherPipeline is a pipeline (not an input repo), fails with the following error message:
`errored downloading data after 341.093933ms: InvalidRange: The requested range is not satisfiable\n\tstatus code: 416`

Note that it would succeed if the input path was anything else than just `/` (for instance `/data`).
This happens one cluster (cf below), but not on a minikube install running k8s 1.16 and Pachyderm 1.9.8.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.11.10
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.7

**Comment by ysimonson** [comment]
Here's another instance of 416's from PFS calls to object storage: https://github.com/pachyderm/pachyderm/issues/4254

**Comment by jdoliner** [comment]
@marcadella which object store are you running on?

**Comment by marcadella** [comment]
Minio 2018-09-01T00:38:25Z

**Comment by marcadella** [comment]
I updated the version of Minio to `2019-10-12T01:39:57Z` and Pachyderm to 1.9.9 and I still get the same issue.

**Comment by marcadella** [comment]
I tested again by changing `/` -> `/run` and I still get the same issue. All the pipelines of my workflow work fine except 4 who all have inputs like this:
```
{
  "union": [
    {
      "cross": [
        {
          "pfs": {
            "name": "ENV_SCRIPT",
            "repo": "reads",
            "branch": "master",
            "glob": "/env_mgmt_egressAssembly.sh"
          }
        },
        {
          "pfs": {
            "name": "assembly_fastqpairer",
            "repo": "assembly_fastqpairer",
            "branch": "master",
            "glob": "/run"
          }
        },
        //some other pipelines looking like the one above
        }
      ]
    },
    {
      "pfs": {
        "name": "__METADATA__",
        "repo": "reads",
        "branch": "master",
        "glob": "/metadata.txt"
      }
    }
  ]
}
```
Is there anything special about this definition???

**Comment by marcadella** [comment]
By looking at the log of the `storage` container, I could find out exactly which file could not be downloaded:
```
2019-12-09T14:09:17Z ERROR pfs.BlockAPI.Obj.GetBlocks {"duration":0.205009542,"error":"InvalidRange: The requested range is not satisfiable\n\tstatus code: 416, request id: 15DEB935141C2F98, host id: ","request":{"blockRefs":[{"block":{"hash":"13e98f61a9874e61923ae359dedc414d"},"range":{}},{"block":{"hash":"3711adf813774f36a08285ad3e9fe587"},"range":{"lower":97157,"upper":97157}}]}} []
2019-12-09T14:09:17Z ERROR pfs.API.GetFile {"duration":0.274540996,"error":"rpc error: code = Unknown desc = InvalidRange: The requested range is not satisfiable\n\tstatus code: 416, request id: 15DEB935141C2F98, host id: ","request":{"file":{"commit":{"repo":{"name":"taxonomy_mapseq_1-2-3"},"id":"19b1f01b870e4f099ae3e488563042e0"},"path":"/run/meta/touch"}}} []
```
`/run/meta/touch` is an empty file (created with `touch`).
Created bug report #4395.
