### ISSUE TITLE
policy error during make-launch

### ISSUE THREAD

**Issue by kevinemoore** [pachyderm/pachyderm#439]
I closed my previous make-launch issue after getting much farther into the process. I got kubernetes up with make launch-kube, but now I'm seeing an error telling met that the pachd replication controller is invalid because it's security context is disallowed by policy (error below). Any help will be greatly appreciated!

air:kmoore>make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy ./src/server/cmd/pachctl-doc
kubectl  create -f etc/kube/pachyderm.json
serviceaccount "pachyderm" created
replicationcontroller "etcd" created
service "etcd" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:32080,tcp:32081,tcp:32082) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "rethink" created
replicationcontroller "rethink" created
job "pachd-init" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30650) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "pachd" created
The ReplicationController "pachd" is invalid.
spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy
make: *** [launch] Error 1

**Comment by jdoliner** [comment]
Hmm, could you do `kubectl version` for me?

**Comment by kevinemoore** [comment]
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree"}

**Comment by jdoliner** [comment]
Hmm, so one thing I'm a little confused about. It looks like your server is `v1.2.1` there but `make launch-kube` seems to use the 1.2.2 docker image. What commit are you on that you did `make launch-kube` from?

**Comment by kevinemoore** [comment]
commit 4fd38cd7d4c33b379b2a122d8f69b943c190cfaf
Author: Derek Chiang <derekchiang93@gmail.com>
Date:   Fri May 20 18:41:05 2016 -0700

    Minor update to pipeline spec to get rid of unwanted highlighting

**Comment by kevinemoore** [comment]
start-kube-docker.sh:
docker run \
    -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    gcr.io/google_containers/hyperkube:v1.2.2 \
    /hyperkube kubelet \
        --containerized \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --allow-privileged=true

**Comment by kevinemoore** [comment]
I see the --privileged=true and --allow-privileged=true options so I was surprised to see that error.

**Comment by jdoliner** [comment]
Hmm, what does `docker ps` give you?

**Comment by kevinemoore** [comment]
OK. I think I see the permission issue. I was getting an instance of "localkube" (from Redspread) running too. I think it was talking to kubectl. But, when it stops, I can't get hyperkube to talk to kubectl.

**Comment by jdoliner** [comment]
Ahhh that makes sense. Where's docker running is it on your local machine or is it running on a vm / in the cloud? If the later you may need to forward port `8080` from your local machine to wherever docker is running. While you're at it you may want to forward `30650` as well since that's what pachyderm uses. If you're using docker machine this command will do what you want:

```shell
$ docker-machine ssh <docker-machine> -fTNL 8080:localhost:8080 -L 30650:localhost:30650
```

**Comment by kevinemoore** [comment]
I'm using docker-machine and I have the port forwarding running. It seems to work for localkube, but not hyperkube.

**Comment by jdoliner** [comment]
Hmm, I'm not familiar with `localkube` is it possible it wrote a file to `~/.kube/config`? Which kubectl is using?

Also it might be that when you did the port forwarding `localkube` was already bound to port `8080` in which case I think it silently fails. So you might have to kill the port forwarding process and restart it.

**Comment by kevinemoore** [comment]
Current status:
air:kmoore>docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
8c3c513a9583        gcr.io/google_containers/hyperkube-amd64:v1.2.2   "/hyperkube apiserver"   5 minutes ago       Up 5 minutes                            k8s_apiserver.78ec1de_k8s-master-127.0.0.1_default_4c6ab43ac4ee970e1f563d76ab3d3ec9_e6b69f86
a3ffa9d5da5c        gcr.io/google_containers/hyperkube-amd64:v1.2.2   "/setup-files.sh IP:1"   5 minutes ago       Up 5 minutes                            k8s_setup.e5aa3216_k8s-master-127.0.0.1_default_4c6ab43ac4ee970e1f563d76ab3d3ec9_6b10c2e2
e380ddf9f1b5        gcr.io/google_containers/hyperkube-amd64:v1.2.2   "/hyperkube scheduler"   5 minutes ago       Up 5 minutes                            k8s_scheduler.fc12fcbe_k8s-master-127.0.0.1_default_4c6ab43ac4ee970e1f563d76ab3d3ec9_d65b389a
5cef63c89019        gcr.io/google_containers/hyperkube-amd64:v1.2.2   "/hyperkube proxy --m"   5 minutes ago       Up 5 minutes                            k8s_kube-proxy.9a9f4853_k8s-proxy-127.0.0.1_default_5e5303a9d49035e9fad52bfc4c88edc8_7b9baca2
46ac3d82190d        gcr.io/google_containers/hyperkube-amd64:v1.2.2   "/hyperkube controlle"   5 minutes ago       Up 5 minutes                            k8s_controller-manager.70414b65_k8s-master-127.0.0.1_default_4c6ab43ac4ee970e1f563d76ab3d3ec9_d0b7eb9c
ae699fd5f845        gcr.io/google_containers/pause:2.0                "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD.6059dfa2_k8s-etcd-127.0.0.1_default_1df6a8b4d6e129d5ed8840e370203c11_bf50a671
7dfca217bc92        gcr.io/google_containers/pause:2.0                "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD.6059dfa2_k8s-master-127.0.0.1_default_4c6ab43ac4ee970e1f563d76ab3d3ec9_ca8f6040
e83db715cd4f        gcr.io/google_containers/pause:2.0                "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD.6059dfa2_k8s-proxy-127.0.0.1_default_5e5303a9d49035e9fad52bfc4c88edc8_dc7f2ccb
1f21f182738f        gcr.io/google_containers/hyperkube:v1.2.2         "/hyperkube kubelet -"   5 minutes ago       Up 5 minutes                            distracted_panini
83b10a82ee5e        weaveworks/weaveexec:1.4.5                        "/home/weave/weavepro"   5 minutes ago       Up 5 minutes                            weaveproxy
9fefc52184d0        weaveworks/weave:1.4.5                            "/home/weave/weaver -"   5 minutes ago       Up 5 minutes                            weave
b0d5227c0473        gcr.io/google_containers/etcd:2.0.9               "/usr/local/bin/etcd "   38 minutes ago      Up 38 minutes                           mad_albattani
air:kmoore>ps -ef | grep ssh
  501  1366     1   0 11:35AM ??         0:00.28 /usr/bin/ssh-agent -l
  501 10967     1   0  5:39PM ??         0:00.00 /usr/bin/ssh -F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/kmoore/.docker/machine/machines/dev/id_rsa -p 52289 -fTNL 8080:localhost:8080 -L 30650:localhost:30650
  501 11064   985   0  5:45PM ttys000    0:00.01 grep ssh

**Comment by kevinemoore** [comment]
air:kmoore>kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
The connection to the server 192.168.99.100:8080 was refused - did you specify the right host or port?

**Comment by kevinemoore** [comment]
Looks like it's connecting to the client, but not the server?

**Comment by jdoliner** [comment]
"Client" just means kubectl in this case so it's just reporting its own version. Does 192.168.99.100 resolve to your machine? If so we know it's not `~/.kube/config` and I'd try killing the port forwarding process and restarting it.

**Comment by kevinemoore** [comment]
~/.kube/config could be the problem. Should I have anything in that file? 

cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: 192.168.99.100:8080
  name: localkube
contexts:
- context:
    cluster: localkube
    user: ""
  name: localkube
current-context: localkube
kind: Config
preferences: {}
users: []

**Comment by jdoliner** [comment]
Nope, just rm it.

**Comment by jdoliner** [comment]
This seems to be resolved. Please reopen if not.
