### ISSUE TITLE
Package pachyderm/yaml.v3 is missing a version

### ISSUE THREAD

**Issue by LaurentGoderre** [pachyderm/pachyderm#4392]
Trying to build pachctl for docker images in LaurentGoderre/docker-pachctl/issues/2 and the build fails with `gopkg.in/pachyderm/yaml.v3@v3.0.0-20191017015716-76e7a8e4bde1: invalid version: unknown revision 76e7a8e4bde1` Can this version be created so that the docker image can get created for that version. 

Note that the version is also referenced here: https://github.com/pachyderm/pachyderm/blob/3926b990528e97e08c825f0b54a898a249c8e33f/go.mod#L124

**Comment by ysimonson** [comment]
Sorry about that! We're currently facing an issue with the latest on master that should be fixed once #4290 is merged in. In the meantime, the latest release should work.

**Comment by ysimonson** [comment]
This should be fixed; feel free to re-open if you're still seeing the issue with the latest on master.
