### ISSUE TITLE
Clarify details of env vars

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#4411]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/reference/pipeline_spec/#environment-variables
https://docs.pachyderm.com/latest/deploy-manage/deploy/environment-variables/#pipeline-worker-environment-variables

**Describe what is wrong:**

**Describe the suggested changes:**
A few minor improvements to discussion of env vars. 

1. clarify that pipeline worker env vars only exist when pachyderm injects them during a job (since they change). You can't exec in and see the full list: https://pachyderm-users.slack.com/archives/GJSKMC0F6/p1576112841360300
2. Per soon-to-opened GH issue by JD, we should have a "Pipeline worker environment" reference doc that covers a variety of topics. The pipeline worker env half of the doc should live as part of that doc instead of under deployment. 
3. Make sure pipeline spec Env Vars section links to full envars doc (the current one and then later, the new "Pipeline worker environment" doc mentioned above. 
**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by svekars** [comment]
I think we have addressed most of these concerns in the last few PRs and the resulting doc is here: https://docs.pachyderm.com/latest/deploy-manage/deploy/environment-variables/. If something is missing, feel free to reopen.
