### ISSUE TITLE
Update gcloud cluster setup to use GKE

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#4414]
https://docs.pachyderm.com/latest/contributing/gcloud-setup/

This doc needs to be updated to use GKE rather than a single VM

**Comment by svekars** [comment]
Can this issue be closed @chainlink ?

**Comment by chainlink** [comment]
Yep. These instructions are old and shouldn't be used anymore

**Comment by mindthevirt** [comment]
I believe this issue should not be closed as the contribution guide still show gcloud and not gke.

**Comment by lbliii** [comment]
https://pachyderm.atlassian.net/browse/DOC-135
