### ISSUE TITLE
Create a pipeline environment doc

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4423]
This came out of an offline discussion with @JoeyZwicker about pipeline docs. I think we should have a doc dedicated to the environment that use code runs in. This would include:

- The env-vars that the pipeline code can access. Right now this is documented in the [pipeline spec](https://docs.pachyderm.com/latest/reference/pipeline_spec/#environment-variables) and [configure env vars doc](https://docs.pachyderm.com/latest/deploy-manage/deploy/environment-variables/#pipeline-worker-environment-variables). I think the latter location doesn't make a ton of sense for pipeline environment variables, because it's about configuring and deployment of Pachyderm, ie env vars that you set to modify the behavior of Pachyderm, rather than env vars that Pachyderm gives to worker code. Once we have a dedicated doc for pipeline environment I think we should remove the pipeline env vars from that doc and have it just be about configuration env vars.

- What `/pfs` looks like, this would be a good place to note that the directories under `/pfs` are actually symlinks to directories and not traditional directories.

- Things that get inherited from the docker container image, such as the user that the code runs as, the entrypoint and working dir.

- We should note that this environment is setup by our worker code, not by kubernetes. So it won't be visible when you exec into a pod, it's only visible from your transform that gets execced.

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by svekars** [comment]
I think we have addressed most of these concerns in the last few PRs and the resulting doc is here: https://docs.pachyderm.com/latest/deploy-manage/deploy/environment-variables/. If something is missing, feel free to reopen.
