### ISSUE TITLE
Implement an interactive Pachyderm shell

### ISSUE THREAD

**Issue by nitinjainsj** [pachyderm/pachyderm#4446]
**What is the goal / desired outcome?**
Implement a pachyderm shell, which can provide auto completion of commands and arguments with necessary help text.

The goal is to reduce user errors, provide necessary context information, and improve pachctl ergonomics.

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
This has been implemented and will land in 1.10.
