### ISSUE TITLE
Address PR feedback in #4447

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4451]
#4447 was merged without addressing the (non-breaking) PR feedback, so we could get it in the next release. At some point, we should address the PR feedback; namely:

* https://github.com/pachyderm/pachyderm/pull/4447#discussion_r360216167
* https://github.com/pachyderm/pachyderm/pull/4447#discussion_r360216206

**Comment by brycemcanally** [comment]
@ysimonson I provided responses to the comments. It probably makes sense to just discuss in that PR, then make a separate PR with any changes we decide on.

**Comment by ysimonson** [comment]
Left some follow-up comments
