### ISSUE TITLE
cannot apply the material to layer

### ISSUE THREAD

**Issue by uki04iii** [pachyderm/pachyderm#4460]
HELLO.
At first, this is my first time to use Pachyderm for rhinoceros, and i donnot have any skills for computer.

I'm sorry but it may be very easy question for you (but i cannot solve because my lack of skills and understandings)

my problem is that, I cannot apply the materials to layer in the material window.
I cannot find the "Apply Material button" under the Delete Material Button (Vimeo tutorial shows me the button there.)

I am very confused cause it's the earliest steps to use this plug-in. (I'm crying)

Please teach me the solution.
And, is anyone in the same situation?(teach me!)

Thank you for reading

**Comment by uki04iii** [comment]
in addition, i cannot find the Scattering and Transparency windows (There is only the absorption window!)

**Comment by uki04iii** [comment]
I can install materials to each objects from property window

**Comment by jdoliner** [comment]
Hi @uki04iii,

I think you have the wrong Pachyderm here, this is a standalone project for Data Science, not the acoustical simulation plug-in for Rhino. Sorry for the confusion, hope you find an answer.
