### ISSUE TITLE
Spout /pfs/marker file is never a valid symlink (existing marker file is not downloaded)

### ISSUE THREAD

**Issue by jfhamlin** [pachyderm/pachyderm#4462]
**What happened?**:

Spout `marker` files aren't available on spout restarts. The file is always a broken symlink.

**What you expected to happen?**:

After successfully outputting a `marker` file on the `/pfs/out` named pipe and completing a commit, the `/pfs/marker` file should contain the data last written.

**How to reproduce it (as minimally and precisely as possible)?**:

Leaving this high level given that the feature isn't functional. A pipeline that:
1. logs the contents of `/pfs/marker` if it's present and a valid symlink
2. writes a non-empty `marker` file to the output tar pipe
3. and exits

should reproduce the issue. You'd expect step 1 to eventually print what is written in step 2. You'll find that it doesn't.

**Anything else we need to know?**:

The issue seems to be here: https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/api_server.go#L539. The marker file is only downloaded if the InspectFile call for an existing marker returns a “not found” error, which won't happen if there _is_ a marker file.

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.14.7
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.10
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws (eks)
- OS (e.g. from /etc/os-release):
- Others:

**Comment by adelelopez** [comment]
Hi James, I've been working on this issue and we have now determined the root cause + robust fix. We'll have the fix out shortly. Thank you for your patience.
