### ISSUE TITLE
Spout marker special cases may affect output files that happen to contain the string "marker" or "out/marker"

### ISSUE THREAD

**Issue by jfhamlin** [pachyderm/pachyderm#4463]
**What happened?**:

While trying to understand why spout markers weren't working, I came across the following lines:
https://github.com/pachyderm/pachyderm/blob/dd5dc4eadba2cb47a4ec433207c31f3ab6007b9c/src/server/worker/api_server.go#L969
https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L917

Both implement special handling of files that happen to contain the strings "marker" or "out/marker" in their names. 

**What you expected to happen?**:

I would expect more precise identification of this special file. As implemented, real errors may be ignored or files improperly overwritten if they happen to contain these strings in their names.

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.14.7
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.10
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws (eks)
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
Closing in favor of #4467 which has a proposal to fix this.
