### ISSUE TITLE
Spout marker improvements

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4467]
Spout markers as designed now are currently a little tricky to use correctly, they force you to emit a file called `marker` to mark your spot in the stream, which means that downstream pipelines need to be aware of that file, so that they can ignore it. It also means that if you happen to want to emit a file called `marker` then you're going to get weird behavior you didn't expect. 2 fairly simple changes should solve this.

- Make users explicitly declare their marker file, like so:

```proto
message Spout {
  bool overwrite = 1;
  Service service = 2;
  // when non-empty, files emitted with this name (or in this directory) will act as a marker
  // of the spouts progress and be given back to the spout when it reboots 
  string marker = 3;
}
```

- Don't emit this file into the same commit as rest of the output, have a separate branch, called `marker`, in the output repo of the spout that we commit to atomically with the output branch when the spout emits a marker.

Subsumes #4463

**Comment by jdoliner** [comment]
This has been implemented.

**Comment by pappasilenus** [comment]
Should this be closed, @nitinjainsj @jdoliner ?

**Comment by jdoliner** [comment]
Yup! Thanks for catching this.
