### ISSUE TITLE
Document interactive Pachyderm shell usage

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4469]
Document the functionality described in #4446

**Comment by JoeyZwicker** [comment]
There is a video of this being demoed and should be pretty easy to document, mainly with a few screenshots maybe a <2min video or gifs -- it's a pretty "visual" feature outside of the basics. 

We should also think about pushing beginner and intermediate users this direction. to be discussed further as part of "onboarding users" conversation.
