### ISSUE TITLE
`make docker-build` always recompiles

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4553]
`make docker-build` will always re-compile, even if there are no changes in the source code. This slows down the dev deployment process.

**Comment by jdoliner** [comment]
I think this means there's some sort of a bug in how we're passing in cached objects for the build. This is the Make task for `docker-build-pachd`:

```Make
docker-build-pachd: docker-clean-pachd
	docker run  \
		--env=CALLING_OS=$$(uname) \
		--env=CALLING_USER_ID=$$(id -u $$USER) \
		--env=DOCKER_GROUP_ID=$$(cat /etc/group | grep docker | cut -d: -f3) \
		--env=DOCKER_BUILD_FLAGS="$(DOCKER_BUILD_FLAGS)" \
		-v $$PWD:/pachyderm \
		-v $$GOPATH/pkg:/go/pkg \
		-v $$HOME/.cache/go-build:/root/.cache/go-build \
		--name pachd_compile $(COMPILE_RUN_ARGS) $(COMPILE_IMAGE) /pachyderm/etc/compile/compile.sh pachd "$(LD_FLAGS)"
```

As you can see it's trying to map in `$GOPATH/pkg` and `~/.cache/go-build` which should in theory lead to builds being cached same as if they were built outside the container.

I also think this might be environment dependent, `make docker-build` takes under 12s when I haven't changed any code. Which I think pretty much has to mean that caching is working for me. I'm wondering if maybe this is related to the changes we've seen that lead to etcd and pachd data getting wiped out on docker for mac. I think both of those use `-v` mappings under the hood.

**Comment by ysimonson** [comment]
I suspect they're unrelated, because docker for mac _always_ recompiles from scratch, whereas etcd/pachd data gets wiped whenever the VM is restarted.

**Comment by msteffen** [comment]
FWIW, I think the question here is where the caching is happening. The go compiler re-uses build artifacts from `~/.cache/go-build`, so even if docker-is building from scratch every time, `make docker-build` should be fast after its first run because the go compiler, running inside the docker container, is not building from scratch every time.

**Comment by msteffen** [comment]
Out of curiosity, did we figure out why the `go` caching wasn't working in docker for mac?

**Comment by ysimonson** [comment]
TBH, no -- I just took the opportunity to do a general cleanup of the build process
