### ISSUE TITLE
Pachctl mount doesn't work on GKE.

### ISSUE THREAD

**Issue by wsxiaoys** [pachyderm/pachyderm#4558]
**What happened?**:
pachctl mount crashed after ls in mounted dir.

**What you expected to happen?**:
pachctl mount works as expected.

**How to reproduce it (as minimally and precisely as possible)?**:
In GKE container:
pachctl mount ~/pfs
cd ~/pfs && ls

**Anything else we need to know?**:
This seems to be a bug in upstream go-fuse as fixed in this commit:
https://github.com/hanwen/go-fuse/commit/fd7328faf9fdf75709f7ba7df7072aaf4eeb18b3#diff-ae3c684c76500760cbff9a5a9bf74ef4

https://github.com/hanwen/go-fuse/issues/276

Can pachyderm get an go-fuse upgrade?

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.13.11-gke.14
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE

**Comment by jdoliner** [comment]
Sure we can upgrade this.

**Comment by wsxiaoys** [comment]
In case anyone need a workaround, here's a patch
https://github.com/pachyderm/pachyderm/pull/4560/files
