### ISSUE TITLE
Pipeline shown as running even though pods are in ImagePullBackOff state

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4568]
**What happened?**: I created a couple of pipelines (one is a spout, one is not.) They both list as being running/starting:

```
% p list pipeline
NAME     VERSION INPUT                            CREATED        STATE / LAST JOB   DESCRIPTION 
consumer 1       (consumer_source:/ ⨯ producer:/) 12 minutes ago running / starting             
producer 1       none                             12 minutes ago running / starting
```

However, both pipelines are in `ImagePullBackOff`:

```
% k get all
NAME                             READY   STATUS                  RESTARTS   AGE
pod/dash-9b6c58cd5-mdm4r         2/2     Running                 0          20h
pod/etcd-db59f8c48-t29fx         1/1     Running                 0          20h
pod/pachd-cbbbf866c-r9w2k        1/1     Running                 0          20h
pod/pipeline-consumer-v1-lfnxj   0/2     Init:ImagePullBackOff   0          12m
pod/pipeline-producer-v1-vsqrc   0/2     Init:ImagePullBackOff   0          12m
```

**What you expected to happen?**: `list pipeline` should show a failure state for these pipelines

Somewhat related, but different issue: https://github.com/pachyderm/pachyderm/issues/3082

**Comment by jdoliner** [comment]
This seems like it might be specific to your setup, `ImagePullBackoff` is one of the k8s failure states that we have the ability to detect. And we have a test for it, `TestPipelineBadImage`, in our CI which I haven't seen failing. So we know this works in some cases.

**Comment by ysimonson** [comment]
This is an `ImagePullBackOff` for the init containers, because I had nuked some docker images, including worker. Though to be fair, I'm not sure that's a common enough failure mode for us to need to detect.

**Comment by marcadella** [comment]
Had the same issue: pipeline's pods are in state `pending` or `initializing` because of `MountVolume.SetUp failed for volume "pachyderm-storage-secret" : secret "pachyderm-storage-secret" not found`, but the pipeline is in state `running`.
I know the secret missing is my own deployment issue, but it would be nice that pipeline `running` really means in running state.

**Comment by ysimonson** [comment]
Dupe of #2925
