### ISSUE TITLE
Pachctl completion installation instructions are unclear

### ISSUE THREAD

**Issue by szeitlin** [pachyderm/pachyderm#4581]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/reference/pachctl/pachctl_completion/

**Describe what is wrong:**
This section is not sufficiently clear.

> Print or install the bash completion code. This should be placed as the file pachctl in the bash completion directory (by default this is /etc/bash_completion.d. If bash-completion was installed via homebrew, this would be $(brew --prefix)/etc/bash_completion.d.)

**Describe the suggested changes:**
Step-by-step, please, and be very clear about what goes where, e.g.

0. Find or create the bash completion directory, which is xx
1. Create a file named `pachctl` 
2. This file should contain xyz 

**Anything else we need to know?**

I'm on a mac, for whatever that's worth. 

**Environment:**

n/a

- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by JoeyZwicker** [comment]
> Print or install the bash completion code. This should be placed as the file pachctl in the bash completion directory (by default this is /etc/bash_completion.d. If bash-completion was installed via homebrew, this would be $(brew --prefix)/etc/bash_completion.d.)

Looks like there are a few of typo and grammatical issues in these docs that fixing would also help clarify things much better too

**Comment by svekars** [comment]
It looks like this functionality has been modified for 1.10 along with the 
description: 

Also, we've added step-by-step instructions on how to configure pachctl completion for 1.10 which should be available by the end of February.
https://docs.pachyderm.com/master/getting_started/install-pachctl-completion/

**Comment by svekars** [comment]
Closing as this seemed to be addressed. Feel free to reopen if you have any questions.
