### ISSUE TITLE
Add support for bucket aliases to the s3 gateway

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#4587]
in concert with issue https://github.com/pachyderm/pachyderm/issues/4586, allow the s3 gateway to be initialized in "pipeline mode" with a pipeline ID. In this mode:
1. accessing logical buckets that don't correspond to any of the pipeline's input repos or output repo won't work.
2. People will use ~job IDs~ PPS Input name (or repo name, if no input name is specified) as the S3 bucket name, rather than commit IDs. Either `s3://123..f.myrepo` or `s3://master.myrepo` won't work. The s3 gateway will be configured at startup to map `s3://my-input` to `s3://<input commit ID>.<input repo>`

**Comment by jdoliner** [comment]
We should think about how this will play with https://github.com/pachyderm/rfcs/pull/7 since after that's implemented Job IDs will be the same as commit IDs.

**Comment by ysimonson** [comment]
This is a 🚲 🏠 , but with this change, should we move s3g out of `src/server/pfs`?

**Comment by jdoliner** [comment]
I suspect you'll kind of have to, to avoid circular dependencies. Although I think maybe the right approach to this is that rather than s3g actually being aware of jobs as a concept it simply allows you to expose data under paths that you can configure when you start up the s3g server, and the worker then configures it at startup to use the job id, but the s3g doesn't know anything more than that it was given a string to use as an alias for a commit.

**Comment by msteffen** [comment]
### Update 2019-2-20

Talked to Yusuf about the best next steps for this project. Two main changes:
- It's easier from an implementation perspective and seems like a better user experience if the s3 gateway constructor simply receives the commit IDs of a job's input repos at startup, and then we make sure that each job only connects to its s3 gateway (rather than trying to support job B's workers reading from its inputs via job A's sidecar s3g). This is similar to JD's suggestion above, but the goal is to remove job IDs completely if possible, and encode all relevant information in the s3 endpoint
- We're also going to require, at least initially, that if a user is reading input data from s3 gateway, then they must write their output via the s3 gateway (though mounting config files locally via non-s3g inputs is still supported). This simplifies the pipeline spec and eliminates a lot of confusing decisions related to merging: we simply won't skip any datums if an s3 gateway is present, and there will be no merge because the pipeline is writing directly to the output repo.

To summarize how this would work end-to-end:
- Pipelines are either **s3 pipelines** (if they contain *any* s3 inputs[1]) or **non-s3 pipelines**
- For s3 pipelines: when starting a job, the sidecars will initialize the S3 gateway server, passing the constructor a list of `(<commit ID>, <repo>, <name>)` tuples. Any requests to this s3 gateway for the bucket `s3://<name>` will be mapped to equivalent requests for `<commit ID>.<repo>`.
- Pass pod IP (or the dns address of a kubernetes service that we create/destroy alongside the job) to the worker. The worker can pass the IP/DNS to kubeflow as an s3 endpoint.
- The worker/kubeflow writes to `s3://<input name>` using the given s3 endpoint, and the input name is mapped to the appropriate commit as described above.
- s3g does not allow writes to `<name>` if `<commit ID>` is closed. This way input repos are read-only
- Similarly, the worker no longer creates or walk `/pfs/out`. Any output data must be written through the S3 gateway.

[1] An "s3 input" is a PFSInput with `s3: true`.

### Open Questions

1) **Kubernetes service per job** Is it worth creating a kubernetes service per job for the s3 gateway? We approximately do this for pachyderm services, so this might be fine, but we'd need to be sure to tear the s3 gateway service down at the end of a job, and consistently deleting kubernetes resources has been surprisingly difficult in the past.

1) **Concurrent Jobs**. Are workers shared across concurrent jobs? If so, then we can't initialize one set of sidecars with one set of input commits, and a second, parallel set of sidecars with different input commits. We'll either need s3 gateway to handle requests to different addresses (if we're using a kubernetes service) and map the address at which it was addressed to the right commit IDs, or change the design in some other way so that the same s3 gateway can handle requests for multiple different jobs

2) Do we have to do anything special for the case where a pipeline takes two branches in the same repo as inputs to prevent a name collision? This is something we could prevent in the CreatePipeline validator if necessary.

**Comment by ysimonson** [comment]
The takeaway I had from our conversation was that we were going to punt on s3 support for pipeline outputs from now, and require outputs be written to `/pfs/out` as per usual. If we do go down the route of s3g support for outputs, I think we'll need to add it as a config from day one, because implicit semantic changes between s3 and non-s3 pipelines is going to be confusing for end-users.

**Comment by ysimonson** [comment]
Re: concurrent jobs, the solution I have in mind is that we bake the job ID (or a part of it) into the ephemeral s3g service name. It's not ideal, because it means we'll need to pass the service name into kubeflow, but I don't see a way around that.

**Comment by msteffen** [comment]
1) Ack on leaving the `s3_out` configuration option in the pipeline spec

2) Re. concurrent jobs, just summarizing our conversation: After talking to JD, we now know that the same set of workers will be expected to run two different jobs concurrently. This means that the s3 gateway running in each worker's sidecar may have to handle requests related to different jobs concurrently; there will be no simple way to distinguish "job A" nodes from "job B" nodes at any given moment in time. However, we can force s3g requests to include information about the job that they're coming from by spawning a k8s service per job, with the job ID in the service's hostname (e.g. `http://<job id>-s3`. This at least gives us a conceptual way to disambiguate "job A" s3g reads from "job B" s3g reads.

At the same time, ideally the S3 gateway should be statically configured; we should not need to update a running s3g instance to inform it of new jobs. In principle we can do this by initializing a new s3g instance for each job (statically configured with its job's input/output commits) and route requests to `http://<job id>-s3` to the right instance.

**Plan A**: Configure the per-job k8s service to direct s3g requests to the right instance. It's an open question how to service multiple s3g instances from a single sidecar (does each instance serve on a random open port? Is it possible to configure k8s services to forward requests to different ports on different nodes?)

**Plan B**: Add a proxy layer to the sidecar. In this plan, all s3g requests will go to a single high-level handler in the sidecar container, which will virtually route requests (based on the job ID in the hostname) to the right s3g instance

**Comment by ysimonson** [comment]
This was shipped in 1.10.0.
