### ISSUE TITLE
Deployment on openshift fail because pachd tries to access port 999

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4588]
I get the error `error in Githook Server: listen tcp :999: bind: permission denied` when deploying pachd to openshift. I think you need to add an envir to tell pachd to use a non default port (1999 for instance) like you did for `PEER_PORT` for instance.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.11

**Comment by jdoliner** [comment]
I believe we have a fix for this in 1.9.12, you can pass `--require-critical-servers-only` and it won't break startup. Sorry for the inconvenience.
