### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4597]
We're currently getting an error on master in CI:

```
-> unzip /go/pkg/mod/cache/download/github.com/hashicorp/vault/@v/v1.1.3.zip: zip: not a valid zip file

build command-line-arguments: cannot load github.com/hashicorp/vault/api: unzip /go/pkg/mod/cache/download/github.com/hashicorp/vault/@v/v1.1.3.zip: zip: not a valid zip file
```

See, e.g. https://travis-ci.com/pachyderm/pachyderm/jobs/286543607

**Comment by jdoliner** [comment]
I've been seeing this a lot lately too. I thought it was maybe a network issue, rather than something bad we implemented, but I could be wrong. Did this code change recently?

**Comment by ysimonson** [comment]
I don't think it's a network issue, because I've tried tried multiple runs on on a failed job, and it reliably produces the same error. Looking at the 5 most recent PRs, 4 of them are failing with that error. 1 is not, but I think it's failing before it gets there. [It doesn't look like there were any recent updates](https://github.com/pachyderm/pachyderm/blame/0d007da25e147e67e89649af373f68a7f27ab492/go.mod#L66), so I suspect it's an issue on vault's side.

**Comment by ysimonson** [comment]
I'm not sure if it's a vault-side issue, now. We're using a go proxy, which allegedly should make package versions immutable. And I didn't see anything about the error in vault's issues.
