### ISSUE TITLE
Search broken on 404 page

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#4599]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/en/latest/fundamentals/creating_services.html

**Describe what is wrong:**
1. Go to a page that doesn't exist and get the 404 page
2. Try entering a search term into the search box,
3. Wait for results, only "Type to start searching" is displayed

![image](https://user-images.githubusercontent.com/1187682/74476268-03cc0b00-4e77-11ea-90d1-da1168eaa89e.png)

**Comment by svekars** [comment]
While it is annoying and must be fixed, I'm setting the priority of this issue to low.

**Comment by mindthevirt** [comment]
This can no longer be reproduced. 
![image](https://user-images.githubusercontent.com/23178090/105726009-9b473400-5ef7-11eb-80c9-b0b506684251.png)
