### ISSUE TITLE
make launch-kube halts, hangs

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#460]
Following the steps mentioned in - https://github.com/pachyderm/pachyderm/blob/master/SETUP.md
After cloning the pachyderm repo from git,
the command - make launch-kube gets stuck; 
On first run, it couldn't find image locally hence pulled it;
Status showed download complete
However it hangs there/snaps. No response henceforth
Waited for 40 minutes

![make launch-kubehang](https://cloud.githubusercontent.com/assets/10992635/15798744/30082a84-2a61-11e6-863a-9aaf238b67a0.png)

[root@localhost pachyderm]# make launch-kube
etc/kube/start-kube-docker.sh
Unable to find image 'gcr.io/google_containers/hyperkube:v1.2.2' locally
v1.2.2: Pulling from google_containers/hyperkube
81cc5f26a6a0: Pull complete 
a3ed95caeb02: Pull complete 
063437597255: Pull complete 
b4020ee389e8: Pull complete 
89b2db79f15b: Pull complete 
df40237c8d23: Pull complete 
d475cf290f14: Pull complete 
9fb4d210982d: Pull complete 
f23e487dc7e4: Pull complete 
c110bb056d31: Pull complete 
7f996656b2e2: Pull complete 
8ea8f63d36ec: Pull complete 
c6a923a7896b: Pull complete 
9fcfc590bc83: Pull complete 
da14f8f2d525: Pull complete 
Digest: sha256:c2de5dbedfd1864048fa399185b56a302fd07f886ce94e08220b89802196c787
Status: Downloaded newer image for gcr.io/google_containers/hyperkube:v1.2.2
efb9798117aea548560ef34d5e10d23407a17aa298c61926b89460b7674b3841

**Comment by jdoliner** [comment]
`make launch-kube` has a loop at the end which waits for kubernetes to come up. However if it can't get in contact it'll just sleep forever. If you kill the sleep and then do `kubectl get all` what does it get you?

**Comment by ChaiBapchya** [comment]
kubectl get all
bash: kubectl: command not found...
Install package 'kubernetes-client' to provide command 'kubectl'? [N/y] y


 * Waiting in queue... 
 * Loading list of packages.... 
 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kubernetes             10.0.0.1     <none>        443/TCP    1h
NAME                   READY        STATUS        RESTARTS   AGE
k8s-etcd-127.0.0.1     1/1          Running       0          1h
k8s-master-127.0.0.1   4/4          Running       4          1h
k8s-proxy-127.0.0.1    1/1          Running       0          1h

[root@localhost pachyderm]# make launch-kube
etc/kube/start-kube-docker.sh
b7d67b55995f195f51761e8df6d1c42a605f9e1a3275f21507622343aa1ad516
[root@localhost pachyderm]# make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
src/server/cmd/pachctl/main.go:5:2: cannot find package "go.pedge.io/env" in any of:
	/usr/local/go/src/go.pedge.io/env (from $GOROOT)
	/work/src/go.pedge.io/env (from $GOPATH)
Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1

echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/go/bin
![kubectl](https://cloud.githubusercontent.com/assets/10992635/15798828/a5d3038a-2a64-11e6-934f-c9a155bd8e20.png)

**Comment by ChaiBapchya** [comment]
I downloaded go.pedge.io/env  in /usr/local/go/src/ 
go get go.pedge.io/env

Then when I try "make launch" in /pachyderm
Still the error exists

# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
go install: no install location for directory /pachyderm/src/server/cmd/pachctl outside GOPATH
	For more details see: go help gopath
go install: no install location for directory /pachyderm/src/server/cmd/pach-deploy outside GOPATH
	For more details see: go help gopath
Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by ChaiBapchya** [comment]
echo $GOPATH
/work

Work structure is
/work/src/github.com/pachyderm/pachyderm

Thus according to
https://github.com/pachyderm/pachyderm/issues/422

Our repo expects to be located at **$GOPATH/src/github.com/pachyderm.** 

Still the error persists

**Comment by jdoliner** [comment]
Hmm, so that error suggests that the repo is located outside of the `$GOPATH` but based on what you told me that doesn't seem to be the case. Would you mind trying this:

```
rm -rf /work/src
go get github.com/pachyderm/pachyderm
```

Then try the commands again, that should download the repo in the right spot and also download all of the dependencies.

**Comment by ChaiBapchya** [comment]
GOPATH, GOROOT - environment variables seem to be set to null once I do go get github.com
Hence it gives me error that when I make install (it cant find it in the 

[chai@localhost /]$ export GOROOT=$HOME/go
[chai@localhost /]$ export GOROOT=/usr/bin/go
[chai@localhost /]$ export PATH=$PATH:$GOROOT/bin
[chai@localhost /]$ export GOPATH=/work
[chai@localhost /]$ cd work/

[chai@localhost work]$ export GOROOT=/usr/local/go

[chai@localhost work]$ go get github.com/pachyderm/pachyderm
# github.com/pachyderm/pachyderm
ar: `u' modifier ignored since `D' is the default (see `U')

[chai@localhost work]$ sudo systemctl start docker
[sudo] password for chai: 
[chai@localhost work]$ sudo su
[root@localhost work]# ls
pkg  src

[root@localhost work]# cd src/github.com/pachyderm/pachyderm/

[root@localhost pachyderm]# make launch-kube
etc/kube/start-kube-docker.sh
6b2bcc4644e9a004b6a27b915fc6cb67de7a00f4a8e1f5116a6d1aad66cc056f


[root@localhost pachyderm]# make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
src/server/cmd/pachctl/main.go:4:2: cannot find package "github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd" in any of:
	/usr/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd (from $GOROOT)
	($GOPATH not set)
src/server/cmd/pachctl/main.go:5:2: cannot find package "go.pedge.io/env" in any of:
	/usr/src/go.pedge.io/env (from $GOROOT)
	($GOPATH not set)
src/server/cmd/pach-deploy/main.go:6:2: cannot find package "github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds" in any of:
	/usr/src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/cmds (from $GOROOT)
	($GOPATH not set)
Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1

[root@localhost pachyderm]# echo $GOPATH

[root@localhost pachyderm]# echo $GOROOT

[root@localhost pachyderm]# 

When I set GOROOT to point to location where it is installed
[root@localhost pachyderm]# export GOROOT=/usr/local/go

GOPATH to /work (where I did go get pachyderm)

and try doing 
make launch it says

[root@localhost pachyderm]# make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
src/server/pfs/fuse/filesystem.go:15:2: cannot find package "bazil.org/fuse" in any of:
	/usr/local/go/src/bazil.org/fuse (from $GOROOT)
	/work/src/bazil.org/fuse (from $GOPATH)
src/server/pfs/fuse/filesystem.go:16:2: cannot find package "bazil.org/fuse/fs" in any of:
	/usr/local/go/src/bazil.org/fuse/fs (from $GOROOT)
	/work/src/bazil.org/fuse/fs (from $GOPATH)
src/server/pps/cmds/cmds.go:15:2: cannot find package "github.com/Jeffail/gabs" in any of:
	/usr/local/go/src/github.com/Jeffail/gabs (from $GOROOT)
	/work/src/github.com/Jeffail/gabs (from $GOPATH)
src/client/pkg/discovery/etcd_client.go:6:2: cannot find package "github.com/coreos/go-etcd/etcd" in any of:
	/usr/local/go/src/github.com/coreos/go-etcd/etcd (from $GOROOT)
	/work/src/github.com/coreos/go-etcd/etcd (from $GOPATH)
src/server/pfs/pretty/pretty.go:10:2: cannot find package "github.com/docker/go-units" in any of:
	/usr/local/go/src/github.com/docker/go-units (from $GOROOT)
	/work/src/github.com/docker/go-units (from $GOPATH)
src/server/pps/pretty/pretty.go:9:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/work/src/github.com/fatih/color (from $GOPATH)
src/client/pfs/pfs.pb.go:60:8: cannot find package "github.com/gengo/grpc-gateway/third_party/googleapis/google/api" in any of:
	/usr/local/go/src/github.com/gengo/grpc-gateway/third_party/googleapis/google/api (from $GOROOT)
	/work/src/github.com/gengo/grpc-gateway/third_party/googleapis/google/api (from $GOPATH)
src/client/pkg/shard/sharder.go:12:2: cannot find package "github.com/golang/protobuf/jsonpb" in any of:
	/usr/local/go/src/github.com/golang/protobuf/jsonpb (from $GOROOT)
	/work/src/github.com/golang/protobuf/jsonpb (from $GOPATH)
src/client/pfs/pfs.pb.go:57:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/work/src/github.com/golang/protobuf/proto (from $GOPATH)
src/client/pkg/uuid/uuid.go:6:2: cannot find package "github.com/satori/go.uuid" in any of:
	/usr/local/go/src/github.com/satori/go.uuid (from $GOROOT)
	/work/src/github.com/satori/go.uuid (from $GOPATH)
src/server/pkg/cmd/cmd.go:9:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
	/work/src/github.com/spf13/cobra (from $GOPATH)
src/server/cmd/pachctl/main.go:5:2: cannot find package "go.pedge.io/env" in any of:
	/usr/local/go/src/go.pedge.io/env (from $GOROOT)
	/work/src/go.pedge.io/env (from $GOPATH)
src/server/pfs/fuse/mounter.go:11:2: cannot find package "go.pedge.io/lion" in any of:
	/usr/local/go/src/go.pedge.io/lion (from $GOROOT)
	/work/src/go.pedge.io/lion (from $GOPATH)
src/client/pkg/shard/sharder.go:14:2: cannot find package "go.pedge.io/lion/proto" in any of:
	/usr/local/go/src/go.pedge.io/lion/proto (from $GOROOT)
	/work/src/go.pedge.io/lion/proto (from $GOPATH)
src/client/pfs/pfs.pb.go:61:8: cannot find package "go.pedge.io/pb/go/google/protobuf" in any of:
	/usr/local/go/src/go.pedge.io/pb/go/google/protobuf (from $GOROOT)
	/work/src/go.pedge.io/pb/go/google/protobuf (from $GOPATH)
src/server/pfs/cmds/cmds.go:17:2: cannot find package "go.pedge.io/pkg/cobra" in any of:
	/usr/local/go/src/go.pedge.io/pkg/cobra (from $GOROOT)
	/work/src/go.pedge.io/pkg/cobra (from $GOPATH)
src/client/pfs.go:8:2: cannot find package "go.pedge.io/proto/stream" in any of:
	/usr/local/go/src/go.pedge.io/proto/stream (from $GOROOT)
	/work/src/go.pedge.io/proto/stream (from $GOPATH)
src/server/pfs/fuse/filesystem.go:21:2: cannot find package "go.pedge.io/proto/time" in any of:
	/usr/local/go/src/go.pedge.io/proto/time (from $GOROOT)
	/work/src/go.pedge.io/proto/time (from $GOPATH)
src/client/version/version.go:7:2: cannot find package "go.pedge.io/proto/version" in any of:
	/usr/local/go/src/go.pedge.io/proto/version (from $GOROOT)
	/work/src/go.pedge.io/proto/version (from $GOPATH)
src/client/pfs/pfs.pb.go:67:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/work/src/golang.org/x/net/context (from $GOPATH)
src/client/pkg/grpcutil/dialer.go:4:2: cannot find package "google.golang.org/grpc" in any of:
	/usr/local/go/src/google.golang.org/grpc (from $GOROOT)
	/work/src/google.golang.org/grpc (from $GOPATH)
src/server/pfs/fuse/filesystem.go:24:2: cannot find package "google.golang.org/grpc/codes" in any of:
	/usr/local/go/src/google.golang.org/grpc/codes (from $GOROOT)
	/work/src/google.golang.org/grpc/codes (from $GOPATH)
src/server/pkg/obj/amazon_client.go:7:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
	/work/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
src/server/pkg/obj/amazon_client.go:8:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOROOT)
	/work/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOPATH)
src/server/pkg/obj/amazon_client.go:9:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/aws/session (from $GOROOT)
	/work/src/github.com/aws/aws-sdk-go/aws/session (from $GOPATH)
src/server/pkg/obj/amazon_client.go:10:2: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/service/s3 (from $GOROOT)
	/work/src/github.com/aws/aws-sdk-go/service/s3 (from $GOPATH)
src/server/pkg/obj/amazon_client.go:11:2: cannot find package "github.com/aws/aws-sdk-go/service/s3/s3Manager" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/service/s3/s3Manager (from $GOROOT)
	/work/src/github.com/aws/aws-sdk-go/service/s3/s3Manager (from $GOPATH)
src/server/pkg/obj/obj.go:7:2: cannot find package "github.com/cenkalti/backoff" in any of:
	/usr/local/go/src/github.com/cenkalti/backoff (from $GOROOT)
	/work/src/github.com/cenkalti/backoff (from $GOPATH)
src/server/pfs/server/obj_block_api_server.go:15:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/local/go/src/github.com/gogo/protobuf/proto (from $GOROOT)
	/work/src/github.com/gogo/protobuf/proto (from $GOPATH)
src/server/pkg/metrics/segment.go:4:2: cannot find package "github.com/segmentio/analytics-go" in any of:
	/usr/local/go/src/github.com/segmentio/analytics-go (from $GOROOT)
	/work/src/github.com/segmentio/analytics-go (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:9:2: cannot find package "github.com/ugorji/go/codec" in any of:
	/usr/local/go/src/github.com/ugorji/go/codec (from $GOROOT)
	/work/src/github.com/ugorji/go/codec (from $GOPATH)
src/server/pfs/server/api_server.go:19:2: cannot find package "go.pedge.io/proto/rpclog" in any of:
	/usr/local/go/src/go.pedge.io/proto/rpclog (from $GOROOT)
	/work/src/go.pedge.io/proto/rpclog (from $GOPATH)
src/server/pkg/obj/google_client.go:7:2: cannot find package "golang.org/x/oauth2/google" in any of:
	/usr/local/go/src/golang.org/x/oauth2/google (from $GOROOT)
	/work/src/golang.org/x/oauth2/google (from $GOPATH)
src/server/pkg/obj/google_client.go:8:2: cannot find package "google.golang.org/cloud" in any of:
	/usr/local/go/src/google.golang.org/cloud (from $GOROOT)
	/work/src/google.golang.org/cloud (from $GOPATH)
src/server/pkg/obj/google_client.go:9:2: cannot find package "google.golang.org/cloud/storage" in any of:
	/usr/local/go/src/google.golang.org/cloud/storage (from $GOROOT)
	/work/src/google.golang.org/cloud/storage (from $GOPATH)
src/server/pfs/server/api_server.go:24:2: cannot find package "google.golang.org/grpc/metadata" in any of:
	/usr/local/go/src/google.golang.org/grpc/metadata (from $GOROOT)
	/work/src/google.golang.org/grpc/metadata (from $GOPATH)
src/server/pkg/metrics/external.go:6:2: cannot find package "k8s.io/kubernetes/pkg/api" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/api (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/api (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:11:2: cannot find package "k8s.io/kubernetes/pkg/api/resource" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/api/resource (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/api/resource (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:12:2: cannot find package "k8s.io/kubernetes/pkg/api/unversioned" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:13:2: cannot find package "k8s.io/kubernetes/pkg/apis/extensions" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/apis/extensions (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/apis/extensions (from $GOPATH)
src/server/pkg/metrics/external.go:7:2: cannot find package "k8s.io/kubernetes/pkg/client/unversioned" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/client/unversioned (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/client/unversioned (from $GOPATH)
Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1
[root@localhost pachyderm]#

**Comment by ChaiBapchya** [comment]
After go get of all the dependencies I got error in 4 dependencies related to k8s.io

make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
src/server/pkg/metrics/external.go:6:2: no buildable Go source files in /usr/local/go/src/k8s.io/kubernetes/pkg/api
src/server/pkg/deploy/assets/assets.go:11:2: cannot find package "k8s.io/kubernetes/pkg/api/resource" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/api/resource (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/api/resource (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:12:2: cannot find package "k8s.io/kubernetes/pkg/api/unversioned" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/api/unversioned (from $GOPATH)
src/server/pkg/deploy/assets/assets.go:13:2: no buildable Go source files in /usr/local/go/src/k8s.io/kubernetes/pkg/apis/extensions
src/server/pkg/metrics/external.go:7:2: cannot find package "k8s.io/kubernetes/pkg/client/unversioned" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/client/unversioned (from $GOROOT)
	/work/src/k8s.io/kubernetes/pkg/client/unversioned (from $GOPATH)
Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by sjezewski** [comment]
Hi there, sorry you're running into all these snags, but thanks for all the debugging diligence you're doing.

There seem to be two issues here:

1) Your go environment variables aren't set

Not sure why these are missing. It's standard practice to set these in your shell init script (e.g. `~/bash_profile`). Are you setting them there?

You'll definitely need these set. You've identified that they're missing, which is great, but I want to make sure that these are always present, or you'll run into a lot of issues along the way. 

2) You're missing all the dependencies for compiling the pachyderm source

What version of go are you using? (Please run `go version` and let us know what it reports). You should be using go 1.6

You errors around building suggest that the compiler isn't using the vendored copies of those dependencies from within our repo. You shouldn't have to manually grab each of them. The reason we vendor our dependencies is to lock them to specific versions that we know the pachyderm code is compatible with.

**Comment by ChaiBapchya** [comment]
1.I used to export $PATH, $GOPATH, $GOROOT and set the environment variables. However now I have set them in shell init script as told (although in few internet articles export also seemed to work, maybe temporarily)

2.I have downloaded the tar file from https://golang.org/doc/install of latest version 1.6+
in usr/local I have the extracted tar
But
[root@localhost /]# go version
go version go1.4.2 gccgo (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6) linux/amd64

I again tried with
[root@localhost /]# export PATH=$PATH:/usr/local/go/bin
[root@localhost /]# go version
go version go1.4.2 gccgo (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6) linux/amd64

**Comment by ChaiBapchya** [comment]
Issue was resolved 
Problem
2 versions of go installed

1st GCC GO version 1.4 - already installed on my Fedora as a dev tool
2nd Go version 1.6

According to doc, 1.4 which was my default wasnt compatible with pachyderm and hence had to be removed, path changed and removed from Hash of the shell

Finally right go version and path
[root@localhost /]# go version
go version go1.6.2 linux/amd64
[root@localhost /]# which go
/usr/local/go/bin/go

Following steps followed
1. Get the git along with dependencies
[root@localhost work]# go get github.com/pachyderm/pachyderm

2.Starting docker
[root@localhost work]# sudo systemctl start docker

3.
[root@localhost work]# cd ../workspace/
[root@localhost workspace]# ls
pkg  src
[root@localhost workspace]# cd src/github.com/pachyderm/pachyderm/

[root@localhost pachyderm]# make launch-kube
etc/kube/start-kube-docker.sh
62a213fadcd1cb4cc065414a020359259b7e0f617661c95460ddb3c53e663a37

Kubernete launched

4. Pachyderm deployed on kubernete
[root@localhost pachyderm]# make launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
kubectl  create -f etc/kube/pachyderm.json
serviceaccount "pachyderm" created
replicationcontroller "etcd" created
service "etcd" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:32080,tcp:32081,tcp:32082) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "rethink" created
replicationcontroller "rethink" created
job "pachd-init" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30650) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "pachd" created
replicationcontroller "pachd" created
# wait for the pachyderm to come up
until timeout 1s ./etc/kube/check_pachd_ready.sh; do sleep 1; done

Issue is - nothing is happening after this

**Comment by jdoliner** [comment]
Closing this as there isn't anything actionable left to be done.
One concrete change that came out of this is that we now check that kubectl is installed before we enter the wait loop. That should prevent the initial issue here.
