### ISSUE TITLE
Validate kubectl installed for any make tasks that use it

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#462]
In #460 a user tried to make launch, which waits on calling kubectl, and if its not installed it will never exit 0.

Let's add a dependency check task to the make file and include it as a prereq for any tasks that use kubectl. Easy to do, and helps make sure users succeed at launching.

**Comment by sjezewski** [comment]
@jdoliner - I think you mentioned you have a fix for this somewhere? If you're working on it, you should assign this to yourself

**Comment by jdoliner** [comment]
@sjezewski nice catch! Fixed by #478.
