### ISSUE TITLE
[WIP] Move to containerized CI - Pull out build process

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#4629]
Current process:
Pachyderm is currently built by first building a 'compile' docker image, then mounting the code and cached deps into that to do the build. See `make docker-build-compile`, `make docker-build-worker` and `make docker docker-build-pachd`

Would like to move to the more standardized docker multi-step build process

Challenges
- The current approach is difficult to replicate in a containerized CI system like cloudbuild
- The go _build_ cache (not to be confused with the deps cache) doesn't work with current docker layer caching, you can see this mounted into our current build process `-v $$HOME/.cache/go-build:/root/.cache/go-build` This significantly speeds up the build process (cold go build is several minutes, warm go build is seconds)

Options tried:
- Using docker buildkit, we've successfully been able to cache the go build cache (Allows for mounting in cache to build steps

Where to find things
- https://github.com/pachyderm/pachyderm/blob/master/etc/testing/travis.sh
- https://github.com/pachyderm/pachyderm/blob/master/Makefile

**Comment by RaananHadar** [comment]
take a look at [this](https://docs.docker.com/develop/develop-images/multistage-build/), i think it looks like an elegant way to achieve what you are looking for.

**Comment by chainlink** [comment]
Thanks @RaananHadar Multi-stage builds are definitely a part of it! The issue lies with go's build cache and how docker caches layers (the two are incompatible) Docker build kit fixes this by allowing you to mount in directories to build steps
