### ISSUE TITLE
Create create and delete pipeline sections

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4632]
Related to https://github.com/pachyderm/pachyderm/pull/4626.

Create the **Delete a pipeline** section that describes the use of all the flags including the --keep-repo. Explain that provenance is preserved when you keep the repo except for the branch provenance itself so no `__spec...`. If the pipeline is recreated the provenance is restored but the branch provenance is reset. 

Create the **Create a pipeline** section that describes how to create a pipeline with all flags.

**Comment by jdoliner** [comment]
To clarify here, not sure if this was what you meant by no `__spec...` only the branch provenance gets removed. So your output repo will still have a `master` branch (or whatever you called it) and a `stats` branch. And the commits on those branches will still have `__spec__` commits in their provenance. However, you won't have any branches in the branch provenance of the `master` branch.
