### ISSUE TITLE
Purge file upon deletion

### ISSUE THREAD

**Issue by rphamle** [pachyderm/pachyderm#4640]
**What is the goal / desired outcome?**
Currently, the only way to physically delete a file is to delete all commits that the file exists in, followed by `pachctl garbage-collect`. This can end up inadvertently removing other files, as well as be a very time intensive process. I want to be able to physically delete/purge a single file without having to delete commits.

**What is your proposal for a feature to solve this?**
Add a parameter to `pachctl delete` in order to delete+garbage collect a single file.
Eg. `pachctl delete file --purge <repo>@<branch>:/<path-to-file>`.

**Comment by jdoliner** [comment]
Closing this in favor of: https://github.com/pachyderm/pachyderm/issues/3123

That issue has more details, take a look at that @rphamle and see if it would meet your needs, and feel free to chime in if you don't think it would.
