### ISSUE TITLE
Pachd auto discovering does not seem to work

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4648]
**What happened?**:

I deployed pachyderm in a namespace. I created a pod containing `pachctl` and ran `pachctl version` which returned:
```
COMPONENT           VERSION             
pachctl             1.9.12              
no pods found for app pachd
```

But the pod pachd exists and has labels `app=pachd`!

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    iam.amazonaws.com/role: ""
  labels:
    app: pachd
    app.kubernetes.io/component: pachyderm
    app.kubernetes.io/instance: metakube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pachyderm
    app.kubernetes.io/part-of: metakube-pachyderm
    app.kubernetes.io/version: 0.2.0-SNAPSHOT
    helm.sh/chart: pachyderm-0.2.0-SNAPSHOT
    pod-template-hash: 5c44695b44
    suite: pachyderm
  name: pachd-5c44695b44-4r6bv
  namespace: metakube
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pachd-5c44695b44
    uid: 5ca8b13e-aa98-498d-8bed-0d15190bfc1d
  resourceVersion: "63651"
  selfLink: /api/v1/namespaces/metakube/pods/pachd-5c44695b44-4r6bv
  uid: d5fa6510-6cf3-475a-865c-402d21641f76
spec:
  ...
```

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.12
- minikube: 1.5.2
- k8s: 1.16.2

**Comment by jdoliner** [comment]
Pachctl's auto discovery is geared toward people connecting to Pachd from outside of their kubernetes cluster. So it checks for things listening on the right port on localhost, and failing that attempts to portforward through kubectl. It doesn't look for service env-vars which is what it would have to do to facilitate connecting from within the cluster. Our go api has a method `NewInCluster` which does this. We can look at integrating this into the list of places pachctl checks to auto discover.

You can get this behavior now by using the value of the env var `PACHD_SERVICE_HOST` as the `PACHD_ADDRESS` env var.
