### ISSUE TITLE
Clarify the <none> branch in the docs

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4649]
Branches with `<none>`
 as their head (also called headless branches). Basically act as placeholders before there's actually a commit to point to. These happen if you call CreateBranch and don't pass it a head, or if you create a pipeline that takes a branch as input that doesn't exist yet.

**Comment by jdoliner** [comment]
Just realized that this can also technically happen if you repeatedly do `delete commit repo@master` until there are no commits left on master. Probably a pretty rare way to get headless branches.
