### ISSUE TITLE
pachctl 1.10.0-rc1 reports version as 1.10.0

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4669]
**What happened?**:

After deploying pachctl 1.10.0-rc1, via

```
brew install pachctl@1.10
```

I issued the command and got back this version:

```
$ pachctl version --client-only
1.10.0
```

**What you expected to happen?**:

I expected the version to be 1.10.0-rc1.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Deploy pachyderm 1.10.0-rc1
2. run `pachctl version --client-only`

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):  N/A
- Pachyderm CLI and pachd server version (use `pachctl version`):  see above :-)
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):   macOS Catalina 10.15.3 (19D76)
- Others:

**Comment by nitinjainsj** [comment]
Fixed in rc3.
