### ISSUE TITLE
`make proto` broken on master

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4697]
**What happened?**: Due to a change in upstream dependencies, it looks like `make proto` is currently broken on master.

**How to reproduce it (as minimally and precisely as possible)?**: Run `make proto`, which will have this output at the end:

```
src/github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/main.go:20:2: use of internal package github.com/grpc-ecosystem/grpc-gateway/internal/codegenerator not allowed
src/github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/main.go:22:2: use of internal package github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/internal/gengateway not allowed
The command '/bin/sh -c go get -u github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway' returned a non-zero code: 1
make: *** [docker-build-proto] Error 1
```

**Anything else we need to know?**: Observed on both mac/docker for mac and ubuntu/minikube.

**Comment by chainlink** [comment]
I'm pretty sure we can nuke the grpc-gateway stuff. I think it was explored at some point for old dash, but I'm (almost) sure it doesn't use it.

**Comment by jdoliner** [comment]
Yeah this should be fine to nuke. Our proto files don't even have the relevant annotations for this. Much less dash using it.
