### ISSUE TITLE
Crash loop

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#472]
This from out in the wild:

[out.txt](https://github.com/pachyderm/pachyderm/files/304112/out.txt)

**Comment by jdoliner** [comment]
Alright I have a PR in for part of this issue. #476. It should fix the panic. Unfortunately I couldn't find a way to reproduce the issue, since it required some sort of corruption of the diffs that would cause `ListRepo` to error.

I'm going to leave this open but we should merge the PR since it'll let us get an error the next time this happens and learn more about the corruption.

We should also try adding some corruption tests to see if we can repro it.

**Comment by derekchiang** [comment]
The PR was merged.  Also, it wasn't about corrupted diffs.  It was about nodes using the local object store got reassigned shards, but couldn't actually find the shards written by other nodes since the local object store is not shared among nodes.
