### ISSUE TITLE
Use Cases, Pachyderm Design Goals - 404 Page Not Found

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#473]
https://github.com/pachyderm/pachyderm/tree/master/doc

Use Cases - redirects to
https://github.com/pachyderm/pachyderm/blob/master/doc/pachyderm.io/use_cases.html

Pachyderm Design Goals - redirects to
https://github.com/pachyderm/pachyderm/blob/master/doc/pachyderm.io/dsbor.html

In both the cases - 404 Page Not Found

- [ ] Edit the URL for both the pages in Pachyderm GitHub repo

**Comment by jdoliner** [comment]
@JoeyZwicker this one is actually in your wheel house.

**Comment by JoeyZwicker** [comment]
Yup i'm on this. We have a few other links broken too.
