### ISSUE TITLE
add "pachctl mount" as one of the ways to export data from Pachyderm

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4731]
**Provide a link to the page with an issue:**

https://docs.pachyderm.com/latest/how-tos/export-data-out-pachyderm/

**Describe what is wrong:**

It doesn't mention pachctl mount as an option

**Describe the suggested changes:**

1. Create a documentation page on pachclt mount and link to it from here.

**Anything else we need to know?**

We should give practical advices on the drivers needed to be installed for various environments.

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by ysimonson** [comment]
If we do this, we should slightly discourage it's use. `pachctl mount` uses fuse, which is full of sharp edges.

**Comment by pappasilenus** [comment]
Absolutely, but it is an option...

**Comment by svekars** [comment]
Depends on https://github.com/pachyderm/pachyderm/issues/4558
