### ISSUE TITLE
Document Native JupyterHub deployments

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4735]
Based on #4732

**Comment by ysimonson** [comment]
One good thing to add would be documentation on how to patch an existing JupyterHub instance that wasn't deployed via `pachctl`. I haven't tried it, but I think this should suffice:

```
helm upgrade "<release name>"  --reuse-values --set-string singleuser.image.name=pachyderm/jupyterhub-pachyderm-user,singleuser.image.tag=1.0.0
```

**Comment by svekars** [comment]
@ysimonson with all the changes to Pachyderm IDE do you think is this still a relevant doc task?

**Comment by ysimonson** [comment]
Yes. It's just that, instead of being called "jupyterhub-pachyderm", it's called "pachyderm IDE".

**Comment by mindthevirt** [comment]
This has been addressed: https://docs.pachyderm.com/latest/deploy-manage/deploy/deploy-pachyderm-ide/
