### ISSUE TITLE
Failure to evict cached hashtrees

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4763]
**What happened?**: A customer is observing a failure to evict cached hashtrees, causing an explosion in the count and aggregate size of files in their `pach-disk` volume.

**What you expected to happen?**: We are supposed to set hard bounds on the number of hashtrees being cached.

**Comment by ysimonson** [comment]
Fixed in #4420, which went into 1.9.10, by @Tryneus

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/31'>Zendesk ticket #31</a>:<br><br>Upgrade this morning to 1.10.4 should solve this issue, since it includes a fix for issue 4763.
