### ISSUE TITLE
No error reported when attempting to delete a non-existing pipeline

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4771]
**What happened?**:
I tried to delete a pipeline with a non existing name. The command completed successfully without any output.
**What you expected to happen?**:
An error would be displayed specifying that I tried to delete a non-existing pipeline
**How to reproduce it (as minimally and precisely as possible)?**:
pachctl delete pipeline 'non-existing-pipe-name' 
**Anything else we need to know?**:
This is mostly an issue when attempting to delete a pipeline and having a typo. The user would think the pipeline was deleted. In reality its still there and jobs would continue to run.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.10

**Comment by adelelopez** [comment]
This is intentional on our end so that you don't have to handle errors when writing cleanup scripts.

**Comment by RaananHadar** [comment]
I see.
