### ISSUE TITLE
pachctl does not respect OSX dns over vpn

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#4807]
**What happened?**:
Because pachctl is not linked against CGO (CGO_ENABLED=0) on osx, it does not honor the DNS resolver setting son OSX when using a vpn.

**What you expected to happen?**:
DNS resolution should work with pachctl commands.

**How to reproduce it (as minimally and precisely as possible)?**:
Easiest way to test:
Edit your /etc/resolv.conf on osx and set the nameserver to something nonsensical like 127.0.0.1.
Observe that your osx applications, and ping on the command line, all still have dns resolution.
Observe that pachctl does not. 

**Anything else we need to know?**:
Similar kubectl issue:
https://github.com/kubernetes/release/issues/469

**Environment?**:
Any osx client using pachctl of any version.

I could have sworn I opened this issue before but I couldn't find it on the issue tracker, so here it is again.<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/42'>Zendesk ticket #42</a>)<br>gz#42</i><br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/44'>Zendesk ticket #44</a>)<br>gz#44</i>

**Comment by brokenjacobs** [comment]
Another link in the kubectl source:
https://github.com/kubernetes/kubernetes/pull/35200

**Comment by brokenjacobs** [comment]
Tracking this down is a pain. But it appears what they did is hand the problem off to the homebrew folks because of cross-compilation concerns:
https://github.com/kubernetes/kubernetes/pull/64219

**Comment by brokenjacobs** [comment]
Looks like this may be possible to do from linux with:
https://github.com/tpoechtrager/osxcross
Looking here:
https://stackoverflow.com/questions/34084597/cross-compilation-of-cgo-for-darwin-fails

**Comment by msteffen** [comment]
Hi Steve, thanks for making so much progress on this issue! I'm marking this as a bug and assigning it to Nitin (our VP of eng.) to prioritize

**Comment by brokenjacobs** [comment]
Hooray!

**Comment by nitinjainsj** [comment]
> Hooray!

@brokenjacobs Let us know if this fixes your issue.

**Comment by ysimonson** [comment]
For posterity, note that we don't build `pachctl` on macOS with CGO disabled. You can verify this with `otool -L $(which pachctl)`. That makes this (resolved) bug all the more surprising...
