### ISSUE TITLE
Broken links in the Kubeflow / Pachy example

### ISSUE THREAD

**Issue by the-laughing-monkey** [pachyderm/pachyderm#4818]
Several links in this example are broken:

https://github.com/pachyderm/pachyderm/tree/master/examples/kubeflow/tfjob

1) The following link give us 404's:

https://github.com/kubeflow/tf-operator/tree/master/examples/v1beta2/mnist_with_summaries

https://docs.pachyderm.com/latest/enterprise/s3gateway/

2) This script throws errors trying to grab the MNIST Jpegs:

for file in $(seq 0 9)
do pachctl put file inputrepo@master:/data/img_${file}.jpg  \
     -f https://raw.githubusercontent.com/pachyderm/pachyderm/tree/master/examples/kubeflow/tfjob/mnist/img_${file}.jpg 
done

error retrieving content from "https://raw.githubusercontent.com/pachyderm/pachyderm/tree/master/examples/kubeflow/tfjob/mnist/img_0.jpg": 404 Not Found
error retrieving content from "https://raw.githubusercontent.com/pachyderm/pachyderm/tree/master/examples/kubeflow/tfjob/mnist/img_1.jpg": 404 Not Found
error retrieving content from "https://raw.githubusercontent.com/pachyderm/pachyderm/tree/master/examples/kubeflow/tfjob/mnist/img_2.jpg": 404 Not Found

**Comment by msteffen** [comment]
This issue has been obsoleted by https://github.com/pachyderm/pachyderm/pull/4850. We'll re-open it if we decide to revive that demo
