### ISSUE TITLE
windows build of pachctl

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4821]
**What is the goal / desired outcome?**
Being able to use pachctl from windows - mainly for uploading data into pachyderm and be able to run the python client from windows.
**If there is a way to accomplish this today via workaround, what does that require?**
The easiest way to upload data from windows is using the s3 gateway. However it does not allow for using transactions, which ultimately can affect how pipelines are designed. One can use a linux VM or WSL2 in the future with pachctl however it is permissive to assume that this will be the general case for windows machines without administrative privileges.
**(Optional) What is your proposal for a feature to solve this?**
Support a build of pachctl for windows. Go is suitable for that. Kubectl is also available for windows so I don't see a technical reason why this shouldn't be possible.

**Comment by ysimonson** [comment]
I think we already support WSL, @Tryneus did some work on it

**Comment by RaananHadar** [comment]
I'm suggesting a native build on windows and not something based on WSL.

**Comment by Tryneus** [comment]
@RaananHadar - It is possible to build `pachctl` for windows, but it is not part of our release process and we don't provide official binaries for it at the moment.  You can build it in VSCode using the `install` task (ctrl-p then `task install`), which should put it in your Go binary path.

**Comment by RaananHadar** [comment]
Will do, thanks @Tryneus .
