### ISSUE TITLE
Sporadic metrics bug

### ISSUE THREAD

**Issue by adelelopez** [pachyderm/pachyderm#4868]
While running some `pachyderm_test.go` tests locally, I got the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x221b672]

goroutine 15 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/metrics.(*router).reportClusterMetricsToSegment(0x0, 0xc000443f20)
        /app/src/server/pkg/metrics/router.go:23 +0x22
github.com/pachyderm/pachyderm/src/server/pkg/metrics.(*Reporter).reportClusterMetrics(0xc0002616a0)
        /app/src/server/pkg/metrics/metrics.go:150 +0x175
created by github.com/pachyderm/pachyderm/src/server/pkg/metrics.NewReporter
        /app/src/server/pkg/metrics/metrics.go:42 +0xdf
```

**Comment by jdoliner** [comment]
@actgardner this came up when @adelelopez and I were debugging some spout issues and it looks like it might be related to the changes you made to the metric reporting. It seems like somehow `reportClusterMetricsToSegment` is getting called with a `nil` router which is causing it to segfault. Not quite sure how we're winding up calling that on a nil router.

**Comment by ysimonson** [comment]
@Tryneus fixed this earlier: https://github.com/pachyderm/pachyderm/pull/4844

**Comment by actgardner** [comment]
Yusuf is right, if you rebase on master this should be resolved. Sorry about that!
