### ISSUE TITLE
delete the previous files created by a spout

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4877]
***This ticket was escalated from Zendesk by John Karabaic:***

**Ticket:** [#51](https://pachyderm.zendesk.com/agent/tickets/51)
**Type:** Ticket
**Priority:** -
**Requester:** samantha.zeitlin
**Organization:** Sentry.io
**Assignee:** John Karabaic
***

**What is the goal / desired outcome?**

As a data engineer, I would like to be able to delete files from within my spout code so that I can use it like any other input repo.

**If there is a way to accomplish this today via workaround, what does that require?**

Deleting the spout deletes all the files and downstream commits, but that seems like overkill

**(Optional) What is your proposal for a feature to solve this?**

It seems like an appropriate part of a spout SDK, since you can't do this via a tarfile.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(created from <a href='https://pachyderm.zendesk.com/agent/tickets/51'>Zendesk ticket #51</a>)<br>gz#51</i>

**Comment by pappasilenus** [comment]
Agent comment from Dale Georg in <a href='https://pachyderm.zendesk.com/agent/tickets/51'>Zendesk ticket #51</a>:<br><br>Feature request was created (Github issue #4877); closing the Support issue.

**Comment by jdoliner** [comment]
Now that spouts are pachctl based I think we have great answer to this one. You can delete files just like you would from any input repo using `pachctl delete file`. Closing, feel free to reopen if you feel like that doesn't satisfy the request.
