### ISSUE TITLE
S3 gateway should work with without authentication with S3 Clients

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4878]
**What is the goal / desired outcome?**

 As most s3 clients expect a nonempty password, the docs specify that the implementation allows using ANY key:pass combo if authentication is not enabled.

**If there is a way to accomplish this today via workaround, what does that require?**

No workaround, currently, but this used to work in earlier versions of the S3 Gateway when authentication wasn't enabled 

**(Optional) What is your proposal for a feature to solve this?**

Allow the use of any user key and secret when authentication is not enabled.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(created from <a href='https://pachyderm.zendesk.com/agent/tickets/48'>Zendesk ticket #48</a>)<br>gz#48</i>

**Comment by ysimonson** [comment]
You can use arbitrary access/secret keys when pachyderm auth is not enabled. I believe this was added in 1.10, but can dig up the specific PR if need be.
