### ISSUE TITLE
Environment Variables for input repos and input commits not created for service pipelines

### ISSUE THREAD

**Issue by gravesal33** [pachyderm/pachyderm#4883]
**What happened?**:
According to the 3rd bullet [here](https://docs.pachyderm.com/latest/reference/pipeline_spec/#environment-variables), an environment variable with the same name as an input should be created for pipelines.  When running a service pipeline, no such env variable is created.

**What you expected to happen?**:
Env variable with the name of my input with value equal to the path specified by my glob value

**How to reproduce it (as minimally and precisely as possible)?**:
`pachctl create repo my-test`
`echo "This is a test" | pachctl put file my-test@master:test_file`

Service pipeline config called `my-service.json`:
```
{
    "pipeline": {
        "name": "my-service"
    },
    "description": "test service pipeline",
    "transform": {
        "image": "ubuntu",
        "cmd": [
            "/bin/bash"
        ],
        "stdin": [ "echo $input_data" ]
    },
    "input": {
        "pfs": {
            "name": "input_data",
            "repo": "my-test",
            "glob": "/"
        }
    },
    "service": {
        "external_port": 30846,
        "internal_port": 10101
    }
}
```

`pachctl create pipeline -f my-service.json`

Run `pachctl logs -p my-service` and alas there is no value.

**Anything else we need to know?**:
Run the same pipeline config as above, but remove the "service" info.  Then run:
`pachctl logs -p my-service` to see the value of $input_data

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.10.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/74'>Zendesk ticket #74</a>)<br>gz#74</i>

**Comment by pappasilenus** [comment]
@nitinjainsj I've confirmed that this bug exists in 1.10.4.  Modified it to include the fact that the input commits are missing, as well.  I created the pipeline my-service and my-pipeline that just print out the environment to stdout, so the values should get logged.

```
$ pachctl logs -p my-service | grep -i input

$ pachctl logs -p my-pipeline  | grep -i input
input_data_COMMIT=908d778c4dc44f40a9f06c42680b18a5
input_data=/pfs/input_data
```
[Archive.zip](https://github.com/pachyderm/pachyderm/files/4726082/Archive.zip)
