### ISSUE TITLE
document how to exit the Pachyderm shell

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4895]
**Provide a link to the page with an issue:**

https://docs.pachyderm.com/latest/deploy-manage/manage/pachctl_shell/

**Describe what is wrong:**

The documentation doesn't mention how to exit the shell.

**Describe the suggested changes:**

Control-D will exit it.

A future release will feature an "exit" command

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by jdoliner** [comment]
Note that starting in 1.11 the shell will say "Type 'exit' or press Ctrl-D to exit." when you start it up, so you can probably just replicate that message.
