### ISSUE TITLE
Provide pre-built binaries for easier installs

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#490]
We can make a release CI job that creates the pre-built binaries for platforms we want to support.

This will allow the homebrew recipe to just download a binary. This would make the install a lot quicker.

(right now the brew formula declares go as a dependency ... so I think that means it will install it if it DNE ... but it takes a minute or so to install even with go already present)

And this would allow us to provide pre-packaged linux installs as well via #381

**Comment by sjezewski** [comment]
@sambooo this would be a good one to tackle next

I'll be revamping (maybe w more of your help) our release / automation process. The broad goal is to have our releases be completely automated. This is a part of that work. 

There are a few steps to this, so I'll add some more details:

1) Add make task for cross compilation
    - `make cross-compile` should create a binary for the last two versions of os x
    -  and whatever's reasonable for ubuntu
2) Update the 'pachyderm/homebrew-tap` repo to use these binaries
    - Right now the [formula](https://github.com/pachyderm/homebrew-tap/blob/master/pachctl.rb) clones and builds pachyderm from source
    - This has caused some bugs related to go versions ... and its slow
    - Please update the formula to use pre-compiled binaries instead

Those will be a PR on this repo and `pachyderm/homebrew-tap` respectively. Once we have each of those ready, we can hook these into #512 to automate all of this.

**Comment by sambooo** [comment]
In order to use github releases from travis, we'll need an encrypted access token which I personally can't get. See: https://docs.travis-ci.com/user/encryption-keys/ and https://gist.github.com/vinceallenvince/a7611b10f84e61eebdcc for an example .travis.yml

**Comment by sjezewski** [comment]
@sambooo's [PR](https://github.com/pachyderm/pachyderm/pull/579) was merged, but I'm leaving this open until I have it fully hooked into the new automated release scripts
