### ISSUE TITLE
add "failed uploads" troubleshooting section to docs

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4903]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/troubleshooting/general_troubleshooting/

**Describe what is wrong:**

Add a troubleshooting section for "failed uploads"

**Describe the suggested changes:**

Suggested section, please edit for clarity and style:

### Symptom

A file upload, particularly  a recursive one of many files, fails.  You may see a log messages containing the following in either pipeline logs, pachd logs, or from the pachctl command locally:

* pachctl errror:  `an error occurred forwarding XXXXX -> 650: error forwarding port 650`
* pachctl error: `EOF`
* pachd or worker: `all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:653: connect: connection refused\"; retrying in XXXX.XXXXXs"}`

### Recourse
Either `pachd` or your pipeline's worker sidecar may be getting OOM killed as it grows while getting data from object storage.  There are a couple of levers you can manipulate to get the storage container to stay within limits you set.

One of the ways you can give storage more resources is by increasing the `cache_size` parameter in your pipeline spec.  Increase it to what you can afford; its default is 64M.(If you’re using a release prior to 1.10.0 and you have cluster-wide or namepace policies on resource limits,  you may need to manually edit the pipeline RC.  This was fixed in PR#4675.)

If it still gets oomkilled by k8s, there are a couple of environment variables you can set on your pachd deployment to limit the amount of memory that sidecar and pachd use.

* `STORAGE_UPLOAD_CONCURRENCY_LIMIT` limits the parallelism to put files into the storage backend, and is available in 1.10.x. Default is 100.
* `STORAGE_PUT_FILE_CONCURRENCY_LIMIT`  is new in 1.10.4 and limits the number of parallel downloads pachd will initiate. Default is also 100.

You may use a binary search technique to hone in on a value appropriate for a production pipeline:

* for `cache_size`, max it out. If it works, halve it.  If it oomkills, increase that value by 50%. and so on
* for the `CONCURRENCY_LIMITS`,  halve and increase by 50% until you get a value that works.

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by mindthevirt** [comment]
This has been addressed by  #5179
