### ISSUE TITLE
Colorize `pachctl logs`

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4906]
**What is the goal / desired outcome?** Colorize pachd log output from `pachctl logs` when in a TTY to make it a little easier to skim contents. Pachd logs are well structured, so this should be straight-forward to do client-side.

**Comment by farhaanbukhsh** [comment]
hey @ysimonson I would like to work on this issue.

**Comment by farhaanbukhsh** [comment]
@ysimonson thanks a lot :), I go through the code and in case if you have any pointers to proceed with this it will be really helpful. Thanks in advance :smile:

**Comment by ysimonson** [comment]
Sure thing, here's the relevant chunk of code: https://github.com/pachyderm/pachyderm/blob/8552a543112a4794f66c47b7bef6665c6f8dc265/src/server/pps/cmds/cmds.go#L455-L493

Once you make changes, you can re-build `pachctl` via `make install`. Make sure that the new `pachctl` is referenced first in the `PATH`; the easiest way to do this is to run `pachctl version --client-only`, and ensuring it has the git commit sha of HEAD on the end, e.g. it should look something like this `1.11.0-0ecee9825ee76b441eb63bda85c138a55cada629`.

**Comment by farhaanbukhsh** [comment]
@ysimonson thanks a ton will create a PR soon

**Comment by ysimonson** [comment]
Awesome! Let me know if you hit any issues, or feel free to message on our slack.

**Comment by farhaanbukhsh** [comment]
Hey @ysimonson should the colour be on `log` level like Green for Info, Red for Warning or should be for different components?

**Comment by farhaanbukhsh** [comment]
Created a PR https://github.com/pachyderm/pachyderm/pull/4996
