### ISSUE TITLE
Tutorial for scraper

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#493]
The scraper example needs a readme and how to use it. I'm going to take a pass at this unless @jdoliner already is working on it.

Should the scraper example should also work as a standalone quickstart guide just like fruit stand? I'm thinking yes. They'll obviously both cover much of same details, but if users decide to try the scraper as their first pipeline it seems annoying to have to read through the fruit stand too to learn about mounting pfs, etc

**Comment by jdoliner** [comment]
Scraper has a tutorial attached to it. Closing.
