### ISSUE TITLE
Broken link issues

### ISSUE THREAD

**Issue by anchal-agrawal** [pachyderm/pachyderm#494]
Came across two typos:

* In [SETUP.md](https://github.com/pachyderm/pachyderm/blob/master/SETUP.md)'s `Intro` section, the bookmark link for GCP is broken.
* In [CONTRIBUTING.md](https://github.com/pachyderm/pachyderm/blob/master/CONTRIBUTING.md), the link to the FAQ page is broken.

I can take these up and submit a PR if needed.

**Comment by JoeyZwicker** [comment]
Thanks for pointing those out and for the PR Anchal! Link stability on GH is a constant problem. :)
