### ISSUE TITLE
Make git input how-to

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4957]
[We plan to deprecate built-in support for git hooks.](https://github.com/pachyderm/pachyderm/issues/4956) As an alternative, we'll need to make either a how-to, or an example (or both) demonstrating how to re-create the equivalent using a vanilla spout+service pipeline.

**Comment by svekars** [comment]
This likely to be deprecated after 1.12 or later.

**Comment by ysimonson** [comment]
There's no firm ETA yet, but yeah, I'd hazard to guess 1.12.

**Comment by nadegepepin** [comment]
Closing this as Git Input will be deprecated with the coming of 2.0 GA, early summer 2021.

**Comment by ysimonson** [comment]
This was about documenting the successor to git inputs, not git inputs themselves

**Comment by nadegepepin** [comment]
Hi Yusuf! Thx for checking in!!!! I believe build pipelines are documented.
Assuming that they are the "Next" Git Input. Or were you referring to
something else?

**Comment by ysimonson** [comment]
That sounds right!
