### ISSUE TITLE
Add a build step for pachyderm pipelines

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4958]
**What is the goal / desired outcome?** We plan to add basic support for build steps in pachyderm pipelines. This will draw from [`create_python_pipeline`](https://pachyderm.github.io/python-pachyderm/python_pachyderm.m.html#python_pachyderm.create_python_pipeline), but be more language-agnostic, built into `pachctl`, and a little cleaner (by avoiding a separate source repo and build pipeline.)

**If there is a way to accomplish this today via workaround, what does that require?**

1. Users can bake docker images and go through the normal pipeline update process.
2. Git hooks, though [they'll be removed shortly.](https://github.com/pachyderm/pachyderm/issues/4956)

**Comment by RaananHadar** [comment]
@ysimonson I humbly suggest you take a look at [S2I](https://github.com/openshift/source-to-image). Its an open source framework used by redhat for openshift, and is very extensible for third parties. Using S2I also has the benefit of Pachyderm appearing as a first class openshift citizen in the future. Source to Pachyderm pipeline anyone? :)

**Comment by ysimonson** [comment]
Thanks for the pointer @RaananHadar. I don't think that'll work for us, though, because the purpose of this would be to avoid baking docker images for a few reasons:

1. Not all environments include docker; in particular, it's not available in the pachyderm IDE due to its reliance on root privileges.
2. Building images requires an understanding of docker that some of our more data science-leaning users don't necessarily have.
3. Building/pushing images adds some rigamarole to updating pipelines. Usually this is OK, but it can get cumbersome when a tight iteration cycle is desired.
