### ISSUE TITLE
Broken and missing links in docs

### ISSUE THREAD

**Issue by anchal-agrawal** [pachyderm/pachyderm#497]
Found a few link issues:

1. On [README.md](https://github.com/pachyderm/pachyderm/blob/master/README.md), the bookmark for the `What's new about Pachyderm...` section is broken.
2. On [FAQ.md](https://github.com/pachyderm/pachyderm/blob/master/doc/FAQ.md):
  1. The pipeline doc link is missing in the `What are pipelines...` section.
  2. The protobufs API link is missing in the `How do I get data from other sources` section.

I'll submit a PR for these. @JoeyZwicker, what should the protobufs link point to?

**Comment by anchal-agrawal** [comment]
I'll submit a PR after fixing the protobufs link.

**Comment by JoeyZwicker** [comment]
Thanks so much for finding all of these! I can just fix both of those now myself. Great catch!
