### ISSUE TITLE
Relink docs repo to netlify to take advantage of selective builds

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#4970]
Looks like if we re-link to netlify it will only attempt builds on the docs folder, saving us a ton of build minutes and removing the netlify clutter from non docs PRs

>For sites connected to a Git repo after October 3rd, 2019, Netlify tries to determine if there are any changes in the site's base directory by comparing the last known version of the files within that directory. If no change was detected, the build system skips the build, returning early from the build process.
For sites created before October 3rd, 2019
If you would like to use this feature for a site that was created before October 3rd, 2019, you'll need to re-link your repository to make this feature available for your site.

[Source](https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds)

**Comment by svekars** [comment]
Thanks for sharing this @chainlink. It looks like "re-linking" means deleting the website on Netlify and then recreating again which likely means downtime. I will reach out to the Netlify team to find out if they have a better procedure for this.

**Comment by svekars** [comment]
This should be resolved now.
