### ISSUE TITLE
Cannot exit `pachctl mount` on macOS

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4982]
**What happened?**:
Cannot exit the `pachctl mount` mount with `CTRL+C`. It just hangs.

**What you expected to happen?**:
The command to exit when `CTRL +C` is pressed. 

**How to reproduce it (as minimally and precisely as possible)?**:
1. install fuse and sshfs:
    `brew cask install osxfuse`
    `brew install sshfs`
1. Deploy a 1.11.0-beta1 cluster locally on macOS.
1. Run `make opencv` from the `examples/` dir.
1. Run `pachctl mount pfs --write`.
1. Try to exit with `CTRL+C`
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.18.0
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.11.0-beta1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube (hyperkit)
- OS (e.g. from /etc/os-release): macOS
- Others:

**Comment by JimmyWhitaker** [comment]
I'm having this issue as well. 

CTRL+C doesn't escape the mount. 

Also tried:  
```bash
$ pachctl unmount ./pfs
operation not permitted
```

Environment?:

- Kubernetes version (use kubectl version):
```
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use pachctl version):
```
COMPONENT           VERSION
pachctl             1.11.0
pachd               1.11.0
```
Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local minikube
OS (e.g. from /etc/os-release): macOS Catalina 10.15.5

**Comment by JoeyZwicker** [comment]
pachctl mount isn't supported on Mac unfortunately. I dont know if unmount failing is something mac-specific that we can fix easily enough. But yeah, it's annoying that OSX has stopped support FUSE

**Comment by Irvenae** [comment]
The unmount issue is happening on linux as well.

**Comment by jdoliner** [comment]
@Irvenae sorry this is impacting you, we have a number of users running FUSE on Linux and they don't generally have this problem so it must be something fairly specific. Does it unmount if you `sudo umount` on the mount?

Also a general on FUSE support clarifying what @JoeyZwicker said before. FUSE support on Apple seems to be possible again thanks to some changes Apple made so it's no longer accurate to say it's not supported on macs.

**Comment by Irvenae** [comment]
This works 👍

**Comment by JoeyZwicker** [comment]
> FUSE support on Apple seems to be possible again thanks to some changes Apple made so it's no longer accurate to say it's not supported on macs.

Sweet!

**Comment by smalyala** [comment]
Not sure at which versions things started working but with the latest macOS and macFUSE versions, `pachctl mount` no longer hangs when interrupted with `ctrl+c`.
