### ISSUE TITLE
CI: Experiment with switching the examples bucket to hub

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4985]

**Comment by chainlink** [comment]
Overall I think this is a good direction, but we'll need an escape hatch for things like mismatched manifests / potentially other things hub doesn't support quite yet.

**Comment by chainlink** [comment]
@yusuf to create a hub cluster at a custom sha use the following request
```
POST /v1/organizations/<you_org_id>/pachs
{
	"data": {
		"attributes": {
			"pachVersion": "d8d7bea1596ec87e6270dcfbdea9716451854c1c"
		}
	}
}
```

**Comment by ysimonson** [comment]
Closing this out as per zoom conversation
