### ISSUE TITLE
Unable to connect to the server: dial tcp w.x.y.z:80: i/o timeout

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#499]
With respect to issue #498 

Same steps followed. However (on server side, Docker image for ubuntu not used, Apache not installed on Ubuntu container, hence port 80 not free)
Hence timeout occurs.

[root@localhost pachyderm]# make MANIFEST=manifest launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy ./src/server/cmd/pachctl-doc
kubectl -s 52.34.196.247 create -f manifest
Unable to connect to the server: dial tcp 52.34.196.247:80: i/o timeout
Makefile:107: recipe for target 'launch' failed
make: *** [launch] Error 1

**Comment by jdoliner** [comment]
Similar to #498. Your problem here is likely that you don't have port forwarding setup correctly or something like that. However it's not a Pachyderm issue, I'd recommend taking this issue to the kubernetes team they'll be much more able to help you with issues like this one.
