### ISSUE TITLE
Missing data link in Neon example

### ISSUE THREAD

**Issue by the-laughing-monkey** [pachyderm/pachyderm#4997]
In the Neon/Pachy example it links to a TSV file of sentiment analysis data that is non-existent:

https://s3-us-west-2.amazonaws.com/wokshop-example-data/labeledTrainData.tsv

**Comment by JoeyZwicker** [comment]
@dwhitena I believe this example, albeit old, was made by you. Do we still have this data somewhere or should we basically scrap this example completely?

**Comment by dwhitena** [comment]
@JoeyZwicker see https://github.com/pachyderm/pachyderm/pull/5012
