### ISSUE TITLE
Format volume - file command not found on server

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#500]
File command not found on server - CoreOS . Amazon (AWS) link for file (command not supported in CoreOS although CoreOS is recommended instance )

[root@localhost /]# cd my-cluster/
[root@localhost my-cluster]# kubectl --kubeconfig=kubeconfig get nodes
NAME                                      STATUS                     AGE
ip-10-0-0-50.us-west-2.compute.internal   Ready,SchedulingDisabled   1d
ip-10-0-0-87.us-west-2.compute.internal   Ready                      1d
[root@localhost my-cluster]# kube-aws status
Cluster Name:	oyeok-nexchanges
Controller IP:	52.34.196.247

[root@localhost /]# ssh -i /td-key-pair-oregon.pem core@ec2-52-34-196-247.us-west-2.compute.amazonaws.com
Last login: Thu Jun  9 13:20:10 2016 from 125.99.120.242
CoreOS stable (1010.5.0)
Update Strategy: No Reboots
core@ip-10-0-0-50 ~ $ sudo su
ip-10-0-0-50 core # cd ..
ip-10-0-0-50 home # cd ..
ip-10-0-0-50 / # cd ..

ip-10-0-0-50 core # lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   30G  0 disk 
|-xvda1 202:1    0  128M  0 part /boot
|-xvda2 202:2    0    2M  0 part 
|-xvda3 202:3    0    1G  0 part /usr
|-xvda4 202:4    0    1G  0 part 
|-xvda6 202:6    0  128M  0 part /usr/share/oem
|-xvda7 202:7    0   64M  0 part 
`-xvda9 202:9    0 27.7G  0 part /
xvdb    202:16   0    4G  0 disk 
xvdf    202:80   0   10G  0 disk 

ip-10-0-0-50 core # sudo file -s /dev/xvdf
sudo: file: command not found

ip-10-0-0-50 / # sudo file -s /dev/xvdf
sudo: file: command not found

Using the command , step 3
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

**Comment by jdoliner** [comment]
This isn't an essential part of setup. `file` is just used to check if you're blowing away data on the drive.
If you want to accomplish this on CoreOS you should run a container with `/dev/xvdf` mapped in that has `file` installed. Ubuntu should work well for that.

Either way we don't have the ability to fix this. We don't determine what goes into the CoreOS images.
