### ISSUE TITLE
Pachyderm Init Containers in CrashLoopBackOff due to argument list too long error when after ~2000 services in namespace

### ISSUE THREAD

**Issue by ronaldosaheki** [pachyderm/pachyderm#5006]
**What happened?**:

New pods are not running due to error in Init Container:
```
Init Containers:
init:
Container ID:  docker://0deade6d4fc11be9af5cde7198e600405ae759291aa244cb2fa8b152747743be
Image:         pachyderm/worker:1.9.12
Image ID:      docker-pullable://pachyderm/worker@sha256:d00490adf160fe2cb62aa1835087a647d8d555089584ce2a9418e350be36e1b0
Port:          <none>
Host Port:     <none>
Command:
/pach/worker.sh
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       Error
Exit Code:    1
Started:      Tue, 09 Jun 2020 20:20:35 +0100
Finished:     Tue, 09 Jun 2020 20:20:35 +0100
Ready:          False
Restart Count:  15
```

When checking the log of the init container:
```
standard_init_linux.go:211: exec user process caused "argument list too long"                                     stream closed
```

It started to happen when we created a staging environment for pachyderm that would trigger deployment of pipelines and after some weeks each pipeline had around 250 versions in history, which translated in 250 services/endpoints per pipeline and ~2000 in total in kubernetes.

**CAUSE/Quick FIX solution**
 It happens because the environment variables for services is too long when having ~2000 services, it could be fixed by setting enableServiceLinks to False (https://github.com/kubernetes/kubernetes/issues/84539) or by removing some services.

**What you expected to happen?**:

Pachyderm should delete services/endpoints from previous versions of the pipeline.

**How to reproduce it (as minimally and precisely as possible)?**:

Deploy ~2000 versions of a pipeline and the pipeline will not be able to launch the pod to ready due to init container error by the environment variables created for each service in kubernetes in that namespace.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
$ pachctl version
COMPONENT           VERSION             
pachctl             1.10.4              
pachd               1.9.12     

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
aws

- OS (e.g. from /etc/os-release):
- Others:

**Comment by msteffen** [comment]
Thanks for reporting this @ronaldosaheki. Pachyderm's old behavior—not deleting k8s services when pipelines are updated—was a bug that should be fixed in Pachyderm >1.10.3 (also reported in https://github.com/pachyderm/pachyderm/issues/1732 and https://github.com/pachyderm/pachyderm/issues/4071). I think if you update your cluster (which seems to be on 1.9.12) then that should hopefully solve the problem.

I'm marking this issue closed because we're not planning to take any further action on it, but please feel free to re-open if needed.
