### ISSUE TITLE
Move pachd back to /pachd in 1.11 for backward compatibility in manifest

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#5015]
Looking through the 1.11 manifest it looks like the only breaking change is the `/pachd` to `/app/pachd` move. Since this mostly a stylistic change, I think we should move back to the old location to ease the potential support burden of the change and reducing breaking changes makes it easier to deploy given branches or new versions to Hub. This is particular important as we start to dogfood hub into CI and allow arbitrary Pach SHA's in Hub

cc @ysimonson

**Comment by ysimonson** [comment]
For context, the stylistic aspect is that we now use the `/app` on both the worker and pachd images. The alternative is that we can support the old path by [symlinking `/pachd` -> `/app/pachd`](https://github.com/pachyderm/pachyderm/pull/5013), though admittedly it has its own stylistic downsides.

**Comment by jdoliner** [comment]
I think it's probably easiest to just move back to the old path for now. That seems like the easiest way to support backward compatibility. This is something we could fix in the 2.0 release if we want to unify the two container images.
