### ISSUE TITLE
Consistency error: the branch master on repo (pipeline) could not be found 

### ISSUE THREAD

**Issue by ronaldosaheki** [pachyderm/pachyderm#5046]
**What happened?**:
Updates to ANY pipeline was not working with the message: 
 could not create/update output branch: rpc error: code = Unknown desc = /pachyderm_pfs/repos/ pipelinenot found

The most intriguing was that we deleted one of the crossinput input pipeline/repo a day ago.

Checking pachctl fsck:
```
Error: consistency error: the branch master on repo pipelinecould not be found 
Error: consistency error: the commit 215699dc53c6403ca8d14900fec88ea4 in repo pipeline could not be found while checking provenance transitivity 
Error: consistency error: the commit 215699dc53c6403ca8d14900fec88ea4 in repo pipeline could not be found while checking provenance for provenance-subvenance duality (=>) 
```

It looks like the pipeline that was using this as input kept commits with provenance from the deleted repo/pipeline.

**Workaround/Fix you are able to delete pipeline**

To fix this problem we **deleted the pipeline that was using the already deleted pipeline as crossinput**. Afterwards we could update successfully other pipelines and fsck had no errors.

**What you expected to happen?**:

Removing a pipeline that was used as crossinput should not create inconsistency and block update operations.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a crossinput pipeline, process some commits and then delete the one of the inputs of crossinputs.

**Anything else we need to know?**:

N/A

**Environment?**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
COMPONENT           VERSION
pachctl             1.10.5
pachd               1.9.12

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
AWS

- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/92'>Zendesk ticket #92</a>)<br>gz#92</i>

**Comment by JoeyZwicker** [comment]
@adelelopez I thought we prevent the users from deleting a repo/pipeline that would break provenance like this? 

@ronaldosaheki did you use `--force` to delete that pipeline?

**Comment by JoeyZwicker** [comment]
How do we want users to handle the need to do this correctly?

**Comment by JoeyZwicker** [comment]
@ronaldosaheki Can you be a bit more explicit about repro steps and exactly what you're trying to accomplish? Specifically:

For discussion simplicity, let's use an example of a pipeline `C` that takes both `A` and `B` as crossed inputs. So your DAG looks like this:
```
Repo: Input A --> Pipeline: A --> Repo: output A
                                                 \
                                                   > cross >  C
                                                 /                                                                         
Repo: Input B --> Pipeline: B --> Repo: output B
```
1. Was the `--force` flag used to delete pipeline B?
2. Do you want to just delete pipeline `B` (leaving the input and output repos) or do you want to delete `input B`, `pipeline B` and `output B`?
3. Before deleting any part of `B`, did you change your pipeline spec `C` to only take `A` in input (e.g. no longer using cross)?
4. Do not that while you've upgraded your pachctl to the latest version, you are still running 1.9.12 of pachd. That's fine and I dont _think_ that mismatched should effect this issue, but we may need to test later if this still happens on the latest version.

**Comment by adelelopez** [comment]
Yeah, I think this is a new provenance consistency bug.

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/92'>Zendesk ticket #92</a>:<br><br>Hi, Ronaldo,

We'd love to be be able to help you out with this. Are you able to answer our questions?

 Can you be a bit more explicit about repro steps and exactly what you're trying to accomplish? Specifically:
For discussion simplicity, let's use an example of a pipeline `C` that takes both `A` and `B` as crossed inputs. So your DAG looks like this:

    Repo: Input A --> Pipeline: A --> Repo: output A \ > cross > C / Repo: Input B --> Pipeline: B --> Repo: output B

1. Was the `--force` flag used to delete pipeline B?
2. Do you want to just delete pipeline `B` (leaving the input and output repos) or do you want to delete `input B`, `pipeline B` and `output B`?
3. Before deleting any part of `B`, did you change your pipeline spec `C` to only take `A` in input (e.g. no longer using cross)?
4. Do not that while you've upgraded your pachctl to the latest version, you are still running 1.9.12 of pachd. That's fine and I dont _think_ that mismatched should effect this issue, but we may need to test later if this still happens on the latest version.

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/92'>Zendesk ticket #92</a>:<br><br>Hi, Ronaldo,

We haven't heard back from you on this.  Are you able to give us some more details?

**Comment by nitinjainsj** [comment]
Using --force can cause this inconsistency. Please reopen with steps to repo this issue.
