### ISSUE TITLE
cli commands could be rearranged

### ISSUE THREAD

**Issue by sambooo** [pachyderm/pachyderm#505]
Since pachctl uses cobra, I think it makes sense to follow the patterns `APPNAME VERB NOUN --ADJECTIVE` and `APPNAME COMMAND ARG --FLAG` it suggests, not only for convention but because also subcommands should be suffixes instead of prefixes.

So, this means instead of:
```shell
$ pachctl create-repo
$ pachctl list-commit
$ pachctl delete-pipeline
```
we would have
```shell
$ pachctl repo create
$ pachctl commit list
$ pachctl pipeline delete
```

Also it's important to consider that right now pachctl operates on (mostly) just five datatypes: `repo, commit, file, job, pipeline` but the command list already pretty-prints 30 lines. Not much room to grow there without overflowing most terminals which makes help output annoying to read.

In my opinion, this:
```shell
Available Commands:
  repo             Docs for repos.
  create-repo      Create a new repo.
  inspect-repo     Return info about a repo.
  list-repo        Return all repos.
  delete-repo      Delete a repo.
  commit           Docs for commits.
  start-commit     Start a new commit.
  finish-commit    Finish a started commit.
  inspect-commit   Return info about a commit.
  list-commit      Return all commits on a set of repos
  flush-commit     Wait for all commits caused by the specified commits to finish and return them.
  list-branch      Return all branches on a repo.
  file             Docs for files.
  put-file         Put a file from stdin
  get-file         Return the contents of a file.
  inspect-file     Return info about a file.
  list-file        Return the files in a directory.
  delete-file      Delete a file.
  mount            Mount pfs locally.
  job              Docs for jobs.
  create-job       Create a new job. Returns the id of the created job.
  inspect-job      Return info about a job.
  get-logs         Return logs from a job.
  list-job         Return info about jobs.
  pipeline         Docs for pipelines.
  create-pipeline  Create a new pipeline.
  inspect-pipeline Return info about a pipeline.
  list-pipeline    Return info about all pipelines.
  delete-pipeline  Delete a pipeline.
  run-pipeline     Run a pipeline once.
  version          Return version information.
```
is harder to read than this:
```shell
Available Commands:
  repo             Create, delete, inspect, list and update repositories
  commit           Start, finish, flush, inspect and list commits
  branch           List branches
  file             Put, delete, get, inspect and list files
  mount            Mount pfs locally
  job              Create, inspect, list and view logs for jobs
  pipeline         Create, delete, inspect, list and run pipelines
  version          Return version information
```

**Comment by sambooo** [comment]
Willing to tackle this myself but I'd like to know what you guys think first

**Comment by ChaiBapchya** [comment]
Even I would like to help and contribute in resolving this. Since it would be more legible and comprehensible when re-arranged in that fashion..

**Comment by jdoliner** [comment]
We considered doing this awhile ago when we were first designing the CLI and ultimately decided against it. We saw the same benefit you do, that commands could automatically be organized by the noun rather than the verb which would make the docs more browsable. After using it for a little while though we realized it was too confusing so we switched it back.

If cobra does indeed recommend that commands be `APPNAME VERB NOUN --ADJECTIVE` then that seems like an argument not to do this. Since I think that's what we already have. Furthermore that's the way `kubectl` organizes things and people are normally going to be using both of them which means it'll be even more confusing if they call it `delete job` while we call it `job delete`.

I think we can get a lot of the benefits of this by making a custom help function, that way we can directly control how the commands are printed.

**Comment by sambooo** [comment]
I suppose then a simple redesign would be more like this:
```shell
Available Commands:
  create
  delete
  list
  ...
```
at which point it does become pretty much pointless, yeah. I had it backwards without thinking after too much `gcloud`.

In this new case the only change to the typed commands would be spaces instead of hyphens which isn't a change worth breaking it for. A shorter help text with the same command names would be best for the end-user but it's prone to getting out of sync with the code.

Could be possible to rewrite commands into this new form and just alias the current names in code by replacing hyphens with spaces. A key benefit there would be that docs would all be tightly coupled to their commands, but at the cost of having some glue holding it together.

Do you have an approach in mind that could let us decorate the command tree with info about list-, create-, delete-, inspect-, and the like without significantly changing the implementation of individual commands? Perhaps prefix matching on commands and storing help per-prefix in a map somewhere, then stitching it together at runtime would work too.

The easiest approach though is to do nothing for now, unless it breaks.
