### ISSUE TITLE
Smarter standby

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#5059]
Currently, standby mode for pipelines is an on/off thing, and defaults to being disabled. This doesn't work great for hub, where an autoscaler will [de-]provision resources on-demand; i.e. since standby is disabled by default, resources will stick around when they're not necessary, bloating costs.

We considered a feature flag to just explicitly enable standby mode by default, but [it introduced its own problems,](https://github.com/pachyderm/pachyderm/pull/5053#issuecomment-652011148) including the fact that we'd risk significant performance degradations in some workloads in frequently scaling from 1->0 or 0->1 nodes in the autoscaled pool (which is a time-consuming operation.)

Pachyderm 2.0 will introduce the opportunity to make backwards-incompatible changes, which will allow us to consider smarter standby modes, namely:

* Defaulting to standby mode enabled.
* Having richer semantics than standby being just a boolean, so that we can ensure some minimum resource allocation that prevents the autoscaler from thrashing.

**Comment by echohack** [comment]
@jdoliner Does `autoscaling` close out this issue?

**Comment by jdoliner** [comment]
`autoscaling` doesn't do all the stuff talked about in this issue but through the autoscaling design process we decided we don't want to do everything here. So I'll go ahead and close this.
