### ISSUE TITLE
Add stack traces to errors

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#508]
We spend a lot of debugging time just trying to figure out which line an error is coming from.

This package: https://godoc.org/github.com/pkg/errors could help a lot with that and shouldn't be too hard to integrate.

**Comment by jdoliner** [comment]
This functionality will be coming to the go stdlib in 1.13, this pkg implements the behavior already: https://godoc.org/golang.org/x/xerrors. This should be a good opportunity to implement it, the main remaining question is how this will be integrated into grpc, since it won't be much good if the stack traces can't cross rpc boundaries. I'm hoping that once it's in the stdlib grpc will support it pretty quickly thereafter.

**Comment by ysimonson** [comment]
Addressed by #4681
