### ISSUE TITLE
Make version numbers prettier and not so spammy.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#511]
I think we should change our version numbers to look like `1.0.0` rather than `1.0.0(849)` having a random build number in there that doesn't mean anything to users is a bit weird.

Also while we're at it I don't think we need anywhere near as many tagged versions as we have. I don't think we've used any of the tags besides `1.0.0(849)` for all the other versions people have just been spinning the server up directly from the repo so the commit hash acts as a de facto version number.

**Comment by sjezewski** [comment]
OK - so we'd:

- omit the last string altogether
- and every time we release, we have to (at least) bump the point number
    - if we automate the release process (see #512) this is easy to enforce

**Comment by sambooo** [comment]
Is [Semantic Versioning](http://semver.org/) what you're after?

**Comment by sjezewski** [comment]
I think we're closing in on something much like semantic versioning. But for now, we're doing what makes sense timing wise when we release (not worrying too much about strict rules at the moment).

We'll see what our build/tagging system allows for this point release this week. That'll also inform how we move towards a standard.
