### ISSUE TITLE
`RestartDatum` backwards-incompatible in 1.11

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#5123]
**What happened?**: In 1.11, `RestartDatum` now requires `data_filters` to be populated.

**What you expected to happen?**: This field was optional prior to 1.10. Changing it to required breaks out backward compatibility promise.

**How to reproduce it (as minimally and precisely as possible)?**: See [this test in python-pachyderm](https://github.com/pachyderm/python-pachyderm/blob/9e3fe9d955efea15272a89c5ebb086764378906a/tests/test_pps.py#L79) - the last line will fail:

```python
def test_datums():
    sandbox = Sandbox("datums")
    job_id = sandbox.wait_for_job()

    # flush the job so it fully finishes
    list(sandbox.client.flush_commit([(sandbox.input_repo_name, sandbox.commit.id)]))

    datums = list(sandbox.client.list_datum(job_id))
    assert len(datums) == 1
    datum = sandbox.client.inspect_datum(job_id, datums[0].datum_info.datum.id)
    assert datum.state == python_pachyderm.DatumState.SUCCESS

    # Just ensure this doesn't raise an exception
    sandbox.client.restart_datum(job_id)
```

This [works on 1.10](https://travis-ci.org/github/pachyderm/python-pachyderm/jobs/710004061), but [fails on 1.11](https://travis-ci.org/github/pachyderm/python-pachyderm/jobs/710004060).

**Comment by JoeyZwicker** [comment]
If it's not too much trouble, whenever this get tackles would be lovely to have the docs and explanation portion of restart datum as described in #3160 also addressed.

**Comment by nitinjainsj** [comment]
With 1.10, when data_filter was not provided it would be a no-op but it would also not print out any errors. With 1.11, we error out the command. So this may be backward incompatible for the command and its output. The behavior in 1.11 makes clear what's happening.
