### ISSUE TITLE
Track module checksums across all tagged versions of pachyderm go library

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#5145]
**What is the goal / desired outcome?** We need a way to keep track of checksums across all tagged versions of the pachyderm go library, as any of our dependencies can break our checksum. This will prevent issues [like this](https://github.com/pachyderm/pachyderm/issues/5143) going forward.

**Comment by jrockway** [comment]
I have done some investigation on what data is required to write such a tool.

I created some example projects so it's easy to reason about what's going on.  github.com/jrockway/evil-module-user is small go program that depends on github.com/jrockway/evil-module.  When evil-module-user was written, github.com/jrockway/evil-module@v0.0.1 was a good module.  Then "they" released a new version that made the module "evil", and force-pushed the v0.0.1 tag again.  Now when you attempt to `go run main.go` in the evil-module-user repository, you get:

```
$ GOPROXY=direct go run main.go
go: downloading github.com/jrockway/evil-module v0.0.1
verifying github.com/jrockway/evil-module@v0.0.1: checksum mismatch
        downloaded: h1:8hZfcGWxgwLDlFobA01ibehmq113HI83t6mw9lLzEUI=
        go.sum:     h1:ddshoT5twMMhZ18FKG+6u1gJ74vRDGLItYxftMxkbBI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

That's what you'd expect.  When the author of evil-module-user first ran their program that depended on evil-module, the checksum of evil-module@v0.0.1 was h1:ddshoT5twMMhZ18FKG+6u1gJ74vRDGLItYxftMxkbBI=.  Now it's h1:8hZfcGWxgwLDlFobA01ibehmq113HI83t6mw9lLzEUI=.  

Note that, in GOPATH mode, go.sum is ignored, so if you `go get github.com/jrockway/evil-module-user` and run `evil-module-user` you'll get the "evil" version (it just prints "This module has turned evil!").  Behind the scenes, go appears to just git clone that repository and checks out the tag; it does no comparison against the go.sum file.  (In non-GOPATH mode, i.e. in a directory with go.mod, it does check, and the check fails.)

I wrote a small tool to contact the Go module sum database server and ask what Google thinks the module checksum is (in pachyderm/sumlint):
```
$ go run main.go
0.159s https://sum.golang.org/lookup/github.com/jrockway/evil-module@v0.0.1
0.020s https://sum.golang.org/tile/8/2/000.p/22
0.022s https://sum.golang.org/tile/8/0/x005/791.p/221
0.024s https://sum.golang.org/tile/8/1/022.p/159
[github.com/jrockway/evil-module v0.0.1 h1:ddshoT5twMMhZ18FKG+6u1gJ74vRDGLItYxftMxkbBI=]
```
Note that that's the "good" version of the module.

Where this is all going is that linting the checksums is going to be more complicated than I thought.  My initial thought was to just make an API request to the Google checksum database, and see if any lines in go.sum didn't match.  That isn't quite what we want in that case.  That lint would detect the case where a developer has a cached copy of an "evil" module, and the rest of the world has the good one.  

I think the more common case is this force push case, and to detect that, we have to clone the repositories ourselves and compute the checksum on the repository.

Complicating factors is how many places the "good" module is cached in.  By default "go mod update" or "go get" will use the Google Module Proxy, which caches the "good" version of the module.  You'll only get the "evil" version of the module if you set "GOPROXY=direct" (or use your own proxy, probably common inside big companies).

I have nothing against writing a tool to go build every version without a module cache.  But now that I've looked into this deeply, I think that even if an upstream tampers with their modules, it's likely that users will still get the version that we specify in our go.sum file.

Obviously, the next step is to look into the exact cases that Pachyderm customers have experienced, to see why the cache didn't save them.  I will do so!

**Comment by jrockway** [comment]
Oh... actually... I tried making this module

```
module github.com/pachyderm/example-broken-go-mod-project

go 1.14

require github.com/pachyderm/pachyderm v1.10.0
```

And `go mod download` does indeed fail:

```
$ go mod download
github.com/pachyderm/pachyderm@v1.10.0: verifying module: checksum mismatch
        downloaded: h1:CxSSPe5FaVzWWqltiX5sYF13v25mGIacQyD+fSuDXZQ=
        sum.golang.org: h1:kfWVPEoi8pXR+0sndL2vOKoOdFNxLtBMoK2oZvScfHo=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I am now looking to why a bad checksum is cached for our code.

**Comment by jrockway** [comment]
After some discussion yesterday, it appears that we intentionally re-tagged some releases.  Going forward, we should not do that, and this should not be a problem.

**Comment by jrockway** [comment]
The mitigation I recommend for users that want to use exactly Pachyderm v1.10.0 is to tag the same commit with a different version number.  go "helpfully" converts a commit hash in go.mod to this tag, unfortunately, so that won't work as a workaround.
