### ISSUE TITLE
Give user feedback that filesystem is mounted.

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#516]
mkdir ~/pfs
mkdir: cannot create directory ‘/root/pfs’: File exists
[root@chai /]# pachctl mount ~/pfs
^[[D^Z
[1]+  Stopped                 pachctl mount ~/pfs
[root@chai /]# pachctl mount ~/pfs &
[2] 3349
[root@chai /]# ls ~/pfs
**HANGS**

 mkdir ~/pfs2
[root@chai /]# pachctl mount ~/pfs
^[[D^C
[root@chai /]# pachctl mount ~/pfs2 &
[1] 3670
[root@chai /]# ls ~/pfs2
data1      filter2   filter7   sum001  test007  test010
filter001  filter3   filter78  sum1    test008  test011
filter007  filter56  sum       test    test009  test2

Thus, when we try to mount an existing directory and load it with repos from Server, it does not list.
Creating a new directory, mounting it and then loading repos works.
Does this mean, I would have to erase the directory to be able to load the repo everytime or mount it a new mount point?..
Shouldn't it enable refreshing and updating the PFS at existing mountpoint and
NOT HANG when Listing PFS?

Wanted more information on how pfs works (on server vis-a-vis on localhost)
Am I right?- 
On GCS we deploy Pachyderm (along with Kubernetes installed)
Using pachctl commands on Localhost (with the Address of the external DNS/I.P. of the server), we
1.Create repo
2. Create files
3.Commit the files
Once committed, they are stored in the server PFS
So, next time we pachctl mount PFS at a given mount point locally, we should be able to view the related commits in the created repos.

**Comment by jdoliner** [comment]
Hey @ChaiBapchya sorry you ran into this, here's what's going on.

```
mkdir ~/pfs
mkdir: cannot create directory ‘/root/pfs’: File exists
[root@chai /]# pachctl mount ~/pfs
<pfs is now mounted>
^[[D^Z
[1]+ Stopped pachctl mount ~/pfs
<pfs is still mounted but the mount process is now stopped>
[root@chai /]# pachctl mount ~/pfs &
[2] 3349
[root@chai /]# ls ~/pfs
HANGS
<this hangs because the mount process is stopped>
```

This is definitely a confusing behavior. I think we should add a comment so the user has some idea the mount succeeded. Something like: `"Successfully mounted pfs on /mount/path. CTRL+C to unmount."`

**Comment by ChaiBapchya** [comment]
Sir, even if we mount it in this fashion

[root@chai /]# mkdir ~/pfs
mkdir: cannot create directory ‘/root/pfs’: File exists
[root@chai /]# pachctl mount ~/pfs &
[2] 4240
*Pachctl is mounted and Process id is output*

[root@chai /]# ls ~/pfs
It **HANGS**

**Comment by jdoliner** [comment]
The old mount is probably still there. What if you do `umount ~/pfs` and try again?

**Comment by ChaiBapchya** [comment]
Realising that old mount is still present - Tried unmount the pfs

umount ~/pfs
^C
[root@chai /]# pachctl umount ~/pfs
bash: pachctl: command not found...
[root@chai /]# umount ~/pfs

**HANGS**

**Comment by sjezewski** [comment]
This fix landed on master
