### ISSUE TITLE
Improper commits used when a pipeline is crossed with its ancestor

### ISSUE THREAD

**Issue by ryansmith23** [pachyderm/pachyderm#5172]
**What happened?**:

We have a pipeline ("Imputed SNP Chip Datasets") that has a Cross input of two pipelines. One of these inputs is also an ancestor of the other pipeline. This one input (see below) is called "SNP Chip Reference Set." This repo follows the deferred processing concept and every time we want to persist one of the results we assign it to a branch (e.g., freeze-1). Once one of the results is persisted it is added as input for the Cross. The idea is that for every saved "SNP Chip Reference Set' we want to perform this "imputation" operation on each Dataset from "SNP Chip Datasets" and organize them into folders based upon the reference set used.

![Pachyderm Genetics Pipeline - Pachyderm Issue](https://user-images.githubusercontent.com/32345279/89204135-98d8d280-d583-11ea-9f60-ed653a3c8fbb.png)

The issue we're facing now is that not all datasets from "SNP Chip Datasets" are being processed. It appears to be randomly determining the input commit that is used to be either "Commit 1" or "Commit 2" (these are the ancestor commits that were used for setting the branches of freeze-1 or freeze-2). It will never use the latest commit for this operation. Similarly, I cannot manually run pipeline and specify the commits.

Here is the pipeline definition:

```
{
  "pipeline": {
    "name": "ImputedSNPChipDatasets"
  },
  "transform": {
    "image": "<redacted>",
    "cmd": [ "bash" ],
    "stdin": [
      "ref=(/pfs/*/reference_set.snp)",
      "path=\"${ref[0]%/*}\"",
      "name=\"${path##*/}\"",
      "impute /pfs/SNPChipDatasets/ \"/pfs/${name}/reference_set.snp\" \"/pfs/out/${name}/\""
    ],
    "image_pull_secrets": [ "github-registry" ]
  },
  "standby": true,
  "enable_stats": true,
  "resource_requests": {
    "cpu": 8,
    "memory": "12G"
  },
  "parallelism_spec": {
    "constant": 6
  },
  "pod_spec": "{\"tolerations\": [ { \"key\": \"node-pool\", \"operator\": \"Equal\", \"value\": \"high-cpu\", \"effect\": \"NoSchedule\" } ]}",
  "input": {
    "cross": [
      {
        "union": 
          {
            "pfs": {
              "repo": "SNPChipReferenceSet",
              "glob": "/reference_set.snp",
              "name": "freeze-2020-01-20",
              "branch": "freeze-2020-01-20"
            }
          },
          {
            "pfs": {
              "repo": "SNPChipReferenceSet",
              "glob": "/reference_set.snp",
              "name": "freeze-2020-05-17",
              "branch": "freeze-2020-05-17"
            }
          }
        ]
      },
      {
        "pfs": {
          "repo": "SNPChipDatasets",
          "glob": "/*"
        }
      }
    ]
  }
}
```

Here are the latest commits on the `SNPChipDatasets` repo:

```
$ pac list commit SNPChipDatasets@master
SNPChipDatasets master 2754dde8121e4c708fb7f7729236d999
SNPChipDatasets master d2148de531fe4d9aa7c712182c12611b
SNPChipDatasets master dbba4a826f6c4f39b6e09815cb24a3a2
SNPChipDatasets master 407a72b82f554eb3b8c1f6905a29c9bc
SNPChipDatasets master 9eb657269b3a45eaae65a25db6656b2f
SNPChipDatasets master fbb79e0cf23749c39b2a6f979be7593b
SNPChipDatasets master 3fd5c9e041584dec999cfccf0e681c76
SNPChipDatasets master 7c30db68975440fc8c76a97fdb55f747
SNPChipDatasets master dacda36132e64710b63d285fdda6c9ac
SNPChipDatasets master dae3f0d997604faf8cf7cb9deec3afdf
SNPChipDatasets master 88562b6a0a984c9bafe4e8f22fb4624e   --- This is the commit being used
SNPChipDatasets master 0620ffe0b89744ad8a95fdd5da21e963
SNPChipDatasets master 5a0cc27cc90b4150800347e3309b8e8c
SNPChipDatasets master 826916baeb97427b86a04b79978df3de
SNPChipDatasets master db545e83ba0e4cd483003c19c5c76d21
SNPChipDatasets master d616c91f1d934e4e8e44258849fc056d
SNPChipDatasets master 7eeaaa1af35e47b1afc93e277ef91eb8
```

And here is the output of inspecting the latest job on `ImputedSNPChipDatasets`:

```
$ pac inspect job 2d1c2f694afd4e68babdbc6765f4ac9a (which is latest on this pipeline)
ID: 2d1c2f694afd4e68babdbc6765f4ac9a 
Pipeline: ImputedSNPChipDatasets  
Started: 3 days ago 
Duration: 9 seconds 
State: [32msuccess[0m
Reason: 
Processed: 0
Failed: 0
Skipped: 60
Recovered: 0
Total: 60
Data Downloaded: 0B
Data Uploaded: 0B
Download Time: Less than a second
Process Time: Less than a second
Upload Time: Less than a second
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER              JOB                 DATUM               STARTED             QUEUE               
Restarts: 0
ParallelismSpec: constant:6 
ResourceRequests:
  CPU: 8
  Memory: 12G 

Input:
{
  "cross": [
    {
      "pfs": {
        "name": "SNPChipDatasets",
        "repo": "SNPChipDatasets",
        "branch": "master",
        "commit": "**88562b6a0a984c9bafe4e8f22fb4624e**",
        "glob": "/*"
      }
    },
    {
      "union": [
        {
          "pfs": {
            "name": "freeze-2020-01-20",
            "repo": "SNPChipReferenceSet",
            "branch": "freeze-2020-01-20",
            "commit": "2b972a53d81e48a8837fca8828b17432",
            "glob": "/"
          }
        },
        {
          "pfs": {
            "name": "freeze-2020-05-17",
            "repo": "SNPChipReferenceSet",
            "branch": "freeze-2020-05-17",
            "commit": "a02bdc64a3da43af8451400dd19692a9",
            "glob": "/"
          }
        }
      ]
    }
  ]
}

Transform:
{
  "image": "",
  "cmd": [
    "bash"
  ],
  "image_pull_secrets": [
    "github-registry"
  ],
  "stdin": [
    "ref=(/pfs/*/reference_set.snp)",
    "path=\"${ref[0]%/*}\"",
    "name=\"${path##*/}\"",
    "impute /pfs/SNPChipDatasets/ \"/pfs/${name}/reference_set.snp\" \"/pfs/out/${name}/\""
  ]
} 
Output Commit: 31a3693aa4a3447dba557eaab131d99d  
Stats Commit: 0a47452defd74ea1bb76ea8d90991fb9  
```

When looking at the provenance for the reference set:
```
$ pac inspect commit SNPChipReferenceSet@freeze-2020-01-20
Commit: SNPChipReferenceSet@2b972a53d81e48a8837fca8828b17432
Original Branch: latest
Parent: a6147e2d9c7b4386b06a59c337b4d2a2
Started: 2 months ago
Finished: 2 months ago
Size: 42MiB
Provenance:  __spec__@ee370bddc8ba4b7c8d88a947db2b6f80 (SNPChipDataset)  SNPChipDatasets@88562b6a0a984c9bafe4e8f22fb4624e (master)  __spec__@fff38ff37ebd4840b85a075423a76f64 (SNPChipReferenceSet)  GeneseekReports@54312595c9774883960d9771b293bd89 (master)  SNPChipDataset@b8393e90b530492b9e93ce5fed7b3e7c (master)  __spec__@1862413da22f473394485187c40e9970 (SNPChipDatasets)  
```

Notice how the **88562b6a0a984c9bafe4e8f22fb4624e** commit is the one being used throughout. If we pick another execution of the job it might have used the provenance of the other freeze branch.

**What you expected to happen?**:

We expect it to use the latest commit on master branch when pulling from "SNP Chip Datasets."

**How to reproduce it (as minimally and precisely as possible)?**:

I believe what is in the diagram is the most minimal way to reproduce it. I am going to test this out more and I will let you know if I can simplify it further.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.14.10-gke.42
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.10.3 for both
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE
- OS (e.g. from /etc/os-release): Arch Linux -- Linux 5.6.13
- Others:

We believe this may be a new issue that started after upgrading to pachyderm 1.10.3 from 1.9.6 (I believe).

**Comment by jdoliner** [comment]
This is a corner case that our provenance system doesn't currently handle. The provenance system is designed with the assumption that each job only processes one commit from each branch, this generally makes sense as a constraint because it gives a consistent view of the world. Different commits on the same branch represent different versions of the same data, and a lot of confusing things can happen if you're using different versions of the same data set. I realize though that it's intentional in this case.  I'm wondering if there's maybe a different way to accomplish the same thing that doesn't require crossing different versions of the same dataset. The data that's in the earlier commits, is it still present in the more recent commit? Or does it get deleted? If it's still present then it seems like you can just cross the commit with itself (or maybe use a join to filter pieces you don't want) to get the data you need. And if it is getting deleted you might want to re-architect things so it doesn't get deleted.

This is definitely a more complicated use case so it might make sense to go over this in slack or a call so we can help you figure out how to get it working.

**Comment by ryansmith23** [comment]
Hey @jdoliner, I can message you on slack and we can setup a call after that if necessary. I will send the message later today. Anyone else you want me to include on it?

**Comment by adelelopez** [comment]
We were able to reproduce the issue, and determined that it's due to a subtle bug with job inputs. When a new job is started, and the provenance for it has multiple commits on the same branch and repo, it uses the last one it sees in the provenance slice. However, the ordering of the provenance slice is non-deterministic, so it essentially will randomly choose one of the commits it sees. Our intended fix is to do a topological sort on the slice before creating a new job, so that it always chooses the latest such commit.

**Comment by ryansmith23** [comment]
Thanks for looking into this @adelelopez. Joe has given us a solution that we will implement in the meantime.
