### ISSUE TITLE
Give user feedback that repo is deleted

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#519]
With response to issue #518 , when repo got deleted the second time, 

[root@chai /]# pachctl list-repo
NAME                CREATED             SIZE                
filter102           About an hour ago   0 B                 
test009             18 hours ago        0 B      
test008             18 hours ago        0 B      

[root@chai /]# pachctl delete-repo test 009
[root@chai /]# pachctl list-repo
NAME                CREATED             SIZE                
filter102           About an hour ago   0 B                 
test008             18 hours ago        0 B                 

Suggestion - Feedback can be given regarding deletion of the repo

**Comment by sjezewski** [comment]
For now we're relying on exit codes to denote success or failure.

If you do:

```shell
pachctl delete-repo something
echo $?
```
And the result is 0, that means it succeeded. If its non-zero that means it erred.
