### ISSUE TITLE
Make error descriptive when pachctl cannot connect to server

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#520]
pachctl version
COMPONENT           VERSION             
pachctl             1.0.0(dirty)        
pachd               UNKNOWN: Error rpc error: code = 4 desc = **context deadline exceeded**

Till now, pachctl,kubectl was working fine. Commits made, Pipeline created (although they didnt go to completion) 
Now, pachctl itself isnt working

kubectl get all
NAME                                     DESIRED         CURRENT            AGE
etcd                                     1               1                  18m
pachd                                    2               2                  18m
rethink                                  1               1                  18m

NAME                                     CLUSTER-IP      EXTERNAL-IP        PORT(S)                        AGE
etcd                                     10.51.251.61    <none>             2379/TCP,2380/TCP              18m
kubernetes                               10.51.240.1     <none>             443/TCP                        2d
pachd                                    10.51.241.191   nodes              650/TCP                        18m
rethink                                  10.51.245.78    nodes              8080/TCP,28015/TCP,29015/TCP   18m

NAME                                     READY           STATUS             RESTARTS                       AGE
134afc472521a77b3fbd249d26f2bf78-30rb7   0/1             ImagePullBackOff   0                             23h

8d6cb9bc6a70190a48b1d8cacca3fc0c-bul4w   1/1             Running            6                              2h

9f5b66319a6f2ecfd44c2558e1f7debf-9kcge   0/1             ImagePullBackOff   0                              22h

etcd-4b4mt                               0/1             Pending            0                              18m

f00ff025943ba8bec6434b0188266609-lkxf9   0/1             ImagePullBackOff   0                              22h

ff63dadd8dd333269b6e0a064ea05eca-l14ia   0/1             ErrImagePull       0                              23h

pachd-init-8xd40                         0/1             Pending            0                              18m
pachd-lm0n1                              0/1             Pending            0                              18m
pachd-use46                              0/1             Pending            0                              18m
rethink-72sqe                            0/1             Pending            0                              18m

With regards to issue #356 , where same error - Context deadline exceeded whenever manifest file upgraded - #510 (it happened 15 hrs back), 

We tried the commands mentioned in the test in Makefile (make launch kube,make clean launch, make launch , etc) in sequential fashion. Error while - make launch!

**Comment by sjezewski** [comment]
Hi there -

When you run `pachctl version` it reports the client version immediately, and requests the version information from the server. That error tells me that `pachctl` cannot connect to your `pachd` server. 

We should make that error message more descriptive / helpful to the user. We can provide a link / steps to try next if they're having trouble connecting to their server.

In your case, please try the following:

1) what is the output of `kubectl get all` ? Please report that here
  
2) If you see something like this:

```shell
$ kubectl get all
NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kubernetes             10.0.0.1     <none>        443/TCP    39d
NAME                   READY        STATUS        RESTARTS   AGE
k8s-etcd-127.0.0.1     1/1          Running       3          39d
k8s-master-127.0.0.1   4/4          Running       14         39d
k8s-proxy-127.0.0.1    1/1          Running       5          39d
```

That tells me that kubernetes is running, but pachyderm is not. In this case run `make launch`

3) If you see pachd from the output of `kubectl get all`, e.g. like this:

```shell
$ kubectl get all
NAME                   DESIRED      CURRENT       AGE
etcd                   1            1             42s
pachd                  2            2             32s
rethink                1            1             41s
NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)                        AGE
etcd                   10.0.0.124   <none>        2379/TCP,2380/TCP              42s
kubernetes             10.0.0.1     <none>        443/TCP                        39d
pachd                  10.0.0.47    nodes         650/TCP                        33s
rethink                10.0.0.224   nodes         8080/TCP,28015/TCP,29015/TCP   41s
NAME                   READY        STATUS        RESTARTS                       AGE
etcd-f5vkb             1/1          Running       0                              42s
k8s-etcd-127.0.0.1     1/1          Running       3                              39d
k8s-master-127.0.0.1   4/4          Running       14                             39d
k8s-proxy-127.0.0.1    1/1          Running       5                              39d
pachd-mnnvn            1/1          Running       0                              32s
pachd-p3oy6            1/1          Running       0                              32s
rethink-dmq0f          1/1          Running       0                              41s
```

Then I'm not sure why you cannot connect. In that case I'd try to do `make clean-launch` and `make launch`

**Comment by sjezewski** [comment]
I'm going to re-name this issue as a todo for us to make the error reported more descriptive / helpful.

**Comment by ChaiBapchya** [comment]
kubectl get all
NAME                                     CLUSTER-IP    EXTERNAL-IP        PORT(S)    AGE
kubernetes                               10.51.240.1   <none>             443/TCP    2d
NAME                                     READY         STATUS             RESTARTS   AGE
134afc472521a77b3fbd249d26f2bf78-30rb7   0/1           ImagePullBackOff   0          1d
25ae86f3d24d272b6da236d6d98b9f96-67v09   0/1           ImagePullBackOff   0          1d
2a8ea3dd00f533b8e85280ea4c3c3500-tzcps   0/1           ImagePullBackOff   0          1d
2b16ed115e0230b81c475ca584f57171-sg5ud   0/1           ImagePullBackOff   0          1d
427da1a27f3712994ac90816104a4a1e-egas4   0/1           ImagePullBackOff   0          1d
548c37ff6f691a919a757f4b4c0e97e8-odgtk   0/1           ImagePullBackOff   0          1d
8a0f6d5a4750656ef3da25294c41fbfe-7gz7c   0/1           ErrImagePull       0          1d
8d6cb9bc6a70190a48b1d8cacca3fc0c-bul4w   1/1           Running            6          8h
97d3b865088b1ff5c655fcdb9a678e5e-py0tt   0/1           ImagePullBackOff   0          12h
9a1f951f238ba4c6d73d4bd6dd8af8bb-d86m3   0/1           ImagePullBackOff   0          12h
9b7c13cee335de6e7b2b9952aaf0f609-x3x28   0/1           ImagePullBackOff   0          12h
9bd2c05d0682771588fd74b80e8df6a2-t7vef   0/1           ImagePullBackOff   0          1d
9f5b66319a6f2ecfd44c2558e1f7debf-9kcge   0/1           ImagePullBackOff   0          1d
b4ef5d9e246d4ea9b7b137a100e941e0-awje5   0/1           ImagePullBackOff   0          1d
c261c1e385e5c8b002967f0d6373c7f0-kles3   0/1           ImagePullBackOff   0          1d
d1a9325c202913e3790886046b882ccc-tdxmc   0/1           ImagePullBackOff   0          1d
e82a2a64287c5d05c99ed7656c5eb38d-xh4f1   0/1           ImagePullBackOff   0          1d
f00ff025943ba8bec6434b0188266609-lkxf9   0/1           ImagePullBackOff   0          1d
ff63dadd8dd333269b6e0a064ea05eca-l14ia   0/1           ImagePullBackOff   0          1d
[root@chai /]# make launch
make: *** No rule to make target 'launch'.  Stop.
[root@chai /]# cd pachy/src/github.com/pachyderm/pachyderm/
[root@chai pachyderm]# make launch
# check that kubectl is installed
which kubectl
/google-cloud-sdk/bin/kubectl
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
kubectl  create -f etc/kube/pachyderm.json
serviceaccount "pachyderm" created
replicationcontroller "etcd" created
service "etcd" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:32080,tcp:32081,tcp:32082) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "rethink" created
replicationcontroller "rethink" created
job "pachd-init" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30650) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
service "pachd" created
replicationcontroller "pachd" created
# wait for the pachyderm to come up
until timeout 1s ./etc/kube/check_pachd_ready.sh; do sleep 1; done
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
No pods found yet
^Z
[1]+  Stopped                 make launch

This has been the case for long time. Hence aborted. Any way forward? @sjezewski

**Comment by sjezewski** [comment]
Yup.

Before we get to that - when you paste log lines please wrap them in triple tick quotes ... like I edited your comment above. That makes the logs way more readable.

It'll take about 1-2minutes for the launch to succeed. So when you run `make launch` make sure that you let it go for at least that long.

Let's see if your cluster is working. To test, run:

```shell
pachctl list-repo
```

If that returns at all, that means the cluster is ready. If not (that shouldn't take a long time to complete the command), then lets find out what the state of the cluster is:

```shell
kubectl get all
```

I'm looking specifically for any errors reported. If we see a certain pod reporting errors we'll do something like:

```shell
kubectl logs pachd-33546
```

For the pod in question.

**Comment by ChaiBapchya** [comment]
```
 pachctl list-repo
^Z
[2]+  Stopped                 pachctl list-repo
[root@chai pachyderm]# kubectl get all
NAME                                     DESIRED         CURRENT            AGE
etcd                                     1               1                  5m
pachd                                    2               2                  5m
rethink                                  1               1                  5m
NAME                                     CLUSTER-IP      EXTERNAL-IP        PORT(S)                        AGE
etcd                                     10.51.241.78    <none>             2379/TCP,2380/TCP              5m
kubernetes                               10.51.240.1     <none>             443/TCP                        2d
pachd                                    10.51.252.52    nodes              650/TCP                        5m
rethink                                  10.51.246.122   nodes              8080/TCP,28015/TCP,29015/TCP   5m
NAME                                     READY           STATUS             RESTARTS                       AGE
134afc472521a77b3fbd249d26f2bf78-30rb7   0/1             ImagePullBackOff   0                              1d
25ae86f3d24d272b6da236d6d98b9f96-67v09   0/1             ImagePullBackOff   0                              1d
2a8ea3dd00f533b8e85280ea4c3c3500-tzcps   0/1             ImagePullBackOff   0                              1d
2b16ed115e0230b81c475ca584f57171-sg5ud   0/1             ImagePullBackOff   0                              1d
427da1a27f3712994ac90816104a4a1e-egas4   0/1             ImagePullBackOff   0                              1d
548c37ff6f691a919a757f4b4c0e97e8-odgtk   0/1             ImagePullBackOff   0                              1d
8a0f6d5a4750656ef3da25294c41fbfe-7gz7c   0/1             ImagePullBackOff   0                              1d
8d6cb9bc6a70190a48b1d8cacca3fc0c-bul4w   1/1             Running            6                              9h
97d3b865088b1ff5c655fcdb9a678e5e-py0tt   0/1             ImagePullBackOff   0                              13h
9a1f951f238ba4c6d73d4bd6dd8af8bb-d86m3   0/1             ImagePullBackOff   0                              13h
9b7c13cee335de6e7b2b9952aaf0f609-x3x28   0/1             ImagePullBackOff   0                              13h
9bd2c05d0682771588fd74b80e8df6a2-t7vef   0/1             ImagePullBackOff   0                              1d
9f5b66319a6f2ecfd44c2558e1f7debf-9kcge   0/1             ImagePullBackOff   0                              1d
b4ef5d9e246d4ea9b7b137a100e941e0-awje5   0/1             ImagePullBackOff   0                              1d
c261c1e385e5c8b002967f0d6373c7f0-kles3   0/1             ImagePullBackOff   0                              1d
d1a9325c202913e3790886046b882ccc-tdxmc   0/1             ImagePullBackOff   0                              1d
e82a2a64287c5d05c99ed7656c5eb38d-xh4f1   0/1             ImagePullBackOff   0                              1d
etcd-5c6ua                               0/1             Pending            0                              5m
f00ff025943ba8bec6434b0188266609-lkxf9   0/1             ImagePullBackOff   0                              1d
ff63dadd8dd333269b6e0a064ea05eca-l14ia   0/1             ImagePullBackOff   0                              1d
pachd-29px6                              0/1             Pending            0                              5m
pachd-init-0037i                         0/1             Pending            0                              5m
pachd-smta1                              0/1             Pending            0                              5m
rethink-njbke                            0/1             Pending            0                              5m


```

3 states exist for the pods - Running, Pending, ImagePullBackOff
Could we get further infomation on what actually happens, once the cluster is spinned - what functions called, which pods used, what purpose do they serve, and the meaning of the states, for better clarity (after we get rid of this error ofcourse)

**Comment by jdoliner** [comment]
This is what a healthy cluster should look like:

```
NAME                   DESIRED      CURRENT       AGE
etcd                   1            1             3h
pachd                  2            2             3h
rethink                1            1             3h
NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)                        AGE
etcd                   10.0.0.85    <none>        2379/TCP,2380/TCP              3h
kubernetes             10.0.0.1     <none>        443/TCP                        52d
pachd                  10.0.0.57    nodes         650/TCP                        3h
rethink                10.0.0.26    nodes         8080/TCP,28015/TCP,29015/TCP   3h
NAME                   READY        STATUS        RESTARTS                       AGE
etcd-g8g4v             1/1          Running       0                              3h
k8s-etcd-127.0.0.1     1/1          Running       0                              52d
k8s-master-127.0.0.1   4/4          Running       0                              41d
k8s-proxy-127.0.0.1    1/1          Running       0                              41d
pachd-2w1gl            1/1          Running       0                              3h
pachd-r90mo            1/1          Running       1                              3h
rethink-9zsh0          1/1          Running       0                              3h
```

Those pod states meanings are:
Pending: kubernetes is still scheduling the pod
Running: alls well the pod is running
ImagePullBackOff: the image failed to pull and is waiting to retry. Most likely this means you made a typo in the pipeline

**Comment by jdoliner** [comment]
For this issue I think the only actionable part is catching the error messages that arise when trying to connect and making them more friendly. I think that's definitely worth doing.

**Comment by ChaiBapchya** [comment]
The fact that the expected status doesn't match with the current status indicates a problem which is not resolved,  isnt it?...
Since my output even after 8 hours is 

```
kubectl get all
NAME                                     DESIRED         CURRENT            AGE
etcd                                     1               1                  8h
pachd                                    2               2                  8h
rethink                                  1               1                  8h
NAME                                     CLUSTER-IP      EXTERNAL-IP        PORT(S)                        AGE
etcd                                     10.51.241.78    <none>             2379/TCP,2380/TCP              8h
kubernetes                               10.51.240.1     <none>             443/TCP                        2d
pachd                                    10.51.252.52    nodes              650/TCP                        8h
rethink                                  10.51.246.122   nodes              8080/TCP,28015/TCP,29015/TCP   8h
NAME                                     READY           STATUS             RESTARTS                       AGE
134afc472521a77b3fbd249d26f2bf78-30rb7   0/1             ImagePullBackOff   0                              1d
25ae86f3d24d272b6da236d6d98b9f96-67v09   0/1             ImagePullBackOff   0                              1d
2a8ea3dd00f533b8e85280ea4c3c3500-tzcps   0/1             ImagePullBackOff   0                              1d
2b16ed115e0230b81c475ca584f57171-sg5ud   0/1             ImagePullBackOff   0                              1d
427da1a27f3712994ac90816104a4a1e-egas4   0/1             ImagePullBackOff   0                              1d
548c37ff6f691a919a757f4b4c0e97e8-odgtk   0/1             ErrImagePull       0                              1d
8a0f6d5a4750656ef3da25294c41fbfe-7gz7c   0/1             ImagePullBackOff   0                              1d
8d6cb9bc6a70190a48b1d8cacca3fc0c-bul4w   1/1             Running            6                              18h
97d3b865088b1ff5c655fcdb9a678e5e-py0tt   0/1             ImagePullBackOff   0                              22h
9a1f951f238ba4c6d73d4bd6dd8af8bb-d86m3   0/1             ImagePullBackOff   0                              22h
9b7c13cee335de6e7b2b9952aaf0f609-x3x28   0/1             ImagePullBackOff   0                              22h
9bd2c05d0682771588fd74b80e8df6a2-t7vef   0/1             ImagePullBackOff   0                              1d
9f5b66319a6f2ecfd44c2558e1f7debf-9kcge   0/1             ImagePullBackOff   0                              1d
b4ef5d9e246d4ea9b7b137a100e941e0-awje5   0/1             ErrImagePull       0                              1d
c261c1e385e5c8b002967f0d6373c7f0-kles3   0/1             ImagePullBackOff   0                              1d
d1a9325c202913e3790886046b882ccc-tdxmc   0/1             ImagePullBackOff   0                              1d
e82a2a64287c5d05c99ed7656c5eb38d-xh4f1   0/1             ImagePullBackOff   0                              1d
etcd-5c6ua                               0/1             Pending            0                              8h
f00ff025943ba8bec6434b0188266609-lkxf9   0/1             ImagePullBackOff   0                              1d
ff63dadd8dd333269b6e0a064ea05eca-l14ia   0/1             ImagePullBackOff   0                              1d
pachd-29px6                              0/1             Pending            0                              8h
pachd-init-0037i                         0/1             Pending            0                              8h
pachd-smta1                              0/1             Pending            0                              8h
rethink-njbke                            0/1             Pending            0                              8h

```

**Comment by ChaiBapchya** [comment]
Awaiting assistance since we have hit the wall. @sjezewski

**Comment by sjezewski** [comment]
What is the output of:

```
kubectl logs pachd-smta1
```

**Comment by sjezewski** [comment]
Actually ... lets move your debugging into a separate issue ... #540

This issue is only to improve the error message logging.

To that end, #147 is related.

**Comment by sjezewski** [comment]
fix is merged

**Comment by PachydermSupport** [comment]
<div>Agent Jan Schwoebel linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/233">233</a> for this issue.</div>
