### ISSUE TITLE
Change PacHub --> PachHub or Pachyderm Hub throughout docs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#5208]
**Provide a link to the page with an issue:**

**Describe what is wrong:**

**Describe the suggested changes:**

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by tantanchen** [comment]
I can work on this. Which versions? 1.10, 1.11, and master?
There are also files and folders with PacHub in their names, do you also want those renamed?

**Comment by JoeyZwicker** [comment]
Thanks @tantanchen! I think it only needs to be updated in 1.11.x and master.

**Comment by JoeyZwicker** [comment]
And yes, we should update all paths and folders, etc.
