### ISSUE TITLE
Support for opening a file in append mode

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#521]
Right now we don't support opening a file (in create|append mode) and writing to it. This is a common enough access pattern that we should support it.
 
Made a failing test case for this on the `open_file_writes` branch.

**Comment by jdoliner** [comment]
If you're not actively working on the branch I'd say submit it for code review with a `Skip()` in the test so we can merge it in and not break CI. That way it won't accrue conflicts and if someone wants to pick this up later they can just delete the `Skip()` and have a failing test case to work with.

**Comment by sjezewski** [comment]
Cool, will do
