### ISSUE TITLE
Concept of Lifecycle of Pipelines in Pachyderm Pipelining System

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#523]
With reference to issues #517 , #518 , #522 , #492 ,
In addition to this, why don't we introduce another state apart from
Starting, Running, Idle, Finished for error conditions

Basically, why don't we establish states such that users can trace the entire life-cycle and ascertain information about the pipeline.
Basic flow of states - 
Initial - Creation - Idle - Running - Terminated (Successful) or Aborted (Failure)

Besides, to find out the cause of Failure, states would act as a preliminary stage.

Thus, Pipeline Lifecycle should be introduced in Documentation, code for better understanding of Pipelines.

**Comment by derekchiang** [comment]
We definitely need more documentation for pipeline states.  We also currently have a mechanism for inspecting pipeline failures (`pachctl inspect-pipeline`), although that needs to be documented as well.

**Comment by jdoliner** [comment]
Definitely agree on documenting these more. I'm not sure if I understand what the additional state would correspond to though. Pipelines can't terminate successfully because the point of the pipeline is that it keeps running indefinitely waiting for new inputs to come in.

I think we already have states for all the other ones proposed don't we?

**Comment by ChaiBapchya** [comment]
Yes, we do. However, in order to show that the currently running pipeline completed its work - We can add a state that associates itself with the same. So ya, Terminated is wrong in this context. Maybe, completed successfully(awaiting next input), would be right way to put it.

**Comment by jdoliner** [comment]
Ah, I see that does make some sense as a feature. I'm currently adding a feature where when you do `inspect-pipeline` you'll see a count of job states from the pipeline, i.e. how many jobs are running, completed and failed. I think this gives you the info you want and then some, if a pipeline has 0 running jobs then it can be considered up to date. This also gives you an idea of how far from up-to-date a pipeline is.

**Comment by jdoliner** [comment]
Job counts are now in master.  Closing.
