### ISSUE TITLE
transform.* subfields aren't being indexed by docs search

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#5248]
**Provide a link to the page with an issue:**
I was trying to search for the `accept return codes` and here is what search shows:
<img width="790" alt="Screen Shot 2020-09-03 at 9 43 12 AM" src="https://user-images.githubusercontent.com/1795008/92143333-fe5df000-edc9-11ea-8af0-317a3e27449e.png">
<img width="746" alt="Screen Shot 2020-09-03 at 9 43 20 AM" src="https://user-images.githubusercontent.com/1795008/92143343-01f17700-edca-11ea-8081-e317c29fd615.png">
<img width="799" alt="Screen Shot 2020-09-03 at 9 43 29 AM" src="https://user-images.githubusercontent.com/1795008/92143344-028a0d80-edca-11ea-8128-c697e5f2415c.png">

Pipeline spec transform does eventually show up in the last screenshot but it's not informative.

**Describe what is wrong:**

Make things in the pipeline spec more searchable.

**Describe the suggested changes:**

I think the search functionality can only index on anchor links perhaps? So we might want to just reformat the transform.* fields (there are a lot) to be their own subheaders of some kind so that they become searchable. Will need to understand the search functionality better to know if this will work. 

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by nadegepepin** [comment]
Closing this - This was solved when we integrated DocSearch (See PR #5733): `Doc - Algolia docsearch #5733`
The Pipeline Specification page is now boosted (i.e.: the search prioritize search results on that page)
