### ISSUE TITLE
pachyderm pipeline created via python-pachyderm SDK fails at merge

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#5281]
**What happened?**:

Creating the python-pachyderm example available here: https://github.com/pachyderm/python-pachyderm/blob/master/examples/jupyter/investigate-unexpected-sales.ipynb 

At In [4], (file = client.get_file(("jupyter", "master"), "data.csv")) 

getting the data fails because the pipeline has failed with the following error in the logs

"pipelineName":"jupyter","jobId":"df654e69d60447aca2f64fdf3714a8ad","workerId":"pipeline-jupyter-v1-2qmh2","datumId":"22f68b99ed6de9857af95c2ac85d12a4737f0a967a3e8650fbc9ee98ff4576c5","data":[{"path":"/","hash":"Po1818fgVaZjcJkuVF7yY8pFbk+gUf6L4N7MHm3Tax4="},{"path":"/","hash":"RmolT8Tq+X8uH5uOWJUdR4thkwBEg/cIh0ILY8zh39k="}],"ts":"2020-09-14T22:45:02.733091815Z","message":"failed to process datum with error: exit status 1\ngithub.com/pachyderm/pachyderm/src/client/pkg/errors.EnsureStack\n\t/app/src/client/pkg/errors/errors.go:50\ngithub.com/pachyderm/pachyderm/src/server/worker/driver.(*driver).RunUserCode\n\t/app/src/server/worker/driver/driver.go:782\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.processDatum.func2.1.1.1\n\t/app/src/server/worker/pipeline/transform/worker.go:449\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.(*Status).withDatum\n\t/app/src/server/worker/pipeline/transform/status.go:89\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.processDatum.func2.1.1\n\t/app/src/server/worker/pipeline/transform/worker.go:447\ngithub.com/pachyderm/pachyderm/src/server/worker/driver.(*driver).WithActiveData\n\t/app/src/server/worker/driver/driver_unix.go:51\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.processDatum.func2.1\n\t/app/src/server/worker/pipeline/transform/worker.go:441\ngithub.com/pachyderm/pachyderm/src/server/worker/driver.(*driver).WithData\n\t/app/src/server/worker/driver/driver.go:502\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.processDatum.func2\n\t/app/src/server/worker/pipeline/transform/worker.go:438\ngithub.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify\n\t/app/src/server/pkg/backoff/retry.go:38\ngithub.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryUntilCancel\n\t/app/src/server/pkg/backoff/retry.go:59\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.processDatum\n\t/app/src/server/worker/pipeline/transform/worker.go:434\ngithub.com/pachyderm/pachyderm/src/server/worker/pipeline/transform.handleDatumTask.func1.1.1.1.1\n\t/app/src/server/worker/pipeline/transform/worker.go:297\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}

**What you expected to happen?**:

The pipeline should have been able to run.  I'm putting this bug in the pachyderm repo because the logs seem to show an issue with pachyderm vs. python-pachyderm

**How to reproduce it (as minimally and precisely as possible)?**:

See the steps above, but you may need to be running in an OpenShift cluster with resource policies.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):

ersion
OpenShift Master:
v3.11.200
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
3.11.200-1-8a53b1d

- Pachyderm CLI and pachd server version (use `pachctl version`):

1.11.3
python-pachyderm 6.0.0

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

On-premises, minio backing store

- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(created from <a href='https://pachyderm.zendesk.com/agent/tickets/112'>Zendesk ticket #112</a>)<br>gz#112</i>

**Comment by JoeyZwicker** [comment]
Based on live conversation, we think this is the user code erroring `exit status 1`, but are workign with user further.

**Comment by echohack** [comment]
This appears to be an old user issue. I'm closing this issue. If this issue appears again, please open an issue over at the [python-pachyderm](https://github.com/pachyderm/python-pachyderm) repo. Thank you!
