### ISSUE TITLE
Improve docs to list valid LOG_LEVEL variables

### ISSUE THREAD

**Issue by mindthevirt** [pachyderm/pachyderm#5289]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/deploy-manage/deploy/environment-variables/#pachd-environment-variables

**Describe what is wrong:**
N/A

**Describe the suggested changes:**
List all valid LOG_LEVEL variables to the description. Valid levels can be found here: https://github.com/pachyderm/pachyderm/blob/master/src/server/cmd/pachd/main.go#L293

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by jabhishek87** [comment]
Is this still open can i take this ?

**Comment by JoeyZwicker** [comment]
@jabhishek87 That would be great! It is still open. Let us know if you need our help putting together a PR.

**Comment by jabhishek87** [comment]
can you assign it to me, would like to work.

**Comment by JoeyZwicker** [comment]
The link to the docs page that needs updating is in this issue above. There is a row for log_level that should include the full list of valid values.
