### ISSUE TITLE
Supporting seeks in FUSE

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#529]
Currently files in FUSE are non-seekable.  This is fine for most big-data workload (where you read and write from the beginning of the file), but sometimes a program might want to read from a certain offset, or a writer might seek to offset 0 before it starts writing (which seems to be what [NodeJS](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) does).

**Comment by sjezewski** [comment]
Related to #333

**Comment by sjezewski** [comment]
This hasn't come up in quite a while. Now that we no longer user FUSE in the distributed processing step, I doubt user's will really want this short term.

Closing. If we see requests for this, we'll re-open.
