### ISSUE TITLE
Pachctl context deadline exceeded using hyper kit with Minikube 

### ISSUE THREAD

**Issue by lavoieunh** [pachyderm/pachyderm#5325]
**What happened?**:
  When following the pachyderm tutorial using hyper kit as the driver in Minikube, I was not able to complete the tutorial. A couple of errors were thrown and are noted below

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:
Run Minikube with hyper kit as driver `Minikube start --driver=hyperkit`
Follow deployment guide https://docs.pachyderm.com/latest/getting_started/local_installation/#deploy-pachyderm 

When trying to run `pachctl version`, a context deadline is exceeded when using hyper kit as the driver

When running `pachctl port-forward`, it indicates that port forward is already in use 

**Environment?**:

- Kubernetes version (use `kubectl version`):

```Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}```

```Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}```

- Pachyderm CLI and pachd server version (use `pachctl version`):
  ```#COMPONENT           VERSION             
  pachctl             1.11.4              
  pachd               1.11.4```

**Comment by JoeyZwicker** [comment]
@mindthevirt this should be a pretty quick repro

**Comment by lavoieunh** [comment]
We can close this. This was due to error in my hyper kit install using hyper kit this was https://github.com/moby/hyperkit.

Using hyper kit included with Docker Desktop operated as expected

**Comment by dgeorg42** [comment]
@lavoieunh - Glad you were able to resolve the issue. I was looking into it last night, and the only way I could find to reproduce the problem was if pachd wasn't running, or if pachctl wasn't configured with the correct address to talk to pachd. Thank you for adding the detail about the install method you used for Hyperkit; even though you've closed this case, I'll see if I can reproduce the issue using that install method.
