### ISSUE TITLE
Runtime error handling, Pipeline in other scripting languages, Pipeline execution explanation

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#536]
@jdoliner @sambooo @sjezewski @JoeyZwicker @dwhitena Thanks for all your support to help us to deploy and get pachyderm up and running on GCS systems. Yes there are some ongoing issues which we are posting here as and when we encounter them. Compiled form of these questions that we would like to put forward ->

1->  What is the procedure for handling errors during run-time in pachyderm ? (Just like issue #520 , which we can't go ahead with)
2->  Apart from JSON , can other languages like python etc be used to deploy pipelines . If yes, what should be the minimum requirements and the predefined structure in the file if any .
3-> Is there any documentation which shows the working of the pipeline ( except the one given in fruit stand example ) . What happens on command createpipeline , how is it executed .. What is the flow of control and subsequent method call? More light on this, would help us debug the errors.

**Comment by sjezewski** [comment]
1) Issue #520 is related to starting up the cluster, not runtime errors

I think you're asking about logging. We leave it to the users to run with k8s tools to do their logging. How you report errors is up to your application logic.

If you're asking how to see logs per pod, do `kubectl logs thenameofthepod`

2) We just support JSON

3) I'm not sure what you're asking. Can you be specific about what you're trying to do?

If you're still blocked on #520, then creating a pipeline definitely won't work. I think you need to make sure that `pachctl list-repo` returns successfully. That shows us that the cluster is working. It's not fruitful to try the create-pipeline methods until your cluster is working.

**Comment by ChaiBapchya** [comment]
Doubt2 - Well, Pachyderm allows users to not be constrained by any specific language/script. Giving users flexibility to create pipelines, leverage the power of different scrips/languages for Warehousing or Designing the Analytics. Hence, the doubt. Hope we are able to use Python scripts for scraping somehow in the near future.

Yes. Doubt 3 was in our minds since some time. Even when our cluster was up and running and we faced issue with getting the output from the pipeline - that's when we wanted to know
1. How CreatePipeline command works after invocation
2. Control flow and underlying working that goes on, during the Execution of the command

Yes, we haven't got a direction as to how to circumvent the issue #520 . So awaiting assistance.

**Comment by derekchiang** [comment]
@ChaiBapchya You can absolute use Python scripts in your pipeline.  There are two ways to do it:

1. Set `cmd` to `python` and have `stdin` be your python script.  This approach is ideal for very short python scripts where you don't mind putting them into the pipeline spec.

2. Use your own Docker image.  Basically it comes down to three steps:

    1. Build your own Docker image which contains your python script.
    2. Set the `image` field to your own Docker image.
    3. Set `cmd` to your python script.

**Comment by ChaiBapchya** [comment]
@derekchiang Our pachctl itself isnt working.since 3 days now
```
 pachctl version
COMPONENT           VERSION             
pachctl             1.0.0(dirty)        
pachd               UNKNOWN: Error rpc error: code = 4 desc = context deadline exceeded
```
Repeatedly stating this since many days. So despite having multiple ideas and keen on implementing them using pachyderm, we are held up by this impediment. Helplessly..Awaiting assistance...

**Comment by derekchiang** [comment]
@ChaiBapchya yeah we definitely need to work on our documentation.  Wanna move the conversation to Slack so we can troubleshoot your cluster?

**Comment by ChaiBapchya** [comment]
Yes, definitely. Add me - chai.bapat@gmail.com
Always keen on **learning**,  **helping**, **promoting** and improving technology and such path-breaking features...

**Comment by ChaiBapchya** [comment]
Awaiting the addition to slack channel! @derekchiang

**Comment by derekchiang** [comment]
@ChaiBapchya hi sorry for the delay.  We are experiencing some technical issues with Slack so let's just do it here.  You probably just want to re-launch your cluster altogether.  This usually do the trick:

`make clean-launch && make full-clean-launch && make launch`

**Comment by bedekarsarvesh** [comment]
@derekchiang We had to restart a new cluster all together. Could you please elaborate on how to use python scripts in pipeline? Like we set cmd to "python" .. how to write python script in the stdin value . Any help appreciated ..

**Comment by jdoliner** [comment]
@ChaiBapchya the problem here is that you're passing `a.py` as stdin to the script rather than as an argument. Your pipeline should look like this:

```
{
  "pipeline": {
    "name": "scrape7"
  },
  "transform": {
    "image": "acf2a3ec273a",
    "cmd": [ "python", "a.py"]
  },
  "parallelism": "1",
  "inputs": [
    {
      "repo": {
        "name": "abode2"
      }
    }
  ]
}
```

**Comment by jdoliner** [comment]
Closing this for staleness and because it doesn't seem like this will lead to changes to code. Feel free to keep asking questions here, we're happy to support you in this thread.
