### ISSUE TITLE
Unusual Test Flake in TestExtractPipeline

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5372]
TestExtractPipeline is failing with an error implicating an invalid pipeline spec. As far as I know, the pipeline specs we use in tests are in every way deterministic, so I don't see how this error could happen:
```
--- FAIL: TestExtractPipeline (0.02s)
    pachyderm_test.go:11768: No error is expected but got rpc error: code = Unknown desc = s3 output is not supported in spouts or services
    pachyderm_test.go:11768: current stack:
        goroutine 2262 [running]:
        runtime/debug.Stack(0x299fb60, 0xc0018b67d0, 0xc00062b998)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2a3f160, 0xc00189a800, 0x0, 0x0, 0x0, 0x25b33e9, 0x1f, 0xc00132b490, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xd9
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2a3f160, 0xc00189a800, 0x299fb60, 0xc0018b67d0, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xef
        github.com/pachyderm/pachyderm/src/server.TestExtractPipeline(0xc00189a800)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:11768 +0x66d
        testing.tRunner(0xc00189a800, 0x2664a18)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350
```

Full Travis logs:
[travis_output.log](https://github.com/pachyderm/pachyderm/files/5423622/travis_output.log)

**Comment by jdoliner** [comment]
`TestExtractPipeline` actually generates a random pipeline spec using `gofakeit` so this failure is consistent with that. It uses `gofakeit` so we have a way to catch when someone adds a field and forgets to add it to extract. We might want to add a message to the check on line 11768 that says explicitly that this test generates a random pipeline spec so if your pr added a new way that pipelines can fail to validate this is likely a real failure.

**Comment by msteffen** [comment]
There's a fix for this pending in https://github.com/pachyderm/pachyderm/pull/5387

**Comment by msteffen** [comment]
Fix has been merged, marking this fixed
