### ISSUE TITLE
Debugging make launch

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#540]
Originated in #520 

What is the output of:
```
kubectl logs pachd-smta1
```

**Comment by ChaiBapchya** [comment]
```
kubectl logs pachd-smta1
**No output**
```

**Comment by sjezewski** [comment]
Ok how about:

`kubectl logs pachd-smta1 --previous` 

And I'd also like to see `kubectl get all` again to make sure we're still seeing an error of some kind w that pod

**Comment by jdoliner** [comment]
Closing for staleness. Please reopen if there's new information.
