### ISSUE TITLE
Unable to authenticate, can't connect Github account to Pachyderm Hub

### ISSUE THREAD

**Issue by osman144** [pachyderm/pachyderm#5403]
**What happened?**:

Unable to authenticate, can't connect Github account to Pachyderm 

Message: 

<img width="547" alt="Screen Shot 2020-10-30 at 9 27 01 PM" src="https://user-images.githubusercontent.com/25594064/97769187-bd970480-1af6-11eb-8e26-2128aa92a3de.png">

**What you expected to happen?**:

Should be able to login and authenticate. Connect github account to Pachyderm Hub.

**How to reproduce it (as minimally and precisely as possible)?**:

Connect a github account to Pachyderm hub

**Anything else we need to know?**:

My Github account settings shows Pachyderm Hub is authorized in `Authorized OAuth Apps`.

<img width="920" alt="Screen Shot 2020-10-30 at 9 28 55 PM" src="https://user-images.githubusercontent.com/25594064/97769230-16669d00-1af7-11eb-8ce2-2b8c2d8dd0a5.png">

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jmcriffey** [comment]
Hey! Thanks for trying out PachHub! Sorry you're having trouble with authentication. There are a few things we can double check and try to get this sorted out. 

1. This could have been a blip. Can you try again and see if you get the same result?
1. We require a verified email from GitHub. Is an email tied to your account verified?
1. If nothing else, I'd try revoking access in GitHub and trying the process again. 

If none of those steps above work out, please let us know and we van dig deeper into what is going on here. Thanks!

**Comment by osman144** [comment]
Hey Jeff, thanks for the quick response. 

Just some more info, I initially did `Login with Google` after clicking the "Try Pachyderm Hub" button and was able to sign up just fine with my Gmail account.  

The issue seemed to occur when trying to connect with Github. It hit a snag due to the same email address being used. My Github account uses the same email as my gmail. There may be something going on in the backend where the system tries to setup the account and it notices there's already an existing email on file as I had initially signed up with the Gmail account before attempting to login with Github. 

Unsure if thats the case. If it is, is there a way to completely delete an account from Pachyderm hub. I'd like to connect the service to my Github instead of using my Google account. Thanks

**Comment by jmcriffey** [comment]
Ah, yeah signing in with gmail first with the same email is definitely a known issue. I'll reach out to our backend folks and see what we can do to set your account straight.

**Comment by chainlink** [comment]
👋 hub backend team here. We haven't implemented social login merge just yet because of security. In the meantime do you mind logging in using Google? Functionally they are the same as we don't have any GH specific integrations built out yet. We've also added a ticket to our backlog to add better message around this, as that can definitely be more clear. 

Thanks for reporting!

**Comment by jmcriffey** [comment]
We have this on our radar internally as a potential new feature, so I'm going to close this out. Please let us know if you have any other issues. Thanks!
