### ISSUE TITLE
More Error Cleanup

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#541]
We've seen a handful of issues for error message cleanup. Summarizing these here:

#520 - desc err when cannot connect to server
#147 - firewall error
#138 - repo name / pipeline conflicts / etc
#136 - fuse write error

**Comment by jdoliner** [comment]
Also we have some error strings that start with capitals which is against the go style guide so we should fix that as well.

**Comment by sjezewski** [comment]
Additionally ... going to update fuse to not report the `FileNotFound` errors to stdout ... those are confusing to users.
