### ISSUE TITLE
Troubleshooting / FAQ

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#543]
We have a FAQ/SETUP docs here on github, but we want to:

1) Expand the troubleshooting portions ... especially around deployment as thats where we see a lot of stumbling atm
2) Make sure wherever the deployment/troubleshooting docs live its in a place people can find and use

**Comment by sjezewski** [comment]
(going to start listing questions we've seen more than once here so we remember what to add to these docs)

We've fielded a few questions for `PullPolicy` settings for custom manifests. Lets ID the symptoms for when this is set wrong (e.g. when you have old features bcz the new default is `Always` when you're trying to use newly compiled versions so you should set it to `IfNotPresent`)

**Comment by JoeyZwicker** [comment]
We get questions about timeout errors during cluster deployment such as
pachd starting up before rethinkdb is ready. Would be good to document that
this is normal.

Same for fuse throwing benign errors

**Comment by sjezewski** [comment]
The fixes from the `error-cleanup` branch silence the fuse errors, so we don't have to document that one anymore ;-)
