### ISSUE TITLE
Detecting that jobs no longer exist

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#544]
Currently if you create a job and remove it via Kubernetes, it still shows up in `pachctl list-job`.

**Comment by ChaiBapchya** [comment]
Rename - **Detecting the jobs that no longer exist.**
Btw, do you remove the job using Kubernetes via below command?

```
kubectl delete <job-id>
```

**Comment by jdoliner** [comment]
This no longer applies.
