### ISSUE TITLE
Configure pachctl to run port-forward automaticly in the background

### ISSUE THREAD

**Issue by JesperLundChristensen** [pachyderm/pachyderm#5443]
**What is the goal / desired outcome?**
To avoid having to manully call pachctl port-forward. 

We were made aware of this from using JupyterHub, and all user has to:
1. Open Terminal
2. pachctl port-forward
Extra: If terminal dies, or JupyterHub stops the session while port-foward is running. We have to manually fix the config.json

**If there is a way to accomplish this today via workaround, what does that require?**
Setup pachctl port-forward manually for all users

**(Optional) What is your proposal for a feature to solve this?**
Not sure. But having an option in the configuration file to have port-forward running automaticly if set up correctly

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
pachctl             1.11.0
pachd               1.11.0

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Azure, AKS

- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
Hey @JesperLundChristensen , thank you for opening up this issue. Since you're running on Azure AKS, you could expose the endpoints for pachd, etc... via load balancers. This would allow your users to not have to run pachctl port-forward but instead just go straight to a URL for the dashboard or configure the context of pachctl to point to the loadbalancer.

The following documentation from Azure covers loadbalancers: https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard

I would recommend to try it on a test instance first. In our yaml files, all you should have to do is to change the service configs from NodePort to LoadBalancer and AKS will take care of the rest.

**Comment by jdoliner** [comment]
I'm not sure there's a good implementation of this. Pachyderm currently isn't running a service on your local machine, `pachctl` is just a binary that gets put in your PATH. To do something like this automatically there would have to be a service that we setup that gets started on boot. Presumably we'd do something using systemd, similar to what docker does, but I doubt we'd be able to make this bulletproof enough that you wouldn't have to manually restart it sometimes. And now you're mucking about with systemd which is going to make things a lot more complicated.

@mindthevirt's suggestion is probably your best bet for simplified ingress. It involves doing the work correctly once for the server but after that it should work for every user the same way.

We also have some built in support for JupyterHub that does the config for you, we'd be happy to give you a demo of it.

**Comment by JesperLundChristensen** [comment]
Thanks alot of some quick and helping comments. I will use @mindthevirt suggestion, which endpoints should I expose? 

At the end of this it will work if the user has the pachctl installed and configured for the correct context, without running port-forward?

**Comment by JesperLundChristensen** [comment]
@jdoliner I have a demo scheduled with @marylowebailey this afternoon, if possible please include the JupyterHub solution.

**Comment by mindthevirt** [comment]
@JesperLundChristensen you want to expose pachd and dash, assuming you want to use the dashboard. pachd will be needed for pachctl to control the cluster. You're correct that once you have pachd exposed via a load balancer, your context will point to it and port-forward won't be needed anymore.

**Comment by JesperLundChristensen** [comment]
@mindthevirt 
Where is the service config that should be changed from nodeport to LoadBalancer?

**Comment by mindthevirt** [comment]
When you deploy pachyderm with `pachctl deploy local/aws/...` you can add `--dry-run > pachyderm.yaml` which will then generate a yaml file. In the yaml file, you want to look for `"type":"NodePort"` and change it to `Loadbalancer`. At this point, you would also need to remove all other references to a nodePort. Btw, all these changes have to be made in the `services` definitions. Nothing has to be modified on the other components.
