### ISSUE TITLE
DNS failure causes pachd not to connect

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#5458]
**What happened?**:

A user attempted to connect via pachctl 1.11.7 and got a connect error because DNS had a strange "server misbehaving" failure looking up localhost.
Changing the DNS server from the router's default to 8.8.8.8 solved the issue.

This failure does not occur on pachctl 1.10.5.

**What you expected to happen?**:
Expected the connection to occur.

**How to reproduce it (as minimally and precisely as possible)?**:

Getting the brand of the router or dhcp server version and the configured DNS settings. Here's a log of what occurred:

```
olly> pachctl version -v

COMPONENT           VERSION

pachctl             1.11.7

[0000] DEBUG Implicit port forwarder listening on port 55528

[0000]  INFO parsed scheme: "dns" source=etcd/grpc

[0001]  INFO grpc: error from DNS TXT record lookup: lookup _grpc_config.localhost on 192.168.1.1:53: server misbehaving source=etcd/grpc

[0001]  INFO ccResolverWrapper: sending update to cc: {[{127.0.0.1:55528  <nil> 0 <nil>} {[::1]:55528  <nil> 0 <nil>}] 0xc000abe680 <nil>} source=etcd/grpc

could not connect to pachd at "grpc://localhost:55528": context deadline exceeded

github.com/pachyderm/pachyderm/src/client.NewOnUserMachine

                src/client/client.go:463

github.com/pachyderm/pachyderm/src/server/cmd/pachctl/cmd.PachctlCmd.func2

                src/server/cmd/pachctl/cmd/cmd.go:411

github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunFixedArgs.func1

                src/server/pkg/cmdutil/cobra.go:31

github.com/spf13/cobra.(*Command).execute

                /home/pach/go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191202130430-b04b5bfc50cb/command.go:833

github.com/spf13/cobra.(*Command).ExecuteC

                /home/pach/go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191202130430-b04b5bfc50cb/command.go:917

github.com/spf13/cobra.(*Command).Execute

                /home/pach/go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191202130430-b04b5bfc50cb/command.go:867

main.main.func1

                src/server/cmd/pachctl/main.go:20

main.main

                src/server/cmd/pachctl/main.go:21

runtime.main

                /usr/local/go/src/runtime/proc.go:203

runtime.goexit

                /usr/local/go/src/runtime/asm_amd64.s:1357


```

**Anything else we need to know?**:

Router is netgear orbi (RBR50), running firmware v2.3.5.30
It’s configured to use OpenDNS upstream (208.67.222.222 and 208.67.220.220)
  

**Environment?**: 
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):  
client: 1.11.7 (fails), 1.10.5 (succeeds)
cluster: 1.11.7
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
EKS
- OS (e.g. from /etc/os-release):
macOS Catalina 10.15.X
- Others:

**Comment by actgardner** [comment]
This is resolved in the 1.11.8 release and on master.
