### ISSUE TITLE
Remove old versions of streaming RPCs

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5485]
Currently we have both e.g. `ListJob` and `ListJobStream`. We have lots of comments in our code to remove the non-streaming implementations, which we should do when we release 2.0 and are allowed by SemVer to break our API. This issue tracks the API methods that should be removed:

- ListJob
- ListDatum
- ListPipeline and ListSecret currently only have non-streaming implementations, but they should probably be made streaming
- ListRepo only has a non-streaming implementation, but should be made streaming
- ListCommit
- ListBranch only has a non-streaming implementation, but should be made streaming
- ListFile
- GetClusterRoleBindings should maybe be made streaming
  - many other auth APIs should be removed, but because we don't want to support them rather than because of a streaming/non-streaming split, e.g. remove GetAdmins and ModifyAdmins in favor of ClusterRoleBinding APIs, the word "Scope" should be "Role" everywhere, SetACL/GetACL/SetScope/GetScope should be ListRoleBindings and SetRoleBinding or something RBAC-y like that, etc

**Comment by brycemcanally** [comment]
All of these have been addressed.
