### ISSUE TITLE
ListDatum blocks indefinitely after failed job

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5508]
A user's job failed due to a failed datum, and in trying to debug the issue, the user called `pachctl list datum` which blocked indefinitely. (A related ergonomic issue is that due to the presentation of the failure, it initially seemed like the failed datum had simply been dropped somehow, which the blocking `list datum` call seemed to corroborate. Specifically, `pachctl list job` in the `PROGRESS` column shows `3776+0/3777`, because the failed datum isn't included in the count)

One theory is that ListDatum takes different codepaths depending on whether the job is finished or not, and it's possible that the job being failed is causing problems in that logic

**Comment by msteffen** [comment]
Some other issues with ListDatum, pointed out by the same user:
1. In the job where `list datum` hangs, it turns out that `pachctl logs --raw --job <jobID> | jq .datum_id` also obtains a list of datums and is perfectly fast and usable. I think this means that the job in question has a stats commit, and `list datum` should essentially just be reading it.

2. Error seen by the user:
```
$ pachctl list job -p <pipeline> 
ID       PIPELINE    STARTED       DURATION    RESTART PROGRESS       DL UL       STATE
5148e... <pipeline>  22 hours ago  15 minutes  0       0 + 180 / 180  0B 0B       success
...
$ pachctl list datum 5148e1d83c514c43912aaa1c29cf5ffb
index 183 out of range
```

3. Another error seen by the user:
```
$ pachctl list job -p <pipeline> 
ID         PIPELINE     STARTED       DURATION    RESTART PROGRESS        DL UL       STATE
cf4063...  <pipeline>   43 hours ago  14 minutes  0       2474 + 0 / 2474 0B 532.9MiB success
$ pachctl list datum cf4063594c634d319e73878637350077
couldn't find job file
```

**Comment by msteffen** [comment]
Just talked to @PFedak about this issue a bit. Just a few notes from our conversation:
- Issue 1 above appears to be releated to the fact that ListDatum constructs a DatumIterator (which is very slow) even if there's a stats commit available, where it would be faster the get the list of datums from the stats commit. We tried to fix this in https://github.com/pachyderm/pachyderm/commit/9953c4fd84bb393d067db7919396edcda3fb2d6a, but the datum iterator is used in [1.12.x:pps/api_server.go:1269](https://github.com/pachyderm/pachyderm/blob/9ec7c0b9f582bbb38ddc1d6c9de42cf880657abc/src/server/pps/server/api_server.go#L1269) to get a datum from the DatumIterator. Maybe we can get that info from the stats commit if it's available, instead of constructing a DatumIterator? Maybe we just don't need to return that info at all in most cases and we should make it optional?
- Issues 2 and 3 above appear to be related to https://github.com/pachyderm/pachyderm/issues/5386.
  - For 2, "couldn't find job file" is emitted by getDatum (called by ListDatum) [if it finds a number of job files != 1](https://github.com/pachyderm/pachyderm/blob/9ec7c0b9f582bbb38ddc1d6c9de42cf880657abc/src/server/pps/server/api_server.go#L1360), which is why multiple job files trigger that error, and is likely what happened here, so the error should be clearer, and say if there are actually too many job files.
  - For 3, if a datum fails and then succeeds in an additive-only job, in addition to an extra job file being added to the parent's stats commit, the contents of the `<datum id>/index` file are appended to the parent's `.../index` file. This happens each time the datum is processed, so it's likely that `index 183 out of range` is because `.../index` contains like `77777`, where the datum has index `7` but was failed five times.

**Comment by PFedak** [comment]
Closing this issue as the hang is likely the same as #5835, which is now substantially improved, and I don't think the others make sense to fix in 1.x based on my investigation into what that would involve.
