### ISSUE TITLE
Test TestPipelineThatOverwritesFile hangs intermitently

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#551]
Seen this pop up a couple of times in CI. Haven't figured out how to reproduce it consistently yet.

**Comment by sjezewski** [comment]
If we see this running/passing on CI on `pfs-refactor` branch, we should close this

**Comment by sjezewski** [comment]
CI is passing on `pfs-refactor` branch, which runs it and it passes. So closing this until we have repro steps
