### ISSUE TITLE
Delete Kube jobs when we delete a Pipeline

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#552]
Currently we only delete the JobInfos in rethinkdb but not the jobs we submitted to kubernetes.
We need to delete the kubernetes jobs because we have a deterministic approach to job naming which means that if someone deletes and recreates a pipeline they'll see errors from kubernetes because the new pipeline can't create jobs due to name conflicts with the jobs created by the last version of the pipeline.

**Comment by derekchiang** [comment]
We do have the code right now which is supposed to do exactly this: https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/api_server.go#L868-L872

However I have run into instances where jobs failed to be removed.  I did not pinpoint the cause though.

**Comment by jdoliner** [comment]
One way I know of reproducing this is just restarting the cluster and recreating the pipeline.
Since currently pfs data survives restarts and pps doesn't that will leave you in a state where you get errors. Have you seen other ways of reproducing it or do you think it might have been that one?

**Comment by derekchiang** [comment]
Yeah I definitely remember deleting a pipeline, restarting the cluster, and some jobs were still there.  I'm not sure if that was 100% reproducible though.

**Comment by jdoliner** [comment]
This has been fixed now by a couple of different prs. Closing.
