### ISSUE TITLE
stop/start pipeline takes pipeline to intermediate states unnecessarily

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#5521]
**What happened?**:

Stopped a pipeline that was in standby, and it was put into `running` before it was stopped.
Started a pipeline that was in standby and it was put into `running` before going into standby. 

Worker pods were started in both cases, incurring unneccessary compute cost.

**What you expected to happen?**:

I expected a direct transition from standby->stopped or stopped->standby without any worker pods starting.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Create a pipeline in standby
2. Stop it.  Observe that it's momentarily put in running, with worker pods starting up before it stops.
3. Start it. Observe that it's momentarily put in running, with worker pods starting up before it goes into standby

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
1.11.8

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
docker desktop
- OS (e.g. from /etc/os-release):
macOS Catalina
- Others:
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/140'>Zendesk ticket #140</a>)<br>gz#140</i>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/235">235</a> for this issue.</div>
