### ISSUE TITLE
pachctl deploy --dry-run outputs invalid json

### ISSUE THREAD

**Issue by kasperbfrank** [pachyderm/pachyderm#5542]
**What happened?**:
pachctl deploy local --dry-run outputs invalid json.

Output snippet:
{
  "kind": "ServiceAccount",
  "apiVersion": "v1",
  "metadata": {
    "name": "pachyderm",
    "namespace": "default",
    "creationTimestamp": null,
    "labels": {
      "app": "",
      "suite": "pachyderm"
    }
  }
}
{
  "kind": "ServiceAccount",
  "apiVersion": "v1",
  "metadata": {
    "name": "pachyderm-worker",
    "namespace": "default",
    "creationTimestamp": null,
    "labels": {
      "app": "",
      "suite": "pachyderm"
    }
  }
}
{ ... }

**What you expected to happen?**:
Valid json

**How to reproduce it (as minimally and precisely as possible)?**:
pachctl deploy local --dry-run 

**Anything else we need to know?**:
Tested with both pachctl deploy local and pachctl deploy microsoft, and both output invalid json. Running with --output yaml outputs valid yaml though

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
pachctl             1.11.0              
pachd               1.11.0

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
@kasperbfrank thank you for opening up this issue. You're correct, it's not one valid JSON manifest at the moment. Instead, it is a file containing multiple valid JSONs, one per component, such as `ServiceAccount, ClusterRole, Service, Secret, Deployment, ...
`
Is this currently blocking you?

**Comment by kasperbfrank** [comment]
It's not blocking me, I needed to deploy a pachyderm cluster from a modified config, so I just used the yaml file format instead.

**Comment by kasperbfrank** [comment]
kubectl create -f <file>.json does not work, but kubectl create -f <file>.yaml does

**Comment by mindthevirt** [comment]
I don't think I can reproduce the issue:

> ➜  ~ pachctl deploy local --dry-run > github.json
➜  ~ kubectl create -f github.json
serviceaccount/pachyderm created
serviceaccount/pachyderm-worker created
clusterrole.rbac.authorization.k8s.io/pachyderm created
clusterrolebinding.rbac.authorization.k8s.io/pachyderm created
role.rbac.authorization.k8s.io/pachyderm-worker created
rolebinding.rbac.authorization.k8s.io/pachyderm-worker created
deployment.apps/etcd created
service/etcd created
service/pachd created
service/pachd-peer created
deployment.apps/pachd created
service/dash created
deployment.apps/dash created
secret/pachyderm-storage-secret created


>  kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

>  ~ pachctl version
COMPONENT           VERSION
pachctl             1.11.7

**Comment by nitinjainsj** [comment]
@kasperbfrank Can you give us an output of the errors? We have not been able to recreate this problem inhouse.

**Comment by nitinjainsj** [comment]
can't reproduce the issue. Please reopen with more info.
