### ISSUE TITLE
Pachyderm images are rate limited by docker hub

### ISSUE THREAD

**Issue by mindthevirt** [pachyderm/pachyderm#5553]
**What happened?**:
When parallelism is set high, downloading Pachyderm images from docker hub may be rate-limited due to https://www.docker.com/increase-rate-limits

The images should be moved to non-rate-limiting repo.

**What you expected to happen?**:
No rate limitation.

**Comment by nitinjainsj** [comment]
pachyderm is part of docker ISV. This should remove rate limits on pachyderm images.
