### ISSUE TITLE
Pachctl logs are unreliable

### ISSUE THREAD

**Issue by Tryneus** [pachyderm/pachyderm#5567]
When using `pachctl logs` with filters (such as `--pipeline`, `--job`, etc), it may appear that some log statements are missing.  This is because of how `pps.GetLogs` is written:

* Spawns a goroutine for each interesting pod, which:
  * Requests the last `request.Tail` log lines
  * Filters out any unparseable log lines
  * Applies any filters from the request
  * Pushes any passing log lines into a channel
* Forwards all log lines in the channel directly to the client

This results in a few problems:

* The `request.Tail` is applied before filtering, which means that we will only return the requested number of log lines if _all_ the found lines match the filters.
* Unparseable log lines (e.g. log lines that did not originate from our logging function) can push out interesting log lines.
* The `request.Tail` is applied on a per-pod basis, so we actually return up to `request.Tail` * `number of pods` log lines.
* While log lines within a given pod are ordered, we don't apply any merging of log lines between pods, so they will arrive in the client in non-chronological order (due to the batched nature of the kubernetes `GetLogs` request).
* If a worker crashed, we do not get logs from the previous instance.

Unfortunately, the kubernetes `GetLogs` options are not very helpful for providing the features we want (https://godoc.org/k8s.io/api/core/v1#PodLogOptions).  There is no way to paginate backwards through logs until we find the minimum requested number of log lines, and we would need to guess timestamps and stop using `TailLines`.  Since the only slicing we can do is by timestamp (rather than offset), it is hard to account for a situation where a large number of log lines are added in a very short period of time.
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/95'>Zendesk ticket #95</a>)<br>gz#95</i>

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/95'>Zendesk ticket #95</a>:<br><br>We've found what we think is the issue and I've linked it to this ticket.  We'll update you when a fix is available!

**Comment by nitinjainsj** [comment]
This should be fixed with #5629
