### ISSUE TITLE
Get empty files in map jobs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#557]
Currently, a map job (or specifically, a job whose partition strategy is "block") can see empty files if the files don't contain any blocks that the job is assigned with.  For instance, if you have 4 parallel jobs but there is a file that only contains 1 block, then this file will appear empty to 3 of the four jobs.

This is less than ideal since empty files are useless and the job most likely wants to loop over all files and by doing so it's wasting a lot of work on empty files.  Ideally, we'd not present empty files at all.

**Comment by jdoliner** [comment]
Hmm... it's possible this is because the fuse driver is doing unsafe reads.
