### ISSUE TITLE
Accumulate new features for docs

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#562]
W 1.1 we have some new features we need to document

- [the changelog](https://github.com/pachyderm/pachyderm/releases/tag/v1.0.1(1433)) should provide a start to the list
- the impetus for this issue was that we added those environment variables to the job environment, but if we don't document it, few people will know to use it

**Comment by sjezewski** [comment]
And API level details (we've fielded some questions about unsafe / handle params). This should be covered in API doc strings, but we should make those docs more prevalent.

**Comment by sjezewski** [comment]
via @JoeyZwicker -- we should up level the docs on how to make a new container that uses the job-shim container

**Comment by sjezewski** [comment]
the example image for that lives here: https://github.com/pachyderm/pachyderm/blob/master/etc/user-job/Dockerfile

**Comment by derekchiang** [comment]
The above example demonstrates how to make your custom image compatible with pachyderm.  Another way is to inherit from the `job-shim` image directly like this: https://github.com/pachyderm/pachyderm/blob/master/examples/fruit_stand/Dockerfile

**Comment by sjezewski** [comment]
Unfortunately, I think 'aggregate' issues for docs doesn't really work. I'll document the following specifics:

- new environment variables
- how to construct / use a new image using pachyderm
- json / bin delimiters

Beyond that ... we should just get into the habit of documenting in the moment. This will get easier once we have a place for docs!

**Comment by sjezewski** [comment]
Fix is merged
