### ISSUE TITLE
Pachyderm Architecture 

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#563]
![architecture-pachyderm](https://cloud.githubusercontent.com/assets/10992635/16208494/0c9780f8-3750-11e6-8df7-ed588cf665c9.png)

Having worked on Pachyderm for some time now, trying to get a hang of things. We went through the GitHub repository (not completely , but through most portions of  documentation), read the blogs, articles, issues. Having deployed Pachyderm locally, tried the examples and ran the pipelines (albeit with a few hiccups here and there, understandable given our lack of expertise and experience in this area) we tried coming up with this rough, birds-eye view on the Architecture revolving Pachyderm with regards to Local and Cloud deployment (Google Cloud storage from the Point of view of Server deployment) 

We understand that this diagram may be flawed, wrong, inappropriate and hence may need clarification, changes. Awaiting the same. Thanks..:)
@jdoliner @JoeyZwicker

**Comment by ChaiBapchya** [comment]
Local deployment -
We install Docker and Kubernetes. Git Clone the Pachyderm repo.
By docker pulling the image, we can set up Local cluster of Pachyderm.
Install Kubectl, Pachctl (allows to talk with the Cluster - Local / Server based on the ADDRESS environment variable set to the corresponding I.P. address)

Server side deployment - 
Using Kubernetes, we can spin up a Cluster of Google Cloud Virtual machine / instances. Docker is pre-installed with them.

Pachyderm File and Pipeline System (PPS,PFS) sits on top of the Google Cluster so as to allow access to Pachyderm from entire cluster.

Questions
How to access PFS from any instance (when we SSH into that instance - pfs cant be mount, pachctl doesnt work in order to mount pfs)
We created a new Docker image (with a Python script we want to input to our pipeline). When we setup a container from this Docker image, it can't access the File system of the Instance on which it is running. Do we need to mount the PFS again into the Docker container, to be able to access the repos and files within the PFS?
@jdoliner @JoeyZwicker @derekchiang @sambooo

**Comment by jdoliner** [comment]
`pachctl` should be able to access `pfs` from any container that is scheduled by Kubernetes. Accessing from an arbitrary Docker container is harder because Docker blocks access to things on the outside machine. I'd recommend scheduling with Kubernetes.

Closing for staleness and because it seems unlikely this will lead to code changes. Feel free to keep asking questions on this thread though.
