### ISSUE TITLE
Use branch name instead of commit ID in mounted PFS

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#565]
Currently if you use `pachctl mount /pfs` to mount pfs, and then create a branch by doing something like `pachctl create-commit repo master`, the directory that you see under `/pfs/repo` has the commit ID as the name.  Ideally, the directory should just be named "master".

**Comment by jdoliner** [comment]
I'd expect to see the branch name in addition to commit ID not in place of it. So you could get the same result from `/pfs/repo/commitID` and `/pfs/repo/master` until a new commit is created on `master` at which point `/pfs/repo/master` will advance and the commitID will become the only way to access it.

**Comment by jdoliner** [comment]
This is present in master now, closing.
