### ISSUE TITLE
s3g: prefix=/ does not list all objects in bucket

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/pachyderm#5655]
Listing the objects in a bucket in s3g works fine when you don't specify a prefix:

![Screenshot from 2021-01-29 16-19-21](https://user-images.githubusercontent.com/264658/106301446-a2e83f00-624f-11eb-8bb2-e254ab05f7d0.png)

But specifying a prefix of `/` (`%2F` urlencoded), which presumably means "root" to regular S3 & friends, errantly returns an empty bucket listing:

![Screenshot from 2021-01-29 16-21-19](https://user-images.githubusercontent.com/264658/106301664-e2169000-624f-11eb-915a-817742adb778.png)

(confirmed that it is specifically the `prefix` argument that causes this, not any of the others in the screenshot)

**Comment by jdoliner** [comment]
This is probably due to us canonicalizing paths to not have the leading slash. We probably just need to strip that value from the request.
