### ISSUE TITLE
New version of Pachyderm ignore Dockerfile WORKDIR.

### ISSUE THREAD

**Issue by hanpeiyu94** [pachyderm/pachyderm#5683]
**What happened?**:
After updating Pachyderm from 1.10 to 1.12.1, pipeline had error calls file not found. After some digging, we found pachyderm seem like to ignore the ```WORKDIR``` we set on Dockerfile. And runs the image on the root directory.
**What you expected to happen?**:
We were expecting the pipeline would run the image normally without anything got changed.
**Anything else we need to know?**:
By adding ```working_dir``` in pipeline specification solved this problem.

**Comment by mindthevirt** [comment]
Hi @hanpeiyu94, thank you for opening this issue. We’ll take a look at it and try to reproduce

**Comment by mindthevirt** [comment]
@hanpeiyu94 I was not able to reproduce this issue. Could you please share your pipeline spec and dockerfile with us?

**Comment by mindthevirt** [comment]
Also, I just tried another example: https://github.com/pachyderm/pachyderm/tree/master/examples/ml/housing-prices which also uses `WORKDIR` in the Dockerfile and had no issues. This was done on 1.12.2

**Comment by nitinjainsj** [comment]
@hanpeiyu94 If you have ways to repo this issue, that would be really helpful.

**Comment by hanpeiyu94** [comment]
Thanks for trying to help. So my Pachyderm version is 1.12.1. And I got this error, ```"python: can't open file 'regression.py': [Errno 2] No such file or directory"``` when I run your example.

**Comment by mindthevirt** [comment]
Just to confirm, could you please post the output of `pachctl version`?

**Comment by hanpeiyu94** [comment]
Sure. 
```
COMPONENT           VERSION             
pachctl             1.12.1              
pachd               1.12.1
```

**Comment by hanpeiyu94** [comment]
Also the Pachyderm cluster is running on Kubernetes server, not on my local computer. Do you think it have anything to do with it?

**Comment by mindthevirt** [comment]
@hanpeiyu94 I tried to reproduce it on 1.12.0 and 1.12.2 and cannot reproduce it. I've tried it with Hub (our SaaS offering), minikube, docker kubernetes and don't see how this may be possible. Could you provide the following output:

`kubectl get nodes -o wide`

**Comment by hanpeiyu94** [comment]
@mindthevirt Sure, here's the output:
```
NAME             STATUS   ROLES               AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
dgx-1            Ready    worker              149d   v1.19.7   10.1.4.5      <none>        Ubuntu 18.04.5 LTS   4.15.0-134-generic   docker://19.3.14
dgx-2            Ready    worker              257d   v1.19.7   10.1.4.6      <none>        Ubuntu 18.04.5 LTS   4.15.0-134-generic   docker://19.3.14
lynx-ctl-1       Ready    controlplane,etcd   268d   v1.19.7   10.1.3.220    <none>        Ubuntu 18.04.5 LTS   4.15.0-135-generic   docker://19.3.6
lynx-ctl-2       Ready    controlplane,etcd   268d   v1.19.7   10.1.3.221    <none>        Ubuntu 18.04.5 LTS   4.15.0-135-generic   docker://19.3.6
lynx-ctl-3       Ready    controlplane,etcd   268d   v1.19.7   10.1.3.222    <none>        Ubuntu 18.04.5 LTS   4.15.0-134-generic   docker://19.3.6
penguin-cpu-1a   Ready    worker              254d   v1.19.7   10.1.4.56     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-1b   Ready    worker              257d   v1.19.7   10.1.4.57     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-1c   Ready    worker              257d   v1.19.7   10.1.4.58     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-1d   Ready    worker              257d   v1.19.7   10.1.4.59     <none>        Ubuntu 20.04.1 LTS   5.4.0-62-generic     docker://19.3.8
penguin-cpu-2a   Ready    worker              257d   v1.19.7   10.1.4.60     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-2b   Ready    worker              257d   v1.19.7   10.1.4.61     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-2c   Ready    worker              257d   v1.19.7   10.1.4.62     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-cpu-2d   Ready    worker              257d   v1.19.7   10.1.4.63     <none>        Ubuntu 20.04.1 LTS   5.4.0-62-generic     docker://19.3.8
penguin-gpu-1    Ready    worker              268d   v1.19.7   10.1.4.50     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-gpu-2    Ready    worker              268d   v1.19.7   10.1.4.51     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-gpu-3    Ready    worker              268d   v1.19.7   10.1.4.52     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-gpu-4    Ready    worker              268d   v1.19.7   10.1.4.53     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-gpu-5    Ready    worker              268d   v1.19.7   10.1.4.54     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
penguin-gpu-6    Ready    worker              268d   v1.19.7   10.1.4.55     <none>        Ubuntu 20.04.1 LTS   5.4.0-64-generic     docker://19.3.8
```

**Comment by nitinjainsj** [comment]
@hanpeiyu94 is there a shareable dockerfile that you can post here? We feel there is something more specific going on in your setup that we are unable to repo or have seen from other users.

**Comment by hanpeiyu94** [comment]
@nitinjainsj Yes, I had the same error with your example: https://github.com/pachyderm/pachyderm/tree/master/examples/ml/housing-prices

**Comment by mindthevirt** [comment]
@hanpeiyu94 we could not reproduce it in any environment so far. My assumption is that this is an environment-specific issue. It seems like you're unblocked since you've set WORKDIR in the pipeline spec, correct?

**Comment by hanpeiyu94** [comment]
Yes, WORKDIR in the pipeline spec is working, WORKDIR in Dockerfile is not working. This issue is not a blocker for us, we just want to share this problem to you guys and see if there's a way to fix it. And it does look like some kind of environment issue on our end. I think that's a good answer for this issue right now. Thank you for you time, I'll close this issue now.
