### ISSUE TITLE
memory request/limit not working

### ISSUE THREAD

**Issue by xubofei1983** [pachyderm/pachyderm#5685]
**What happened?**:
I created a pipeline with resource request/limit for both cpu and memory

with inspect pipeline command I can see:
`Description: A pipeline that convert bam files to fastq files
...
ResourceRequests:
  CPU: 2
  Memory: 10g
ResourceLimits:
  CPU: 4
  Memory: 20g`

however, in the kubectl describe pod
`Containers:
  user:
    Image:      573640641260.dkr.ecr.us-east-1.amazonaws.com/data:test149
    Port:       <none>
    Host Port:  <none>
    Command:
      /pach-bin/worker
    Limits:
      cpu:  4
    Requests:
      cpu:     2
      memory:  64M`

**What you expected to happen?**:

memory request/limit should be applied in worker pods.

**How to reproduce it (as minimally and precisely as possible)?**:
any pipeline with resource limit I think.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
EKS 1.16
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.12.1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- aws
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
@xubofei1983 , I just tried this and could not reproduce it on 1.12.2.

Here's the setting in my pipeline JSON:
`"resource_requests": {
    "memory": 128M,
    "cpu": 1`}

And when I describe my worker pod, I see the correct settings:

`Containers:
  user:
    Image:      v4tech/imagemagick
    Port:       <none>
    Host Port:  <none>
    Command:
      /pach-bin/worker
    Requests:
      cpu:     1
      memory:  128M`

**Comment by xubofei1983** [comment]
@mindthevirt   ok I get it.   "2G" would work.  "2g" not work.
feel free to close it.
