### ISSUE TITLE
Give users more control over what incremental data is shown.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#569]
Right now if you set `incremental` to `true` then Pachyderm will show jobs only the new data. Often times there are cases where you want a little bit more than just the new data. For example if you're doing an incremental reduce you might need all of the other files which are present in the directory in order to process that new value. We can fix this by adding an additional field to the inputs which controls how they display their changes. We've had 2 slightly different proposals for the behavior of this field:

The first is to add an `incremental-partition` field which would accept the same things that `partition` accepts and also have a default value, maybe called `MINIMAL` which would give you the current behavior of showing just the new stuff and nothing else. Setting the incremental partition would give you a full partitions worth of any piece of data that had new data. For example if partition were set to `FILE` then any file that had changes would be displayed as the full file.

The other proposal is a simpler version of the above, instead of adding a new field we switch incremental to be an enum with the following values: `None` the default which performs no incrementality. `Diff` which displays only the new data (equivalent to `incremental = true` right now) and `Changed` which gives you full values which were changed. What counts as a value is determined by the partitioning of the input. So if an input is partitioned by files then be setting `incremental = changed` you'd get all the files that have changed. If it's global you'd get the entire repo if anything changed.

**Comment by JonathanFraser** [comment]
The issue I see with the second one is it doesn't allow for a differential behaviour between when there is new data and when there is not. This case matters when you have more than one input repo.

**Comment by jdoliner** [comment]
@JonathanFraser I'm not sure I understand. When a pipeline has more than 1 input the input that doesn't have a new commit for you to process will display all of its values so that you can cross them with the new ones in the other repo. Since it's already displaying every value it's unclear to me how either proposal would impact that behavior; in my mind both leave it unchanged. How would you like to be able to modify that behavior?

**Comment by JonathanFraser** [comment]
ahh, i was under the impression that it would display it's values as dictated by the `partition` flag

**Comment by JonathanFraser** [comment]
actually, then what does partition do? if incremental means you only see the increment on new data and you see the entire repo when there isn't what does partition actually specify?

**Comment by jdoliner** [comment]
Partition specifies how the data is partitioned between multiple containers when the job is run in parallel. So when a repo has no new data you'll see the entire repo, but it might be split between multiple containers for parallelism purposes. If partition is `FILE` then we guarantee that files don't get split between multiple containers.

The interplay between this feature and the `Partition` field is pretty subtle but I think it makes sense. Basically setting `incremental = changed` means that instead of seeing a diff you see whatever type of object is specified in `incremental`. I think this makes sense because the `Partition` field is basically specifying how this data needs to be grouped together in order for the computation to be performed correctly. If we did a lower granularity for incremental stuff then it'd be really easy for a computation to accidentally return a wrong result with out realizing it since different data is available under different conditions.

**Comment by jdoliner** [comment]
Bumping this to 1.2.

**Comment by jdoliner** [comment]
Now in master.
