### ISSUE TITLE
Refactor PPS

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#571]
This has been briefly discussed offline but is not yet as well thought-out as #411.

The main motivation here is that PPS is currently very stateful.  For instance, each pipeline is manged by a goroutine that runs on some PPS node.  Relying on goroutines, however, is somewhat fragile since there isn't a general way to ensure that one and only one goroutine is running for each pipeline in a cluster.

Ideally, PPS should follow the philosophy of Kubernetes where a backing data store (RethinkDB in our case) specifies the "ideal state" of the cluster, and the daemons (PPS nodes) ensure that the actual state converges towards the ideal state.

One idea that I have so far is to use Kubernetes jobs instead of goroutines to manage pipelines.  That way, Kubernetes can ensure that one and only one job is managing a pipeline at any given time.

**Comment by sjezewski** [comment]
I think 'etcd state' as a source of truth is true w our current PPS implementation.
