### ISSUE TITLE
Job is stuck on "pulling" after deleting and creating a pipeline.

### ISSUE THREAD

**Issue by pratheekrebala** [pachyderm/pachyderm#572]
Hi, I mentioned this on the #users channel on Slack -- there seems to be an issue when deleting and re-creating a pipeline of the same name using pachctl that causes the re-created pipeline to be stuck in "Pulling" state.

To recreate this:

`pachctl create-pipeline -f pipeline.json`
`pachctl delete-pipeline pipeline_name`
`pachctl delete-repo pipeline_name`
`pachctl create-pipeline -f pipeline.json`

Doing `pachctl list-job` after this shows the job stuck in the "pulling" state although `pachct list-pipeline` says that the pipeline is in "running" state.

Just recreating the same pipeline with a slightly different name seems to resolve this issue.

**Comment by jdoliner** [comment]
Thanks for reporting this @pratheekrebala.

I think we've found the issue, jobs in Pachyderm have deterministic names so when you recreate the pipeline it will recreate jobs with exactly the same names. To avoid conflicts we delete the jobs along with their corresponding Kubernetes jobs. However deleting a job in k8s doesn't delete the pods that it created and when you recreate the job those same pods will count as completed pods for the job so the job won't spawn any new pods.
