### ISSUE TITLE
dashboard ingress docs have a recurring typo and malformed yaml

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#5758]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/deploy-manage/deploy/ingress/pach-ui-ingress/#set-up-ingress-with-traefic-to-access-pachyderm-ui-dash-service-in-your-cluster

**Describe what is wrong:**
1. The page discusses using traefik for ingress but refers to it to it with a typo throughout: 'traefic'.
2. The yaml file for the `mypachydermUICRDs.yaml` seems to be malformed. Attempting to apply it with kubectl, I get the following error: `error: error parsing mypachydermUICRDs.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context`

**Anything else we need to know?**
I would had fixed it myself, unfortunately there is a diagram in the page that includes the typo as well.

**Comment by nadegepepin** [comment]
Nice catch Raanan! Thank you for taking the time to report this issue.
