### ISSUE TITLE
Make local fuse mount more persistent

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#576]
Right now if I:

1) mount locally:

``` shell
mkdir ~/pfs
pachctl mount &
```

2) Relaunch pachyderm `make clean-launch; make launch`
3) Then try to look at the mount:

``` shell
$ ls ~/pfs
ls: cannot open directory '/Users/sjezewski/pfs': Device not configured
```

I cannot. It would be nice if the mount would wait / try to reconnect next time it fields a request from FUSE. Instead I have to remount:

``` shell
umount ~/pfs
pachctl mount ~/pfs &
```

I think that using the local mount to inspect the state of things is pretty common for users. I'm not sure how common it is to relaunch pachyderm (I'm guessing fairly ... but I was doing it as a sledgehammer alternative to the new `delete-all` command). 

Maybe this is an edge case ... but seems nice to have while a user is trying to get their own use case working.

**Comment by jdoliner** [comment]
This would definitely be a nice to have for 1.2.
We can probably just catch the error and retry with some sort of a timeout.

**Comment by sjezewski** [comment]
I'm not convinced users utilize the FUSE mount locally that often, especially now that we've moved away from FUSE. Closing this issue.
