### ISSUE TITLE
What's the difference between pachctl deploy microsoft/azure ?

### ISSUE THREAD

**Issue by artem-yushkovsky** [pachyderm/pachyderm#5760]
What's the difference between deploying to `azure` and to `microsoft`?
```
$ pachctl deploy --help     
Deploy a Pachyderm cluster.

Usage:
  pachctl deploy [command]

Available Commands:
...
  azure         Deploy a Pachyderm cluster running on Microsoft Azure.
...
  microsoft     Deploy a Pachyderm cluster running on Microsoft Azure.
...

$ pachctl version  
COMPONENT           VERSION             
pachctl             1.12.2 
```

**Comment by mindthevirt** [comment]
Hi @artem-yushkovsky there's no difference between them. As a matter of fact, they're aliases to each other.

**Comment by echohack** [comment]
Hey @artem-yushkovsky I'm going to close this issue. Please let us know if you have any further questions about this command!

Here's a link to the alias, for reference: https://github.com/pachyderm/pachyderm/blob/9b7c365665477ce73c514c9e1d902a4fa1555322/src/internal/deploy/cmds/cmds.go#L881
