### ISSUE TITLE
Pachyderm Shell: clear screen command

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#5762]
**What is the goal / desired outcome?**
You used Pachyderm Shell long enough that you want to clean the clutter and get a clearer look at your screen.

**If there is a way to accomplish this today via workaround, what does that require?**
Close the Pachyderm Shell and start a new one.

**(Optional) What is your proposal for a feature to solve this?**
implement a 'clear' command that clears the screen.

**Comment by echohack** [comment]
Hi @RaananHadar 

CTRL + L should clear the screen for you.

This seems like a reasonable request. For now, I'll mark this as a general improvement for `pachctl shell` should the team work on improving it further.

See also #3150

**Comment by RaananHadar** [comment]
Oh, didn't know that! I think that a quick fix would be to add this to the docs in the meanwhile.

**Comment by echohack** [comment]
@RaananHadar No worries! I don't think we should add this to the docs as this is a standard feature of most shells, and not something that we support. I'll keep this issue open though as a way of tracking this idea for the future!

**Comment by RaananHadar** [comment]
Its interesting to note that i've been using a shell forever and didn't know about ctrl+L and I am betting that many others don't. Keyboard shortcuts in shells aren't commonly discussed. In short, if its a trivial addition to Pachyderm shell I would add a clear command, mention ctrl+L it in the docs or at least make this issue easily discoverable :smiley: 

If you are willing to consider the docs option, i'll write a PR :smile:

**Comment by echohack** [comment]
Thanks @RaananHadar. If you'd like to add to the doc, please submit your PR and tag @echohack and @nadegepepin for review! Also link your PR to this issue so we can close it properly when everything is merged!
