### ISSUE TITLE
Failed to execute  “pachctl  mount” in  Kubernetes pod

### ISSUE THREAD

**Issue by toyow** [pachyderm/pachyderm#5767]
**What happened?**:
![image](https://user-images.githubusercontent.com/37426295/109768564-07723180-7c34-11eb-9f6e-e383058d2949.png)
The mount command can be executed successfully on the host computer，but failed in Kubernetes pod，even if I've set the --privilege mode。
**What you expected to happen?**:
Successfully mount file in pod
**How to reproduce it (as minimally and precisely as possible)?**:
Start a pod with privilege mode on, and execute the mount command in the pod container
**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0"
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1",
- Pachyderm CLI and pachd server version (use `pachctl version`):
pachctl             1.12.1              
pachd               1.12.1 
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
aliyun 
- OS (e.g. from /etc/os-release):
Linux version 3.10.0-957.5.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Fri Feb 1 14:54:57 UTC 2019

**Comment by mindthevirt** [comment]
Hi @toyow how did you resolve the issue?
