### ISSUE TITLE
Get file does not support some characters in the file path

### ISSUE THREAD

**Issue by Gezzellig** [pachyderm/pachyderm#5774]
**What happened?**:
pachctl get file (and its go-client sibling) are unable to handle special characters like [ and ] in the filepath.
```
pachctl get file visualize@51dc9520ca684b83a4b8a85b991b60d4:/post_processing/Local_disagg_haz_Sa[0.01].png
```
returned
```
file /post_processing/Local_disagg_haz_Sa[0.01].png not found in repo visualize at commit 51dc9520ca684b83a4b8a85b991b60d4
```
Altough the file is present:
```
pachctl list file visualize@51dc9520ca684b83a4b8a85b991b60d4:/post_processing | grep Local
```
```
/post_processing/Local_disagg_haz_Sa[0.01].png               file 578KiB
```
**What you expected to happen?**:
That the command would return the file

**How to reproduce it (as minimally and precisely as possible)?**:
Add a file containing `[` or `]` in its filename using a pipeline:
```
"stdin": "echo test1 > /pfs/out/test.txt && echo test2 > /pfs/out/test[].txt" 
```
Then see that pachctl get file for text.txt works, but pachctl get file for text[].txt fails.
**Anything else we need to know?**:
The minimal example on minikube gave a different response but it still failed:
```
pachctl get file first@master:/test[].txt
```
```
transport is closing
```
Which is very wierd since it is the same pachd version.

Minikube pachyderm version:
```
COMPONENT           VERSION             
pachctl             1.11.0              
pachd               1.11.0 
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION             
pachctl             1.11.0              
pachd               1.11.0
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Self hosted (also tested minimal version on minikube)
- OS (e.g. from /etc/os-release):
- Others:

**Comment by PFedak** [comment]
Some of the issues you're seeing are because pachyderm interprets the path in `get file` and `list file` as a [glob pattern](https://github.com/pachyderm/ohmyglob). I'm not sure how well this is reflected in our documentation, but the expression you want is `pachctl get 'file first@master:/test\[\].txt'`, quoting the path to keep the shell from interpreting the glob itself.  Unfortunately, an error in our globbing library is causing a crash rather than showing you the error.

**Comment by Gezzellig** [comment]
Yes this works!
First didn't notice your `' '` around the whole file definition.
This also works in the golang client, but there it has to be taken into account that a single slash is a local escape
```
buf := bytes.NewBufferString("")
filePath := "test\\[\\].txt"
println(filePath)
err = pachyClient.GetFile("first", "master", filePath, 0, 0, buf)
check(err)
println(buf.String())
```

**Comment by Gezzellig** [comment]
Sorry should not yet be closed, untill the fix of the proper error message is implemented

**Comment by Gezzellig** [comment]
Important find:
The inspect file notation does not require and even breaks on the added / with special characters
```
pachctl inspect file 'first@master:test\[\].txt'
```
```
file test\[\].txt not found in repo first at commit f7ba56ba16e34a05ae6c610b6095ec39
```
This does work:
```
pachctl inspect file first@master:test[].txt
```
```
Path: test[].txt
Type: file
Size: 5B
Children: 
```
This is not consistent with the get file notation

**Comment by PFedak** [comment]
Currently `inspect file` seems to be the only file system command which doesn't treat the path as a glob pattern. It's unfortunate that the help text doesn't currently reflect that. The crash you observed should be fixed in our next release, and it looks like the behavior is slated to become more predictable in our 2.0 release, with only `glob file` performing globbing. I think we generally recommend avoiding special characters in file paths - we prevent them from being created in some cases.

**Comment by jdoliner** [comment]
@PFedak to clarify this a little bit, inspect file is different from other calls because it can only return a single file. All other file calls (including `get file`) can return multiple files. That being said there should be some consistent way for us to get this to not crash.

**Comment by nadegepepin** [comment]
Documented in `pachctl list` and `get file` commands:
 -> master: PR 5934
 -> 1.13.x: PR 5932
 -> 1.12.x: PR 5887
 -> pused in doc: PR 5931
