### ISSUE TITLE
Memory leak in jobs indirectly causes kernel panic

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#581]
I'm working on a fix but documenting it here in case someone runs into it.

## Setup

```
Provider: GCE
Node count: 3
OS: Debian 7 (Wheezy)
Kernel: 3.16.0-4-amd64
Docker: 1.9.1
Kubernetes: v1.2.4
```

Docker Info:

```
Containers: 42
Images: 308
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 392
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 3.625 GiB
Name: gke-pachyderm-c43e9b09-node-r3mo
ID: KZSN:ITV2:7ZZS:NRIC:UVCK:M7DS:FGU6:TRVW:2CX2:KHPE:5DO3:TAVE
WARNING: No swap limit support
```
## Symptom

Jobs fail.  Pods get restarted for no apparent reason.

## Cause

This apparently happens when you run a job that writes a lot of files to PFS.  The job will apparently use so much memory that the kernel decides to kill the process, at which point the kernel panics, causing the node to restart.  Kubernetes thus loses contact with this node, so it reschedules all pods that previously ran on this node to other nodes, causing the observed restarting of pods.

**Comment by derekchiang** [comment]
Here is what I've learned from debugging with @tv42, about why a job that writes a large amount of files can use a huge amount of memory:

1. The [Go FUSE driver](https://github.com/bazil/fuse) internally uses a [pool](https://golang.org/pkg/sync/#Pool) of buffers, so that it doesn't have to allocate a new buffer every time it needs one.  However, the pool is implemented such that `Any item stored in the Pool may be removed automatically at any time without notification` (from the godoc).  For instance, if your program is using a lot of memory, the Go garbage collector can decide to recycle the items in the pool.

2. For reasons yet to be determined, when you write a lot of files in your jobs, you end up with a lot of open gRPC connection (see #588).  These gRPC connections eat up a lot of memory, causing the garbage collector to run frequently, at which point it might collect buffers from the aforementioned pool.

3. The implementation of the FUSE driver is such that, when there aren't enough buffers in the pool, it just allocates new buffers and put them into the pool.

4. Step 2 and 3 just keep cycling.  That is, FUSE keeps allocating new buffers and putting them into the pool, whereas the garbage collector keeps taking them out.

5. Now, apparently the garbage collector does not immediately free the buffers it collects (I'm going to read more about Go's GC to figure out why).  As a result, we get more and more buffers stuck in memory waiting to be freed.  That's why the memory usage keeps growing.

**Comment by sjezewski** [comment]
Very interesting.

Maybe this is too tricky to test, but I wonder if this behavior changed recently w the grpc update. IIRC before the recent update, we were able to re-use grpc connections. This may have prevented the grpc connection count from growing and triggering GC. If so, it sounds like solving #588 would help mitigate this issue. Although it feels like it might mitigate, but not solve it, if the FUSE buffer pool is sensitive to GC at a certain rate.

**Comment by tv42** [comment]
The write-up above seems aligned with my current understanding.

Latest bazil.org/fuse should fix this (by decreasing the buffer size on Linux): https://github.com/bazil/fuse/commit/9e8e65293a037ce998ba0df102710c49313aa513

You still need to vendor in the new version. I gave @derekchiang https://github.com/tv42/pachyderm/tree/fuse-memory-leak-revendored & https://github.com/tv42/pachyderm/commit/a2c5eb509f75e87b038bf9248d504ba24b823005 that's on top of his then-current branch.

Let me know if you need something more.
