### ISSUE TITLE
just copying from the input repo generates io errors in a pipeline

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#583]
output of get logs, like this for pretty much every file.
```
2016-06-23T20:00:08Z ERROR fuse.FileRead {"file":{"file":{"commit":{"repo":{"name":"prospector_input"},"id":"723e2340a6c94630a7ecc9051fba71da"},"path":"194/digitizer/BIH310090052_T_BI348.bson.gz"},"shard":{"fileModulus":"1"}},"error":"read more than we need; this is likely a bug"}
0 | cp: error reading '/pfs/prospector_input/194/digitizer/BIH310090052_T_BI348.bson.gz': Input/output error
0 | cp: failed to extend '/inputs/prospector_input/194/digitizer/BIH310090052_T_BI348.bson.gz': Input/output error
```

**Comment by jdoliner** [comment]
Hey @JonathanFraser really sorry you ran into this. We have several tests that `cp` data from input repos so I'm guessing there's something subtly different here. Would it be possible to share the code that created this error so I can reproduce it locally and figure out what's going on?

**Comment by JonathanFraser** [comment]
@jdoliner sure here is the manifest file
as you can see it's executing cp as the very first command
`{
  "pipeline": {
    "name": "prospector_preprocessing7"
  },
  "transform": {
    "image": "generalfusion/fushim:new_base",
    "cmd": [
      "sh"
    ],
    "stdin": [
      "export PACH_REPO=prospector_preprocessing",
	  "mkdir /inputs",
	  "cp -r /pfs/prospector_input /inputs",
      "repo/gfpy/digitizer/preprocess.py /temp_output /inputs || exit 1",
      "data-replicator -bucket-name=generalfusion-temp /temp_output/ /pfs/out/ || exit 1"
    ]
  },
  "parallelism": 0,
  "inputs": [
    {
      "repo": {
        "name": "prospector_input"
      },
      "method": {
        "partition": "file",
        "incremental": true
      }
    }
  ]
}`

**Comment by jdoliner** [comment]
@JonathanFraser thanks! Will repro on our end and figure out what's going on.

**Comment by jdoliner** [comment]
@JonathanFraser update on this. I created a test in our test suite which mimics your pipeline as best I could. You can see the test [here](https://github.com/pachyderm/pachyderm/pull/585/files#diff-169b88a58cc85335a06d29c2e7678bc9R2036). Unfortunately I wasn't able to get this test to fail. 1 thing that comes to mind: what do your files look like? I'm creating 100 files, each of which is 10,000 lines long I'm guessing maybe that's the difference but I'm not sure. Any chance you could share the data files? That may be the best hope for getting a faithful recreation on our end.

**Comment by jdoliner** [comment]
@JonathanFraser update on this, I tried downloading some of your specific data files in a further attempt to recreate and wasn't able to get it to show up. I think there's a decent chance that the error was caused by getting pachd into some sort of a weird state which caused pfs ops to error. It might be that this issue goes away if you do a clean deploy. Please let me know if you reproduce the error again with a fresh deploy, hopefully if that happens it'll teach us a bit more about how to reproduce the issue.

Sorry we couldn't find a better solution to this one for you.
