### ISSUE TITLE
S3 gateway produces infinite open sockets

### ISSUE THREAD

**Issue by smthpickboy** [pachyderm/pachyderm#5856]
**What happened?**:
pachd's open sockets increase when read/write files through S3 gateway, and lead to "too many open files" error in the end.

**What you expected to happen?**:
The number of open sockets shouldn't change while read/write files through S3 gateway.

**How to reproduce it (as minimally and precisely as possible)?**:
Simply deploy locally (with local backend) and read/write files through S3 gateway's 30600 port.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+f293dbfc18ff89", GitCommit:"f293dbfc18ff8996048a765046088325c6575d2d", GitTreeState:"clean", BuildDate:"2021-01-29T13:59:02Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+f293dbfc18ff89", GitCommit:"f293dbfc18ff8996048a765046088325c6575d2d", GitTreeState:"clean", BuildDate:"2021-01-29T14:00:13Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):

COMPONENT           VERSION
pachctl             1.12.3
pachd               1.12.3

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): microk8s v1.20.2
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Others:
Read/write through pfs API or pachctl has no problem. Can it be related to pachyderm/s2 ?

**Comment by dgeorg42** [comment]
Thanks for submitting this issue. I'm going to be doing some testing on the S3 Gateway next week, so I'll take a look at this issue while I'm doing so.

Dale Georg
Pachyderm Customer Engineer

**Comment by xyz2566841** [comment]
**supplement @smthpickboy's problem！**
According to the example 
https://github.com/pachyderm/pachyderm/blob/1.12.x/examples/opencv/goclient-example/opencv-example.go
I started a scheduled Task  locally, execute GetFile() operation of pfs every two seconds,  like this:
```
import "github.com/pachyderm/pachyderm/src/client"

func main() {
	c := cron.New()
	c.AddFunc("*/2 * * * * *", func() {
		exec()
	})
	c.Start()
        ...
}
func exec() {
	c, err := client.NewFromAddress("x.x.x.x:30650")
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	err1 := c.GetFile("images", "master", "/cars", 0, 0, &buf)
	if err1 != nil {
		fmt.Println(err1)
	}
}
```
The observed phenomenon is that the number of open Sockets in the pachd's process continues to increase，
and the number of local scheduled task process open Sockets also continues to increase。

**Comment by jrockway** [comment]
@xyz2566841 I think it makes sense for the number of open sockets to increase in your example.  With each run of the cron job, you're creating a new client, and the client maintains a gRPC channel connected to the server, with will consume a file descriptor on each side of the connection.  You can close the client when you're done using it to release the connection.  

It may also be possible to reuse the client between requests -- initialize it once per program, then use the same client each time exec() is called.  That is more typical of gRPC APIs, but it's unclear to me whether our client is safe to use from multiple goroutines (exec() calls run in parallel in your program, assuming `cron` is `"github.com/robfig/cron"`, so being sure of thread safety is necessary unless you provide your own synchronization).  The convention in Go land is to assume it's not thread safe unless the documentation says it's safe, and our documentation doesn't say it's safe.  So, closing the client after you're done with it is the best way to avoid fd leaks, until we check the client for goroutine safety.

**Comment by smthpickboy** [comment]
@jrockway @dgeorg42 @xyz2566841 I've found the root cause of this connection leak.
It comes from controller.clientFactory
```Go
# controller
type controller struct {
	logger *logrus.Entry

	// Name of the PFS repo holding multipart content
	repo string

	// the maximum number of allowed parts that can be associated with any
	// given file
	maxAllowedParts int

	driver Driver

	clientFactory ClientFactory
}
// ClientFactory is a function called by s3g to create request-scoped
// pachyderm clients
type ClientFactory = func() (*client.APIClient, error)
```
The problem is how S3 gateway defines and uses ClientFactory, e.g.:
https://github.com/pachyderm/pachyderm/blob/d3ae19dcd0fa2dd755f9834a28ca6eb3c14d165e/src/server/cmd/pachd/main.go#L958
the clientFactory closure defined in pachd server simply create a new *APIClient without any lock, so whenever it's called, in
https://github.com/pachyderm/pachyderm/blob/d3ae19dcd0fa2dd755f9834a28ca6eb3c14d165e/src/server/pfs/s3/auth.go#L14
https://github.com/pachyderm/pachyderm/blob/d3ae19dcd0fa2dd755f9834a28ca6eb3c14d165e/src/server/pfs/s3/auth.go#L44
https://github.com/pachyderm/pachyderm/blob/d3ae19dcd0fa2dd755f9834a28ca6eb3c14d165e/src/server/pfs/s3/s3.go#L55
it will create a new *APIClient (which creates gRPC connection under the hood) which I think won't be closed.

That's the source of the leak.

btw, is there any reason that ClientFactory creates `request-scoped` pach client? Seems like a waste for me not to reuse the gRPC connection in it.

**Comment by smthpickboy** [comment]
@dgeorg42 any update on this?

**Comment by echohack** [comment]
@smthpickboy We've picked this up internally to fix. Will link the PR here whenever it lands. Thank you again for opening this issue!
