### ISSUE TITLE
Question about pachctl get file

### ISSUE THREAD

**Issue by PriyankaUrs1796** [pachyderm/pachyderm#5861]
Can i fetch file from repo and download into local Directory using this Command pachctl get file <repo>@<branch-or-commit>:<path/in/pfs> [flags]

**Comment by mindthevirt** [comment]
Hello @PriyankaUrs1796 , I'm not sure if you're having an issue or if this is just a question but you can download a file from a repo and branch by using

```
# get file "XXX" on branch "master" in repo "foo"
$ pachctl get file foo@master:XXX
```

**Comment by PriyankaUrs1796** [comment]
> Hello @PriyankaUrs1796 , I'm not sure if you're having an issue or if this is just a question but you can download a file from a repo and branch by using
> 
> ```
> # get file "XXX" on branch "master" in repo "foo"
> $ pachctl get file foo@master:XXX
> ```

Hi @mindthevirt by using this command pachctl get file foo@master:XXX you can display the content of a file not able to download .

**Comment by mindthevirt** [comment]
@PriyankaUrs1796 you'll need to specify -o with the output file name. For example:


```
pachctl list file images@master
NAME         TYPE SIZE
/46Q8nDz.jpg file 57.27KiB
/8MN9Kg0.jpg file 78.7KiB
/g2QnNqa.jpg file 102.4KiB

pachctl get file images@master:/46Q8nDz.jpg -o 46Q8nDz.jpg
46Q8nDz.jpg 58.64KB / 58.64 KB [========================================================================================================================================================================] 0s 0.00 b/s
```

**Comment by PriyankaUrs1796** [comment]
@mindthevirt thanks jan i am able to download the file to my local directory now ,but the issue is 
REPO   BRANCH    COMMIT                           FINISHED       SIZE     PROGRESS DESCRIPTION
images newMaster 1c53b8a0662247949e5b989bb00c5783 3 minutes ago  1.438MiB -         
images newMaster 76727a9663be412196e1d5d94c6f0801 15 minutes ago 1.047MiB -     

I have uploaded the file with same name but different content, i need to do Data Versioning so when i download the file with their corresponding COMMIT ID the first file which i uploaded is getting download .So how can i resolve this.

**Comment by PriyankaUrs1796** [comment]
@mindthevirt I am able to download file using their commit ids ,but now i am struck to download a directory from repo i am using --recursive Flag but i am not able to do .
$ pachctl get file images@02506b3e70ce41ecb45e2e62d00d8927:/Input_dir -r  /newdir

Input_dir is the directory i have uploaded and newdir is the new dir i want the uploaded files.

**Comment by echohack** [comment]
Hi @PriyankaUrs1796

I think you might not be uploading your files to the directory structure you're expecting.

Here's a series of commands that does what you're trying to do:

```shell
$ mkdir data-output
$ pachctl put file test-data@master:data/housing-simplified-0.csv -f data/housing-simplified-0.csv
$ pachctl put file test-data@master:data/housing-simplified-1.csv -f data/housing-simplified-1.csv
$ pachctl get file test-data@master:/data/ --recursive -o ./data-output/
```

I hope this helped. I'm closing this issue now. If you need additional help, please drop by our #users channel in our [Pachyderm Slack Community](https://www.pachyderm.com/slack/) for additional help. Thank you!
