### ISSUE TITLE
Consider using GRPC spec health check instead of custom 

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#5862]
Currently, we implement our own custom [health check service](https://github.com/pachyderm/pachyderm/blob/1.12.x/src/client/health/health.proto) but GRPC has it's own [health check service spec](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)

This is compatible with GRPC tooling such as https://github.com/grpc-ecosystem/grpc-health-probe/ and may make it easier to add checks for things such as load balancers

**Comment by jrockway** [comment]
Done in #6234
