### ISSUE TITLE
Pachdash has 404 link in pipeline wizard to shuffles and joins cookbook entry

### ISSUE THREAD

**Issue by lhayhurst** [pachyderm/pachyderm#5863]
**What happened?**:

In the "Edit Input" field of the `Pachdash`'s pipeline wizard:

![image](https://user-images.githubusercontent.com/216183/112004691-41ba4a80-8adf-11eb-872a-194a72ce75ca.png)

The bottom right link to "shuffles and joins" 404s. It is pointing at: http://docs.pachyderm.io/en/latest/cookbook/combining.html

**What you expected to happen?**: No

**How to reproduce it (as minimally and precisely as possible)?**: Yes

**Anything else we need to know?**: No

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.20.5
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.12.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube v1.18.1
- OS (e.g. from /etc/os-release): ubuntu 20

**Comment by mindthevirt** [comment]
@lhayhurst thank you for bringing this to our attention. The dashboard will be replaced by a newer version over the next couple of weeks but we may be able to fix the redirect.

@nadegepepin could we just create a redirect to fix this? Possibly redirect it to https://docs.pachyderm.com/latest/concepts/pipeline-concepts/
