### ISSUE TITLE
ability to form more or less even datums based on file count, ratio or potential datum size

### ISSUE THREAD

**Issue by izapolsk** [pachyderm/pachyderm#5878]
Use case. I have two big pipelines made up of many smaller pachyderm pipelines. 
pipeline 1 -> prepare initial dataset 
pipeline 2 -> streaming updates 

Pipeline 1 has >2.5M small files in repo. 
I need to group them into more or less even datums and process those datums by workers.
Currently I add artificial group_id to file names in order to group them using "group_by" construction. 
However, this is rather a workaround and it makes life more sophisticated because of maintaining such generated group_ids in "streaming updates" pipeline and "initial dataset" pipeline.

So, it would be great if there was a way to split one big datum "/" to a number of smaller ones or group many small datums "/*" into bigger ones.
Ideally, it could be something like

```
{
  input: {
    "pfs": {
      "name": "in",
      "repo": some-repo,
      "glob": "/*",
      "group_by": {
        count: 100000 (amount of files),
        percent: 10 (10 percent of files are put into datum)
        size: 10M (10M files are put into datum)
      }
    }
  }
}
```
or

```
{
input: {

"pfs": {
  "name": "in",
  "repo": some-repo,
  "glob": "/",
  "split_by": {
     count: 100000 (amount of files),
     percent: 10 (10 percent of files are put into datum)
     size: 10M (10M files are put into datum)
   }
}
}
```

**What is the goal / desired outcome?**
ability to form datums based on count or percentage.

**If there is a way to accomplish this today via workaround, what does that require?**
the only workaround I could come up with is adding artificial group ids to files in dataset and then use "group" feature

**(Optional) What is your proposal for a feature to solve this?**
add an option to form datums based on count of files/percentage of files and etc

**Comment by echohack** [comment]
@izapolsk I think you're looking for `chunk_spec` here in order to process datums more evenly by the workers, yes?

https://docs.pachyderm.com/latest/reference/pipeline_spec/#chunk-spec-optional

**Comment by RaananHadar** [comment]
From my understanding you want to partition the data into x partitions.

What I would probably do is write a shuffle pipeline that uses [empty files](https://docs.pachyderm.com/latest/reference/pipeline_spec/#pfs-input). And write a simple script that partitions the data into x output directories. Then go from there.
Here is an example of a [shuffle pipeline](https://github.com/pachyderm/pachyderm/tree/master/examples/shuffle).

A quick google search found examples in [python](https://gist.github.com/zupo/5849843) and [bash](https://stackoverflow.com/questions/29116212/split-a-folder-into-multiple-subfolders-in-terminal-bash-script) for splitting directory into multiple directories with up to x files. Which is extremely similar to what you want and can be fixed with very little changes to split into x directories (I think that splitting to directories with up to x files is actually a better approach). My suggestion is that you pick your favorite scripting language and turn it into a shuffle pipeline so you will have the best maintainability.

**Comment by izapolsk** [comment]
@echohack,  as @RaananHadar, mentioned above, I'd like to partition data into N partitions.
chunk_spec doesn't help since workers anyway process datums one by one despite of chuck_spec value.

My actual problem is that I have a dataset with > 2.5M small files. each file is one entity.
there is a bunch of pipelines which create and process this dataset. 
If I use glob `/*`, those small files are sent to workers one by one and it takes a lot time to download and process them. 
If I use glob `/`, I can have all those small files downloaded at once and it takes significantly less time and I can process them in many processes simultaneously but I'm limited to one worker.
Only viable solution for me for the time being is to use glob `/*-(group_id)-*.json` for the time being and process formed datums in ~ 20 pachyderm pipeline workers where I run 50-100 processes.

So, I have to either form datums using group + group_id in filename or store them in different folders and here another pipeline comes into play. There is a pipeline that regularly updates this dataset with updates coming from Kafka.
So, I need to somehow or other form datums based on filename or folder name and regulary re-shuffle them in order to keep groups even.

If there was a way to form datums based on given partitioning parameter in pipeline spec like amount of files / percent of whole dataset, it would be really great.

@RaananHadar , thank you for the advice. When I weighed up both approaches before development, it looked to me that group_id in filename would be easier and better maintainable but maybe you're right. Anyway, it would be great to have such feature out of the box if it sounds reasonable for sure.

**Comment by echohack** [comment]
> chunk_spec doesn't help since workers anyway process datums one by one despite of chuck_spec value

That doesn't seem correct. `chunk_spec` should download the number of datums specified together to the worker node and process them together. Essentially, when a worker is available to claim work, it will claim a number of available datums set by the `chunk_spec`. Are you sure these are different datums and not different input commits? Perhaps you're seeing a bug?

**Comment by izapolsk** [comment]
@echohack, this is what I have noticed by myself and what I was told [here](https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1616510526047300?thread_ts=1616485309.046700&cid=C3UN0S0Q0)
I'll jump for a joy if this is a bug and someone is going to fix it.

**Comment by RaananHadar** [comment]
@izapolsk, I think @echohack has a point and my original suggestion may not be optimal.

Besides the chunk spec, I also think that you should look at [max queue size](https://docs.pachyderm.com/latest/reference/pipeline_spec/#max-queue-size-optional). It allows you to download datums concurrently to the processing so your workers will be more efficient. If you have alot of short jobs, this really sounds like an important addition.

This might take some fine tuning. But It has an advantage over my original suggestion, in that it looks much more suitable for streaming than downloading a few big datums into the worker and only once they are done, perform processing, which in practice can be slower.

**Comment by izapolsk** [comment]
I tried setting max_queue_size: 100 + chunk_number to 10000 + parallelizm to 50 - 100 + glob /*. 
it has significantly worse performance that just running  glob: / + 100 processes in one worker.
So, this feature request is still actual.

**Comment by echohack** [comment]
@izapolsk I believe https://github.com/pachyderm/pachyderm/pull/5738 will solve this issue. I'm going to close this issue. Please feel free to reopen if you see this persist in 1.13.0.

**Comment by izapolsk** [comment]
@echohack, my main point was that it would be great to have ability to group datums/files evenly into bigger datums since pachyderm workers process a lot of small datums extremally slow. I looked thru that PR and didn't notice any related changes.
Could you please help me to get how it may influence processing speed ?

**Comment by echohack** [comment]
@izapolsk Hey there. We're hard at work on [Pachyderm 2.0](https://github.com/pachyderm/pachyderm/releases/tag/v2.0.0-alpha.11) which is aimed at improving small file performance. We recognize that this is a bottleneck for some workloads in 1.x.

The linked issue provides a new way to Autoscale your workers, as well as some significant changes to datum ordering. 1.13.0 is also targeting many performance fixes.

I'd encourage you to check out the 2.0.0 alpha and 1.13.0 for improvements in performance.
