### ISSUE TITLE
DeleteRepo with all=True causes stack trace in 2.0

### ISSUE THREAD

**Issue by actgardner** [pachyderm/pachyderm#5890]
**What happened?**:

Called `DeleteRepo` with the `all` flag set to true and `Repo` set to nil in 2.0.0-alpha.8. `validatedAPIServer` tries to do an auth check but `Repo` is nil, which causes a nil pointer dereference.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e7e6ee]

goroutine 13330 [running]:
github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM.func1.1(0xc0012521e0)
	/app/src/internal/collection/transaction.go:101 +0xa5
panic(0x240afc0, 0x3b83270)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*validatedAPIServer).DeleteRepoInTransaction(0xc0005ed9c0, 0xc000de7a90, 0xc00042bb90, 0xc00042bb90, 0x30)
	/app/src/server/pfs/server/val_server.go:35 +0x4e
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*directTransaction).DeleteRepo(0xc00108c708, 0xc00042b350, 0x1e7ce01, 0xc00108c708)
	/app/src/internal/transactionenv/env.go:250 +0x79
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*apiServer).DeleteRepo.func3(0x2b85220, 0xc00108c708, 0xc000de7a90, 0x2b22fc0)
	/app/src/server/pfs/server/api_server.go:138 +0x3a
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*TransactionEnv).WithTransaction.func1(0xc000de7a90, 0xc000de7a90, 0x2b22fc0)
	/app/src/internal/transactionenv/env.go:387 +0x6b
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*TransactionEnv).WithWriteContext.func1(0x2b866a0, 0xc0004fe780, 0x0, 0x0)
	/app/src/internal/transactionenv/env.go:407 +0x10a
github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM.func1(0xc0012521e0, 0x2b866a0, 0xc0004fe780, 0xc00042b9b0, 0x40e300)
	/app/src/internal/collection/transaction.go:109 +0x95
created by github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM
	/app/src/internal/collection/transaction.go:95 +0x86
```

**What you expected to happen?**:

Should delete all the repos. Do we even need this? We have an RPC called DeleteAll.

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by brendoncarroll** [comment]
> Do we even need this? We have an RPC called DeleteAll.
 No I don't think so. We can probably rip that flag out.  @brycemcanally

**Comment by brycemcanally** [comment]
Yeah, `DeleteAll` is functionally the same. It might actually be better to remove `DeleteAll` because we might want to have similar functionality for branches later, so we would have an all flag for each respective `Delete*` rpc. Also, the panic has already been addressed by this PR: https://github.com/pachyderm/pachyderm/pull/6171

**Comment by brendoncarroll** [comment]
I would prefer not to add booleans which totally change the behavior of a method.  Just add another method.

**Comment by brendoncarroll** [comment]
Fixed in https://github.com/pachyderm/pachyderm/pull/6221
