### ISSUE TITLE
ModifyFile consumes first message on stream without reading content

### ISSUE THREAD

**Issue by actgardner** [pachyderm/pachyderm#5898]
**What happened?**:

When I was working on the Python client, I was sending ModifyFile streams to add files to a commit. The first file in the stream was being skipped, because it turns out `ModifyFile` reads off the first message in the stream to get the commit without looking at the content: https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/server/api_server.go#L329

It's not clear whether it's valid to send an AppendFile in the first message of the stream. One way to make this foolproof would be to make the "commit" message a separate type in the `oneof` and require it to be the first message of the stream.

**What you expected to happen?**:

Either it should be an error to send an AppendFile/DeleteFile as the first message in the stream, or we could pass through the first message instead of dropping it.

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by brendoncarroll** [comment]
> One way to make this foolproof would be to make the "commit" message a separate type in the oneof and require it to be the first message of the stream.

👍   It would also allow us to pick the first message off the stream and pipe the rest to CreateFileset.
