### ISSUE TITLE
Get File Issue

### ISSUE THREAD

**Issue by PriyankaUrs1796** [pachyderm/pachyderm#5908]
Hi,
I am not able to get to know the Use  of --parallelism int Please exaplain with an example.

**Comment by dgeorg42** [comment]
The --parallelism flag (or simply -p) indicates how many files the pachctl process can download in parallel.  So, for example, let's say that you have a repo called `myrepo` with a directory called `mydir` that contains 100 files.  If you ran a command like the following:  `pachctl get file myrepo@master:/mydir/* -o . -p 20` there would be 20 separate threads downloading those files in parallel to the current directory.  The default for parallelism is 10, which is typically a reasonable value, but if you are downloading a very large number of files, you may benefit from setting it higher.

Hope this answers your question sufficiently!

---
Dale Georg
Pachyderm Customer Engineer

**Comment by PriyankaUrs1796** [comment]
Thanks @dgeorg42  it was useful to me.My doubt is can we transfer files from one repo to another repo without downloading to a local system.

**Comment by dgeorg42** [comment]
What would be your use case for doing this? Understanding the use case will help me to come up with some ideas for how you could achieve it.  One thing that comes to mind is that you could have a pipeline that reads one repo and then just writes the files to its output repo. That would give you 2 repos with the same contents, but I'm not sure if this is really what you need.

**Comment by echohack** [comment]
Hi @PriyankaUrs1796 thanks for opening this issue. In general, if you have a question about how to use Pachyderm, we recommend joining our [Slack community](https://www.pachyderm.com/slack/). We have a #help channel there where you can get more timely help around these kinds of issues from our community.

I'm closing this issue now. Please feel free to join our Slack and ask for more #help !
