### ISSUE TITLE
1.13.0 rc1: pachctl update pipeline Doesn't Enforce Parallelism Limits

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#5916]
**What happened?**:

I had an existing pipeline running with no parallelism spec set. I edited the JSON file for the pipeline and added a parallelism_spec with constant = 200. I then ran `pachctl update pipeline` and was able to successfully update the pipeline to that level of parallelism, despite not having an Enterprise token.

**What you expected to happen?**:

I expected to receive an error message informing me that parallelism greater than 8 requires an Enterprise token.

**How to reproduce it (as minimally and precisely as possible)?**:

Do what I did above. :)  Create a pipeline with parallelism < 8, then update the spec to have paralelism > 8 and run `pachctl update pipeline`

**Anything else we need to know?**:

Nope. :)

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.18.6
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.13.0-rc.1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by dgeorg42** [comment]
I just learned that `update pipeline` will also create the pipeline if it doesn't already exist. So I tested that scenario, and in that case `update pipeline` _does_ fail with the expected error message.  Which isn't too surprising since it's likely directing to the `create pipeline` code path under the hood.

**Comment by jdoliner** [comment]
Fixed in #5923
