### ISSUE TITLE
Remove Minio Client Implementation

### ISSUE THREAD

**Issue by brendoncarroll** [pachyderm/pachyderm#5919]
This issue is to track the effort to remove the minio client from the `obj` package.  Minio support would still be provided via the s3 client.  Only the separate minio implementation would be removed.

The constructors for the minio client should probably alias the s3 client, so this doesn't affect users.

**Comment by jdoliner** [comment]
Trying to triage this issue, what more information is needed for this one @brendoncarroll

**Comment by brendoncarroll** [comment]
We should probably get an idea of how many users rely on the minio client.  The case that comes to mind is in-house object stores, which are minio compatible, but have quirks preventing use of the s3 client.

Asking our users to try using the amazon client instead is a good first step, and then after some time, assuming no breakage, we can yank out minio.  We could also be more aggressive and alias the s3 client. Essentially forcing people to do that test, and then assess the damage.

**Comment by brycemcanally** [comment]
After thinking about this more, I think we should just keep the minio client as an option. Our object storage usage is pretty simple and I remember us getting bit by several quirks after switching over to the s3 client for custom deployments (which used the minio client prior). Keeping that as an option and leaving the door open to other object storage clients seems like the right path forward.
