### ISSUE TITLE
Allow different blob storages in the same deployment

### ISSUE THREAD

**Issue by A-K-Fischer** [pachyderm/pachyderm#5984]
**What is the goal / desired outcome?**
Optimize operational costs by allowing to store different data sets in blob storages of different performance tiers depending on individual performance needs.

**If there is a way to accomplish this today via workaround, what does that require?**
Not possible AFAIK. 

**(Optional) What is your proposal for a feature to solve this?**
Allow to attach several blob storages for storing the underlying files. Which blob storage to use could be configured at a per-repository level.

**Comment by echohack** [comment]
Hi @A-K-Fischer Thanks for opening this feature request. Can you give me a bit more detail about how you'd like this to work?

You're correct in that presently the S3 compatible storage has to be same storage class and we don't pull files out of multiple different PVs / storage classes. Would you, for example, like all of the data put into one repository to be tied to a particular storage class? Or do you need a higher level grouping, of say, multiple repositories?

Some more details on your use-case would be very helpful here to understand this feature request.

**Comment by A-K-Fischer** [comment]
Hi @echohack! We are using Microsoft Azure.

Right now, only one storage account is linked with each Pachyderm deployment and that storage account has to be set to Premium as per the documentation. Premium blob storage space costs about 16.5 cents per GB per month. So for files that are computed once and then read rarely while being kept for long, costs become unnecessarily high.

Let me think about what a good solution would be.

Azure offers automated lifecycle management which will optimize costs depending on accesses, but that's only available for Standard storage accounts.

Many of our data flows would be fine to put into Standard storage at all times. Other times it would be best to keep something in Premium for a while, then transition that to Standard.

Being able to specify per repository where it's supposed to reside should work well.

For pipelines, I think going from Standard storage to Premium storage might be helpful sometimes (i.e. when something needs to be batch-computed cost efficiently and the results will get accessed a great many times relative to their size).

I suspect that it would be fairly complex to implement something that can store parts of a repository in one storage and parts in another. But it would be great if we could define a "link" between repos so that new data could e.g. first be stored in a Premium repo and then moved to the corresponding Standard repo. Ideally, we could define either a set time (span) to keep data in Premium or trigger that transition via a signal/event of some sorts.

Does this make sense?

**Comment by RaananHadar** [comment]
This is a [copy of this issue](https://github.com/pachyderm/pachyderm/issues/5662). I am glad that there is more demand for this :smiley:

**Comment by echohack** [comment]
@RaananHadar good morning and good call out there! I am going to close this issue as a duplicate and move our discussion over to #5662

@A-K-Fischer Could you please follow #5662 for this issue instead? Thank you!
