### ISSUE TITLE
Autoscaling enterprise validation doesn't exist in master

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6010]
AFAICT, the autoscaling enterprise validation that we introduced in 1.13 doesn't exist in master. I tried to add it, and add the new tests for it, but the enterprise tests have changed quite a bit so I figured it made more sense to create an issue, so I could either come back when I had more time or @actgardner might be able pick it up, as they're the expert on the enterprise tests

**Comment by jdoliner** [comment]
It's not just the enterprise validation that doesn't exist, autoscaling doesn't exist in master at all it still needs to be ported over.
