### ISSUE TITLE
Specify parallelism in terms of cluster size

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#602]
Currently the `parallelism` flag specifies the static number of containers that should be run in parallel.  However, a lot of the times what the user really wants is to be able to say, e.g., run 2 containers per machine, run 1 container per CPU, etc.  Currently the only way to set a dynamic parallelism is to set it to 0, at which point we run N containers where N is the number of nodes.

So it'd be nice if there's a way to specify parallelism in terms of the number of containers per machine or per CPU.

**Comment by jdoliner** [comment]
This is in master, compliments of @msteffen.
