### ISSUE TITLE
The same blocks are assigned to the same container

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#603]
Reported by @jdoliner:

The way Pachyderm works right now, in a `map` job, the same blocks are always assigned to the same container, due to the fact that we simply use the hash of a block's name to determine which container gets it.

Now imagine if you have a repo where 90% of the files have the same content (i.e. they consist of the same blocks).  Now if you run a map job on this repo, 90% of the data will be sent to one container, no matter how many parallel containers you are running.

So the solution here is probably to hash `filename + blockref` when determining which container gets a particular block.

**Comment by jdoliner** [comment]
@derekchiang this is fixed now right since `BlockInShard` takes a filename?

**Comment by derekchiang** [comment]
Yes.
