### ISSUE TITLE
PPS_WORKER_GRPC_PORT doesn't get propagated to sidecars

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6059]
**What happened?**:

Edited PPS_WORKER_GRPC_PORT to > 1024 to make Pachyderm run in a restricted environment and the setting wasn't propagated to sidecars.  

**What you expected to happen?**:

The sidecars should have used the correct configuration. 

**How to reproduce it (as minimally and precisely as possible)?**:

Edit pachd's deployment, changing the value of PPS_WORKER_GRPC_PORT from the default of 80
Create a pipeline
Observe that the RC's configurat doesn't have the correct value
See this error in the logs:

listen tcp :80: bind: permission denied

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/261">261</a> for this issue.</div>

**Comment by actgardner** [comment]
Just tried this on master and the port is now correctly propagated to the worker, closing.
