### ISSUE TITLE
Add force delete for repos

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#608]
We have a number of issues that can leave pfs in a state where listing commits fails because one of the internal api servers doesn't have all of the shards it should. This will be fixed by the pfs refactor since pfs nodes will become stateless. However in the short term we should add a `--force` flag to `DeleteRepo` so that users can at least recover from this situation without having the blow away the cluster.

**Comment by jdoliner** [comment]
@derekchiang do you think you could find time for this one before 1.1?

**Comment by derekchiang** [comment]
@jdoliner sure, I can look into that
