### ISSUE TITLE
Deployment is stuck by CrashBackOff

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#610]
I followed the instruction of the official website to deploy Pachyderm on Google Container Engine. However, I was stuck in the situation that the pods is CrashBackOff.
The situation can be seen as following:
`NAME                   DESIRED        CURRENT            AGE`
`etcd                   1              1                  20m`
`pachd                  2              2                  20m`
`rethink                1              1                  20m`
`NAME                   CLUSTER-IP     EXTERNAL-IP        PORT(S)                        AGE`
`etcd                   10.3.255.3     <none>             2379/TCP,2380/TCP              20m`
`kubernetes             10.3.240.1     <none>             443/TCP                        1h`
`pachd                  10.3.255.16    nodes              650/TCP                        20m`
`rethink                10.3.242.114   nodes              8080/TCP,28015/TCP,29015/TCP   20m`
`NAME                   READY          STATUS             RESTARTS                       AGE`
`etcd-45q17             1/1            Running            0                              20m`
`pachd-530l6            0/1            CrashLoopBackOff   8                              20m`
`pachd-init-qy1x8       0/1            CrashLoopBackOff   8                              20m`
`pachd-wr6d4            0/1            CrashLoopBackOff   8                              20m`
`rethink-6ust6          0/1            CrashLoopBackOff   8                              20m`
`NAME                   STATUS         VOLUME             CAPACITY                       ACCESSMODES   AGE`
`rethink-volume-claim   Bound          rethink-volume     200Gi                          RWO           20m`

As described in the code, four pods pachd-530I6, pachd-init-qy1x8 and, pachd-wr6d4 and rethink-6ust6 are CrashLoopBackOff, and I can do nothing about Pachyderm.

**Comment by ShengjieLuo** [comment]
The log of the patch pod can be seen as following
`kubectl logs pachd-init-sh6j8 --previous`
`time="2016-07-01T01:37:47Z" level=warning msg="Error creating connection: gorethink: dial tcp 10.3.253.212:28015: i/o timeout" 
gorethink: dial tcp 10.3.253.212:28015: i/o timeout`
It seems that the TCP port or rethink pod is error.

**Comment by ShengjieLuo** [comment]
The log of the rethink can be seen as following
`kubectl logs rethink-6ust6 --previous`
`Running rethinkdb 2.3.3~0jessie (GCC 4.9.2)...`
`Running on Linux 3.16.0-4-amd64 x86_64`
`Loading data from directory /var/rethinkdb/data`
`Version: rethinkdb 2.3.3~0jessie (GCC 4.9.2)`
`error: Inaccessible database file: "/var/rethinkdb/data/metadata": No such file or directory`
`       Some possible reasons:`
`       - the database file couldn't be created or opened for reading and writing`
`       - the user which was used to start the database is not an owner of the file`
It is confused that the metadata file seems lose from the cluster.

**Comment by ShengjieLuo** [comment]
Actually, there is no directory named '/var/rethink/data' either in Google Cloud Shell or Google VM instances. So the question is related to rethinkdb or anything else? @jdoliner

**Comment by derekchiang** [comment]
Hi @ShengjieLuo, did you format the persistent volume and `rm -rf` before you launch pachyderm?  RethinkDB requires a completely empty disk in order to run.  The instructions can be found here: https://github.com/pachyderm/pachyderm/blob/master/SETUP.md#format-volume

After you've done that, you should be able to relaunch the cluster with `make clean-launch && make launch`.  Let me know if you run into any issues after that.

**Comment by ShengjieLuo** [comment]
I do format the disk in GCE but not do `rm -rf` command. I had thought the new mount disk would be a empty disk and omitted this step. I would do this steps at once to see whether it works.

**Comment by derekchiang** [comment]
@ShengjieLuo yeah it's a common gotcha: the disk utility usually dumps a bunch of garbage files into a hidden `lost+found` folder, so your disk won't be completely empty unless you explicitly `rm -rf`.

Also, make sure to launch with the correct manifest: `make clean-launch && make MANIFEST=manifest launch` where `manifest` points to the file you generated via `make google-cluster-manifest`

**Comment by ShengjieLuo** [comment]
A question occurred to me that the `rm -rf [path to disk]/*`, what does the [path-to-disk] mean? Dose that mean `/mnt/disks/[MNT_DIR]` or `/dev/disk/by-id/google-[DISK_NAME]` ? See [https://cloud.google.com/compute/docs/disks/add-persistent-disk#formatting]
@derekchiang

**Comment by ShengjieLuo** [comment]
Tanks for you help. All of the pods are running. And the launch finished in 41 seconds. You do help me a lot for this problem.

**Comment by jdoliner** [comment]
Closing this one, seems the immediate issue has been solved and #612 should make this problem go away.
