### ISSUE TITLE
Things in the 1.13 branch that aren't in master

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6123]
- [x] Autoscaling
- [ ] ~~admin/v1_12 protos (for extract/restore)~~
- [ ] https://github.com/pachyderm/pachyderm/pull/5831 and https://github.com/pachyderm/pachyderm/pull/6083 (bug fixes for pollPipelinePods)

**Comment by nitinjainsj** [comment]
Thanks @msteffen for the tracking issue. Autoscaling and fixes associated with pipelinepds should be ported to master. I don't think we need to port the protos -- since we won't support extract from 1.x cluster and restore to 2.x cluster.
