### ISSUE TITLE
pachd is slow after upgrading to 1.13.2

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#6131]
**What happened?**:
Interaction with pachd is very slow. For example `pachctl update pipeline` can take over 10 seconds to return.
When typing `pachctl list job` the command hangs and after a few seconds I see the following output:
```
~
~
~
... (this fills the whole screen)
~
~
~
~
:...skipping...
```
EDIT: upon inspection, I am seeing that pachd is crashing and getting OOM killed. The pod is becoming unhealthy for some reason.

**What you expected to happen?**:
pachd works in a timely manner.
**How to reproduce it (as minimally and precisely as possible)?**:
run `pachctl list job` or `pachctl update pipeline` with the latest version in an environment similar to mine.
**Anything else we need to know?**:
This started after upgrading to 1.13.2
**Environment?**:
- Kubernetes version (use `kubectl version`): 1.20.2
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.13.2 for both
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): azure AKS 1.20.5

**Comment by RaananHadar** [comment]
Updating on this: i've updated my pachd spec to 4cpu and 16GB and my etcd volume to use premium storage. Will test if this solves this and if it does I will close the issue.

**Comment by nitinjainsj** [comment]
@RaananHadar Thanks for filing the issue. Can you also provide info about what was the previous version pachd? Also the resources for pachd in previous version?

**Comment by RaananHadar** [comment]
Thanks for the quick response @nitinjainsj . I used version 1.12.5 with the default resources requests, limits and storage classes for etcd (I did use premium class object storage). I did not notice any slowdowns with these settings. I can update that deploying with the increased resources allocation really helped. Pachd no longer hangs for over 10 seconds.. but I do see some slow downs of a few seconds when running `pachctl list job`.

**Comment by PachydermSupport** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/243">243</a> for this issue.</div>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/243">243</a> for this issue.</div>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/285">285</a> for this issue.</div>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg unlinked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/243">243</a> from this issue.</div>

**Comment by RaananHadar** [comment]
closing this as this should behave differently in 2.x
