### ISSUE TITLE
missing "" diff

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#614]
## Symptom

You see error messages of the form `missing "" diff` in most PFS operations such as `list-repo`, `create-repo`, `delete-repo`, etc.

## Cause

This is a known issue that happens for undetermined reasons.  Basically this suggests that cluster membership is messed up somehow.  As such, this should be fixed once we get to #411, at which point membership will be a non-issue.

## Recovery

Currently, the only sure way to recover from this erroneous state is to force remove the problematic repo:

```
$ pachctl delete-repo --force problematic_repo
```

**Comment by sjezewski** [comment]
No known reliable way to reproduce this + addressed by refactor, so closing
