### ISSUE TITLE
pachctl get file reports file sizes that are slightly larger than the actual file size

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#6145]
**What happened?**:
I ran a simple `pachctl get file ...`. The reported file size number, adjacent to the waitbar is consistently slightly larger than the real file size reported when listing the repo.

**What you expected to happen?**:
I think the number should be the same as the file size, unless this can be justified.

**How to reproduce it (as minimally and precisely as possible)?**:
Run a simple `pachctl get file...`

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.20.5
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.13.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): azure

**Comment by PFedak** [comment]
Our progress bars use metric/power of ten measures for size (that is, kilobytes rather than kibibytes), which would indeed cause them to be larger than reported sizes on many platforms. The value shown should agree with the first few digits of the raw byte count reported by e.g. `stat`.

**Comment by jdoliner** [comment]
We could consider moving these to kibibytes if those are more standard. I though kilobytes was going to be the more expected metric.

**Comment by RaananHadar** [comment]
Got it, just wanted to make sure that its not a bug.
