### ISSUE TITLE
config list context should show active-enterprise-context

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6161]
**What is the goal / desired outcome?**

As a Pachyderm user, I would like to see all the information about my active contexts when I list my context so I know to set them correctly.

**If there is a way to accomplish this today via workaround, what does that require?**

The user must explicitly call pachctl config get active-enterprise-context.

**(Optional) What is your proposal for a feature to solve this?**

Add an "E" to indicate the currently active enterprise context:

When they're different:
```
$  pc config list context
ACTIVE	NAME
	aws
	cluster-metrics
	demo
	docker-desktop
	enterprise
E	enterprise-2-16-alpha
*	jk-2-16-alpha
```
When they're the same:
```
$  pc config list context
ACTIVE	NAME
	aws
	cluster-metrics
	demo
	docker-desktop
	enterprise
	enterprise-2-16-alpha
E*	jk-2-16-alpha
```

**Comment by acohen4** [comment]
Hey @pappasilenus , this feature request sounds good to me! 

I haven't gotten others' feedback on it yet, but in the meantime made a corresponding PR to implement this: https://github.com/pachyderm/pachyderm/pull/6184

**Comment by actgardner** [comment]
This should be resolved in the next alpha, closing
