### ISSUE TITLE
create Hub-specific "Beginner's Tutorial" doc for linking in Hub ui

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6163]
**Provide a link to the page with an issue:**

https://docs.pachyderm.com/latest/getting_started/beginner_tutorial/

**Describe what is wrong:**

1. [Prerequisites](https://docs.pachyderm.com/latest/getting_started/beginner_tutorial/#prerequisites) are for Community Edition / Enterprise and should be modified to instruct the user on how to deploy pachctl and connect to their hub cluster.
2. [Exploring your DAG](https://docs.pachyderm.com/latest/getting_started/beginner_tutorial/#exploring-your-dag-in-the-pachyderm-dashboard) section should instruct the user on how to connect to the dash using hub and omit licensing information
3. [Next Steps](https://docs.pachyderm.com/latest/getting_started/beginner_tutorial/#next-steps) should omit all mention of local deployment and just mention loading data and creating pipelines.

**Describe the suggested changes:**

Create a hub-specific Beginner's Tutorial document, deploy in the hub directory, and, when complete, notify hub team so the card on the workspace list page can be modified to point to it.

**Anything else we need to know?**

cc @nitinjainsj @lparobek 

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by nadegepepin** [comment]
Closing this following Hub deprioritization
