### ISSUE TITLE
2.X garbage collection doesn't recover space after repo deleted

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6180]
**What happened?**:

I ran multiple load tests and deleted the load_test repo, but the contents of the S3 bucket Pachyderm was configured with never changed.

**What you expected to happen?**:

My expectations were that within 1-10 minutes after deletion, files would be deleted in the object store.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Run a load test (see my sample configuration file below.)
2. Check the contents of the bucket Pachyderm is configured with.  Note the size, paths &  number of files.
2. delete the created load_test repo
3. Wait more than 10 minutes
4.  Check the contents of the bucket. It hasn't changed.  There's no indication in the logs that garbage collection has run.

**Anything else we need to know?*:

This contains 
* first_load_test.yaml config, which creates 10 small files.
* first_load_test_sorted.txt, the output of `aws s3 ls s3://pachyderm-bucket/  --recursive | sort`  after that test was run
* second_load_test.yaml config, which creates many more small files to medium files
* second_load_test_sorted.txt, the output of `aws s3 ls s3://pachyderm-bucket/  --recursive | sort` after that test was run

Note the timestamps.

[load_tests.zip](https://github.com/pachyderm/pachyderm/files/6541287/load_tests.zip)

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

- Pachyderm CLI and pachd server version (use `pachctl version`):
COMPONENT           VERSION
pachctl             2.0.0-alpha.18
pachd               2.0.0-alpha.18
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- AWS EKS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by brendoncarroll** [comment]
This looks like a problem with the chunk garbage collection.  There's a problem reading the row from postgres.

```
2021-05-25T18:07:11Z ERROR during chunk GC: expected slice but got struct
```
```
postgres=# select count(1) from storage.tracker_objects;
 count
-------
     0
(1 row)

postgres=# select count(1) from storage.chunk_objects;
 count
-------
   590
(1 row)

postgres=# select tombstone, count(*) from storage.chunk_objects group by tombstone;
 tombstone | count
-----------+-------
 t         |   590
(1 row)
```
There are no tracker objects, so all the metadata has been cleaned up.  But the chunk GC hasn't made any progress, so all the chunks and objects are still around.

**Comment by brendoncarroll** [comment]
This should be fixed in the latest alpha 19 with this P.R. https://github.com/pachyderm/pachyderm/pull/6193

I don't see errors in the logs after deleting the repo.  But I'll wait until after the hackathon today to close this issue.
