### ISSUE TITLE
Pipelines and Repos Don't Survive Cluster Restart

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6189]
**What happened?**:

I have an EKS cluster on AWS which is scheduled to automatically shut down at 8 PM each night to ensure that I don't forget to shut it down after I'm done using it.  Yesterday I was using the cluster to test 2.0.0-alpha.18, but when I restarted the cluster this morning, my pipelines, repos, and job history were all gone.

**What you expected to happen?**:

With Pachyderm 1.11, 1.12, and 1.13, whenever I would start the cluster, my pipelines, repos, and job history all still existed.  I expected the same behavior with 2.0.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a pipeline and/or repo, shut down the cluster, restart it, and then check to see they no longer exist.

**Anything else we need to know?**:

The repo had files in it, and now even though the repo doesn't exist anymore, the chunks still exist in the S3 bucket.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.19
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.0.0-alpha.18
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by nitinjainsj** [comment]
Also repo'ed on alpha.21

**Comment by jrockway** [comment]
Does postgres have a persistent volume in your configuration?  The latest released helm chart seems to provision one, so that data shouldn't get lost.

`kubectl get pv`, `kubectl get pvc` and `kubectl get storageclass` would be interesting.

How do you tell EKS to shut down your cluster?  Could it be deleting EBS volumes claimed through PVCs when this operation occurs?

**Comment by nitinjainsj** [comment]
I should have clarified... my test was local. PV makes sense.

Retest with helm install

**Comment by nitinjainsj** [comment]
@chainlink I think this will get address with the helm changes to have a PV.

**Comment by dgeorg42** [comment]
@nitinjainsj  @chainlink - This is still an issue on Beta 2 using the Helm deployment.  Thanks.

**Comment by chainlink** [comment]
@dgeorg42 Sorry you're still hitting this. We need more information to debug:
-  what command are you using to shutdown the cluster? 
- Are you using the local deploy option? AWS option?

It seems like the most likely culprit here is that the PVCs are being deleted by amazon on shutdown. There may be a setting we can add to prevent this.

**Comment by dgeorg42** [comment]
@chainlink - I have an autoscaling policy configured to scale my cluster down to 0 nodes every night at 10 PM; mainly so that I don't inadvertently leave my cluster running for days on end when I'm done using it. But I see the same behavior if I manually edit the cluster's node group to set desired size to 0.

It doesn't appear that Amazon is deleting the PVCs, either.  If I shut down all of my nodes, you can see that the PVCs and PVs still exist.
```
[Thu Jul 22 10:36:22]
{pach 2.0.0-beta.2 : default} / {k8s 1.16.13-dispatcher : aws} / {git 2.24.3 : customer-success/master}
~/Documents/Work/Repos ... /performance/2.0.0-beta.1 -->> kubectl get pvc
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
etcd-storage-etcd-0           Bound    pvc-e921a96e-44fe-4482-94d6-7cc40598091c   500Gi      RWO            etcd-storage-class         17h
postgres-storage-postgres-0   Bound    pvc-0799b3e1-e4ef-4df5-89d3-64a959683f65   500Gi      RWO            postgresql-storage-class   17h

[Thu Jul 22 10:39:51]
{pach 2.0.0-beta.2 : default} / {k8s 1.16.13-dispatcher : aws} / {git 2.24.3 : customer-success/master}
~/Documents/Work/Repos ... /performance/2.0.0-beta.1 -->> kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS               REASON   AGE
pvc-0799b3e1-e4ef-4df5-89d3-64a959683f65   500Gi      RWO            Delete           Bound    default/postgres-storage-postgres-0   postgresql-storage-class            17h
pvc-e921a96e-44fe-4482-94d6-7cc40598091c   500Gi      RWO            Delete           Bound    default/etcd-storage-etcd-0           etcd-storage-class                  17h
```
When I start my nodes back up again, the same objects with the same IDs still exist, and they still show the age as "17h" (which is correct because yesterday I did a complete reinstall via Helm when I was switching from 1.13.2 to 2.0 for my performance testing).  But any pipelines and repos that I had are now gone.

**Comment by dgeorg42** [comment]
The command I've used to deploy is the following:
`helm install pachd -f helm-deploy.yaml pachyderm/pachyderm --version 2.0.0-beta.2`

My Helm settings file is attached (renamed to .txt since GitHub won't let me upload it as .yaml!)

[helm-deploy.txt](https://github.com/pachyderm/pachyderm/files/6863096/helm-deploy.txt)

**Comment by chainlink** [comment]
Fix here: https://github.com/pachyderm/pachyderm/pull/6605

**Comment by chainlink** [comment]
@dgeorg42 this should be fixed in beta.4, please let me know and close if so.

**Comment by dgeorg42** [comment]
This is definitely fixed. Closing.
