### ISSUE TITLE
pachctl put file Should Retain the -o Parameter (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6192]
In 2.0, the default behavior for `pachctl put file` has changed from append to overwrite. As a result of this change, the command now has a `-a` parameter which can be used when append is the behavior you actually want, and the `-o` parameter has been removed since it is now the default.

However, I would recommend that we keep the `-o` parameter as a valid (if deprecated) option in order to support backward compatibility. Since many users use `-o` to force overwrite, any scripts they may have will break upon upgrading to 2.0.

**Comment by nitinjainsj** [comment]
@dgeorg42 There are several pachctl commands that are not backward compatible. It seems odd to have an option for default behavior. Since this is a popularly used option, we should document it and make it part of release notes. I am inclined to close this one.

**Comment by brycemcanally** [comment]
I agree with not retaining this.

**Comment by dgeorg42** [comment]
OK, I'm fine to close this out. Beyond inclusion in the release notes, I think that as part of the 2.0 documentation we'll need to have an Upgrade Guide where things like this are documented so that users don't get tripped up.
