### ISSUE TITLE
Inconsistent Behavior from pachctl delete file (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6194]
This is somewhat related to Issue #6190 

In trying to understand why I could no longer use wildcards to delete all of the files from a repo, I thought that I had stumbled upon a solution, namely: `pachctl delete file repo@master:/`  Presumably, that should delete everything in the root of the repo. But so far, all of the testing I have done has shown very inconsistent results, specifically:

- If the repo has a single directory at the root, with files in it that were all added as part of the same commit, then `pachctl delete file repo@master:/` does nothing. Until you run it a _second_ time, and then all of the files in the repo are deleted.
-  If the repo has a single directory at the root, with files in it that were added as part of _different_ commits, then the first time you run `pachctl delete file repo@master:/` the files from the earlier commits will be deleted, but the files from the most recent commit will remain.  Run `pachctl delete file repo@master:/` again, and the rest of the files get deleted.
- If a repo has multiple directories at the root, where each directory was added as part of a separate commit, then the first time you run `pachctl delete file repo@master:/` all but the most recent directory gets deleted.  Run `pachctl delete file repo@master:/` a second time, and the final directory gets deleted.

Those are the only combinations that I've tested.  I haven't, for example, tested what happens with files directly in the root.  But I suspect we'd see a similar pattern where the first run of `pachctl delete file repo@master:/` deletes everything except for what was added with the most recent commit, and then running it a second time deletes the remainder of the files.

**Comment by brycemcanally** [comment]
This should be fixed in the most recent alpha.
