### ISSUE TITLE
pachyderm pipeline workers try connecting to segment.io despite metrics are disabled

### ISSUE THREAD

**Issue by izapolsk** [pachyderm/pachyderm#6199]
**What happened?**:
Metrics are disabled in my deployment.
But I often see the following errors in pipeline worker logs 

`segment 2021/05/27 08:47:03 error sending request: Post "https://api.segment.io/v1/batch": read tcp 172.17.128.26:38126->52.89.58.223:443: read: connection reset by peer`

**What you expected to happen?**:
pachyderm shouldn't try connecting to segment.io if metrics are disabled

**How to reproduce it (as minimally and precisely as possible)?**:
1. deploy pachyderm with no access to internet
2.  set "METRICS" variable to false for pachd
3.  run some pipeline and check storage container logs for above error

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
(.venv) ➜  tmp kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
(.venv) ➜  tmp pachctl version
COMPONENT           VERSION
pachctl             1.12.4
pachd               1.12.4
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

on prem k8s

- OS (e.g. from /etc/os-release):
```
(.venv) ➜  tmp cat /etc/os-release
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Comment by PFedak** [comment]
You're absolutely right, thanks for pointing this out!

**Comment by PFedak** [comment]
We weren't passing the metrics flag into the worker pods. This will be fixed in 2.0 and our next 1.13 release. In the meantime, it looks like the best option is to add a `pod_spec` field to any relevant pipelines that sets a `METRICS` environment variable to false in the first two containers, something like

**Comment by izapolsk** [comment]
thanks

**Comment by PFedak** [comment]
Sorry to contradict myself again, but I was misreading the JSON patch spec - the following will disable metrics correctly in a pipeline: 
`"pod_patch": "[{\"op\":\"add\", \"path\":\"/containers/0/env/-\", \"value\":{\"name\":\"METRICS\", \"value\":\"false\"}},{\"op\":\"add\", \"path\":\"/containers/1/env/-\", \"value\":{\"name\":\"METRICS\", \"value\":\"false\"}}]",`
