### ISSUE TITLE
Add minikube to SETUP.md

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#620]
As of k8s 1.3 minikube is the lowest barrier to entry way of getting a local kube cluster running.
We should probably put it at the top of deployment options since it's the lowest barrier to entry.
I think there's still value in keeping around the dockerized version, it's still a better option if you're using Docker Machine or running on native linux I think.

**Comment by sjezewski** [comment]
I think this is already done?

**Comment by sjezewski** [comment]
I believe this is on the `doc-sidebar` branch

**Comment by msteffen** [comment]
Strictly speaking, setup.md doesn't exist anymore, but the [getting started page in our readthedocs guide](http://pachyderm.readthedocs.io/en/latest/installation.html) is written using minikube
