### ISSUE TITLE
Error Message Logged by Postgres Every 2 Seconds (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6207]
After deploying 2.0.0-alpha.18 to AWS, I noticed that the following is logged to the `postgres-0` pod log every 2 seconds, even if there are no pipeline jobs or anything else running:
```
2021-05-27 20:27:13.568 UTC [273] ERROR:  canceling statement due to user request
2021-05-27 20:27:13.568 UTC [273] STATEMENT:  SELECT metadata_pb FROM storage.filesets WHERE id = $1
```

**Comment by brendoncarroll** [comment]
That query is run any time we read a fileset.  The cancelling is probably from a context expiring.  I'm not sure what does this every 2 seconds. Maybe it's a retry?

@Tryneus Any chance this is related to sharing connections with the Listeners?

**Comment by Tryneus** [comment]
FWIW, I believe this is coming from the PPS master which is polling a different pipeline every two seconds as a fail-safe to make sure we don't miss a notification and leave the worker RC out-of-date, and it will do a read of the pipeline spec.

**Comment by dgeorg42** [comment]
Not sure when this was fixed, but I have validated that it no longer occurs in Beta 3.
