### ISSUE TITLE
Use PetSets for rethink/etcd deployment

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#621]
Kubernetes 1.3 added PetSets which make stateful services much easier. I think they'll be a more robust way to deploy rethink and etcd.

**Comment by derekchiang** [comment]
To clarify, we may not need etcd anymore in 1.2.

**Comment by derekchiang** [comment]
We should look to using local disks (ideally SSDs) for rethinkdb instead of GCE persistent disks / elastic block storage, since the latter is networked and therefore has much worse performance.

**Comment by msteffen** [comment]
Minor updates:
- PetSets don't let you use local disks, unfortunately, so we're still stuck with network volumes for the time being
- PetSets work by creating N "pets", where each pet is a container + a persistent volume claim
- This means that to create an N-node rethink cluster, users will have to create N persistent volumes (which means creating N EBS volumes/GCE persistent disks). Ideally we'll make that easy to do with pachctl

**Comment by sjezewski** [comment]
No longer use rethink. We have etcd deployable as a petset in 1.4. Double closed!
