### ISSUE TITLE
Pipeline streaming

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#624]
Currently, a pipeline is not run until some data has been committed into the input repo.  However, in theory the pipeline can run as soon as **any** data has been written to the input repo, even before the commit is finished.  The obvious downside is that the pipeline can waste work if the input commit ends up being cancelled.

This can significantly speed up multi-pipeline applications where commits might be large.  Imagine three repos A, B, and C connected by two pipelines `A->B` and `B->C`.  Without this feature, `B->C` won't run until `A->B` finishes.  With this feature, `A->B` and `B->C` can run concurrently where the data sort of "flows" through the pipelines.

**Comment by derekchiang** [comment]
One can however argue that, if you care about having a pipeline run as soon as some data comes in, you can just split the input data into many small commits, as opposed to one single large commit.

However, creating many small commits can be unwieldy in many situations.  Sometimes you really just want your data to sit in one single commit, so it's easier to reason about your data.

One alternative solution is to introduce something like a "commit set", which is basically a large commit that composes of many small commits.  Users would use "commit sets" like they use commits today; and commits become more like a unit of streaming data.

**Comment by jdoliner** [comment]
At this point we've got a much better understanding of our current semantics and where they break down. I think there's some performance improvements we can make on when we process datums in jobs, but I don't think it's very likely we'll want to process things off of commit boundaries, it would be very difficult with how our code currently works, and it seems like for every case where it improves performance there's another case where it worsens it by processing data that isn't ready to be processed, is going to change, and thus is going to need to be reprocessed.

For those finding this issue, the recommended way to do this is to use granular commits that allow for granular processing and [deferred processing](https://docs.pachyderm.io/en/latest/cookbook/deferred_processing.html) to prevent the deleterious performance effects of lots of small commits.
