### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#626]
Once we are done with #411, we will be in a very good position to finally implement a garbage collector that removes unreferenced blocks, since all block references will be stored in a very queryable database (RethinkDB).

**Comment by jdoliner** [comment]
An initial proposal for how to do this:

- Add a global generation counter
- All commits are assigned to the current generation on creation
- Any time a block is written as part of a commit we record the generation it's being written in. This allows us to know the most recent generation a block has been written in.
- When we want to gc we increment the global generation. If the generation is `n` then we know that all blocks in generation `[0,n-1]` that aren't referenced in commits `[0,n-1]` can be GCed.
- There will never be any new Commits in `[0,n-1]` so there's no writes that this computation can race with. If Commits are later deleted though GC can be rerun to reclaim the space.

**Comment by sjezewski** [comment]
Just to restate the user's use case from #914 :

They ran out storage on their local disk (which prevented them from running pipelines). They did `pachctl delete-all` and were surprised that all of the raw files weren't also deleted. This seems like a reasonable thing to be surprised about.

I'm not sure what the implementation would be to service this (I think there are several), but want to make sure we understand this use case when considering our design.

**Comment by jdoliner** [comment]
I think the above implementation would service this. Calls to `pachctl delete-all` would leave all of the blocks unreferenced which means that they would eventually be GCed and the space would be reclaimed.

**Comment by Seth-Karlo** [comment]
This is also a requirement for us, commenting here so I can keep track of what's happening :)

**Comment by jdoliner** [comment]
Now that 2.0 is in master with full featured GC it's time to close this. 🎉 🎉
