### ISSUE TITLE
Ability to configure Pachyderm cluster settings via kube-native approaches

### ISSUE THREAD

**Issue by tybritten** [pachyderm/pachyderm#6307]
**What is the goal / desired outcome?**
Currently, `helm install` will deploy the pachyderm cluster, but any further base configuration (enterprise license, auth, etc) requires using `pachctl` commands or the API after installation which is manual intervention and does not support a gitops workflow.

**If there is a way to accomplish this today via workaround, what does that require?**
A pod with a pachyderm goclient that could read the various configuration settings from a configmap and/or secret and run as an init container after install in the helm chart to configure the cluster.
 
**(Optional) What is your proposal for a feature to solve this?**
A longer-term solution would have `pachd` check for the existence of certain environment variables and/or secrets/configmaps on startup to configure or reconfigure settings on the cluster. This would allow a more standard gitops workflow for customers who want to keep track of their cluster configurations and update them programmatically.

[AB#75](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/75)

**Comment by chainlink** [comment]
This is addressed with the config pod, but we need some docs for it

**Comment by tybritten** [comment]
If I'm looking at the template for the config secret right, this isn't fully implemented yet to document?

**Comment by chainlink** [comment]
It works with the local values yaml. To activate the config pod you need to specify an enterprise key and a root password

**Comment by chainlink** [comment]
The plan is to built the local values in so you don't need to specify (but keep the values blank in the values.yaml)

**Comment by tybritten** [comment]
what if i'm deploying not locally? Is the expected flow that I create the secret manually before deploying?
