### ISSUE TITLE
GCP cluster -> Node Pool Image type now defaults to Containerd causing a ImagePullBackOff on the pipeline's pod

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6315]
**What happened?**:
Created a new cluster on GCP  ( https://docs.pachyderm.com/latest/deploy-manage/deploy/google_cloud_platform/#google-cloud-platform ) using **1.19.9-gke.1900**.

I had to manually edit my Node pool to set docker as the default registry - The initial value at  the cluster creation was **Containerd** -> `kubectl get nodes -o wide` which resulted in an ImagePullBackOff on my pipeline's pod.

**What you expected to happen?**:
Since Docker.io is Containerd's default registry, I would expect my image to be pulled properly

**Comment by nadegepepin** [comment]
Pipeline spec used: https://github.com/pachyderm/pachyderm/blob/master/examples/spouts/go-rabbitmq-spout/pipelines/spout.pipeline.json

**Comment by jrockway** [comment]
We chatted about this in DMs and during Game Day today, and this bug warrants careful investigation.  I'd expect Google's switch to containerd to break code that requires a docker socket, but I wouldn't expect it to cause ImagePullBackoff.  

Maybe https://github.com/pachyderm/pachyderm/blob/master/examples/spouts/go-rabbitmq-spout/pipelines/spout.pipeline.json#L13 (a docker hub container label) needs to be `docker.io/pachyderm/...` when running under containerd.  It would surprise me though, a lot of people are broken if that default changes.  So it's possible that containerd is a red herring and something else is actually wrong (and it fixed itself after cycling the node pool), and we should investigate that.

**Comment by nadegepepin** [comment]
Re-tested on **1.19.10-gke.1600** -> worked fine.

**Comment by tybritten** [comment]
happening on v1.20.8-gke.900 now too

**Comment by tybritten** [comment]
Update- it only happens when pachyderm is deployed via 'pachctl deploy google' it doesn't happen with helm deployed versions

**Comment by tybritten** [comment]
ok i've found the cause- when you deploy with pachctl deploy, any pipeline created gets /var/run/docker.sock from docker (rw) in the mounts which cause pachd to try to use the (nonexistant) docker socket
