### ISSUE TITLE
'pachctl auth login' should print URL if browser can't be exec-ed

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6318]
Currently when running `pachctl auth login` in e.g. WSL (or any VM), pachctl tries to open a login page in your browser, but the VM may not have a browser installed.

In this case, we should ideally make the `-b/--no-browser` flag discoverable, or simply default to the "no browser" behavior in this case

(We ran into this during the 2.0 gameday because @PFedak uses Windows)

**Comment by jdoliner** [comment]
I think the easiest thing to do here would be to always print the URL. It seems like reasonable UX to always alert the user which page they're being redirected to and if it fails then they'll have the URL right there.

**Comment by PFedak** [comment]
The URL is already printed, the real issue was not understanding what exactly was failing - the command was actually exiting on an error when it failed to open a browser, which doesn't really make sense.
