### ISSUE TITLE
pachctl list repo should sort access levels

### ISSUE THREAD

**Issue by jrockway** [pachyderm/pachyderm#6320]
All three of these repos have the same access level, but it's not obvious that that's the case with a quick scan:

![Capture](https://user-images.githubusercontent.com/2367/121740731-885e8600-cacb-11eb-8dc6-46410cdafe25.PNG)

If we sort the access levels, then it would be quicker to see that they're actually the same.

(If the order matters, then we can't sort... but those three repos were not intentionally created with different permissions.)

Found during gameday in a couple rooms.

**Comment by jdoliner** [comment]
Closed by #6336
