### ISSUE TITLE
`pachctl list datum -f` doesn't work in pachyderm 2.0

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6322]
From the [Joins example](https://github.com/pachyderm/pachyderm/tree/master/examples/joins):
![image](https://user-images.githubusercontent.com/235674/121741253-1f6b1400-cab3-11eb-9cd5-cc39742be772.png)

However, when I run that command locally, I get this error:
```
$ pc list datum -f inner_join.json
Error: unknown shorthand flag: 'f' in -f
Usage:
  pachctl list datum <pipeline>@<job> [flags]

Flags:
  -h, --help            help for datum
  -o, --output string   Output format when --raw is set: "json" or "yaml" (default "json")
      --raw             Disable pretty printing; serialize data structures to an encoding such as json or yaml

Global Flags:
      --no-color   Turn off colors.
  -v, --verbose    Output verbose logs

unknown shorthand flag: 'f' in -f
```

**Comment by jdoliner** [comment]
@acohen4 have you got bandwidth to take a look at this. I think the behavior was never hooked up in 2.0. Feel free to ping me if you want a run down of how this should work and how to approach this.

**Comment by acohen4** [comment]
@jdoliner happy to work on this :)

**Comment by acohen4** [comment]
Submitted PR to hook this back up in 2.0 : https://github.com/pachyderm/pachyderm/pull/6355
Closing this issue.

cc @jdoliner @msteffen
