### ISSUE TITLE
Output of inner_join pipeline in joins demo changed in 2.0

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6324]
Due to 2.0's new merge semantics, the output of the inner_join pipeline (in the [joins demo](https://github.com/pachyderm/pachyderm/tree/master/examples/joins)) is different:

**1.x output**
```
$ pachctl list file inner_join@master
NAME       TYPE SIZE
/02108.txt file 314B
/90210.txt file 308B
```

**2.x output**
```
$ pc list file inner_join@master
NAME       TYPE SIZE
/02108.txt file 105B
/02108.txt file 105B
/02108.txt file 104B
/90210.txt file 102B
/90210.txt file 104B
/90210.txt file 102B
```
One usability/comprehension note: it took us a second to realize that this was showing us two paths, instead of six

`get file` output is the same, though:
```
$ pc get file inner_join@master:/02108.txt

Purchase at store: 1 - washington st.
ORDER_HEADER|W080521|2020-10-10
SKU|2002|QTY|1|UNIT_PRICE|250.00

Purchase at store: 1 - washington st.
ORDER_HEADER|W080520|2020-10-10
SKU|1001|QTY|2|UNIT_PRICE|100.00

Purchase at store: 2 - hollywood bvd.
ORDER_HEADER|W078929|2020-10-10
SKU|0615|QTY|1|UNIT_PRICE|75.00
```

**Comment by brendoncarroll** [comment]
The output of list file is correct.  We need to add a column for tags because those all came from different datums, and have different tags.

I'm not sure why GetFile is concatenating everything, that shouldn't happen anymore.  Those should all be separate files in a sub-directory.

**Comment by brendoncarroll** [comment]
Talked with @brycemcanally about this some

To close this issue:
- Display tags in `list file`.
- Add `GetFile` API call which gets a single file or errors.  The command line should use that instead of `GetFileTAR`

**Comment by jdoliner** [comment]
@brendoncarroll do you have bandwidth to implement the fix?

**Comment by brendoncarroll** [comment]
I don't think I can get this done before the next alpha goes out tomorrow.  I can probably finish it before the end of the week.  It will push back the pg_bouncer integration work I have next.

**Comment by nitinjainsj** [comment]
We display tags for the files
