### ISSUE TITLE
Edit pipeline errors in 2.0

### ISSUE THREAD

**Issue by JimmyWhitaker** [pachyderm/pachyderm#6330]
In the Iris example, when running `pachctl edit pipeline inference` the command errors with: 
`Subcommand required`

**Comment by Tryneus** [comment]
It appears that `pachctl edit pipeline` was removed (but the top-level `edit` verb was left in) - do we need to add it back or should we just remove `pachctl edit`?

**Comment by jdoliner** [comment]
I think `pachctl edit pipeline` is a nice to have and shouldn't be too hard to keep. I think `extract pipeline` still works (it kind of has to because `extract` still works in general) so this shouldn't be too hard to hook up.
