### ISSUE TITLE
`pachctl list commit` returns size column of 0B - tested on opencv / 2.0.0-alpha.21 

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6351]
On 2.0.0-alpha.21 - OpenCV example

`pachctl list commit images`, `pachctl list commit edges`,  and `pachctl list commit montage` all return empty sizes.
<img width="559" alt="Screen Shot 2021-06-15 at 4 59 47 PM" src="https://user-images.githubusercontent.com/5490706/122122669-1b186100-cdfb-11eb-90cb-71d0e81d3a25.png">

Note: If those sizes can't be updated as part of the list commit, then this column should be removed and exposed with a flag.

**Comment by brycemcanally** [comment]
This should be addressed in the current alpha.
