### ISSUE TITLE
Opencv on  2.0.0-alpha.21 - Description of commit whose job failed marked as (empty) in `pachctl list commit montage`

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6352]
on  2.0.0-alpha.21 - opencv example.

After a 'make opencv':

- the description column of `pachctl list commit images` and `pachctl list commit edges` is empty, even for the empty commits.
<img width="553" alt="Screen Shot 2021-06-15 at 5 08 30 PM" src="https://user-images.githubusercontent.com/5490706/122123717-51a2ab80-cdfc-11eb-8ff1-55857440df1e.png">

- whereas `pachctl list commit montage` shows the string (empty) in the description column of the job that failed. See [#6339](https://github.com/pachyderm/pachyderm/issues/6339)
<img width="1049" alt="Screen Shot 2021-06-15 at 5 11 05 PM" src="https://user-images.githubusercontent.com/5490706/122124121-d7bef200-cdfc-11eb-8dbc-58c88da4997c.png">

This is a confusing message (`(empty)`) and a confusing location (the description column) from a user perspective as it so happens that the given commit on which the description is marked as `(empty)` is also an empty commit. The empty commits from the repo images are not labeled as empty... We might want to find a different location to display the failure of the job info as well as a different wording.

**Comment by brycemcanally** [comment]
This should be addressed in the current alpha (https://github.com/pachyderm/pachyderm/pull/6427)
