### ISSUE TITLE
undefined proto.RegisterFile

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#636]
`pachyderm/src/client/pkg/shard/shard.pb.go:335: undefined: proto.RegisterFile`

When trying to use the go library after pulling master this morning.

**Comment by jdoliner** [comment]
Hey @erikreppel this is due to some go libraries being updated. I think to fix this all you have to do is:

```shell
go get -u google.golang.org/grpc
go get -u github.com/golang/protobuf
go get -u go.pedge.io/proto/...
```

**Comment by jdoliner** [comment]
@erikreppel did that make the issue go away?

**Comment by erikreppel** [comment]
@jdoliner Yup! 

It was actually an error caused by not vendoring grpc properly, I was getting `panic: http: multiple registrations for /debug/requests` here too, for some reason Godeps didnt like updating the vendored version of grpc but deleting my vendor folder and updating grpc on my GOPATH worked.
