### ISSUE TITLE
Potential issue with pachctl diff file wrapper

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#6364]
We are seeing an error when attempting basic usage of pachctl diff file: `pattern contains path separator`. Need to take a pass over this wrapper to ensure it is functioning correctly with 2.0. In general, we need more comprehensive automated testing of pachctl because several issues that have popped up through game days are related to issues with pachctl rather than underlying issues with the Go client or backend.

**Comment by acohen4** [comment]
Closing with merge of fix: #6446
