### ISSUE TITLE
Pachctl create branch related issues

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#6365]
For pachctl create branch, when using the head flag, you have to specify the head as `repo@branch` instead of just `branch`. We should allow just specifying the branch and filling in the repo based on the first parameter. Also, create branch currently allows setting the head to a branch in a different repo which we should disallow.

**Comment by brendoncarroll** [comment]
Also ran into this in the market-sentiment example.

@JimmyWhitaker depending on the resolution here this may need to be updated
```pachctl create branch financial_phrase_bank@v1 --head master
```

**Comment by acohen4** [comment]
the updated behavior in https://github.com/pachyderm/pachyderm/pull/6399 allows passing a branch / commit-id as the `head` value, or passing the fully qualified commit ID: <repo>@ <branch>=<commit-id>. 

The fully qualified commit format is only necessary in the edge case where there may be multiple commits in a repo for the commit-set-id (up to one per repo branch). For example, commit-set-id `id-2` may be in both data@master and data@test, in which case we need the user to provide that repo@branch info to determine which exact commit to branch off of. 

@nitinjainsj @Tryneus @brycemcanally @brendoncarroll

**Comment by acohen4** [comment]
This issue is fixed as mentioned in the comment above
