### ISSUE TITLE
Diff File empty. Prints "pattern contains path separator"

### ISSUE THREAD

**Issue by brendoncarroll** [pachyderm/pachyderm#6369]
**What happened?**:
This is in the market-sentiment example.  Same repo different files (note the different sizes)
```
➜  market-sentiment git:(master) ✗ pachctl inspect file financial_phrase_bank@v2
Path: /
Tag:
Type: dir
Size: 292.6KiB
➜  market-sentiment git:(master) ✗ pachctl inspect file financial_phrase_bank@v1
Path: /
Tag:
Type: dir
Size: 655.6KiB
➜  market-sentiment git:(master) ✗ pachctl diff file financial_phrase_bank@v1 financial_phrase_bank@v2
pattern contains path separator
```

How to reproduce
Create two branches in the same repo, put different files at the same path, diff them.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Alpha 23
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Hub
- OS (e.g. from /etc/os-release):
macOS
- Others:

**Comment by brycemcanally** [comment]
Similar issue here: https://github.com/pachyderm/pachyderm/issues/6364
