### ISSUE TITLE
`pachctl wait commit` with `--raw` prints the header after raw output.

### ISSUE THREAD

**Issue by brendoncarroll** [pachyderm/pachyderm#6371]
**What happened?**:
```
➜  market-sentiment git:(master) ✗ pachctl wait commit financial_phrase_bank@v1 --raw
{
  "commit": {
    "branch": {
      "repo": {
        "name": "financial_phrase_bank",
        "type": "user"
      },
      "name": "v1"
    },
    "id": "586ebfa5a325441cbcf2ba7341a37819"
  },
  "origin": {
    "kind": "ALIAS"
  },
  "parentCommit": {
    "branch": {
      "repo": {
        "name": "financial_phrase_bank",
        "type": "user"
      },
      "name": "master"
    },
    "id": "586ebfa5a325441cbcf2ba7341a37819"
  },
  "started": "2021-06-17T18:45:28.268368454Z",
  "finished": "2021-06-17T18:45:28.268368454Z",
  "sizeBytes": "671355"
}REPO BRANCH COMMIT FINISHED SIZE DESCRIPTION
```

**What you expected to happen?**:
That same output, but without the trailing header.

**How to reproduce it (as minimally and precisely as possible)?**:
I think this applies to `--raw` on any command.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
Alpha 23
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Hub
- OS (e.g. from /etc/os-release):
macOS
- Others:

**Comment by Tryneus** [comment]
This appears to have already been fixed in `master`.
