### ISSUE TITLE
Hook godoc update into release script

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#638]
As part of our release task, we should hit the 'refresh' button on godocs for our documentation. This has to be done after the latest stuff is pushed and available on GH / master.

**Comment by jdoliner** [comment]
@sjezewski thinking about this more is there really any point? Whatever we accomplish by requesting the new version of the docs will be accomplished by the first user who requests the docs. Which is also the first time the fact that we requested them could be seen by someone.

**Comment by sjezewski** [comment]
Interesting - I wasn't sure if it would refresh when hit, so I double checked. At the bottom of their page they have:

```
Package client imports 10 packages (graph). Updated a day ago. Refresh now. Tools for package owners.
```

The presence of the button tells me that it doesn't refresh when a user hits it. But as long as it can't get older than a day, then yea I say no need to automate. If its longer than that, it would be nice to hit 'refresh' so that they stay up to date.

**Comment by sjezewski** [comment]
Ok, after the 1.2 release it seemed to digest the changes properly.
