### ISSUE TITLE
Exception when running Fruit Stand

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#640]
Hello, I am deploying pachyderm on local kubernetes. The deployment is successful without error report. Then I try to use the Fruit Stand to test whether it works.

First, when I write the example to pfs,  Pachyderm report an error:
`cat examples/fruit_stand/set1.txt > ~/pfs/data/b11fc97a24e14d5aa106bdcd39980cc4/sales`
`2016-07-11T04:23:52Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"data"},"id":"b11fc97a24e14d5aa106bdcd39980cc4"}},"write":true,"shard":{"fileModulus":"1","blockModulus":"1"}},"name":"sales","err":"no such file or directory"}`

Then, I ignore the error as the quickstart guide says. Then after I commit the data, I can see the fruit data in document sales.
`cat ~/pfs/data/b11fc97a24e14d5aa106bdcd39980cc4/sales`
`orange  4`
`banana  2`
`banana  9`
`orange  9`
`apple   6`
`orange  4`
`... ...`
It seems to be a correct result.

I continue the quickstartguide. 
`pachctl create-pipeline -f examples/fruit_stand/pipeline.json`
nothing happens. And I try to verify the result. A fatal error happens this time.
`pachctl list-job`
`Error from InspectJob: grpc: failed to unmarshal the received message proto: bad wiretype for field google_protobuf.Timestamp.Seconds: got wiretype 2, want 0`

I use another method to bulid the pipeline
`pachctl create-pipeline examples/fruit_stand/pipeline.json`
`Reading from stdin.`
And then no response.

When I stop the process, the dictory /pfs/sum existed, but no file exists in it.

**Comment by ShengjieLuo** [comment]
I doubt that if there is error in reading input. Also I try to find the log of pachyderm, but fail to find the log file. Could anyone help me for this problem? Thanks. @derekchiang @jdoliner

**Comment by ShengjieLuo** [comment]
Issue #605 share similiars problem with mine. I will try to match the version problem first.

**Comment by ShengjieLuo** [comment]
i have checked my version again. The kubenetes version and kubectl version are both 1.3.0 following the guide here [http://kubernetes.io/docs/getting-started-guides/docker/](url)
The kubernetes used in the pachyderm source code is Kubernetes 1.2.2.
Is it a matter to use v1.3.0?
If I use v1.3.0, I will not use the command `make launch-kube`, and directly execute command `make launch`. 
Or I try to use `make launch-kube` to install 1.2.2 version, the process lasts for a long time without any response, usually more than one hour, therefore I have to use the 1.3.0 version.

**Comment by sjezewski** [comment]
Hi there!

1) You're correct, that first error:

```
2016-07-11T04:23:52Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"data"},"id":"b11fc97a24e14d5aa106bdcd39980cc4"}},"write":true,"shard":{"fileModulus":"1","blockModulus":"1"}},"name":"sales","err":"no such file or directory"}
```

Is totally normal. You can safely ignore it.

2) The first command you used to create the pipeline should have worked. When creating the pipeline, Pachyderm will also create the corresponding `filter` and `sum` repos.

The error you see here: 

```
Error from InspectJob: grpc: failed to unmarshal the received message proto: bad wiretype for field google_protobuf.Timestamp.Seconds: got wiretype 2, want 0
```

Happens when you're pachyderm client (pachctl) and pachyderm server (pachd) are running incompatible versions. We recently made an update that requires you to use the latest version.

So please, make sure you have the latest code on master, then do:

- reinstall pachctl (from source / homebrew / deb package ... however you did it the first time)
- `make clean-launch` and `make launch` to update your Pachyderm server

Then `pachctl version` should report the latest versions for both client and server:

```
$ pachctl version
COMPONENT           VERSION             
pachctl             1.1.0               
pachd               1.1.0  
```

Once you have reached this state, running the example should work just fine.

**Comment by ShengjieLuo** [comment]
I have checked my pachyderm version. That's true I use the oldder version
`COMPONENT           VERSION`
`pachctl             1.0.1-3ef7e74acf7074e38c350c8c19c71243f5e9ffc8`
`pachd               1.0.1-1433`

I will change it to the new version soon. Keep contact and see whether the new version works.

**Comment by ShengjieLuo** [comment]
@sjezewski @jdoliner  Hi, the deployment problem has been solved. I update Pachyderm to version 1.1.0, and it works to the previous problem. The error message mentioned above doesn't occur this time. Thanks a lot.

**Comment by jdoliner** [comment]
@ShengjieLuo glad it worked!! Closing.
