### ISSUE TITLE
Pipeline in inner_join example crashes on 2.0.0-alpha.24

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6425]
in the joins examples https://github.com/pachyderm/pachyderm/tree/master/examples/joins:

- `make setup`
- `make create`
- `pachctl create pipeline -f inner_join.json` (make sure that you have updated the tag of the image to 2.0)
->>`"transform": {
  "cmd": [ "python", "inner/main.py" ],
  "image": "pachyderm/example-joins-inner-outer:2.0"
}`

`pachctl list pipeline`
>>NAME       VERSION INPUT CREATED STATE / LAST JOB  DESCRIPTION
outer_join -       -     -       running / failure pipeline details unavailable

`pachctl list job`
>>ID                               PIPELINE   STARTED           DURATION  RESTART PROGRESS  DL   UL STATE
883a018b28004ec0a8852c85b5d2fa99 outer_join About an hour ago 7 seconds 0       0 + 0 / 7 760B 0B failure: datum 8c2ba186bd32e96600a...

`pachctl logs --job=outer_join@883a018b28004ec0a8852c85b5d2fa99`
>>python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory
python: can't open file '//outer/main.py': [Errno 2] No such file or directory

**Comment by PFedak** [comment]
Looks like this is a side effect of #6397, which removed docker entirely from our worker image. As a result, we explicitly run pipeline code from the `working_dir` in the pipeline spec (if it's empty, that means `/`) instead of letting the container default take over (which I assume comes from WORKDIR in the Dockerfile).

**Comment by actgardner** [comment]
Taking a look at this, one thing to note is the `pachyderm/example-joins-inner-outer:2.0` image in DockerHub seems to be ARM and not x86_64 :(
