### ISSUE TITLE
How to comprehend the image 'fruitstand'

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#646]
As the first example says, the pipeline's component uses the image 'fruitstand'. 
` "transform": {`
`    "image": "fruit_stand",`
`    "cmd": [ "sh" ],`
` ... ...`

However, I don't run the 'fruit stand' image manually or install the image previously, but when I run the example, the image run successfully. So my question is where the image 'fruitstand' positioned and how it works properly. Is the image related to the file `/examples/fruit_stand/Dockerfile` ?

By contrast, in another example 'word_count',  we use 'pachyderm/job_shim' automatically, but program the image 'wordcount_map' based on local file 'map.go' and docker. So there are two methods to establish the image, one seems from the installation file, the other from GO file locally.  Is it a correct assertion?

**Comment by jdoliner** [comment]
The `fruit_stand` image gets built when you do `make docker-build`.
It's built from the `Dockerfile` you mentioned.

There's two methods for establishing the container in that you can specify it or leave it blank in which case the default `pachyderm/job_shim` is used. There's nothing special about the `map.go` file, it's just a file that gets put in a container, it could just as easily be written in ruby.

Hope this clears things up.

**Comment by jdoliner** [comment]
Also it doesn't look there's something actionable here to fix so I'm going to close this issue. Feel free to keep using it for questions though.

**Comment by ShengjieLuo** [comment]
Thanks for your help. My team is working on  Pachyderm to establish a big data analysis platform.
This process will help us to explore the possibilities of using the Container as the primitive unit in big data analyzing.
Also I wish to go into the Pachyderm project further, and have a deep understanding of the core implement.
Wish to have the opportunities contributing for the project.

BTW, the latest version's manual is much clearer and more useful than the prior version. Thanks for your work!

----- �������� -----
������: "Joe Doliner" <notifications@github.com>
������: "pachyderm/pachyderm" <pachyderm@noreply.github.com>
����: "Luo Shengjie" <luoshengjie@sjtu.edu.cn>, "Author" <author@noreply.github.com>
��������: ������, 2016�� 7 �� 14�� ���� 1:14:34
����: Re: [pachyderm/pachyderm] How to comprehend the image 'fruitstand' (#646)

Also it doesn't look there's something actionable here to fix so I'm going to close this issue. Feel free to keep using it for questions though.

---
