### ISSUE TITLE
pachctl deploy amazon instructs user to use --iam-role flag when that flag has been removed

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6499]
**What happened?**:

```
$  pachctl deploy amazon ${AWS_REGION} ${STORAGE_SIZE}  --dynamic-etcd-nodes 1 --dry-run
WARNING: The version of Pachyderm you are deploying (2.0.0-beta.1) is an unstable pre-release build and may not support data migration.

Are you sure you want to do this? (y/N): y
got confirm result: y

one of --credentials, or --iam-role needs to be provided
```

**What you expected to happen?**:

It should have prompted with instructions on how to use --credentials

**How to reproduce it (as minimally and precisely as possible)?**:

See above.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by chainlink** [comment]
This will be closed when we fully deprecate pachctl deploy
