### ISSUE TITLE
pachctl deploy "got confirm result" should go to stderr

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6501]
**What happened?**:

If you run `pachctl deploy` with the `--dry-run` flag on a pre release that requires confirmation from the user that it is a prerelease,  and pipe the results to a file for later deployment, the text

```
got confirm result: y

```

will appear at the beginning of the deployment manifests, requiring the use to edit them before use.  It also means that a direct pipe to jq or kubectl will fail.

```
$ pachctl deploy amazon ${AWS_REGION} ${STORAGE_SIZE}  --dynamic-etcd-nodes 1 --namespace pachyderm-enterprise  --credentials "redacted,redacted" --enterprise-server --dry-run -o yaml  > enterprise-2.0.0-beta.1.yaml
WARNING: The version of Pachyderm you are deploying (2.0.0-beta.1) is an unstable pre-release build and may not support data migration.

Are you sure you want to do this? (y/N): y

$ head enterprise-2.0.0-beta.1.yaml
got confirm result: y

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm
  namespace: pachyderm-enterprise
---
```

**What you expected to happen?**:

`--dry-run` should give me a clean manifest to stdout.

**How to reproduce it (as minimally and precisely as possible)?**:

Run `pachctl deploy` on a prerelease where the warning is given.   See above for an example.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by nitinjainsj** [comment]
pachctl deploy is going away in 2.0.
