### ISSUE TITLE
Helm chart auth setup notes don't work/are unclear

### ISSUE THREAD

**Issue by tybritten** [pachyderm/pachyderm#6503]
https://github.com/pachyderm/pachyderm/blob/master/etc/helm/pachyderm/templates/NOTES.txt#L6-L23

1) Needs more detail (or doc/readme link) about setting up idp
2) the `cat <<EOF` doesn't work. Needs to be:
```
pachctl idp update-client --config -<<EOF
{
  "id": "pachd",
   "trusted_peers": ["dash"]
}
EOF
``` etc
3) the `{{ .Values.dash.host }}` is not correct

**Comment by chainlink** [comment]
Related Doc: https://docs.google.com/document/d/17MFcNywJmb5TDc5oFK6rZLjCNlYAhEHDGeiRdHED2Gc/edit

**Comment by chainlink** [comment]
https://github.com/pachyderm/pachyderm/pull/6584
