### ISSUE TITLE
Support Delayed Execution

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#651]
Right now pipelines just run, they always try to keep their outputs as up-to-date with their inputs as possible. In the future I suspect there will be use cases for pipelines that delay their execution. For example you might delay so that you can wait for spot instances to become cheap or because the pipeline isn't incremental and you know more data is coming. We shouldn't implement this until we understand these use cases a bit more.

**Comment by gabrielgrant** [comment]
Related to #2296 and #252

**Comment by jdoliner** [comment]
I'm just going to close this since I think what it's describing is pretty well satisfied by our current deferred processing model and the other things we might want to do in regard to this functionality are better described by the issues you linked.
