### ISSUE TITLE
"no pods found for app pachd" when using pachyderm enterprise

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#6511]
**What happened?**:
I am trying to deploy pachyderm enterprise version of the pachyderm 2.0.0 beta. Deploying the community version works well. However with the enterprise version, all the pods come up successfully, but any attempt to communicate with the pachd service such as `pachd version` results in a `no pods found for app pachd`.

**What you expected to happen?**:
Communication with the pachd enterprise service should work as expected.

**How to reproduce it (as minimally and precisely as possible)?**:
Deploy with pachctl deploy and a `--enterprise-server` flag.

**Environment?**:
- Kubernetes version (use `kubectl version`):
AKS 1.20.7
- Pachyderm CLI and pachd server version (use `pachctl version`):
2.0.0 Beta 1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Azure

[AB#171](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/171)

**Comment by chainlink** [comment]
This should be addressed with the move to the helm chart
