### ISSUE TITLE
Allow updating pipelines

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#652]
The process for iterating on pipelines is too cumbersome right now. Updating requires deleting the pipeline and output repo and then doing a fresh create. We can wrap all of this up into a single command, however rather than adding an `UpdatePipeline` rpc and corresponding command to pachctl I think we're better off making it a flag on `CreatePipeline` since updating a pipeline should always take the same arguments as creating one and return the same things as well. Although currently `CreatePipeline` doesn't return anything.

There are a couple of interesting design questions we've hit while talking about `UpdatePipeline`:

1. What should happen to the existing data from jobs spawned by the last version of the pipeline and how does this impact the semantics of `FlushCommit`?
2. What happens with downstream data?

### 1. What happens to existing data, how does this affect `FlushCommit`?

From speaking to customers we know that there's a need for the old data to persist. They expect to be able to hand out commit IDs and have them provide access to the data forever. This means we can't do the easy thing and just blow away the old data. However I think it's very likely that there will be times when you just want to blow away the old data, for example when you're developing a new pipeline and iterating rapidly. I propose a flag called, `Purge` which would default to `false` but when set to `true` would tell Pachyderm that the user wants the old data cleaned up.

The next question is how does this affect `FlushCommit`. The issue is this: `FlushCommit` works by first using repo provenance to figure out which repos could wind up with commits for which the flushed commits are provenant. Then it uses `ListCommit` to wait for those commits to show up. This all assumes that there will only be a single commit which is provenant. When the pipeline gets redeployed it'll reprocess all the commits it previously processed creating a second provenant commit. This second commit is probably going to be the one that users are after when they call `FlushCommit`, however as the implementation stands the first commit will be returned so we need some way to distinguish it.

Another similar, but simpler issue is that right now you can go into a pipeline's output repo and do `ListCommit` to see all of the things the repo has outputted, with this scheme you won't be able to be sure that the data you're seeing is from the current version of the pipeline that seems problematic to me. At best it introduces an extra overhead to exploration but even worse it's likely to confuse people who are new to the system and might act on this data thinking it's from the current pipeline.

I think we can fix both of these issues by introducing the concept of archived commits. Archived commits are just like normal commits except they don't show up in `ListCommit` and thus don't show up in `FlushCommit` either. I'm thinking we'd implement this almost identically to cancelled commits with a bool field on `CommitInfo`. The 1 difference is that while cancelled commits are shown in mounts by default I don't think archived commits should be due to the fear of confusing people I discussed above. Finally I don't think that archiving on update should be optional, I think it's a nice invariant that pipelines output repos only ever contain data that was created by the present version of the pipeline.

### 2. What happens with downstream data?
When a pipeline is updated all of the downstream pipelines will need to be rerun as well. @JoeyZwicker and I had an offline discussion about this in which he expressed concern that this might be a huge amount of computation that needs to happen and we considered an implementation in which there was a way to update a pipeline but not trigger everything downstream. Ultimately we decided against that because it seems that in most cases users will just want everything to run so they can access results ASAP. There will probably be use case that come up later where users won't want that, however I think that this aren't really specific to `UpdatePipeline` users might just as well be worried about creating a massive pipeline and having it launch of a huge number of jobs. I'm going to remove this question from the scope of this issue, I've opened #651 to track it.

**Comment by derekchiang** [comment]
@jdoliner can this issue be closed now that #694 has landed?

**Comment by jdoliner** [comment]
You know I believe it can be.
