### ISSUE TITLE
Resumable downloads in pachctl get file

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/pachyderm#6536]
**What is the goal / desired outcome?**

If there's a network glitch or pachd restarts while a large file is downloaded via `pachctl get file` currently the experience is a frustrating failure. This is especially annoying for long slow downloads.

**If there is a way to accomplish this today via workaround, what does that require?**

Currently it can be achieved by using the S3 gateway in conjunction with `wget -c --timeout=1 --tries=5 --retry-connrefused`:

```
luke@mind:~$ (sleep 5; kubectl delete po -l app=pachd) &
[1] 189910
luke@mind:~$ wget -c --timeout=1 --tries=5 --retry-connrefused 192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
--2021-07-15 13:11:07--  http://192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
Connecting to 192.168.39.50:30600... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1215168512 (1.1G) [application/octet-stream]
Saving to: 'ubuntu-20.04.2-live-server-amd64.iso'
ubuntu-20.04.2-live-server-amd64.iso                  27%[===============================>                                                                                      ] 324.01M   105MB/s    eta 8s     pod "pachd-6b9f84b767-rr5sv" deleted
ubuntu-20.04.2-live-server-amd64.iso                  29%[==================================>                                                                                   ] 346.00M   107MB/s    in 3.2s    
2021-07-15 13:11:11 (107 MB/s) - Connection closed at byte 362807296. Retrying.
--2021-07-15 13:11:12--  (try: 2)  http://192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
Connecting to 192.168.39.50:30600... failed: Connection refused.
Retrying.
--2021-07-15 13:11:14--  (try: 3)  http://192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
Connecting to 192.168.39.50:30600... failed: Connection refused.
Retrying.
--2021-07-15 13:11:17--  (try: 4)  http://192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
Connecting to 192.168.39.50:30600... failed: Connection refused.
Retrying.
--2021-07-15 13:11:21--  (try: 5)  http://192.168.39.50:30600/master.foo/ubuntu-20.04.2-live-server-amd64.iso
Connecting to 192.168.39.50:30600... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1215168512 (1.1G), 852361216 (813M) remaining [application/octet-stream]
Saving to: 'ubuntu-20.04.2-live-server-amd64.iso'
ubuntu-20.04.2-live-server-amd64.iso                 100%[+++++++++++++++++++++++++++++++++++==================================================================================>]   1.13G   105MB/s    in 7.9s    
2021-07-15 13:11:29 (103 MB/s) - 'ubuntu-20.04.2-live-server-amd64.iso' saved [1215168512/1215168512]
[1]+  Done                    ( sleep 5; kubectl delete po -l app=pachd )
luke@mind:~$ md5sum ubuntu-20.04.2-live-server-amd64.iso 
aba7e22636c435c5008f5d059ae69a62  ubuntu-20.04.2-live-server-amd64.iso
```

This command can also be re-run as many times as needed until the file is successfully downloaded, it will resume from where it left off each time.

**(Optional) What is your proposal for a feature to solve this?**

`pachctl get file` should copy the behavior of `wget -c --timeout=1 --tries=5 --retry-connrefused`. See the `wget` manpage for description of the behavior of those options.

**Comment by jdoliner** [comment]
A few things we need to do for this:

- [ ] 1.x has all this functionality but it's not exposed in pachctl, that should be fairly easy to add since it's just punching through a flag.
- [ ] For 2.0 this is a bigger lift since it's not implemented at the api level.

I'm going to add this to both projects for tracking.

@acohen4 tagging you on this since you're oncall, feel free to reassign if you don't have bandwidth for this one it's a little bit outside of your wheelhouse.

**Comment by acohen4** [comment]
I'll make the change for 1.x. 

I'm happy to take on the 2.x change but will sync up on it with @brendoncarroll and defer to his better judgment on how to best execute it

**Comment by brendoncarroll** [comment]
@acohen4 and I talked about this briefly offline.  This needs to be added to GetFile not GetFileTAR.  It's not clear what an offset means in the context of a TAR stream.  An offset into the whole stream itself vs. each file in the stream is offset, vs. one file in the stream is offset, but the others aren't.

The GetFile change might also require some changes to the storage layer.  It is efficient to seek into a file, but we don't expose any way of doing it right now.  It would probably best be implemented as an option to `fileset.File.Content`

**Comment by acohen4** [comment]
In both 1.13.4 & 2.0, we can now 'resume' a partially completed `pachctl get file` command by passing the `--retry` flag
