### ISSUE TITLE
Examples for 'design goals' under PPS section

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#656]
[On this page](http://pachyderm.readthedocs.io/en/latest/pachyderm_pipeline_system.html) we list what PPS is designed for. 

Those are reasonably common use cases, so it would be nice to provide examples / walk throughs on each.

**Comment by dwhitena** [comment]
Irrelevant until PPS/PFS docs are brought back to life.  Tracked here: https://github.com/pachyderm/pachyderm/issues/1869
