### ISSUE TITLE
Example for SQL adapter

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#657]
[We mention this as a possibility under this section](http://pachyderm.readthedocs.io/en/latest/deploying.html#inputting-data-into-pfs) and should provide an example.

This is commonly asked for.

**Comment by sjezewski** [comment]
Ideally should include:

- 'dump' case ... where you input all the data in a table into a single commit
- 'update' case ... where additionally on subsequent runs, it dumps the things in the DB that were added since the last commit (since we don't support line-diffs we can't semantically support rows that were updated, though you could always re-dump everything)

**Comment by JoeyZwicker** [comment]
@dwhitena I think we've talked about adding this as a cookbook multiple times.We got stuck trying work on it during 1.6, but might be worth revisiting. We have a lot of users who are starting and ending with SQL data and we'd like to give them a best practices usage pattern.

**Comment by dwhitena** [comment]
Yeah, I can revisit this release cycle @JoeyZwicker.

**Comment by dwhitena** [comment]
I'm changing this issue to track a SQL cookbook, as I think this is what @JoeyZwicker and I have discussed. Also, I'm moving this off of the 1.7 milestone, as I don't think it is high priority.

**Comment by gabrielgrant** [comment]
related: #3066

also, it's kinda old, but started documenting some possible patterns here: https://github.com/gabrielgrant/pach-postgres-demo

**Comment by mindthevirt** [comment]
Referenced in #243

**Comment by nadegepepin** [comment]
Covered in https://github.com/pachyderm/pachyderm/pull/7268
