### ISSUE TITLE
pachctl put file Failing on Large File

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6571]
This is on Beta 2.

I am attempting to upload a file that is approximately 2 GiB in size using pachctl put file.  However, the upload consistently fails after exactly 1 GiB has been uploaded.  On the client side, it just says "EOF" - as if pachctl thinks it's reached the end of the file:
```
[Tue Jul 20 02:59:53]
{pach 2.0.0-beta.2 : default} / {k8s 1.16.13-dispatcher : aws} / {git 2.24.3 : customer-success/master}
~/Documents/Work/Repos ... /performance/2.0.0-beta.1 -->> pachctl put file bench@master -f storagelog-1.13.2-singledatum.log
storagelog-1.13.2-singledatum.log 1.00 GB / 1.00 GB [=================================================================================================================================] 0s 2.65 MB/s
EOF
```

Notice how it shows exactly "1.00 GB" for both the amount uploaded as well as for what it thinks the total size of the file was. This is reproducible every time for me.

The pachd logs show the following:
```
2021-07-20T19:07:23Z ERROR pfs.API.ModifyFile {"duration":422.112130988,"error":"context canceled","request":{"branch":{"repo":{"name":"bench","type":"user"},"name":"master"},"id":"f00d93be768b472a9c73bc238d63b285"},"stack":null} 
```

[AB#24](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/24)

**Comment by dgeorg42** [comment]
Note also, I don't think it's a timeout issue, for two reasons:

1. It always fails at exactly 1.00 GB, whereas I would expect some variation here if it was a timeout; and
2. On the last run I did, it failed after 7 minutes and 30 seconds, which would be a rather unusual value for a timeout. :)

**Comment by brycemcanally** [comment]
This appears to be fine on Hub with beta 2. We did have an issue before where >= 1GB size files were problematic because we would buffer that much in memory then buffer it again elsewhere, which would result with an OOM kill on the Hub machines since the memory limits are pretty low. The memory threshold now accounts for the buffering at both layers, and that appears to be resolved in Hub with beta 2, but this may be a similar issue with your environment. Is there some more information you could provide such as the memory limits and the full set of logs as well as checking if an OOM kill occurred?

**Comment by dgeorg42** [comment]
When my current set of performance tests completes, I'll reproduce this and upload the logs. There definitely were no OOM conditions being hit as none of the pods had restarted, and there were no errors in the `pachd` log other than the "context cancelled" one that I mentioned earlier.  The resource requests for the containers are set to 1 CPU and 2 GiB of memory, with no limit being explicitly set.  The nodes themselves have 32 vCPUs and 128 GiB memory.

**Comment by dgeorg42** [comment]
@brycemcanally - Here are the logs from my latest repro of this issue.

[pachd.log](https://github.com/pachyderm/pachyderm/files/6858913/pachd.log)
[postgres.log](https://github.com/pachyderm/pachyderm/files/6858914/postgres.log)
[etcd.log](https://github.com/pachyderm/pachyderm/files/6858915/etcd.log)
[pipeline-benchmarking-v1-t52gh-storage.log](https://github.com/pachyderm/pachyderm/files/6858916/pipeline-benchmarking-v1-t52gh-storage.log)
[pipeline-benchmarking-v1-t52gh-user.log](https://github.com/pachyderm/pachyderm/files/6858917/pipeline-benchmarking-v1-t52gh-user.log)

**Comment by dgeorg42** [comment]
Some additional info - it turns out that this is not limited to a single large file.  The exact same behavior occurs if you attempt with a single `put file` command to upload multiple files whose aggregate size is greater than 1 GiB.

**Comment by actgardner** [comment]
I attempted to reproduce this on Hub with beta.2, both over the internet and port-forwarding, and I wasn't able to. I'm going to try AWS + port forwarding, which is the same setup Dale is using. Dale also confirmed the same command doesn't fail with AWS + port forwarding on 1.13, on the same k8s cluster.

**Comment by dgeorg42** [comment]
This problem exists in Beta 3 as well.

**Comment by actgardner** [comment]
I'm almost certain this is an issue with port-forwarding in k8s 1.20 interacting with the way our putfile RPC works. I'm trying to upgrade a GKE cluster to 1.20 to confirm.

**Comment by actgardner** [comment]
With the most verbose logging possible in kubelet (`--v=5` for the kubelet process and `DEBUG=1` in the env), there are no errors in the kubelet. The stream opens and proxies traffic normally, then kubelet stops recieving data and waits until it times out (socat stays up during this time). 

From the pach client perspective, wireshark shows that the connection just disappears - we get 3 RST in a row with no FIN. 
The pach client connection is to the k8s master IP and not the kubelet, so it seems like the traffic must go client -> master -> kubelet -> pod. It seems like the master process itself is crashing, but it's difficult to tell in a managed k8s cluster.

There is an open k8s issue here that suggests this could actually be provoked by a specific byte sequence - considering this seems to happen deterministically based on the offset in the file being uploaded and it doesn't affect 1.13, that might be worth considering (https://github.com/kubernetes/kubernetes/issues/74551#issuecomment-600750593).

**Comment by avigil** [comment]
@dgeorg42 this just needs a kb article now

**Comment by dgeorg42** [comment]
I'm not sure how this just needs a KB article now. I mean, at this point all we've identified for certain is that:

1. Uploads of one or more files with a total file size > X will always fail after uploading exactly X bytes; 
2. The value of X varies based on some unknown factor that may or may not be connection speed (for Alysha it failed consistently at 2.1 GB, for me it was always at 1.0 GB); and
3. It's probably not a Pachyderm issue per se because the `pachctl` client just sees the connection mysteriously vanish.

But we still don't know the actual root cause, or even what to suggest as a workaround.

**Comment by dgeorg42** [comment]
Also, I'm not convinced that this is a k8s 1.20 or AWS networking issue, as Alysha has proposed. One or both of those may be contributing factors, but this issue is ONLY reproducible in 2.0.  I have tried to reproduce this in 1.13, keeping everything else the same, and have been unable to do so.

**Comment by dgeorg42** [comment]
Still unclear what the actual issue was, but this is no longer reproducible as of 2.0.0, so I'm closing this.
