### ISSUE TITLE
Link to S3 setup instructions for local deployment

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#659]
Since you can use it there as well.

**Comment by JoeyZwicker** [comment]
How do you actually set up an S3 bucket for a local deployment? `pachctl deploy local` doesn't offer an option to take S3 so users would have to update the manifest manually?

**Comment by sjezewski** [comment]
Might be helpful for having egress go to AWS, even when running code locally. I think it's just a matter of propagating the secrets through (either manually or via flags).

Since no else is asking for this, and I don't remember why I needed it, I'm closing.
