### ISSUE TITLE
Expand Metrics

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#662]
Some usage information we'd like to collect:
- job durations / states
- type of jobs (`map`/`reduce`/etc)
- parallelism of jobs
- commit states
- pipeline lifetimes (hook `delete-pipeline` to see how long they live for ... very helpful for us to understand dev cycles w pachyderm)

**Comment by sjezewski** [comment]
Also, I think we regard a session as a single pachd run. Would be nice if we could tag a user to understand development patterns.

**Comment by sjezewski** [comment]
To be clear - right now a session is a start of the pachd cluster (not a single pachd node)

**Comment by jdoliner** [comment]
Fixed in #5698
