### ISSUE TITLE
Issues coming from squash commit

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#6632]
**What happened?**:

Calling `pachctl squash commit` on the head of a branch leads to a few issues. `list job` will start returning errors. I believe this is already addressed by #6627. Jobs can get in a stuck state with the workers crashing due to not finding the job.

**What you expected to happen?**:

`list job` should work and workers shouldn't crash.

**How to reproduce it (as minimally and precisely as possible)?**:

Should work with any pipeline, I was using opencv. Just create a few commits then call `pachctl squash commit` on the head.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by Tryneus** [comment]
Fixed by #6627
