### ISSUE TITLE
Postgres Won't Start on Beta 4 After Uninstalling Beta 3

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6634]
I uninstalled Beta 3, and then installed Beta 4. However, Postgres is failing to start, with the following message:
```
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
It contains a lost+found directory, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```

When I uninstalled Beta 3, I did so following the same procedure that has worked in the past:

- First run `helm uninstall pachd`
- Then run `make clean-launch` from the Pachyderm Github repo

This second step says that it removed the Postgres PVC, so it's not clear to me how / why there is still Postgres data hanging around for Beta 4 to complain about.
```
persistentvolumeclaim "postgres-storage-postgres-0" deleted
```

**Comment by jdoliner** [comment]
This is something we should figure out, users are unlikely to be in this situation though so I think we can push this off to post 2.0. This also seems like it's probably a standard postgres management thing.

**Comment by brendoncarroll** [comment]
@smalyala recently encountered this issue. Deleting the persistent volume claim is a work around.

**Comment by dgeorg42** [comment]
@brendoncarroll - My problem was that the PVC _was_ in fact deleted and yet I kept getting this error.
@jdoliner - Agreed; this is an issue for post-2.0

**Comment by chainlink** [comment]
Will be addressed in https://github.com/pachyderm/pachyderm/issues/6659

**Comment by dgeorg42** [comment]
This has been resolved.
