### ISSUE TITLE
Test AzureBoards sync - please ignore and ping Tony Vigil with any questions - updated title in GH

### ISSUE THREAD

**Issue by avigil** [pachyderm/pachyderm#6635]
**Provide a link to the page with an issue:** Please ignore - this is just for testing. Updated this in Zenhub

**Describe what is wrong:**

**Describe the suggested changes:**

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

[AB#7](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/7)

**Comment by avigil** [comment]
Added a comment in github at 7:53am

**Comment by avigil** [comment]
Test comment from Zenhub

**Comment by avigil** [comment]
CORE-23 #comment comment in github intended for jira

**Comment by nadegepepin** [comment]
Closing this - This was part of the Azure Board tests -
