### ISSUE TITLE
Unclear How to Use Amazon RDS for the Postgres Server

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6639]
Because of issue #6634 I tried to set up Postgres on Amazon RDS and use that instead of the internal Postgres instance. Looking at the logs, I could see that `pg-bouncer` was connecting to my RDS instance successfully, but then it was failing because the "pachyderm" database did not exist. I was expecting that it would automatically create the database.

After several failed attempts to connect to the database, `pg-bouncer` then started trying to use the user "pachyderm" to connect, rather than the user I configured. This failed because user "pachyderm" doesn't exist on my Postgres instance.  It repeatedly tried to log in every second using this invalid user until I ran `helm uninstall`.

YAML file and logs attached:

[helm-deploy.txt](https://github.com/pachyderm/pachyderm/files/6897017/helm-deploy.txt)
[postgres-errors.log](https://github.com/pachyderm/pachyderm/files/6897018/postgres-errors.log)

**Comment by dgeorg42** [comment]
I changed the database name in my Helm chart from "pachyderm" to "postgres" ("postgres" being the name of my user account) and that got past the issue of the database not being found, EXCEPT that then it complained about not being able to find the "dex" database (which seems to be something not specified in the Helm YAML?)

So I created the "dex" database, and now everything starts up correctly.

I think there are two things here that need to be addressed:

1. Should we expect `pg-bouncer` to be able to create the "pachyderm" and "dex" databases if they don't exist? If yes, this is a bug that should be addressed (probably post-2.0).  If no, then this is a docs issue; we need to clearly document the requirements for customers who wish to use their own Postgres instance.
2. If `pg-bouncer` is unable to connect, then: a) it probably shouldn't keep trying every second forever; b) it definitely shouldn't start trying to use the "pachyderm" user account rather than the user account that was configured. Again, I think this could be fixed post-2.0

**Comment by chainlink** [comment]
For 1, I think this is probably a docs issue. In the case of self hosted postgres, the user should be responsible for setting up the user role and databases.

For 2, this is likely a bug, we likely missed a hardcoded instances of "pachyderm" in the db code.

**Comment by chainlink** [comment]
Related: https://github.com/pachyderm/pachyderm/issues/6510

**Comment by dgeorg42** [comment]
@chainlink - I agree on number 1; docs issue was the direction I was leaning as well.  For number 2, it's weird because it used the correct username for several tries before it started trying to use the "pachyderm" username. Almost like someone thought, well if the configured name doesn't work let's try the default.  Which isn't necessarily a bad fallback approach, except for the infinite retries. :)

**Comment by brendoncarroll** [comment]
It's possible that one connection path was through pg_bouncer (which passes through the user as configured), and one was direct.  One could also have been the worker, which is improperly configured.  We don't change the database configuration during any of the retry loops.

**Comment by brendoncarroll** [comment]
There are no places in the code where we call `dbutil.NewDB` without setting the user and database.  We only default when the environment variable is not set.  So it has to be an issue passing the environment variable to the worker, or getting it from the helm chart.  It could also be an issue setting up dex, which uses different environment variables.

**Comment by chainlink** [comment]
I think this could use a retest actually (I believe this was before we moved everything over to env vars)

**Comment by chainlink** [comment]
We use an external PG instance on Hub, so it should work on AWS as well

**Comment by dgeorg42** [comment]
The external PG instance works on AWS as long as:

1. The "dex" database has been created; and
2. You a.) use the default "postgres" login and "postgres" database for Pachyderm OR b.) create the specific user account and/or database you want to be used.

It's reasonable to expect the customer to set this up; we just need to make sure it gets into the docs. <-- @nadegepepin  :)

**Comment by nadegepepin** [comment]
Now that this is documented - Can we close this issue? https://docs.pachyderm.com/latest/deploy-manage/deploy/aws-deploy-pachyderm/ 

Or is there something pending still?
