### ISSUE TITLE
Problem met in the example Web Scraper

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#666]
Hi, I have a met a problem in the example Web Scraper, I guess it is led by the proxy server problem.

I follow the guide of Web Scraper.  The pachyderm job's status is running, but with no result.
`pachctl list-job`
`ID                                 OUTPUT                                             STARTED             DURATION            STATE`
`4823900e201664353385d198bd6c7b86   scraper/4cf15ae67e5d43d39177a590ea1ee876           23 minutes ago      -                   running`

`ls ./pfs5/scraper/4cf15ae67e5d43d39177a590ea1ee876/`
`Nothing in the output file folder`

It confuses me so I directly use the command in the `pipeline.json`
`wget  --recursive --level 1 --accept jpg,jpeg,png,gif,bmp  --page-requisites --adjust-extension --span-hosts --no-check-certificate  --timestamping --directory-prefix /root  --input-file /root/pfs5/urls/a996ffb34c6742a6a3368d9715330686/urls`

The command works successfully,
`--2016-07-15 12:53:52--  http://www.google.com/`
`Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.80`
`Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.80|:914... connected.`
`Proxy request sent, awaiting response... 200 OK`
`Length: unspecified [text/html]`
`Saving to: ‘/root/www.google.com/index.html’`
  `[ <=>                ] 10,427      --.-K/s   in 0.002s`

Note that my server used a proxy to connect the google.com. The proxy works in my server, but does it work in the pachyderm container as well? Do I need to review the Dockerfile used in this example to add the proxy configuration? Or  the network configuration and environment variables are shared in dockers and servers ? And if this is necessary to add the proxy configuration, would you mind tell me how to deal with it?

**Comment by ShengjieLuo** [comment]
See logs here:

`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | 2016-07-15T04:40:53Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"scraper"},"id":"4cf15ae67e5d43d39177a590ea1ee876"}},"repoAlias":"out","write":true},"name":"www.google.com","err":"no such file or directory"}`
`0 | --2016-07-15 04:40:53--  http://www.google.com/`
`0 | Resolving www.google.com (www.google.com)... 216.58.221.100, 2404:6800:4005:803::2004`
`0 | Connecting to www.google.com (www.google.com)|216.58.221.100|:80... failed: Connection timed out.`
`0 | Connecting to www.google.com (www.google.com)|2404:6800:4005:803::2004|:80... failed: Network is unreachable.`

Two problems are reported.
First Problems is there is no directory named 'www.google.com'. Similar problems happen in other examples, I used to ignore it.
Second problem is the connection timeout. The google is blocked by company network configuration. Proxy server is needed in this situation.

**Comment by ShengjieLuo** [comment]
To address this issue, I change the command in the pipeline.json as following,
`"pipeline": {`
`    "name": "scraper_export_proxy"`
`  },`
 ` "transform": {`
    `"cmd": [`
       ` "export","http_proxy=http://username:password@child-prc.intel.com:914",`
       ` "export","https_proxy=https://username:password@child-prc.intel.com:914",`
      `  "echo","$http_proxy",">","/pfs/out/test.txt",`
       ` "echo","$https_proxy",">","/pfs/out/test.txt",`
       ` "wget",`
       ` "--recursive",`
       ` "--level", "1",`
       `... ...`

Unfortunately, the change doesn't work.
See job status here,
`ID                                 OUTPUT                                                  STARTED             DURATION            STATE`
`9e172109fe3522527883473a01688ab9   scraper_export_proxy/6bada8e255f446cd8d60d6bb2ab04ec8   7 minutes ago       -                   pulling`

See logs here,
`pachctl get-logs 9e172109fe3522527883473a01688ab9`
`container "user" in pod "9e172109fe3522527883473a01688ab9-6uqeu" is waiting to start: ContainerCreating`

See kubectl status here,
`NAME                                     READY        STATUS              RESTARTS                       AGE            IP           NODE`
`9e172109fe3522527883473a01688ab9-6uqeu   0/1          ContainerCreating   0                              9m             <none>       127.0.0.1`

So this method don't works for the proxy problem.

**Comment by ShengjieLuo** [comment]
Also this problem is in the example Word Count. Besides the wget problem, in the Docker image, 
`RUN apt-get update && apt-get install -y --no-install-recommends \`
`                g++ \`
`                gcc \`
`                libc6-dev \`
`                make \`
`        curl \`
`        && rm -rf /var/lib/apt/lists/*`

The apt-get also need refine the apt-conf to affirm the proxy server.  The container cannot be established. 

See pachyderm status here,
`ID                                 OUTPUT                                                  STARTED             DURATION            STATE`
`79b18e985de343bfbea9a2bea9a97f77   wordcount_map/fc7898973a964026bf88427269b0fdd4          45 hours ago        -                   pulling`

See kubectl status here,
`NAME                                     READY        STATUS              RESTARTS                       AGE            IP           NODE`
`79b18e985de343bfbea9a2bea9a97f77-tj8n4   0/1          ImagePullBackOff    0                              1d             172.17.0.6   127.0.0.1`

**Comment by jdoliner** [comment]
Hi @ShengjieLuo, sry you ran into this.
The reason your `Cmd` isn't working is that it's not quite as smart as a shell. It's just an `exec`. To get shell like semantics you should do something like in the [fruit stand example](https://github.com/pachyderm/pachyderm/tree/master/examples/fruit_stand).
Maybe we should add an `Env` section to the `Transform` to make that experience a little better?

Also small github tip. you can do extended code snippets with 3 back ticks \`\`\`

**Comment by ShengjieLuo** [comment]
Thanks for the tips.  I would try to establish the `Env` field in the `Transform` section instead of directly exporting it.  It's my first time to contact the docker and container project, so maybe some problems are to some extent naive. Keep contact and I will modify it in Next Monday.

**Comment by ShengjieLuo** [comment]
Hi @jdoliner  I have added `ENV http_proxy  $my_proxy$` to the image and it can work now. I also mentioned that #668 planed to add the `ENV`M section in 'Transform'.  It works for this kind of problems, thanks.  You can close this issue.
