### ISSUE TITLE
Problem met in PFS mount

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#667]
We mount the Pachyderm File System (PFS) in Local File System to help debug.
However,  when I close the ssh connection and open the ssh connection next day. The PFS seems to be unmount and  I need mount the file system again with another name.

See here, the directory /pfs is mount one day before, I use the same user to ssh the server and /pfs cannot get accessible.
`ls ~`
`ls: cannot access pfs: Transport endpoint is not connected`
`drive.google.com            kubernetes       master.zip.1      time.txt                                              work
examples                    mail.google.com  pachyderm     pfs play.google.com  virtualbox-5.0_5.0.24-108355~Ubuntu~trusty_amd64.deb  www.google.com
go1.6.2.linux-amd64.tar.gz  master.zip   test.txt         wget-log`

I cannot remove the unmount directory /pfs or view the content in /pfs. Noting can be done to deal with it. I have to mount Pachyderm repo to another directory, for example /pfs2 by:
`pachctl mount pfs2 &`

In the new mount directory, the repo in /pfs still exists in /pfs2, and no file is lost. I can use /pfs2 to work normally.Is that a normal phenomenon or a operation mistake?

**Comment by jdoliner** [comment]
Hi @ShengjieLuo really sorry you hit this. We already have an issue that's scheduled for the 1.2 release, #576. I'm going to close this one in favor of that. To clean up the existing mounts you can do `umount ~/pfs`. Please feel free to keep asking questions in this issue even though it's closed.

**Comment by ShengjieLuo** [comment]
Thanks. Hope to see the new version soon.
