### ISSUE TITLE
Add Fruit Stand image to DockerHub

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#669]
From a user:

"I actually had a problem with my aws cluster setup.  Dug around the codebase a little and figured out what I was doing wrong.  I'm running pachyderm remotely on AWS and realized that the "fruit stand" image isn't on docker hub, but found the job-shim image instead."

Even though it identical to job-shim, there isn't a good reason not to have the fruit stand image on DockerHub too. In addition to removing a minor hiccup for users, it also encourages the right idea that building your own image for a specific pipeline includes `from job-shim` -- in this case thats "all_ it includes.

@sjezewski This should be just a one line addition to the deployment scripts you've built.

**Comment by jdoliner** [comment]
Closing in favor of #559.
