### ISSUE TITLE
[HELM] Mention gp2 as the default installation setting for Pachyderm's pvs and add IOPS/Disk size requirementss

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6699]
AWS: https://docs.pachyderm.com/2.0.x-beta/deploy-manage/deploy/amazon_web_services/	

gp2 is back to being the default disk type for our pvs. 
Update documentation to give users both options (given that gp3 is not the default but is the production recommendation)

	

[AB#70](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/70)

**Comment by avigil** [comment]
@nadegepepin can you verify that this is done?
