### ISSUE TITLE
Does it have the method to revise the committed data?

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#671]
As the manual says, the data before finish-commit is write-only, and the data after committed is read-only. It seems that if a set of data is committed, I have no methods to revise it. If I do need to revise an item, I must return back to the previous version and commit all data again. Is that opinion correct?

**Comment by ShengjieLuo** [comment]
For example, if for the first time I submit 40GB data, the second time I submit 20GB data, and the third time I submit 40GB data. Totally, 100GB is stored in the disk.
Now, I find one data item in the second submit need to be revised. Then is it necessary to come back to the first version, and then repeat the second and third submit? If I do need this, there will be 100GB(first branch) + 60GB(second branch) data in the disk. Is it any method to revise only one item?

**Comment by JoeyZwicker** [comment]
You can create a 4th commit where you delete the one incorrect item and add the correct one. You don't need to go all the way back and branch.

**Comment by jdoliner** [comment]
As @JoeyZwicker there's no way to modify a commit after it has been finished. This is an intentional design decision, it's important that the immutability of commits be a strict guarantee so that we have a consistent record of what the data looked like when we doing processing.
