### ISSUE TITLE
Add documentation for 2.0 directory semantics

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#6740]
In 2.0, directories are not stored in the storage format, so they will not exist unless there are files in the directory. This needs to be made clear to users through documentation because it is a pretty significant semantic change from 1.x.

[AB#99](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/99)

**Comment by nadegepepin** [comment]
Added the following in concepts/data-concepts/file/
<img width="725" alt="Screen Shot 2021-09-10 at 12 33 38 PM" src="https://user-images.githubusercontent.com/5490706/132887155-5a1c4d2f-ea9b-4616-902a-d3839514320d.png">
