### ISSUE TITLE
List commit doesn’t respect ancestry syntax

### ISSUE THREAD

**Issue by JimmyWhitaker** [pachyderm/pachyderm#6758]
**What happened?**:
List commit doesn’t respect ancestry syntax
```
$ pachctl list commit data
REPO BRANCH COMMIT                           FINISHED       SIZE ORIGIN DESCRIPTION
data master 55589fe63b3b46b19d4e8362a24e6d60 3 seconds ago  364B USER    
data master 2b8b243b5a654985a1ef6d22c6f6af72 8 seconds ago  0B   USER    
data master 619517fbf86f42a7a70c708679b89673 14 seconds ago 364B USER  
```
When you reference the previous commit, it still returns the same output. 
```
$ pachctl list commit data@master^
REPO BRANCH COMMIT                           FINISHED       SIZE ORIGIN DESCRIPTION
data master 55589fe63b3b46b19d4e8362a24e6d60 3 seconds ago  364B USER    
data master 2b8b243b5a654985a1ef6d22c6f6af72 8 seconds ago  0B   USER    
data master 619517fbf86f42a7a70c708679b89673 14 seconds ago 364B USER  
```

**What you expected to happen?**:
It should return the commits list for the commit referenced. 

**How to reproduce it (as minimally and precisely as possible)?**:

```
pachctl create repo data
touch file.txt
pachctl put file data@master -f file.txt
pachctl delete file data@master:/file.txt
pachctl put file data@master -f file.txt
pachctl list commit data@master
pachctl list commit data@master^
```

**Environment?**:
Pachyderm Hub 
```
COMPONENT           VERSION             
pachctl             2.0.0-beta.5        
pachd               2.0.0-beta.5 
```

[AB#110](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/110)

**Comment by PFedak** [comment]
What do you expect the output of this command to be? It seems like you want to use the `--from` flag, as the help text doesn't list `pachctl list commit <fully-specified-commit>`  as an option, just `pachctl list commit <branch>` and `pachctl list commit <commit-id>`.

**Comment by JimmyWhitaker** [comment]
I believe that's correct. I would expect the ID to resolve to the commit ID before passing it to the command. Otherwise we end up with some pretty gnarly pipe commands for examples. 

The behavior in 1.12.5 is: 

```
$ pachctl list commit data
REPO BRANCH COMMIT                           FINISHED       SIZE ORIGIN DESCRIPTION
data master 55589fe63b3b46b19d4e8362a24e6d60 3 seconds ago  364B USER    
data master 2b8b243b5a654985a1ef6d22c6f6af72 8 seconds ago  0B   USER    
data master 619517fbf86f42a7a70c708679b89673 14 seconds ago 364B USER  
```
And for the ancestry syntax it's:
```
$ pachctl list commit data@master^
REPO BRANCH COMMIT                           FINISHED       SIZE PROGRESS DESCRIPTION
data master 44e71eeb040e4453a13014c22c9a80ed 17 minutes ago 0B   -         
data master 4670ab8ce78e4306a5789144f30b4afd 21 minutes ago 364B -  
```

This is the same if I use any form of `data@master.1`/`data@master.-1`

**Comment by PFedak** [comment]
Ahh, I see, the actual change is that we're expecting a branch and then creating a commit. In 1.x this was all done with strings so the distinction wasn't important. It seems like we should just make this take a commit and everything should match the previous behavior.

**Comment by PFedak** [comment]
The linked PR (#6785) restores the functionality in 1.x, which might not quite match what you're requesting here.
