### ISSUE TITLE
pachy@2.0 use local-dev-values.yaml occurs Error "Values.pachd.storage.backend is required."

### ISSUE THREAD

**Issue by oosugi84** [pachyderm/pachyderm#6759]
**Provide a link to the page with an issue:**
https://github.com/pachyderm/helmchart
https://docs.pachyderm.com/2.0.x-beta/deploy-manage/deploy/helm_install/

**Describe what is wrong:**
```
% helm install pachd pach/pachyderm -f local-values.yaml 
Error: execution error at (pachyderm/templates/pachd/deployment.yaml:52:20): .Values.pachd.storage.backend is required.
% helm install pachd pach/pachyderm -f local-dev-values.yaml 
Error: execution error at (pachyderm/templates/pachd/deployment.yaml:52:20): .Values.pachd.storage.backend is required.
```

**Describe the suggested changes:**
Is there a default file for helm install like pachctl deploy?

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`): 1.21
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.0.0 beta.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS:
- Other:

[AB#112](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/112)

**Comment by tybritten** [comment]
The docs are for post-release so the version information isn't included. To install the beta now, you need to either include the `--devel` flag with the helm command or `--version pachyderm-2.0.0-beta.5` if you don't, helm will try to install the latest full release version of the chart which is currently `1.13.4`
