### ISSUE TITLE
Update spouts101 example to use python-pachyderm 7.0.0-rc1

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6775]
Currently, spouts101's requirements.txt file specifies python-pachyderm>=7.0.0. No such version currently exists in pypi. We're about to release python-pachyderm 7.0-rc1, which will fix this example for the public if we update teh requirements.txt file afterwards, so this issue tracks the need to do so after the release

[AB#119](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/119)

**Comment by nadegepepin** [comment]
v7 of python-pachyderm is now released. The requirements.txt rightfully points to >=7.0.0 now.
This issue is no longer relevant. I am closing it.
