### ISSUE TITLE
Add meaningful OpenCV use case example

### ISSUE THREAD

**Issue by SoheilSalehian** [pachyderm/pachyderm#681]
This intermediate level example's main contribution is a use case for:

- Downloading 1000 images from s3 and processing them
- How to build native opencv algorithm for pachyderm pipelines

It is to find the top 5 dominant colors of the 1000 images. Analyzing the results and/or performance comparisons will be done in separate PRs.

**Comment by jdoliner** [comment]
Example has been merged!!
