### ISSUE TITLE
Prometheus Pipeline worker stats missing

### ISSUE THREAD

**Issue by tybritten** [pachyderm/pachyderm#6811]
**What happened?**:
Using the prometheus endpoint on pipelines exposes pachd_pfs metrics (and go and grpc ones) but the expected pipeline worker ones aren't there (https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/stats/stats.go)
**What you expected to happen?**:
the documented job metrics to be there (https://docs.pachyderm.com/2.0.x-rc/deploy-manage/deploy/prometheus/job_metrics/)
**How to reproduce it (as minimally and precisely as possible)?**:
curl the /metrics endpoint of any pipeline service
**Anything else we need to know?**:
broken in 1.13 and 2.0
**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

[AB#130](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/130)

**Comment by jdoliner** [comment]
Does this bug apply to all pipelines or is it specific to pipelines with autoscaling / standby enabled. I remember there being an issue with that because the pipeline gets spun down and thus the endpoint goes away.

**Comment by tybritten** [comment]
All pipelines

**Comment by avigil** [comment]
@Tryneus assigning to you since you made the last changes on the file listed in description

**Comment by jdoliner** [comment]
Looking at release notes for 1.13 this PR looks a little bit suspicious: https://github.com/pachyderm/pachyderm/pull/5912

**Comment by Tryneus** [comment]
Fixed by #6914.

**Comment by tybritten** [comment]
Trying w RC2 and I see all the pachd/pfs stats, but still no worker stats?

**Comment by JoeyZwicker** [comment]
@tybritten do we need to reopen this issue for worker stats too?
