### ISSUE TITLE
rethink Flush semantics

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#687]
Currently `FlushCommit` will return only the downstream commits not the commit that was flushed. I think we should reconsider that for a couple of reasons.
1. I think it actually makes more sense to return it and talking to a user offline confirmed this. Anecdotal of course, but we often talk about the thing returned as a consistent snapshot so that feels like it should include the root of the tree as well.
2. It solves a weird hiccup with usage, suppose we have 2 input repos and someone flushes a commit from 1 of them. To get a consistent snapshot we have to pick a commit from the other input repo since pipelines with 2 inputs are always run with a commit from each. There's no easy way to see which commit we picked, the best you can do is check the provenance of the other commits. Returning input commit from the second repo along with the specified one from the first seems like a pretty elegant way to handle this.

**Comment by ysimonson** [comment]
`FlushCommit` now blocks on the root commit (#3478), but still doesn't return it

**Comment by jdoliner** [comment]
I think we thought about changing the semantics on this but decided to stick with what we've got. At this point it's no longer true that we select a commit on other input branches, we use the subvenance of the flushed commits, which is implicitly selecting commits on other input branches, potentially more than one per branch, which would be confusing to get back. I think we're happy with the semantics we have now, it works well for our tests and internal use cases. Users mostly use the `FlushJob` command, which doesn't have this issue because there aren't input jobs.
