### ISSUE TITLE
[Doc] Document the deployment of Pachyderm 2 on Openshift -  IBM-Cloud or On Premises

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6884]
Based on the following pages from 1.13:
- https://docs.pachyderm.com/2.0.x-rc/deploy-manage/deploy/ibmcloud-openshift/
- https://docs.pachyderm.com/2.0.x-rc/deploy-manage/deploy/openshift/#preparing-to-deploy-pachyderm 

Adapt/update the deployment of Pachyderm 2 on openshift (hosted version and on-premises) including  Helm install instructions.

Open Question: Should we also define and document how to install Notebooks and Console on Openshift in both scenarios as well?

**Comment by msteffen** [comment]
Just discussed this face-to-face, and the solution we came to is:
- Delete the old openshift docs
- If a user wants to run Pachyderm on OpenShift

**Comment by msteffen** [comment]
Reopening until the old docs are actually deleted, but hopefully that will be easy.
