### ISSUE TITLE
Console for Community Edition

### ISSUE THREAD

**Issue by jay-manday** [pachyderm/pachyderm#6916]
**What is the goal / desired outcome?**

I wanted to start a conversation exploring the possibility for a lightweight version of the console that would be available to users of the community edition. I totally understand the need for a Enterprise edition but gating console behind that might be a pretty large barrier to entry for people just starting to spin up their own pachyderm clusters.

Is there any guidance for pipeline observability without console? Could a future iteration of console make it's way over to the community edition in future releases? I feel like the lack of this might turn some adopters away.

Thanks again for looking at this.

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 2.0-rc
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
hi @jay-manday, thanks so much for the request! I'm one of the founders of Pachyderm and figured I'd chime in here. 

While there are no near-term plans to make a lightweight version on Console open source, we're always looking for ways to open source additional features so feedback like this is excellent! We recently made our [Node_Pachyderm](https://github.com/pachyderm/node-pachyderm) client available and officially supported. This is what we use for Console to interface with the pachyderm server and this hopefully helps others build their own simple dashboards around Pachyderm. 

We do have Pachyderm Hub which comes with Console and all our Enterprise features available as a much lower barrier to entry. I do understand where you're coming from though -- even Hub still isn't totally free or you may have specific requirements where you want to run Pachyderm yourself. 

When you ask about "observability without Console", can you explain more about what you mean? Are you specifically asking about visualizing the DAG shape or are there other parts of observability you're looking for such as alerts to job failures, pipeline statuses, viewing data, etc?

**Comment by jay-manday** [comment]
Hey @JoeyZwicker thanks for following up, I've been scaffolding our Pachyderm Cluster and Pipelines over at [1build](1build.com) and we've so far been pretty impressed w/ it.

The biggest concern I have is knowing when & what pipelines are failing anything more is a nice to have, after thinking about it again, I saw there are Loki and Prom integrations, we use both heavily which gives me hope that we can probably cobble some Grafana boards together. With the absence of console in the community edition, some more documentation or even examples of how people can further instrument & add alerting to their pipelines, even in a basic way I think would be helpful.


Thanks again for taking a look at this, I really appreciate it.

**Comment by JoeyZwicker** [comment]
@jay-manday you hit the nail on the head. For things like pipeline failures (pods crashing or failing to schedule on k8s) or job failures, prometheus and Loki alerts are absolutely the right approach. While Console does give a human-visual view of these, even for Enterprise Edition users, we recommend an actual alerting/monitoring system. We've purposefully designed pachyderm so it can piggy-back on existing best-in-class kubernetes tools so we're not trying to reimplement features that already exist. 

In terms of documentation & examples around using Loki and Prom, we're always looking for ways to improve there. here are our [Loki docs](https://docs.pachyderm.com/latest/deploy-manage/deploy/loki/#shipping-logs-to-loki) and [Prom docs](https://docs.pachyderm.com/latest/deploy-manage/deploy/prometheus/#monitor-your-pachyderm-cluster-with-prometheus). Any specific suggestions on more detail you'd like to see there or portions that need more clarity are always appreciated.

**Comment by JoeyZwicker** [comment]
Anytime! We love having passionate users like you as part of our community so never hesitate to get in touch with any questions, requests, or feedback!
