### ISSUE TITLE
Put GA on read the docs site

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#692]
Should be possible.

Will also help us understand / validate how people are using it

**Comment by jdoliner** [comment]
We should use either mixpanel or heap since we're already using those for this type of thing. No need to bring a third technology into the mix.

**Comment by sjezewski** [comment]
There's baked in support for GA [on the RTD dashboard for our project](https://readthedocs.org/dashboard/pachyderm/advanced/)

I'm not sure if we can inject our own JS and use their existing 'theme' (the thing that provides the basic styles / search / etc):

https://github.com/rtfd/readthedocs.org/issues/728

But it's something we can look into if we don't want to add another analytics service (which is a very reasonable thing to want).

**Comment by jdoliner** [comment]
Oh I didn't realize it was builtin support. If that's the easiest route we should just do that.

**Comment by sjezewski** [comment]
Ok, its hooked in now. Signin to GA through your gapps account to see traffic
