### ISSUE TITLE
[Helm] Make pgbouncer values configurable

### ISSUE THREAD

**Issue by echohack** [pachyderm/pachyderm#6945]
https://github.com/pachyderm/pachyderm/blob/master/etc/helm/pachyderm/templates/pgbouncer/deployment.yaml#L46

As a Pachyderm user I need to be able to edit pgbouncer values in the `values.yaml` to ensure I can continue to scale my cluster. In particular, `PGBOUNCER_MAX_CLIENT_CONN` is important to be configurable beyond 1000.

Note that `PGBOUNCER_POOL_MODE` *must* be transaction due to how pachd is working, otherwise values should be editable to my knowledge.

**Comment by tybritten** [comment]
fixed by https://github.com/pachyderm/pachyderm/pull/6952
