### ISSUE TITLE
Suggest a Revision in Makefile Section amazon-cluster

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#706]
A suggestion is given in this issue to revise the `Makefile` in order to be compatible with AWS client.

The original script would lead to a fatal error `IllegalLocationConstraintException`

```
amazon-cluster:
        #aws s3api create-bucket --bucket $(BUCKET_NAME) --region $(AWS_REGION)
        aws ec2 create-volume --size $(STORAGE_SIZE) --region $(AWS_REGION) --availability-zone $(AWS_AVAILABILITY_ZONE) --volume-type gp2
```

I suggest to revise the script to

```
amazon-cluster:
        aws s3api create-bucket --bucket $(BUCKET_NAME) --create-bucket-configuration LocationConstraint=$(AWS_REGION)
        aws ec2 create-volume --size $(STORAGE_SIZE) --region $(AWS_REGION) --availability-zone $(AWS_AVAILABILITY_ZONE) --volume-type gp2
```

The new script has been checked and it works for following process.
Similar issues are also reported to aws_cli team. The reference here (https://github.com/aws/aws-cli/issues/589)
The option used in the original script is not allowed in aws client reference. http://kubernetes.io/docs/user-guide/kubectl/kubectl_create/

**Comment by sjezewski** [comment]
merged
