### ISSUE TITLE
pachctl inspect job workflow is unintuitive

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#7065]
**What happened?**:
I did the tutorial on Pachyderm 2, had a job run then did a `pachctl list job` followed by a `pachctl inspect job <jobid>`.

This returned a `invalid format "<jobid>": expected pipeline@job-id`

The problem is that doing a `pachctl list job` shows no info about which pipelines were involved in the job. For a simple scenario such as the tutorial, it is trivial to guess that the pipeline is edges, but for a complex production scenario with multiple pipelines involved with the job, this leaves the user guessing.

**What you expected to happen?**:
I would expect a `pachctl inspect job <jobid>` to return some aggregated information about all the pipelines were involved in the job. 

Alternatively, doing a `pachctl list job` should specify which pipelines were involved with the job in a new column and maintain the `pipeline@job-id` format.

**How to reproduce it (as minimally and precisely as possible)?**:
As described above.

**Comment by PFedak** [comment]
`pachctl list job <job-id>` does some of what you want - while it just looks like a filter, it shows output more similar to `pachctl list job --expand` which has the extra column you want. It isn't literally in `name@id` format, though, could be something to consider.
