### ISSUE TITLE
Port Forwarding Problem in AWS deploy

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#707]
Hi. I meet some problems in the port forwarding, please give me some instruction to solve the problems.

The AWS client vm has a public IP `54.187.24.127`  and a private IP `172.31.5.119`. `kubectl` and `pachctl` is installed in this client instance and be used to control the cluster. I ssh to this instance from my local server.

The Kubernetes cluster (1-major-5-minor) is built. The network environment of Kubernetes Cluster is displayed as follows. Thus, I can use the client instance to control the cluster.
![image](https://cloud.githubusercontent.com/assets/20234415/17506479/c24d206c-5e3b-11e6-8a1c-a96dbe63ff12.png)
![image](https://cloud.githubusercontent.com/assets/20234415/17506531/11ece602-5e3c-11e6-9059-786528c99179.png)

Then I setup Pachyderm on this Kubernetes cluster.  The network status of Pachyderm can be read from the Kubernetes Dashboard. All pachyderm pods and services is running and distributed with a private IP.
![image](https://cloud.githubusercontent.com/assets/20234415/17506582/9eb2ea5a-5e3c-11e6-8ae8-91e45295a9c9.png)
![image](https://cloud.githubusercontent.com/assets/20234415/17506623/f2ca39cc-5e3c-11e6-86fa-73240635d803.png)

However, I cannot use the `pachctl` in client machine to communicate with the `pachd` pod. I speculate the reason is that  `pachctl` cannot find the pachyderm service location.
I think it need port forwarding to forward the info of the docker container pod to some network interfaces. However, the official guide doesn't tell me which port to forward and the forward method.

I try some options, but they don't work.
`export ADDRESS=52.41.165.87:30650`   public IP of master node
`export ADDRESS=10.0.81.183:30650`     private IP of service pachd
`export ADDRESS=172.20.0.9`                  private IP of master node

Therefore, I report this issue and ask for the help. Also the deployment guide can be improved if we add the content and information into it.

**Comment by derekchiang** [comment]
Hi @ShengjieLuo , from what you described, seems like you have 2 `pachd` pods running on 5 nodes?  If that's the case, then the `pachd` pods can be on any of the 5 nodes, so you can try the public IP address of each of them.

**Comment by ShengjieLuo** [comment]
@derekchiang  Sorry for response this issue late. It seems not work for the aws deployment.
See pachd pod work in two nodes,
```
NAME            READY     STATUS    RESTARTS   AGE       NODE
etcd-qd1xn      1/1       Running   0          25m       ip-172-20-0-253.us-west-2.compute.internal
pachd-czle8     1/1       Running   5          25m       ip-172-20-0-252.us-west-2.compute.internal
pachd-gd4bk     1/1       Running   5          25m       ip-172-20-0-253.us-west-2.compute.internal
rethink-g3isl   1/1       Running   0          25m       ip-172-20-0-253.us-west-2.compute.internal
```
When we use the public IP address of `pachd-czle8`
```
# export ADDRESS=54.218.71.178:30650
# pachctl version
COMPONENT           VERSION
pachctl             1.1.0-9a683a7fa30cf3215e846979e50a3f7991789672
pachd               (version unknown) : error connecting to pachd server at address (54.218.71.178:30650): context deadline exceeded
please make sure pachd is up (`kubectl get all`) and portforwarding is enabled
```
When we use the public IP address of `pachd-gd4bk`
```
# export ADDRESS=54.149.184.159:30650
# pachctl version
COMPONENT           VERSION
pachctl             1.1.0-9a683a7fa30cf3215e846979e50a3f7991789672
pachd               (version unknown) : error connecting to pachd server at address (54.149.184.159:30650): context deadline exceeded
please make sure pachd is up (`kubectl get all`) and portforwarding is enabled
```
So neither of the public addresses work. Could you give me a possible method to enable the communication between `pachctl` and `pachd` pods. Thanks for that.

**Comment by ShengjieLuo** [comment]
The port forwarding problem has been solved.We need use the following command to do the port-forwarding.
`kubectl port-forward <pachyderm pods name> 30650:650 &`
For example,
`kubectl port-forward  pachd-czle8 30650:650 &`
Do you think we need give the explanation on the document? Since it is not a apparent solution most times.

**Comment by jdoliner** [comment]
@ShengjieLuo glad this worked for you and sorry we didn't mention it as an option earlier. `kubectl port-forward` was broken for a while so it wasn't something we used internally.
Starting in 1.2 you'll be able to do:

```
$ pachctl port-forward
```

Which will have the same effect as what you've done above but saves the user having to find a pachd pod.

**Comment by jdoliner** [comment]
Closing as this seems to be resolved.
