### ISSUE TITLE
Error pachd on newly created cluster : certificate signed by unknown authority

### ISSUE THREAD

**Issue by quematech** [pachyderm/pachyderm#7071]
**What happened?**:
I did a gke cluster deployment following the procedure you gave us in : 
https://github.com/pachyderm/pachyderm/issues/7059#issuecomment-961386827

The cluster is up and running, and we can check the available pods : 
```
NAME                          READY   STATUS    RESTARTS   AGE
etcd-0                        1/1     Running   0          7m56s
pachd-ffbc4c8b9-jvqjr         1/1     Running   0          7m57s
pg-bouncer-7b855cb797-bfsd6   1/1     Running   0          7m57s
postgres-0                    1/1     Running   0          7m56s
```

However, any of the following command will fail with the same error message : 
* pachctl version
* pachctl list repo
* pachctl create repo XXX

Error is : 
`Get "https://34.90.118.164/api/v1/namespaces/default/pods?labelSelector=app%3Dpachd%2Csuite%3Dpachyderm": x509: certificate signed by unknown authority`

The pachd pod logs give : 

```
2021-11-06T09:13:07Z INFO started setting up Proxy API GRPC Server
2021-11-06T09:13:07Z INFO finished setting up Proxy API GRPC Server
2021-11-06T09:13:07Z INFO finished setting up Internal Pachd GRPC Server
2021-11-06T09:13:07Z WARNING s3gateway TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory
```

**What you expected to happen?**:

For pachctl to work properly

**How to reproduce it (as minimally and precisely as possible)?**:

Create a GKE Cluster as in https://docs.pachyderm.com/latest/deploy-manage/deploy/quickstart/#google
Try pachctl version

**Anything else we need to know?**:

There is uncertainty about the service account we should use in the values.yaml, about which authorizations should be set

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI and pachd server version (use `pachctl version`):

```
COMPONENT           VERSION             
pachctl             2.0.0               
Get "https://34.90.118.164/api/v1/namespaces/default/pods?labelSelector=app%3Dpachd%2Csuite%3Dpachyderm": x509: certificate signed by unknown authority
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

GKE

- If you deployed with helm, the values you used (`helm get values pachyderm`):

deployTarget: GOOGLE

```
pachd:
  storage:
    google:
      bucket: "bucketname"
      # You can also pass the creds on the command line using helm install --set-file storage.google.cred=creds.json 
      cred: |
        {
          "type": "service_account",
.....
        }
  externalService:
    enabled: true
```

- OS (e.g. from /etc/os-release):

Debian

- Others:

**Comment by quematech** [comment]
Update : the issue is just that I'm a moron who do not read carefully the documentation

With all due apologies : closing this issue.

**Comment by mindthevirt** [comment]
@quematech haha not a problem at all, I'm glad you figured it out. Could elaborate which part you missed?

**Comment by quematech** [comment]
Gladly :)

I was following the quick cloud deployment method (https://docs.pachyderm.com/latest/deploy-manage/deploy/quickstart/#4-have-pachctl-and-your-cluster-communicate) for GKE, but at first totally missed the "Have 'pachctl' And Your Cluster Communicate" part...
