### ISSUE TITLE
Downloading a file from console does not download the file itself

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#7074]
**What happened?**:
I tried downloading a file from console, it downloads a file that is much smaller.

**What you expected to happen?**:
The right file will download.

**How to reproduce it (as minimally and precisely as possible)?**:
Attempt to download the file in a similar env to mine.

**Anything else we need to know?**:
I suspect somewhat that this might be related to the initial state of my pach 2 deployment. I have yet to replicate this on hub.

**Environment?**:
- Kubernetes version (use `kubectl version`): AKS 1.20.9
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.0.1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): Azure.
- If you deployed with helm, the values you used (`helm get values pachyderm`): Quickstart deploy, with a basic ingress (This is a very initial and raw dev cluster, i've yet to make it worthy with things like idp and tls).

**Comment by mindthevirt** [comment]
@RaananHadar thank you for opening this ticket. What type of file was it and when you say the file was much smaller than displayed in Console, was the content of the file truncated, was it the wrong file or was the file corrupted?

**Comment by RaananHadar** [comment]
I am closing this as this was probably caused by me working with a hybrid ingress/port-forward approach. Working with an ingress now and this is no longer an issue.
