### ISSUE TITLE
Suggest a Revision in Makefile Section clean-amazon-cluster

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#708]
The `Makefile`  is not effective enough in the section `clean-amazon-cluster`. Several components remained undeleted after `make clean-launch` and `make clean-amazon-cluster`. I suggest to add a `clean-amazon-launch` section with the following script

```
clean-launch
clean-amazon-cluster
kubectl delete secrets amazon-secret
kubectl delete persistentvolumes rethink-volume
kubectl delete persistentvolumeclaims rethink-volume-claim
```

The script has been merged in my program locally and it works to deploy amazon.

**Comment by jdoliner** [comment]
Hi @ShengjieLuo thanks for the issues this seems like a great change. Btw when you have a change this specific in mind you can submit it as a Pull Request. If you've made the change to a forked copy then I think all you have to do is push it to GH and go to the repo and you'll get a big PR button. As a bonus you get your name in our contributors list 😸.

If that's not feasible for some reason we'll happily add this, but latency on this stuff will invariably bet a bit slower than if there's just a big green merge button I can hit.

**Comment by derekchiang** [comment]
FYI here is a tutorial on pull requests: https://help.github.com/articles/using-pull-requests/

**Comment by sjezewski** [comment]
merged
