### ISSUE TITLE
setting parallelism to zero generates errors when run locally via the make file

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#709]
when parallelism is set to zero it fails to determine cluster size of the locally run k8s cluster and cannot deploy the pipelines.

**Comment by derekchiang** [comment]
@JonathanFraser sorry that you ran into this.  If you have the error messages could you post them?

**Comment by jdoliner** [comment]
Afaik this is no longer an issue, coefficient pipelines can fail to schedule if the pachyderm service account doesn't have the right permissions but we have warning messages for this and constant parallelism will fix it.
