### ISSUE TITLE
Allow annotations on Service manifests in helm chart

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#7168]
**What is the goal / desired outcome?**
To allow custom annotations to be specified on Service manifests from the pachyderm helm chart. This is necessary on Google Cloud Platform when using internal load balancers to add annotations to the service to allow it to be used. For example I want to add the following annotations to the pachd service:
```
cloud.google.com/neg: '{"ingress": true}'
networking.gke.io/load-balancer-type: Internal
cloud.google.com/backend-config: '{"default": "pachd-hc-config"}'
```
There is already a `pachd-lb` that allows annotations (that is not intended to be used with an ingress it looks like), this would extend adding annotations to the internal pachd service that is intended to be used with a loadbalancer frontend. 

I am a bit confused about what is intended to be used with a loadbalancer and what isn't. I'll talk to my customer rep about that.

**If there is a way to accomplish this today via workaround, what does that require?**
You could create additional services after deploying the chart with the annotations, but that is duplicating what the helm chart is supposed to be doing.

**(Optional) What is your proposal for a feature to solve this?**
Add `addtionalAnnotations` blocks to the service accounts in the values.yaml for the helm chart and use the settings in the helm chart templates. At a minimum add this to the pachd service.

**Comment by brendoncarroll** [comment]
Thanks for creating an issue.  We are working on support for annotations on deployments and statefulsets and plan to include services as well.
