### ISSUE TITLE
make docker-build fails silently

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#720]
If your code isn't compiling then doing `make docker-build` won't return a nonzero exit code and it won't give you any output explaining what went wrong. This is a bug I introduced with the detached compiles. `docker wait ...` returns the error code on stdin if the process fails (not as a return code like I had hoped). We can just check that and do `docker logs ...` if it's not `0`.

**Comment by sjezewski** [comment]
Master has the fix for this
