### ISSUE TITLE
Pipeline stuck, impossible to update, do not launch

### ISSUE THREAD

**Issue by quematech** [pachyderm/pachyderm#7220]
**What happened?**:

We have a small data architecture based on Pachyderm. One of the pipeline is totally stuck, and can not process the last commit it has on a new datum.

Behavior is quite weird : 

* When starting pipeline : "pachctl start pipeline metadatas_one", the pods are created, but the pipeline is still set as paused in "pachctl list pipeline" : 

```
pachctl list pipeline
NAME                          VERSION INPUT                                                                                      CREATED      STATE / LAST JOB DESCRIPTION                                                                                              
metadatas_one                 4       ((compl_metadata:/(*) ⋈ dump_metadata:/(*)) ∪ (dump_metadata:/(*) ⋈ image_annotated:/(*))) 14 hours ago paused / killed  Merge entre dump_metadatas && compl_metadatas -> metadatas_one 
```

* Every one of the three pods for this pipeline has the same error log : 

```
kubectl logs pipeline-metadatas-one-v3-f844t -c user
{"pipelineName":"metadatas_one","workerId":"pipeline-metadatas-one-v3-f844t","master":true,"ts":"2022-01-05T09:22:31.477528338Z","message":"errored transform spawner process: jobs metadatas_one@af9893153b1e41b1b01faac4f235d155 not found"}
{"pipelineName":"metadatas_one","workerId":"pipeline-metadatas-one-v3-f844t","master":true,"ts":"2022-01-05T09:22:31.481270069Z","message":"master: error running the master process, retrying in 17.73980232s: jobs metadatas_one@af9893153b1e41b1b01faac4f235d155 not found\ngithub.com/pachyderm/pachyderm/v2/src/internal/grpcutil.ScrubGRPC\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/internal/grpcutil/error.go:16\ngithub.com/pachyderm/pachyderm/v2/src/client.APIClient.InspectJob\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/client/pps.go:211\ngithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*pendingJob).load\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/pipeline/transform/pending_job.go:107\ngithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*registry).startJob\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/pipeline/transform/registry.go:134\ngithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.Run.func1\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/pipeline/transform/transform.go:30\ngithub.com/pachyderm/pachyderm/v2/src/client.APIClient.SubscribeJob\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/client/pps.go:391\ngithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.Run\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/pipeline/transform/transform.go:19\ngithub.com/pachyderm/pachyderm/v2/src/server/worker.runSpawner.func2\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/worker.go:174\ngithub.com/pachyderm/pachyderm/v2/src/server/worker/logs.(*taggedLogger).LogStep\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/logs/logger.go:190\ngithub.com/pachyderm/pachyderm/v2/src/server/worker.runSpawner\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/worker.go:173\ngithub.com/pachyderm/pachyderm/v2/src/server/worker.(*Worker).master.func1\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/worker.go:139\ngithub.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryUntilCancel\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/internal/backoff/retry.go:129\ngithub.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryNotify\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/internal/backoff/retry.go:118\ngithub.com/pachyderm/pachyderm/v2/src/server/worker.(*Worker).master\n\t/Users/avigil/Pachyderm/Pachyderm_releases_2.x/pachyderm/src/server/worker/worker.go:128\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
```

An interesting point is that this job id (af9893153b1e41b1b01faac4f235d155) does not appear in the pachctl list job pipeline@master

* When trying to launch a whole reprocess of the pipeline, we have a very frightening error : 
```
pachctl update pipeline -f=pipeline.json --reprocess
more than one matching row found in pipelines on index version with value metadatas_one@00000004
```
Which looks like there is some conflict in the postgres Database

* The postgres pod show some errors too : 

```
2022-01-05 09:04:31.218 GMT [873095] STATEMENT:  insert into collections.branches (key, proto, idx_repo, version) values ($1, $2, $3, $4) on conflict (key) do update set (key, proto, idx_repo, version) = ($1, $2, $3, $4)
2022-01-05 09:04:31.793 GMT [873091] ERROR:  could not serialize access due to read/write dependencies among transactions
2022-01-05 09:04:31.793 GMT [873091] DETAIL:  Reason code: Canceled on identification as a pivot, during write.
2022-01-05 09:04:31.793 GMT [873091] HINT:  The transaction might succeed if retried.
2022-01-05 09:04:31.793 GMT [873091] STATEMENT:  update collections.repos set version = $1, key = $2, proto = $3, idx_name = $4, idx_type = $5 where key = $6
```

The pipeline specification is as follows : 
```

{
    "pipeline": {
      "name": "metadatas_one"
    },
    "description": "XXXX",
    "parallelism_spec" : {
      "constant":3
    },
    "input": {
        "union" : [
          {
            "join" : [
              {
                "pfs": {
                  "repo": "dump_metadata",
                  "branch": "master",
                  "glob": "/(*)",
                  "join_on": "$1",
                  "outer_join": true
                  }
              },
              {
                "pfs": {
                    "repo": "compl_metadata",
                    "branch": "master",
                    "glob": "/(*)",
                    "join_on": "$1"
                }
              }
            ]
          },
          {
            "join" : [
              {
                "pfs": {
                  "repo": "dump_metadata",
                  "branch": "master",
                  "glob": "/(*)",
                  "join_on": "$1"
                  }
              },
              {
                "pfs": {
                    "repo": "image_annotated",
                    "branch": "master",
                    "glob": "/(*)",
                    "join_on": "$1"
                }
              }
            ]
          }
          
        ]
    },
    
    "transform": {
      "cmd": [ "/pipeline/start.sh" ],
      "image": "IMAGE"
    }
  }

```
**What you expected to happen?**:
At least, the reprocess should create a new "clean" version of the pipeline

**How to reproduce it (as minimally and precisely as possible)?**:
No idea at this point, deeply sorry about that

**Anything else we need to know?**:
There may be some bad practices we have, as we : 
* Often stop and start pipelines 
* Dumped in the input repository (here, dump_metadata) multiple times the same folder

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI and pachd server version (use `pachctl version`):

```
COMPONENT           VERSION             
pachctl             2.0.4               
pachd               2.0.4   
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

GKE

- If you deployed with helm, the values you used (`helm get values pachyderm`):

```
USER-SUPPLIED VALUES:
deployTarget: GOOGLE
global:
  postgresql:
    postgresqlPassword: PASS
    postgresqlPostgresPassword: PASS
pachd:
  clusterDeploymentID: ID
  enterpriseSecret: ""
  externalService:
    enabled: true
  oauthClientSecret: ""
  rootToken: ""
  storage:
    google:
      bucket: exxacts-dataprod-v2
      cred: |
        JSON

```
- OS (e.g. from /etc/os-release):
Debian
- Others:

**Comment by quematech** [comment]
We investigated if there was any duplicate row in the postgresql database, does not look like the case. Hope it helps : 

```
pachyderm=> select idx_name,idx_version from "collections"."pipelines" where idx_name='metadatas_one';
   idx_name    |      idx_version       
---------------+------------------------
 metadatas_one | metadatas_one@00000001
 metadatas_one | metadatas_one@00000002
 metadatas_one | metadatas_one@00000003
 metadatas_one | metadatas_one@00000004
```

**Comment by dgeorg42** [comment]
@quematech - My first suspicion here is that there may be an open commit which was never finished for some reason.  I say that because I've seen that happen before and the "job not found" was a side effect of it.  Can you run `pachctl list commit --all --expand` and then post the results here?  That will tell us definitively if that's the issue.

In case that's _not_ the issue, though, can you also run `pachctl debug dump debug-dump.tar.gz` and upload the resultant file here?  That will give me a complete dump of the current state of the system to look through.

Thanks,
Dale

**Comment by quematech** [comment]
@dgeorg42 : Thank you a lot for your answer.

Looks like you're right, we got an open commit in the "meta" of metadatas_one, with the corresponding id (that was given as a "job id" in the pod logs) : 

```
compl_metadata         master af9893153b1e41b1b01faac4f235d155 42 hours ago 0B       ALIAS                    
dump_metadata          master af9893153b1e41b1b01faac4f235d155 42 hours ago 13.2MiB  ALIAS                    
image_annotated        master af9893153b1e41b1b01faac4f235d155 42 hours ago 0B       ALIAS                    
metadatas_one.spec     master af9893153b1e41b1b01faac4f235d155 42 hours ago 0B       ALIAS                    
metadatas_one.meta     master af9893153b1e41b1b01faac4f235d155 -            ≤ 0B     AUTO 
``` 

What is interseting is that : 
* this commit does not exist on metadatas_one@master. 
* all commits are ALIAS or this very AUTO
* all commits are finished except from this one : 

```
pachctl inspect commit metadatas_one.meta@af9893153b1e41b1b01faac4f235d155
Commit: metadatas_one@af9893153b1e41b1b01faac4f235d155
Original Branch: master
Parent: b88d8c5b912e4ea39e3c7107506a3117
Started: 42 hours ago
```

* I can list files but not datums, and find this "job not found" error while trying to check the datum : 

pachctl list file metadatas_one.meta@af9893153b1e41b1b01faac4f235d155
NAME   TYPE SIZE     
/meta/ dir  87.98KiB 
/pfs/  dir  26.21MiB 

pachctl list datum metadatas_one.meta@af9893153b1e41b1b01faac4f235d155
ID FILES STATUS TIME 
jobs metadatas_one.meta@af9893153b1e41b1b01faac4f235d155 not found

I don't want to mess it up, so what would you recommend for this case ? I'm not even sure to understand what this "meta" is. Trying to squash/delete the whole commit ? Moreover, we have finished commits on this repo after this one commit : 

```
pachctl list commit --all --expand | grep metadatas_one.meta
metadatas_one.meta master b77a7db9755e49babdabd8a664e09a20 20 hours ago 26.3MiB  AUTO                     
metadatas_one.meta master 91e8a468c11a47578d4724b9e2c9bb64 24 hours ago 26.3MiB  AUTO                     
metadatas_one.meta master 689e14ab15c74f10922cb6af045889bf 38 hours ago 26.3MiB  AUTO                     
metadatas_one.meta     master 389e2a0b5b014133b19b914cd51a2932 38 hours ago 26.3MiB  AUTO                     
metadatas_one.meta     master a3b8810324f84b6993cfaed14a08b637 41 hours ago 26.3MiB  AUTO                     
metadatas_one.meta     master bc2662bdda104d1d98cd42c6eed7f668 42 hours ago 26.3MiB  AUTO                     
metadatas_one.meta     master af9893153b1e41b1b01faac4f235d155 -            ≤ 0B     AUTO                     
metadatas_one.meta     master b88d8c5b912e4ea39e3c7107506a3117 42 hours ago 26.3MiB  AUTO 
```

Thank you a lot for your time and your help, and best regards

**Comment by dgeorg42** [comment]
@quematech - OK, so this is exactly the same problem that I saw with one of our Enterprise customers.  Fortunately, it is easy to resolve.  You just need to force that commit to finish with the following command:

`pachctl finish commit metadatas_one.meta@af9893153b1e41b1b01faac4f235d155`

Everything should start working properly after that.

To answer your other question about what precisely the meta repo is - Every pipeline has a couple of "system repos" associated with it, which typically are hidden (which is why we used the --all flag so we could see them).  One of these is the "spec" repo where we store each version of the pipeline spec whenever you update it; another is the "meta" repo, where certain metadata about the pipeline executions (such as provenance information) gets stored.

I'm going to bring this to Engineering's attention since this is now the second time we've encountered an unfinished commit on a meta repo, and we haven't yet identified the cause. In the meantime, though, finishing that commit should get you back in business.

Thanks,
Dale

**Comment by quematech** [comment]
@dgeorg42 : I'm sorry, but the finish commit command does not look like it works : 

```
pachctl finish commit metadatas_one.meta@af9893153b1e41b1b01faac4f235d155
cannot finish a pipeline output or meta commit, use 'stop job' instead
```

I tried a stop job but no luck : 

```
pachctl stop job  metadatas_one.meta@af9893153b1e41b1b01faac4f235d155
error from StopJob: jobs metadatas_one.meta@af9893153b1e41b1b01faac4f235d155 not found
```

Would you have any idea ?

Thank you a lot

**Comment by quematech** [comment]
I guess reading from the documentation that we could use the -force parameter, but I would prefer to be sure before forcing anything :)

**Comment by quematech** [comment]
Ok, we recreated the usecase on another pipeline and tried the -force option. It does work perfectly :)

Thank you a lot @dgeorg42 for your time.

If you want, we can look into a minimal reproducable scenario.

Best Regards

**Comment by PFedak** [comment]
Unfortunately, yes, `-force` was necessary there as you found. As a result of the issue, no job was ever created, so `StopJob` wouldn't work. That also means that using `-force` here isn't too risky. 

I'm not sure how valuable it is to you to try reproducing the issue, but it would be useful for us to know a little bit more about your pachyderm workflow besides frequent stopping and starting - do use triggers or manual branch movement (basically anything other than just putting data into an input repo)?

**Comment by quematech** [comment]
Hi.

(Quite) Basically, we have some input repositories that receive the data and some pipelines that process it sequentially. We use a shell script to stop/start pipelines while dumping data, as we have a few number of nodes.

For more details, it would be easier to have a private exchange. We had talked with some people from your company in 2021 and they had suggested we exchange with your engeneering team. However, confidentiality was, if I remember properly, an issue.

Best Regards
