### ISSUE TITLE
put file does not check if repo exists before uploading

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#7251]
**What happened?**:
When using `pachctl put file` files are uploaded to pachyderm and only once they finish an error is thrown that the repo does not exist.
**What you expected to happen?**:
I'd expect the error to be thrown in advance and the upload to be avoided, this can save precious user time.

**How to reproduce it (as minimally and precisely as possible)?**:
run a `pachctl put file` to a nonexisting repo

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
2.0.5

**Comment by robert-uhl** [comment]
Closed by #7549. Thanks for reporting!
