### ISSUE TITLE
pachctl delete file repo-name@master stopped working in 2.x

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#7254]
**What happened?**:
Running `pachctl delete file <repo-name>@master` used to work in Pachyderm 1.x. It no longer works in 2.x but requires
`pachctl delete <repo-name>@master:/` to work.

**What you expected to happen?**:
`pachctl delete file <repo-name>@master` should work. Its more concise.

**How to reproduce it (as minimally and precisely as possible)?**:
run `pachctl delete file <repo-name>@master` in 2.x

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
2.0.6

**Comment by dgeorg42** [comment]
This is related to #6190

**Comment by BOsterbuhr** [comment]
@RaananHadar in 2.0 there was a  `-r` / `--recursive` flag added to `pachctl delete file`.
In 2.x `pachctl delete file -r <repo-name>@master` has the same behavior as `pachctl delete file <repo-name>@master` in 1.x. 
This change protects users from deleting all the files in their repo if they inadvertently run `pachctl delete file <repo-name>@master` without providing a file path.
