### ISSUE TITLE
Step 4 in working with pipelines how-to doc unclear

### ISSUE THREAD

**Issue by shacharhelmer** [pachyderm/pachyderm#7292]
**Relevant page:**
https://github.com/pachyderm/pachyderm/blob/master/doc/docs/2.0.x/how-tos/developer-workflow/working-with-pipelines.md

**What's wrong:**
Step 4 (Create/Edit the Pipeline Config) describes a list of sub-steps for creating a pipeline config that has just a single item. 
For readers this might be confusing as they might expect further steps (especially if they're not fluent in pachyderms terms yet).

**Suggested fix**
I suggest either removing the list or expending the config example section giving separate items for each of the objects in the config JSON.

**Context**
Latest docs (2.0.x).

**Comment by nadegepepin** [comment]
Very valid point @shacharhelmer!  
We have updated the docs https://docs.pachyderm.com/latest/how-tos/developer-workflow/working-with-pipelines/#step-4-createedit-the-pipeline-config

Thanks for bringing this up. Feel free to reach out with more suggestions.
