### ISSUE TITLE
Incorrect results from `ListFile`

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#732]
In our current implementation of pfs `ListFile` can return wrong results.
The issue arises due to bugs with sharding. When we put the file `foo/bar` `APIServer turns that into 2 requests. One to put the directory `foo` and one to put the actual file `foo/bar`. Each of these requests gets routed to their respective shards, which means they probably wind up on different shards. Now when we do a `ListFile` for `foo` we route that request to the shard that contains `foo` and that node checks for `foo`'s children such as `foo/bar` which it won't find if `foo/bar` happens to be on a different shard than `foo`.

**Comment by msteffen** [comment]
![mr-bean](https://cloud.githubusercontent.com/assets/235674/17789125/9bed96c0-6545-11e6-81a3-0480391135bf.jpg)

**Comment by sjezewski** [comment]
`TestBigListFile` is running and passing on `pfs-refactor` branch
