### ISSUE TITLE
Web CLI as a part of Console

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#7358]
**What is the goal / desired outcome?**
Having an ability to open a CLI straight from Console can make it a convenient one stop shop for managing Pachyderm. The CLI can also use the Pachyderm shell and save the user from authenticating multiple times both from the Console and from a different linux instance which will act as a gateway. Another use case where this can help is when a new user needs access or when a new server is provisioned to act as a gateway with Pachyderm and requires configuration to access Pachyderm. It might take time to setup a machine with pachctl and config properly things to connect with grpc, which data scientists may have issues with. So it is also more secure and time saving feature for the Pachyderm admin compared to a ssh session.

**If there is a way to accomplish this today via workaround, what does that require?**
The user can use pachctl from a remote server or Pachyderm notebooks. This is a viable alternative, but I think a web-cli can make Console more useful overall for the reasons specified above.

**(Optional) What is your proposal for a feature to solve this?**
Implement a popup, quake style window in console that opens the cli. Very similarly to how this is performed in Azure cloud shell.

**Comment by chainlink** [comment]
Jupyterlab would work for this if that's of interest. We're also building out extensions to integrate pachyderm with Jupyter such as mount, which allows you to mount Pachyderm files within your notebook.

**Comment by RaananHadar** [comment]
Thanks @chainlink I agree that there are more pressing issues.
