### ISSUE TITLE
Setup Logging Service

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#748]
This service should:

- consume all the logs from all pods
- keep the logs for at least 3 days
- provide a UI to view the logs

We'll add the manifests for deploying the log service to our repo, and either deploy this service as part of `make launch` or provide a different make target.

For now, I'm running w fluentd / elasticsearch / kibana a la http://kubernetes.io/docs/getting-started-guides/logging-elasticsearch/

**Comment by jdoliner** [comment]
Scheduling this for 1.3. And assigning to @sjezewski since he's working on it.

**Comment by sjezewski** [comment]
I'm still figuring out how these components fit together, but the basics are:

- We spin up a fluentd pod per node (VM) that is provisioned. These gather logs from each node and send the logs to the `elasticsearch-logging` pods
- The `elasticsearch-logging` pods, which store the logs and expose them via a REST API
- The kibana pod provides a web UI for viewing the logs

**Comment by sjezewski** [comment]
The above is probably a valid path if we want to vendor in some logging tools w a given pachyderm cluster deployment. But! GCE and AWS seem to have builtin cluster wide logging already.

In particular, GCE provides monitoring (of CPU/MEM) via stackdriver, and logs (w search and past a few days) via their dashboard.
