### ISSUE TITLE
Minimize the size of our docker container

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#75]
Our container's size is starting to be an annoyance. AWS would come up way quicker if we could reduce its size.

This shouldn't be too hard, our whole server can pretty easily be made in to a static binary.

**Comment by peter-edge** [comment]
Only thing you need to take care of is lib/btrfs/btrfs.go

The functions in there shell out to `btrfs` and `sync`. `sync` you can handle, but `btrfs` goes to `/bin/btrfs`/ which is `chroot /host brtrfs`, and a minimal docker container with the `scratch` base image won't have chroot (or anything else). You can do this with os/syscall package, but...well read bout it haha. And it changes the whole go process which is obviously not ok.

But ya, there's solutions to this. If you don't care about absolute minimal binary, you could use either the `busybox` or `gliderlabs/alpine` images instead, which are still super small, and have chroot. What you think?

Only other super common thing to worry about (haven't gone through the code yet) is if you do any HTTP calls anywhere, or plan to, root certs aren't available. So you can add them straight up (just copy them from CoreOS), or I put together this https://github.com/peter-edge/go-cacerts for this exact reason. Be careful to cache any objects you use from `cacerts` though, a ton of memory is allocated for each call to `cacerts.NewX509CertPool()`.

**Comment by jdoliner** [comment]
Just took a swing at setting this up with busy box and it looks like that will be an pretty easy way to improve this a lot. I got an 11.86 MB image vs. 577.2 MB before.

This link is helpful:

https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

**Comment by jdoliner** [comment]
Code is at for those interested.
https://github.com/pachyderm/pfs/tree/minimal_container

**Comment by peter-edge** [comment]
Done
