### ISSUE TITLE
Error creating pipeline from fruit stand example

### ISSUE THREAD

**Issue by statik** [pachyderm/pachyderm#754]
Hi! I am trying to work through the fruit stand example on my OSX laptop:
https://github.com/pachyderm/pachyderm/tree/master/examples/fruit_stand

`pachctl version` shows 
pachctl version
COMPONENT           VERSION
pachctl             1.1.0
pachd               1.1.0

When I create the pipeline I get an error about unmarshaling a string into a bool:

```
pachctl create-pipeline -f examples/fruit_stand/pipeline.json
error marshalling JSON into protobuf: json: cannot unmarshal string into Go value of type bool
```

I wasn't able to track down exactly where the error happened, but the filter repository was created and the filter pipeline was created, the sum repository and job was not created. It seems like this problem might be related to the bug fixed in #751 .

**Comment by jdoliner** [comment]
Hey @statik sorry you hit this. We made some updates to the pipeline spec and the version of the fruitstand pipeline in master isn't currently compatible with the v1.1.0. To fix this you first need to delete the `filter` pipeline like so:

```
pachctl delete-pipeline filter
pachctl delete-repo filter
```

Then to make it work:

```
git checkout v1.1.0
pachctl create-pipeline -f examples/fruit_stand/pipeline.json
```

**Comment by statik** [comment]
@jdoliner aha! makes perfect sense now. that worked great, thank you.

**Comment by jdoliner** [comment]
Glad that worked! :)
