### ISSUE TITLE
Performance comparison between Pachyderm and local docker

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#755]
See #701 . It is a rough comparison between local host and Pachyderm. To improve the comparison, I would make a detailed comparison between Pachyderm, local server and local docker.

I take the `wordcount_reduce` as the test sample. In this sample we would reduce the word count from a source data file and statistic the numbers of every word.

The script has been changed to record the time with more details.

```
echo begin> /pfs/out/MapReduceTime; \
date +%s.%N >> /pfs/out/MapReduceTime ; \
find /pfs/wordcount_map -name '*tion' | while read count;  \
      do 
      echo $count > /tmp/count ; 
      date +%s.%N >> /tmp/count; 
      cat $count | awk '{ sum+=$1} END {print sum}' >> /tmp/count;
      date +%s.%N >>/tmp/count; mv /tmp/count /pfs/out/`basename $count`; 
done; 
echo end>>/pfs/out/MapReduceTime;
date +%s.%N >> /pfs/out/MapReduceTime;
```

The wordcount reduce step is a loop with about 830 cycles. Within this script , I can record the begin time and end time of whole program,  as well as, the duration time of each loop.

Details about these three methods are explained as follows
1 The Pachyderm is realized on a AWS VM as a single node pachyderm platform. Firstly, a Kubernetes is launched on the single-node VM. Then, Pachyderm is built on this  Kubernetes. Therefore , no S3 storage is used. The process all follows the official guide except the transform script is changed to display more details.
2 The local host:  Also an AWS VM. The source data file is put in the local file system. And the script I have mentioned is used to execute the word reduce step.
3 The local docker: The source data file is put in the image before execution. Then the script is executed in the docker to reduce the words. 
See the dockerfile used to built the test image,

```
FROM ubuntu:14.04
MAINTAINER jdoliner@pachyderm.io

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    ca-certificates \
    fuse \
    wget && \
  apt-get clean && \
  rm -rf /var/lib/apt

RUN mkdir data
ADD map data  
#The data file located in ./map (local file system), now we add it into the docker image.
```

As a result, with the same task, local server spends 2.754sec, local docker spends 5.016sec and Pachyderm spends 31.909 sec. There is 6x performance difference still.
The detail can be seen from the following picture.
![image](https://cloud.githubusercontent.com/assets/20234415/17919075/10f88662-69fd-11e6-9c1b-40d848f9a4a0.png)

**Comment by derekchiang** [comment]
Thanks for the evaluation.  I think this confirms the finding in #701 that Pachyderm as it is introduces significant latency to workloads where many small files are written.  We will be looking into this issue soon.

Meanwhile, would you be able to evaluate Pachyderm against a workload that operates on a few big files?  Something like writing 10GB of data into one single file.  In that case, I'd hope that Pachyderm maintains the same level of throughput as the filesystem allows .

**Comment by ShengjieLuo** [comment]
@derekchiang Could you give me some recommended applications that involving little file operations but large file size? I would work on it tomorrow.

**Comment by derekchiang** [comment]
For the purpose of this evaluation, a simple script like this will do:

dd if=/dev/urandom of=/pfs/out/file bs=1M count=10000

This just writes 10GB of random data into PFS.

**Comment by sjezewski** [comment]
Thanks for the benchmark. We've ripped out FUSE and a lot has changed in our processing model. I don't see any more todo's here, so I'm closing the issue. Please reopen if you disagree.
