### ISSUE TITLE
Update docker client testing

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#771]
See this travis output:

https://travis-ci.org/pachyderm/pachyderm/builds/156372869

Basically, the version of the client we use (I have the following locally), but travis is using 1.12, and so we have a mismatch. We should probably add these tests to CI, but for now I'll leave them be (on the refactor branch)

`````` shell
$docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64```
``````

**Comment by sjezewski** [comment]
@jdoliner thinks that these don't test any code that is used anymore

If so, we can just remove these

**Comment by jdoliner** [comment]
Yeah, the container package isn't imported by anything. I think it can safely be removed.

**Comment by jdoliner** [comment]
I believe these tests have been removed.
