### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#773]
Services are something we've talked about a lot internally, in a nut shell services are like pipelines except that instead of running some code that reads some data, writes some data and then exits they run some code that reads some data and does not exit. Services are often the last step in the data pipeline, for example you might compute a model for detecting fraud and then ship that off to a service which uses it to validate requests as they come in to your site. Normally services like this are considered separate from the data infrastructure but there are several reasons that I think it will be good to make them part of it:
- We can automatically update services as new data comes in, keeping them up to date.
- If there's an upstream failure we can keep the old version of the service running, eliminating the risk of running with corrupt or incomplete data.
- Services will run in our k8s cluster so we'll be able to make data locality optimizations on them just like with pipelines.
# Implementation Proposal

Because Services are so similar to Pipelines I think it makes more sense to extend those requests rather than adding new ones. I think we should add a `bool` to `pps.Transform` called `Service`. There are 2 requests that include a `Transform`, `CreateJob` and `CreatePipeline`. When `Service` is `false` (the default) those requests behave as they do now. When it's `true` though they have the following differences:
- `CreatePipeline` doesn't create an output repo when its `Transform` has the `Service` flag set.
- `CreateJob` creates a ReplicationController rather than a Job. It also creates a service for the pods in that replication controller. The service should use `CreateJobRequest.Pipeline` as its name if it's set, otherwise it should use the name of the Job.
# Open Questions
- Can pipelines reference services? This seems like it could be very useful, for example you could have a service that spins up a postgres cluster and loads in some data and then another pipeline that does computations by accessing that postgres cluster.
- Similarly, how should `FlushCommit` behave with respect to `Services`? There should be a way to block until a commit has been seen by all `Services` but without an output commit to wait on our current mechanism doesn't work.
- Should we have a concept initializing a service? For example if you were spinning up a postgres cluster there will be a period when the cluster is still loading data during which we probably don't want to let people query it because they'll get back partial results which could lead to confusion.
- How does the user express which ports should be exposed from their service.
- Should there be scoping on services? If we just create a k8s service then every pod in the cluster will be able to see the service, this could lead to some weird usages where pipelines depend on services without explicitly declaring it. Might be something we can live with being possible but not recommended but if there's a good way to limit the scope we should consider it.

**Comment by sjezewski** [comment]
We've broken down this implementation into a few steps:

- 'job' analog of a service (mounts the data ... but data never gets refreshed)
- updating pachctl CLI to have a `delete-job` method (and implement deletion
- 'pipeline' analog of a service (mounts the data and does a rolling update each time a new commit is available)

We expect at least the first part to land for 1.3

**Comment by sjezewski** [comment]
The 'job' analog + the `delete-job` CLI landed in 1.3

Moving this issue to 1.4 for the remaining `pipeline` analog feature

**Comment by jdoliner** [comment]
We've had services for a while, they're far from complete but we have a number of issues detailing improvements we want to make to them so I don't think it makes sense to keep the broader issue open.
