### ISSUE TITLE
Version Conflict in Pachctl

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#779]
According to the official guide ,there are two methods to install the pachctl. However, the two methods provide two different versions and neither of the two versions alone can be used in deployment. 

## The first method 

> Deb Package
If you’re on linux 64 bit amd, you can use our pre-built deb package like so:
`$ curl -o /tmp/pachctl.deb -L https://pachyderm.io/pachctl.deb && dpkg -i /tmp/pachctl.deb`

This method provides the pachctl with the version 1.1.0. This version of pachctl cannot be used in deployment, because we use the `pachctl deploy -dry-run` in `make launch` and `make launch-dev`. The 1.1.0 version does not have this interface.

## The second method

> From Source
To install pachctl from source, we assume you’ll be compiling from within $GOPATH. So to install pachctl do:
$ go get github.com/pachyderm/pachyderm
$ cd $GOPATH/src/github.com/pachyderm/pachyderm
$ make install

This method  provides the pachctl with the version 1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48. This version has the interface we require, but it cannot work in pipeline operation since the version conflicts I mentioned in #778 .

##Work around
I use the 1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48 version when deploying the Pachyderm. After that I use the version 1.1.0 to replace the latest version, which works for this problem. However, I regard it as an expedient and please check the code to rectify it.

**Comment by ShengjieLuo** [comment]
RE-test the Pachyderm with new master-version today. The version conflict and json problem has been solved. Thanks ! @jdoliner You can close the issue for it has been solved now.

**Comment by jdoliner** [comment]
Glad that worked!
