### ISSUE TITLE
Better versioning

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#78]
A few things we could use versioning wise.

- `--version` flag, we should be able to pass that to our services to get their versions
- `/version` route, it might also be nice to be able to get a version from running services
- Versioned api. This might be a bit farther out but it would be nice to be able to post to `pfs/<version>/file/foo` and know that I'm using a particular version of the API.

**Comment by peter-edge** [comment]
https://github.com/pachyderm/pachyderm/commit/f6dc3b9dc1a073c4f61db4f4822965f058aa12ec
