### ISSUE TITLE
Getting Started... without a credit card

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#789]
Love what you're doing here!

I was hoping you might provide some advice to someone who wants to play with a pachyderm cluster but doesn't have a credit card. Maybe like teenagers or something?

"Mom, can you sign me up for Google Cloud?"

Well, I guess it doesn't sound that crazy...

**Comment by ShengjieLuo** [comment]
@rexmortus You can try the Pachyderm on AWS or Google GCE if you have the account. Otherwise, a local  host (a server with 4CPU and 16GB memory) is enough to do some simple tests, which is my experiment environment. If you do not deploy it to a real commercial environment, it would certainly be okay.

**Comment by rexmortus** [comment]
Thanks @ShengjieLuo :+1:

**Comment by JoeyZwicker** [comment]
Obviously this doesn't let you leverage the distributed properties of Pachyderm, but you can easily run pachyderm locally on OSX or Linux using our Quickstart guide. We've got a MUCH better guide coming within a week that shows you how to easily run Pachyderm in [minikube] (http://kubernetes.io/docs/getting-started-guides/minikube) locally too. It hasn't been pushed out yet but you can also email me and I'll give you early access.

**Comment by rexmortus** [comment]
@JoeyZwicker fantastic news! I reluctantly gave Google yet another CC # but frankly I have to scratch the pachyderm itch. Looking forward to the OS X guide. :smile:

**Comment by JoeyZwicker** [comment]
Yeah no need to spend money if you just want to try things out locally. Below is an abridged version of the guide using minikube. That should get you most of the way and feel free to post here if you run into any problems you can figure out.

[This Minikube Guide](http://kubernetes.io/docs/getting-started-guides/minikube) will get you kubernetes running locally.

You then just need to get pachctl installed; 

```shell
$ brew tap pachyderm/tap && brew install pachctl
```
Deploy Pachyderm
```
kubectl create -f https://pachyderm.io/manifest.json
```
Wait for pachd pods to show "running" and then forward the ports:
```
kubectl get all
#copy one of the pachd pod names
kubectl port-forward <pachd_pod_name> 30650:650 &
```

`pachctl version` should return:
```shell
$ pachctl version
COMPONENT           VERSION
pachctl             1.1.0
pachd               1.1.0
```
