### ISSUE TITLE
Problems with Google Container Engine guide

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#792]
:clap: so close!

I've created the cluster and run `make MANIFEST=manifest launch`, which hangs forever.

The issue is that Kubernetes apparently cannot pull the pachyderm images.

This is the error produced by the `pachd-init` job:

```
Failed to pull image "pachyderm/pachd:1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48": Tag 1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48 not found in repository docker.io/pachyderm/pachd
Error syncing pod, skipping: failed to "StartContainer" for "pachd-init" with ErrImagePull: "Tag 1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48 not found in repository docker.io/pachyderm/pachd"
```

I'm new to Docker generally and I'm feeling rather defeated at this stage.

Any advice on how I can get my cluster pulling the pachyderm images would be most welcome.

Thanks! :heart:

**Comment by JoeyZwicker** [comment]
Sorry you ran into this @rexmortus! You've got a version problem in that you're using  pachd 1.1.0-ba43 but we only have v1.1.0 container pushed to DockerHub. You'll either need to build the container from HEAD or change the manifest to v1.1.0 instead.

**Comment by jdoliner** [comment]
Hey @rexmortus, as @JoeyZwicker mentioned this is a version mismatch issue. Probably the easiest way for you to get pachyderm up and running would be to deploy v1.1.0. To do that all you need to do is:

```
$ git checkout v1.1.0
$ make launch
```

Sorry you ran into this, it should get a lot better starting with v1.2.0.

**Comment by rexmortus** [comment]
Thanks @JoeyZwicker and @jdoliner :+1: 

![2016-09-08-085828_958x836_scrot](https://cloud.githubusercontent.com/assets/308827/18331453/784be128-75a2-11e6-92e0-e725477b063b.png)

I deeply appreciate the support. I can't wait to get started! First project is to write a scraper for [Melbourne Open Data](https://data.melbourne.vic.gov.au/).
