### ISSUE TITLE
where is graphql code?

### ISSUE THREAD

**Issue by triyes** [pachyderm/pachyderm#7930]
When query the files of a commit in https://public-sandbox.workspace.pachyderm.io/, web server calls graphql interface whose name is "getFiles", but I cannot find the code about it.

**Comment by jrockway** [comment]
The GraphQL server is actually a part of our Console product, which is not open source at this time.  It's not a full version of the Pachyderm API, just convenience for the implementation of that product.  

If you want to talk to Pachyderm with an API, you can use our go client (in this repo), Python client (https://github.com/pachyderm/python-pachyderm) or Node client (https://github.com/pachyderm/node-pachyderm).  These actually use GRPC and not GraphQL.

**Comment by triyes** [comment]
> The GraphQL server is actually a part of our Console product, which is not open source at this time. It's not a full version of the Pachyderm API, just convenience for the implementation of that product.
> 
> If you want to talk to Pachyderm with an API, you can use our go client (in this repo), Python client (https://github.com/pachyderm/python-pachyderm) or Node client (https://github.com/pachyderm/node-pachyderm). These actually use GRPC and not GraphQL.

ok, thanks @jrockway
