### ISSUE TITLE
Chained Pipelines not Triggering Properly

### ISSUE THREAD

**Issue by alexsbromberg** [pachyderm/pachyderm#797]
I'm having and issue with pipeline not being triggered by certain commits. Here's my setup, i have four repos connected like so:

C <-- B <-- A
^
|   
| ------ D

Here's my order of events with what I expected to happen:

- create repo A
- create repo D
- commit to repo A
- commit to repo D
- create pipeline connecting B to A
- create pipeline connecting C to B and D
- one job get triggered for C (once B and D both have data) and C sees data in both B and D

Here's what I actually see (note difference in last step)

- create repo A
- create repo D
- commit to repo A
- commit to repo D
- create pipeline connecting B to A
- create pipeline connecting C to B and D
- one job get triggered for C (once B and D both have data) and C sees data in D, **but C doesn't see and data in B**

When I try creating the pipelines before making the initial commits the job between A and B gets triggered, but the job to from B and D to C doesn't get triggered. 

I've looked at the environment variables pachyderm generates and `PACH_D_COMMIT_ID` is a commit id but `PACH_B_COMMIT_ID` is an empty string.

If I take repo A out the equation, then C sees data from both B and D as expected

Here's what my pipeline spec looks like:
```
{
  "pipeline": {
    "name": "B"
  },
  "transform": {
    "image": "custom_image",
    "cmd": [ "/usr/bin/R", "--vanilla"],
    "stdin": [
       CODE]
  },
  "parallelism": 1,
  "inputs": [
    {
      "repo": {
        "name": "A"
      },
      "method": {
        "partition": "file",
        "incremental": "DIFF"
      }
    }
  ]
}
{
  "pipeline": {
    "name": "C"
  },
  "transform": {
    "image": "custom_image",
    "cmd": [ "/usr/bin/R", "--vanilla"],
    "stdin": [
       CODE]
  },
  "parallelism": 1,
  "inputs": [
    {
      "repo": {
        "name": "B"
      },
      "method": {
        "partition": "file",
        "incremental": "DIFF"
      }
    },
    {
      "repo": {
        "name": "D"
      },
      "method": {
        "partition": "block",
        "incremental": "DIFF"
      }
    }
  ]
}
```

I've tried this on 1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48 of pachctl and pachd as well as version 1.1.0 and have seen the same results.

I've been struggling with this for a couple of days and have had to reinstall a couple of different of versions of pachyderm to confirm what i'm seeing. I can run the fruitstand example fine, so its not like all chained commits are causing the problem. Does anyone know what the issue could be? Am I missing something obvious?

**Comment by alexsbromberg** [comment]
As some additional info, when my job for repo C runs and it tries to copy the file it expects in repo B, i'm seeing the following error:
```
ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{}}}},"name":"B","err":"operation not permitted"}
```

**Comment by jdoliner** [comment]
Hi @alexsbromberg, sorry you ran into this. Definitely doesn't sound like the behavior I'd expect either. Would you mind gathering a bit more information for me about which jobs run? You can do this with: `pachctl list-job` which will show you all the jobs that have run. Then for each of those do `pachctl inspect-job <job-id>` which will give extended information about the jobs and what they're running on.

**Comment by alexsbromberg** [comment]
Here's the output from `pachctl list-job`
```
ID                                 OUTPUT                                               STARTED             DURATION            STATE               
5d51743c6f52cf4e18257a26aa7e8984   C/e68bffd9ed71483f9949ab5841ba1ede   10 seconds ago      3 seconds           success    
055ba2f24ca92c1d56b110772039fdbc   B/6de392756ce04674a79b4b492164e434        20 seconds ago      9 seconds           success
```

From `pachctl inspect-job 5d51743c6f52cf4e18257a26aa7e8984`
```
ID: 5d51743c6f52cf4e18257a26aa7e8984 
Started: 53 seconds ago 
Duration: 3 seconds 
State: success
Parallelism: 1
Inputs:
NAME                 COMMIT                             PARTITION           INCREMENTAL              
D   46d854308eab498abeec4d61321e0e1c   BLOCK               %!t(pps.Incremental=1)   
Transform:
{
  "image": "custom_image",
  "cmd": [
    "/usr/bin/R",
    "--vanilla"
  ],
 "stdin": [
  <code truncated>
 ]
}
```

From `pachctl inspect-job 055ba2f24ca92c1d56b110772039fdbc`

```
ID: 055ba2f24ca92c1d56b110772039fdbc 
Started: 3 minutes ago 
Duration: 9 seconds 
State: success
Parallelism: 1
Inputs:
NAME                COMMIT                             PARTITION           INCREMENTAL              
A          f82b0531fac84cdc9159a5a2bc64f3f1   FILE                %!t(pps.Incremental=1)   
Transform:
{
  "image": "custom_image",
  "cmd": [
    "/usr/bin/R",
    "--vanilla"
  ],
  "stdin": [
    <code truncated>
  ]
}
```

**Comment by jdoliner** [comment]
Thanks for that, was able to reproduce your issue with a test here: https://github.com/pachyderm/pachyderm/pull/805. Will take a crack at fixing the issue tomorrow.

**Comment by jdoliner** [comment]
Just tried reproducing on the pfs-refactor branch. It still fails but differently than on the the previous pfs. Rather than triggering a job that can only see data from 1 repo it doesn't trigger a job at all.

@derekchiang could you try running the test on the pfs refactor branch when you get a chance and see if you can understand the behavior?

**Comment by derekchiang** [comment]
Fixed in the refactor branch.  Will keep the issue open until we merge.

**Comment by jdoliner** [comment]
:rocket:! What was the issue?
