### ISSUE TITLE
Implement new API

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#800]
This happens after pfs-refactor gets merged, but before 1.2 release.

There are breaking API changes that we want to make after the merge.

**Comment by sjezewski** [comment]
Starting to make a list of such changes.

1) Update `PutFile()` and `GetFile()`

Refer to the comment at `src/server/pfs/server/server_test.go#L1421`

We want to update `PutFile()` and `GetFile()` to only accept commit not repo (since commit's have a repo), because this makes validating document existence easier (since we don't have to do the extra hop for repo).

2) Remove redundant code for handling ambiguous commit IDs

**Comment by derekchiang** [comment]
* To generate `CommitInfo` which has a `ParentCommit` field, we have to go to the database to find the parent commit.  But once all commits are of the form `master/2`, parent commits should be self-evident.

**Comment by jdoliner** [comment]
@derekchiang close this? Or is there still more you want to do?

**Comment by derekchiang** [comment]
Fixed by #831
