### ISSUE TITLE
Add rethinkdb readiness check

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#801]
Right now we wrap `make test` w a single `make launch-test-rethinkdb` sub task. (Before we had this subtask running on each suite that required it ... so that e.g. if you run `make fuse` it'll spin up the dependencies it needs to run the tests).

The problem is that the start time of rethinkdb is flaky. We know this lesson well from how `pachd` starts up (if it can't connect, it panics, and k8s reschedules the pod until it connects).

However, for the testing purposes it would be nice to have something block until its ready. Even the fix we have in place now will err sometimes if rethink happens to take longer than 20s to startup.

**Comment by jdoliner** [comment]
Do you think we could make things simpler and just use the rethink server that's spun up by `make launch`? That already has readiness checking. And it has the really nice advantage that it's guaranteed to be deployed the same way as you get from the manifest. So we'll avoid issues resulting from things like different versions of rethink being spun up?

**Comment by sjezewski** [comment]
Yea, thats a good point. However we want to make sure `make test-fuse` and `make test-local` also launch the cluster to make sure they have what they need for the tests. So, I'll:

- Make each suite that needs it launch the cluster in its make task (`make test`, `make test-fuse`, `make test-local`)
- Update `make launch` to do nothing if it detects that the cluster is already up (so that its idempotent)

This way we'll only launch the cluster once on CI, not three times.

----

Then, I'll go ahead and add the readiness probe to the manifest for rethinkdb. That should make pachd startup cleaner (and less confusing to users). [I'll be using their own script for this](https://github.com/rosskukulinski/kubernetes-rethinkdb-cluster/blob/master/rethinkdb-quickstart.yml#L107)

**Comment by sjezewski** [comment]
Ok, this is all done on the `pfs-refactor` branch (just using the `launch-dev` task for spinning up DB, updating rethinkDB in manifest to use readiness probe).

One note -- if you're using docker-machine now, you'll need to forward the `28015` port to be able to run the tests locally.

**Comment by sjezewski** [comment]
I got this partly working on `pfs-refactor` branch, but couldn't get local tests suites connecting to the rethink instance (which I'm sure is some k8s networking config).

However, I left the readiness probe in place, but there seem to be a few issues with it.

A) For a user on GCE, it wasn't working at all

They see the following logs:

```shell
  54m        1s        655    {kubelet gke-pach-cluster-default-pool-26852678-alpi}    spec.containers{rethink}    Warning        Unhealthy    Readiness probe failed: Get http://localhost:8080/: dial tcp 127.0.0.1:8080: getsockopt: connection refused```

I'd expect maybe a few failures in the course of spinning this up, but it really shouldn't take that long (54 minutes and not up)

B) They reported that they saw the following when executing the curl manually:

They did `curl localhost:8080` and got the loading message below

```html
    <body>
        <div class="alert global_loading">Loading...</div>
    </body>
```

Which I think is the message you see when the dashboard isn't connected to the backend? In which case, the server responding w any payload and a 200 gives us the wrong signal for a readiness check. In other words .... it'll respond before the backend is truly ready.

**Comment by sjezewski** [comment]
Oh one thing that comes to mind to explain the first effect. 

I used the defaults I saw elsewhere to specify the total number of times it'll retry the readiness probe. If they're deploying k8s on a smaller VM, its possible it'll take rethink longer to startup, but by that time we'll have spent all of our readiness checks. We should consider updating that number (or removing it if it'll just try indefinitely)

**Comment by jdoliner** [comment]
Readiness check should probably keep going indefinitely.

We also might want to consider removing it, at least for non-dev clusters, it seems like it's an added liability to a functional system coming up and we already have a pretty effective readiness check for pachd which can't pass unless rethink has also come up correctly.

**Comment by jdoliner** [comment]
Do our tests depend on the readiness check?

**Comment by sjezewski** [comment]
Yea, I'll remove it for now. If we find we want it later we'll need to vet these issues to make sure it works.

Right now the integration tests implicitly rely on the cluster being up, so rely on the readiness check. But as you said, the pachd startup mechanism was working before without this check.

**Comment by sjezewski** [comment]
[Ok, removed it](https://github.com/pachyderm/pachyderm/commit/2ac79ca4018fd6a2f5dae82192adfa31c094f729)

Putting that link here for posterity for when we do look at this again.

**Comment by sjezewski** [comment]
Rethink is no more. Closing.
