### ISSUE TITLE
ADDRESS environment variable not picked up by `pachctl`

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#803]
On Ubuntu 14.04, using `gvm` running `go1.6` and `1.1` of Pachyderm.

I set the environment variable `ADDRESS` to `<external IP of a kubernetes node>:30650`

Then, run `pachctl` I see:

```
Envronment variables:
  ADDRESS=0.0.0.0:30650, the server to connect to.
```

It seems like `pachctl` isn't using the address I've specified.

Is this just a cosmetic thing, and behind the scenes it's using the address I've specified?

**Comment by ShengjieLuo** [comment]
@rexmortus Could you check the `env | grep ADD` to see whether the environment has been loaded in your system. Such function has been used up till now in my environment with no problems. Also, you can close #802 , since there is no content in this issue, thanks.

**Comment by rexmortus** [comment]
Thanks @ShengjieLuo 

```
env | grep ADD
ADDRESS=104.155.230.41:30650
```

Yep, the variable is there in the environment.

**Comment by ShengjieLuo** [comment]
@rexmortus  Have no idea about it. Could you please show your result of the command `pachctl version` ? Or we need to ask for help from other members.

**Comment by rexmortus** [comment]
Thanks @ShengjieLuo I can tell that you care about the community!

```
$ pachctl version
COMPONENT           VERSION             
pachctl             1.1.0               
pachd               1.1.0    
```

^ Looks good

`make logs` produces nothing out of the ordinary.

```
get pods -o wide
NAME            READY     STATUS    RESTARTS   AGE       IP          NODE
etcd-924uc      1/1       Running   0          5h        10.56.1.3   gke-pachyderm-default-pool-1037cff7-y8s2
pachd-h8fcn     1/1       Running   3          5h        10.56.1.5   gke-pachyderm-default-pool-1037cff7-y8s2
pachd-s109q     1/1       Running   3          5h        10.56.0.6   gke-pachyderm-default-pool-1037cff7-plg8
rethink-pqufb   1/1       Running   0          5h        10.56.2.5   gke-pachyderm-default-pool-1037cff7-bw9x
```

Looks like those are going OK, too?

**Comment by ShengjieLuo** [comment]
@rexmortus If you have `pachctl version` correct, it means that your pachctl can have a talk with pachd pods. If we analysis the code of Pachyderm, we will find that pachctl (client) need to make a connection to pachd(server), and pachd would tell pachctl the exact version you have. 
In other word, if you do `pachctl version` right, actually you have got the correct address to connect the pachd server. So show me where you get this error information and what command you have done, also the log information is necessary for debug.

**Comment by rexmortus** [comment]
Thanks again @ShengjieLuo.

As I suspected, it's just a cosmetic issue.

When I have `$ADDRESS` set to an IP with `pachd` running, I get this result:

```
pachctl version
COMPONENT           VERSION                                          
pachctl             1.1.0-2a4d2ddd55192cf80aa7c9b162290489d1ab7290   
pachd               1.1.0    
``` 

However, when I run `pachctl` with no arguments and the list of commands appears:

```
$ pachctl
Access the Pachyderm API.

Envronment variables:
  ADDRESS=0.0.0.0:30650, the server to connect to.

Usage:
  pachctl [command]
...
```

Two things to note about the above message.

1) There is a typo. It says "Envronment" when it should say "En**i**vronment".
2) It says that $ADDRESS is set to `0.0.0.0:30650`

Which, as we've determined, it's not.

Indeed, when I change `ADDRESS` to an IP where no `pachd` is running, `pachctl version` returns what I'd expect - an error!

```
$ export ADDRESS=0.0.0.0:30650
$ pachctl version
COMPONENT           VERSION                                          
pachctl             1.1.0-2a4d2ddd55192cf80aa7c9b162290489d1ab7290   
pachd               (version unknown) : error connecting to pachd server at address (0.0.0.0:30650): context deadline exceeded
```

So as I've discovered, it would seem that this is just a cosmetic issue, although it is more a than bit confusing.

**Comment by ShengjieLuo** [comment]
Glad you work on this issue. Maybe we should change the information showed in the command `pachctl`.  It's not a difficult work.

**Comment by sambooo** [comment]
@rexmortus [the source](https://github.com/pachyderm/pachyderm/blob/114c5d04df2b4cb9520ed84faed6033a239c42d2/src/server/cmd/pachctl/cmd/cmd.go#L41) of that output shows that it's a hardcoded value that (probably) isn't meant to reflect the environment you're running in. It's not really clear from the output that it's just listing defaults, so maybe that's worth noting there.

@jdoliner I can go through and see if there are any similar occurrences like this that could cause confusion and fix them. Worth doing or nah?

Also worth noting the irony of the typo here:

> 1) There is a typo. It says "Envronment" when it should say "En**iv**ronment".

😀

**Comment by jdoliner** [comment]
@sambooo yeah, the intention of putting `ADDRESS=0.0.0.0:30650` is to indicate the default value. I can see how that's confusing though seeing as that line right there is the one thing you'd never want to actually type. I'd change to something like `ADDRESS, the server to connect to, defaults to 0.0.0.0:30650`.

Might as well fix the type while you're at it, although the correct spelling is actually Environment isn't it?

**Comment by rexmortus** [comment]
I would like to take a moment and acknowledge the hilarity of me offering a correction to a typo, only to  offer a typo myself.

GO ME! :boom:

@jdoliner now that I understand the intent, it makes more sense. Maybe an explicit label would be helpful, as I (wrongly assumed) that line was reflecting the current environment's configuration.
