### ISSUE TITLE
postgresql database no data

### ISSUE THREAD

**Issue by hongery** [pachyderm/pachyderm#8042]
The local installation of pachyderm via minikube, the browser and pachctl commands work fine, but when I enter the postgresql database, the pachyderm database only uses one table, migrations. Why don't I see other tables.

pachyderm=> \d
            List of relations
 Schema |    Name    | Type  |   Owner
--------+------------+-------+-----------
 public | migrations | table | pachyderm
(1 row)

pachyderm=> select * from migrations
pachyderm-> ;
 id |                        name                        |         start_time         |          end_time
----+----------------------------------------------------+----------------------------+----------------------------
  0 | init                                               | 2022-08-04 07:00:01.57073  | 2022-08-04 07:00:01.57073
  1 | create storage schema                              | 2022-08-04 07:00:01.581224 | 2022-08-04 07:00:01.581224
  2 | storage tracker v0                                 | 2022-08-04 07:00:01.588252 | 2022-08-04 07:00:01.588252
  3 | storage chunk store v0                             | 2022-08-04 07:00:01.648552 | 2022-08-04 07:00:01.648552
  4 | storage fileset store v0                           | 2022-08-04 07:00:01.658555 | 2022-08-04 07:00:01.658555
  5 | create license schema                              | 2022-08-04 07:00:01.665324 | 2022-08-04 07:00:01.665324
  6 | license clusters v0                                | 2022-08-04 07:00:01.66821  | 2022-08-04 07:00:01.66821
  7 | create pfs schema                                  | 2022-08-04 07:00:01.674234 | 2022-08-04 07:00:01.674234
  8 | pfs commit store v0                                | 2022-08-04 07:00:01.677326 | 2022-08-04 07:00:01.677326
  9 | create identity schema                             | 2022-08-04 07:00:01.687515 | 2022-08-04 07:00:01.687515
 10 | create identity users table v0                     | 2022-08-04 07:00:01.690692 | 2022-08-04 07:00:01.690692
 11 | create identity config table v0                    | 2022-08-04 07:00:01.696666 | 2022-08-04 07:00:01.696666
 12 | create auth schema                                 | 2022-08-04 07:00:01.703177 | 2022-08-04 07:00:01.703177
 13 | create auth tokens table v0                        | 2022-08-04 07:00:01.70568  | 2022-08-04 07:00:01.70568
 14 | license clusters v1                                | 2022-08-04 07:00:01.712642 | 2022-08-04 07:00:01.712642
 15 | create collections schema                          | 2022-08-04 07:00:01.715995 | 2022-08-04 07:00:01.715995
 16 | create collections trigger functions               | 2022-08-04 07:00:01.718813 | 2022-08-04 07:00:01.718813
 17 | create collections                                 | 2022-08-04 07:00:01.730171 | 2022-08-04 07:00:01.730171
 18 | license clusters client_id column                  | 2022-08-04 07:00:01.794982 | 2022-08-04 07:00:01.794982
 19 | identity config token lifetime                     | 2022-08-04 07:00:01.797969 | 2022-08-04 07:00:01.797969
 20 | create license collection                          | 2022-08-04 07:00:01.800718 | 2022-08-04 07:00:01.800718
 21 | add rotation_token_expiry to identity.config table | 2022-08-04 07:00:01.807849 | 2022-08-04 07:00:01.807849
 22 | move enterpriseconfig from etcd -> postgres        | 2022-08-04 07:00:01.81168  | 2022-08-04 07:00:01.81168
 23 | remove old enterpriseconfig record from etcd       | 2022-08-04 07:00:01.81928  | 2022-08-04 07:00:01.81928
 24 | create pfs cache v1                                | 2022-08-04 07:00:01.822251 | 2022-08-04 07:00:01.822251
(25 rows)

**Comment by BOsterbuhr** [comment]
@hongery Have you preformed any actions that would make any other table? Try creating a repo and then add data to it. What tables do you see after doing that?

**Comment by hongery** [comment]
> @hongery Have you preformed any actions that would make any other table? Try creating a repo and then add data to it. What tables do you see after doing that?

## DB
I have no name!@postgres-0:/$ psql -h localhost -p 5432 -U pachyderm -d pachyderm --password
Password:
psql (13.3)
Type "help" for help.

pachyderm=> \d
            List of relations
 Schema |    Name    | Type  |   Owner
--------+------------+-------+-----------
 public | migrations | table | pachyderm
(1 row)

pachyderm=> \l
                                   List of databases
   Name    |   Owner   | Encoding |   Collate   |    Ctype    |    Access privileges
-----------+-----------+----------+-------------+-------------+-------------------------
 dex       | pachyderm | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/pachyderm          +
           |           |          |             |             | pachyderm=CTc/pachyderm
 pachyderm | pachyderm | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/pachyderm          +
           |           |          |             |             | pachyderm=CTc/pachyderm
 postgres  | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres            +
           |           |          |             |             | postgres=CTc/postgres
 template1 | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres            +
           |           |          |             |             | postgres=CTc/postgres
(5 rows)

pachyderm=> \d
            List of relations
 Schema |    Name    | Type  |   Owner
--------+------------+-------+-----------
 public | migrations | table | pachyderm
(1 row)

pachyderm=> \c dex
Password:
You are now connected to database "dex" as user "pachyderm".
dex=> \d
              List of relations
 Schema |      Name       | Type  |   Owner
--------+-----------------+-------+-----------
 public | auth_code       | table | pachyderm
 public | auth_request    | table | pachyderm
 public | client          | table | pachyderm
 public | connector       | table | pachyderm
 public | device_request  | table | pachyderm
 public | device_token    | table | pachyderm
 public | keys            | table | pachyderm
 public | migrations      | table | pachyderm
 public | offline_session | table | pachyderm
 public | password        | table | pachyderm
 public | refresh_token   | table | pachyderm
(11 rows)

## pachctl
hongery@ubuntu:~$ pachctl list repo
NAME       CREATED      SIZE (MASTER) DESCRIPTION
model      19 hours ago ≤ 0B          Output repo for pipeline model.
raw_data   19 hours ago ≤ 5.49KiB
parameters 19 hours ago ≤ 123B
data       19 hours ago ≤ 0B
reduce     21 hours ago ≤ 0B          Output repo for pipeline reduce.
map        21 hours ago ≤ 0B          Output repo for pipeline map.
scraper    21 hours ago ≤ 115.1KiB    Output repo for pipeline scraper.
urls       21 hours ago ≤ 81B
edges      4 days ago   ≤ 167.1KiB    Output repo for pipeline edges.
iris       4 days ago   ≤ 285.6KiB
labels     4 days ago   ≤ 285.6KiB
images     4 days ago   ≤ 760.7KiB

BUT，No tables in the database

**Comment by PFedak** [comment]
We use separate schemas for most tables. The `\dn` command will list schemas, and you can see several tables under the `collections` schema, for example, via `\dt collections.`. I'll close for now, but feel free to reopen if something isn't working or you are trying to do something specific which requires more information about our postgres usage.
