### ISSUE TITLE
Issue Creating New Branch From Existing Branch

### ISSUE THREAD

**Issue by alexsbromberg** [pachyderm/pachyderm#806]
How can i create a new branch in a repo that branches from an existing commit (as opposed to starting out empty)? Lets say i have a repo `test` with the following commits already in it:
```
BRANCH              ID                                 PARENT                             STARTED             FINISHED            SIZE                
                    6a6e996150f94524be38f5999363ae8a   6d594ceb2d454be583ac020b68884851   11 minutes ago      10 minutes ago      2.818 MiB           
master              939b4ca31d1a4671a7d81557663706c4   35610db5c5e44e37b4ebfb41bcb1fcad   13 minutes ago      13 minutes ago      2.818 MiB           
dev                 6d594ceb2d454be583ac020b68884851   <none>                             15 minutes ago      14 minutes ago      2.818 MiB           
master              35610db5c5e44e37b4ebfb41bcb1fcad   <none>                             15 minutes ago      15 minutes ago      2.818 MiB 
```

As you can see, the most recent commit in that repo has the commit labeled `dev` as its parents. This was straight forward to do via `pachctl start-commit test -p 6d594ceb2d454be583ac020b68884851`.

However, if I try to start and new commit while specifying both the branch name and the parent like `pachctl start-commit test new_branch -p 6a6e996150f94524be38f5999363ae8a` I got the following error:
```
branch new_branch already exists as 6a6e996150f94524be38f5999363ae8a, can't create with 6a6e996150f94524be38f5999363ae8a as parent
```
Then, when i try to run `pachctl list-commit test` I get:
```
commit 72b09176bd864f268f0c8b45d9afed45 not found in repo test
```
and I don't get the list of commits in the repo.

Now, reading the docs of the go api, it does seem like specifying both a branch name and a parent id shouldn't really work. But, my question is, how can I start a commit that has an existing branch as its parent, but gets assigned a new branch name?

Also, I think its a bug that i can't view the list of commits after making this ill formed request (i can still make new commits).

Here's my pachyderm version:
```
COMPONENT           VERSION                                          
pachctl             1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48   
pachd               1.1.0-ba43f31be2be7e013f1373eac6581f9093f37f48
```

Also, thanks for being so responsive on the issue reports.

**Comment by jdoliner** [comment]
Hi @alexsbromberg, sorry you hit this. The way you were trying to make a branch is supposed to work but I think you hit a bug in pfs. We're about to merge in a big refactor of pfs that we've been working on that I'm hoping will fix this issue because it handles branches in a different and much more consistent way. I'm going to add this issue to the 1.2 to milestone so that we remember to check that it works before shipping 1.2.

**Comment by sjezewski** [comment]
Just to add to jd's comments ... I'll explain how this might look once 1.2 lands.

Most often users are going to want to start a new commit at the `HEAD` of a branch. This workflow looks like this:

```shell
$pachctl create-repo test
$pachctl start-commit test master
e8b9e6bc428547aa9bd0286068eee3e1
$pachctl finish-commit test master
$pachctl list-commit test
BRANCH              ID                                 PARENT              STARTED             FINISHED            SIZE                
master              e8b9e6bc428547aa9bd0286068eee3e1   <none>              10 seconds ago      4 seconds ago       0 B                 
$pachctl start-commit test master
46e286b0c88e439c88937a9370b01366
$pachctl finish-commit test master
$pachctl list-commit test
BRANCH              ID                                 PARENT                             STARTED              FINISHED             SIZE                
master              46e286b0c88e439c88937a9370b01366   e8b9e6bc428547aa9bd0286068eee3e1   23 seconds ago       17 seconds ago       0 B                 
master              e8b9e6bc428547aa9bd0286068eee3e1   <none>                             About a minute ago   About a minute ago   0 B                 
```

In the other case (where you want to start a new branch off of a commit) you specify both the branch and the commitID as you did above:

```shell
$pachctl start-commit test dev -p 46e286b0c88e439c88937a9370b01366
49309f5820e3439f81e21c2dad30571f
$pachctl finish-commit test dev
$pachctl list-commit test
BRANCH              ID                                 PARENT                             STARTED             FINISHED            SIZE                
master              46e286b0c88e439c88937a9370b01366   e8b9e6bc428547aa9bd0286068eee3e1   6 minutes ago       6 minutes ago       0 B                 
master              e8b9e6bc428547aa9bd0286068eee3e1   <none>                             7 minutes ago       7 minutes ago       0 B                 
dev                 49309f5820e3439f81e21c2dad30571f   46e286b0c88e439c88937a9370b01366   11 seconds ago      5 seconds ago       0 B                 
```

**Comment by alexsbromberg** [comment]
Cool. I'll check that it works on my end too once that refactor is merged in.

**Comment by sjezewski** [comment]
Refactor is merged onto master now, and the new behavior is supported
