### ISSUE TITLE
Docs Sidebar dropdown menus

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#810]
Read The Docs theme sidebar menus are incredibly confusing to navigate. Clicking on a subsection opens up the menu in multiple places (see screenshots below). I'd be perfectly fine with the sidebar being completely static navigation without any dropdown menus. While I'm working on more content, @sjezewski can you take a look at figuring out this formatting stuff because it'll likely involve diving into the theme code a bit. 

![screen shot 2016-09-08 at 3 07 02 pm](https://cloud.githubusercontent.com/assets/1795008/18368727/58c06eb2-75d6-11e6-93bc-35bbbaf6fca3.png)

**Comment by sjezewski** [comment]
Looks like we're referencing the same document in a few places.

I'm betting they did the naive jquery thing to add a click listener, e.g. something like:

```javascript
$(".creating-analysis-pipelines").click(
function() {
   $(".creating-analysis-pipelines div").toggle()
}
)
```

**Comment by sjezewski** [comment]
[I was close](https://github.com/snide/sphinx_rtd_theme/blob/master/js/theme.js#L138)

But basically that function returns too many things ... not the actual content you want to drill down on

**Comment by JoeyZwicker** [comment]
We thought that deleting the extra toc tree in the Analyze Your Data section would solve this. I just did that and it doesn't fix it. Also seeing some other odd behaviors like sections I've deleted still showing up in the sidebar -- I don't think it's caching because I've reset the cache in my browser and I'm just viewing local files.

**Comment by JoeyZwicker** [comment]
nevermind, it was a caching problem of sorts. I didn't blow away my past build files correctly like I thought I had.

**Comment by JoeyZwicker** [comment]
The major issues with multiple references has been solved. We just need to check on getting `nagivation_depth

**Comment by sjezewski** [comment]
Ok, updated the `doc-sidebar` branch to handle that option.

@joey if you do:

```shell
pip uninstall sphinx_rtd_theme
pip install -r requirements.txt
```

Then you should have this option working for your local setup. We may hit a snag when we deploy to RTD, but we'll see when we cross that bridge

**Comment by JoeyZwicker** [comment]
I hadn't tried this locally ( I will shortly), but it doesnt seem to be working on the live RTD site.

**Comment by JoeyZwicker** [comment]
@sjezewski Yeah it seems to have built correctly on https://readthedocs.org/projects/pachyderm/builds/ but still has the dropdown on RTD. I'm going to test locally now, but open to theories if you have any

**Comment by JoeyZwicker** [comment]
Works locally for me. not sure why its not working on RTD.

**Comment by JoeyZwicker** [comment]
@sjezewski Does this solve our problem perhaps? RTD has a place to declare your requirement file? I would assume it automatically grabs its from the root of the project, but maybe not? https://readthedocs.org/dashboard/pachyderm/advanced/

**Comment by sjezewski** [comment]
Yup, that looks like it should work. I'll try it out

**Comment by sjezewski** [comment]
That was part of it. The other part was updating our conf.py file. Pr incoming

**Comment by sjezewski** [comment]
This is live
