### ISSUE TITLE
Include benchmarks in CI

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#813]
@jdoliner has added a benchmark suite (`make bench`).  It'd be nice if we can add it to CI so we don't lose track of changes in performance.

Partially solves #199

**Comment by jdoliner** [comment]
I like this idea in theory, I'm a bit worried that the performance of a travis box is so variable that it will be hard to separate the single from the noise when looking at CI results.
But given that the cost is adding a line to our travis file I can't see a reason not to do it.

**Comment by sjezewski** [comment]
In particular, `TestWriteManyFiles` in the fuse test suite is a stress test. In particular when doing 10k the CI build time is ~30 minutes. At 1k files its 17 minutes. We want to tighten the CI feedback loop, so I'm all for having a lower count for that test.

One thing we can do is run it as a post-job task. This gives us shorter test times but allows us to run benchmarks on CI

**Comment by jdoliner** [comment]
Does a post-job task run and get reported but not block the results from CI coming back? That would be perfect for our needs :)

**Comment by sjezewski** [comment]
duplicate
