### ISSUE TITLE
Parent job output can be racy

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#819]
Reported by @jdoliner.  Right now, a job can run concurrently with its parent job.  But since a job can also access the parent job's output via `/pfs/prev`, there can be a race between the job reading from and the parent job writing to the output commit.

A few obvious solutions:
- Don't start a job until its parent job completes.
- Don't expose `/pfs/prev` at all.
- Have a flag that optionally exposes `/pfs/prev/` and blocks the job until its parent completes.

**Comment by sjezewski** [comment]
fixed
