### ISSUE TITLE
Max file length issue

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#820]
Hit this error trying to run the opencv example:

```
Primary key too long (max 127 characters): "741c40a13a484e088bc29c70427a94a9:/wikipedia/commons/thumb/f/f7/Skoda-museum-mlada-boleslav-rr-091.jpg/800px-Skoda-museum-mlada-boleslav-rr-091.jpg"
```

Seems like we've inherited the key length from rethink's primary key length limit. This may be a bit limiting for people especially since with 33 characters for the commit id we're left only 94 for the filename + directories.

@derekchiang @sjezewski how hard would it be to work around the limit?

**Comment by derekchiang** [comment]
Discussed with @jdoliner offline.  We will be hashing the primary key to make it shorter.
