### ISSUE TITLE
force parallelization on small-sized input data

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#825]
Hi guys, I'm on version 1.1.0 and I was trying to parallelize my pipelines, but I couldn't make it work. So I tried to simply the problem and just run the examples with parallelism enabled. 

In the example of wordcount, when setting `"parallelism": 10` of the `wordcount-map` pipeline, I could see the correct number of docker containers and also see the number by `inspect-job`. I tested this to make sure the parallelization works on at least one example.

But in the example of fruit_stand, when I set `"parallelism": 2` of the `filter` pipeline, I could only see one corresponding docker container and also `parallelism = 1` by `inspect-job`.

I wonder if it's because I didn't set it correctly. Please advise.

**Comment by derekchiang** [comment]
Hi @willguxy , it's not a bug, it's a feature!  Pachyderm automatically detects when the input size is too small to be distributed to the specified number of parallel jobs, and reduce the parallelism automatically to save resources.  The number you specified (2 in this case) serves as an upper bound: Pachyderm promises to spawn no more than this many jobs.

If you had a larger input (~20Mb, for instance), you would've seen 2 jobs.  Let us know if you have more questions!

**Comment by willguxy** [comment]
Thanks for your prompt response. Would like to reopen this issue because in my case I would like to have the parallelization feature on small input data size.

The reason why I would need it is because I'm running a set of models in parallel. Each model transforms the same data set but has different model parameters. They have no overlap and the goal is to run these models in parallel. The output can be stacked as a table consisting of model parameters and corresponding model output.

Model parameters are necessarily small in data size. So it wouldn't trigger the parallelization no matter what. Is there a way to force parallelization?

**Comment by derekchiang** [comment]
Hi @willguxy, your use case makes sense.  Currently, we always partition data for parallel jobs; there isn't a way to run parallel jobs and have them all see the same set of input.

What I'd suggest you to do is to create one pipeline per model.  These pipelines will have the same input, but run with different model parameters.  So every time an input commit comes in, all these pipelines will be triggered with the same input.

Does that make sense?  Does that work for your use case?

**Comment by willguxy** [comment]
@derekchiang Yes it does make sense. The problem though, is that I might need to run hundreds or thousands of such models, and if each of them has a unique pipeline, it becomes harder to manage the jobs and collect the results.

**Comment by derekchiang** [comment]
Hi @willguxy that makes sense.  I think I have a pretty good understanding of your problem now.  Here is what you can do:

First all, you create two repos: `raw_data` and `model_parameters`.

Then, you create a pipeline that runs your model.  The `inputs` section of your pipeline spec will look like this (refer to the [pipeline spec](https://github.com/pachyderm/pachyderm/blob/master/doc/pipeline_spec.md) for a full description of all the flags):

```
"inputs": [
    {
      "repo": {
        "name": "raw_data"
      },
      "method": "global"
    },
    {
      "repo": {
        "name": "model_parameters"
      },
      "method": {
        "partition": "file",
        "incremental": true
      }
    }
]
```

To briefly explain:

* The `global` flag tells Pachyderm that any job should see the entirety of this repo, which is what you want for the `raw_data` repo.

* The `method` of the `model_parameters` input repo tells Pachyderm that this repo should be partitioned by files.  Here I'm assuming that in the `model_parameters` repo, you will have a number of files like `model1.json`, `model2.json`, `model3.json`, etc.

Now, the pipeline will spawn N jobs, where N is bounded by the parallelism you specify.  Each of these jobs will see a subset of your model parameters, and the **entire** `raw_data` repo.

Does that sound like what you want?

**Comment by willguxy** [comment]
@derekchiang many thanks and yes, that's what I want. Does that mean the input data size issue you mentioned earlier is only related the `block` method? So in the above case if I separate the parameters as different files, it wouldn't restrain me from parallelizing the pipeline right?

**Comment by derekchiang** [comment]
Yup, a block is typically 8MB of data, so if your parameters are small, then they might all fit in one block, and as a result only one job gets spawned.  By using the `file` partition method, you are telling Pachyderm to partition input by files, regardless of file size.

Note that Pachyderm is JSON-aware, meaning that you can also have a file called `models.json` that contains a number of JSON objects, each of which corresponds to one model.  Then you'd use the `block` partition method, and Pachyderm will make sure that each block contains one JSON object.  But that's kind of an advanced use case; I'd just use one file per model for simplicity.

**Comment by willguxy** [comment]
@derekchiang Thank you for your detailed explanation. It was very clear. 

Can I request adding scheme of switching on/off the `feature` of constrains on `block` data size to parallelize pipelines? I feel that it will very useful not just in our use case, but in many others as well.

**Comment by willguxy** [comment]
closed because it's not an issue.

**Comment by derekchiang** [comment]
I was mistaken when I said that each JSON object is stored in its own block.  Currently Pachyderm still groups JSON objects into 8MB blocks.

This is an issue when you have a pipeline that gets a small file (< 8MB) which contains a number of JSON objects, and you want to spawn parallel jobs such that each job gets some of the JSON objects.  But currently you can't, since all the objects are in one block.

**Comment by sjezewski** [comment]
Hi there. In v1.4 we have 'datums' which means you can explicitly control how your data is parallelized w file glob patterns, e.g. "/*"

If you're still having this issue, please upgrade to 1.4 and try out the new semantics.

**Comment by sjezewski** [comment]
This issue https://github.com/pachyderm/pachyderm/issues/1515

is where we're tracking the docs for this feature, FYI
