### ISSUE TITLE
https://pachyderm.io/manifest.json has a typo

### ISSUE THREAD

**Issue by jbowles** [pachyderm/pachyderm#826]
lnn 261 and 354 have a typo in the container version. 

Has `"pachyderm/pachd:v1.2.0-RC1"`, should be `"pachyderm/pachd:1.2.0-RC1"`

Dockerhub tag is `1.2.0-RC1` : https://hub.docker.com/r/pachyderm/pachd/tags/

**Comment by JoeyZwicker** [comment]
Thanks @jbowles We'll fix that right away.

**Comment by sjezewski** [comment]
Ah, as part of [this PR](https://github.com/pachyderm/pachyderm/pull/823) we decided to remove support for the manifest on the live URL. 

But I hadn't removed that file from www yet, so its in a funny state. You're right @jbowles - there is a typo. That was from debugging that PR.

Once the PR lands, the new recommended way of launching a pachyderm cluster with the latest manifest is simply:

```
make launch
```

Which uses your version of `pachctl` to generate the manifest directly. So you'll need to make sure you have the latest version of `pachctl`.

If you want to generate the actual manifest file (we do recommend checking it into your codebase), you can do:

```
pachctl deploy --dry-run > somefile.json
```

Which is what `make launch` uses under the hood to deploy the manifest from `pachctl`

Let me know (or feel free to comment on that PR) if this new behavior doesn't suit your needs.

**Comment by sjezewski** [comment]
In the meantime (till that PR lands), I've [fixed the manifest](https://pachyderm.io/manifest.json)

**Comment by jbowles** [comment]
awesome, thanks
