### ISSUE TITLE
slack.pachyderm.io

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#829]
Make slack.pachyderm.io point to https://pachyderm-slack.herokuapp.com/

Also, in order to get the badges to work, what else do we need to do? See https://github.com/rauchg/slackin

**Comment by sjezewski** [comment]
Looks like the badge should work just fine. Once we have the domain hooked in you can use whichever form you want.

The static image one is the one I'd put on github. If you have a link to slack on RTD you might be able to use the fancier one? Not sure if you can embed scripts w rst. I haven't seen a way yet, but there may be a way.

**Comment by sjezewski** [comment]
http://slack.pachyderm.io/ is live now

Sounds like you got the image badge working w the other address. This works now w the new address:

[![Slack Status](http://slack.pachyderm.io/badge.svg)](http://pachyderm.io)

Or in markdown:

```
[![Slack Status](http://slack.pachyderm.io/badge.svg)](http://pachyderm.io)
```
