### ISSUE TITLE
Version differences

### ISSUE THREAD

**Issue by frstie** [pachyderm/pachyderm#836]
I've installed pachctl using homebrew on OSX and have version 1.1.0

The version installed in the manifest URL at https://pachyderm.io/manifest.json is 1.2.0 RC1

This installed OK but had issues with some serialisation when uploading files which I'm guess is a client-server mismatch somewhere.

I spotted issue #826 which is related, so it looks like you're phasing out that online manifest, which makes sense if there are issues with backwards compatibility.

What's my best bet for either getting a 1.1.0 compatible manifest from somewhere? Or should I be upgrading the CLI to the latest?

**Comment by jdoliner** [comment]
Hi @frstie sorry, you hit this. We're in a bit of flux right now regarding versioning as we gear up for the 1.2 release. I think your quickest path to a working cluster would be to use the 1.2.0 release candidate.

If you do:

`brew untap pachyderm/tap && brew tap pachyderm/tap && brew unlink pachctl && brew install pachctl`

That should get you a 1.2.0 version of pachctl.
Then you can just do:

```
pachctl deploy
```

and it'll deploy a matching version of pachd.

**Comment by sjezewski** [comment]
Now that 1.2 has landed, the best way to launch is how @jdoliner described it above. I'm closing this issue, but please re-open if you're still having trouble
