### ISSUE TITLE
pachd-init pod sometimes gets stuck in CrashLoopBackoff after make launch-dev

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#837]
When running e.g. make launch-dev, if you have leftover rethink data from a previous k8s cluster, pachd-init will get stuck in a crash loop with the log:

```
$ kc logs pachd-init-3d8lq
gorethink: Table `pachyderm_pps.JobInfos` already exists. in: 
r.DB("pachyderm_pps").TableCreate("JobInfos", primary_key="JobID")
```

Instead of this, it might be nice if `pachd init` failed gracefully (either by simply exiting, so k8s doesn't keep restarting it, or even by cleaning up the old data)

**Comment by jdoliner** [comment]
Fixed via #995
