### ISSUE TITLE
Downstream job can only see partial output from a parallelized job

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#846]
Hi, 

I ran in the an issue of reading file from pfs folder within the docker container.

My setup is `A + B -> C -> D`, where A and B are inputs to C, and C runs **in parallel**. The problem comes when running D. Here are some log entries of D job:

```0 | 2016-09-16T18:30:43Z ERROR fuse.FileRead {"file":{"file":{"commit":{"repo":{"name":"foo"},"id":"9600a15646e042f1bea0afa5b3cdfe2e"},"path":"/bar.csv"},"shard":{"fileModulus":"1"}},"error":"read more than we need; this is likely a bug"}```
```0 | 2016-09-16T18:30:44Z ERROR fuse.FileRead {"file":{"file":{"commit":{"repo":{"name":"foo"},"id":"9600a15646e042f1bea0afa5b3cdfe2e"},"path":"/bar.csv"},"shard":{"fileModulus":"1"}},"error":"read more than we need; this is likely a bug"}```

and 

```# trying to cat the output of C```
```0 | cat: /pfs/foo/bar.csv: Input/output error```

The job of pipeline D only sees output of one of the parallelized processes from C, but not the rest. eg I use `parallelism: 16` for C, and D can only see 1 output out of all 16.

**Comment by sjezewski** [comment]
Hi there @willguxy - sorry you ran into this.

This looks awfully similar to the bug we found in #833. (My bet is that all but one of your files is larger than a single block)

I'm looking into issue #833 as we speak, and we should have a fix shortly.

**Comment by sjezewski** [comment]
[We have a PR up now](https://github.com/pachyderm/pachyderm/pull/848)

**Comment by willguxy** [comment]
@sjezewski Thank you very much. I pulled the latest code with your fix merged and tested my pipelines. Now everything works like a charm. I'm gonna close this issue for now.
