### ISSUE TITLE
Cancelling a commit can cause unexpected behavior in subsequent commits

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#847]
I encountered this while validating the OpenCV example for the 1.2 release. What I observed:
1. examples/opencv contains three image files (or will, once [pr/830](https://github.com/pachyderm/pachyderm/pull/830) is merged). `images.txt` contains a long image URL, while `images2.txt` and `images3.txt` do not.
2. If I start the pipeline and then run `pachctl put-file images master -c -i examples/opencv/images2.txt`, the pipeline runs successfully. If I then run `pachctl put-file ... images.txt`, Pachyderm doesn't start any jobs for the pipeline. This happens because the file contains a long image URL, which is scraped to a file named with that image URL. RethinkDB rejects the long file name, and the commit is cancelled. This behavior—Pachyderm doesn't start any pipeline jobs after an input commit is cancelled—is expected.
3. If I then run `pachctl put-file ... images3.txt`, Pachyderm also doesn't start any jobs for the pipeline. This is because `HEAD` in `images/master` points to a commit that was cancelled (in step 2), and then the `put-file` operation creates a commit with a parent commit of `HEAD`. Because the commit that we created has a parent commit that was cancelled, Pachyderm doesn't process it. _(Update: see comments below, but `HEAD` doesn't really exist in PFS. I'm leaving this description though, so that subsequent comments make sense)_

We agree that this behavior—running `pachctl put-file ... images3.txt` does not start any jobs`—is unexpected, and there are several things we could change. This issue will document some of our ideas, and then we may create child issues for implementing them.

There are at least two potential problems we've identified:
1. PFS shouldn't reject long filenames
2. Committing after a previous commit was cancelled should typically work.

We've already discussed (1) a fair amount, and in particular we've discussed solving that issue by keying file contents by a long hash of the filename (I forget the RethinkDB limit, but e.g. 127 characters) instead of by the filename itself 

For (2), some thoughts we've raised:
- Pachyderm looks like a stream-based data processing system in many ways. Typically, if you attempt to publish a datum to a stream and the attempt fails, you wouldn't expect that to affect other elements of the stream, you would simply retry (e.g. if processing a stream of financial transactions) or drop it (e.g. if processing a stream of tweets)
- Perhaps `HEAD` shouldn't be moved until the new commit has finished successfully. Alternatively, perhaps `HEAD` should be rolled back if the commit is cancelled or fails. Commits may be cancelled due to e.g. network partitions, so users may not know the state of `HEAD` (and may not be able to figure it out easily)

**Comment by jdoliner** [comment]
I think rolling back might make more sense than waiting to move `HEAD` the reason being that the common workflow here is to do:

```
StartCommit("foo", "master")
PutFile("foo", "master", "file")
FinishCommit("foo", "master")
```

For `PutFile` and `FinishCommit` to work in that way `HEAD` has to point to the newly created but not yet finished commit.

Rolling back seems pretty reasonable to me in terms of semantics, basically it would give us the invariant that cancelled commits are confined to their own branches. The only thing that seems a bit dicy is that we're kinda renaming commits, so when `master/2` gets cancelled we'll want to reclaim the name `master/2` so a non cancelled commit can use it. @derekchiang how hard do you think it'd be to get that working with the current pfs?

Another question: should the system even let people create commits when the parent is cancelled? It doesn't seem like there's much legit use for that since the data in there will still be somewhat incoherent due to the parent being cancelled.

**Comment by msteffen** [comment]
What happens if two clients are committing concurrently? Can you start a commit while another client has a commit running? Do the lines/records you append show up in their commit, or is there some kind of dual-HEAD situation?

**Comment by msteffen** [comment]
Updating after short discussion with @sjezewski:

- To illustrate the kind use-case I have in mind, consider several servers that are all logging and are all publishing their logs to pachyderm. Each server opens a commit, and starts calling `PutFile` with its log files. Then one server fails and its commit is cancelled. What happens to the logs-processing pipeline that's watching these commits?

- Re. my question above: Using `PutFile` without a commit ID is sugar (AFAICT). `StartCommit` does return a commit ID, and it's possible to call `PutFile("foo", "master", <commit-id>, "file")` (or something equivalent), and the contents of `file` would be written to the commit with the id `commit-id`. Only if you call `PutFile` with no commit ID, does PFS put the contents of `file` into the highest-indexed commit (which is the most recently created commit, and what I've been calling `HEAD`)

- In that vein, there's no actual pointer to `HEAD`. It's just the case that commits to a repo are given a monotonically increasing index, and calling `PutFile` with no commit ID (like I said) uses the highest-indexed commit that's been created.

- Therefore this change amounts to: when we create a commit with index `n`, and then it's cancelled, we need to rename commit `n+1` to `n`, so that the cancelled commit is effectively replaced by its child in the commit history.

- In fact, one stumbling block that Sean thought of is that when a commit `n` is cancelled, it might have several children, all of which will need to be renamed. In the context of the the logs use-case, suppose you have 10 servers, and they open commits at approximately the same time, and your repo looks like this:
```
m/1 → m/2 → ... → m/10
```

Then, the first server (`m/1`) fails. We'll need to rename all of `m/2, ... , m/10` to be `m/1, ..., m/9`

**Comment by sjezewski** [comment]
stale
