### ISSUE TITLE
Inconsistency in `PutFile`

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#852]
Right now, `PutFile` does the following:
1. Check if the commit has been finished
2. If not, insert diffs

However, step 1 and 2 are currently not atomic, since they are database operations that span multiple documents, and RethinkDB (the database we use) does not support multi-document transaction.

What it means is that, someone can finish the commit between 1) and 2), and they will be surprised to find that even though they finish the commit, the content of the commit is still changing (since diffs are being inserted).

**Comment by derekchiang** [comment]
@jdoliner proposed the following solution:

* Have a `counter` field in the commit document, which is the number of diffs this commit contains.
* `PutFile` increments this `counter` field before inserting diffs.
* `FinishCommit` blocks until the actual number of diffs in the database matches the counter.

This solution leads to another question: what happens if `PutFile` fails after updating the counter, but before finishing inserting the diffs?

**Comment by sjezewski** [comment]
stale
