### ISSUE TITLE
Ad's on RTD?

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#862]
@sjezewski

**Comment by jdoliner** [comment]
Is this about ads as in advertisements? Or something different?

**Comment by JoeyZwicker** [comment]
pachyderm.readthedocs.io has an ad display in the bottom left. It must be something from readthedocs and we just noticed it when we pushed. Sean was there so I didn't ad more info. We want to figure out how to get rid of it, obviously.

**Comment by JoeyZwicker** [comment]
We started paying for RTD and got rid of ads. Also got a few new nice features we can consider using such as a Canonical URL such as docs.pachyderm.io instead of pachyderm.readthedocs.io.
