### ISSUE TITLE
Versioning Documentation to match with GH

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#871]
Read the Docs gives us a great versioning system. We can lock versions of RTD to versions of Pachyderm. For example, v1.2.0 can have a set of docs that is different from HEAD on master. 

As discussed today with @sjezewski and @msteffen, this will also let us make frequent point releases and always have docs that match (sets us up for eventual backwards compatibility concerns too).

https://readthedocs.org/dashboard/pachyderm/edit/ <-- others might need to make an account and I'll add you to the RTD project.

**Comment by sjezewski** [comment]
Should just be a matter of updating the settings on:

https://readthedocs.org/dashboard/pachyderm/versions/

But it'll help if the redirection is working, so we don't have to hardcode in a version in the links

**Comment by derekchiang** [comment]
I think this issue has already been fixed.  Currently you can switch versions for readthedocs.  Feel free to reopen if I'm wrong.
