### ISSUE TITLE
RTD redirect not working properly

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#881]
http://pachyderm.readthedocs.io/getting_started/getting_started.html doesn't redirect to http://pachyderm.readthedocs.io/en/latest/getting_started/getting_started.html like it should. I think this used to work, but maybe it never redirected correctly and was only working locally.

**Comment by sjezewski** [comment]
See https://github.com/rtfd/readthedocs.org/issues/2422

I'm not sure its possible. We'll see if they respond. If not, we'll deal, and have to update the links once more when we implement #871

**Comment by JoeyZwicker** [comment]
I think this can be closed.
