### ISSUE TITLE
Cleanup example_test.go

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#889]
A few things I think could be improved:

- Don't read files from github that are present on the local filesystem. Even though that's how users will be running it I don't think that's the best way to test it. For 1 it means it's impossible to run tests locally when the commit hasn't been pushed to github and if you run tests without commiting then, confusingly, you're not testing the changes you just made. It also means a failed request to github can fail tests which can get annoying quickly.
- Don't use `pachyderm/job-shim:latest`. This might require changing the examples as well. The reason is that `pachyderm/job-shim:latest` will always pull the latest image from docker hub which means that if a commit changes the API between `job-shim` and `pachd` it will never be able to pass CI. It's probably best to just leave the image field blank if you want `job-shim` that way `pachd` will make sure it uses a matching version.
- Try to deduplicate the pipelines. The word count example now has 3 copies of every pipeline, one in README.md, one in pipeline.json and one in the tests. I feel like that can be consolidated a bit.

**Comment by sjezewski** [comment]
That first one should be done already w the latest fruit-stand PR

https://github.com/pachyderm/pachyderm/pull/883#discussion_r80266206

**Comment by sjezewski** [comment]
The easiest thing to do to consolidate the pipeline would be only have `pipeline.json` and have the example reference the file. That'll require making the readme (e.g. wordcount) a little less 'hand-hold-y' (instead of supplying  a command to copy paste that includes the meat of the pipeline ... it includes the filename).

**Comment by jdoliner** [comment]
I think that's fine, wordcount is a more advanced example so people doing that should hopefully be comfortable with the idea of a single pipeline file that includes multiple steps.
