### ISSUE TITLE
Dispel Magic of rm /tmp/pach

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#890]
[See this issue](https://github.com/pachyderm/pachyderm/issues/843) for an example of such magic

**Comment by jdoliner** [comment]
Can this be closed? I think the magic of `rm /tmp/pach` is just that you were assuming that `make launch` blew away database state when it actually doesn't. So it makes perfect sense that schema changes would require `rm /tmp/pach`

**Comment by sjezewski** [comment]
Yup! After our slack discussion this makes sense
