### ISSUE TITLE
See if we can use any new features from Kubernetes 1.4

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#895]
Relevant release post: http://blog.kubernetes.io/2016/09/kubernetes-1.4-making-it-easy-to-run-on-kuberentes-anywhere.html

For starters, seems like it's now very easy to deploy Kubernetes on a cloud provider.  We can potentially "bundle" pachyderm with kubernetes such that a user can just deploy pachyderm on any cloud, without knowing kubernetes.

**Comment by sjezewski** [comment]
We're using k8s 1.4 at this point. I didn't see anything specific in that link about making deployment easier.

We use kops + `pachctl deploy` now which gets us pretty far. Is there something more specific you had in mind @derekchiang ?

**Comment by jdoliner** [comment]
I'm going to close this since it's pretty old and we have a number of specific issues about new k8s features we want to use.
