### ISSUE TITLE
Extend the types of urls that PutFile accepts

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#897]
Right now `PutFile` will allow you to specify a file's data as a URL to scrape... with the caveat that it has to be an `http://` url.
This has proven to be a pretty nice workflow for people so we should consider extending this to allow scraping from other sources. Sources that I think are worth considering for the first pass at this:
- s3
- gcs
- git

It might also be worth adding some wildcard logic so you can put the contents of an entire bucket at once.

**Comment by derekchiang** [comment]
This was fixed by #1059 .
