### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#898]
This issue tracks what kinds of benchmarks we want to add.

For now, I think the performance problem with Pachyderm is significant enough that even the simplest benchmarks can capture the performance issues.  As in, it's not like Pachyderm is already very well optimized and we need this sophisticated workload to reveal performance issues.

I'm thinking that we start with the following benchmarks:
- Writing and reading a big number of files from/to PFS.  The files should form hierarchies; as in, they shouldn't all reside in the top-level directory.  This benchmark can be mainly used to optimize critical-path PFS operations such as PutFile and GetFile.
- Run a pipeline that performs simple computations on each file.  For instance, the pipeline can simply compute the checksum of each file.  This benchmark can be mainly used to optimize PPS.

**Comment by jdoliner** [comment]
Adding to 1.3 milestone.

**Comment by derekchiang** [comment]
A couple non-trivial benchmarks have since been added: https://github.com/pachyderm/pachyderm/blob/master/src/server/pachyderm_bench_test.go

Gonna close this for now.  What's left to do is to run the benchmarks regularly; that will be tracked by #813 and #892
