### ISSUE TITLE
Direct API access in jobs

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#900]
Jobs right now access data by reading from the filesystem at `/pfs`. Our FUSE layer translates those syscalls into pfs api calls. This issue would allow users to talk directly with the API by constructing an `APIClient` in their code and sending requests. This would have the advantage of bypassing the FUSE layer and all associated overhead and getting data directly into their code. It's already technically possible to do this, since any pod created by kubernetes will have environment variables telling it how to access the pachd service. However it's not an ideal workflow because it's up to the user to figure out which data they should read and where they should write output. Furthermore if they make mistakes it can have some weird effects, for example if they forget to declare an input then they'll still be able to read from it which will result in the pipeline getting unexpectedly out of date as the repo won't trigger new runs of it.

I think we might want to introduce the concept of a `View`. It would be pretty similar to what we call `CommitMount`s right now, except not fuse specific. You could construct an `APIClient` with a particular `View` of the filesystem. The `View` would limit which repos and commits are visible. Specify aliases for them, in particular it would alias your output repo to `"out"`. It would also specifiy `FilterShards`.

This feature would make a certain class of user jobs much less painful. It will also be useful for a number of internal features such as SQL connectors since getting programatic access to SQL within Go is relatively straightforward.

**Comment by jdoliner** [comment]
I'm going to take a swing at this one since it opens up some new use cases and I think it'll be nice to have as much of the release cycle as possible to play with them and see what works. Starting with a design doc:

The first step in getting this working is taking the fuse specific messages that describe the set of mounted commits and making those work with an `APIClient` instead. The message in question is:

```
message CommitMount {
    pfs.Commit commit = 1;
    pfs.DiffMethod diff_method = 2;
    bool full_file = 3;
    string alias = 4;
    pfs.Shard shard = 5;
}
```

I'm going to rename this to `CommitView` and relocate it into `src/client/pfs.proto` since it's no longer fuse specific. Fuse can still use it in the same way. `APIClient` can also use it to create a limited view of pfs in which only some repos and commits are visible. Furthermore I'll make it so that the constructor `NewInCluster` looks for serialized `CommitView`s somewhere in the filesystem which will allow us to inject views using kubernetes.

I think that'll give us everything we need to get a working example of a fuse free job. There are still a couple of open questions though:

- Should the API allow users to specify if jobs are fuse based or API based or should we expose both and allow jobs to use whichever one they want?

- Should views be a client side or a server side thing? I see downsides to both. If they're clientside it means that implementing an APIClient for a new language requires duplicating the View semantics. If they're server side then all `Commit` and `File` requests are going to need to have the View object attached to them. For the time being I'm going to stick to client side because that's what we have now for fuse so it's less work. I'll consider switching as I progress on the issue.

**Comment by jdoliner** [comment]
This didn't make 1.3. With the datum changes we're thinking about I'm less sure of the value of this issue so I'm going to leave it unmilestoned for now.

**Comment by sjezewski** [comment]
stale
