### ISSUE TITLE
Data prefetching

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#901]
There are a number of places we could make performance gains by trying to fetch data ahead of time for a job so that it's cached in memory by the time the actual job requests hit it. I could see this working at a couple of levels:
- have the fuse layer request data once it knows which commits the job has access to. This has the advantage that caching would be on the local machine and thus very fast.
- have have pachd prefetch data when it schedules a job and store it in pachd's caching layers. This doesn't have the benefit above but it does have the benefit that it can be requesting data while the job is being scheduled by k8s which can take a while sometimes.

There's no reason we can't do both of these things.

**Comment by derekchiang** [comment]
#1078 partially addresses this.  There are more ways of prefetching that we can do, such as prefetching data at the pachd layer.  Gonna move this off 1.3.

**Comment by sjezewski** [comment]
stale
