### ISSUE TITLE
Reconsider FullFile

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#904]
FullFile is a very special purpose that's pretty opaque unless you happen to need exactly the semantics it implements. We should see if there's a more general set of semantics we could implement that would allow this use case without being so special purpose.

**Comment by derekchiang** [comment]
@jdoliner has since proposed a more general framework (the one where we have `partition` and `incrementality`).  @jdoliner do you wanna describe it here or open a new issue?

**Comment by jdoliner** [comment]
In the process of opening a new issue right now, will close / reference this one when it's up.

**Comment by jdoliner** [comment]
Closing in favor of #1108 since that has a plan to get rid of `FullFile`
