### ISSUE TITLE
Add test coverage for object stores

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#906]
CI currently just uses local disk storage. We should evaluate if we want this to run as part of CI, I'm thinking yes since I don't see any reason it should slow down CI too much. It might be a bit of a hassle in terms of getting each CI run space in buckets to use, but I think it should be doable with some sort of prefix.

**Comment by sjezewski** [comment]
This PR should have coverage once we have support for obj stores:

https://github.com/pachyderm/pachyderm/pull/1215

**Comment by sjezewski** [comment]
duplicate. referenced in aggregation issue
