### ISSUE TITLE
Remove "/pfs/prev"

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#907]
In the past we needed "/pfs/prev" because it wasn't possible to read from "/pfs/out". Now that it is I don't think "/pfs/prev" is doing us much good and I think removing it would simplify things. It's probably best to do this sooner rather than later so people have less time to depend on its existence in their code.

Anyone have objections to getting rid of it?

**Comment by derekchiang** [comment]
Am I right in understanding that `/pfs/out` right now presents the exact same content as `/pfs/prev` before any writes?

**Comment by jdoliner** [comment]
Yes, I believe that's the case.

**Comment by derekchiang** [comment]
#1078 makes `/pfs/out` a real (i.e. non-FUSE) directory, thereby making `/pfs/prev` necessary again.  Closing.

P.S. we have discussed some designs that would remove `/pfs/prev` in favor of a better abstraction, such as #1057.
