### ISSUE TITLE
pachctl exits with status 0 on bad argument

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#908]
I'm not yet familiar enough with Cobra to know how to fix this quickly, but to illustrate the issue:

```
$ pachctl create-repo && echo -e "\n***This command exited successfully***"
expected 1 arguments, got 0

Usage:
  pachctl create-repo repo-name [flags]

Flags:
  -h, --help   help for create-repo

Global Flags:
  -v, --verbose   Output verbose logs

***This command exited successfully***
```

**Comment by sjezewski** [comment]
As we see more customer implementations / ingress automation, having proper exit codes is important for scripting.

**Comment by AmundsenJunior** [comment]
Is there an expectation anywhere of what exit status should be provided in this error case? Reviewing `src/server/pkg/cmdutil/cobra.go`, the `Run...Args` func calls all exit 0 after outputting `cmd.Usage()`, and only will exit nonzero (via `ErrorAndExit`) when running the called cmd and receiving an `err`.

**Comment by jdoliner** [comment]
Not sure what fixed this but just tested on master and it returns 1. I'm guessing it was an update to the cobra library.
