### ISSUE TITLE
wrong proxy port in local deployment tutorial

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#9099]
**Provide a link to the page with an issue:**
[link](https://docs.pachyderm.com/latest/set-up/local-deploy/docker/#docker-desktop-5-connect-to-cluster)

**Describe what is wrong:**
The doc suggests connecting using port 80 while the proxy runs on 8080.

**Describe the suggested changes:**
Change the docs to suggest port 8080.

**Environment:**
- Kubernetes version (use `kubectl version`):
1.24.2 via docker desktop
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.6.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local

**Comment by lbliii** [comment]
Hey Rannan, thanks for the feedback!

Did you happen to set the httpPort value when you were running the helm install command? like `--set proxy.service.httpPort=8080` or did it require port 8080 for you by default?

**Comment by paterson-191** [comment]
I have explicitly used port 8080, as this was originally suggested in the docs. So the solution was clear to me but let me be clear why this is a documentation issue:

[Step 3.3](https://docs.pachyderm.com/latest/set-up/local-deploy/docker/#docker-desktop-3-install--configure-helm) in the docs (install PachD) suggests using port 8080. However [step 5](https://docs.pachyderm.com/latest/set-up/local-deploy/docker/#docker-desktop-5-connect-to-cluster), uses port 80 in the command to connect to the cluster, so a failure is expected.

**Comment by RaananHadar** [comment]
I have explicitly used port 8080, as this was originally suggested in the docs. So the solution was clear to me but let me be clear why this is a documentation issue:

[Step 3.3](https://docs.pachyderm.com/latest/set-up/local-deploy/docker/#docker-desktop-3-install--configure-helm) in the docs (install PachD) suggests using port 8080. However [step 5](https://docs.pachyderm.com/latest/set-up/local-deploy/docker/#docker-desktop-5-connect-to-cluster), uses port 80 in the command to connect to the cluster, so a failure is expected.

**Comment by lbliii** [comment]
Yep, you are right! It's suggested to switch to port 8080 if the default (80) is used after checking in your browser -- but not required if it's unused. I've added a new similar callout to step 5 for situations where people do follow that tip and change the default value.  Thanks for this feedback, as it's something I didn't catch before when adding that tip. 

 If you encounter anything else in our docs, don't hesitate to reach out :)
