### ISSUE TITLE
429 error when doing a put file using a url in the Pachyderm tutorial

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#9100]
**What happened?**:
I tried following the tutorial on a fresh cluster and ran:
```
pachctl put file images@master:liberty.png -f http://imgur.com/46Q8nDz.png
```
yielding a 429 Too Many Requests error

**What you expected to happen?**:
The put file used to work in previous versions.

**How to reproduce it (as minimally and precisely as possible)?**:
Run the tutorial, this was reproduced on multiple versions - see below.

**Anything else we need to know?**:
Doing a put file from a local drive worked fine.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.24.2 (docker desktop) and 1.25.6 (Azure)
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.6.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): both docker desktop and Azure had this issue.

**Comment by lbliii** [comment]
Hey Raanan,

Thanks for catching this! I've updated the images links in that article and they should work now. Feel free to re-open this if you encounter more issues.
