### ISSUE TITLE
See if we can put the example tests under /doc/examples

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#917]
A symlink of `doc/examples/vendor` to `src/server/vendor` should do it I think. And the client code is 'vendored' via symlink under `src/server/vendor` so that should get use the right client code as well

**Comment by derekchiang** [comment]
What's the motivation for this?

**Comment by sjezewski** [comment]
The short answer is just my OCD :-P

Organizationally, I think it makes sense to keep the tests for examples alongside the examples.

But doing this and trying some of the obvious things for vendoring it wasn't super straightforward. Also I think there are some edge cases w running all tests w vendoring / symlinks / and the Makefile. 

Sooo .... I don't think its worth the trouble.
