### ISSUE TITLE
Upgrade Metrics Reporting

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#921]
Goals:
- Better understand how our software is being used
- Specifically ... be able to detangle unique users from unique clusters
- Be transparent (we should provide an opt out mechanism)

Plan of attack
- Upgrade existing metrics to report whats in the database (instead of just incrementing counters)
- Upgrade metrics to report a unique user
- Provide an opt out mechanism

**Comment by sjezewski** [comment]
[This PR addresses the first part](https://github.com/pachyderm/pachyderm/pull/965)

For a plan of attack for identifying unique users:

- We'll do so via pachctl only (not via the client code)
- We'll provide an opt out mechanism
- We'll store/create the unique at `~/.pachyderm/config.json` (which will be backed by a protobuf)
- We'll pass this value as part of the `context` for all requests to the cluster
- Which will allow the cluster to report the metrics (and associate user actions w a cluster)

**Comment by sjezewski** [comment]
Also - we agreed to write up a 'semantic conventions' doc for contributors outlining when to put a field on a `context` vs a request proto object.

Generally, anything needed for a 'session' should go in context, whereas functional things (or things that can affect execution patterns) should go into a proto obj

**Comment by sjezewski** [comment]
This is a great doc to reference in our writeup: https://medium.com/@cep21/how-to-correctly-use-context-context-in-go-1-7-8f2c0fafdf39#.77fbkc67x

Specifically talks about how context informs, but doesn't change behavior

**Comment by sjezewski** [comment]
Also - we'll report only one metric in `pachctl` and that'll be when a user calls `pachctl deploy` ... in which case we can look at the `--no-metrics` flag for that call to Do The Right Thing

That'll help us see how many users are trying to startup clusters but never succeed.

**Comment by sjezewski** [comment]
In the case that the client is older than the server, we can handle this case server side. In this situation, the server will have metrics enabled, but will not receive a UUID from the client, so shouldn't report metrics.

In general, we don't have an upgrade policy around client/servers. If we're ok with requiring users to upgrade, we could instead return an error message if we don't receive the user data. But that seems heavy handed for this use case.

**Comment by jdoliner** [comment]
I agree that that is heavy handed. Metrics breaking shouldn't prevent users from using the system.

**Comment by sjezewski** [comment]
The PR landed, so this issue is complete
