### ISSUE TITLE
Tracing support

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#922]
When debugging an issue, we could use more information about API call stacks.

E.g.

A)

FUSE calls 'open' which in turn can make many calls to `GetFile` ... it would be great if we could associate that single FUSE request to the subsequent many `GetFile` requests.

B) 

Internally within PPS, within `CreateJob` we make several calls to PFS API methods `StartCommit` ... etc

It would be helpful to be able to trace these types of requests through.

**Comment by msteffen** [comment]
Not sure if these will turn out to be useful, but we had a system at Google that was broadly used for similar kinds of tracing called Dapper. There are a few open-source systems that look like they're trying to do the same thing:

http://opentracing.io/
http://zipkin.io/  (just based on the screenshots, this looks very similar to dapper)
http://htrace.incubator.apache.org/
http://www.x-trace.net/wiki/doku.php

**Comment by derekchiang** [comment]
gRPC integration with OpenTracing: https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc

**Comment by JoeyZwicker** [comment]
@sjezewski @msteffen Is this relevant?

**Comment by sjezewski** [comment]
Yea, this is some outstanding tech debt. We haven't gotten to it, but it would up level our debug tools.

**Comment by msteffen** [comment]
Initial solution to this implemented in https://github.com/pachyderm/pachyderm/pull/3541

Still to do:
- Trace HTTP calls (e.g. `put-file <url>`).
  - Right now the time spent waiting for an HTTP response shows up as a huge unexplained stretch in the span
- Tag RPCs
  - Right now we have generic spans reported by a gRPC interceptor, but if we implemented tracing versions of each of our clients, then we could tag spans (e.g. GetFile and PutFile could include the name of the file being gotten/put).
  - We've already done this in a limited way with `src/server/pkg/obj/tracing.go`

**Comment by jdoliner** [comment]
At this point we have tracing that seems to satisfy our needs in that when we need to get a closer look at what's going on in a user's cluster we turn on tracing and we get the info. I'm going to close this issue since I don't think it's tracking anything specific, if you want to see improvements to tracing feel free to reopen and clarify or open more specific issues.
