### ISSUE TITLE
Upgrade Docs Footer

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#927]
I really like the footer for the rethink docs:

https://www.rethinkdb.com/api/javascript/object/

We have a slack, GH issues, etc. We should provide links on our doc site for some recourse for users who don't find what they need.

**Comment by JoeyZwicker** [comment]
This is a great idea. Let's add this to 1.3 milestone as a docs upgrade that shouldn't be too hard.

**Comment by sjezewski** [comment]
This change landed
