### ISSUE TITLE
am not able to get into your slack channel

### ISSUE THREAD

**Issue by mwaaas** [pachyderm/pachyderm#928]
<img width="478" alt="screen shot 2016-10-04 at 3 39 36 am" src="https://cloud.githubusercontent.com/assets/6207932/19058880/ceaa045a-89e3-11e6-80dc-4a76e1c367d1.png">

**Comment by JoeyZwicker** [comment]
Sorry you ran into that. Give me a few minutes and I'll fix that.

**Comment by JoeyZwicker** [comment]
Should be working again. @mwaaas

**Comment by mwaaas** [comment]
thanks
