### ISSUE TITLE
Cluster management

### ISSUE THREAD

**Issue by mwaaas** [pachyderm/pachyderm#929]
From this blog https://medium.com/pachyderm-data/lets-build-a-modern-hadoop-4fc160f8d74f#.6hmaua9ra

cluster management is a separate layer. Can I write a pull request to add an alternative option for cluster management. I prefer using the default docker cluster management ( swarm mode) its easy to get started locally and have tried it in production and still works fine

**Comment by jdoliner** [comment]
Hi @mwaaas we'd certainly accept a PR adding support for Docker Swarm. However the implementation is somewhat non-trivial and may prove almost impossible. We rely pretty heavily on Kubernetes jobs to implement Pachyderm jobs and it seems like Docker Swarm doesn't yet have an equivalent judging by this issue: https://github.com/docker/docker/issues/23880. There are other things that we rely on Kubernetes for that we may not find alternatives to in Swarm but that's the most obvious one.

Still I'd be very interested to find out places where this breaks down and even getting pfs working on Swarm (which doesn't require jobs) would be a big step in eventually supporting swarm as a deployment target.

**Comment by mwaaas** [comment]
@jdoliner  will try to do one.   
This diagram is not correct https://medium.com/pachyderm-data/lets-build-a-modern-hadoop-4fc160f8d74f#.6hmaua9ra. the cluster management is not a complete separate layer. if it was it should be very easy to be swapped with another cluster management especially if you are running containers ( am assuming everything in pachyderm is a container even the Pachyderm jobs)

**Comment by jdoliner** [comment]
Everything Pachyderm runs is a container including the jobs. The cluster management layer is separate from Pachyderm but Pachyderm does require some fairly specific things from its cluster management layer, jobs being an example. Unfortunately just because Kubernetes and Swarm are both containerized cluster management systems they don't necessarily have total feature parity yet.

**Comment by mwaaas** [comment]
@jdoliner  thanks for the info. closing the ticket for now, when I get time will try implementing docker-swarm option. 

The reason I wan docker-swarm, it would be easy to host it in docker-cloud.
