### ISSUE TITLE
Can't deploy pachyderm locally.

### ISSUE THREAD

**Issue by mwaaas** [pachyderm/pachyderm#932]
<img width="445" alt="screen shot 2016-10-04 at 4 28 15 am" src="https://cloud.githubusercontent.com/assets/6207932/19059687/82119ec6-89ea-11e6-906e-c216786d0790.png">
<img width="1072" alt="screen shot 2016-10-04 at 4 30 14 am" src="https://cloud.githubusercontent.com/assets/6207932/19059710/af6cda98-89ea-11e6-96ea-6c8334f1e6a2.png">

**Comment by JoeyZwicker** [comment]
Your version of pachctl is out of date. `pachctl deploy` was added in v1.2 

`brew uninstall pachctl && brew untap pachyderm/tap` and then `brew tap pachyderm/tap && brew install pachctl``

`pachctl version` should show v1.2.1
