### ISSUE TITLE
Decouple block size and data chunking

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#933]
## Problem

Right now Pachyderm has a static block size which is used when writing files to pfs with `PutFile`. A single write will be broken up based on the delimiter being used in such a way that block boundaries correspond to delimiter boundaries. If the delimiter boundary doesn't fall right on a block boundary then pfs will create a block bigger than the block size. And if the total `PutFile`  (or the fragment of data that remains after previous blocks have been filled) is smaller than a block it will create a block smaller than the block size. Blocks, and thus the block size, also come into play when processing data. Map steps split files up based on blocks and 2 datums that are in the same block will necessarily be processed by the same container.

The issue here is that there are competing goals that require moving the block size in opposite directions. Right now we have a block size of 8 MB which satisfy both goals badly. A larger block size makes our access pattern on object storage much nicer, 8MB is a pretty small object for most object storage and we've been seeing issues with sending too many requests to obj storage. However a smaller block size makes it so that Pachyderm can parallelize more data sets. Users have been running into problems where they'll want to parallelize over a file that's less than 8MB and the only way they can get this to work is to have 1 step in the pipeline which first splits the file up into separate files and then another step which does a `Reduce` on them so that things get split up by file not block. This is definitely a kludgy workflow that we would like to avoid. It also has the problem that each of these files becomes its own very small block which is even worse for obj storage access patterns than 8MB blocks. Although it's slightly orthogonal, I think this is a pretty good chance to make our system smarter about merging multiple files together into the same block.
## Goals
- BlockSize should be a value that we set entirely based on the underlying object storage, different object stores have different sweet spots in terms of file size that maximizes performance.
- BlockSize shouldn't be hard coded anymore, setting it as an env var will make it easier for people to tweak stuff.
- Multiple small files within the same commit should be written to the same block. Having small files span commit boundaries seems like it's going to be difficult because when `FinishCommit` is called all of the data referenced in the commit needs to be safely written to obj storage before it can proceed.
- How data is chunked for processing should have nothing to do with blocks, instead there should be a separate indexing scheme for this that allows you to chunk the data in a delimited way by reading smartly from different locations in blocks.
## Implementation

The biggest change we need is a separate index for the delimiters in a file. Currently we store `Diff`s in rethinkdb for pfs that contain an array of `BlockRef`s. A `BlockRef` looks like:

```
message BlockRef {
  string hash = 1;
  uint64 lower = 2;
  uint64 upper = 3;
}
```

I think we should add a field `repeated int64 delimiters = 4;` which will be all of the bytes we can break the chunk up into. This can be computed by the block server in `readBlock` pretty trivially. Once we have this information it should be pretty simple to use it in `GetFile` which already figures out what data to send using `BlockRef`s

In order to get coalescing small files to work we may need to rethink how we name blocks a little bit. The issue is that normally a call to `PutBlock` returns a `BlockRef` which gives you the block's hash. This isn't going to work because if later calls to `PutBlock` might add to data to the same block then it's going to need have a different hash. Naming the blocks with their hashes (content addressing) might make less sense now that blocks can be composed of smaller files since it's only going to work if the file requests happen to hit in the same order and thus create a truly identical block. Instead it might make more sense to do deduplication at the diff level, computing a hash for each file chunk that we write to a block and seeing if the hash for that chunk is present in any other block. If it is then we can just reference that chunk instead of putting it in a new block. Under this scheme blocks could just be named using a UUID I think. Since hashing the content wouldn't correspond to anything that interesting. They could also still be hashed and I don't really see any downside to that either.

**Comment by derekchiang** [comment]
If I understand the proposal correctly, BlockRef is gonna looks like this:

```protobuf
message BlockRef {
  string hash = 1;
  uint64 lower = 2;
  uint64 upper = 3;
  repeated int64 delimiters = 4;
}
```

So each BlockRef refers to a section with a block, and each delimiter refers to a section within a BlockRef.  This strikes me as a little strange.

What about something like this:

Each BlockRef is a unit of partition.  BlockRef still looks like:

```protobuf
message BlockRef {
  string hash = 1;
  uint64 lower = 2;
  uint64 upper = 3;
}
```

But it's guaranteed that `lower` and `upper` are both at delimiter boundaries.  So if we are putting a JSON file with 3 JSON objects, then we end up with 1 block but 3 BlockRefs, each corresponding to 1 JSON object.  Then in PPS, we distribute work by distributing BlockRefs.

**Comment by jdoliner** [comment]
My only worry on that would be size, I think for the 2 schemes the sizing looks like this:

- `hash + lower + upper + (delimiter * lines) = 512 + 8 + 8 + (8 * objects)`
- `(hash + lower + upper) * lines = (512 + 8 + 8) * objects`

For large numbers of objects, which I think is what we should be optimizing for, thats a `66x` difference which seems pretty meaningful to me.

> So each BlockRef refers to a section with a block, and each delimiter refers to a section within a BlockRef. This strikes me as a little strange.

I 100% agree that this is strange, looking at it now it seems like we actually don't need `lower`, `upper` and `delimiters` we could theoretically roll them all into one.

```
message BlockRef {
  string hash = 1;
  repeated int64 delimiters;
}
```
The first value in `delimiters` would be the index of the first byte of the first object, the second value the first byte of the second object and so on. The last value in delimiters would be the byte after the last byte of the last object, or put another way the first byte of the first object that isn't part of the diff. So if you want `lower` or `upper` you just look at `delimiters[0]` and `delimiters[len(delimiters) - 1]`. 

---

Also we talked about this in slack but I just want to state for the record that I don't like the name `delimiters` here and @derekchiang doesn't either (at least that's what he said). How do people feel about the name `Chunks`? I feel like we kick that one around a lot in conversation but it's not used by anything in our code.

**Comment by derekchiang** [comment]
Yeah your concern about size is totally legit.  I like this scheme:

```protobuf
message BlockRef {
  string hash = 1;
  repeated int64 delimiters;
}
```

This has the following property:

* The size of the BlockRef is `delimiters[n-1] - delimiters[0]` where n is the number of delimiters.
* The size of object k is `delimiters[k+1] - delimiters[k]`
* The number of objects is `n-1`.

Then, to distribute data, we can either make sure that:

1) each shard gets roughly the same number of objects, or
2) each shard gets roughly the same number of bytes.

Both of which are easy to enforce.

**Comment by jdoliner** [comment]
Unless I'm very much mistaken that commit does not fix this issue.

**Comment by jdoliner** [comment]
Also, those properties are really nice :)

**Comment by jdoliner** [comment]
Thinking about this issue some more I realized there's one major flaw with the proposal above, it only really works well for append based workloads. If a user changes a single line in a file then that will lead to a completely new block that will be 99% the same. This negates a lot of the benefits of our version control system. It also makes it pretty hard for us to give people semantics they expect from a version control system. In particular the ability to see line based diffs between commits easily. I think those should both be goals of the new system:

# Goals
- Changing a single line in a file should result in about the size the new line in extra needed storage
- It should be easy to show users a line by line diff between different commits.

To this end I'd like to introduce a slightly different proposal for this issue. It starts with the concept of a `Datum` which is our smallest unit of data. For line based files this would be a line, for json files a document, etc. In protobuf a `Datum` would look like this:

```protobuf
message Datum {
  string hash = 1;
  string block = 2;
  int64 lower = 3;
  int64 upper = 4;
}
```

It's pretty similar to what a `BlockRef` was before but with the major difference being that we have a hash of the datum's content instead of a hash of the block's content. That's a nice thing to have because it means the same datum can be written in other files (or other places in the same file) and we'll be able to detect that it's the same just by hashing. This will also require a new table in rethink for the Datums in which the hash will be the primary key.

Under this scheme a `Diff` would look like this:

```protobuf
message Diff {
  map<int64, Datum> insertions = 1;
  repeated int64 deletions = 2;
  // along with a bunch of other stuff ofc
}
```

Under this scheme modifying a line would be result in a `Diff` like:

```
Diff{
  Insertions: {
    4: {...}
  },
  Deletions: [4],
}
```

Reading a file over a range of commits would require pulling out the relevant diffs and combining them, I won't detail the algorithm for combining diffs but I think it should fairly straightforward and we might even be able to find something off the shelf that works. Our diffing algorithm is now similar enough to how git works that I think they're pretty well understood. This also makes it pretty straight forward to render diffs for users.

**Comment by derekchiang** [comment]
I like where this proposal is going and agree that our current scheme is very append-oriented and doesn't work well with modification-heavy workloads.

Some concerns that came to my mind:

* The metadata-to-data ratio seems really big.  Currently we store one `Block` struct per 8MB of data.  Under this proposal, we'd store one `Datum` struct per datum, which can be as small as a line for normal files.
* If I understand the proposal correctly, the `int64` in `Diff` specifies the position of a Datum.  However, this seems to mean that in order to write any data at all, you'd first need to figure out how many datums the file already has (let's say it has N datums).  Then you create datums that are N+1, N+2, etc.  In other words, it seems like appending datums to a file requires either 1) tracking the number of datums in the file, or 2) read/construct the file to figure out how many datums it has.  This is in contrast with the current implementation of `PutFile` where we don't need to read/reconstruct the original file since we are just appending blocks.

**Comment by jdoliner** [comment]
> The metadata-to-data ratio seems really big. Currently we store one Block struct per 8MB of data. Under this proposal, we'd store one Datum struct per datum, which can be as small as a line for normal files.

Very valid concern. One some level this is inescapable, if we want to have content addressability for `Datum`s we're going to need to store a hash for each one. If we use a 128 bit hash that's 16 bytes, for really short lines that could be as bad as doubling the size. But I think for larger datums this works well and that's likely closer to our sweet spot than lines around 16 bytes in size.

The above proposal would require a lot more than 16 bytes per datum because it also requires `Diff`s to reference 1 `Datum` at a time which is at least another 16 bytes. Here's what I think we could do to fix that: introduce a `Block` table, which would also be the place that we keep track of `Datum` hashes. The schema would look like:

```proto
message DatumIndex {
  string hash;
  int64 offset;
}

message Block {
  string id;
  repeated DatumIndex datum_indexes;
}
```

This table would require having a secondary multi-index on the datums present in the block so later writes/reads could find them. Using this scheme `Diff`s could reference `Datum`s a lot more efficiently. They could still reference a single datum since the `Block` table would have an index on them. But they could also reference entire blocks by id which could then easily be turned into `Datum`s by joining to the `Block` table. They could also reference ranges of `Datum`s within a block. I think we could get the data sizes down low enough for this to work.

> If I understand the proposal correctly, the int64 in Diff specifies the position of a Datum. However, this seems to mean that in order to write any data at all, you'd first need to figure out how many datums the file already has (let's say it has N datums). Then you create datums that are N+1, N+2, etc. In other words, it seems like appending datums to a file requires either 1) tracking the number of datums in the file, or 2) read/construct the file to figure out how many datums it has. This is in contrast with the current implementation of PutFile where we don't need to read/reconstruct the original file since we are just appending blocks.

Tracking the total number of datums in the file wouldn't be too hard, just an extra int64 in the `Diff`. That would make it so you could easily append to the end of the file. It would also make deleting the file and completely overwriting it pretty simple since you'd know all the lines you need to remove and then you could just start writing like it's a new file. Those are the two access patterns we support well right now.

For more complicated operations, like changing a single line in the middle you'd probably need to reconstruct the `Datum`s so you can figure out which ones changed and which ones didn't. This will be a bit of added overhead while writing the data, but I don't think it's untenable.

# Caching

Something that occurred to me while writing this. I think with this scheme we'd be able to have a much more effective caching layer by caching `Datum`s rather than `Block`s. It's better because there's going to be less overlap. Right now you could theoretically have 2 blocks that are almost identical except for a few lines but they'll still be separate blocks with separate hashes and thus they'll be separate cache entries and separate entries to s3. This system will deduplicate a lot of that.

**Comment by JonathanFraser** [comment]
At some point going down this road you are simply trading off a filesystem tree for a datum tree.

**Comment by jdoliner** [comment]
@JonathanFraser we are basically trading a filesystem tree for a datum tree. This is appealing though because a datum tree gives us much higher granularity for detecting changes to data. For example, a pretty common pattern in Hadoop land is to dump your database into hdfs and have each table correspond to a file. This is possible in Pachyderm right now but it doesn't play very nicely with our version control semantics. If the rows get dumped in a different order, or one of them gets deleted or then the blocks are unlikely to align correctly and we'll wind up storing a separate copy of the data. However if we think in a datum centric way, then each row in the database can be a datum and if that datum is unchanged our system will be able to detect that and we can just reference the previous version of the datum. If people are doing a database dump every night then it's likely that a very small percent of the rows will have been changed, so this technique can actually provide massive space savings.

**Comment by JonathanFraser** [comment]
@jdoliner Right, so what I'm about to suggest might well be heresy but please bear with me. This pattern of you dumping a database to a directory where each file refers to a table and each line a row exactly maps to the case where each table is a directory and each file corresponds to a row. This would be a perfectly valid way to dump a database and has the convenient property that the user gets to set the granularity with external tools. So rather than bake all of this into pachyderm, build it on top with additional tools. The only thing to make this work is for reduces directories need to be able to be presented atomically.

**Comment by jdoliner** [comment]
@JonathanFraser not heresy at all I think it's totally reasonable for users to lay their data out like this. However in Pachyderm today this layout won't perform very well because 1 file per row implies 1 block per row which implies 1 s3 object per row. This is going to make having large numbers of rows very expensive since s3 charges per transaction. It's also a lot less efficient in terms of total bandwidth for small objects vs bigger objects.

That's really the root problem we're trying to fix in this issue, `Block`s define both the granularity at which we content address and the granularity with which we write to object storage. That's bad because you normally want fine granularity for content addressing but coarse granularity for object storage and with the current system you can't have both.

While I agree that your layout for data is totally valid and one that we should support well laying a bunch of rows out in a single file also seems valid to me. Furthermore from talking to users it seems to be something that most users expect our system to be able to do, probably because it's something they're used to from Hadoop. Ultimately I'm hoping we can come to a solution here that supports both workloads well.

**Comment by JonathanFraser** [comment]
@jdoliner  so I think there is a very fundamental difference between Hadoop and pachyderm and this hits it on the head. Hadoop is based on injecting user code as plugins into every aspect of it, including how it parses and breaks up files. Unless pachyderm starts to include a similar plugin based API there is no way the core can hope to cover all possible ways of breaking up files. After all, there are as many ways to breakup files as there are users. You can specify delimiters into the blocks but then how do users influence that. do we get to choose a set stock delimiters or do I inject parsing code somehow. If it's a set of stock delimiters? Is it only one type per repo/pipeline or can I combine them? How can I inject my own delimiters by modifying pachyderm?

In the current system there is two ways to inject behaviour, via various config options (so long as pachyderm supports it) and via a user supplied docker container. If we want to support the ability for end users to inject delimiters without modifying pachyderm itself then there needs to be a way to do that interacting only with the files and a filesystem. There is a solution to this and that's writing out to individual files. The only difference between this and a single large file is coming up with a name.

I guess I kind of feel like, because of the way pachyderm works with containers and exposing things via a filesystem,  that large sharded files are almost an anti-pattern. So instead of asking the question "Given that I have a large quantity of coarsely broken data, how do I finely content address it?" into "Given that I have a large quantity of finely addressed data, how do I store it coarsely?". I Suppose this is the same problem but it is perhaps slightly easier to think about. 

If was to solve this problem, I would batch up writes to files in a given commit into one blob. The meta data for a file diff then contains the blob where the file is stored, the offset into the blob and the length of the file. S3 supports partial reads so this is ok, I don't know about other stores. This also means most of a diff is stored together and so that when a pipeline needs to operate on it then it will likely use most of the diff and we can read the blob in its entirety. Ultimately I just think batching is an easier problem to solve than slicing.

**Comment by jdoliner** [comment]
I'm not sure I see this as quite the fundamental difference between Pachyderm and Hadoop that you do. In my experience and from what I can find online it seems that for the most part in Hadoop files are broken up by line. If users want something other than that they can specify a string used for the delimiter. I didn't find much about more complicated behaviors with injected code, but I agree that, that's way too complicated and not something we want to implement in Pachyderm. Your point that it needs to be possible to indicate delimiters entirely through the filesystem is well taken, right now we let users indicate that with the suffix of their filenames ie, `.json` indicate delimiting by json objects. I like that because it seems like a pattern that's pretty common and people are used to it. Still I can see how it's weird to have something like a suffix modifying behavior.

Ultimately I think we can consider this issue without worrying too much about delimiters since it's somewhat orthogonal. We want to upgrade the system so that it can pack multiple file modifications into the same s3 object. This change should leave the functionality of delimiters untouched and there's not much in the design that wouldn't need to be implemented if we were completely eliminating the concept of delimiters. Even if a file can't be composed of multiple `Datum`s that were broken apart due to delimiters it can still be composed of multiple `Datum`s that were added in successive commits. We'll need approximately the same query patterns for those 2 cases, since in both you'll need to be able to get the `Datum`s individually or all grouped together.

**Comment by jdoliner** [comment]
Took an initial crack at a design for this feature, below is a diff of `src/client/pfs.proto` which adds a new type of message for `Object`s. This is what I was referring to as `Datum` above, I actually think the name `Object` makes more sense because `Datum` suggests that it should be a single piece of data which based on the discussion in this thread doesn't seem like a good direction, we'll likely want. `Object` is the name git uses for content addressed blobs so I think it makes sense here.

Here's the API:

```
message Object {
   string hash = 1;
 }
 
message Block {
  string id = 1;
}

message ObjectInfo {
  Object object = 1;
  uint64 size_bytes = 2;
}

message ObjectInfos {
  repeated ObjectInfo object_infos = 1;
}
 
message PutObjectRequest {
  bytes value = 1;
}

message GetObjectRequest {
  Object object = 1;
}

message InspectObjectRequest {
  Object object = 1;
}

message ListObjectRequest {
}

message DeleteObjectRequest {
  Object object = 1;
}

message FlushObjectRequest {
  repeated Object object = 1;
}

message ObjectRef {
  Object object = 1;
  uint64 offset_bytes = 2;
}

message PutBlockRequest {
  Block block = 3;
  bytes value = 1;
  repeated ObjectRef object_refs = 4;
  reserved 2;
}
 
service BlockAPI {
  rpc PutObject(stream PutObjectRequest) returns (Object) {}
  rpc GetObject(GetObjectRequest) returns (stream google.protobuf.BytesValue) {}
  rpc InspectObject(InspectObjectRequest) returns (ObjectInfo) {}
  rpc ListObject(ListObjectRequest) returns (ObjectInfos) {}
  rpc DeleteObject(DeleteObjectRequest) returns (google.protobuf.Empty) {}
  rpc FlushObject(FlushObjectRequest) returns (google.protobuf.Empty) {}

  rpc PutBlock(stream PutBlockRequest) returns (google.protobuf.Empty) {}
  rpc GetBlock(GetBlockRequest) returns (stream google.protobuf.BytesValue) {}
  rpc DeleteBlock(DeleteBlockRequest) returns (google.protobuf.Empty) {}
  rpc InspectBlock(InspectBlockRequest) returns (BlockInfo) {}
}
```

A few things I want to point out about this API:
- there's a `FlushObject` request, this is the key thing that allows us to write a bunch of `Object`s and have them get grouped together into blocks and serialized to s3. `PutObject` will not actually record the object in a persistent way until `FlushObject` is called, we'll be calling `FlushObject` as part of `FinishCommit`
- This removes the notion of `BlockRef` files will reference `Object`s instead.
- `Delimiter` is removed from the `BlockAPI` this layer of the API, as per discussion with @JonathanFraser. We won't be completely removing delimiters but this will confine them to the PFS layer where I think they make more sense and where it will be easier to remove them if we decide that's what we want to do.

**Comment by jdoliner** [comment]
This is how 1.4 works.
