### ISSUE TITLE
Fix up stray comments

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#935]
https://github.com/pachyderm/pachyderm/blob/master/src/server/cmd/pachd/main.go#L143

And while we're at it, a quick grep also reports:

https://github.com/pachyderm/pachyderm/blob/master/src/client/pkg/discovery/discovery_test.go#L42
https://github.com/pachyderm/pachyderm/blob/master/src/client/pkg/discovery/mock_client.go#L70
https://github.com/pachyderm/pachyderm/blob/master/src/client/pkg/shard/router.go#L74

Some of these may be unused code.

**Comment by jdoliner** [comment]
For the 2 that are directed at me there, I think we can just delete them along with the rest of the code in the file. I'd be very surprised if we use the mock client anywhere considering that it's missing some key methods (ie the ones that say `// TODO jdoliner`).

That comment about a huge race has been there for a while, looking at the code it doesn't seem like there's much of a race going on and that code has changed a lot so I think that comment is useless at this point.
