### ISSUE TITLE
Run a docker registry in the cluster to support faster iteration cycles

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#937]
## Problem

The iteration cycle for pushing new code into Pachyderm is still slower than it should be. A common workflow to push new code into Pachyderm is
- build a docker image
- tag it using something unique
- push that tag to docker hub
- update the pipeline to reference the new image

This is annoying because it requires traffic to go from the users laptop to Dockerhub to the cluster which is often also running on the users laptop.
It's also annoying because the user has to come up with a tag and then copy it into the pipeline spec.
## Proposal

The first thing I think we should do is add a Docker registry to our cluster. This should be pretty trivial to do given that a Docker registry is one of the built in k8s add-ons. https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry has more information.

Once we have that it opens up a number of new workflows that can address this problem.
### Local file system workflow

 Suppose you have a directory structure like this:

```
./pipeline.json
./image
  +-- Dockerfile
  +-- src/
         +-- foo
         +-- bar
```

You could update (or create) this pipeline with:

```
pachctl update-pipeline -f pipeline.json --image-path image
```

This would do the following:
- build the image found in `image` by running `docker build image`
- tag the image as `localhost:5000/uuid`
- forward `localhost:5000` to the registry in the cluster using `kubectl port-forward`
- push the image to the registry in the cluster
- send the pipeline from `pipeline.json` to `pachd`, but first set the `image` field to `localhost:5000/uuid`

This would update the pipeline very efficiently since there's no need to talk to Dockerhub. In the case of a cluster running on minikube all traffic would go over localhost.
### Git workflow

This would also make it easy to build images from git repos. Docker actually supports this natively, for example you can build our `opencv` image with:

```
docker build https://github.com/pachyderm/pachyderm.git\#v1.2.1:doc/examples/opencv
```

To leverage this we'd expand our pipeline spec so that in place of the `image` field on `Transform` you could reference a git repo instead. When that request hit the server we'd first kick off a docker build for the image, then fill in the image field with the resulting image.

This wouldn't necessarily be useful for speeding up iteration because it requires committing code and pushing it to a central registry which is pretty much the same as building an image and pushing to docker hub. But it would be good for things like continuous integration and deploying a known image directly without having to talk to Dockerhub. For example we could use this to reference our opencv image rather than pushing it to Dockerhub.

**Comment by ccotar** [comment]
Any updates on this for the product roadmap?  This would make local development so much better!

**Comment by jdoliner** [comment]
The best way to solve this problem is to use the same Docker host for building images and running pipelines, if you're using Minikube this can be done with `minikube docker-env` or with `--vm-driver=none`. Setting up a registry is non-trivial enough with regard to getting certificates into it and potentially more security on top of that, that it probably doesn't make sense for Pachyderm to do this. Most companies that use containers have some existing solution for this and all clouds have built in registries at this point. So I think we're better off having Pachyderm be bring-your-own-registry than trying to solve this ourselves.
