### ISSUE TITLE
Update our images to build from ubuntu 16.04

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#945]
Currently they all build from 14.04.  Is there any reason why we might not want to use 16.04?

**Comment by jdoliner** [comment]
👍
No reason I can think of assuming we can get everything to work, and I'd be surprised if we couldn't. I think a good policy here is to stick to the LTS releases which both 14.04 and 16.04 are and not bother with the intermediate releases since they have shorter support windows.

**Comment by AmundsenJunior** [comment]
Would it make sense at this point to update issue for updating to Ubuntu 18.04?

**Comment by jdoliner** [comment]
Our images are mostly `from scratch` at this point, but those that aren't use 18.04.
