### ISSUE TITLE
Add cpu shares field to pipeline/job

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#946]
Users would like to be able to set the cpu shares of pods that get created by the job.
This might also be a good chance to see what other attributes make sense to punch through. Mem shares comes to mind, maybe others?

**Comment by derekchiang** [comment]
Could you explain what you mean by CPU shares?  Is it in the same sense as [Kubernetes' CPU resources](http://kubernetes.io/docs/user-guide/compute-resources/#meaning-of-cpu)?

**Comment by jdoliner** [comment]
Yup exactly. Basically just exposing that functionality in pipelines.

**Comment by sjezewski** [comment]
This landed recently. But is not documented :-/ (but there's an open issue for the docs)
