### ISSUE TITLE
Error reading from remote file in fruit stand example

### ISSUE THREAD

**Issue by bhueth** [pachyderm/pachyderm#947]
pachctl create-pipeline https://.../fruit_stand/pipeline.json
http: read on closed response body

pachtl list-job
ID
[NOTHING]

pachctl create-pipeline -f pipeline.json
pachctl list-job

ID
fdeb21f51566ff7581d2912d0a5eb25f   
67c30d70ba9d2179aa133255f5dc81db

**Comment by jdoliner** [comment]
Hi @bhueth sorry you ran into this. I've reproduced it locally and we should have a fix a ready soon.
