### ISSUE TITLE
Unreported permissions problem creating pipeline in fruit stand example

### ISSUE THREAD

**Issue by bhueth** [pachyderm/pachyderm#948]
pachctl list-job
ID 
59585d4d85bc6ad70d3fe6369db9b13f  
67c30d70ba9d2179aa133255f5dc81db   

pachctl get-logs 59585d4d85bc6ad70d3fe6369db9b13f

0 | 2016-10-06T08:21:39Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{}}}},"name":"prev","err":"operation not permitted"}
0 | cat: /pfs/prev/apple: Operation not permitted
0 | 2016-10-06T08:21:39Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{}}}},"name":"prev","err":"operation not permitted"}
0 | cat: /pfs/prev/orange: Operation not permitted
0 | 2016-10-06T08:21:39Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{}}}},"name":"prev","err":"operation not permitted"}
0 | cat: /pfs/prev/banana: Operation not permitted

**Comment by jdoliner** [comment]
Hi @bhueth this actually looks like it might be correct behavior. The fruit stand job reads from `/pfs/prev` to try to find the old value of the pipeline, if this is the first run of the pipeline then `/pfs/prev` won't exist and it'll get an error which is what you're seeing here. However it handles this error by using `0` in that case since it's performing a sum. The result is you'll see this error in the logs but the job shouldn't fail because of this. Are you seeing a failing status for the job?

**Comment by bhueth** [comment]
I think so? Here's what I see:

pachctl create-repo data
pachctl put-file data master sales -c -f set1.txt
pachctl create-pipeline -f pipeline.json

pachctl list-job
ID                                 OUTPUT                                    
5eebd488fbd96dee3dc4d746a879b14c   sum/2a5de2d05f0c41b9abccee30cd6b4aaa/0    
67c30d70ba9d2179aa133255f5dc81db   filter/0fc94f46efb4401090ea09c22c948fca/0

pachctl list-repo
NAME                CREATED              SIZE
data                About a minute ago   874 B
filter              22 seconds ago       400 B
sum                 22 seconds ago       24 B

pachctl get-file sum sum/2a5de2d05f0c41b9abccee30cd6b4aaa/0 apple
commit sum/2a5de2d05f0c41b9abccee30cd6b4aaa/0 not found in repo sum

**Comment by JoeyZwicker** [comment]
Ah, I see the problem. The command should be `pachctl get-file sum
2a5de2d05f0c41b9abccee30cd6b4aaa/0 apple`. `get-file` takes the arguments
<repo> <commitID> <file>. Sum is the repo name and
2a5de2d05f0c41b9abccee30cd6b4aaa/0 is the commit ID. I can definitely see
how that's confusing so we can change the headers there to make that
clearer.

does `pachctl get-file sum 2a5de2d05f0c41b9abccee30cd6b4aaa/0 apple` return
correctly?

**Comment by bhueth** [comment]
Sure does. Thanks.

**Comment by derekchiang** [comment]
I believe this issue has been fixed.  [This line](https://github.com/pachyderm/pachyderm/blob/master/doc/examples/fruit_stand/pipeline.json#L34) ignores `/prev` if it doesn't exist.
