### ISSUE TITLE
Update Node List error message

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#955]
Reported by a user in slack:

```
Hi guys! Quick question. I've just got access to a kubernetes cluster in my research lab, and I'm trying to deploy a Pachyderm pipeline. The pipeline i stuck in a "restarting" state and prints "Recent Error: Unable to retrieve node list from k8s to determine parallelism" when I inspect it. Running `kubectl get nodes` also throws the error "the server does not allow access to the requested resource (get nodes)". Any suggestion on how to fix? Thanks!
```

We should test namespacing rules and priveliges to see if we can reproduce. If we can't we can at least update our error message to be more descriptive.

**Comment by fjukstad** [comment]
Hi,

After setting the `parallelism_spec` to constant the problem moved on to the pipeline running, but jobs failing with the error message: 
```
the server does not allow access to the requested resource (get pods)
```

This error was caused by the pachyderm serviceaccount no having permission to get pods within the namespace I was using. We updated the permissions on the service account and the pipelines are now running as they should.

**Comment by sjezewski** [comment]
Great! I'm glad you got a workaround.

So to make this clearer next time this happens, we want to:

- report a clearer error message
- create a startup suite that issues any requests pachd might make to the k8s client
- so that if we don't have access, we fail on startup

**Comment by sjezewski** [comment]
stale

**Comment by danielefranceschi** [comment]
Encountered the same problem, IMO this issue should be reopened.

**Comment by JoeyZwicker** [comment]
@danielefranceschi Can you outline in more detail what you're seeing here since this issue is 3 years old?

**Comment by danielefranceschi** [comment]
@JoeyZwicker sorry, I exceeded in issue deduplication: the RBAC-related error message is the same but actually I encountered the `parallelism.coefficient` issue.
