### ISSUE TITLE
docs updates

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#958]
parallelism spec 
get rid of /prev (when it's merged and update for appropriate version)
reorganize reference docs (PFS, PPS, FAQ)
Add readme's for each directory the point people to RTD
update instances of v1.2.0 to v1.2.1
remove bad benchmark - already outdated

**Comment by jdoliner** [comment]
@JoeyZwicker don't get rid of /prev while the behavior is still present in master. We're trying to get in the habit of updating docs as patches that change behavior are merged in so you shouldn't have to worry about that one. Whoever removes /prev will update the docs too.

**Comment by JoeyZwicker** [comment]
I didn't actually check yet to see if the /prev PR landed and what release it's under, 1.2.1 or 1.2.2(e.g. HEAD right now, or not at all yet), but I won't change the docs until it is. It's on this list as something to check on.

**Comment by dwhitena** [comment]
Now being tracked here: https://github.com/pachyderm/pachyderm/issues/1869
