### ISSUE TITLE
Azure Support

### ISSUE THREAD

**Issue by jpoon** [pachyderm/pachyderm#960]
Hi! 👋  I'd like to help in adding support for running pachyderm on Microsoft Azure ☁️ . From my understanding, in addition to deploying a standard k8s cluster, what will be needed is:

- [x] [data disk for rethinkdb](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go)
- [x] azure storage implementation similar to that of [google](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/obj/google_client.go)
- [x] pachctl command line arguments updates
- [x] doc updates
- [ ] data disk for etcd, should be identical to the situation for rethink
- [x] make target for easily spinning up the cluster, similar to make amazon-cluster

Let me know if I'm missing anything else, and how best to go about adding this support. Thanks.

--

Updated above list to reflect the new comments below.

**Comment by JoeyZwicker** [comment]
Hey @jpoon! This would be great and we're here to help! I think that basically covers it!

**Comment by jdoliner** [comment]
Really excited to finally get Azure support :)

Two very minor additions:

- [ ] data disk for etcd, should be identical to the situation for rethink
- [ ] make target for easily spinning up the cluster, similar to `make amazon-cluster`

**Comment by jdoliner** [comment]
In terms of how best to go about adding this support, I'd start with the storage driver. That's probably the most interesting bit. From there we should be able to get something up and running to test and start building to other parts.

**Comment by jpoon** [comment]
> data disk for etcd, should be identical to the situation for rethink

is this separate of the etcd cluster needed for kubernetes?

**Comment by jdoliner** [comment]
Yes, Pachyderm currently uses etcd and rethink for different things because they have different consistency models. Unfortunately k8s won't give applications access to the internal etcd cluster because it would be a potential security hole.
We're working on getting rid of etcd but currently we still need it.

**Comment by jpoon** [comment]
How do I deploy my modified `pachd` image to my k8s cluster? 

I tried:
1. `make docker-build` to build the necessary docker images on my local dev machine
2. `pachctl deploy microsoft (... and some other flags I added to the cmd line ...) --dev` which makes it use a `pachyderm/pachd:local` image

But the pods fail to pull said image. Do I need to setup my own docker registry?

**Comment by jdoliner** [comment]
Yup registry is needed.
Steps needed to get it working would be:

```
docker tag pachyderm/pachd:local jpoon/pachd:local
docker push jpoon/pachd:local
pachctl deploy microsoft --dry-run --dev | sed 's/pachyderm\/pachd/jpoon/pachd' | kubectl create -f -
```
Sorry that's a bit awkward.

**Comment by jpoon** [comment]
My code changes to add Azure storage support worked on the first try which makes me suspicious. Are there automated tests I can run against my deployment?

**Comment by jdoliner** [comment]
Yes, you can run them with `go test ./src/server`.
They can be a bit flaky if you try to run them all at once so you may want to play with how much parallelism the tests have.

**Comment by jpoon** [comment]
With https://github.com/pachyderm/pachyderm/pull/974, that should be the last of it. Looking at the kubernetes manifest, the etcd services are using a hostpath volume so no further changes are needed there.

**Comment by jpoon** [comment]
Closed with https://github.com/pachyderm/pachyderm/pull/974

**Comment by jpoon** [comment]
@jdoliner Awesome possum. When should we expect the next patch release? As mentioned on the email, it'd be great to have one with these bits prior to Nov. 7 so no rush.

**Comment by jdoliner** [comment]
Awesome possum indeed :). Should have the release out early next week.
