### ISSUE TITLE
Bug in put-file

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#961]
Not sure if this usage is as intended, but when I do:

``` shell
echo 'foo' | pachctl put-file foo master -c /blah -f -
```

It succeeds, but I see no commits on repo `foo`.

**Comment by sjezewski** [comment]
Oh weird ... it seems like the commits were created, but were archived? I noticed this when trying to do this operation manually, and getting back commit id `master/7`:

```shell
$pachctl start-commit foo master
master/7
$pachctl list-commit foo -a
BRANCH              REPO/ID             PARENT              STARTED             FINISHED            SIZE                
master              foo/master/0        <none>              6 minutes ago       6 minutes ago       0 B                 
master              foo/master/1        master/0            5 minutes ago       5 minutes ago       0 B                 
master              foo/master/2        master/1            5 minutes ago       5 minutes ago       0 B                 
master              foo/master/3        master/2            3 minutes ago       3 minutes ago       4 B                 
master              foo/master/4        master/3            2 minutes ago       2 minutes ago       4 B                 
master              foo/master/5        master/4            2 minutes ago       2 minutes ago       4 B                 
master              foo/master/6        master/5            2 minutes ago       2 minutes ago       4 B                 
master              foo/master/7        master/6            10 seconds ago                          0 B                 
$pachctl list-commit foo 
BRANCH              REPO/ID             PARENT              STARTED             FINISHED            SIZE                
master              foo/master/7        master/6            25 seconds ago                          0 B   
```

**Comment by sjezewski** [comment]
Running with versions:

```shell
$pachctl version
COMPONENT           VERSION                                          
pachctl             1.2.1-a8a6a98f4cb074014ebce6d2cdb03877bc398a92   
pachd               1.2.1-a8a6a98f4cb074014ebce6d2cdb03877bc398a92   
```

**Comment by sjezewski** [comment]
Hmmm if I blow away the repo, and run the command it works:

```shell
$echo 'foo' | pachctl put-file foo master -c /blah -f -
$pachctl list-commit foo 
BRANCH              REPO/ID             PARENT              STARTED             FINISHED            SIZE                
master              foo/master/0        <none>              1 seconds ago       1 seconds ago       4 B  
```

But I was fiddling w that putfile command. If I blow foo away again and use one of my malformed ones, we see the error:

```shell
$echo 'foo' | pachctl put-file foo master -c -f blah -
open blah: no such file or directory
dag:1$pachctl list-commit foo
BRANCH              REPO/ID             PARENT              STARTED             FINISHED            SIZE                
dag:0$pachctl list-commit foo -a
BRANCH              REPO/ID             PARENT              STARTED             FINISHED            SIZE                
master              foo/master/0        <none>              10 seconds ago      10 seconds ago      0 B   
```

**Comment by sjezewski** [comment]
So ... while it makes sense that if an individual put file fails the commit that was created will be finished and archived ... in the broader flow (a user such as myself trying to get the putfile command working) this can be confusing ... because the 'parent' commits on master will be archived ... and so my commit will also be archived.

**Comment by jdoliner** [comment]
I can't think of why these commits would be archived. Are you sure they're getting archived and not cancelled?

**Comment by sjezewski** [comment]
You're correct, they're cancelled.

To summarize:

- If a user incorrectly does a `PutFile()` it can create a cancelled commit
- If a user then does a correct `PutFile()` w the branch shorthand, it'll create a commit whose parent is cancelled
- So the commit won't show up with a normal `ListFile`

We agree this behavior is confusing, but this behaves as expected w the current implementation. Soon we may remove the idea of 'cancelled commit's and this issue will go away.

**Comment by derekchiang** [comment]
This is actually a huge problem.  Just ran into a user that used `put-file` in correctly:

```
pachctl put-file -r fish master -c focusnoise -f /path/to/a/directory
```

which didn't work because -f doesn't accept a directory.  However, unbeknownst to the user, a commit was created and cancelled.  The user then tried a few correct `put-file` calls, but those resulted in cancelled commits as well, since the first commit was cancelled.

We should fix `pachctl put-file` so that if the usage is incorrectly, no commit is created.

**Comment by JoeyZwicker** [comment]
@jdoliner After seeing this issue I immediately realized this is what broke our live demo today. I had moved files around since the Strata demo so my first put-file request couldn't find what it was looking for a created a cancelled commit. Even though my other requests were correct, it wouldn't show up. List-repo also showed that there was data from later correct commits even though they were cancelled. 

Damn -- I should have just tried deleting the repo and doing put-file again, but that's why live demo demons suck. Bummer.

**Comment by msteffen** [comment]
related: https://github.com/pachyderm/pachyderm/issues/847. Ideally, if a commit is cancelled, child commits also don't become invisible to ListCommit

**Comment by JoeyZwicker** [comment]
This is still a problem that still bites people. 

After thinking/talking about this more, it seems like put-file just isn't a good place to be using cancelled commits. If a put-file fails, keep that commit around isn't useful and we should basically just delete it. We don't have commit deletion yet. 

This also has the implication right now that a single bad put-file request can effectively "kill" a whole branch by making everything else downstream cancelled as well (as Matt said above).
