### ISSUE TITLE
1.2.2 pachd image missing

### ISSUE THREAD

**Issue by jpoon** [pachyderm/pachyderm#967]
Deployments with the new version of [pachctl](https://github.com/pachyderm/homebrew-tap/blob/master/pachctl.rb) fail as the 1.2.2 pachd image is missing from docker hub.

**Comment by jdoliner** [comment]
@msteffen did you get a chance to push the image?

**Comment by msteffen** [comment]
Sorry about this, we're still working out some kinks in our release process. It should be available now, though!
