### ISSUE TITLE
Make sure pachctl fork-commit documentation is clear enough

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#980]
This came up in https://github.com/pachyderm/pachyderm/pull/964
It was unclear at the time what the difference between fork and branch were. I couldn't resolve it in the CL because I don't myself know the difference (I was just regenerating the docs) but we should make sure it's clear to users.

**Comment by derekchiang** [comment]
`fork-commit` is branching.  What's unclear about the current documentation?

**Comment by dwhitena** [comment]
Not in the API anymore, correct?  Closing.
