### ISSUE TITLE
Think about supporting reflinking

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#982]
This would allow efficient 'copy on write' usage.

In particular this would efficiently support the following use cases:

a) A 'filter' step that is just copying files that match the data you want to process in the next step

b) Debugging some data ... by copying some (subset) from an existing repo to another repo to debug

**Comment by jdoliner** [comment]
Let's close this in favor of #573. Reflinking, move and rename will all be fairly similar under the hood I think. At least enough so that the same person implementing them all together makes sense. I updated that issue to reflect that reflink support should be added as part of it.
