### ISSUE TITLE
Concurrency bug in put-file / finish-commit

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#983]
This needs to be triaged and reproduced, but based on discussion we think is a valid bug in theory

a) Initiate a long running `PutFile()` request that is streaming data to an open commit
b) call `FinishCommit()` while the `PutFile()` request is still streaming

The commit will be finished, but the diffs that are associated w the commit are in an undefined state. If the `PutFile()` completes, its probably as the user intended. If the `PutFile()` fails, the commit is finished, but there is data 'missing'.

**Comment by derekchiang** [comment]
Another problem is that `FinishCommit` computes the size of the commit.  So if there's an ongoing `PutFile` while `FinishCommit` runs, the commit can end up with an incorrect size.

**Comment by sjezewski** [comment]
PPS only finishes a commit after all pods have finished, which means they have also finished any `put-file`s, so the only way to trigger this is as a user doing 'manual' `put-file`s.

So we think this is an edge case, and we can de-prioritize.

**Comment by gabrielgrant** [comment]
Is this actually still an issue? There have been some big model changes and a lot of refactoring since this was opened

**Comment by jdoliner** [comment]
I'm pretty sure this is not still an issue. It was always theoretical but we've added a lot more safe guards to put-file since then. Feel free to reopen if you find a way to reproduce this.
