### ISSUE TITLE
Make logs easy for users

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#989]
We don't want logs to become a stumbling block for user's trying to evaluate the software. We've seen a few people w AWS (in particular) run w the default cluster only to have logs fill up their disks and cause problems.

So, this is a beacon issue to make sure we make this as easy as possible.

Some ideas we have:

1) Instructions / configuration scripts for enabling logging w vendor toolchains (e.g. GCP cloud logging, AWS ???)

This depends on the availability of these tools (I'm not familiar w the AWS version for instance) and the amount we can configure them on behalf of our users. Or if we can't configure them, we can at least document how to enable these services.

There is some concern that not all providers will have this tooling.

2) Optionally provide our own logging service module (as part of our k8s manifest) to spin up a logging service that is cloud provider independent

This would have the advantage that it would be provider agnostic. However, the logs do need to get stored somewhere, so we'd probably want to make sure they're in a RRD or something.

The downside to this is that we don't want to be in the business of maintaining / debugging / scaling logging services.

3) Tactical improvements for users to control the size of the logs
#987
#988

**Comment by jdoliner** [comment]
We now have our logging module which can be spun up with `make logging` in our repo.
It deploys a number of manifests to whatever kubernetes cluster it finds with kubectl, adding this into `pachctl` would make things even easier for users since they wouldn't have to clone our repo to get the stack.

**Comment by sjezewski** [comment]
Additionally, we discussed how the UI would consume logs either via the `pachctl get-logs` API or a logging service.

**Comment by sjezewski** [comment]
stale
