### ISSUE TITLE
Error handling and recovery for PPS

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#990]
Errors/failures in PPS can be broadly classified into three categories:
1. Buggy code: there's something wrong with your code and you would like to update it
2. Erroneous data: you committed erroneous data and you would like to remove/update it.
3. Internal failures: everything else.  Examples: 
   - Transient failures (e.g. the pipeline is a web scraper and the pod lost internet connection briefly)
   - Pod crashing (e.g. due to bug in job-shim)
   - Node crashing
   - Pods lost connection with PPS
   - K8S internal errors

The current state is this:
1. We have a good way of recovering from buggy code.
2. We don't have a good way of recovering from erroneous data.
3. We are working on a way to recover from internal failures.

Following is a summary of how we currently handle each kind of errors:
## Buggy code

`pachctl update-pipeline` lets you use a new container with a pipeline.

If you want to reprocess all input commits using the new pipeline, use `pachctl update-pipeline`.

If you only want to process new input commits, use `pachctl update-pipeline --no-archive`.
## Erroneous data

Currently the only thing you can do is to replay (`pachctl replay-commit`) all commits up until the erroneous commit onto another branch.  Then you forget about the old branch and commit new input data onto the new branch.

This is very much less than ideal because:
1. The original erroneous branch still exists, and maybe you would really like to use that branch name.
2. The pipeline needs to reprocess all input commits all over again.

There are currently two proposals for handling erroneous data:
- Implement `delete-commit`.  Then the user would simply use `delete-commit` to delete the erroneous input commit.  However, PPS needs to be smart enough to delete the corresponding output commits as well.  Or maybe `delete-commit` can accept a flag that would also delete all commits that have the given commit as provenance.
- Make it possible to "revert" a commit, similar to `git revert`.  However, it's unclear how we should expose the revert commit to a job.
## Internal failures

I'm currently working on a PR that makes it so that PPS automatically reschedules failed pods for up to a certain number of times before giving up.  The user will have access to information such as:
1. How many times a pod has restarted.
2. The logs of all pods that have ever been launched, including failed pods.
3. The output of all pods that have ever been launched, including failed pods.

**Comment by dwhitena** [comment]
@derekchiang This is awesome.  A few questions:

- How does one know they committed "erroneous data"?  Just by the pipeline failing or by obtaining unexpected results?  Would it be nice to have some sort of `head` functionality to observe samples of the commits in/out of pipelines?  Something less than `git-file` and more than `list-commit`.
- Is it true that `pachctl update-pipeline --no-archive` updates the pipeline images and waits for new commits of data?  This combined with `pachctl update-pipeline` address many of my workflow issues.

**Comment by derekchiang** [comment]
@dwhitena 

* I'm imagining that a user would look at the logs from their failed container (e.g. an error message like `error parsing JSON object`) and realize that there's something wrong with the data.  Could you elaborate a bit on how this `head` functionality would work?  What does this offer over `pachctl list-file` and `pachctl get-file`?
* I think so.  Also I think it's actually `pachctl update-pipeline --archive=false`

**Comment by dwhitena** [comment]
@derekchiang I think this is already enabled to some extent, because we can mount PFS.  I'm imagining that most data issues have something to do with weird formatting, missing data, mixed up types, etc. that are visible in a quick look at the data (e.g., via `head`).  And I'm imagining the case of tabular data more so than JSON data (which is so common in data science).

`get-file` is nice, but pumps out the entire contents right?  It might be nice to look at only some of a file (just to get an idea about how it looks).  However, I guess we don't have to reinvent the wheel, as long as we can do unix-like stuff on the mounted files.

**Comment by derekchiang** [comment]
@dwhitena copying your comment regarding `head` here so we don't forget:

"...in many cases there are patterns in the data that are visible very quickly by looking at the head (e.g., missing columns, bad formatting, etc.). I think these types of issues are most common. Moreover, this gives a lot of context in terms of an eventual UI, even for successful jobs. If a user can have a quick understanding of what data in coming in and out (without having to look at entire files) alongside indications of job status and logs, that could go a long way to increase confidence. I think this is probably covered by functionality that already exists (because we could just mount pfs and head the files). I'm just try to think about what I look at when debugging data science workflows. I like to see a bit of the data, the logs, and the output. Most all debugging is taken care of if I have quick access to this."

**Comment by derekchiang** [comment]
Update: #1022 has added a retry mechanism to PPS that improves its resilience to internal failures.  Now the only failure case that's still not well handled is that of erroneous data.

**Comment by sjezewski** [comment]
@derekchiang -- can you update this issue in light of 1.4?

**Comment by derekchiang** [comment]
We can close this issue now since we have an answer for all three forms of failures:

* Erroneous code: `pachctl update-pipeline`
* Erroneous data: just make a new commit that fixes the data.  This is now possible in 1.4 because we are able to process data modifications/deletions correctly.
* Internal failures: we are working on improving our handling of internal failures and there are many other more specific issues for that.
