### ISSUE TITLE
Add --registry and --version to pachctl deploy, so users can control which images are deployed

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#992]

**Comment by jdoliner** [comment]
It might make more sense to add a `--version` and `--registry` flags instead so you would do

```
pachctl deploy --version :v1.1-<commit-id> --registry my_registry/jdoliner
```

And it would deploy `my_registry/jdoliner/pachd:v1.1-<commit-id>` and `my_registry/jdoliner/job-shim:v1.1-<commit-id>`. It seems like those are the only pieces of information users are going to want to modify so this would let them do what they want but would decrease the risk of deploying mismatched `job-shim` and `pachd` versions which can lead to weird bugs.

**Comment by jdoliner** [comment]
So one problem I just realized is that `--registry` already controls whether or not a registry gets deployed so we're going to need to use a different name for one of those. Maybe the other one could be called `--cluster-registry`.

**Comment by JonathanFraser** [comment]
I think it makes more sense (and be more inline with existing tooling) if the image is passed as an opaque string.

**Comment by sjezewski** [comment]
stale
