### ISSUE TITLE
Potential Fuse driver memory leak

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#996]
Symptom:

Running minikube locally for opencv demo. After mounting pachctl, it starts to steadily consume more memory over repeated run of the demo. Even after killing minikube, pachctl continue to hold on the memory (@msteffen helped me figure out that is was the fuse mount) and it went away after unmounting. 

Collected some data points by reproducing a few times. Wanted to offer as much info as possible to help you track down the issue. Sorry if some of this info isn't useful as I don't have a good sense for which actions turn into FUSE calls so I'm just writing down a bunch of random things I tried.

- Started with a clean minikube cluster and mount, after a single `create-repo` call, memory usage was 139MB (and slowly climbing at ~1MB/min with no other activity). 
-`put-file` requests didn't create a meaningful spike, but accessing the files through the mount (browser) did. ~20-30MB per file access (the files themselves are <100KB). Although this behavior wasn't consistent. 
- creating/running a pipeline over dozens of images didn't create a meaningful memory spike
- creating more repos creates an additional uptick as does accessing commits in those repos
- after about 10 mins of creating/deleting repos and adding a few small commits, total memory usage was above 400MB.
-unmounting and remounting FUSE when it was taking up 400MB of memory brought it back down to ~140MB again. 

Hope all of this is helpful. Happy to test other things if you have trouble reproducing.

**Comment by jdoliner** [comment]
Confirmed that this is indeed an issue. Thanks for a nice descriptive report @JoeyZwicker. 
The cuplrit here is the auto reconnect functionality, it was deferring a method to cleanup some things, however the function it's in never returns until the an unmount happens, so memory would build up while the mount was active.
#1003 fixes the issue.

I also noticed while debugging that our cpu usage for a mount was pretty high, this was the same code it was doing its retries if a very tight loop. I made that loop only run every 5 seconds which fixed the problem. That's in the same pr.

**Comment by jdoliner** [comment]
Fixed via #1003.
